const UData = [
  {
    colleges: [
      "U C A Institute Of Nursing, Chennai - Tamil Nadu",
      "U N Mehta Arts College - Gujarat",
      "U R College - Bihar",
      "U S P COLLEGE OF EDUCATION - Tamil Nadu",
      "U. V. Patel Engineering College, Mehsana - Gujarat",
      "U.B.K.W.T.D. Pharmacy College, Aurangabad - Maharashtra",
      "U.C.A. College of Physiotherapy, Chennai - Tamil Nadu",
      "U.C.A. INSTITUTE OF TEACHER TRAINING - Tamil Nadu",
      "U.G. Smuruti Mahavidyalaya - Orissa",
      "U.N.S. College - Orissa",
      "U.P. Institute for the Hearing Handicapped, Allahabad - Uttar Pradesh",
      "U.P. Rajarshi Tandon Open University - Uttar Pradesh",
      "U.P. Rural Institute of Medical Sciences & Research, Etawah - Uttar Pradesh",
      "U.P. Rural Institute of Medical Sciences Research, Etawah - Uttar Pradesh",
      "U.S.P. Polytechnic College - Tamil Nadu",
      "U.V.K. Gautham College of Pharmacy, Bangalore - Karnataka",
      "Udai Institute of Management Studies - Rajasthan",
      "Udai Pratap College - Uttar Pradesh",
      "UDAI PRATAP COLLEGE - Uttar Pradesh",
      "Udaipur College Of Nursing, Udaipur - Rajasthan",
      "Udaipur Institute Of Nursing, Udaipur - Rajasthan",
      "Udaipur Institute Of Nursing, Udaipur - Rajasthan",
      "Udaipur Post Basic Nursing College, Udaipur - Rajasthan",
      "Udala College - Orissa",
      "Udalguri College, Darrang - Assam",
      "UDASINACHARYA JAGAT GURU SHREE CHAND JI MAHAVIDYALAYA - Uttar Pradesh",
      "Uday Degree College, Vizianagaram - Andhra Pradesh",
      "UDAYA COLLEGE OF EDUCATION - Tamil Nadu",
      "Udaya Polytechnic College, Tiruvallur - Tamil Nadu",
      "Udaya Polytechnic College, Kanyakumari - Tamil Nadu",
      "Udaya School of Engineering, KANYAKUMARI - Tamil Nadu",
      "Udayanath College Of Science & Technology - Orissa",
      "Udayanath College of Science & Technology - Orissa",
      "Udhayam Polytechnic College - Tamil Nadu",
      "Udit Narain Degree College - Uttar Pradesh",
      "Udit Narain Rishav Mahavidyalaya - Uttar Pradesh",
      "UDUPI COLLEGE OF EDUCATION - Karnataka",
      "Udupi College Of Nursing , Udupi, UDUPI - Karnataka",
      "Udupi Dhanvanthari College Of Nursing ,Udupi, UDUPI - Karnataka",
      "Udyog College of Education - West Bengal",
      "UEI Global Education - Delhi",
      "Uhuberia College - West Bengal",
      "Ujani Majuli Kherkatia College - Assam",
      "UJAS TEACHER TRAINING COLLEGE - Rajasthan",
      "Ujjain Engineering College, UJJAIN - Madhya Pradesh",
      "Ujwal Gramin Mahavidyalaya - Maharashtra",
      "UJWAL VIDYA SAMSTE(R) GURUNARAYAN D.ED COLLEGE - Karnataka",
      "Ujwala Degree College, NALGONDA - Andhra Pradesh",
      "UKA Tarsadia University - Gujarat",
      "Uklana Polytechnic & Engineering College - Haryana",
      "ULTRA College of Engineering and Technology for Women - Tamil Nadu",
      "Ultra College of Pharmacy , Thasildar Nagar, MADURAI - Tamil Nadu",
      "Uluberia College - West Bengal",
      "Uma Arts Nathiba Commerce Mahila College - Gujarat",
      "Uma Charan Pattnaik Engineering School , Berhampur - Orissa",
      "UMA Educational and Technical Society, KAKINADA - Andhra Pradesh",
      "Uma Institute Of Nursing Education,Sangli, SANGLI - Maharashtra",
      "Uma Maheswara School Of Nursing , Raichur, RAICHUR - Karnataka",
      "Uma Nath Singh Vidhi Mahavidyalaya, BAREILLY - Uttar Pradesh",
      "UMA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "UMA SHIV MEMORIAL TEACHER TRAINING COLLEGE, Rajasthan",
      "Umaid Hospital, School Of Nursing, Jodhpur, Rajasthan",
      "Umalok Health Worker Training Centre, Meerut, Uttar Pradesh",
      "UMAMAHESWARANAR COLLEGE OF EDUCATION, Tamil Nadu",
      "Umang Red Cross Institute of Special Education, Punjab",
      "UMER BIN KHATTAB WELFARE TRUST, Maharashtra",
      "Umesh Chandra College, West Bengal",
      "UMIYA KANYA SHIKSHA MAHAVIDHYALAYA, Madhya Pradesh",
      "UMRED SHIKSHAN MAHAVIDYALAYA, Maharashtra",
      "Umrer College of Engineering, Maharashtra",
      "Umrer Polytechnic, Maharashtra",
      "Umshyrpi College, Meghalaya",
      "Uni Trust Surajba Mahila Arts College, Gujarat",
      "Union Christian College, Karnataka",
      "Union Christian College, Alwaye, Kerala",
      "Union Christian College, Barapani, Meghalaya",
      "Union Christian Training College, West Bengal",
      "Union Christian Training College, Murshidabad, West Bengal",
      "UNION TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Unique College of Law, Moradabad, Uttar Pradesh",
      "Unique Institute Of Management, Uttar Pradesh",
      "Unique Institute of Management, Maharashtra",
      "UNIQUE INSTITUTE OF MANAGEMENT & TECHNOLOGY, Uttar Pradesh",
      "Unique Law College, Ghaziabad, Uttar Pradesh",
      "Unison Law College, Dehradun, Uttaranchal",
      "Unison School of Law, Dehradun, Uttaranchal",
      "United Christian School Of Nursing, Jalandhar, Punjab",
      "United College, Manipur",
      "United College of Engineering & Research, Noida, Uttar Pradesh",
      "United College of Engineering & Research., Allahabad, Uttar Pradesh",
      "United College of Engineering and Research, - Uttar Pradesh",
      "UNITED EDUCATION SOCIETY, - Haryana",
      "UNITED EDUCATION SOCIETY, - Haryana",
      "UNITED INSTITUTE OF MANAGEMENT, - Uttar Pradesh",
      "UNITED INSTITUTE OF MANAGEMENT, ALLAHABAD - Uttar Pradesh",
      "United Institute of Technology, ALLAHABAD - Uttar Pradesh",
      "United Institute Of Technology, COIMBATORE - Tamil Nadu",
      "United Medical Centre, School Of Nursing,Kasaragod - Kerala",
      "United Mission Degree College, - Karnataka",
      "United Missionary Primary Teacher's Training Institute, - West Bengal",
      "UNITED SCHOOL OF BUSINESS MANAGEMENT, - Orissa",
      "United School Of Nursing , Amritsar - Punjab",
      "Unitedworld Institute of Design, - Gujarat",
      "Unitedworld Institute of Design, - Gujarat",
      "Unitedworld School of Business, - Gujarat",
      "Unitedworld School of Law, - Gujarat",
      "Unity Academy Of Education, College Of Nursing ,Mangalore - Karnataka",
      "Unity Academy Of Education, Mangalore - Karnataka",
      "Unity College Of Nursing,Chitradurga - Karnataka",
      "UNITY DEGREE COLLEGE, - Uttar Pradesh",
      "Unity Degree College, - Uttar Pradesh",
      "Unity Hospital p Ltd,Kerala - Kerala",
      "Unity Law College, - Uttar Pradesh",
      "Unity Nursing Institute School Of Nursing , Mangalore - Karnataka",
      "UNITY TEACHERS TRAINING INSTITUTE, - Karnataka",
      "Unity Women College, - Kerala",
      "Univ B D T College Of Engineering, - Karnataka",
      "Universal Business School, - Maharashtra",
      "UNIVERSAL COLLEGE OF EDUCATION, - Uttar Pradesh",
      "UNIVERSAL COLLEGE OF EDUCATION, - Karnataka",
      "UNIVERSAL COLLEGE OF EDUCATION, - Tamil Nadu",
      "Universal College of Engineering and Technology, - Tamil Nadu",
      "Universal College of Management ,Nashik - Maharashtra",
      "Universal College Of Nursing , Bangalore - Karnataka",
      "Universal Institute of Hotel Management, - Rajasthan",
      "Universal Polytechnic College, - Rajasthan",
      "Universal School Of Nursing , Bangalore - Karnataka",
      "UNIVERSAL SOCIETY FOR QUALITY EDUCATION AND RESEARCH, - Maharashtra",
      "UNIVERSAL TEACHER TRAINING COLLEGE, - Rajasthan",
      "UNIVERSAL TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "UNIVERSAL TEACHERS TRAINING CENTRE, - Karnataka",
      "UNIVERSAL TEACHERS TRAINING INSTITUTE, - Haryana",
      "UNIVERSAL TEACHERS TRAINING INSTITUTE, - Karnataka",
      "University B.T. and Evening College, - West Bengal",
      "University B.T. Evening College, - West Bengal",
      "University College, - Kerala",
      "University College, - Haryana",
      "University College, TRIVANDRUM - Kerala",
      "University College, GUNTUR - Andhra Pradesh",
      "University College Arts Science College, WARANGAL - Andhra Pradesh",
      "University College Education Kurushetra, - Haryana",
      "University College for Women, HYDERABAD - Andhra Pradesh",
      "University College Of Education, - Karnataka",
      "UNIVERSITY COLLEGE OF EDUCATION, - Madhya Pradesh",
      "UNIVERSITY COLLEGE OF EDUCATION, - Karnataka",
      "University College of Engineering , Dindigul - Tamil Nadu",
      "University College of Engineering , Ramanathapuram - Tamil Nadu",
      "University College of Engineering Orissa, SAMBALPUR - Orissa",
      "University College of Engineering Osmania, - Andhra Pradesh",
      "University College of Engineering, Ariyalur - Tamil Nadu",
      "University College of Engineering, Nagercoil - Tamil Nadu",
      "University College of Engineering, Tindivanam - Tamil Nadu",
      "University College of Engineering, Villupuram - Tamil Nadu",
      "University College Of Engineering, Arni - Tamil Nadu",
      "University College of Engineering, Kancheepuram - Tamil Nadu",
      "University College of Engineering, Thirukkuvalai - Tamil Nadu",
      "University College Of Fine Arts - Karnataka",
      "University College Of Fine Arts Music - Karnataka",
      "University College of Law, WARANGAL - Andhra Pradesh",
      "University College of Law - Andhra Pradesh",
      "University College of Law, Kurnool - Andhra Pradesh",
      "University College of Law, Osmania University, HYDERABAD - Andhra Pradesh",
      "University College of Medical Sciences & G.T.P Hospital, New Delhi - Delhi",
      "University College of Medicine, Kolkata - West Bengal",
      "University College Of Nursing, Faridkot - Punjab",
      "University College Of Nursing, Jalandhar - Punjab",
      "University College of Pharmaceutical Sciences, WARANGAL - Andhra Pradesh",
      "UNIVERSITY COLLEGE OF PHYSICAL EDUCATION - Karnataka",
      "UNIVERSITY COLLEGE OF PHYSICAL EDUCATION - Karnataka",
      "UNIVERSITY COLLEGE OF PHYSICAL EDUCATION SPORTS - Karnataka",
      "University College Of Sciences Technology - West Bengal",
      "University Commerce College - Rajasthan",
      "University Department Of Chemical Tech - Maharashtra",
      "University Department of Commerce and Business Administration - Bihar",
      "University Departments Of Anna University Of Tech. Tiruchirapalli, Bit Campus - Tamil Nadu",
      "University Evening College - Karnataka",
      "UNIVERSITY INSTITUTE OF COMPUTER SCIENCE AND APPLICATION, JAGDALPUR - Madhya Pradesh",
      "University Institute of Engineering and Technology, CHANDIGARH - Chandigarh",
      "University Institute Of Information Technology - Himachal Pradesh",
      "University Institute of Legal Studies UILS - Punjab",
      "University Institute of Pharmaceutical University, KURUKSHETRA - Haryana",
      "University Institute Of Technology, - Chhattisgarh",
      "University Institute Of Technology, - West Bengal",
      "University Institute of Technology Bhopal, - Madhya Pradesh",
      "University Institute of Technology Madhya Pradesh, - Madhya Pradesh",
      "University Law College, CHINGLEPUT - Tamil Nadu",
      "University Law College, - Orissa",
      "University Law School, VARANASI - Uttar Pradesh",
      "University Maharajas College, - Rajasthan",
      "University Maharanis College, - Rajasthan",
      "University Of Agricultural Sciences, - Karnataka",
      "University Of Agricultural Sciences Banglore, - Karnataka",
      "University Of Allahabad, ALLAHABAD - Uttar Pradesh",
      "University Of Bombay, MUMBAI - Maharashtra",
      "University Of Calicut, - Kerala",
      "UNIVERSITY OF CALICUT, - Kerala",
      "University Of Delhi, DELHI - Delhi",
      "UNIVERSITY OF DELHI, - Delhi",
      "University of Engineering Management, - Rajasthan",
      "University Of Hyderabad, HYDERABAD - Andhra Pradesh",
      "University Of Jammu, JAMMU - Jammu and Kashmir",
      "University Of Kashmir, - Jammu and Kashmir",
      "University Of Kerala, - Kerala",
      "UNIVERSITY OF KERALA, - Kerala",
      "University of Kota, - Rajasthan",
      "University Of Madras, CHENNAI - Tamil Nadu",
      "UNIVERSITY OF MADRAS, - Tamil Nadu",
      "UNIVERSITY OF MUMBAI, - Maharashtra",
      "University of Patanjali, - Uttaranchal",
      "University of Petroleum & Entergy Studies, DEHRADUN - Uttaranchal",
      "University of Petroleum and Energy Studies, - Uttaranchal",
      "University Of Pune, PUNE - Maharashtra",
      "University Of Rajasthan, - Rajasthan",
      "University of Science & Technology, - Meghalaya",
      "University of Technology & Management, - Meghalaya",
      "University Post Graduate College, ADILABAD - Andhra Pradesh",
      "University Post Graduate College, KARIMNAGAR - Andhra Pradesh",
      "University Post Graduate College Warangal, WARANGAL - Andhra Pradesh",
      "University Rajasthan College, - Rajasthan",
      "UNIVERSITY SCHOOL OF EDUCATION, - Delhi",
      "University School of Law and Legal Studies, - Delhi",
      "University Studies In Law, - Rajasthan",
      "University Studies in Law, - Rajasthan",
      "UNIVERSITY TEACHER TRAINING COLLEGE, - Haryana",
      "University Visveshwaraya College Of Engineering, - Karnataka",
      "University VOC College of Engineering, - Tamil Nadu",
      "University18, - Haryana",
      "Unnamalai Institute of Technology, - Tamil Nadu",
      "UP Vastra Prodhogiki Sansthan, - Uttar Pradesh",
      "Upadhi Mahavidyalaya, - Uttar Pradesh",
      "Upasana College Of Nursing , Kollam, KOLLAM - Kerala",
      "Upasana School Of Nursing,Kollam, KOLLAM - Kerala",
      "Upchar College Of Nursing , Jaipur, JAIPUR - Rajasthan",
      "UPDESH ELEMENTRY TEACHER EDUCATIONAL INSTITUTE, - Haryana",
      "Upendra Nath Brahma College, - Assam",
      "Upendra Pai Memorial College, - Karnataka",
      "Upendranath College, - Orissa",
      "Upendranath College, - Orissa",
      "Upleta Municipal Arts And Commerce College, - Gujarat",
      "UPR COLLEGE OF EDUCATION, - Tamil Nadu",
      "Urdu Arts Evening College, Hyderabad - Andhra Pradesh",
      "Urdu Education Board,  - Delhi",
      "Urdu Medium Govt. Primary Teacher's Training Institute,  - West Bengal",
      "Ursuline Primary Teacher Education College,  - Jharkhand",
      "Ursuline Primary Teacher's Education College,  - Jharkhand",
      "Ursuline Women's Teachers Training College,  - Jharkhand",
      "Ursuline Womens Teacher Training College,  - Jharkhand",
      "Urumu Dhanalakshmi College, Trichy - Tamil Nadu",
      "USAMA CHARITABLE TRUST(R),  - Karnataka",
      "USHA EDUCATIONAL INSTITUTE,  - Uttar Pradesh",
      "USHA LATCHUMANAN COLLEGE OF EDUCATION,  - Pondicherry",
      "Usha School Of Nursing , Bidar, Bidar - Karnataka",
      "Usha School Of Nursing , Vijayawada, Vijayawada - Andhra Pradesh",
      "Ushodaya Degree College, Chodavaram - Andhra Pradesh",
      "Ushodaya Mahila Degree College, Rangareddy - Andhra Pradesh",
      "USMR First Grade College,  - Karnataka",
      "UTHANOOR EDUCATION SOCIETY,  - Karnataka",
      "Utikan Kerada Mahabir College,  - Orissa",
      "Utkal Gourav Madhusudan Institute of Technology,  - Orissa",
      "UTKAL Institute of Engineering & Technology,  - Orissa",
      "Utkal Mani Gopabandhu B.Ed. College,  - Orissa",
      "Utkal Sangeet Mahavidyalaya,  - Orissa",
      "Utkal University, Bhubaneswar - Orissa",
      "Utkal University of Culture,  - Orissa",
      "Utkalmani Gopabandhu Institute of Engineering,  - Orissa",
      "Utkalmani Gopabandhu Mahavidyalaya,  - Orissa",
      "Utkalmani Homoeopathy College,  - Orissa",
      "Utkalmani Homoeopathy College,  - Orissa",
      "Utkarsh Apang Prashikshan Sanstha, Aurangabad - Maharashtra",
      "Utkranti Mandal Vidhi Mahavidyalaya at Jarud Tq., Amravati - Maharashtra",
      "Uttam Chand Mali Devi College of Management Science, - Rajasthan",
      "Uttam Devi Mohanlal College of Engineering, - Rajasthan",
      "Uttam Institute of Management studies, - Uttar Pradesh",
      "UTTAMRAO DAHAKE SHIKSHAN MAHAVIDYALAYA, - Maharashtra",
      "Uttamrao Umak Memorial Nursing Training School, Amravati - Maharashtra",
      "Uttar Banga B.P.Ed. College, - West Bengal",
      "Uttar Banga Krishi Vishwavidyalaya , Cooch Behar - West Bengal",
      "Uttar Banga Primary Teacher's Training Institute, - West Bengal",
      "Uttar Banga Womens B.Ed. College, - West Bengal",
      "Uttar North Dinajpur Primary Teacher Training Institute, - West Bengal",
      "UTTAR PRADESH College, - Bihar",
      "UTTAR PRADESH TECHNICAL UNIVERSITY, - Uttar Pradesh",
      "Uttarakhand Ayurved University, - Uttaranchal",
      "Uttarakhand Open University, - Uttaranchal",
      "UTTARAKHAND SANSKRIT UNIVERSITY, - Uttaranchal",
      "Uttarakhand Technical University, - Uttaranchal",
      "Uttaran College of Education, - West Bengal",
      "Uttaranchal Dental College & Medical Research Institute , Uttarakhand - Uttaranchal",
      "Uttaranchal Institute of Business Studies, - Uttaranchal",
      "UTTARANCHAL INSTITUTE OF MANAGEMENT, - Uttaranchal",
      "Uttaranchal Institute of Technology, Dehradun - Uttaranchal",
      "Uttaranchal Sanskrit University, - Uttaranchal",
      "UTTRANCHAL COLLEGE OF EDUCATION, - Uttaranchal",
    ],
  },
];
