const YData = [
  {
    colleges: [
      "Y A Govt College For Women, Chirala - Andhra Pradesh",
      "Y D Mane Institute Of Nursing, Kolhapur - Maharashtra",
      "Y M T School Of Nursing, Mumbai - Maharashtra",
      "Y V Rao Siddhartha College Education, Vijayawada - Andhra Pradesh",
      "Y,S.L. COLLEGE OF EDUCATION, - Uttar Pradesh",
      "Y. Subbi Reddy Memorial College, Cuddapah - Andhra Pradesh",
      "Y.C. Institute Of Science, - Maharashtra",
      "Y.D.D.Government First Grade College, - Karnataka",
      "Y.K. College, - Manipur",
      "Y.K.D Polytechnic, - Karnataka",
      "Y.M.S. DEGREE COLLEGE, - Uttar Pradesh",
      "Y.M.T. COLLEGE OF MANAGEMENT, Mumbai - Maharashtra",
      "Y.P.R. Degree College, - Andhra Pradesh",
      "Y.S.R. & B.S. Degree College, Tadepalligudem - Andhra Pradesh",
      "Yadav Deshmukh V.D. Arts & Commerce College, - Maharashtra",
      "Yadava College, - Tamil Nadu",
      "YADAVA COLLEGE OF EDUCATION, - Tamil Nadu",
      "YADAVRAO TASGAONKAR INSTITUTE OF BUSINESS MANAGEMENT, Raigad - Maharashtra",
      "Yadavrao Tasgaonkar Institute of Engineering, Karjat - Maharashtra",
      "Yadavrao Tasgaonkar Institute of Pharmacy, Raigad - Maharashtra",
      "Yadavrao Tasgaonkar Polytechnic, - Maharashtra",
      "Yadgir Polytechnic, - Karnataka",
      "YADU NATH PAL SINGH COLLEGE, - Uttar Pradesh",
      "Yadunandan College, - Bihar",
      "YADUVANSHI INSTITUTE OF EDUCATION, - Rajasthan",
      "YADUVANSHI INSTITUTE OF EDUCATION, - Haryana",
      "Yaduvanshi Polytechnic, Sohali - Rajasthan",
      "YADUVANSHI TEACHER TRAINING COLLEGE, - Haryana",
      "YADUVANSHI TEACHER TRAINING COLLEGE, - Rajasthan",
      "YADUVANSHI TEACHER TRAINING COLLEGE, - Haryana",
      "YADUVANSI INSTITUTE OF EDUCATION, - Haryana",
      "Yagna Degree College, ARMOOR - Andhra Pradesh",
      "Yagyavalkya Institute of Technology YIT, - Rajasthan",
      "Yalamarthy Institute Of Computer Science, VISAKHAPATNAM - Andhra Pradesh",
      "Yalamarty D.Pharmacy College, Visakhapatnam, VISAKHAPATNAM - Andhra Pradesh",
      "Yalamarty Institute Of Computer Sciences, - Andhra Pradesh",
      "YAMAKANAMARDI VIDYAVARDHAK SANGH, - Karnataka",
      "Yamuna Institute of Engineering & Technology, - Haryana",
      "YAMUNABAI KURHE B.ED COLLEGE, - Maharashtra",
      "YANAM SCHOOL OF EDUCATION, - Pondicherry",
      "Yash Institute Of Nursing,Yavatmal, YAVATMAL - Maharashtra",
      "YASH SHIKSHAN SANSTHA N AND GRAMIN VIKAS SAMITI, - Madhya Pradesh",
      "Yash Special Teacher Training Institute, WASHIM - Maharashtra",
      "YASH TEACHER TRAINING COLLEGE, - Haryana",
      "Yashas College Of Nursing,Bangalore, BANGALORE - Karnataka",
      "Yashawantrao Chavan College, - Maharashtra",
      "Yashawantrao Chavan College, - Maharashtra",
      "Yashoda College Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
      "YASHODA NANDAN HARIBANS MAHAVIDYALAYA, - Uttar Pradesh",
      "YASHODA NANDAN HARIBANS MAHAVIYALAYA, - Uttar Pradesh",
      "YASHODA NANDAN HARIBANSH MAHAVIDYALAYA, - Uttar Pradesh",
      "Yashoda School Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
      "Yashoda Shikshan Prasarak Mandals, SHOLAPUR - Maharashtra",
      "YASHODA TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "Yashodhara Nursing Institute,,Solapur, SHOLAPUR - Maharashtra",
      "YASHOGATHA SHIKSHAN PRASARAK MANDAL, - Maharashtra",
      "Yashraj Institute Of Professional Studies ,Kanpur, KANPUR - Uttar Pradesh",
      "Yashraj Institute Of Professional Studies,Kanpur, KANPUR - Uttar Pradesh",
      "Yashratna College of Special Education Mental Retardation, NAGPUR - Maharashtra",
      "Yashvantrao Chavan College of Pharmacy , AHMEDNAGAR - Maharashtra",
      "Yashvir Memorial Technical Institute - Haryana",
      "YASHWANT JUNIOR COLLEGE OF EDUCATION - Maharashtra",
      "Yashwant Mahavidyalaya - NANDED, Maharashtra",
      "Yashwant Nursing School,Beed - BEED, Maharashtra",
      "Yashwant Nursing School,Latur - LATUR, Maharashtra",
      "Yashwant Rao Chavan Arts & Commerce Mahavidyalaya - Washim, Maharashtra",
      "Yashwant Rao Chavan Arts And Commerce College - Maharashtra",
      "Yashwant Rao Chavan College Of Arts Commerce & Science - Maharashtra",
      "Yashwant Rao Chavan College Of Science - Maharashtra",
      "Yashwant Rao Chavan Law College - KARAD, Maharashtra",
      "Yashwant Rao Chavan Maharashtra Open University - Maharashtra",
      "Yashwant Rao Chavan Mahavidyalaya - Maharashtra",
      "Yashwant Rao Chavan Mahavidyalaya - Osmanabad, Maharashtra",
      "Yashwant Rao Chavan Mahavidyalaya - Kolhapur, Maharashtra",
      "Yashwant Rao Chavan Warana Mahavidyalaya - Maharashtra",
      "YASHWANT RAO MOHITE INSTITUTE OF MANAGEMENT - SATARA, Maharashtra",
      "YASHWANTRAO CHAVAN MARATHWADA OPEN UNIVERSITY - Maharashtra",
      "Yashwantrao Chavan School of Social Work - Maharashtra",
      "Yashwantrao Chavan Shikshan Prasarak Mandal's Dadasaheb DS Patil Arts Comm & Sc College - Maharashtra",
      "Yasin Meo College - Haryana",
      "Yasodha School Of Nursing ,kancheepuram - KANCHIPURAM, Tamil Nadu",
      "Yavatmal Zilla Vikas Samiti Pataldhamal Wadhwani, D. Pharmacy College , YAVATMAL - Maharashtra",
      "YE - BHADUR SINGH MAHAVIDYALAYA - Uttar Pradesh",
      "YELLALING EDUCATION TRUST - Karnataka",
      "Yellamma Dasappa Institute of Technology - BANGALORE, Karnataka",
      "Yenepoya College Of Nursing , Mangalore - MANGALORE, Karnataka",
      "Yenepoya Dental College & Hospital , Mangalore - MANGALORE, Karnataka",
      "Yenepoya Institute Of Nursing Sciences , Mangalore - MANGALORE, Karnataka",
      "Yenepoya Medical College, Mangalore - MANGALORE, Karnataka",
      "Yenepoya Nursing College ,Dakshina Kannada - Karnataka",
      "Yenepoya Nursing College,Mangalore - Karnataka",
      "Yeola Nursing School,nashik - Maharashtra",
      "Yerala Medical Trust & Research Centres Dental College & Hospital , Navi Mumbai - Maharashtra",
      "Yerala School Of Nursing, Mumbai - Maharashtra",
      "Yerneni Venkata Nageswara Rao Govt Degree College - Andhra Pradesh",
      "YESH BAHUUDESHIYA SHIKSHAN SANSTHA - Maharashtra",
      "Yeshwant Mahavidyalaya - Maharashtra",
      "Yeshwant Mahavidyalaya - Maharashtra",
      "Yeshwant Mahavidyalaya - Wardha - Maharashtra",
      "Yeshwantrao Chavan College of Engineering - Nagpur - Maharashtra",
      "Yeshwantrao Chavan College Of Engineering - Maharashtra",
      "Yeshwantrao Chavan College of Engineering - Maharashtra",
      "Yingli College - Nagaland",
      "YMCA COLLEGE OF PHYSI EDUCATION - Karnataka",
      "YMCA COLLEGE OF PHYSICAL EDUCATION - Tamil Nadu",
      "YMCA College of Physical Education - Tamil Nadu",
      "YMCA Institute of Engineering & Technology - Haryana",
      "YMCA University of Science & Technology - Haryana",
      "YMT College of Management - Maharashtra",
      "Yogada Satsangha Palpara Mahavidyalaya - West Bengal",
      "Yogananda Institute of Technology & Science - Andhra Pradesh",
      "Yogeshwari Science Mahavidyalaya - Maharashtra",
      "Yogi Vemana University Kadapa - CUDDAPAH - Andhra Pradesh",
      "Yogiji Maharaj Mahavidyalaya Mahila Arts Commerce College - Gujarat",
      "YOGINATH DEGREE COLLEGE - Uttar Pradesh",
      "Yogiraj Institute of Technology - Rajasthan",
      "Yogita Dental College & Hospital , Ratnagiri - Maharashtra",
      "Yogmani Institute Of Nursing ,Jabalpur - JABALPUR - Madhya Pradesh",
      "Yogoda Satsanga Palpara Mahavidyalaya - West Bengal",
      "Yogwashistha Shikshan Prarak Mandal Polytechnic - Maharashtra",
      "Younus College of Engineering & Technology - KOLLAM - Kerala",
      "Youth School Of Nursing , Anantapur - ANANTAPUR - Andhra Pradesh",
      "YPS MEMORIAL TEACHER TRAINING COLLEGE - Haryana",
      "YSL COLLEGE OF EDUCATION - Uttar Pradesh",
      "YUGANTAR EDUCATION SOCIETY TIRPUDE COLLEGE OF SOCIAL WORK - NAGPUR - Maharashtra",
      "Yugantar Institute of Technology & Management - RAIPUR - Chhattisgarh",
      "YUVA RASHTRA SANT BHAYYUJI MAHARAJ B. ED WOMENS COLLEGE - Maharashtra",
      "YUVA VYAVSAIK SHIKSHAN MAHAVIDYALAYA - Madhya Pradesh",
      "Yuvarajas College - Karnataka",
      "Yuvraj Dutt (PG) College - Uttar Pradesh",
      "Yuvraj Pratap Singh Memorial Homoeopathic Medical College - Rajasthan",
      "Yuvraj Subhaghsinhji Arts And Sri K S Commerce College - Gujarat",
    ],
  },
];
