const data = [
  {
    colleges: [
      "Vif College Of Engineering & Technology",
      "Vrs & Yrn College Of Engineering & Technology",
      "V. R. Siddhartha Engineering College",
      "Vaagdevi Engineering College",
      "Vaagdevi Institute Of Tech & Science",
      "Vallurupalli Nageswara Rao Vignana Jyothi Institute Of Engineering",
      "Vardhaman College Of Engineering",
      "Vasavi College Of Engineering",
      "Vathsalya Institute Of Science & Technology",
      "Vazir Sultan College Of Engineering",
      "Vidya Bharathi Institute Of Technology",
      "Vidya Jyothi Institute Of Technology",
      "Vignan Engineering College",
      "Vignan Institute Of Tech & Science",
      "Vignan Bharathi Institute Of Technology",
      "Vignan's Institute Of Information Technology",
      "Vijay Instt. Of Tech.& Science",
      "Vijaya Rural Engineering College",
      "Viswanandha Institute Of Technology & Management",
      "Vivekananda Institute Of Tech. & Science",
      "Vivekananda Institute Of Engineering And Technology",
      "Vaish College Of Engineering",
      "Vemana Institute Of Technology",
      "Vidyavardhaka College Of Engineering",
      "Vidya Vikas Institute Of Engineering And Technology",
      "Vivekananda College Of Engineering & Technology",
      "Vivekananda Institute Of Technology",
      "Vijayanagara Sri Krishnadevaraya University",
      "Veda Vyasa Institute Of Technology",
      "Vidya Academy Of Science And Technology",
      "Vimal Jyothi Engineering College",
      "Viswajyothi College Of Engineering & Technology",
      "Vishwakarma Institute Of Information Technology",
      "Vjt Institute, Hr Mahajani Marg",
      "Vidarbha Youth Welfare Soc.'s Prof. Ram Meghe Institute Of Technology & Research",
      "Vidya Pratishthan's Institute Of Information Technology",
      "Vidyalankar Institute Of Technology",
      "Vidyavardhini Soc's College Of Engineering & Tech",
      "Vishweshvarya Regional College Of Engineering",
      "Vivekanand Education Society's Institute Of Technology",
      "Vp Muthaiah Pillai Meenakshi Ammal Engineering College For Women",
      "V.r.s. College Of Engineering And Technology",
      "Vsb Engineering College",
      "Valliammai Engineering College",
      "Vel High Tech Sri Rangarajan Sakunthala Engineering College",
      "Vel's Srinivasa College Of Engineering And Technology",
      "Vel Tech",
      "Vellalar College Of Engineering & Technology",
      "Velammal Engineering College",
      "Vellore Institute Of Technology - Vit University",
      "Vickram College Of Engineering",
      "Vinayaka Missions Kirupananda Variyar Engineering College.",
      "Vins Christian College Of Engineering",
      "Vivekanandha College Of Engineering For Women",
      "Vira College Of Engineering",
      "Vishveshwarya Institute Of Engineering & Technology",
      "Vindhya Institute Of Technology & Science Indore",
      "V K V Government Degree College",
      "V R College",
      "V R S Y R N College",
      "V R S Degree College",
      "V S M College",
      "V S R N V R College",
      "V T J M K T R Degree College",
      "V V M Degree College",
      "Vemalpalli Kodanda Ramayya College",
      "Visakha Govt Degree College For Women's",
      "Visvodaya Government College",
      "Vivek Vardhini Afternoon College Arts",
      "Vivek Vardhini College",
      "Vivekannanda Government College",
      "V S J College",
      "Vaishali Mahila College",
      "Vanijya Mahavidyalaya Patna",
      "Vidya Bhawan Mahila Mahavidyalaya",
      "Venkateshwara Institute Computer Science Tech",
      "V.m. Salgaocar College Of Law",
      "V N S B Ltd Arts And Commerce College",
      "V S Patel College Arts Science",
      "V.t. Choksi Sarvajnik Law College",
      "V T Choksi Sarvjanik College Education",
      "Vaidya Shri M M Patel College Education",
      "Vijaynagar Arts College",
      "Vitthalbhai Patel And Rajrathanp T Patel Science College",
      "Vivekanand Arts College",
      "Vivekanand College Commerce",
      "Vivekanand College Education",
      "Vivekanand College Of Law",
      "Vivekanand Vanijya Mahavidyalaya",
      "Vallabh Government College",
      "Vaish Arya Kanya Mahavidyalaya",
      "Vaish College Bhiwani",
      "Vaish College Rohtak",
      "Vaish College Education",
      "Vaish Mahila Mahavidyalya",
      "V B Women College",
      "V.m.s.r. Vastrad Arts Science And Vijanya Mahantosh Commerce Col",
      "V.p.mandals Shri S.r.n. Arts & Sh. Mbs Commerce College",
      "V.p.s.c.s.b.artsshamrp Science And Samitis Commerce College",
      "V.v.ss S.v.m Arts Science & Commerce College",
      "Vaikunta Baliga Law College",
      "Valaballary Channabasaveshwar Education Societys Arts And Commerce College",
      "Vankisannarudrappa Law College",
      "Vasavi Vidyaniketan College For Women",
      "Verrasaiva College",
      "Vidya Vardhak Sanghs Arts And Commerce College",
      "Vidyavardhaka Law College",
      "Vidyavardhaka Sangh First Grade College For Women",
      "Vidyavardhika F.g.college",
      "Vidyodaya College Of Arts And Commerce",
      "Vidyodaya Law College",
      "Vijay College Of Fine Arts",
      "Vijaya College",
      "Vijaya College",
      "Vijaya College",
      "Vijaya First Grade College",
      "Vijayanagar College",
      "Visveswarapura College Of Arts And Commerce",
      "Visveswarpura College Of Science",
      "Visveswarpura Evening College Of Arts & Commerce",
      "Vivekanand College Of Arts Sc. & Commerce",
      "Vivekanand Law College",
      "Vivekananda College Of Education",
      "Vivekananda First Grade Coll. Of Arts Sc. & Comm",
      "Vvss Shri Khasgatesh College Of Arts & Comm",
      "Vellu Thampi Memorial N.s.s. College",
      "Vimla College",
      "V.m.v. Commercej.m.t. Arts And J.g. Patel College Of Science",
      "V.r. College Of Engineering",
      "V.v. Mandals Arts Science And Commerce College",
      "V.w. Sabhas Arts Science & Commerce College",
      "Vanijya Mahavidyalaya",
      "Vasantrao Naik Arts Sc. & Commerce College",
      "Vasantrao Naik Institute Of Arts & Social Sciences",
      "Vasantrao Naik Mahavidyalaya",
      "Veer Wajekar Arts Science & Commerce College",
      "Veermata Jijabai Technical Institute",
      "Venutai Chavan College",
      "Vidarbha Ayurved Mahavidyalaya",
      "Vidarbha Mahavidyalaya",
      "Vidnyan Mahavidyalaya",
      "Vidya Bharathi Mahavidyalaya",
      "Vidya Prasarak Mandals K.g. Joshi Arts & N.g. Bedekar Coll. Of Comm",
      "Vidya Pratishthans Arts Science & Comerce College",
      "Vidya Vikas Mandals Arts And Commerce College",
      "Vijaysinh Mohite Patil Mahavidyalaya",
      "Vinayakrao Patil Mahavidyalaya",
      "Vishawasrao Naik College",
      "Vivekanand Arts & Sardar Dilip Singh Science & Commerce College",
      "V.r. Arts & Commerce College",
      "Vanijya Mahavidyalaya",
      "V.s.s. Medical College - Sambalpur, Orissa",
      "Vedvyas Mahavidyalaya - Sundergarh, Orissa",
      "Vesaja Patel College - Sundergarh, Orissa",
      "Vikram Dev College - Koraput, Orissa",
      "Vyasnagar College - Jajpur, Orissa",
      "Vedic Kanya College - Jaipur, Rajasthan",
      "Vidya Bhawan Gs Teachers Training College - Udaipur, Rajasthan",
      "Vidya Bhawan Rural Institute - Udaipur, Rajasthan",
      "Vinodani College - Jhunjhunu, Rajasthan",
      "V.l.b. Janaki Ammal College Of Arts & Science - Coimbatore, Tamil Nadu",
      "V.o. Chidambaram College - Thoothukudi, Tamil Nadu",
      "V.o.c. College Of Education - Thoothukudi, Tamil Nadu",
      "V.p. Muthaiah Pillai Meenakshi Ammal College For Women - Virudhunagar, Tamil Nadu",
      "V.s. Sivalingam Chettiar Government Arts College - Sivaganga, Tamil Nadu",
      "V.v. Vanniaperumal College For Women - Virudhunagar, Tamil Nadu",
      "Vels College Of Science - Chennai, Tamil Nadu",
      "Vellalar College For Women - Erode, Tamil Nadu",
      "Vidyasagar College Of Arts & Science - Coimbatore, Tamil Nadu",
      "Virudhunagar Hindu Nadars Senthikumara Nadar College - Virudhunagar, Tamil Nadu",
      "Vivekanand College - Kanyakumari, Tamil Nadu",
      "Vivekanand College - Madurai, Tamil Nadu",
      "Voorhees College - Vellore, Tamil Nadu",
      "V.v. College - Muzaffarnagar, Uttar Pradesh",
      "Vallabharam Saligram Mehta College Of Science - Allahabad, Uttar Pradesh",
      "Vardhaman College - Bijnor, Uttar Pradesh",
      "Vasanta Kanya Mahavidyalaya - Varanasi, Uttar Pradesh",
      "Vasantha College For Women - Varanasi, Uttar Pradesh",
      "Veerangna Awanti Bail Mahila Mahavidalaya - Etah, Uttar Pradesh",
      "Viduttma Kanya Mwahavidyalaya - Muzaffarnagar, Uttar Pradesh",
      "Vidya Mandir Degree College - Farrukhabad, Uttar Pradesh",
      "Vidyant Hindu Degree College",
      "Vidyavati Mukand Lal Girls College",
      "Vijay Singh Pathik Rajkiya Mahavidyalaya",
      "Vikram Singh Kanya Mahavidyalaya",
      "Vikramjit Singh Sanatan Dharam (pg) College",
      "Vir Bahadur Singh Degree College",
      "Virangana Awantibai Government Degree College",
      "Vivekanand Gramoudyog M. Degree College",
      "Victoria Institution",
      "Vidyanagar College",
      "Vidyasagar College",
      "Vidyasagar College For Women",
      "Vidyasagar Evening College",
      "Vidyasagar School Of Social Work",
      "Vidyasagar Teachers Training College",
      "Vijaygarh Jyotish Ray College",
      "Vivekanand College",
      "Vivekanand College For Women",
      "Vivekananda College",
      "Vivekananda College",
      "Vivekananda Mahavidyalaya",
      "Vivekananda Mahavidyalaya",
      "Vivekananda Mission Mahavidyalaya",
      "Vivekananda Setavarsiki Mahavidyalaya",
      "Vkk Vijayan Engineering College",
      "Vandayar Polytechnic College",
      "Valliammai Polytechnic College",
      "Valivalam Desikar Polytechnic College",
      "V.s. Vellaichamy Nadar Polytechnic College",
      "V.l.b. Janaki Ammal Polytechnic College",
      "V. Ramakrishna Polytechnic College",
      "Vignesh Polytechnic College",
      "Venkateswara Polytechnic College",
      "Vel Tech Polytechnic College",
      "Vivekananda Polytechnic College",
      "V.h.n.s.n. College",
      "V.n. Krishnasamy Naidu College Of Arts & Science For Women",
      "Vellakoil Arts And Science College",
      "Vel Sri Ranga Sanku College Of Arts And Science",
      "Valliammal College For Women",
      "Vailakanni Malathy Pannicker College Of Arts & Science",
      "Vidhya Sagar Womens College, Chenglepet",
      "Vysya College",
      "Vivekanandha College Of Arts And Science",
      "Vivekananda College, Chennai",
      "Vinayaka Missions Kirupananda Variyar Arts And Science College",
      "Vel R.s. Medical College, College Of Physiotherapy",
      "Vel's College Of Physiotherapy",
      "Vinayaka Mission's College Of Physiotherapy",
      "Velumailu Siddha Medical College",
      "Veer Kunwar Singh University",
      "Veer Narmad South Gujarat University",
      "Visveswaraiah Technological University",
      "Visvesvaraya National Institute Of Technology (vnit), Nagpur",
      "Vikram University",
      "Vidyasagar University",
      "Visvabharati University",
      "Veer Bahadur Singh Purvanchal University",
      "Vardhaman Mahaveer Open University",
      "Vinayaka Missions University",
      "Vinoba Bhave University Hazaribag",
      "Vaageswari College Of Engineering",
      "Vaishnavi Institute Of Technology",
      "Vanjari Seethaiah Memorial Engineering College - Engineering Colleges",
      "Vasireddy Venkatadri Institute Of Technology",
      "Velagapudi Ramakrishna Siddhartha Engineering College",
      "Vivekananda Institute Of Tech & Science Bommakal",
      "Visvesvaraya College Of Engineering Technology",
      "Vidya Vikas Institute Of Technology",
      "Vignan Lara Institute Of Technology & Science",
      "Vijaya Engineering College",
      "Valia Institute Of Technology",
      "Vyavsai Vidya Prathisthan's Sanch College Of Engineering",
      "Vedica Institute Of Technology",
      "Vikrant Institute Of Technology & Management",
      "Vindhya Institute Of Technology & Science, Amoudha",
      "Vindhya Institute Of Technology & Science Neemkheda",
      "Vns Institute Of Technology",
      "Vishwakarma Institute Of Technology, Bibwewadi",
      "Vidya Vikkas College Engineering Technology",
      "Velammal College Of Engineering & Technology",
      "Vr Institute Of Pg Studies",
      "Vaagdevi Degree & Pg College",
      "Vagadevi Institue Of Mgt Studies",
      "Velangini Institute Of Mgt",
      "Velankanni Institute Of Mgt. Studies",
      "Villa Marie Pg College For Women",
      "Visakha Institute Of Professional Studies",
      "Viswa Bharathi P.g.college Of Engineering & Management",
      "Vivekananda Pg Centre",
      "Vivekananda School Of Pg Studies",
      "Vijaya School Of Business Mangement",
      "Vani Niketan Institute Of Management Studies",
      "Vestal Institute Of Mgt. And Information Tech",
      "Vaishali Institute Of Business & Management",
      "Vishwabharati Academy's College Of Engineering",
      "V.m. Patel Institute Of Management",
      "Vaish School Of Business",
      "V.v.s's. Vijayanagar Instt. Of Mgt",
      "Vivekananda Degreee College Of Arts, Commerce & Science",
      "V.v.n. Institute Of Management & Tech & Research",
      "Vidyasagar Institute Of Management",
      "V.n.s. Institute Of Management",
      "Vanashpati Smiriti Siksha Samiti",
      "Vishwakarma Institute Of Management",
      "Vasantraodada Patil Institute Of Management Studies & Research",
      "Viva Institute Of Management Studies",
      "Vyas Institute Of Engineering & Technology",
      "Vidya Bharathi  Institute Of Research & P.g. Studies In Science & Management",
      "V.p.m's Dr. V.n. Bedekar Institute Of Managenet Studies",
      "Vivekanand Education Society Institute Of Management Studies & Research",
      "Vignan Degree College",
      "Vassireddy Sri Laxmi & Meka Rama Krishna (vsl&mrk) Degree College",
      "Vidya Kendram Degree College",
      "Venigalla Jayasri Ram College",
      "Veesam Jayaprada & Dogiparthy Lakshmi Bhagavathi Degree College",
      "Vijaya Jyothi Degree College",
      "Vasavi Degree College For Women",
      "V.k.r. Degree College",
      "Vikas Degree College",
      "Vignan College",
      "Venkata Rama Degree College",
      "Vidyalaya Degree College",
      "Viswabharathi Degree College",
      "Vidyanjali Degree College",
      "Vidyanjali Degree College, Mudinepalli",
      "Vignan Degree College, Kaikalur",
      "Vikas Degree College, Mandavalli",
      "Vikas Degree College, A.kondur",
      "Venkateswara Mahila Degree College",
      "V.s.r & A.m. Degree College",
      "Viveka Arts & Science College",
      "Vivekananda Degree College",
      "Vivekananda Degree College, Tangutur",
      "Vignan Degree College, Chimakurthy",
      "Vidya Jyothi Degree & Pg College",
      "Vignana Bharathi Degree College",
      "Vasavi Degree College",
      "Vikas Degree College, Mahabubabad",
      "Vikas Degree College, Jangaon",
      "Vaasavi Degree College",
      "Vivekavardhini Degree College",
      "Vikas Degree College, Khammam",
      "Vamsee Vinay Degree College",
      "V.k.d.v. Satyanarayana Raju Degree College",
      "Vivekavardhani Degree College For Women",
      "Vivekananada Degree & Pg College",
      "Vani Niketan Degree & Pg College",
      "Vikas Degree College, Sircilla",
      "Vidya Latha Degree College Of Commerce & Business Management",
      "Vivekananda Degree College, Huzurabad",
      "Vodithala Srinivasa Rao Degree College",
      "Vanisri Degree College, Karimnagar",
      "Vaageswari Degree College",
      "Vagdevi Degree College, Vemulawada",
      "Vashishta Degree College",
      "Vivekavardhini Degree College, Mancherial",
      "Vidyarthi Degree College",
      "Vidya Bharathi Degree College, Tandoor",
      "Vagdevi Arts & Science Degree College",
      "Vasundhara Degree College, Adilabad",
      "Vikas Degree College, Jannaram",
      "Vaagdevi Degree College, Adilabad",
      "Vivekanada Degree College",
      "Vagdevi Degree College, Khanapur",
      "Vijaya Nagar College Of Commerce",
      "Viswa Bharathi Degree College",
      "Vidya Dayani College",
      "Vivekananda College",
      "Vidyapeth College",
      "Vandana College",
      "Vidyabharathy Degree College For Women",
      "Vani Degree College For Women",
      "Vijaya College Of Computer Science",
      "Vijetha Degree College",
      "Vivekananada Degree College, Rangareddy",
      "Vidyasagar Degree College",
      "Vijay Karans Degree College",
      "Vivekananda Degree College, Kukatpally",
      "Viswa Bharathi Degree College, Rangareddy",
      "Vasundara Degree College For Women",
      "Vasavi Degree College, Nalgonda",
      "Vijetha Degree College, Nalgonda",
      "Vayuputra Degree College",
      "Vivekavardhani Degree College",
      "Vasu Degree College",
      "Vasistha Degree College",
      "Vaagdevi Degree College",
      "Vijetha Degree College, Nizamabad",
      "Vijay Degree College, Nizamzbad",
      "V.r.k. College Of Computer Science",
      "Viswa Vikas Degree College",
      "Vikas Degree College, Mahabubnagar",
      "V.r.k. Degree College, Mahabubnagar",
      "Vivekananda Degree College, Mahabubnagar",
      "Vijeta Degree College",
      "Vignan Degree College, Sangareddy",
      "Vijaya Sai Degree College",
      "V.m.c. Mahila Vidyapeeth Degree College For Women",
      "V.i.p.s. Degree College",
      "Vidyaarthi Degree College",
      "V.v.r. Kanaka Mahalaxmi Degree College",
      "Vivekananda College, Visakhapatnam",
      "Vidyarthi Degree College, Anakapalli",
      "Vignana Bharathi Mahila Degree Kalasala",
      "V.s. Reddy Rural Degree College",
      "Valangi College, Karapa",
      "V.v.s. Degree College",
      "Vignan Institute Of Science & Arts",
      "V.s. Lakshmi Degree College For Women",
      "V.s.k. Degree College, Bhimavaram",
      "Vijnana Nilayam Degree College",
      "Vikas Degree College, Nidadavolu",
      "Vidwan Degree College, Vizianagaram",
      "Vivekavardhini Bhaskar Degree College",
      "Vagdevi Degree College, Vizianagaram",
      "Vamsadhara Degree College",
      "Vidya Dhari Degree College",
      "Vamsadhara Degree College, Srikakulam",
      "Viswabharathy Degree College, Tirupati",
      "Vignana Sudha Degree College",
      "V.c.r. College, Chittoor",
      "Viswam Degree College, Madanapally",
      "Vijayam Science & Arts Degree College",
      "V.r.n College Of Computer Science Management",
      "V.s.r. Institute Of Computer Education",
      "V.v.r Pg College Of Technology",
      "Vinukonda Pg College",
      "Vagdevi Degree College, Proddatur",
      "Veeravalli Vidya Sundar Pg College",
      "Vikas Degree College, Cuddapah",
      "Vidyasadhana Degree College, Cuddapah",
      "Vidya Dayini College Of Information Tech",
      "Vignan Degree College,guntur",
      "Vijaya Pg College",
      "Vishwa Vishwani Institute Of Systems And Management",
      "Vivekananda School Og Pg Studies",
      "Vivekananda Degree College, Vempalli",
      "V.s.r. & N.v.r. College, Tenali",
      "Vivekananda Institute Of  Information Technology",
      "Viswaganga Institute Of Technology",
      "Vision Institute Of Science And Technology",
      "Vivekananda Degree College, Nellore",
      "Vidyalaya Degree College, Gudur",
      "Vagdevi College Of Science",
      "Vignan Degree College, Podalakur",
      "Vidyanjali College Of Arts & Science",
      "V.s Lakshmi Institute Of Computer Application & Management Studies",
      "V.c.r. Institute Of Computer Science",
      "Vidya Ratna Dr. K.g.a. Gupta Degree College",
      "Vijayawada Nalanda Degree College",
      "Vavilala Degree College, Kurnool",
      "Vaibhav College Of Higher Learining",
      "Vyshnavi Degree College",
      "Vasavi Mahila Kalasala",
      "Vysya Institute Of Management Studies",
      "Vidya School Of Business",
      "V.g.p School Of Management",
      "Vivekananda Institute Of Information Management Studies",
      "Vision School Of Management",
      "Vyas Insititute Of Management",
      "Vardhman Medical College / Chalmeda Anand Rao Institute Of Medical Sciences, Karimnagar",
      "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi",
      "Vivekanand Institute Of Medical Sciences & Research, Valia",
      "V.d. Siddhartha College Of Law",
      "V.r. Law College",
      "Vijay Law College",
      "Vishwanath Bidhi Sansthan",
      "Vivekananda Institute Of Professinal Studies",
      "Vijaynagar Institute Of Medical Sciences, Bellary",
      "Vydehi Institute Of Medical Sciences & Research Centre, Bangalore",
      "Vidhyan Chal Mahavidyakaya",
      "Visveswarapura College Of Law",
      "Vivekananda College Of Law",
      "Vidya College Of Engineering",
      "Vivekananda Institute Of Technology & Science",
      "Vinayak Vidyamandir College Of Law",
      "Vinayaka Missions Medical College, Pondicherry",
      "Vinayaka Missions Kirupananda Variyar Medical College, Salem",
      "Vivek College Of Law",
      "Vidyasthali Law College",
      "V.s.s.d. College",
      "Vrindavan Law College",
      "V.p Chest Institute Of Medical Sciences,delhi",
      "Vivekananda Institute Of Medical Sciences, Kolkata",
      "Venkateshwar Institute Of Technology",
      "Vivekanand College",
      "Vidya Bharathi College",
      "Velammal Institute Of Technology",
      "Vivekanandha Institute Of Engineering And Technology For Women",
      "Vivekanandha Business School For Women",
      "Varuvan Vadivelan Institute Of Technology",
      "Vindhya Institute Of Technology & Science",
      "Vivekanandha Dental College For Women",
      "Vels University",
      "Velammal College Of Management And Computer Studies",
      "Viswanadha Business School",
      "Vignana Jyothy Institute Of Management, Hyderabad",
      "Vindhya Institute Of Technology & Science",
      "Vidarbha Bhu-uddeshiya Shikshan Sanstha",
      "Vadodara Jilla Sarvodaya Seva Mandal",
      "Vaibhav Shikshan Sanstha",
      "Vardhaman College",
      "Vasant College Of Education",
      "Vasantrao Naik B.ed. College",
      "Veena Vadini Educational And Prashikshan Sanstha",
      "Veena Vadini Teachers Training Institute",
      "Vetalwadis College Of Education For Women",
      "Vibhas Trust",
      "Victoria College Of Education",
      "Victoria College Of Education",
      "Vidarbha Sharirik Shikshan Mahavidyalaya",
      "Vidya Niketan Samitis",
      "Vidya Prasarini Sabhas D.ed. College Bhaje",
      "Vidya Pratishtan Colleg Of Education",
      "Vidya Sagar College",
      "Vidya Vahini Shiksha Mahavidyalaya",
      "Vidya Vihar Shikshan Sanstha",
      "Vidyasagar College",
      "Vidyawati College",
      "Vindhyachal College",
      "Virangana Awantibai Mahavidyalaya",
      "Vishwashanti Gurukul Teacher Training Academy",
      "Viswa Bharti Institute",
      "Vithobaji Amle College Of Education",
      "Vivek Jyoti B.ed. College",
      "Vivekanand College Of Education",
      "Vivekvardhani College Of Education For Women",
      "Vns College Of Physical Education And Managment Studies",
      "Vspm College Of Education",
      "V - Tech. Institute Of Integrated Technology",
      "V.b.institute Of Teachers Training & Research",
      "V.d.institute Of Technology",
      "V.k. Jain College Of Education",
      "V.k. Jaln College Of Education",
      "V.k. Jaln College Of Education",
      "V.k. Tyagi Teacher Training College",
      "V.t.college Of Education",
      "V.v.k.degree College",
      "Vadant College Of Education",
      "Vaid Shankar Lal Memorial Teacher Training College",
      "Vaidanti Shiksha Mahavidyalaya",
      "Vaidic Teacher Training College",
      "Vaidik Shikshak Prakshikshan Mahavidyalaya",
      "Vaidya Shree Gajanand Shashtri Shikshak Prashikshan Mahavidyalaya",
      "Vaish Ariya Shishkshan Mahila Mahavidyalaya",
      "Vaish Arya Shikhan Mahila Mahavidyalaya",
      "Vaish Teacher Training College",
      "Vaish Teacher Training College",
      "Vaishno Devi Prashikshan Mahavidyalaya",
      "Vaishno Teacher Training College",
      "Vallabh Elementary Education Advancaemant Society",
      "Vallabh Government College",
      "Vansh Higher Education Institute",
      "Vansha Devi College",
      "Varda College Of Education",
      "Varda Teacher Training College",
      "Vardev Devi Institute Of Technical Education",
      "Vardhaman College",
      "Vardhman Shikshak Mahavidyalaya",
      "Vardhman Shikshak Prashikshan Bstc Vidhyalaya, Sikar, Rajasthan",
      "Vardhman Teacher Training College, Dholpur, Rajasthan",
      "Vardman Teacher Training College, Tonk, Rajasthan",
      "Varsha Teachers Training College, Jhunjhunu, Rajasthan",
      "Varshney College, Aligarh, Uttar Pradesh",
      "Vasundhara Mahila Shikshak Prashikshan Mahavidyalaya, Sikar, Rajasthan",
      "Vasundhara Mahila Shikshak Prashikshan Mahavidyalaya, Jaipur, Rajasthan",
      "Vb Institute Of Teacher Training & Research, Rohtak, Haryana",
      "Veakateshwara Institute Of Computer Science & Technology, Meerut, Uttar Pradesh",
      "Vedant College Of Education, Ghaziabad, Uttar Pradesh",
      "Vediv Teacher Training College, Mahendragarh, Haryana",
      "Veena Memorial Teacher Training College, Karauli, Rajasthan",
      "Veer Bahadur Singh Degree College, Gorakhpur, Uttar Pradesh",
      "Veer Kunwer Degree College, Bijnor, Uttar Pradesh",
      "Veerangana Narsuery Teacher Training Institute, Uttar Pradesh",
      "Veerb Bhadur Singh Mahila Mahavidyalaya, Lucknow, Uttar Pradesh",
      "Venkateshwara Institute Of Computer Science & Technology, Meerut, Uttar Pradesh",
      "Venketeshwar Teacher Training College, Bhiwani, Haryana",
      "Venteshwara Teacher Training College, Sonipat, Haryana",
      "Vicion International Teacher Training College, Hisar, Haryana",
      "Victor Public College, Etah, Uttar Pradesh",
      "Vidhavati Mukend Mahila Mahavidhyalaya, Uttar Pradesh",
      "Vidhyadshram Institute Of Teachers Training, Jodhpur, Rajasthan",
      "Vidhyawati Teacher Training College, Mahendragarh, Haryana",
      "Vidya Bharti Teacher Training College, Sikar, Rajasthan",
      "Vidya Bharti Teacher Training College, Udaipur, Rajasthan",
      "Vidya Bhavan Teacher Training College, Gurgaon, Haryana",
      "Vidya Sagar Teacher Training College, Sangrur, Punjab",
      "Vidya Teacher Training College, Bhiwani, Haryana",
      "Vidya Training Institute, New Delhi, Delhi",
      "Vidyamandir Teacher Training College, Sonipat, Haryana",
      "Vidyarthi Sanatak Mahavidyalaya, Kushinagar, Uttar Pradesh",
      "Vidyasthali Mahila Shikshak Prashikshan Mahavidyalaya, Jaipur, Rajasthan",
      "Vidyatthi Snatak Mahavidyalaya, Kushinagar, Uttar Pradesh",
      "Vidyavati Mukandlal (p.g.)college For Woman, Shahjahanpur, Uttar Pradesh",
      "Vijay College Of Education, Ghaziabad, Uttar Pradesh",
      "Vijay Laxmi Teacher Training College, Hisar, Haryana",
      "Vijay Memorial Teacher Training College, Mandi, Himachal Pradesh",
      "Vijaya Mahavidyalaya, Aligarh, Uttar Pradesh",
      "Vijaya Raje Mahila Shiksha Shastri Prashikshan Mahavidyalaya, Jhalawar, Rajasthan",
      "Vijayalaxmi Balmandir Samiti, Dausa, Rajasthan",
      "Vikarmaditya Teacher Training College, Rohtak, Haryana",
      "Vikram Singh Kanya Mahavidyalaya, Chandauli, Uttar Pradesh",
      "Vikramaditya Group Of Educational Institute, Rohtak, Haryana",
      "Vikramaditya Teacher Training College, Rohtak, Haryana",
      "Vikranmajit Singh Sanatan Dharma College, Kanpur Nagar, Uttar Pradesh",
      "Vinayak College Of Education, Sikar, Rajasthan",
      "Vision International Teacher Training Collegefor Women, Hisar, Haryana",
      "Vivekanand College, Delhi",
      "Vivekanand College Of Teachers Education, Udaipur, Rajasthan",
      "Vivekanand Girls Teachers Training College, Alwar, Rajasthan",
      "Vivekanand Gramodyog P.g. College, Auraiya, Uttar Pradesh",
      "Vivekanand Institute Of Management & Technology, Etah, Uttar Pradesh",
      "Vivekanand Shikshak Prashikshan Mahavidyalaya, Karauli, Rajasthan",
      "Vivekanand Teacher Training College, Rewari, Haryana",
      "Vivekanand Teacher Training College, Sikar, Rajasthan",
      "Vivekanand Teacher Training College, Hanumangarh, Rajasthan",
      "Vivekanand Vidya Sharam Teacher Training College, Churu, Rajasthan",
      "Viyay College Of Education, Ghaziabad, Uttar Pradesh",
      "Vljay Vallabh College Of Physical Education, Hamirpur, Himachal Pradesh",
      "Vp Teacher Training College",
      "Vyas Teacher Training College",
      "Venkateshwar Institute Of Computer Science & Technology",
      "Venkteshwara Teacher Training College",
      "Vidyavati Mukandlal P.g.college For Woman",
      "Vidyavati Mukandlal Girls College",
      "Viragna Avanti Bai Mahila Mahavidyalaya",
      "Vidyarthi Snatak Mahavidyalaya",
      "Vikramaditya Mahila Shikshak Prashikshan Mahavidyalaya",
      "Vikramajeet Singh Sanatan Dharm College",
      "Vikramjeet Singh Sanatan Dharam College",
      "Vimal Mahavidyalaya",
      "Vimla Ramashankar Degree College",
      "Vimla Vikram Mahavidyalaya",
      "Vinayak College",
      "Vinayak College Of Education",
      "Vinayak Girls College Of Education & Management",
      "Vinayak Teacher Training College",
      "Vinayak Teacher Training College",
      "Vinayak Vidyapeeth",
      "Viragna Avanti Mahila Mahavidyalaya",
      "Virendra Nath Shukla Institute Of Education & Technology",
      "Vishva Bharti Teacher Training College",
      "Vishveshwarya Institute Of Engineering & Technology",
      "Vishwa Bharti B,ed College",
      "Vishwa Bharti Shiksha Shashtri College",
      "Vishwa Bharti Teacher Training College",
      "Vishwa Bharti Teacher Training College",
      "Vishwa Bharti Teachers Training College",
      "Vishwas Teacher Training College",
      "Vishweshraiya College Of Education",
      "Vision International Teacher Training College(women)",
      "Vit College Of Education,jatorli",
      "Vivek College Of Education",
      "Vivek College Of Education",
      "Vivek Shikshan Prashikshan Vidyalaya",
      "Vivekanad College Of Education",
      "Vivekanad Teacher Training College",
      "Vivekanand College",
      "Vivekanand College",
      "Vivekanand College Of Education",
      "V-tech Institute Of Integrated Technology",
      "Vimal Bibhuti College Of Education",
      "Veerkunwarsingh University",
      "Vinaya Bhawan Dept. Of Education",
      "Vidyapati Bachelor Of Education College",
      "Vidyasagar Teacher Training College",
      "Vidyasagar College Of Education",
      "Vishweshwaraiya B.ed. College",
      "Vidyasagar Primary Teacher's Training Institute",
      "Vidyasagar Primary Teacher's Training Institute",
      "Vidyasagar Primary Teacher Training Institute",
      "Vivekananda Primary Teacher Training Institute",
      "Vinoba Bhave University",
      "Vivekananda Ramkrishna Mission B.ed. College",
      "Vivekananda College Of Education",
      "Vidyasagar Bani Bhawan Primary Teacher's Traininginstitute",
      "Viharilal College Of Education",
      "Vidya Sagar Teacher's Training College",
      "Vivekananda Teacher's Training College",
      "Veerayatan B.ed. College",
      "Vidyasagar Primary Teacher's Training Institute",
      "Vidyasagar Foundation School Of Education & Training",
      "Vidyasagar Teacher Training College",
      "Vivek Jyoti College",
      "V N T Teacher Training Institute",
      "V S Teacher Training Institute",
      "V.e.s.d.ed College Vocational Education Societ",
      "V.j.p.college Of Education",
      "V.l.s. Eduacation Trust",
      "V.m.lingaiah College O Education",
      "V.o. Chidambaram College Of Education",
      "V.p.muthaiah Pillai Meenakshi Ammal College Of Education",
      "V.p.n. Memorial Teacher Training Institute",
      "V.r.naidu College Of Physical Education",
      "V.s.isaac College Of Education",
      "V.v. Sangha College O Education",
      "V.v. Sanghas Teacher Training Institute",
      "V.v. Sanghs Primary School T.t.i",
      "V.v. Teacher Training Institute",
      "V.venkatasamy Naidu College Physical Education",
      "Vadaranyam College Of Education",
      "Vagdevi College Of Education",
      "Vaijinath Kamthane D.e College",
      "Vailankanni College Of Education",
      "Valivalam Desikar Institute Teacher Training",
      "Valiyam Memorial College For Teacher Education",
      "Vallalar Teacher Training Institute",
      "Valliammaiyar Hindu Teacher Training Institute",
      "Valluvar Teacher Training Institutes",
      "Valummel Teacher Training Institute",
      "Vandayar College Of Education",
      "Vani College Of Education",
      "Vanitha Teacher Training Institute",
      "Vanitha Vidyalaya Teachers Training Institute",
      "Varma Teachers Training Institute",
      "Varruvan Vadivelan College Of Education",
      "Vasavi College Of Teacher Education",
      "Vasu Teacher Training Institute",
      "Vathsala Johnson College Of Teacher Education",
      "Vathsalya Mahileyara Mattu Makkala Ashraya Samsthe",
      "Vedanth D Ed College",
      "Vedavathi D.ed College",
      "Veeralakshmi Teacher Training Institute For Women",
      "Vekateswara College Of Education",
      "Vekkaliyamman College Of Education",
      "Vel College Of Education",
      "Vel Teachers Training Institute",
      "Velammal College Of Education",
      "Vellalar College Of Education",
      "Vellore College Of Education",
      "Veludayar School Of Education",
      "Venkat International College Of Education",
      "Venkat Teacher Training Institute",
      "Venkatacalapathy Teacher Training Institute",
      "Venkatagiri Aithal Memorial D Ed College",
      "Venkatesha Tch College",
      "Venkatesvara College Of Education",
      "Venkateswara College O Education",
      "Venkateswara College Of Education",
      "Vestley College Of Education, Pudukkottai, Tamil Nadu",
      "Vet College Of Education, Tirunelveli, Tamil Nadu",
      "Vet College Of Education, Viluppuram, Tamil Nadu",
      "Vettri Vel College Of Education, Salem, Tamil Nadu",
      "Vickram College Of Teacher Education, Sivaganga, Tamil Nadu",
      "Victoria Ded College, Bangalore, Karnataka",
      "Victory College Of Education, Dindigul, Tamil Nadu",
      "Victory College Of Teacher Education, Thiruvananthapuram, Kerala",
      "Victory Teacher Training Institute, Chennai, Tamil Nadu",
      "Victory Teacher Training Institute, Tiruvallur, Tamil Nadu",
      "Vidhya Sagar Womens College Education, Kanchipuram, Tamil Nadu",
      "Vidhya Sagar Womens Teacher Training Institute, Chennai, Tamil Nadu",
      "Vidhya Vikas College Of Education, Namakkal, Tamil Nadu",
      "Vidhya Vikas Plus The Institute Of Education, Perambalur, Tamil Nadu",
      "Vidhyalaya Teacher Training Institute, Tiruvannamalai, Tamil Nadu",
      "Vidya Dan Samitis Smt.m.b.huilgol College Of Education, Gadag, Karnataka",
      "Vidya Prachara Sangha Vijaya Teacher Training College, Mandya, Karnataka",
      "Vidya Prasarak Mandal, Bagalkot, Karnataka",
      "Vidya Prasarak Samiti Killa, Belgaum, Karnataka",
      "Vidya Rashmi Teacher Training Institution, Kannada, Karnataka",
      "Vidya Samvardhak Manda, Belgaum, Karnataka",
      "Vidya Samvardhaka Teacher Training Institute, Belgaum, Karnataka",
      "Vidya Vahini T.ch College, Bangalore, Karnataka",
      "Vidya Vihar Teacher Training Institute, Vellore, Tamil Nadu",
      "Vidya Vikas College Of Education, Mysore, Karnataka",
      "Vidya Vikas Teachers Training Institute, Chamrajnagar, Karnataka",
      "Vidya Vikas Teachers Training Institute, Gulbarga, Karnataka",
      "Vidyabharati Pratishtha (r), Uttara Kannada, Karnataka",
      "Vidyananda Gurukula Education Trusts D.ed College, Koppal, Karnataka",
      "Vidyanidhi Education Society, Bangalore, Karnataka",
      "Vidyanikethan D.ed College",
      "Vidyaranya Education College",
      "Vidyaranya Vidya Samasthe(r)",
      "Vidyasagar Alpasankyata Shaikshanik Samsthes",
      "Vidyavahini College",
      "Vidyodaya D.ed College",
      "Vighneshwara College Of Diploma Education",
      "Vignesh College Of Education",
      "Vignesh Teacher Training Institute",
      "Vignesh Teacher Training Institute",
      "Vignesh Teacher Training Institute",
      "Vignesh Teacher Training Institute",
      "Vigneshwara Teacher Training Institute",
      "Vijay College Of Education",
      "Vijaya Bharathi Teacher Training Institute",
      "Vijaya Teachers Training Institute",
      "Vijaya Vidyanikethan Primary Teacher Training Institute",
      "Vijayalakshmi Teacher Training Institute",
      "Vijayanagar College Of Teachers Training",
      "Vijayanagara College Of Education",
      "Vikram College Of Education",
      "Vikram Sara Bai Teacher Training Institute",
      "Vikramaditya Education Society",
      "Vinayaga College Of Education",
      "Vinayaga Education College",
      "Vinayaga Teacher Training Institute",
      "Vinayagas Institute Of Teacher Education",
      "Vinayaka Missions College Of Education",
      "Vinayaka Missions College Of Physical Education",
      "Vinayaka Saraswathi Vidya Kendra",
      "Vinayaka Vidya Vardhak Trust",
      "Vinoothana Shikshana Seva Samsthe, Koppal, Karnataka",
      "Vinoothana Shikshana Seva Samsthe Priyadarshini College Of Education, Gadag, Karnataka",
      "Vioce Of God Teacher Training Institute, Namakkal, Tamil Nadu",
      "Virudhnagar M.s.p.nadar College Of Education, Virudhunagar, Tamil Nadu",
      "Vishal Teacher Training Institute, Bidar, Karnataka",
      "Vishnu Lakshmi Trust Vishnu Lakshmi Trust, Erode, Tamil Nadu",
      "Vishnu Teacher Training Institute, Kolar, Karnataka",
      "Vishwa Bharathi College Of Education, Dharmapuri, Tamil Nadu",
      "Vishwadarshana Teachers Training Institution, Uttara Kannada, Karnataka",
      "Visveswaraya College, Shimoga, Karnataka",
      "Viswabharathi College Of Education, Salem, Tamil Nadu",
      "Viswadarshini Teacher Training Institute, Thiruvananthapuram, Kerala",
      "Vivekananda College Of Education, Bangalore, Karnataka",
      "Vivekananda College Of Education, Cuddalore, Tamil Nadu",
      "Vivekananda College Of Education, Karnataka",
      "Vivekananda College Of Education, Hassan, Karnataka",
      "Vivekananda College Of Education, Kanyakumari, Tamil Nadu",
      "Vivekananda College Of Education, Sivaganga, Tamil Nadu",
      "Vivekananda College Of Education, Tiruvallur, Tamil Nadu",
      "Vivekananda Shikshana Samsthe, Mysore, Karnataka",
      "Vivekananda Teacher Training Institute, Belgaum, Karnataka",
      "Vivekananda Vidyalaya College Of Education, Vellore, Tamil Nadu",
      "Vivekanandha College Of Education For Women, Namakkal, Tamil Nadu",
      "Voc College Of Education, Thoothukudi, Tamil Nadu",
      "Vpn College For Teacher Education, Viluppuram, Tamil Nadu",
      "Vsk Teacher Training Institute, Pudukkottai, Tamil Nadu",
      "Vysya College Of Education, Salem, Tamil Nadu",
      "Vishwaksena College Of Education, Tiruvallur, Tamil Nadu",
      "Vivekananda College Of Education, Raichur, Karnataka",
      "V T Choksi Sarvjanik College Education, Surat, Gujarat",
      "Vai Dhunda Maharaj Deglulkar College",
      "Vaikunta Baliga Law College",
      "Vallurupalli Nageshwara Rao Vignana Jyothi Institute Of Engineering & Technology",
      "Vanilisetti Satyanarayana Krishna Murthy Degree Colleg",
      "Vankisannarudrappa Law College",
      "Vasundhara Mahila P.g. Mahavidyalaya",
      "Vedanta P.g. Girls's College",
      "Vedic Kanya P.g. Mahavidyalaya",
      "Veer Kunwar Singh Mahila College",
      "Veermata Jijabai Technical Institute",
      "Venkatesh Mahajan Senior College",
      "Vidya Vikas Arts Commerce & Science College",
      "Vijay Shikshan Prasasak Mandal's Dagdjirao Deshmukh Arts Commerce And Science College",
      "Vindhya Vasini (+3) College",
      "Vivek Vardhini (afternoon) College Of Arts",
      "Vivekanandha College Of Arts And Science For Women",
      "Vk Krishna Menon College Of Commerce & Economics & Science",
      "Vpspms Arts Commerce & Science College",
      "Vr College Of Engineering",
      "Vr Sidhartha Engineering College",
      "Vslakshmi Women's Degree & Pg College",
      "Vss Medical College",
      "Vtjm & Ivtrdegree College",
      "Vansathali Degree College",
      "Vanvasi Mahila Mahavidyalaya",
      "Vasanta College For Women",
      "Victor Public College",
      "Vidyarthi P.g. College",
      "Vijay College Of Education",
      "Vimla Rani Bhargava Degree College",
      "Vishwanath Singh Mahavidyalaya",
      "Vivekanand Mahavidyalaya Semari",
      "Viya Institute Of Creative Teaching",
      "Vidnyan Mahavidyalaya",
      "Vision Institute Of Advanced Studies",
      "Vivekananda Mission Asram",
      "V.r. Ruia Mook Badhir Vidyalayam, Teacher Training Centre",
      "Vasudha Kalyani Special Education Institute",
      "Vidyaniketan Social Cultural Educational Multi Objectal Oriented Society",
      "Vijay Human Services",
      "Vidya Sagar",
      "V-excel Educational Trust",
      "Vasantdada Patil Dental College And Hospital , Sangli",
      "Vidarbha Youth Welfare Societys Dental College & Hospital , Amravati",
      "Vinayaka Missions Sankarachariyar Dental College , Salem",
      "Vydehi Institute Of Dental Sciences & Research , Bangalore",
      "V.s. Dental College, Bangalore",
      "Vaidik Dental College And Research Centre, Daman",
      "Vananchal Dental College & Hospital, Garhwa",
      "Vidya Shikshan Prasarak Mandals Dental College & Research Centre , Nagpur",
      "Vinayaka Missions Dental College , Sitapur",
      "Vivekanandha Dental College For Women , Tiruchengode",
      "Vishnu Dental College , Bhimavaram",
      "Vyas Dental College & Hospital , Jodhpur",
      "V.s. Dental College",
      "Vss Medical College, Burala",
      "Villupuram Medical College, Villupuram",
      "Veer Chandra Singh Garhwali Govt. Medical Sc. & Research Instt, Srinagar, Pauri Garhwal",
      "Venkateswara College Of Pharmacy , Thanjavur",
      "Vidyavati College Of Nursing, Bhind",
      "Vinayaka Hospital School Of Nursing,wayanad, Wayanad, Kerala",
      "Vishwa Bharathi College Of Pharmaceutical Sciences Perechereta Junction , Guntur, Andhra Pradesh",
      "Vagdevi College Of Pharmacy And Research Centre , Nellore, Andhra Pradesh",
      "Visweswarapura Institute Of Pharmaceutical Sciences , Bangalore, Karnataka",
      "Vaageswari College Of Pharmacy , Karimnagar, Andhra Pradesh",
      "Vikas Pharmacy College , Nalgonda, Andhra Pradesh",
      "V.v. Sanghas T.v.m. College Of Pharmacy , Bellary, Karnataka",
      "Vels College Of Pharmacy , Pallavaram, Tamil Nadu",
      "Vinayaka Missions College Of Pharmacy , Ariyanoor, Salem, Tamil Nadu",
      "Vishwavidya Samsthes P.b.college Of Pharmacy , Yadgiri, Karnataka",
      "V.l. College Of Pharmacy , Raichur, Karnataka",
      "Vaagdevi College Of Pharmacy , Hanamkonda, Warangal, Andhra Pradesh",
      "Vasantidevi Patil Instt. Of Pharmacy , Kolhapur, Maharashtra",
      "Vishal Junnar Seva Mandal Institute Of Pharmacy For Women , Junnar, Pune, Maharashtra",
      "V.v. Sangha Togari Veeramallappa Memorial College Of Pharmacy , Bellary, Karnataka",
      "Vivekanand Education Society College Of Pharmacy , Ranebennur, Karnataka",
      "Vikas College Of B. Pharmacy , Suryapet, Nalgonda, Andhra Pradesh",
      "V.m.v.v. Sanga School Of Pharmacy,hungund, Karnataka",
      "Vidya Vikas Trust College Of Pharmacy , Bidar, Karnataka",
      "Vagdevi College Of Pharmacy, Guntur, Andhra Pradesh",
      "V.n.s. Instt. Of Pharmacy , Bhopal, Madhya Pradesh",
      "V.m.s. College Of Pharmacy , Gurdaspur, Punjab",
      "Vedica College Of Pharmacy Polytechnic , Bhopal, Madhya Pradesh",
      "Vidyabharati College Of Pharmacy , Amravati, Maharashtra",
      "Varun College Of Pharmacy , Jaipur, Rajasthan",
      "Vidarbha Youth Welfare Society, Institute Of Pharmaceutical Education And Research , Wardha, Maharashtra",
      "Vinayaka Missions College Of Pharmacy , Salem, Tamil Nadu",
      "Visveswarapura Institute Of Pharmaceutical Sciences , Bangalore, Karnataka",
      "Vels College Of Pharmacy , Pallavaram, Chennai, Tamil Nadu",
      "Vishal Junnar Seva Mandals Institute Of Pharmacy , Ale, Maharashtra",
      "Vivek College Of Technical Education, Bijnor, Uttar Pradesh",
      "Vagadevi Institute Of Pharmaceutical Science, Warangal, Andhra Pradesh",
      "Vengurla Homoeopathic Medical College & Hospital, Sindhudurg, Maharashtra",
      "Venutai Yashwantrao Chavan Homoeopathic Medical College, Kolhapur, Maharashtra",
      "Venkateswara Homoeopathic Medical College And Hospital, Kanchipuram, Tamil Nadu",
      "Vasundhra Raje Homoeopathic Medical College And Hospital, Gwalior, Madhya Pradesh",
      "Vidya Vaibhav Shikshan Mandal Dapoli Homoeopathic Medical College, Ratnagiri, Maharashtra",
      "Vinayaka Missions Homoeopathic Medical College, Salem, Tamil Nadu",
      "Vinayaka Missions Sikkim University College Of Nursing, East Sikkim, Sikkim",
      "Vidyarathna College Of Nursing, Udupi, Karnataka",
      "Vivekanand College Of Nursing, Vivekanand Hospital & Research Centre, Moradabad, Uttar Pradesh",
      "V V Vanniaperumal Nursing College For Women, Virudhunagar, Tamil Nadu",
      "Vee Care College Of Nursing, Thiruvallur, Tamil Nadu",
      "Vel R S Medical College, Chennai, Tamil Nadu",
      "Vellalar College Of Nursing, Erode, Tamil Nadu",
      "Vignesh Nursing College, Tiruvannamalai, Tamil Nadu",
      "Viswa Sai College Of Nursing, Bangalore, Karnataka",
      "Venkateswara College Of Nursing, Chitradurga, Karnataka",
      "Victory College Of Nursing, Bangalore, Karnataka",
      "Vasantha College Of Nursing, Bidar, Karnataka",
      "Vidya College Of Nursing, Udupi, Karnataka",
      "Vikram College Of Nursing, Mysore, Karnataka",
      "Venkatnayadu Mphw F Trg Institute, East Godavari, Andhra Pradesh",
      "V P M M College Of Nursing, Virudhunagar, Tamil Nadu",
      "Vijaya College Of Nursing, Kollam, Kerala",
      "Vidya Institute Of Nursing Sciences, Nashik, Maharashtra",
      "Vande Maatram School Of Nursing, Gwalior, Madhya Pradesh",
      "Veena Vadini College Of Nursing, Gwalior, Madhya Pradesh",
      "Viashnavi Institute Of Proffesional Studies, Gwalior, Madhya Pradesh",
      "V S Alwar Nursing Institute, Alwar, Rajasthan",
      "Vinayak Nursing School, Jaipur, Rajasthan",
      "Vyas Nursing Institute, School Of Nursing, Jodhpur, Rajasthan",
      "Vinayaka Missions Sikkim University School Of Nursing, East Sikkim, Sikkim",
      "Vijaya Health Care Academic Society College Of Nursing, Ranga Reddy, Andhra Pradesh",
      "Vande Matram College Of Nursing, Gwalior, Madhya Pradesh",
      "V S P Ms College Of Nursing & Research Centre, Nagpur, Maharashtra",
      "Vydehi Institute Of Nursing Sciences & Research Centre, Bangalore, Karnataka",
      "Vinayaka Missions Annapoorna College Of Nursing, Salem, Tamil Nadu",
      "Vivekanandha College Of Nursing, Namakkal, Tamil Nadu",
      "Vinayaka Missions College Of Nursing, Kirumampakkam, Pondicherry",
      "Vagdevi College Of Nursing, Bangalore, Karnataka",
      "Vidya College Of Nursing, Udupi, Karnataka",
      "Vidyakirana Institute Of Nursing Sciences, Bangalore, Karnataka",
      "Vidyarathna College Of Nursing, Udupi, Karnataka",
      "Vikram College Of Nursing, Mysore, Karnataka",
      "Vrundavan Institute Of Nursing Education, Bardez, Goa",
      "Vidya Nikunj Nursing School, Rajkot, Gujarat",
      "Voctoria Jubilee Hospital Trust, School Of Nursing, Ahmedabad, Gujarat",
      "Ved Nursing Training Instt, Panipat, Haryana",
      "Vidyavati Institute Of Health And Medical Sciences, Mahendergarh, Haryana",
      "Vani School Of Nursing, Cuddapah, Andhra Pradesh",
      "Venkata Padma School Of Nursing, Vizianagaram, Andhra Pradesh",
      "Venkata Sai School Of Nursing, Medak, Andhra Pradesh",
      "Victoria Memorial Hospital, Hanamkonda, Andhra Pradesh",
      "Vijay Institute Of Nursing Sciences, Srikakulam, Andhra Pradesh",
      "Vijay School Of Nursing, Vijayawada, Andhra Pradesh",
      "Vijaya School Of Nursing, Guntur, Andhra Pradesh",
      "Vijaya School Of Nursing, Rangareddy, Andhra Pradesh",
      "Vijaya School Of Nursing, Nellore, Andhra Pradesh",
      "Vimala School Of Nursing, Anantapur, Andhra Pradesh",
      "Vinayaka School Of Nursing, Tirupati, Andhra Pradesh",
      "Visakha School Of Nursing, Visakhapatnam, Andhra Pradesh",
      "Vishwa Bharathi School Of Nursing, Kurnool, Andhra Pradesh",
      "Viswa Sai School Of Nursing, Kovvur, Andhra Pradesh",
      "Viswavani School Of Nurisng, Nandyal, Andhra Pradesh",
      "Vardhan School Of Nursing, Vijayawada, Andhra Pradesh",
      "Vijay Marie, Hospital School Of Nursing, Begumpet, Andhra Pradesh",
      "Vijaya College Of Nursing, Kurnool, Andhra Pradesh",
      "Ved Nursing College, Panipat, Haryana",
      "V S S College Of Nursing, Bangalore, Karnataka",
      "Varadaraja College Of Nursing, Tumkur, Karnataka",
      "Varma College Of Nursing, Tirupati, Andhra Pradesh",
      "Vignan College Of Nursing, Ongole, Andhra Pradesh",
      "Vijay College Of Nursing, Srikakulam, Andhra Pradesh",
      "Vijay Marie College Of Nursing, Khairatabad, Andhra Pradesh",
      "Vijaya Health Care Academic Society, College Of Nursing, Andhra Pradesh",
      "Viswabharathi College Of Nursing, Kurnool, Andhra Pradesh",
      "Varalakshmi College Of Nursing, Bangalore, Karnataka",
      "Vidya Vikas College Of Nursing, Mysore, Karnataka",
      "Vivekananda College Of Nursing, Chitradurga, Karnataka",
      "Vydehi Institute Of Nursing Sciences & Res Centre, Bangalore, Karnataka",
      "Vijaya College Of Nursing, Nellor, Andhra Pradesh",
      "V N S S College Of Nursing, Kollam, Kerala",
      "Vijaya College Of Nursing, Kottarakara, Kerala",
      "V S P M College Of Nursing & Research Centre, Nagpur, Maharashtra",
      "Vinayaka Missions College Of Nursing, Kirumampakkam, Pondicherry",
      "Vinayaka Missions College Of Nursing, Karaikal, Pondicherry",
      "Vel R S Medical College, Chennai, Tamil Nadu",
      "Venkateswara Nursing College, Chennai, Tamil Nadu",
      "Vivekananda College Of Nursing, Namakkal, Tamil Nadu",
      "Vinayaka Missions Annapoorana College Of Nursing, Salem, Tamil Nadu",
      "Vinayaka Hospital, Wayanad, Kerala",
      "Vande Maatram College Of Nursing, Gwalior, Madhya Pradesh",
      "Veena Vadini College Of Nursing, Bhopal, Madhya Pradesh",
      "Veerangna Awanti Bai Nursing College, Chhatarpur, Madhya Pradesh",
      "Vijay Laxmi College Of Nursing, Gwalior, Madhya Pradesh",
      "Vishal Vate Memorial College Of Nursing, Bhopal, Madhya Pradesh",
      "Vagdevi College Of Nursing, Bangalore, Karnataka",
      "Vinayaka Missions School Of Nursing Sciences, Bahour, Pondicherry",
      "Vidyakirana Institute Of Nursing Sciences, Bangalore, Karnataka",
      "Vinayakrao Patil Shikshan Prasarak Mandals, Aurangabad, Maharashtra",
      "Vishwabharathi College Of Nursing, Mysore, Karnataka",
      "Vivekananda Institute Of Social Work & Social Science, Orissa",
      "Varanasi College Of Nursing, Varanasi, Uttar Pradesh",
      "Vanita Vishram School Of Nursing, Surat, Gujarat",
      "Vinayaka Institute Of Nursing, Anand, Gujarat",
      "Vinayak College Of Nursing, Jaipur, Rajasthan",
      "Vyas College Of Nursing, Jodhpur, Rajasthan",
      "Vision ANM Female Health Worker, Koraput, Orissa",
      "Vivekananda Charitable Trust ANM Training Centre, Kalahandi, Orissa",
      "Vijaya Multipurpose Health Workers F Training Institute, Guntur, Andhra Pradesh",
      "Vijetha Multi Purpose Health Workers Female Training Institute, Hyderabad, Andhra Pradesh",
      "Vande Matram Nursing School, Gwalior, Madhya Pradesh",
      "Veerangana Awanti College Of Nursing, Chhatarpur, Madhya Pradesh",
      "Vidhyanavi Vidhya Peeth School Of Nursing, Gwalior, Madhya Pradesh",
      "Ved Nursing Training Institute, Panipat, Haryana",
      "Vivekananda College Of Nursing, Lucknow, Uttar Pradesh",
      "Vijaya Raje College Of Nursing, Jodhpur, Rajasthan",
      "V V M School Of Nursing, Bhopal, Madhya Pradesh",
      "Vatsalya Institute Of Nursing & Paramedical Sciences, Allahabad, Uttar Pradesh",
      "Vignan Institute Of Nursing, Bangalore, Karnataka",
      "Vidya Kirana School Of Nursing, Bangalore, Karnataka",
      "Viswa Sai School Of Nursing, Bangalore, Karnataka",
      "Vivekananda School Of Nursing, Chitradurga, Karnataka",
      "Vidya Sagar School Of Nursing, Mansa, Punjab",
      "V S S Medical College Hospital, School Of Nursing, Sambalpur, Orissa",
      "Vikash G N M Training School, Balasore, Orissa",
      "Vivekananda Institute Of Social Work & Social Science, V I S W A S S School Of Nursing, Kumarbas, Orissa",
      "Vinayaka Missions College Of Nursing, Karaikal, Pondicherry",
      "Vinayaka Missionss College Of Nursing, Kirukambakkam, Pondicherry",
      "Vidyasagar Institute Of Health, Paschim Medinipur, West Bengal",
      "Vananchal School Of Nursing, Garhwa, Jharkhand",
      "V L M College Of Nursing & Allied Health Sciences, Allahabad, Uttar Pradesh",
      "V S S School Of Nursing, Bangalore, Karnataka",
      "Vagdevi Nursing School, Bangalore, Karnataka",
      "Varalakshmi School Of Nursing, Bangalore, Karnataka",
      "Vaidya School Of Nursing, Hassan, Karnataka",
      "Valley School Of Nursing, Bangalore, Karnataka",
      "Vanie Nursing School, Bangalore, Karnataka",
      "Varalakshmi School Of Nursing, Bangalore, Karnataka",
      "Vardaraja School Of Nursing, Tumkur, Karnataka",
      "Victoria Hospital, School Of Nursing, Fort Bangalore, Karnataka",
      "Vidya School Of Nursing, Udupi, Karnataka",
      "Vidya Vikas Trusts, School Of Nursing, Bidar, Karnataka",
      "Vamanrao Ithape Rgnm School, Ahmednagar, Maharashtra",
      "Vidyamani School Of Nursing, Bidar, Karnataka",
      "Vidyarashmi School Of Nursing, Dakshina Kannada, Karnataka",
      "Vidyasagar School Of Nursing , Bangalore",
      "Vidyavahini School Of Nursing , Tumkur",
      "Vighneshwara Institute Of Nursing Sciences , Hubli",
      "Vijayalakshmi School Of Nursing , Kolar",
      "Vikram School Of Nursing , Mysore",
      "Vishnu School Of Nursing , Kolar",
      "Vishwa Bharathi Instt Of Nsg Sci & Tech , Mysore",
      "Vishwa Darshana School Of Nursing , Ankola",
      "Viswa Bharathi School Of Nursing , Bangalore",
      "V S Alwar Nursing Institute,alwar",
      "V I P School Of Nursing , Bhopal",
      "Vydehi Institute Of Nursing Sciences & Res. Centre , Whitefield",
      "V S General Hospital , School Of Nursing,thane",
      "Vaidyanath Nursing School,beed",
      "Vijaya Ganga Rural Medical And Res Foundation,ahmednagar",
      "Vimal Nursing School,kolhapur",
      "Vishwasattya School Of Nursing,nashik",
      "Vee Care School Of Nursing , Thiruvallur",
      "Vel S School Of Nursing, , Chennai",
      "Vinayaka School Of Nursing, ,salem",
      "Vinayaka Missions Annapoorna School Of Nursing, , Salem",
      "Vivekananda School Of Nursing, , Salem",
      "Vindhya School Of Nursing,satna",
      "Vision School Of Nursing,betul",
      "Vijaya School Of Nursing,kollam",
      "Vijaymatha School Of Nursing,thrissur",
      "Vikramaditya Institute Of Medical Sciences ,bhopal",
      "Vindhyanchal College Of Nursing, Rewa",
      "Vishwas Training Institute For Professional Sciences ,morena",
      "V G School Of Nursing , Coimbatore",
      "V S Educational Trust, School Of Nursing, Salem",
      "Vikram School Of Nursing, Madurai",
      "Vinayaka College Of Nursing, Sitapur",
      "V L M College Of Nursing And Allied Health Sciences, Allahabad",
      "Vatsalya Institute Of Nursing & Paramedicla Sciences, Allahabad",
      "Victor Institute Of Nursing And Paramedical Sciences, Mohali",
      "Vidya Sagar College Of Nursing, Mansa",
      "V M S Institute Of Nursing & Paramedical Sciences, Gurdaspur",
      "Vijayanagar College Of Nursing, Bangalore",
      "V M S College Of Nursing, Gurdaspur",
      "Veeravalli College Of Law",
      "Visakha Law College, Visakhapatnam",
      "Virindavan Law College",
      "V. P. Mandals Thane Municipal Councils Law College",
      "Vidya Pratishthans Law College",
      "Victor Dantas Law College",
      "Vidhi Mahavidyalaya",
      "Vivekanand Education Societys College Of Law",
      "Virangana Avanti Bai Law College",
      "Virendra Kumar Singhal Law College",
      "Vinayak Vidhi Mahavidyalaya",
      "Viswa Bharathi College Of Law",
      "V. R. Law College",
      "Vivekananda Institute Of Professional Studies",
      "Vivekananda College Of Commerce And Law",
      "Vithaldas Thakordas Choksi Sarvajanik Law College",
      "Vitasta School Of Law",
      "Vindhyan Chal Law College",
      "Vardhman College",
      "Vikramjeet Singh Sanatan Dharama College V. S. S. D. College",
      "V. M. S. College Of Law, Gurdaspur, Punjab",
      "Veena Memorial Law College, Karauli, Rajasthan",
      "Vidya Vardhaka Law College, Mysore, Karnataka",
      "V. V. V. Sanghas Vunki Sannarudrappa Law College, Bellary, Karnataka",
      "Vaikunta Baliga College Of Law, Udupi, Karnataka",
      "Vivekananda Law College, Dakshina Kannada, Karnataka",
      "Vivekanand College Of Agriculture, Buldhana, Maharashtra",
      "Vpv College Of Engineering, Theni, Tamil Nadu",
      "Vsa Educational And Charitable Trusts Group Of Institutions, Salem, Tamil Nadu",
      "V V College Of Engineering, Tirunelveli, Tamil Nadu",
      "Vetri Vinayaha College Of Engineering And Technology, Tiruchirappalli, Tamil Nadu",
      "Vandayar Engineering College, Thanjavur, Tamil Nadu",
      "Veltech Multi Tech Dr.rangarajan Dr.sakunthala Engineering College, Tiruvallur, Tamil Nadu",
      "Vel Tech High Tech Dr.rangarajan Dr.sakunthala Engineering College, Tiruvallur, Tamil Nadu",
      "Vision School Of Management, Chittorgarh, Rajasthan",
      "Vision School Of Commerce, Chittorgarh, Rajasthan",
      "V.s.b College Of Engineering Technical Campus, Coimbatore, Tamil Nadu",
      "Vivekananda Institute Of Management Studies, Coimbatore, Tamil Nadu",
      "Vaigai College Of Engineering, Madurai, Tamil Nadu",
      "Vidhya Mandhir Institute Of Technology, Erode, Tamil Nadu",
      "Veerammal Engineering College, Dindigul, Tamil Nadu",
      "V K S College Of Engineering And Technology, Karur, Tamil Nadu",
      "Vins Christian Women's College Of Engineering, Kanyakumari, Tamil Nadu",
      "Vivekanandha College Of Technology For Women, Namakkal, Tamil Nadu",
      "Vivekanandha Institute Of Information And Management Studies, Namakkal, Tamil Nadu",
      "Vijay Institute Of Management, Dindigul, Tamil Nadu",
      "Vedhantha Institute Of Technology, Viluppuram, Tamil Nadu",
      "Vyasanagar Junior College, Jajpur, Orissa",
      "Vidyanidhi Info Tech Academy, Mumbai City, Maharashtra",
      "Vidya Niketan Institute Of Engineering & Technology(vniet), Nagpur, Maharashtra",
      "Vikram Simhapuri University, Nellore, Andhra Pradesh",
      "Veer Surendra Sai University Of Technology, Sambalpur, Orissa",
      "V.i.t. University, Jaipur, Rajasthan",
      "Vignan University, Guntur, Andhra Pradesh",
      "Vinayaka Missions Sikkim University, East Siang, Sikkim",
      "Vivekanand Institute Of Hotel & Tourism Management, Rajkot, Gujarat",
      "Vivekananda Parvatiya Krishi Anusandhan Sansthan, Almora, Uttaranchal",
      "Vimal Jyothi Institute Of Management And Research, Kannur, Kerala",
      "Vaishali Institute Of Business And Rural Management, Muzaffarpur, Bihar",
      "Vishveshwarya School Of Management, Gautam Buddha Nagar, Uttar Pradesh",
      "Vishnu Institute Of Technology, West Godavari, Andhra Pradesh",
      "Vignana Bharathi Institute Of Technology, Rangareddy, Andhra Pradesh",
      "Vivek College Of Management Technology, Bijnor, Uttar Pradesh",
      "V.m.patel Institute Of Management, Mehsana, Gujarat",
      "Vinuthna Institute Of Technology & Science And Vinuthna College Of Management, Warangal, Andhra Pradesh",
      "Vivekananda Degree College, Karnataka",
      "Visakha Techincal Campus, Visakhapatnam, Andhra Pradesh",
      "Veerappa Nisty Engineering College, Gulbarga, Karnataka",
      "Vivek Vardhini School Of Business Management, Hyderabad, Andhra Pradesh",
      "Vignan's Institute Of Technology And Aeronautical Engineering, Andhra Pradesh",
      "Vkr, Vnb & Agk College Of Engineering, Krishna, Andhra Pradesh",
      "Vsm College Of Engineering, East Godavari, Andhra Pradesh",
      "Vaagdevi College Of Engineering, Warangal, Andhra Pradesh",
      "Vikas Institute Of Engineering And Technology, Andhra Pradesh",
      "Vijaya Institute Of Technology For Women, Krishna, Andhra Pradesh",
      "Vms Institute Of Management Batala, Gurdaspur, Punjab",
      "Vijaya Krishna Institute Of Technology & Sciences, Rangareddy, Andhra Pradesh",
      "Vaageswari Institute Of Management Sciences, Karimnagar, Andhra Pradesh",
      "Visakha Institute Of Engineering & Technology, Visakhapatnam, Andhra Pradesh",
      "Visvodaya Engineering College, Nellore, Andhra Pradesh",
      "Vignan's Institute Of Engineering For Women, Visakhapatnam, Andhra Pradesh",
      "Vestal Academy Of Information Technology & Management, Warangal, Andhra Pradesh",
      "Vs Lakshmi Engineering College For Women, East Godavari, Andhra Pradesh",
      "Vizag Institute Of Technology, Visakhapatnam, Andhra Pradesh",
      "Visakha Institute Of Technology And Science, Visakhapatnam, Andhra Pradesh",
      "Vinayak Institute Of Management, Karnal, Haryana",
      "Vemu Institute Of Technology, Chittoor, Andhra Pradesh",
      "Viswa Bharathi College Of Technology & Management, Guntur, Andhra Pradesh",
      "Velankanni Institute Of Management Studies, Andhra Pradesh",
      "Vijay Rural Engineering College, Nizamabad, Andhra Pradesh",
      "Vasavi Institute Of Management And Computer Sciences, Ysr District, Andhra Pradesh",
      "V.r. College Of Management And Information Technology, Warangal, Andhra Pradesh",
      "Vivekanand College Of Computer Science, Rajkot, Andhra Pradesh",
      "Vishnu Sree Institute Of Technology, Nalgonda, Andhra Pradesh",
      "Vmr Institute Of Technology & Management Sciences, Rangareddy, Andhra Pradesh",
      "Vijaya Institute Of Management Sciences For Women, Krishna, Andhra Pradesh",
      "Vivekananda Group Of Institutions, Rangareddy, Andhra Pradesh",
      "Venkteshwar Institute Of Technology, Indore, Madhya Pradesh",
      "Vindhya Institute Of Management And Research, Indore, Madhya Pradesh",
      "Vip College Of Management, Bhopal, Madhya Pradesh",
      "Vet Bvl Polytechnic, Karnataka",
      "Vidya Vikas Polytechnic, Karnataka",
      "Vasavi Gnanapeeta Polytechnic, Karnataka",
      "Vmvs Polytechnic, Hungund, Bagalkot, Karnataka",
      "Vidhya Prasaaraka Mandal Polytechnic, Bagalkot, Karnataka",
      "V.p. Institute Of Management Studies & Research, Sangli, Maharashtra",
      "Vivekananda Polytechnic, Puttur (dk), Dakshina Kannada, Karnataka",
      "Vivekanand Education Society's Institute Of Management Studies And Research, Mumbai City, Maharashtra",
      "Vaish Technical Institute, Rohtak, Haryana",
      "Vidya Pratisthan's Institute Of Information Technology, Pune, Maharashtra",
      "Vidya Bharati Mahavidyalaya, Amravati",
      "Veer Abhimanyu Polytechnic, Ambala",
      "Vijayalakshmi Polytechnic, Kolar",
      "Vidya Vikas Education Trust Polytechnic, Mysore",
      "Vidyavardhaka Polytechnic, Mysore",
      "Vaikunth Mehta National Institute Of Co-operative Management, Pune",
      "Vinayak College Of Polytechnic, Karnal",
      "Vikramaditya Polytechnic, Rajkot",
      "Vignan Institute Of Technology And Management, Gurgaon",
      "Virangna Jhalkari Bai Govt Girls Polytechnic, Jhansi",
      "Vidhya Bhawan Polytechnic, Udaipur",
      "Veena Institute Of Tech. Edu., (mahila Poly. College) Karauli",
      "Vivekanand Institute Of Technology, Bhilwara",
      "Vikas Polytechnic College, Deeg",
      "Vasavi Polytechnic. ,banaganapally",
      "Vijay Institute Of Technology & Science, Nizamabad",
      "Vkr & Vnb Polytechnic, gudiwada",
      "Vagdevi College Of Pharmacy An Research Center, mukthar",
      "Vrs & Yrn College Of Engineering & Technology, chirala",
      "Vikas Polytechnic College, vissannapeta",
      "Vidarbha Youth Welfare Society Polytechnic, Amravati",
      "Vidarbha Rural Reconstruction Foundation, Yavatmal",
      "Visakha Institute Of Diploma Pharmacy, Visakhapatnam",
      "Vivekanand Polytechnic College Rajota",
      "Vasant Polytechnic College, Beed",
      "Vivekananda Polytechnic College, Neyveli",
      "Vigneshwara Polytechnic College, Kurinjipadi",
      "Vriddhi Polytechnic College, Jaipur",
      "Varadharajan Polytechnic College, Perambalur",
      "Vishwabharati Polytechnic Institute, Nanded",
      "Vamanrao Ithape Polytechnic, Velhale, Ahmednagar, Maharashtra",
      "Vetaleshwar Shikshan Sanstha's Rajiv Gandhi Institute Of Polytechnic, Latur, Maharashtra",
      "Vilasrao Deshmukh Foundations School Of Polytechnic, Latur, Maharashtra",
      "V.j.shinde Polytechnic Institute, Osmanabad, Maharashtra",
      "Vivekanand Institute Of Polytechnic, Aurangabad, Maharashtra",
      "Vashisth Polytechnic College, Suratgarh, Rajasthan",
      "Vivekanand Education Society Polytechnic, Mumbai City, Maharashtra",
      "Vidya Prasarak Mandal Polytechnic, Thane, Maharashtra",
      "Vidyavardhini's Bhausaheb Vartak Polytechnic, Thane, Maharashtra",
      "Vidyalankar Polytechnic, Mumbai City, Maharashtra",
      "Venkateswara Polytechnic College, Pudukkottai, Tamil Nadu",
      "Vivekanand Polytechnic College, Hanumangarh, Rajasthan",
      "V.d. Polytechnic College, Laxmangarh, Sikar, Rajasthan",
      "Vidya Vikas Pratishthan Polytechnic, Solapur, Maharashtra",
      "Vidya Pratishthan's Polytechnic College Indapur, Pune, Maharashtra",
      "Valliammai Polytechnic College, Chengalpattu, Kanchipuram, Tamil Nadu",
      "Vivekananda Polytechnic College, Kanyakumari, Tamil Nadu",
      "Venkatramana Polytechnic College, Karur, Tamil Nadu",
      "Vsv Nadar Polytechnic College, Virudhunagar, Tamil Nadu",
      "Vickram Polytechnic College, Sivaganga, Tamil Nadu",
      "Vivekananda Polytechnic College, Sivaganga, Tamil Nadu",
      "Voice Of God Polytechnic College, Namakkal, Tamil Nadu",
      "Vairamani Ramasasmy Polytechnic College, Thanjavur, Tamil Nadu",
      "Vandayar Polytechnic College, Thanjavur, Tamil Nadu",
      "V J P Catering And Hotel Management, Tiruchirappalli, Tamil Nadu",
      "V.j.p. Polytechnic College, Tiruchirappalli, Tamil Nadu",
      "Vetri Vinayaha Polytechnic College, Tiruchirappalli, Tamil Nadu",
      "V K P Polytechnic College, Tirunelveli, Tamil Nadu",
      "V Ramakrishna Polytechnic College, Tiruvallur, Tamil Nadu",
      "Vel Tech, Tiruvallur, Tamil Nadu",
      "Vethathiri Maharishi Inatitude Of Technology, Tiruvallur, Tamil Nadu",
      "Vandavasi Polytechnic College, Tiruvannamalai, Tamil Nadu",
      "Vignesh Polytechnic College, Tiruvannamalai, Tamil Nadu",
      "Vaani Polytechnic College, Vellore, Tamil Nadu",
      "Vellore Polytechnic College, Vellore, Tamil Nadu",
      "V S V Nadar Polytechnic College, Virudhunagar, Tamil Nadu",
      "Vaish College Of Engineering, Rohtak, Haryana",
      "Vogue Institute Of Fashion Technology, Bangalore, Karnataka",
      "Vismayam College Of Art And Media, Kozhikode, Kerala",
    ],
  },
];
