const FData = [
  {
    colleges: [
      "F D Arts And Commerce College For Women,  - Gujarat",
      "F H W Training Centre , Kenderapara, KENDRAPARA - Orissa",
      "F I College Of Nursing,Lucknow, LUCKNOW - Uttar Pradesh",
      "F X Polytechnic College,  - Tamil Nadu",
      "F. Education Societys Girls College,  - Maharashtra",
      "F.A. Ahmed College, KAMRUP - Assam",
      "F.A.A.Government Degree (Pg) College,  - Uttar Pradesh",
      "F.M. College,  - Orissa",
      "F.S. College Of Education,  - Uttar Pradesh",
      "F.S.COLLEGE OF EDUCATION,  - Uttar Pradesh",
      "FACULTY & DEPARTMENT OF EDUCATION,  - Uttar Pradesh",
      "Faculty Of Agriculrtal Engineering,  - West Bengal",
      "Faculty of Allied Health Science, SALEM - Tamil Nadu",
      "Faculty of Dental Sciences, IMS BHU, VARANASI - Uttar Pradesh",
      "Faculty of Dental Sciences, Institute of Medical Sciences, Varanasi, VARANASI - Uttar Pradesh",
      "Faculty of Dental Sciences, Lucknow, LUCKNOW - Uttar Pradesh",
      "Faculty of Dentistry, Jamia Millia Islamia, Delhi, DELHI - Delhi",
      "FACULTY OF EDUCATION,  - Uttar Pradesh",
      "FACULTY OF EDUCATION,  - Uttar Pradesh",
      "FACULTY OF EDUCATION,  - Uttar Pradesh",
      "FACULTY OF EDUCATION & ALLIED SCIENCE,  - Uttar Pradesh",
      "Faculty of Engineering and Technology, DELHI - Delhi",
      "Faculty of Engineering and Technology Uttra Pradesh, AGRA - Uttar Pradesh",
      "Faculty of Law,  - Bihar",
      "FACULTY OF MANAGEMENT,  - Uttar Pradesh",
      "FACULTY OF MANAGEMENT,  - Gujarat",
      "FACULTY OF MANAGEMENT STUDIES,  - Rajasthan",
      "FACULTY OF MANAGEMENT STUDIES,  - Madhya Pradesh",
      "FACULTY OF MANAGEMENT STUDIES, UNIVERSITY INSTITUTE OF MANAGEMENT, JABALPUR - Madhya Pradesh",
      "FACULTY OF MANAGEMENT STUDIES, UNIVERSITY OF DELHI, DELHI - Delhi",
      "Faculty of Pharmacy Integral University, Lucknow - Uttar Pradesh",
      "Faculty of Pharmacy, JamiaHamdard - Delhi",
      "Faculty of Technology & Engineering - Gujarat",
      "Fae - Uttar Pradesh",
      "Faith India - Kerala",
      "Faith Institute Of Nursing Sciences, Bangalore - Karnataka",
      "Faith Institute Of Nursing Sciences, Bangalore - Karnataka",
      "FAIZ-E-AAM MODERN DEGREE COLLEGE - Uttar Pradesh",
      "Faiz-E-Am Degree College - Uttar Pradesh",
      "FAIZUL ULOOM TEACHERS TRAINING INSTITUTE - Karnataka",
      "Fakhruddin Ali Ahmed Medical College - Assam",
      "Fakir Chand College - West Bengal",
      "Fakir Chand College (B.Ed.Section) - West Bengal",
      "Fakir Moham University - Orissa",
      "Fakiragram College - Assam",
      "Falakata B.Ed. College - West Bengal",
      "Falakata College - West Bengal",
      "Falakata Polytechnic - West Bengal",
      "Falcon Aircraft Maintenance Engineers Institue - Uttar Pradesh",
      "FALGUNRAO PATIL PATOLE B.ED. COLLEGE - Maharashtra",
      "FAMITHA GIRLS TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Farah College of Engineering & Technology - Andhra Pradesh",
      "Farah Institute Of Computer Sciences - Andhra Pradesh",
      "Faran College Of Nursing, Bangalore - Karnataka",
      "Faran School Of Nursing, Bangalore - Karnataka",
      "Farida Iqbal School Of Nursing, Lucknow - Uttar Pradesh",
      "Faridabad Institute of Technology - Haryana",
      "Farook College - Kerala",
      "Farook College, Kozhikode - Kerala",
      "FAROOK EDUCATIONAL SOCIETY - Kerala",
      "FAROOK INSTITUTE OF MANAGEMENT STUDIES, KOZHIKODE - Kerala",
      "Farook Training College, KOZHIKODE - Kerala",
      "FAROOK TRAINING COLLEGE, KOZHIKODE - Kerala",
      "Farooqia College of Pharmacy , MYSORE, MYSORE - Karnataka",
      "Farooqia Dental College & Hospital, Mysore, MYSORE - Karnataka",
      "Farooqia Polytechnic For Women, Mysore, MYSORE - Karnataka",
      "FAROOQIA TEACHER TRAINING INSTITUTE FOR WOMEN, MYSORE - Karnataka",
      "Fateh Chand College for Women, - Haryana",
      "Father Agnel Polytechnic, - Delhi",
      "Father Agnel Technical College, - Maharashtra",
      "Father Mathews College Of Nursing,Bangalore, BANGALORE - Karnataka",
      "Father Muller College, - Karnataka",
      "Father Muller Homoeopathic Medical College & Hospital, MANGALORE - Karnataka",
      "Father Muller'S Institute of Medical Education And Research, Mangalore, MANGALORE - Karnataka",
      "Father Mullers Institue of Medical Education and Research, Mangalore, MANGALORE - Karnataka",
      "Fathima College of Pharmacy , Kollam, KOLLAM - Kerala",
      "Fathima Institute of Medical Sciences, - Andhra Pradesh",
      "Fathima Institute Of Nursing,Kadapa, KARAPA - Andhra Pradesh",
      "FATHIMA MEMORIAL TRAINING COLLEGE, - Kerala",
      "Fathima Michael College of Engineering and Technology, - Tamil Nadu",
      "Fathima School Of Nursing,Calicut, CALICUT - Kerala",
      "FATHIMA TEACHER TRAINING INSTITUTE FOR WOMEN, - Karnataka",
      "Fatima College, MADURAI - Tamil Nadu",
      "Fatima Hospital School Of Nursing , Lucknow, LUCKNOW - Uttar Pradesh",
      "Fatima Hospital, School Of Nursing, Mau, - Uttar Pradesh",
      "Fatima Institute Of Medical Sciences , Gorakhpur, GORAKHPUR - Uttar Pradesh",
      "Fatima Mata Mission Hospital,Wayanad, WAYANAD - Kerala",
      "Fatima Mata National College, KOLLAM - Kerala",
      "Fatima School Of Nursing , Cuddapah, CUDDAPAH - Andhra Pradesh",
      "FATIMA TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "FAZFARI TEACHERS TRAINING INSTITUTE, Kerala - Kerala",
      "Fazl Ali College, Nagaland - Nagaland",
      "Federal College Of Nursing,Bangalore, Bangalore - Karnataka",
      "Federal Institute of Science and Technology, Ernakulam - Kerala",
      "FEDERAL PRIMARY TEACHE TRAINING CENTRE, Karnataka - Karnataka",
      "Fellowship Mission Hospital, School Of Nursing,Pathanamthitta, Pathanamthitta - Kerala",
      "Fellowship School Of Nursing,Mahasamund, Mahasamund - Chhattisgarh",
      "Female Health Supervisors Trg. Sch. , Idukki, Idukki - Kerala",
      "Female Health Training Centre , Balaghat, Balaghat - Madhya Pradesh",
      "Female Health Worker Training Center,Jashpur, Jashpur - Chhattisgarh",
      "Female Health Worker Training Centre , Jhabua, Jhabua - Madhya Pradesh",
      "Female Health Worker Training Centre , Mandla, Mandla - Madhya Pradesh",
      "Female Health Worker Training Centre,Dhamtari, Dhamtari - Chhattisgarh",
      "Female Health Worker Training Centre,Rajnandgaon, Rajnandgaon - Chhattisgarh",
      "Female Health Worker Training School , Shillong, Shillong - Meghalaya",
      "Female Health Workers Training Center,,Udaipur, Udaipur - Rajasthan",
      "Ferguson Degree College, Hyderabad - Andhra Pradesh",
      "Fergusson College, Maharashtra - Maharashtra",
      "FERGUSSON COLLEGE PG CENTRE, Hyderabad - Andhra Pradesh",
      "Fernandez School Of Nursing , Hyderabad, Hyderabad - Andhra Pradesh",
      "Fernandez School Of Nursing , Rangareddy, Rangareddy - Andhra Pradesh",
      "Feroz Gandhi Institute Of Engineering & Technology, Uttar Pradesh - Uttar Pradesh",
      "Feroze Gandhi Degree (PG) College, Uttar Pradesh - Uttar Pradesh",
      "Feroze Gandhi Memorial Govt College, Haryana - Haryana",
      "Fhw Anm Training School , Amreli, Amreli - Gujarat",
      "Fhw Anm Training School , Dahod, Dahod - Gujarat",
      "Fhw Anm Training School , Surendranagar, Surendranagar - Gujarat",
      "Field Marshal K M Kariappa College, Karnataka - Karnataka",
      "Film And T.V. Institute Of Tamilnadu, Coimbatore - Tamil Nadu",
      "Finolex Academy of Management and Technology, Mirjole - Maharashtra",
      "FIROZ GANDHI COLLEGE, Uttar Pradesh - State",
      "Firoz Gandhi Poly., Raibareily, Uttar Pradesh - State",
      "Firozabad School Of Nursing , Firozabad, Uttar Pradesh - State",
      "First aid & CPR training, Delhi - State",
      "First Grade College Arts science Commerce, Karnataka - State",
      "First Grade College K G F, Karnataka - State",
      "First Grade College K G F, Karnataka - State",
      "Flaiz Memorial Adventist College, Narsapur, Andhra Pradesh - State",
      "FLORA TEACHER S TRAINING COLLEGE, Karnataka - State",
      "Florence College Of Nursing , Bangalore, Karnataka - State",
      "FLORENCE ENGLISH INSTITUTION, Karnataka - State",
      "Florence Nightangle School Of General Nursing , & Paramedical Sciences,Shahajahanpur, Uttar Pradesh - State",
      "Florence Nightingale Anm female Health Worker Trg Sch , Koraput, Orissa - State",
      "Florence Nightingale Cn & Research Centre , Gwalior, Madhya Pradesh - State",
      "Florence Nightingale College Of Nursing , Gwalior, Madhya Pradesh - State",
      "Florence Nightingale College Of Nursing,Krishna, Andhra Pradesh - State",
      "Florence Nightingale College Of Nursing,Shahjahanpur, Uttar Pradesh - State",
      "Florence Nightingale Inst Of Nursing , Edu. Mumbai, Maharashtra - State",
      "Florence Nightingale Modern Degree College For Women,Kadapa, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing , Bidar, Karnataka - State",
      "Florence Nightingale School Of Nursing , East Godawari, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing , Gulbarga, Karnataka - State",
      "Florence Nightingale School Of Nursing , Gwalior, Madhya Pradesh - State",
      "Florence Nightingale School Of Nursing , Kakinada, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing , Rajam, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing , Srikakulam, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing , Tiruvannamalai, Tamil Nadu - State",
      "Florence Nightingale School Of Nursing , Vijayawada, Andhra Pradesh - State",
      "Florence Nightingale School Of Nursing,Rajasthan, Rajasthan - State",
      "Florence Nightingale Training College Of Nursing, Wardha, Maharashtra",
      "Florence Nightingle Nursing Schoo,Rajapeth Araravati, Maharashtra",
      "Florence Nursing College,Kota, Rajasthan",
      "Florence Polytechnic, Delhi",
      "Florence School & College Of Nursing , Faridabad, Haryana",
      "Florence School Of Nursing , Faridabad, Haryana",
      "Florence School Of Nursing , Ranchi, Jharkhand",
      "Florence Schoolof Nursing,Kolhapur, Maharashtra",
      "Florida College Of Nursing,Bangalore, Karnataka",
      "Florida School Of Nursing , Bangalore, Karnataka",
      "Food Craft Institute,Visakhapatnam, Andhra Pradesh",
      "Forbesganj College, Bihar",
      "FORE SCHOOL OF MANAGEMENT, Delhi",
      "Forensic Science Laboratory, Chennai, Tamil Nadu",
      "Forensic Science Laboratory, Tamil Nadu",
      "FOREST COLLEGE AND RESEARCH INSTITUTE,METTUPALAYAM, Tamil Nadu",
      "Forest Research Institute, Uttaranchal",
      "FORTE INSTITUTE OF TECHNOLOGY, Uttar Pradesh",
      "FORTE INSTITUTE OF TECHNOLOGY, Uttar Pradesh",
      "Forte Institute of Technology, Uttar Pradesh",
      "Fortis Institute Of Nursing , Mumbai, Maharashtra",
      "Fortis Institutte Of Nursing , Bangalore, Karnataka",
      "Fortis School Of Nursing , Mohali, Punjab",
      "FORTUNE INSTITUTE OF INTERNATIONAL BUSINESS, Delhi",
      "Foster Development Homoeopathic Medical College, Aurangabad, Maharashtra",
      "FOSTER DEVELOPMENTS COLLEGE OF EDUCATION, Maharashtra",
      "Foundation for ACtion Motivation & Empowerment(F.A.M.E., India), Bangalore, Karnataka",
      "Fr Agnel College Of Arts And Commerce, Goa",
      "Fr Mullers College Of Nursing , Mangalore, Karnataka",
      "Fr Mullers College Of Nursing , Mangalore, Karnataka",
      "Fr Mullers College Of Nursing, Mangalore - Karnataka",
      "Fr. Agnel Ashram, Verna - Goa",
      "Fr. Conceicao Rodrigues College of Engineering, Mumbai - Maharashtra",
      "FR. CONCEICAO RODRIGUES INSTITUTE OF MANAGEMENT STUDIES, Thane - Maharashtra",
      "Fr. Heyer College, Guntur - Andhra Pradesh",
      "Fr. Muller Medical College Hospital, Mangalore - Karnataka",
      "Frances Newton Hospital, Firozpur Cantt - Punjab",
      "Francis Xavier Engineering College - Tamil Nadu",
      "FRANK COLLEGE OF EDUCATION - Karnataka",
      "Frank College Of Nursing, Bangalore - Karnataka",
      "Friends Cultural Educational Society, Sri Venkateswara C.K. Institute of Pharmacy, Bangalore - Karnataka",
      "FS Aviation Academy - Kerala",
      "FS College - Kerala",
      "FS College Of Advances Studies - Kerala",
      "FS School Of Fashion - Kerala",
      "Fulera Polytechnic College, Fulera - Rajasthan",
      "FUTURE BUSINESS SCHOOL - West Bengal",
      "FUTURE GROUP OF COLLEGES - Jharkhand",
      "Future Institute of Engineering & Management, Kolkata - West Bengal",
      "Future Institute of Management & Technology, Bareilly - Uttar Pradesh",
    ],
  },
];
