const IData = [
  {
    colleges: [
      "I B College - Haryana",
      "I C Institute Of Women Health Worker , Gwalior - Madhya Pradesh",
      "I D S G Govt College - Karnataka",
      "I E T School Of Nursing,Jaunpur - Uttar Pradesh",
      "I G E S Institue Of Nursing And Health Sciences , Jammu Tawai - Jammu and Kashmir",
      "I G E S Institute Of Nursing And Health Sciences , Jammu - Jammu and Kashmir",
      "I G Govt College - Haryana",
      "I G Mahila Mahavidyalaya - Haryana",
      "I G National College - Haryana",
      "I H M Hospital, School Of Nursing,Kottayam - Kerala",
      "I I M T College Of Medical Science, School Of Nursing , Meerut - Uttar Pradesh",
      "I I M T College Of Medical Sciences,Meerut - Uttar Pradesh",
      "I I M T School Of Nursing, , Agra - Uttar Pradesh",
      "I I M T School Of Nursing,Agra - Uttar Pradesh",
      "I I T S Collegeschool Of Nursing,Guna - Madhya Pradesh",
      "I I T S School Of Nursing , Guna - Madhya Pradesh",
      "I L S Nursing Institute , Agartala - Tripura",
      "I L S Nursing Institute , behind Central School, Agartala - Tripura",
      "I R Polytechnic, Bangalore -",
      "I R T School Of Nursing , Erode - Tamil Nadu",
      "I. E. R. T. Allahabad - Uttar Pradesh",
      "I. I. M. T. Law College - Uttar Pradesh",
      "I. L. S. Law College - Maharashtra",
      "I. M. E. Law College - Uttar Pradesh",
      "I. M. Nanavati Law College - Gujrat",
      "I. M. S. Law College - Uttar Pradesh",
      "I. P. E. M. Law Academy - Uttar Pradesh",
      "I.A.M.R. Law College - Uttar Pradesh",
      "I.B WOMEN TEACHER TRAINING COLLEGE & MANAGEMENT - Haryana",
      "I.C.N.A.S. College - Kerala",
      "I.C.V. Polytechnic, Jhargram - West Bengal",
      "I.E.S. TEACHERS TRAINING COLLEGE - Karnataka",
      "I.G.M. TEACHER TRAINING COLLEGE - Rajasthan",
      "I.H.R.D. College Of Applied Sciences - Kerala",
      "I.H.R.D. College Of Applied Sciences, Mavelikara - Kerala",
      "I.I.L.M ACADEMY OF HIGHER LEARNING - Uttar Pradesh",
      "I.I.L.M ACADEMY OF HIGHER LEARNING JAIPUR - Rajasthan",
      "I.I.M.T College of Medical Sciences - Uttar Pradesh",
      "I.I.M.T College of Science and Technology - Uttar Pradesh",
      "I.I.M.T Engineering College - Uttar Pradesh",
      "I.I.M.T Law College - Uttar Pradesh",
      "I.I.M.T. COLLEGE OF EDUCATION - Uttar Pradesh",
      "I.I.M.T. Law College - Uttar Pradesh",
      "I.L.S. Law College - Maharashtra",
      "I.M. Nanawati Law College - Gujarat",
      "I.M.E. Law College - Uttar Pradesh",
      "I.M.P.S. Degree College - Orissa",
      "I.M.S. Law College - Uttar Pradesh",
      "I.P. Degree College - Uttar Pradesh",
      "I.P. POST GRADUAT COLLEGE - Uttar Pradesh",
      "I.P. TEACHER TRAINING COLLEGE - Haryana",
      "I.P.E.M. Law Academy - Uttar Pradesh",
      "I.P.S. Law College - Uttar Pradesh",
      "I.P.S.E. TEACHER TRAINING COLLEGE - Haryana",
      "I.S.M. ACADEMY - Uttar Pradesh",
      "I.S.S. COLLEGE OF TEACHER EDUCATION - Kerala",
      "I.T.M. College Of Arts & Science - Kerala",
      "I.T.S. Centre for Dental Studies & Research , Ghaziabad - Uttar Pradesh",
      "I.T.S. Dental College Hospital & Research Center - Uttar Pradesh",
      "I.T.S. Dental College, Hospital & Research Centre , Noida - Uttar Pradesh",
      "I.T.S. Law College - Uttar Pradesh",
      "I.V.N. Raju Degree College, Vizianagaram - Andhra Pradesh",
      "IASAM Academy - Delhi",
      "IASE - Uttar Pradesh",
      "Ibrahimpatnam Degree College - Andhra Pradesh",
      "IBT College of Diploma Engineering - Chhattisgarh",
      "ICAR Research Complex for Eastern Region including Centre of Makhana, Patna - Bihar",
      "ICAR Research Complex Goa - Goa",
      "ICARE Institute of Medical Sciences & Research, Haldia, Purba Midanpore - West Bengal",
      "ICFAI College of Education - Tripura",
      "ICFAI Law School - Uttaranchal",
      "ICFAI UNIVERSITY - Tripura",
      "ICFAI University - Rajasthan",
      "ICFAI University - Chhattisgarh",
      "ICG INSTITUTE OF EDUCATIONAL RESEARCH & DEVELOPMENT - Rajasthan",
      "ICHALKARANJI SHIKSHAN SHASTRA MAHAVIDYALAYA - Maharashtra",
      "ICL Institute of Hotel Management and Catering Technology - Haryana",
      "ICL INSTITUTE OF MGT. & TECH - Haryana",
      "ICL Institute of Technical Education - Haryana",
      "ICS INFOTECH - Delhi",
      "Idar Ajana Patidar H K M Arts College P N Patel Commerce College - Gujarat",
      "Ideal And Sri Krishna Chaitanya Memorial Degree College - Andhra Pradesh",
      "Ideal Business School - Uttaranchal",
      "Ideal College Arts Science - Andhra Pradesh",
      "Ideal College Of Arts & Science - Andhra Pradesh",
      "IDEAL COLLEGE OF EDUCATION - Uttar Pradesh",
      "Ideal College of Pharmacy , Thane - Maharashtra",
      "IDEAL D.ED COLLEGE - Karnataka",
      "Ideal Degree College For Women - Andhra Pradesh",
      "IDEAL EDUCATIONAL INSTITUTE OF TEACHER TRAINING - Kerala",
      "IDEAL EDUCATIONAL SOCIETY TRAINING COLLEGE - Kerala",
      "Ideal Girls College - Manipur",
      "Ideal Institute of Hotel Management - Rajasthan",
      "IDEAL INSTITUTE OF MANAGEMENT & TECHNOLOGY - Delhi",
      "Ideal Institute of Management and Technology - Delhi",
      "Ideal Institute of Technology - Uttar Pradesh",
      "Ideal Institute of Technology - Madhya Pradesh",
      "Ideal Nursing ranm School,Sindhudurg - Maharashtra",
      "IDEAL PUBLIC SHIKSHA SANSTHAN - Rajasthan",
      "Ideal School of Engineering & Polytecnic - Orissa",
      "IDEAL TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "IDEAL TRAINING COLLEGE EDUCATION - Kerala",
      "Ideals International College of Management - Rajasthan",
      "Ideas Nursing College , Gwalior - Madhya Pradesh",
      "Idhaya College Of Arts & Scence For Women - Pondicherry",
      "Idhaya College Of Arts And Science For Women - Tamil Nadu",
      "Idhaya Engineering College for Women - Tamil Nadu",
      "Idhaya Womens College, Sarugani - Tamil Nadu",
      "IDHAYAAM COLLEGE OF EDUCATION - Tamil Nadu",
      "Idhayam Womens College - Tamil Nadu",
      "iDreamMBA - Karnataka",
      "IDSG Governement College - Karnataka",
      "IEC College of Engineering & Technology - Uttar Pradesh",
      "IEC Group of Institution - Uttar Pradesh",
      "IEIBS (India Europe International Business School) - Maharashtra",
      "IERCEM Institute of Information Technology - West Bengal",
      "IES COLLEGE OF EDUCATION - Madhya Pradesh",
      "IES College of Engineering - Kerala",
      "IES College of Technology - Madhya Pradesh",
      "IES College of Technology - Madhya Pradesh",
      "IES Institute of Pharmacy - Madhya Pradesh",
      "IES Management College and Research Centre - Maharashtra",
      "IET Bhaddal Technical Campus - Punjab",
      "IFER TEACHER TRAINING INSTITUTE - Kerala",
      "IFET College of Engineering - Tamil Nadu",
      "IFTM University - Uttar Pradesh",
      "IGM B.STC SCHOOL - Rajasthan",
      "IGM BSTC SCHOOL - Rajasthan",
      "Iha Delhi - Delhi",
      "IHM, Ahmedabad - Gujarat",
      "IHM, Aurangabad (Taj Group) - Maharashtra",
      "IHM, Bangalore - Karnataka",
      "IHM, Chennai - Tamil Nadu",
      "IHM, Delhi - Delhi",
      "IHM, Hyderabad - Andhra Pradesh",
      "IHM, Kolkata - West Bengal",
      "IHM, Lucknow - Uttar Pradesh",
      "IIAS School of Management - Goa",
      "IIHMR University - Rajasthan",
      "IIMT Hotel Management College - Uttar Pradesh",
      "IIPM-SCHOOL OF MANAGEMENT - Orissa",
      "IIS University - Rajasthan",
      "IITT College of Engineering and Technology - Himachal Pradesh",
      "IITT College of Engineering and Technology Punjab - Punjab",
      "Ikon Nursing College , Ramanagar - Karnataka",
      "Ikon Nursing College , Ramanagar - Karnataka",
      "Ikon Nursing School , Bangalore Rural - Karnataka",
      "ILAHIA College of Engineering & Technology - Kerala",
      "Ilahiya Arts & Science College - Kerala",
      "ILAKKIYA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Illahia College of Arts and Science - Kerala",
      "ILS Law College - Maharashtra",
      "ILVA COMMERCE AND SCIENCE COLLEGE - Madhya Pradesh",
      "IM Nanawati Law College - Gujarat",
      "Image Engg. & Technical Institute - Gujarat",
      "Image Madhapur College Of Nursing, Hyderabad - Andhra Pradesh",
      "Image School Of Nursing , Ramachandrapuram - Andhra Pradesh",
      "IMAM COLLEGE OF BUSINESS MANAGEMENT & SCIENCE - Bihar",
      "Imamul Hai Khan Law College - Jharkhand",
      "Imanuel Business School - Andhra Pradesh",
      "Imanul hai Khan Law College - Jharkhand",
      "Imayam College Of Engineering - Tamil Nadu",
      "Imayam College of Information Technology - Tamil Nadu",
      "Imayam Polytechnic College - Tamil Nadu",
      "IMAYAM TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "IME Law College - Uttar Pradesh",
      "Immaculate College - Andhra Pradesh",
      "IMMACULATE COLLEGE FOR WOMENS - Tamil Nadu",
      "IMMACULATE COLLEGE OF EDUCATION FOR WOMEN - Pondicherry",
      "Immaculate Heart Of Mary Hospital, School Of Nursig , Kottayam - Kerala",
      "IMMACULATE PRE PRIMARY TEACHER TRAINING INSTITUTE - Kerala",
      "Immaculate School Of Nursing, , Sivgangai - Tamil Nadu",
      "IMMACULATE TEACHER TRAINING INSTITUTE - Pondicherry",
      "IMMANUEL ARASAR COLLEGE EDUCATION - Tamil Nadu",
      "Immanuel Arasar J J College of Engineering - Tamil Nadu",
      "Immanuel College - Nagaland",
      "IMPACT COLLEGE OF EDUCATION & APPLIED SCIENCES - Karnataka",
      "Impact College Of Engineering And Applied Sciences - Karnataka",
      "IMPACT Polytechnic, Bangalore - Karnataka",
      "IMPACT TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Imperial College of Engineering & Research - Maharashtra",
      "Imperial College Of Nursing,Jaipur - Rajasthan",
      "Imperial Institute of Polytechnic & Tech - Rajasthan",
      "imperial institute of technology and management - Uttar Pradesh",
      "Imperial School Of Nursing ,Jaipur - Rajasthan",
      "Imphal Art College - Manipur",
      "Imphal College - Manipur",
      "IMPS College of Engineering & Technology - West Bengal",
      "IMRAM COLLEGE OF COMPUTER APPLICATION - Andhra Pradesh",
      "Imran Polytechnic - Karnataka",
      "IMS Business School - West Bengal",
      "IMS Engineering College - Uttar Pradesh",
      "IMT COLLEGE OF EDUCATION - Uttar Pradesh",
      "Inder Dev Institute Of Education Of Technology - Uttar Pradesh",
      "Inder Dev Institute of Education of Technology - Uttar Pradesh",
      "Inder Prastha Polytechnic College - Haryana",
      "INDERDEV INSTITUTE OF EDUCATION AND TECHNOLOGY - Uttar Pradesh",
      "INDERPRASTH COLLEGE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "Inderprastha Dental College & Hospital , Ghaziabad - Uttar Pradesh",
      "INDERPRASTHA ENGINEERING COLLEGE - Uttar Pradesh",
      "Index Medical College Hospital & Research Centre, Indore - Madhya Pradesh",
      "Index Medical College Hospital & Research Centre,Indore - Madhya Pradesh",
      "Index Nursing College , Indore - Madhya Pradesh",
      "Index School Of Nursing , Indore - Madhya Pradesh",
      "INDHIRA COLLEGE OF EDUCATION - Tamil Nadu",
      "INDHIRA GANDHI TEACHER TRAININGINSTITUTE - Tamil Nadu",
      "Indhirani College Of Nursing , Ariyur - Pondicherry",
      "India Culture League Societys Motilal Jhunjhunwal - Maharashtra",
      "India International College Of Life Sciences & Technology,Gwalior - Madhya Pradesh",
      "INDIA OVERSEAS COLLEGE FOR EDUCATION - Rajasthan",
      "INDIA PASTA EDUCATION COLLEGE, - Haryana",
      "INDIA PASTA EDUCATION COLLEGE, - Haryana",
      "India Shri Shivaji Memorial Society,s Institute of Information Technology - Maharashtra",
      "Indian Academy College Of Nursing , Bangalore - Karnataka",
      "Indian Academy Degree College - Karnataka",
      "Indian Academy of International Law And Diplomacy - Delhi",
      "INDIAN ACADEMY SCHOOL OF MANAGEMENT STUDIES - Karnataka",
      "Indian Academy School Of Nursing , Bangalore - Karnataka",
      "Indian Aerospace & Engineering College - Maharashtra",
      "Indian Agricultural Research Institute - Delhi",
      "Indian Agricultural Statistical Research Institute, New Delhi - Delhi",
      "INDIAN ANGELS MAHILA TEACHER TRAINING COLLEGE - Rajasthan",
      "INDIAN BITS INSTITUTE OF EDUCATION - Haryana",
      "Indian College Of Arts & Draftmanship - West Bengal",
      "INDIAN COLLEGE OF EDUCATION - Karnataka",
      "INDIAN COLLEGE OF EDUCATION - Tamil Nadu",
      "INDIAN COLLEGE OF EDUCATION FOR WOMEN - Karnataka",
      "Indian College of Engineering - Bihar",
      "Indian College Of Nursing , Bellary - Karnataka",
      "Indian College Of Nursing , Bellary - Karnataka",
      "Indian College Of Nursing ,Mahaboobnagar - Andhra Pradesh",
      "Indian College Of Nursing,Bangalore - Karnataka",
      "INDIAN D.ED INSTITUTE - Karnataka",
      "Indian Educational Trust, School Of Nursing, , Jaunpur - Uttar Pradesh",
      "INDIAN GIRLS TEACHER TRAINING COLLEGE - Rajasthan",
      "Indian Grassland and Fodder Research Institute, Jhansi - Uttar Pradesh",
      "Indian Harvard Arts And Science College - Tamil Nadu",
      "Indian Inst. Of Hotel Management & Culinary Arts - Andhra Pradesh",
      "Indian Institute Management And Commerce - Andhra Pradesh",
      "Indian Institute Of  Technology (IIT), Chennai - Tamil Nadu",
      "Indian Institute of Agricultural Biotechnology, Ranchi - Jharkhand",
      "Indian Institute of Art & Design - Delhi",
      "Indian Institute of Carpet Technology - Uttar Pradesh",
      "Indian Institute of Cerebral Palsy,IICP ( Formerly Spastic Society of Eastern India) - West Bengal",
      "INDIAN INSTITUTE OF COST MANAGEMENT& RESEARCH - Maharashtra",
      "INDIAN INSTITUTE OF EDUCATION,SHIMLA - Himachal Pradesh",
      "Indian Institute of Export Management - Gujarat",
      "Indian Institute of Finance - Uttar Pradesh",
      "Indian Institute Of Foreign Trade - Delhi",
      "Indian Institute of Foreign Trade (IIFT) New Delhi -",
      "INDIAN INSTITUTE OF FOREST MANAGEMENT, BHOPAL - Madhya Pradesh",
      "Indian institute of health education & Research - Bihar",
      "Indian Institute of Horticultural Research, Bangalore - Karnataka",
      "Indian Institute of Information Technology and Management Gwalior - Madhya Pradesh",
      "Indian Institute of Information Technology And Management, Kerala - Kerala",
      "Indian Institute of Information Technology, Allahabad - Uttar Pradesh",
      "Indian Institute of Information Technology, Bangalore - Karnataka",
      "Indian Institute of Information Technology, Design and Manufacturing Jabalpur - Madhya Pradesh",
      "Indian Institute of Information Technology, Jabalpur, - madhya pardesh",
      "Indian Institute of Information Technology,Allahabad - Uttar Pradesh",
      "Indian Institute of Information Technology,Delhi - Delhi",
      "Indian Institute of Learning & Advanced Development - Haryana",
      "Indian Institute of Legal Studies - West Bengal",
      "Indian Institute of Management (IIM), Ahmedabad - Gujarat",
      "Indian Institute of Management (IIM), Bangalore - Karnataka",
      "Indian Institute of Management (IIM), Calcutta - West Bengal",
      "Indian Institute of Management (IIM), Indore - Madhya Pradesh",
      "Indian Institute of Management (IIM), Kashipur - Uttaranchal",
      "Indian Institute of Management (IIM), Kozhikode - Kerala",
      "Indian Institute of Management (IIM), Lucknow - Uttar Pradesh",
      "Indian Institute of Management (IIM), Raipur - Chhattisgarh",
      "Indian Institute of Management (IIM), Ranchi - Jharkhand",
      "Indian Institute of Management (IIM), Rohtak - Haryana",
      "Indian Institute of Management (IIM), Shillong - Meghalaya",
      "Indian Institute of Management (IIM), Tiruchirappalli - Tamil Nadu",
      "Indian Institute of Management (IIM), Udaipur - Rajasthan",
      "Indian Institute of Management and Commerce - Andhra Pradesh",
      "Indian Institute of Management Kozhikode - Kerala",
      "Indian Institute of Natural Resins and Gums, Ranchi - Jharkhand",
      "Indian Institute Of Nursing , Bangalore - Karnataka",
      "Indian Institute Of Nursing , Bellary - Karnataka",
      "Indian Institute Of Nursing , Gulbarga - Karnataka",
      "Indian Institute Of Nursing Science And Research , Jabalpur - Madhya Pradesh",
      "Indian Institute of Pharmacy , Jamshedpur - Jharkhand",
      "INDIAN INSTITUTE OF PLANTATION MGT - Karnataka",
      "Indian Institute of Polytechnic, Asada - Rajasthan",
      "INDIAN INSTITUTE OF PROGRESSIVE STUDIES & DEVELOPMENT - Uttaranchal",
      "Indian Institute of Pulses Research, Kanpur - Uttar Pradesh",
      "Indian Institute Of Science - Karnataka",
      "INDIAN INSTITUTE OF SCIENCE & INFORMATION TECHNOLOGY - Orissa",
      "Indian Institute of Science and Information Technology - Orissa",
      "INDIAN INSTITUTE OF SOCIAL WELFARE & BUSINESS MANAGEMENT, KOLKATA - West Bengal",
      "Indian Institute of Soil Sciences, Bhopal - Madhya Pradesh",
      "Indian Institute of Space Science and Technology - Kerala",
      "Indian Institute of Sugarcane Research, Lucknow - Uttar Pradesh",
      "Indian Institute of Teacher Education - Gujarat",
      "INDIAN INSTITUTE OF TEACHER TRAINING INSTITUTE - Kerala",
      "Indian Institute Of Technical Training , Jammu - Jammu and Kashmir",
      "Indian Institute Of Technology (IIT), Bhubaneswar - Orissa",
      "Indian Institute Of Technology (IIT), Delhi - Delhi",
      "Indian Institute Of Technology (IIT), Gandhinagar - Gujarat",
      "Indian Institute Of Technology (IIT), Guwahati - Assam",
      "Indian Institute Of Technology (IIT), Hyderabad - Andhra Pradesh",
      "Indian Institute Of Technology (IIT), Indore - Madhya Pradesh",
      "Indian Institute Of Technology (IIT), Kanpur - Uttar Pradesh",
      "Indian Institute Of Technology (IIT), Kharagpur - West Bengal",
      "Indian Institute Of Technology (IIT), mandi - Himachal Pradesh",
      "Indian Institute Of Technology (IIT), Mumbai - Maharashtra",
      "Indian Institute Of Technology (IIT), Patna - Bihar",
      "Indian Institute Of Technology (IIT), Punjab - Punjab",
      "Indian Institute Of Technology (IIT), Rajasthan - Rajasthan",
      "Indian Institute Of Technology (IIT), Roorke - Uttarakhand",
      "INDIAN INSTITUTE OF TOURISM AND TRAVEL MANAGEMENT - Delhi",
      "Indian Institute of Vegetable Research, Varanasi - Uttar Pradesh",
      "Indian Law Institute - Delhi",
      "INDIAN MANAGEMENT SCHOOL & RESEARCH CENTER - Maharashtra",
      "Indian Marine Univesity - Tamil Nadu",
      "Indian Medical Institute Of Nursing Training , Jalandhar - Punjab",
      "Indian National Portage Association - Chandigarh",
      "Indian nursing council - Orissa",
      "Indian Oil Corporation Ltd, School Of Nursing ,Digboi - Assam",
      "INDIAN PRIMARY TEACHERS TRAINING COLLEGE - Rajasthan",
      "Indian Red Cross Society M P H W F Trg Inst,West Godawari - Andhra Pradesh",
      "Indian red Cross Societys Mukh Badhir Vidyalaya - Maharashtra",
      "Indian School Of Business & Finance (ISBF) - Delhi",
      "INDIAN SCHOOL OF MINES - Jharkhand",
      "Indian School of Nursing , Bangalore - Karnataka",
      "Indian School Of Nursing , Bidar - Karnataka",
      "Indian School Of Nursing B , Bangalore - Karnataka",
      "Indian School Of Public Relations - Delhi",
      "Indian School of Public Relations - Delhi",
      "Indian Spinal Injuries Centre - Delhi",
      "Indian Statistical Institute - West Bengal",
      "Indian Statistical Institute (ISI), Bangalore - Karnataka",
      "Indian Statistical Institute (ISI), Chennai - Tamil Nadu",
      "Indian Statistical Institute (ISI), Coimbatore - Tamil Nadu",
      "Indian Statistical Institute (ISI), Giridih - Jharkhand",
      "Indian Statistical Institute (ISI), Hyderabad - Andhra Pradesh",
      "Indian Statistical Institute (ISI), Mumbai - Maharashtra",
      "Indian Statistical Institute (ISI), New Delhi - Delhi",
      "Indian Statistical Institute (ISI), Pune - Maharashtra",
      "Indian Statistical Institute (ISI), Vadodora - Gujarat",
      "Indian Statistical Institute(ISI), Kolkata - West Bengal",
      "INDIAN TEACHERS TRAINING COLLEGE - Rajasthan",
      "Indian Veterinary Research Institute - Uttar Pradesh",
      "INDIGENOUS PEOPLE EDUCATIONAL TRUST - Karnataka",
      "Indira A N M Training Centre,Mandya - Karnataka",
      "Indira Bahuddeshiya Shikshan Sanstha College Of Nursing , Buldana - Maharashtra",
      "Indira Bahuuddeshiya Shikshan Sanstha A N M School,Buldana - Maharashtra",
      "Indira Bahuuddeshiya Shikshan Sanstha Dr. Rajendra Gode Polytechnic - Maharashtra",
      "Indira Bahuuddeshiya Shikshan Sanstha School Of Nursing,Buldana - Maharashtra",
      "INDIRA COLLEGE OF EDUCATION - Karnataka",
      "Indira College of Engineering and Management - Maharashtra",
      "Indira College Of Nursing , Thiruvallur - Tamil Nadu",
      "Indira College Of Nursing , Trichy - Tamil Nadu",
      "Indira Education Institute Of Nursing, Udaipur - Rajasthan",
      "Indira Gandhi (Sr) College Cidco - Maharashtra",
      "Indira Gandhi Arts & Commerce College - Maharashtra",
      "Indira Gandhi Arts Science College - Chhattisgarh",
      "INDIRA GANDHI B.ED COLLEGE - Karnataka",
      "INDIRA GANDHI B.ED. MAHAVIDHALYA - Madhya Pradesh",
      "INDIRA GANDHI BALIKA NIKETAN - Rajasthan",
      "Indira Gandhi Balika Niketan College - Rajasthan",
      "Indira Gandhi College For Women - Andhra Pradesh",
      "INDIRA GANDHI COLLEGE OF EDUCATION - Maharashtra",
      "INDIRA GANDHI COLLEGE OF EDUCATION - Tamil Nadu",
      "Indira Gandhi College of Engineering - Madhya Pradesh",
      "Indira Gandhi College Of Engineering & Technology For Women - Tamil Nadu",
      "Indira Gandhi College Of Nursing , Kochi - Kerala",
      "Indira Gandhi College Of Nursing,Bangalore - Karnataka",
      "INDIRA GANDHI COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Indira Gandhi College of Special Education - Tamil Nadu",
      "Indira Gandhi Colleges Of Arts & Science - Pondicherry",
      "Indira Gandhi Cooperative Hospital,Kannur - Kerala",
      "Indira Gandhi Degree College - Uttar Pradesh",
      "INDIRA GANDHI DEGREE COLLEGE - Uttar Pradesh",
      "Indira Gandhi Degree College, Bobbili - Andhra Pradesh",
      "Indira Gandhi Education Institute Of Nursing ,Chittorgarh - Rajasthan",
      "INDIRA GANDHI GIRLS DEGREE - Uttar Pradesh",
      "Indira Gandhi Government College - Arunachal Pradesh",
      "Indira Gandhi Government Degree College - Uttar Pradesh",
      "Indira Gandhi Government Dental College , Jammu - Jammu and Kashmir",
      "Indira Gandhi Govt. Degree College - Uttar Pradesh",
      "Indira Gandhi Govt. General Hospital And Post Graduate Institute - Pondicherry",
      "Indira Gandhi Govt. Polytechnic Mahavidhalaya - Madhya Pradesh",
      "Indira Gandhi Institute of Child Health, Bangalore - Karnataka",
      "Indira Gandhi Institute of Chind Health, Bangalore - Karnataka",
      "INDIRA GANDHI INSTITUTE OF CO-OPERATIVE MANAGEMENT - Uttar Pradesh",
      "Indira Gandhi Institute of Dental Sciences , Kothamangalam - Kerala",
      "Indira Gandhi Institute of Dental Sciences , Pondichery - Pondicherry",
      "Indira Gandhi Institute Of Development Research - Maharashtra",
      "Indira Gandhi Institute Of Medical Sciences - Bihar",
      "Indira Gandhi Institute of Medical Sciences - Bihar",
      "Indira Gandhi Institute of Pharmaceutical Sciences , Bhubaneswar - Orissa",
      "Indira Gandhi Institute Of Science And Technology - Orissa",
      "Indira Gandhi Institute of Science and Technology - Orissa",
      "Indira Gandhi Institute of Technology - Orissa",
      "Indira Gandhi Institute of Technology,Sarang - Orissa",
      "INDIRA GANDHI INSTITUTEOF PHYSICAL EDUCATION - Delhi",
      "Indira Gandhi Jayanthi Womens College - Tamil Nadu",
      "Indira Gandhi Krishi Vishwavidyalaya - Chhattisgarh",
      "Indira Gandhi Medical College - Himachal Pradesh",
      "Indira Gandhi Medical College & Hospital , Trg College Of Nursing, Nagpur - Maharashtra",
      "Indira Gandhi Medical College & Hospital, Nagpur - Maharashtra",
      "Indira Gandhi Medical College & Research Institute, Puducherry - Pondicherry",
      "Indira Gandhi Medical College , Shimla - Himachal Pradesh",
      "Indira Gandhi Memorial Homoeopathic Medical College - Madhya Pradesh",
      "INDIRA GANDHI MEMORIAL TEACHER TRAINING COLLEGE - Rajasthan",
      "INDIRA GANDHI MEMORIAL TEACHER TRAINING COLLEGE - Rajasthan",
      "Indira Gandhi National Open University - Delhi",
      "INDIRA GANDHI NATIONAL OPEN UNIVERSITY - Haryana",
      "Indira Gandhi National Open University , Study Centre, College Of Nursing , Ahmedabad - Gujarat",
      "Indira Gandhi National Open University , Study Centre, College Of Nursing , Hyderabad - Andhra Pradesh",
      "Indira Gandhi National Open University , Study Centre, College Of Nursing , Kanpur - Uttar Pradesh",
      "Indira Gandhi National Open University , Study Centre, Fort College Of Nursing , Bangalore - Karnataka",
      "Indira Gandhi National Open University,S S K M College Of Nursing , Kolkatta - West Bengal",
      "Indira Gandhi National Tribal University - Madhya Pradesh",
      "Indira Gandhi Nursing Institute,Nanded - Maharashtra",
      "Indira Gandhi Nursing School,Ahmednagar - Maharashtra",
      "Indira Gandhi Nursing School,Latur - Maharashtra",
      "Indira Gandhi Nursing School,Nagpur - Maharashtra",
      "Indira Gandhi Nursing School,Osmanabad - Maharashtra",
      "Indira Gandhi Polytechnic College - Tamil Nadu",
      "Indira Gandhi Polytechnic College, Mahe - Pondicherry",
      "Indira Gandhi Polytechnic for Women - Delhi",
      "INDIRA GANDHI POST GRADUATE COLLEGE - Uttar Pradesh",
      "INDIRA GANDHI PRIMARY TEACHER TRAINING CENTE - Karnataka",
      "Indira Gandhi Rajkiya Mahila Mahavidyalaya - Uttar Pradesh",
      "Indira Gandhi Rashtriy Uran Akadamic - Uttar Pradesh",
      "Indira Gandhi School Of Nursing , Chitradurga - Karnataka",
      "Indira Gandhi School Of Nursing, Sultanpur - Uttar Pradesh",
      "Indira Gandhi School Of Nursing,Kochi - Kerala",
      "Indira Gandhi School Of Nursing,Nanded - Maharashtra",
      "INDIRA GANDHI TEACHER TRAINING COLLEGE - Rajasthan",
      "INDIRA GANDHI TEACHERS TRAINING INSTITUTE - Kerala",
      "Indira Gandhi Technological and Medical Science University - Arunachal Pradesh",
      "Indira Gandhi Womens College - Orissa",
      "INDIRA INSTITUTE OF BUSINESS MANAGEMENT - Maharashtra",
      "Indira Institute of Engineering and Technology - Tamil Nadu",
      "Indira Institute of Management - Maharashtra",
      "INDIRA INSTITUTE OF MANAGEMENT AND RESEARCH - Tamil Nadu",
      "Indira Institute Of Technology - Maharashtra",
      "Indira Kala Sangit Vishwavidyalaya - Chhattisgarh",
      "INDIRA KOTE D.P.ED COLLEGE - Karnataka",
      "Indira Mahavidyalaya - Maharashtra",
      "Indira Nursing College , Mangalore - Karnataka",
      "Indira Nursing School , Mangalore - Karnataka",
      "Indira Priyadarshini College of Engineering and Technology For Women - Andhra Pradesh",
      "Indira Priyadarshini College of Law - Karnataka",
      "INDIRA PRIYADARSHINI COLLEGE OF MANAGEMENT - Madhya Pradesh",
      "Indira Priyadarshini College Of Nursing , Kadapa - Andhra Pradesh",
      "Indira Priyadarshini Education Trust Srinivasa College of Pharmacy , Bangalore - Karnataka",
      "Indira Priyadarshini Govt Degree Colleg For Women - Andhra Pradesh",
      "Indira Priyadarshini Law College - Andhra Pradesh",
      "Indira Priyadarshini School of Nursing , Bangalore - Karnataka",
      "Indira Priyadarshini School Of Nursing , Bidar - Karnataka",
      "Indira Priyadarshini School Of Nursing , Tumkur - Karnataka",
      "Indira School Of Nursing, , Thiruvallur - Tamil Nadu",
      "INDIRA SHIKSHAN PRASARAK MANDAL COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Indira Shiva Rao Polytechnic - Karnataka",
      "Indira Smriti Mahavidyalaya - Madhya Pradesh",
      "INDIRA TEACHERS TRAINING INSTITUTE - Karnataka",
      "INDIRA TEACHERS TRAINING INSTITUTE - Tamil Nadu",
      "Indira Womens Degree College - Andhra Pradesh",
      "Indira Womens Degree College, Siddipet - Andhra Pradesh",
      "Indirabai Meghe Mahila Mahavidyalaya - Maharashtra",
      "Indiramma Womens Degree College - Andhra Pradesh",
      "Indirani College Of Nursing , Ariyur - Pondicherry",
      "INDO - AMERICAN INSTITUTE - Rajasthan",
      "Indo American College Of Nursing , Moga - Punjab",
      "Indo American College Of Nursing , Moga - Punjab",
      "Indo American College Of Nursing, Hyderabad - Andhra Pradesh",
      "Indo American Institutions - Andhra Pradesh",
      "Indo American School Of Nursing , Hyderabad - Andhra Pradesh",
      "Indo American School Of Nursing , Moga - Punjab",
      "Indo Asian Academy Degree College - Karnataka",
      "Indo Global College of Engineering - Punjab",
      "INDO GLOBAL TEACHER TRAINING COLLEGE - Punjab",
      "Indo Hiroshima Institute Of Nursing , Patna - Bihar",
      "Indo Soviet Friendship Pharmacy College , Ferozepur - Punjab",
      "INDO UNIVERSAL COLLEGE OF MANAGEMENT AND TECHNOLOGY - Uttar Pradesh",
      "Indo-American College - Tamil Nadu",
      "Indore Christian College - Madhya Pradesh",
      "Indore Christian College - Madhya Pradesh",
      "Indore Institute of Law - Madhya Pradesh",
      "Indore Institute Of Medical Sciences College Of Nursing , Indore - Madhya Pradesh",
      "Indore Institute Of Nursing , Indore - Madhya Pradesh",
      "Indore Institute of Pharmacy , Indore - Madhya Pradesh",
      "Indore Institute of Technology - Madhya Pradesh",
      "INDORE MANAGEMENT INSTITUTE - Madhya Pradesh",
      "Indore Nursing College , Indore - Madhya Pradesh",
      "Indore Nursing School,Indore - Madhya Pradesh",
      "Indore School of Social Work - Madhya Pradesh",
      "Indore Women''s Polytechnic College - Madhya Pradesh",
      "Indore Womens Polytechnic - Madhya Pradesh",
      "IndoSoviet Friendship College of Pharmacy , Ferozepur - Punjab",
      "Indoss Polytechnic For Women - Delhi",
      "INDRA EDUCATIONAL & CHARITABLE TRUST - Karnataka",
      "INDRA GANESAN COLLEGE OF EDUCATION - Tamil Nadu",
      "Indra Ganesan College of Engineering - Tamil Nadu",
      "INDRA PRASTHA COLLEGE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "INDRA PRASTHA COLLEGE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "Indra Priyadarshini College - Madhya Pradesh",
      "Indra Singh B.Ed.Teacher's Training College - Jharkhand",
      "INDRADEV INSTITUTE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "INDRADEV INSTITUTE OF EDUCATION AND TECHNOLOGY - Uttar Pradesh",
      "Indrani Mahavidyalaya - Maharashtra",
      "INDRAPATI MAHAVIDYALAYA - Uttar Pradesh",
      "INDRAPRASTH INSTITUTE OF EDUCATION OF MANAGEMENT - Uttar Pradesh",
      "Indraprasth Institute of Management - Haryana",
      "Indraprasth Nursing College,Gwalior - Madhya Pradesh",
      "Indraprastha College For Women - Delhi",
      "Indraprastha College of Management & Technology - Rajasthan",
      "Indraprastha Engineering College - Uttar Pradesh",
      "INDRAPRASTHA ENGINEERING COLLEGE - Uttar Pradesh",
      "Indraprastha Institute Of Nursing, Jaipur - Rajasthan",
      "INDRAPRASTHA MANAGEMENT & TECHNOLOGY - Delhi",
      "Indraprastha University - Delhi",
      "Indravati Mahavidyalaya (+3) - Orissa",
      "Indrawas Kumari Memorial Degree College - Uttar Pradesh",
      "Indu Management Institute - Gujarat",
      "INDU MEMORIAL TEACHER TRAINING CENTRE - Kerala",
      "Indu Nursing School , Vadodara - Gujarat",
      "INDUKAKA LPCOWALA INSTITUTE OF MANAGEMENT - Gujarat",
      "Indur Institute of Engineering & Technology - Andhra Pradesh",
      "INDUR PG COLLEGE OF BUSINESS MANAGEMENT - Andhra Pradesh",
      "Indus Business Academy - Uttar Pradesh",
      "Indus Business Academy - Karnataka",
      "Indus College of Engineering - Tamil Nadu",
      "Indus College of Engineering Orissa - Orissa",
      "Indus Institute of Engineering & Technology - Gujarat",
      "Indus Institute of Engineering & Technology - Haryana",
      "Indus Institute of Technology and Management - Uttar Pradesh",
      "Indus School of Business Management - Haryana",
      "INDUS School of Engineering - Orissa",
      "INDUS TEACHER TRAINING COLLEGE - Haryana",
      "Indus University - Gujarat",
      "INDUTAI MEMORIAL COLLEGE OF EDUCATION - Maharashtra",
      "INDUTAI MEMORIAL COLLEGE OF EDUCATION - Maharashtra",
      "INDUTAI MEMORIAL COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Indyana Global Technical Campus - Maharashtra",
      "INFANT JESUS COLLEGE - Karnataka",
      "INFANT JESUS COLLEGE OF EDUCATION - Tamil Nadu",
      "Infant Jesus College Of Engineering - Tamil Nadu",
      "Infant Jesus College of Engineering and Technology - Tamil Nadu",
      "INFANT JESUS EDUCATIONAL ACADEMY - Tamil Nadu",
      "Infant Jesus Polytechnic College - Tamil Nadu",
      "Infant Jesus Polytechnic College - Tamil Nadu",
      "INFANT JESUS TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Info Institute Engineering - Tamil Nadu",
      "INFOTECH EDUCAITON SOCEITY - Madhya Pradesh",
      "Ingraham Polytechnic - Uttar Pradesh",
      "INNOCENT HEARTS COLLEGE OF ELEMENTARY TEACHER TRAINING - Punjab",
      "Innocent Hearts Group of Institutions - Punjab",
      "Innova College Of Nursing , Hyderabad - Andhra Pradesh",
      "INNOVATIVE INSTITUTE OF EDUCATIN AND TECHNOLOGY - Uttar Pradesh",
      "Innovative Institute Of Education And Technology - Uttar Pradesh",
      "Innovative Institute of Education and Technology - Uttar Pradesh",
      "Innovative Institute of Law - Uttar Pradesh",
      "Innovative Pharmacy - Uttar Pradesh",
      "Inservice Training School , Nadia - West Bengal",
      "Insight Institute Education And Training - Jammu and Kashmir",
      "INSPIRATION COLLEGE OF TEACHER EDUCATION - Uttaranchal",
      "Inst Of Nursing Edu , Panjim - Goa",
      "Inst Of Nursing Edu Nsg Sch Tiswada,Panjim - Goa",
      "INST. OF MARKETING & MANAGEMENT - Delhi",
      "Institute Aviation Medicine - Karnataka",
      "INSTITUTE COLLEGE OF EDUCATION - Uttar Pradesh",
      "Institute for Communicative & Cognitive Neuro Sciences - Kerala",
      "INSTITUTE FOR FINANCIAL MANAGEMENT AND RESEARCH - Tamil Nadu",
      "Institute for Future Education  Entrepreneurship and Leadership - Maharashtra",
      "INSTITUTE FOR HIGHER EDUCATION - Uttar Pradesh",
      "INSTITUTE FOR INTEGRATED LEARNING IN MANAGEMENT, DELHI - Delhi",
      "Institute for International Management & Technology - Haryana",
      "INSTITUTE FOR MANAGEMENT STUDIES - Uttaranchal",
      "Institute for Special Education, Y.M.C.A - Delhi",
      "INSTITUTE FOR TECHNOLOGY & MANAGEMENT, CHENNAI - Tamil Nadu",
      "INSTITUTE FOR WOMEN - Tamil Nadu",
      "INSTITUTE OF CO-OPERATIVE MANAGEMENT - Madhya Pradesh",
      "INSTITUTE OF HOTEL MANAGEMENT CATERING & NUTRITION - Haryana",
      "INSTITUTE OF ADVANCE STUDIES IN EDUCATION - Chhattisgarh",
      "INSTITUTE OF ADVANCE STUDIES IN EDUCATION - Kerala",
      "Institute of Advanced Computer - Orissa",
      "INSTITUTE OF ADVANCED CTUDIES IN EDUCATION,DEEMED UNIVERSITY - Rajasthan",
      "Institute of Advanced Information Technology and Research - Tamil Nadu",
      "Institute of Advanced Management - West Bengal",
      "institute of advanced nursery teacher training - Uttar Pradesh",
      "Institute Of Advanced Studies  In Education - Tamil Nadu",
      "INSTITUTE OF ADVANCED STUDIES IN EDUCATION - Delhi",
      "INSTITUTE OF ADVANCED STUDIES IN EDUCATION - Rajasthan",
      "INSTITUTE OF ADVANCED STUDIES IN EDUCATION - Uttar Pradesh",
      "Institute of Advanced Studies in Education of Gandhi Vidya Mandir - Rajasthan",
      "Institute of Advanced Studiesin Education - Tripura",
      "INSTITUTE OF ADVANCED STUDY EDUCATION - Tamil Nadu",
      "INSTITUTE OF ADVANCED TECHNOLOGY AND SCIENCE - Madhya Pradesh",
      "Institute of AdvancedScience and Technology - Madhya Pradesh",
      "Institute of Aeronautical Engineering - Andhra Pradesh",
      "Institute of Aerospace Medicine Indian Air Force, Bangalore - Karnataka",
      "Institute Of Applied Medicines & Research - Uttar Pradesh",
      "Institute of Applied Medicines & Research - Uttar Pradesh",
      "Institute of Aviation Medicine - Karnataka",
      "INSTITUTE OF BUSINESS & COMPUTER STUDIES - Orissa",
      "INSTITUTE OF BUSINESS ADMINSTRATION & TRAINING - Orissa",
      "INSTITUTE OF BUSINESS MANAGEMENT - Bihar",
      "Institute of Business Management - Bihar",
      "INSTITUTE OF BUSINESS MANAGEMENT & FASHION TECHNOLOGY - Uttar Pradesh",
      "INSTITUTE OF BUSINESS MANAGEMENT & RESEARCH - Madhya Pradesh",
      "INSTITUTE OF BUSINESS MANAGEMENT & RESEARCH - Maharashtra",
      "INSTITUTE OF BUSINESS MANAGEMENT & RESEARCH - West Bengal",
      "INSTITUTE OF BUSINESS MANAGEMENT & RESEARCH. - Maharashtra",
      "INSTITUTE OF BUSINESS MANAGEMENT & RURAL DEVELOPMENT - Maharashtra",
      "INSTITUTE OF BUSINESS MANAGEMENT & TECHNOLOGY, BANGALORE - Karnataka",
      "INSTITUTE OF BUSINESS MANAGEMENT AND RESEARCH - Maharashtra",
      "INSTITUTE OF BUSINESS MANAGEMENT&amp; FASHION TECHNOLOGY - Uttar Pradesh",
      "INSTITUTE OF BUSINESS MANAGEMENT&amp; FASHION TECHNOLOGY - Uttar Pradesh",
      "Institute of Business Management, Bela - Bihar",
      "INSTITUTE OF BUSINESS MGT. &amp; TECH - Haryana",
      "Institute Of Ceramic Technology - Tamil Nadu",
      "Institute of Chartered Financial Analysis of India University - Tripura",
      "Institute of Chartered Financial Analysts of India (ICFAI) - Uttaranchal",
      "Institute of Chartered Financial Analysts of India University - Sikkim",
      "Institute Of Chemical Technology - Tamil Nadu",
      "Institute of Chemical Technology -",
      "Institute of Child Health, Kolkata - West Bengal",
      "INSTITUTE OF CO OPERATIVE &amp; CORPORATE - Uttar Pradesh",
      "INSTITUTE OF CO-OPERATIVE MANAGEMENT - Uttaranchal",
      "INSTITUTE OF CO-OPERATIVE MANAGEMENT - Tamil Nadu",
      "Institute of Co-operative Management Dehradun - Uttaranchal",
      "INSTITUTE OF COMPUTER AND MANAGEMENT RESEARCH - Maharashtra",
      "INSTITUTE OF COMPUTER SCIENCE &amp; TECHNOLOGY - Uttar Pradesh",
      "Institute of Computer Science &amp; Technology - Uttar Pradesh",
      "INSTITUTE OF COMPUTERS &amp; BUSINESS MANAGEMENT - SCHOOL OF BUSINESS EXCELLENCE - Andhra Pradesh",
      "Institute of Dental Education &amp; Advance Studies IDEAS , Gwalior - Madhya Pradesh",
      "Institute of Dental Sciences , Bareilly - Uttar Pradesh",
      "Institute of Dental Sciences, Bhubaneswar - Orissa",
      "Institute of Dental Sciences, Sehora - Jammu and Kashmir",
      "Institute of Dental Studies &amp; Technology , Modinagar - Uttar Pradesh",
      "INSTITUTE OF EDUCATION - Uttar Pradesh",
      "INSTITUTE OF EDUCATION - Uttar Pradesh",
      "INSTITUTE OF EDUCATION - Uttar Pradesh",
      "Institute of Education - West Bengal",
      "INSTITUTE OF EDUCATION - Tamil Nadu",
      "Institute of Education (PG) for Women - West Bengal",
      "INSTITUTE OF EDUCATION AND MANAGEMENT - Uttar Pradesh",
      "INSTITUTE OF EDUCATION AND MANAGEMENT - Uttar Pradesh",
      "Institute Of Education For Women - West Bengal",
      "Institute of Education for Women - West Bengal",
      "Institute of Educational Research & Studies Primary Teacher's Training Institute - West Bengal",
      "Institute of Engineering - Madhya Pradesh",
      "Institute of Engineering & Industrial Technology - West Bengal",
      "Institute of Engineering and Emerging Technologies - Himachal Pradesh",
      "Institute of Engineering and Rural Technology - Uttar Pradesh",
      "Institute of Engineering for Women - Rajasthan",
      "Institute of Engineering Science - Madhya Pradesh",
      "Institute of Engineering Technology Jaipur - Rajasthan",
      "Institute of Engineering Technology Kerala - Kerala",
      "Institute of Engineering Technology Lucknow - Uttar Pradesh",
      "Institute of Engineering Technology Madhya Pradesh - Madhya Pradesh",
      "Institute of Engineering Technology Punjab - Punjab",
      "Institute of Engineering Technology Rajasthan - Rajasthan",
      "Institute of Engineering Technology Sitapur - Uttar Pradesh",
      "Institute of Environment & Management - Uttar Pradesh",
      "INSTITUTE OF ENVIRONMENT & MANAGEMENT, LUCKNOW - Uttar Pradesh",
      "Institute of Excellence in Higher Education - Madhya Pradesh",
      "INSTITUTE OF EXCELLENCE IN MGT. SCIENCE - Karnataka",
      "INSTITUTE OF FINANCE AND INTERNATIONAL MGT - Karnataka",
      "INSTITUTE OF FINANCIAL MANAGEMENT & RESEARCH, CHENNAI - Tamil Nadu",
      "Institute of Fire & Safety Management - Uttaranchal",
      "INSTITUTE OF FORGEN TRADE AND MANAGEMENT (IFTM) - Uttar Pradesh",
      "Institute Of Health And Social Science , Dakshin Dinajpur - West Bengal",
      "INSTITUTE OF HEALTH MANAGEMENT RESEARCH - Rajasthan",
      "Institute of Health Sciences - Orissa",
      "Institute Of Health Sciences,Greater Noida - Uttar Pradesh",
      "INSTITUTE OF HIGHER EDUCATION - Delhi",
      "INSTITUTE OF HIGHER EDUCATION - Himachal Pradesh",
      "INSTITUTE OF HIGHER EDUCATION - Uttar Pradesh",
      "Institute Of Home Economics, New Delhi - Delhi",
      "Institute of Hotel and Restaurant Management - West Bengal",
      "Institute of Hotel Management - IHM, Aurangabad (Taj Group) -",
      "Institute of Hotel Management and Catering Technology, Bharati Vidyapeeth Deemed University - Maharashtra",
      "Institute Of Hotel Management Catering Nutrition - Punjab",
      "Institute of Human Behaviour & Allied Sciences - Delhi",
      "Institute of Human Behaviour And Allied Sciences, Delhi - Delhi",
      "INSTITUTE OF INFORMATICS & MANAGEMENT SCIENCES - Uttar Pradesh",
      "INSTITUTE OF INFORMATICS AND MANAGEMENT SCIENCE - Uttar Pradesh",
      "INSTITUTE OF INFORMATIES & MANAGEMENT SCIENCE - Uttar Pradesh",
      "INSTITUTE OF INFORMATIES & MANAGEMENT SCIENCE - Uttar Pradesh",
      "INSTITUTE OF INFORMATIES & MANAGEMENT SCIENCE - Uttar Pradesh",
      "INSTITUTE OF INFORMATION & MANAGEMENT SCIENCE - Rajasthan",
      "INSTITUTE OF INFORMATION AND MANAGEMENT SCIENCES - Uttar Pradesh",
      "Institute of Information Management & Technology - Uttar Pradesh",
      "INSTITUTE OF INFORMATION MANAGEMENT AND TECHNOLOGGY - Uttar Pradesh",
      "Institute of Information Technology & Management - Delhi",
      "Institute of Information Technology & Management Gawlior - Madhya Pradesh",
      "Institute of Integral Technology - Uttar Pradesh",
      "Institute of Jute Technology - West Bengal",
      "Institute of Language Research - Madhya Pradesh",
      "Institute of Law - Madhya Pradesh",
      "INSTITUTE OF LAW AND ACADEMIC STUDIES - Uttar Pradesh",
      "Institute of Law and Forensic Science - Gujarat",
      "Institute of Law and Management Studies - Haryana",
      "Institute of Law and Research - Haryana",
      "Institute of LawCh. Charan Singh University - Uttar Pradesh",
      "Institute of Laws - Punjab",
      "Institute Of Leather Technology - Tamil Nadu",
      "Institute Of Leather Technology - Karnataka",
      "Institute of Liver and Biliary Sciences, New Delhi - Delhi",
      "Institute of Management - Chhattisgarh",
      "INSTITUTE OF MANAGEMENT - Chandigarh",
      "INSTITUTE OF MANAGEMENT - Maharashtra",
      "Institute of Management  Research - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT & CAREER COURSES - Maharashtra",
      "INSTITUTE OF MANAGEMENT & CAREER DEVELOPMENT - Maharashtra",
      "INSTITUTE OF MANAGEMENT & COMPUTER STUDIES - Maharashtra",
      "INSTITUTE OF MANAGEMENT & ENTREPRENEURSHIP DEVELOPMENT - Maharashtra",
      "INSTITUTE OF MANAGEMENT & INFORMATION TECHNOLOGY - Orissa",
      "INSTITUTE OF MANAGEMENT & RESEARCH - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT & RURAL DEVELOPMENT ADMINISTRATION - Maharashtra",
      "INSTITUTE OF MANAGEMENT & TECHNOLOGY, - Uttar Pradesh",
      "Institute Of Management &Technology - Haryana",
      "INSTITUTE OF MANAGEMENT AND COMPUTER STUDIES - Maharashtra",
      "Institute of Management and Global Education - Chhattisgarh",
      "Institute of Management and Information Technology - Orissa",
      "Institute of Management and Technology - Kerala",
      "INSTITUTE OF MANAGEMENT DEVELOPMENT & RESEARCH - Maharashtra",
      "INSTITUTE OF MANAGEMENT EDUCATION - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT EDUCATION - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT EDUCATION - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT EDUCATION - Uttar Pradesh",
      "Institute of Management Education - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT EDUCATION & RESEARCH - Maharashtra",
      "INSTITUTE OF MANAGEMENT EDUCATION RESEARCH & TRAINING - Maharashtra",
      "Institute of Management Engineering - West Bengal",
      "INSTITUTE OF MANAGEMENT SCIENCE - Uttar Pradesh",
      "Institute of Management Science, Pmpri - Maharashtra",
      "INSTITUTE OF MANAGEMENT SCIENCES - Jammu and Kashmir",
      "INSTITUTE OF MANAGEMENT STUDIES - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES - Madhya Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES - Uttaranchal",
      "INSTITUTE OF MANAGEMENT STUDIES - Rajasthan",
      "INSTITUTE OF MANAGEMENT STUDIES - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES - Uttaranchal",
      "Institute of Management Studies - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES & RESEARCH - Maharashtra",
      "INSTITUTE OF MANAGEMENT STUDIES AND RESEARCH - Madhya Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES AND RESEARCH - Maharashtra",
      "INSTITUTE OF MANAGEMENT STUDIES, GHAZIABAD - Uttar Pradesh",
      "INSTITUTE OF MANAGEMENT STUDIES, NOIDA - Uttar Pradesh",
      "Institute of Management Studies, Roorkee - Uttaranchal",
      "INSTITUTE OF MANAGEMENT TECHNOLOGY - Uttaranchal",
      "INSTITUTE OF MANAGEMENT TECHNOLOGY - Madhya Pradesh",
      "INSTITUTE OF MANAGEMENT TECHNOLOGY, GHAZIABAD - Uttar Pradesh",
      "Institute of Management Technology, Ghaziabad - Uttar Pradesh",
      "Institute of Management Technology, Nagpur - Maharashtra",
      "Institute of Management, Badnapur - Maharashtra",
      "INSTITUTE OF MARKETING AND MANAGEMENT - Delhi",
      "Institute of Medical Science and Research, Vidyagiri, Satara - Maharashtra",
      "Institute Of Medical Sciences Bhu Varanasi - Uttar Pradesh",
      "Institute of Medical Sciences, Banaras Hindu University , Varanasi - Uttar Pradesh",
      "Institute of Medical Sciences, BHU, Varansi - Uttar Pradesh",
      "Institute Of Medical Technology & Nsg Edu,Jaipur - Rajasthan",
      "Institute Of Medical Technology And Nursing Education , Jaipur - Rajasthan",
      "Institute of Medical Technology Pharmacy College , Puri - Orissa",
      "Institute of Mental Health and Hospital - Uttar Pradesh",
      "Institute Of Mental Health And Hospital ,Agra - Uttar Pradesh",
      "Institute of Mental Health and Hospital, Agra - Uttar Pradesh",
      "INSTITUTE OF MGT. & TECH - Haryana",
      "INSTITUTE OF MGT. STUDIES - Himachal Pradesh",
      "Institute Of Multipurpose female Health Worker Training Centre,Chattisgarh - Chhattisgarh",
      "institute of Music and Fine Arts - Jammu and Kashmir",
      "Institute of Navel Medicine, INHS, Aswini - Maharashtra",
      "Institute of Navel Medicine, Inhs,Aswini, Mumbai - Maharashtra",
      "Institute of Nuclear Medicine & Allied Sciences, New Delhi - Delhi",
      "Institute Of Nursing , Hubli - Karnataka",
      "Institute Of Nursing , Sindudurga - Maharashtra",
      "Institute Of Nursing Education - Maharashtra",
      "Institute Of Nursing Education & Paramedical Sciences , Thane - Maharashtra",
      "Institute Of Nursing Education & Training , Nashik - Maharashtra",
      "Institute Of Nursing Education , Bambolim - Goa",
      "Institute Of Nursing Education , Ernakulam - Kerala",
      "Institute Of Nursing Education , Ernakulum - Kerala",
      "Institute Of Nursing Education , Kottayam - Kerala",
      "Institute Of Nursing Education , Ludhiana - Punjab",
      "Institute Of Nursing Education , Mumbai - Maharashtra",
      "Institute Of Nursing Education , Pathanamthitta - Kerala",
      "Institute Of Nursing Education , School Of Medical Education , Idukki - Kerala",
      "Institute Of Nursing Education ,Guru Teg Bahadur Sahib C Hospital , Ludhiana - Punjab",
      "Institute Of Nursing Education ,Parbani - Maharashtra",
      "Institute Of Nursing Education And Research,Akola - Maharashtra",
      "Institute Of Nursing Education, , Bombay - Maharashtra",
      "Institute Of Nursing Education, School Of Medical Education , Angamaly - Kerala",
      "Institute Of Nursing Education, School Of Medical Education , Ernakulam - Kerala",
      "Institute Of Nursing Education, School Of Medical Education , Kochi - Kerala",
      "Institute Of Nursing Education, School Of Medical Education , Kottayam - Kerala",
      "Institute Of Nursing Education,Bombay - Madhya Pradesh",
      "Institute Of Nursing Education,Parbhani - Maharashtra",
      "Institute Of Nursing Education,Pune - Maharashtra",
      "Institute Of Nursing Education,Sangli - Maharashtra",
      "Institute Of Nursing Science , Agartala - Tripura",
      "Institute Of Nursing Science Studies & Research I N S R , Gwalior - Madhya Pradesh",
      "Institute Of Nursing Science Studies & Research insr , Gwalior - Madhya Pradesh",
      "Institute Of Nursing Science Studies And Research,Gwalior - Madhya Pradesh",
      "Institute Of Nursing Science, ,Tripura West - Tripura",
      "Institute Of Nursing Sciences , Hubli - Karnataka",
      "Institute Of Opthalmology Joseph Eye Hospital, Tiruchirapalli - Tamil Nadu",
      "Institute of Oriental Philosophy - Uttar Pradesh",
      "Institute Of Para Medicla Services,Sitapur - Uttar Pradesh",
      "Institute Of Paramedical & Vocational Education , Sabarkantha - Gujarat",
      "Institute Of Paramedical Sciences, , Sitapur - Uttar Pradesh",
      "Institute Of Paramedical, School Of Nursing , Lucknow - Uttar Pradesh",
      "Institute of Paramedicals , Lucknow - Uttar Pradesh",
      "Institute of People's Science and Technology - Madhya Pradesh",
      "Institute of Pharm Sciences & Technology , Cuttack - Orissa",
      "Institute of Pharm. Sciences , THIRUVANANTHAPURAM - Kerala",
      "Institute of Pharmaceutical Sciences , Srikanthapur - Orissa",
      "Institute of Pharmacy - Chhattisgarh",
      "Institute of Pharmacy & Technology , Salipur - Orissa",
      "Institute of Pharmacy , Bankura - West Bengal",
      "Institute of Pharmacy , Jalpaiguri - West Bengal",
      "Institute of Pharmacy , Jhansi - Uttar Pradesh",
      "Institute of Pharmacy , Kalyani - West Bengal",
      "Institute of Pharmacy , Pune - Maharashtra",
      "Institute of Post Graduate Medical Education - West Bengal",
      "Institute Of Printing Technology - Tamil Nadu",
      "Institute of Printing Technology - Karnataka",
      "Institute of Printing Technology & Govt Polytechnic College - Kerala",
      "INSTITUTE OF PRODUCTIVITY & MANAGEMENT, GHAZIABAD - Uttar Pradesh",
      "INSTITUTE OF PROFESSIONAL EDUCATION AND  RESEARCH - Madhya Pradesh",
      "INSTITUTE OF PROFESSIONAL EXCELLENCE & MANAGEMENT - Uttar Pradesh",
      "INSTITUTE OF PROFESSIONAL EXCELLENCE & MANAGEMENT - Uttar Pradesh",
      "Institute of Professional Excellence & Management - Uttar Pradesh",
      "INSTITUTE OF PROFESSIONAL STUDIES - Madhya Pradesh",
      "INSTITUTE OF PROFESSIONAL STUDIES - Uttar Pradesh",
      "INSTITUTE OF PROFESSIONAL STUDIES - Uttar Pradesh",
      "Institute of Professional Studies - Uttar Pradesh",
      "INSTITUTE OF PROFESSIONAL STUDIES & RESEARCH - Orissa",
      "Institute of Professional Studies and Reserach - Madhya Pradesh",
      "Institute of Professional Studies College of Pharmacy Diploma , Gwalior - Madhya Pradesh",
      "Institute of Professional Textile Technology (IPTT) - Haryana",
      "Institute Of Psychiatry , Kolkata - West Bengal",
      "Institute of Public Enterprise University Campus - Andhra Pradesh",
      "INSTITUTE OF PUBLIC ENTERPRISE, HYDERABAD - Andhra Pradesh",
      "Institute Of Rail Transport - New Delhi - Delhi",
      "Institute of Rehabilitation - Uttar Pradesh",
      "Institute of Rehabilitation Science and Special Education - Tamil Nadu",
      "Institute of Road and Transport Technolog - Tamil Nadu",
      "Institute Of Road Transport Polytechnic College, Chennai - Tamil Nadu",
      "Institute Of Road Transport Polytechnic College, Dharmapuri - Tamil Nadu",
      "Institute Of Road Transport Polytechnic College, Tirunelveli - Tamil Nadu",
      "INSTITUTE OF RURAL MANAGEMENT - Rajasthan",
      "INSTITUTE OF RURAL MANAGEMENT (IIRM) - Rajasthan",
      "INSTITUTE OF RURAL MANAGEMENT, ANAND - Gujarat",
      "Institute of Science - Maharashtra",
      "Institute of Science - Maharashtra",
      "Institute of Science & Management - Jharkhand",
      "INSTITUTE OF SCIENCE & MANAGEMENT, RANCHI - Jharkhand",
      "Institute of Science & Technology Klawad - Haryana",
      "Institute of Science and Technology - Haryana",
      "Institute of Science and Technology - West Bengal",
      "Institute of Science Education - West Bengal",
      "Institute of Science Poona's College of Computer Sciences - Maharashtra",
      "INSTITUTE OF SCIENCE POONAS COLLEGE OF EDUCATION - Maharashtra",
      "Institute of Shipbuilding Technology - Goa",
      "Institute of Solar Technology - West Bengal",
      "INSTITUTE OF TEACHERS EDUCATION - Haryana",
      "INSTITUTE OF TEACHERS EDUCATION - Uttar Pradesh",
      "INSTITUTE OF TECHNICAL EDUCATION & RESEARCH CENTRE - Uttar Pradesh",
      "Institute of Technical Education & Research Centre - Uttar Pradesh",
      "Institute of Technical Education and Research - Orissa",
      "Institute of Technology - Chhattisgarh",
      "INSTITUTE OF TECHNOLOGY - Kerala",
      "Institute of Technology & Management - Uttar Pradesh",
      "Institute of Technology & Management - Uttar Pradesh",
      "Institute of Technology & Management - Maharashtra",
      "Institute of Technology & Marine Engineering - West Bengal",
      "Institute Of Technology (IIT), Varanasi - Uttar Pradesh",
      "INSTITUTE OF TECHNOLOGY AND MANAGEMENT - Maharashtra",
      "Institute Of Technology and Management Bhilwara - Rajasthan",
      "Institute of Technology and Management Gorakhpur - Uttar Pradesh",
      "Institute of Technology and Management Gwalior - Madhya Pradesh",
      "Institute of Technology and Management Haryana - Haryana",
      "Institute of Technology and Management itm - Uttar Pradesh",
      "Institute of Technology and Management Rajasthan - Rajasthan",
      "INSTITUTE OF TECHNOLOGY AND MGT - Karnataka",
      "Institute Of Technology Banaras Hindu University - Uttar Pradesh",
      "Institute Of Technology For Womens University - Maharashtra",
      "Institute of Technology Kobra - Chhattisgarh",
      "Institute of Technology Maharastra - Maharashtra",
      "INSTITUTE OF TECHNOLOGY SCIENCE - Uttar Pradesh",
      "Institute of Technology Science - Uttar Pradesh",
      "Institute of Techonology & Management - Madhya Pradesh",
      "Institute of Textile Technology - Orissa",
      "Institute Of Textile Technology - Tamil Nadu",
      "Institute Of Textile Technology, Bangalore - Karnataka",
      "Institute of Textile Technology,Choudwar - Orissa",
      "Institute Of Tool Engineering - Tamil Nadu",
      "INSTITUTE OF VOCATIONAL STUDIES - Delhi",
      "INSTITUTE.OF ADVANCED STUDIES IN EDUCATION - Uttar Pradesh",
      "INSTITUTION OF PROFESSIONAL STUDIES - Uttar Pradesh",
      "Instt Of Med Tech & Nsg Educ, School Of Nursing,Jaipur - Rajasthan",
      "Instt. of Medical Sciences & Sum Hospital, Bhubaneswar - Orissa",
      "INTECH INSTT.OF BUSINESS MGT - Karnataka",
      "INTEGRAL INSTITUTE FOR ADVANCED MANAGEMENT, VISAKHAPATNAM - Andhra Pradesh",
      "Integral University - Uttar Pradesh",
      "Integrated Academy of Management & Technology - Uttar Pradesh",
      "Integrated Institute for the Disabled - Uttar Pradesh",
      "INTEGRATED SCHOOL OF EDUCATION - Uttar Pradesh",
      "Integrated School of Law, Delhi - Delhi",
      "Intel Degree College - Andhra Pradesh",
      "Intel Engineering College - Andhra Pradesh",
      "intell engineering college - Andhra Pradesh",
      "Intellectual Institute of Technology - Andhra Pradesh",
      "INTERGATED SCHOOL OF EDUCATION - Uttar Pradesh",
      "INTERGRANTED ACADEMY OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "Internatinoal Hospital School Of Nursing , Kamrup - Assam",
      "INTERNATIONAL ACADEMY FOR CREATIVE TEACHING - Karnataka",
      "International Agribusiness Management Institute , Anand - Gujarat",
      "International Auditing College - Tamil Nadu",
      "INTERNATIONAL CENTER COLLEGE OF EDUCATION - Uttar Pradesh",
      "International Center For Excellence in Engineering & Management - Maharashtra",
      "INTERNATIONAL CENTRE FOR DISTANCE EDUCATION & OPEN LEANING - Himachal Pradesh",
      "INTERNATIONAL CENTRE OF COLLEGE - Uttar Pradesh",
      "International College - Bihar",
      "INTERNATIONAL COLLEGE OF EDUCATION - Tamil Nadu",
      "International College Of Nursing , Tarn Taran - Punjab",
      "INTERNATIONAL DIVINE TEACHER TRAINING COLLEGE - Punjab",
      "INTERNATIONAL ENTREPRENEURSHIP & MANAGEMENT PROCESS - Delhi",
      "International Executive Education Center (IEEC) - Chhattisgarh",
      "INTERNATIONAL INST. OF HEALTH MGT. RESEARCH - Delhi",
      "International Institute For Population Science - Maharashtra",
      "INTERNATIONAL INSTITUTE FOR SPECIAL EDUCATION - Uttar Pradesh",
      "International Institute of Aviation & Tourism Management - Uttar Pradesh",
      "International Institute of Fashion Design - West Bengal",
      "International Institute of Fashion Technology - Delhi",
      "International Institute of Health Management Research - Delhi",
      "International Institute Of Hotel Management - ",
      "International Institute Of Information Technology - Andhra Pradesh",
      "International Institute Of Information Technology - Orissa",
      "International Institute of Information Technology - Andhra Pradesh",
      "International Institute of Information Technology - Karnataka",
      "INTERNATIONAL INSTITUTE OF MANAGEMENT SCIENCE - West Bengal",
      "INTERNATIONAL INSTITUTE OF PROFESSIONAL STUDIES - Madhya Pradesh",
      "International Institute of Rehabilitation Sciences & Research - Orissa",
      "INTERNATIONAL MANAGEMENT CENTRE - Delhi",
      "INTERNATIONAL MANAGEMENT INSTITUTE - Delhi",
      "International Management Institute - West Bengal",
      "International Management Institute - Orissa",
      "International Maritime Institute - Uttar Pradesh",
      "International Mphw F Trg Institute,East Godawari - Andhra Pradesh",
      "International Polytechnic for Women - Delhi",
      "International School of Business & Media - Karnataka",
      "INTERNATIONAL SCHOOL OF INFORMATICS & MANAGEMENT - Rajasthan",
      "International School Of Management Studies - Maharashtra",
      "International School Of Nursing , Amritsar - Punjab",
      "International School Of Nursing , Tarn Taran - Punjab",
      "International Women Polytechnic - Delhi",
      "Interscience Institute of Management & Technology, Bhubaneswar - Orissa",
      "INVERTIES INSTITUTE OF MANAGEMENT STUDIES - Uttar Pradesh",
      "Invertis Institute of Management Studies - Uttar Pradesh",
      "Invertis University - Uttar Pradesh",
      "Invertis University, - Uttar Pradesh",
      "Ipcowala Institute Of Engg And Technology - Gujarat",
      "IPJ TEACHER TRAINING COLLEGE - Haryana",
      "IPS ACADEMY - Madhya Pradesh",
      "IPS ACADEMY COLLEGE OF EDUCATION - Madhya Pradesh",
      "IPS College of Technology & Management - Madhya Pradesh",
      "Iqbal College - Kerala",
      "Iqbal Institute of Technology and Management - Jammu and Kashmir",
      "IQBAL TRAINING COLLEGE - Kerala",
      "IQRA EDN SOCIETYS COLLEGE OF EDUCATION - Maharashtra",
      "IRA EDUCATION SOCIETYS COLLEGE OF EDUCATION - Maharashtra",
      "Irengbam Thamcha Devi Nursing And Health Care Res Inst , Imphal - Manipur",
      "Irinjalakuda Cooperative School Of Nursing,Thrissur - Kerala",
      "Irshad Memorial Institute Of Nursing Education,Jaipur - Rajasthan",
      "IRT Polytechnic College - Tamil Nadu",
      "IRT Polytechnic College - Tamil Nadu",
      "IRT Polytechnic College, Bargur - Tamil Nadu",
      "IRUDAYA ANDAVAR TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Isabel Mc Connel School Of Nursing , Jhabua - Madhya Pradesh",
      "Isabella Thouburn College - Uttar Pradesh",
      "ISBR Business School - Karnataka",
      "ISHAN INSTITUTE OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "ISHAN INSTITUTE OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "ISHWAR CHAND VIDYA SAGAR INSTITUTE OF EDUCATION AND RESEARCH - Uttar Pradesh",
      "Ishwar Chand Vidya Sagar Institute of Technology - Uttar Pradesh",
      "Ishwar Chandra Vidyasagar Vidhi Mahavidyalaya - Madhya Pradesh",
      "Ishwar Deshmukh College of Physical Education - Maharashtra",
      "ISHWAR DESHMUKH COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "ISHWAR Institute of Prosthetics & Orthotics - Tamil Nadu",
      "Ishwar Saran Degree College - Uttar Pradesh",
      "Ishwarchand Vidya Sagar Institute of Management - Uttar Pradesh",
      "ISL Women's Engineering College - Andhra Pradesh",
      "Islamia Arts Science College - Andhra Pradesh",
      "Islamia College for Women - Jammu and Kashmir",
      "Islamia College of Commerce - Uttar Pradesh",
      "Islamia College of Law - Uttar Pradesh",
      "ISLAMIA COLLEGE OF SCIENCE & COMMERCE - Jammu and Kashmir",
      "Islamia College of Science & Commerce - Jammu and Kashmir",
      "ISLAMIA DEGREE COLLEGE - Uttar Pradesh",
      "Islamia Degree College For Women - Andhra Pradesh",
      "Islamia Degree College For Women - Andhra Pradesh",
      "Islamia Karimia Degree College - Madhya Pradesh",
      "Islamia Nurses Training Centre , Kolkata - West Bengal",
      "Islamia Teacher Training College(B.Ed.) - Bihar",
      "Islamiah College - Tamil Nadu",
      "Islamiah Institute of Technology - Karnataka",
      "Islamiah Womens Arts And Science College - Tamil Nadu",
      "Islamic University Of Science Technology - Jammu and Kashmir",
      "Islampur College - West Bengal",
      "ISMAIL NATIONAL MAHILA P.G. COLLEGE - Uttar Pradesh",
      "Ismail National Post-graduate College for Women - Uttar Pradesh",
      "Ismail National Postgraduate College For Women - Uttar Pradesh",
      "Ismail Saheb Mulla Law College - Maharashtra",
      "Ismail Yusuf College of Arts Science & Commerce - Maharashtra",
      "Ispat College - Orissa",
      "Itanagar Government College - Arunachal Pradesh",
      "Ithaya Jyothi College Of Nursing , Tirunelveli - Tamil Nadu",
      "ITM Business School - Karnataka",
      "ITM Group of Institutions - Madhya Pradesh",
      "ITM University - Madhya Pradesh",
      "ITM University - Chhattisgarh",
      "ITM University - Haryana",
      "ITS Engineering College - Uttar Pradesh",
    ],
  },
];
