const TData = [
  {
    colleges: [
      "T & T V School Of Nursing , S D V S Ashaktashram Hospital, Surat, Surat - Gujarat",
      "T B D S Janta College, , Bihar",
      "T D Abdul Khadar College For Women Ramanathapuram, Ramanathapuram - Tamil Nadu",
      "T D Institute Of Professional Studies ,Rewa, Rewa - Madhya Pradesh",
      "T D Medical College, Alleppey Allappuzha, , Kerala",
      "T H B College, , Assam",
      "T J P S College, Guntur - Andhra Pradesh",
      "T J S Polytechnic College, , Tamil Nadu",
      "T John College Of Nursing , Bangalore, Bangalore - Karnataka",
      "T John Institute Of Technology, , Karnataka",
      "T John Institute of Technology, Bangalore, , Karnataka",
      "T John School Of Nursing , Bangalore, Bangalore - Karnataka",
      "T John School Of Nursing , Gulbarga, Gulbarga - Karnataka",
      "T K R College of Engineering and Technology, , Andhra Pradesh",
      "T K R College Of Nursing , Hyderabad, Hyderabad - Andhra Pradesh",
      "T M A E S School Of Nursing , Bellary, Bellary - Karnataka",
      "T M A E Society Polytechnic, , Karnataka",
      "T M A E Societypolytechnic, Hospet, , Karnataka",
      "T M M College Of Nursing , Pathanamthitta, Pathanamthitta - Kerala",
      "T M S School Of Nursing ,Sheopur, , Madhya Pradesh",
      "T N B College, , Bihar",
      "T P College, , Bihar",
      "T P E V R Govt. Polytechnic College, , Tamil Nadu",
      "T P S College, , Bihar",
      "T P V College, , Bihar",
      "T R Girls College, , Haryana",
      "T R R Government Degree College, Kandukur - Andhra Pradesh",
      "T S Bhama College, , Bihar",
      "T S Srinivasan Center For Polytechnic College And Advanced T, , Tamil Nadu",
      "T V M College of Education, Tamil Nadu",
      "T V M Gurukul School Of Nursing , Ranchi, Jharkhand",
      "T. John College, Karnataka",
      "T. John College, Karnataka",
      "T. M. Government College, Kerala",
      "T. R. C. Law College, Uttar Pradesh",
      "T. R. S. Government College, Madhya Pradesh",
      "T. Romana College, Mizoram",
      "T.A. Pai Mgt. Institute, Karnataka",
      "T.B.Girwalkar Polytechnic, Maharashtra",
      "T.B.M.L. College, Tamil Nadu",
      "T.C. College Of Arts Science And Commerc, Maharashtra",
      "T.C.L. Govt. Lead College, Chhattisgarh",
      "T.C.M.T. Degree College, Andhra Pradesh",
      "T.D. Education College, Madhya Pradesh",
      "T.D. Medical College , ALAPPUZHA, Kerala",
      "T.D. Medical College, Alappuzha (Alleppy), Kerala",
      "T.D.M.N.S. College, T. Kallikulam, Tamil Nadu",
      "T.E Thiyagaraja Pillai I.A.S Teacher Training Institute, Tamil Nadu",
      "T.E.S. Elementary Teacher Training Institute, Tamil Nadu",
      "T.E.T. Teacher Training Institute For Women, Tamil Nadu",
      "T.JOHN College, Karnataka",
      "T.John college, Karnataka",
      "T.JOHN Institute of Management & Science, Karnataka",
      "T.K. Madhava Memorial College, Kerala",
      "T.K.M College of Engineering, Kerala",
      "T.K.M. Institute of Arts & Science, Kerala",
      "T.K.M. Institute of Management, Kerala",
      "T.K.R. Institute of Mgt. & Science, Andhra Pradesh",
      "T.K.Raja Educational Charitab Trust, Tamil Nadu",
      "T.M.A.E . SOCIETYS EDUCATION COLLEGE, Karnataka - Karnataka",
      "T.M.A.E SOCIETY S COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "T.M.A.E. Soceity S.C.S.College of Pharmacy, HARAPANAHALLI, DAVANAGERE - Karnataka",
      "T.M.A.E. Society M.M.J.G. ,College of Pharmacy , Gadag, GADAG - Karnataka",
      "T.M.A.E. SOCIETY S COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "T.M.A.E. Societys College Of Education, Karnataka - Karnataka",
      "T.M.A.E.s College Of Education, Karnataka - Karnataka",
      "T.M.C.s Sideswar Arts College, Karnataka - Karnataka",
      "T.M.G. College Of Arts And Science, Tamil Nadu - Tamil Nadu",
      "T.M.S.S. Womens Degree College, RANGAREDDY - Andhra Pradesh",
      "T.N. RAO COLLEGE OF MANAGEMENT STUDIES, RAJKOT - Gujarat",
      "T.N.B. Law College, BHAGALPUR - Bihar",
      "T.P.D.Malaw College, Punjab - Punjab",
      "T.R.R & S. Degree College, GUNTUR - Andhra Pradesh",
      "T.R.R & S.S.S. Degree College, PRAKASAM - Andhra Pradesh",
      "T.R.S. College, REWA - Madhya Pradesh",
      "T.S. Narayanasamy Arts And Science College, CHENNAI - Tamil Nadu",
      "T.S. Paul Manipur Womens College, Manipur - Manipur",
      "T.S.M. COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "T.S.M. Jain College of Technology, Tamil Nadu - Tamil Nadu",
      "T.S.P.S. Mandals Ltd. Sindgi C.M. Managuli A Arts College, Karnataka - Karnataka",
      "T.S.R. & T.B.K. Womens Degree College, VISAKHAPATNAM - Andhra Pradesh",
      "T.S.R. & T.B.K.R. College, VISAKHAPATNAM - Andhra Pradesh",
      "T.S.S.s S.S.R.G. Women College, Karnataka - Karnataka",
      "T.T. Mahavidyalaya, Orissa - Orissa",
      "T.T. Narasimhan - Swami Dayananda College Of Arts And Science, THANJAVUR - Tamil Nadu",
      "T.T.KUNHAHAMMED MEMORIAL TEACHER TRAINING INSTITUTE, Kerala - Kerala",
      "T.V.E.S. Instt. of Pharmacy , FAIZPUR, JALGAON - Maharashtra",
      "T.V.R. TEACHERS COLLEGE, Pondicherry - Pondicherry",
      "Tadikela Subbaiah College Of Nursing,Shimoga, SHIMOGA - Karnataka",
      "Tadikela Subbaiah School Of Nursing , Shimoga, SHIMOGA - Karnataka",
      "Tago Memorial Institute Of Health Science & Hospital , Papumpare,  - Arunachal Pradesh",
      "Tagore Arts College, PONDICHERRY - Pondicherry",
      "Tagore College Of Arts And Science, CHENNAI - Tamil Nadu",
      "TAGORE COLLEGE OF EDUCATION,  - Tamil Nadu",
      "Tagore Dental College & Hospital, Chennai, CHENNAI - Tamil Nadu",
      "Tagore Engineering College,  - Tamil Nadu",
      "TAGORE GOVERNMENT COLLEGE OF EDUCATION,  - Andaman and Nicobar Islands",
      "Tagore Institute of Engineering and Technology, SALEM - Tamil Nadu",
      "Tagore Medical College and Hospital, Chennai,  - Tamil Nadu",
      "Tagore Memorila Polytechnic,  - Karnataka",
      "Tagore Nursing College,Jaipur, JAIPUR - Rajasthan",
      "Tagore Public Law College, JAIPUR - Rajasthan",
      "TAGORE SHIKSHAK PRASHIKSHAN SANSTHAN,  - Rajasthan",
      "TAGORE SHIKSHAN PRASHIKSHAN SANSTHAN,  - Rajasthan",
      "TAGORE TEACHER TRAINING COLLEGE,  - Rajasthan",
      "TAGORE TEACHER TRAINING COLLEGE,  - Rajasthan",
      "TAGORE TEACHER TRAINING COLLEGE,  - Haryana",
      "TAGORE TEACHER TRAINING COLLEGE,  - Haryana",
      "TAGORE TEACHER TRAINING COLLEGE,  - Haryana",
      "TAGORE TEACHER TRAINING COLLEGE,  - Punjab",
      "TAGORE TEACHER TRAINING COLLEGE FOR WOMEN,  - Punjab",
      "TAGORE TEACHERS TRAINING COLLEGE,  - Rajasthan",
      "TAGORE TEACHERS TRAINING COLLEGE,  - Rajasthan",
      "TAGORE WOMENS TEACHER TRAINING COLLEGE,  - Rajasthan",
      "TAJ COLLEGE OF EDUCATION,  - Karnataka",
      "TAJ MEMORIAL TEACHERS TRAINING COLLEGE,  - Rajasthan",
      "TAK SHIKSHA NIKETAN TEACHERS TRAINING COLLEGE,  - Rajasthan",
      "Takhatmal Srivallabh Homoeo Medical College,  - Maharashtra",
      "Takhatmal Srivallabh Homoeo. Medical College,  - Maharashtra",
      "Taki Government College, West Bengal - West Bengal",
      "Taksha Shila Degree College, MAHABUBNAGAR - Andhra Pradesh",
      "Takshashila Mahavidyalaya, Maharashtra - Maharashtra",
      "TAKSHASHILA TEACHER TRAINING INSTITUTE, Karnataka - Karnataka",
      "Takshila Institute Of Technology Tietch, JABALPUR - Madhya Pradesh",
      "Takshshila Institute of Engineering &amp; Technology, Madhya Pradesh - Madhya Pradesh",
      "TALASILA COLLEGE OF MANAGEMENT &amp; INFORMATION TECH, KHAMMAM - Andhra Pradesh",
      "TALAT SHIKSHAN MANDAL, Maharashtra - Maharashtra",
      "Talchar College, Orissa - Orissa",
      "Talegaon General Hosp &amp; Convalescent Home S , Training School Of Nursing,Pune, PUNE - Maharashtra",
      "Talekchand Mayachand Shah Mahila Arts College, Gujarat - Gujarat",
      "TALIMUDDIN NISWAN DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Taliparamba Arts &amp; Science College, Kerala - Kerala",
      "Talla Padmavathi College of Engineering, Andhra Pradesh - Andhra Pradesh",
      "Talla Padmavathi College of Pharmacy , Warangal, WARANGAL - Andhra Pradesh",
      "TALUK VOKKALIGARA SANG SAHYADRI TEACHERS TRAINING INSTITUTE, Karnataka - Karnataka",
      "TALUKA SHIKSHANA PRASARAK MANDALIS COLLEGE, Karnataka - Karnataka",
      "Taluka Vidyarthi Sahayyak Samitis College Of Nursing,Ahmednagar, AHMEDNAGAR - Maharashtra",
      "Tam Bran School Of Nursing , Gwalior, GWALIOR - Madhya Pradesh",
      "Tamana  School of Hope Special School, DELHI - Delhi",
      "Tamanna Association (School of Hope), DELHI - Delhi",
      "Tamanna Institute Of Allied Health Sciences, , Allahabad, ALLAHABAD - Uttar Pradesh",
      "Tamanna Institute Of Allied Health Sciences,Allahabad, ALLAHABAD - Uttar Pradesh",
      "Tamenglong College, Manipur - Manipur",
      "Tamil Nadu Agricultural University, COIMBATORE - Tamil Nadu",
      "Tamil Nadu Arts And Science College, CHENNAI - Tamil Nadu",
      "Tamil Nadu Dr Ambedkar Law University, Tamil Nadu - Tamil Nadu",
      "Tamil Nadu Dr M G R Medical University, CHENNAI - Tamil Nadu",
      "Tamil Nadu Government Dental College &amp; Hospital, CHENNAI - Tamil Nadu",
      "Tamil Nadu Government Dental College &amp; Hospital, Chennai, CHENNAI - Tamil Nadu",
      "Taki Government College, West Bengal - West Bengal",
      "Taksha Shila Degree College, MAHABUBNAGAR - Andhra Pradesh",
      "Takshashila Mahavidyalaya, Maharashtra - Maharashtra",
      "TAKSHASHILA TEACHER TRAINING INSTITUTE, Karnataka - Karnataka",
      "Takshila Institute Of Technology Tietch, JABALPUR - Madhya Pradesh",
      "Takshshila Institute of Engineering & Technology, Madhya Pradesh - Madhya Pradesh",
      "TALASILA COLLEGE OF MANAGEMENT & INFORMATION TECH, KHAMMAM - Andhra Pradesh",
      "TALAT SHIKSHAN MANDAL, Maharashtra - Maharashtra",
      "Talchar College, Orissa - Orissa",
      "Talegaon General Hosp & Convalescent Home S , Training School Of Nursing,Pune, PUNE - Maharashtra",
      "Talekchand Mayachand Shah Mahila Arts College, Gujarat - Gujarat",
      "TALIMUDDIN NISWAN DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Taliparamba Arts & Science College, Kerala - Kerala",
      "Talla Padmavathi College of Engineering, Andhra Pradesh - Andhra Pradesh",
      "Talla Padmavathi College of Pharmacy , Warangal, WARANGAL - Andhra Pradesh",
      "TALUK VOKKALIGARA SANG SAHYADRI TEACHERS TRAINING INSTITUTE, Karnataka - Karnataka",
      "TALUKA SHIKSHANA PRASARAK MANDALIS COLLEGE, Karnataka - Karnataka",
      "Taluka Vidyarthi Sahayyak Samitis College Of Nursing,Ahmednagar, AHMEDNAGAR - Maharashtra",
      "Tam Bran School Of Nursing , Gwalior, GWALIOR - Madhya Pradesh",
      "Tamana School of Hope Special School, DELHI - Delhi",
      "Tamanna Association (School of Hope), DELHI - Delhi",
      "Tamanna Institute Of Allied Health Sciences, , Allahabad, ALLAHABAD - Uttar Pradesh",
      "Tamanna Institute Of Allied Health Sciences,Allahabad, ALLAHABAD - Uttar Pradesh",
      "Tamenglong College, Manipur - Manipur",
      "Tamil Nadu Agricultural University, COIMBATORE - Tamil Nadu",
      "Tamil Nadu Arts And Science College, CHENNAI - Tamil Nadu",
      "Tamil Nadu Dr Ambedkar Law University, Tamil Nadu - Tamil Nadu",
      "Tamil Nadu Dr M G R Medical University, CHENNAI - Tamil Nadu",
      "Tamil Nadu Government Dental College & Hospital, CHENNAI - Tamil Nadu",
      "Tamil Nadu Government Dental College & Hospital, Chennai, CHENNAI - Tamil Nadu",
      "Tarapith College of B.Ed, West Bengal - West Bengal",
      "Tarasankar Bandhya padhyay B.Ed. Institution, West Bengal - West Bengal",
      "Tarasankar Bandhya padhyay Primary Teacher's Training Institute, West Bengal - West Bengal",
      "Tarini School Of Nursing , Mayurbhanj, Orissa - Orissa",
      "Tarkeshwar Narayan Agrawal Teacher's Training College, Bihar - Bihar",
      "TARUR COLLEGE OF PHYSICAL EDUCATION, Karnataka - Karnataka",
      "Tata Cancer Research Memorial Institute, Mumbai, Maharashtra - Maharashtra",
      "TATA CMC Academy, Chandigarh - Chandigarh",
      "Tata College, Jharkhand - Jharkhand",
      "Tata College, Jharkhand - Jharkhand",
      "Tata Institute of Social Science, Mumbai, Maharashtra - Maharashtra",
      "Tata Institute Of Social Sciences, Maharashtra - Maharashtra",
      "Tata Main Hospital, School Of Nursing , Jamshedpur, Jharkhand - Jharkhand",
      "Tata Memorial Hospital, College Of Nursing , Mumbai, Maharashtra - Maharashtra",
      "Tathagat Goutam Budh Govt. Polytechnic, Srawasti, Uttar Pradesh - Uttar Pradesh",
      "Tathagat Teacher's Training College, Jharkhand - Jharkhand",
      "Tatineni Gopaiah Triveni College, Krishna - Andhra Pradesh",
      "Tatyasaheb Kore College of Pharmacy , Kolhapur, Kolhapur - Maharashtra",
      "Tatyasaheb Kore Dental College & Research Centre , Kolhapur, Kolhapur - Maharashtra",
      "TAU DEVI LAL MEMORIAL TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "TAVARAGERAS TEACHER EDUCATION INSTITUTION, Karnataka - Karnataka",
      "TAVITE B.ED. TRAINING COLLEGE, Madhya Pradesh - Madhya Pradesh",
      "Taxila Business School, Rajasthan - Rajasthan",
      "TAXSHILA VIDYAPEETH SANSTHAN, Rajasthan - Rajasthan",
      "Tayyib Muslim Polytechnic, Andhra Pradesh - Andhra Pradesh",
      "TCM College of Engineeering, Haryana - Haryana",
      "TDTA COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "Teacher Training College, Bihar - Bihar",
      "TEACHER TRAINING COLLEGE FOR WOMEN,RAIKOT, Punjab - Punjab",
      "TEACHER TRAINING COLLEGE KUTANA, Haryana - Haryana",
      "TEACHER TRAINING COLLEGE(FOR GIRLS),BIKHI, Punjab",
      "TEACHER TRAINING COLLEGE,FEROZEPUR, Punjab",
      "TEACHER TRAINING INSTITUTE, Kerala",
      "TEACHER TRAINING INSTITUTE, Kerala",
      "TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "TEACHER TRAINING INSTITUTE KEEZHAMOONGILADI, Tamil Nadu",
      "Teacher's Training College, Bihar",
      "Teacher's Training College, Assam",
      "Teacher's Training College, Assam",
      "Teacher's Training College of India, Bihar",
      "Teachers Law College, Karnataka",
      "TEACHERS TRAINING INSTITUTE, Kerala",
      "Teachers' Training College, Assam",
      "Teachers' Training College Jharkahand, Jharkhand",
      "Tech Vidhya Telecom Training Institute, Delhi",
      "Tech. & Medical Education Society's J. T. Mahajan College of Engineering, Maharashtra",
      "TECHNIA INSTITUTE OF ADVANCED STUDIES, Delhi",
      "TECHNICAL INSTITUTE & RESEACH INSTITUTE, Uttar Pradesh",
      "Techno India, West Bengal",
      "Techno India College of Technology, West Bengal",
      "Techno India University, West Bengal",
      "TECHNO Institute of Management Sciences, Uttar Pradesh",
      "Techno-Apex Polytechnic, Haryana",
      "Technocarts Institute of Technology Diploma Pharmacy , Bhopal, Madhya Pradesh",
      "Technocrats Institute of Technology, Madhya Pradesh",
      "Technocrats Institute of Technology Excellence, Madhya Pradesh",
      "Technocrats Institute of Technology Science, Madhya Pradesh",
      "Technological Institute of Textile & Science, Haryana",
      "Technological Institute of Textile & Sciences, Haryana",
      "Technology Education & Research Institute, Haryana",
      "TECNIA INSTITUTE OF ADVANCED STUDIES, Delhi - Delhi",
      "TECNIA INSTITUTE OF TEACHER EDUCATION, Delhi - Delhi",
      "Teegala Krishna Reddy Engineering College, Andhra Pradesh - Andhra Pradesh",
      "TEERATH INSTITUTE, Madhya Pradesh - Madhya Pradesh",
      "Teerath Institute of Scienceand Technology , Bhopal, Bhopal - Madhya Pradesh",
      "Teerthankar Mahaveer Institute Of Management And Technology, Moradabad - Uttar Pradesh",
      "Teerthankar Mahaveer Medical College, Moorabad, Moorabad - Uttar Pradesh",
      "Teerthanker Mahaveer College of Law and Legal Studies, Moradabad - Uttar Pradesh",
      "Teerthanker Mahaveer College Of Nursing , Moradabad, Moradabad - Uttar Pradesh",
      "Teerthanker Mahaveer Dental College & Research Centre , Moradabad, Moradabad - Uttar Pradesh",
      "TEERTHANKER MAHAVEER INSTITUTE OF MANAGEMENT & TECHNOLOGY, Uttar Pradesh - Uttar Pradesh",
      "Teerthanker Mahaveer University, Uttar Pradesh - Uttar Pradesh",
      "Teerthanker Parshavnath School Of Nursing , Maradabad, Maradabad - Uttar Pradesh",
      "Tehmi Grant Institute Of Nursing Education , Pune, Pune - Maharashtra",
      "Tejaa Shakthi Institute of Technology for Women, Coimbatore - Tamil Nadu",
      "TEJASVI COLLEGE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "Tejaswi Educational Academy, Hyderabad - Andhra Pradesh",
      "Tejaswini Nursing School,Pune, Pune - Maharashtra",
      "Tejeswi School Of Nursing , Kukatpally, Kukatpally - Andhra Pradesh",
      "TEJU SINGH MEMORIAL DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Teju Singh Memorial Law College, Uttar Pradesh - Uttar Pradesh",
      "Telangana University, Nizamabad - Andhra Pradesh",
      "TELC TEACHER TRAINING INSTITUTE FOR MEN, Tamil Nadu - Tamil Nadu",
      "TELC TEACHER TRAINING INSTITUTE FOR WOMEN, Tamil Nadu - Tamil Nadu",
      "Telengana University, Nizamabad - Andhra Pradesh",
      "TELLAKULA JPS COLLEGE, Guntur - Andhra Pradesh",
      "Temi Grant Institute Of Nursing Education , Pune, Pune - Maharashtra",
      "TempleCity Institute of Technology & Engineering, Orissa - Orissa",
      "Tenali Engineering College, Andhra Pradesh - Andhra Pradesh",
      "Tengakhat College, Assam - Assam",
      "Tentulia Sasan Debasthan College, Orissa - State",
      "TERASA COLLEGE OF EDUCATION, Tamil Nadu - State",
      "Teresian College, Karnataka - State",
      "Terfs Academy College Of Arts And Science, Tirupur - Tamil Nadu",
      "Teri University, Delhi - State",
      "Terna Dental College & Hospital , Navi Mumbai, Mumbai - Maharashtra",
      "TERNA JR. COLLEGE OF EDUCATION, Maharashtra - State",
      "Terna Mahavidyalaya (Arts Science & Commerce), Maharashtra - State",
      "Terna Medical College, Navi Mumbai, Mumbai - Maharashtra",
      "Terna Nursing College , Navi Mumbai, Mumbai - Maharashtra",
      "Terna Public Charitable Trust's  Engineering College, Maharashtra - State",
      "Terna Public Charitable Trust's Terna Engineering College, Mumbai - Maharashtra",
      "Terna Public Charitable Trust's Terna Polytechnic, Maharashtra - State",
      "TES Polytechnic, Karnataka - State",
      "test, Chennai - Tamil Nadu",
      "TET's Thakur College of Science & Commerce, Maharashtra - State",
      "Tetri Chandravansi College of Education, Jharkhand - State",
      "Texcity Arts And Science College, Coimbatore - Tamil Nadu",
      "Texcity College Of Nursing , Coimbatore, Coimbatore - Tamil Nadu",
      "Texcity College of Pharmacy , Coimbatore, Coimbatore - Tamil Nadu",
      "Texcity School Of Nursing , Coimbatore, Coimbatore - Tamil Nadu",
      "Texila American University, Tamil Nadu - State",
      "Tezpur College, Tezpur - Assam",
      "Tezpur Law College, Tezpur - Assam",
      "Tezpur University, Nappam - Assam",
      "TGLG.Polytechnic,Adoni, Andhra Pradesh - State",
      "Th. Biri Singh Mahavidyalaya, Uttar Pradesh - State",
      "Thadomal Shahani Engineering College, Mumbai - Maharashtra",
      "Thai Moogambigai Dental College & Hospital , Chennai, Chennai - Tamil Nadu",
      "Thai Moogambigai Polytechnic College, Madurai - Tamil Nadu",
      "Thai Moogambigai Polytechnic College, Tamil Nadu - Tamil Nadu",
      "Thaimoogambigai Dental College & Hospital, Tamil Nadu - Tamil Nadu",
      "Thakral College of Technology, BHOPAL - Madhya Pradesh",
      "Thakur Aidal Singh Smriti Kanya Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "Thakur Chhedilal Government College, Chhattisgarh - Chhattisgarh",
      "Thakur College of Engineering & Technology, MUMBAI - Maharashtra",
      "Thakur Dharam Singh Tds College Education, Jammu and Kashmir - Jammu and Kashmir",
      "THAKUR DIN PATHAK SMRITI MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "THAKUR DURG PAL SINGH MEMORIAL TEACHER TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Thakur Hari Prasad Institute of Research & Rehabilitation for the Mentally Handicapped, HYDERABAD - Andhra Pradesh",
      "Thakur Institute of Management Studies and Research, Maharashtra - Maharashtra",
      "Thakur Jagdev Chand Memorial Government Degree College, Himachal Pradesh - Himachal Pradesh",
      "Thakur Kripal Singh Memorial Degree College, Uttar Pradesh - Uttar Pradesh",
      "Thakur Nigamanada Mohavidyalaya, Orissa - Orissa",
      "Thakur Panchanan Mahila Mahavidyalaya, West Bengal - West Bengal",
      "THAKUR SHYAMNARAYAN COLLEGE OF EDUCATION AND RESEARCH (B.ED. COLLEGE), Maharashtra - Maharashtra",
      "THAKUR TEACHER TRAINING COLLEGE, Himachal Pradesh - Himachal Pradesh",
      "THAKUR TEACHER TRAINING COLLEGE, Himachal Pradesh - Himachal Pradesh",
      "Thakur Yugraj Singh Law College, Uttar Pradesh - Uttar Pradesh",
      "THALAPATHY COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "Thambal Marik College, Manipur - Manipur",
      "THAMIL THAI TEACHER TRAINING INSTITUTE, Tamil Nadu - Tamil Nadu",
      "Thamilavel Umamaheswaranar Karanthai Arts College, THANJAVUR - Tamil Nadu",
      "Thamirabharani Engineering College, Tamil Nadu - Tamil Nadu",
      "Thammi Naidu Degree College, PALAKONDA - Andhra Pradesh",
      "Thamminaidu Vidya Degree College, SRIKAKULAM - Andhra Pradesh",
      "Thanapandian Polytechnic College, CHENNAI - Tamil Nadu",
      "THANBEEHUL ISLAM TEACHERS TRAINING, Kerala - Kerala",
      "Thandra Paparaya Degree College, Vizianagaram - Andhra Pradesh",
      "Thandra Paparaya Institute of Science & Technology, BOBBILI - Andhra Pradesh",
      "Thane Municiple Councils Law College, THANE - Maharashtra",
      "Thangal Kunju Musaliar College, Location Not Provided - Kerala",
      "Thangam Muthu Polytechnic College, Location Not Provided - Tamil Nadu",
      "Thangam Muthu Polytechnic College, MADURAI - Tamil Nadu",
      "Thangavelu College Of Science & Management, CHENNAI - Tamil Nadu",
      "Thangavelu Engineering College, CHENNAI - Tamil Nadu",
      "Thanjavur Medical College, THANJAVUR - Tamil Nadu",
      "Thanjavur Medical College Hospital , School Of Nursing, Thanjavur, THANJAVUR - Tamil Nadu",
      "Thanthai Hans Roever College, PERAMBALUR - Tamil Nadu",
      "THANTHAI HANS ROEVER COLLEGE EDUCATION, Location Not Provided - Tamil Nadu",
      "Thanthai Hans Roever Institute Of Management, TRICHY - Tamil Nadu",
      "Thanthai Hans Roever Institute Of Management, Location Not Provided - Tamil Nadu",
      "Thanthai Periyar E.V.R. Government Polytechnic College, MADURAI - Tamil Nadu",
      "Thanthai Periyar Government Institute of Technology, Location Not Provided - Tamil Nadu",
      "Thanthai Roever College Of Nursing , Perambalur, PERAMBALUR - Tamil Nadu",
      "Thanthai Roever College Of Nursing , Perambalur, PERAMBALUR - Tamil Nadu",
      "Thanthai Roever College of Pharmacy , Perambalur, PERAMBALUR - Tamil Nadu",
      "Thanthai Roever Inst.of  Polytechnic College, Location Not Provided - Tamil Nadu",
      "Thanthai Roever Inst.of  Polytechnic College, Location Not Provided - Tamil Nadu",
      "Thanthai Roever Institute Of Polytechnic College, VELLORE - Tamil Nadu",
      "Thanthai Roever School Of Nursing, , Perambalur, PERAMBALUR - Tamil Nadu",
      "Thanthai Rover College of Physiotherapy, TRICHY - Tamil Nadu",
      "Thapar College of Pharmacy , Dr.Shyam Lal Thapar Nursing , Moga, MOGA - Punjab",
      "Thapar Institute Of Engineering Technology, Location Not Provided - Punjab",
      "Thapar University, Location Not Provided - Punjab",
      "Thasiah College Of Nursing , Kanyakumari, KANYAKUMARI - Tamil Nadu",
      "Thassim Beevi Abdul Kadar College For Women, RAMANATHAPURAM - Tamil Nadu",
      "THATAVATI IT & BUSINESS SCHOOL, KRISHNA - Andhra Pradesh",
      "Thatha School Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
      "THAVATHIRU KUNDRAKUDI ADIGALA COLLEGE OF EDUCATION FOR WOMEN, Location Not Provided - Tamil Nadu",
      "Thavathiru Santhalinga Adigalar Arts Science And Tamil College, COIMBATORE - Tamil Nadu",
      "The Academy Of Nursing Science & Hospital , Kedarpur,  - Madhya Pradesh",
      "The Academy Of Nursing Science And Hospital ,Gwalior, GWALIOR - Madhya Pradesh",
      "The Academy Of Nursing Sciences & Hospital , Gwalior, GWALIOR - Madhya Pradesh",
      "The Academy Of Nursing Sciences And Hospital , Gwalior, GWALIOR - Madhya Pradesh",
      "The Adoni Arts Science College, ADONI - Andhra Pradesh",
      "The Amalapuram Degree College, Amalapuram, AMALAPURAM - Andhra Pradesh",
      "The American College, MADURAI - Tamil Nadu",
      "THE ASIAN SCHOOL FOR TERACHER EDUCATION,  - Uttaranchal",
      "The Assam Kaziranga University,  - Assam",
      "The Assembly of God Church Teacher's Training Junior College,  - West Bengal",
      "The Badagara Co operative Institute Of Nursing,Kozhikode, KOZHIKODE - Kerala",
      "THE BERKLEY COLLEGE,  - Punjab",
      "THE BEST COLLEGE OF EDUCATION,  - Tamil Nadu",
      "The Bhaskar Pandurang Hivale Education Society's Institute of Management Studies, Career Development & Research,  - Maharashtra",
      "THE BHOPAL SCHOOL OF SOCIAL SCIENCE,  - Madhya Pradesh",
      "THE BIJAPUR DIST. MINORITY NATIONALEDUCATION SOCIETY,  - Karnataka",
      "The C N S Bank Arts And Sh B A Patel Sh D B Vyas Commerce College,  - Gujarat",
      "The Calcutta Homoeopathic Medical College and Hospital,  - West Bengal",
      "The Calcutta Medical Research Institute , Kolkata, KOLKATA - West Bengal",
      "The Calcutta Technical School,  - West Bengal",
      "The Capitol College Of Nursing , Bangalore, BANGALORE - Karnataka",
      "The Capitol School Of Nursing , Bangalore, BANGALORE - Karnataka",
      "The Chikitsak Samute Sir Sitram And Lady Shantabai Patkar College,  - Maharashtra",
      "The Christian Institute For Technical Education, TRICHY - Tamil Nadu",
      "The Christian Institute for Technical Education,  - Tamil Nadu",
      "The City School Of Nursing , Bhopal, BHOPAL - Madhya Pradesh",
      "The Clarke School for the Deaf, Sadhna, CHENNAI - Tamil Nadu",
      "THE CO-OPERATIVE TEACHERS TRAINING INSTITUTE,  - Pondicherry",
      "The College of Law and Legal Aid, SHAHDOL - Madhya Pradesh",
      "The College Of Law And Legal Ed, Madhya Pradesh",
      "The College of Law and Legal Ed, Madhya Pradesh",
      "The College Of Medical Technology , School Of Nursing , Ongole, Andhra Pradesh",
      "THE COLLEGE OF PHYSICAL EDUCATION, Gujarat",
      "THE COLLEGE OF PHYSICAL EDUCATION, Gujarat",
      "THE CONGREGATION OF THE FRANCISCAN SISTER OF THE PRESENTATION OF THE BLESSED VIRGIN MARY, Tamil Nadu",
      "The Deaf and Dumb Relief Association, Maharashtra",
      "THE DEPARTMENT OF PHYSICAL EDUCATION, Punjab",
      "The Dharmapuri District Co-Op. Sugar Mills Polytechnic College, Tamil Nadu",
      "The Erode College of Pharmacy, Tamil Nadu",
      "THE ERODE COLLEGE OF PHARMACY,Erode, Tamil Nadu",
      "The Evangelical Mission Hospital , Raipur, Chhattisgarh",
      "The Excellence College Of Nursing ,Vidisha, Madhya Pradesh",
      "The Excellence School Of Nursing Sciences And Research Hospital, Vidisha, Madhya Pradesh",
      "The Gandhigram Institute Of Rural Health & Famil Welfare Trust ,Dindigul, Tamil Nadu",
      "The Gandhigram Institute of Rural Health And Family Welfare Trust , Ambathurai, Tamil Nadu",
      "The Gandhigram Institute of Rural Health And Family Welfare Trust, Ambathurai, Tamil Nadu",
      "The Global Open University, Nagaland",
      "The Glocal University, Uttar Pradesh",
      "The Goa Eduation Society Dhempe College Arts Science, Goa",
      "THE GOOD SAMARITAN ELEMENTAR TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "The Government Guru Teg Bahadur College, Punjab",
      "The Graduate School College for Women, Jharkhand",
      "The Graduate School College Woman, Jharkhand",
      "THE GRANTHAM COLLEGE PHYSICAL VIDISHA, Madhya Pradesh",
      "The Gujarat Cancer & Research Institute, Ahmedabad, Gujarat",
      "The Guru Nank Vidyak Societys College Of Arts Science & Commerce, Maharashtra",
      "The H N S Bank Ltd Science College, Gujarat",
      "THE HINDU COLLEGE, Andhra Pradesh",
      "The Hindu College, Guntur, Andhra Pradesh",
      "The Hitech College Of Nursing, BHUBANESWAR - Orissa",
      "The Hotel School Haldwani,  - Uttaranchal",
      "The Ideal Fine Arts Society College Of Visual Art,  - Karnataka",
      "The Indian Polytechnic College,  - Tamil Nadu",
      "THE INSTITUTE OF CERTIFIED MANAGEMENT ACCOUNTANTS OF INDIA, JAIPUR - Rajasthan",
      "The Institute of Chartered Financial Analysts of India University,  - Mizoram",
      "The Institute of Chartered Financial Analysts of India University, Meghalaya,  - Meghalaya",
      "The Institute Of Education,  - Karnataka",
      "The Institute of Engineering and Emerging Technologies, SUNDER NAGAR - Himachal Pradesh",
      "THE INSTITUTE OF MANAGEMENT FOR STUDIES,  - Uttar Pradesh",
      "The Institute Of Mathematical Science,  - Tamil Nadu",
      "THE INSTITUTE OF PROFESSIONAL EDUCATION & TECHNOLGY,  - Uttar Pradesh",
      "The Institute of Road Transport Perundurai Medical College, Perundurai, ERODE - Tamil Nadu",
      "The Institute of Road Transport Perunthurai Medical College, Perunthurai, ERODE - Tamil Nadu",
      "The institute of Rural Education (IRE),  - Manipur",
      "THE INTEGRAL UNIVERSITY,  - Uttar Pradesh",
      "The Jijamata Mahavidyalaya,  - Maharashtra",
      "The K.P.E. Socitys Law College,  - Karnataka",
      "The K.P.E. Socitys Law College,  - Karnataka",
      "THE KAGAL EDUCATION SOCIETYS B ED COLLEGE,  - Maharashtra",
      "The Karnataka College Of Nursing , Bangalore, BANGALORE - Karnataka",
      "The Karnataka College Of Nursing,Bangalore, BANGALORE - Karnataka",
      "The Karur Polytechnic College, SALEM - Tamil Nadu",
      "The Karur Polytechnic College, Athur,  - Tamil Nadu",
      "THE KAVERY COLLEGE OF EDUCATION,  - Tamil Nadu",
      "The Kavery College of Engineering,  - Tamil Nadu",
      "The Kavery Engineering College, SALEM - Tamil Nadu",
      "The Kavery Institude Of Tedchnology,  - Tamil Nadu",
      "The Kavery Polytechnic College, NAMAKKAL - Tamil Nadu",
      "The Kavery Polytechnic College,  - Tamil Nadu",
      "The Kerala Law Academy Law College, Kerala - Kerala",
      "The Kevin Polytechnic College, Tamil Nadu - Tamil Nadu",
      "The Khanaya Medical Mission , Menathottam Hospital, School Of Nursing, Kerala - Kerala",
      "The Konghu Polytechnic College, Tamil Nadu - Tamil Nadu",
      "THE KRISHNA EDUCATION RESEARCH AND TECHNOLOGICAL INSTITUTE, Haryana - Haryana",
      "The Lallubhai Motilal College Pharmacy, Gujarat - Gujarat",
      "The Lallubhai Motilal College Pharmacy, Gujarat - Gujarat",
      "The Law Academy Law college, Kerala - Kerala",
      "The Law College, CUTTACK - Orissa",
      "The Little Flower School Of Nursing , Hyderabad, Andhra Pradesh - Andhra Pradesh",
      "THE LORDS UNIVERSAL COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "The M T B Arts College, Gujarat - Gujarat",
      "The M.D.T. Hindu College, TIRUNELVELI - Tamil Nadu",
      "The M.E.S. Arts And Commerce College, Karnataka - Karnataka",
      "The Madurai Diravyam Thayumanavar Hindu College, TIRUNELVELI - Tamil Nadu",
      "THE MAHARASHTRA EDUCATION & SPORTS ACADEMY, Maharashtra - Maharashtra",
      "The Mandvi Education Society Institute of Business Management and Computer Studies, Mandvi, Gujarat - Gujarat",
      "The Mothers Degree College For Women, HYDERABAD - Andhra Pradesh",
      "THE MRINALINI COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "THE MUDALGI EDUCATION SOCIETY S D.ED COLLEG, Karnataka - Karnataka",
      "The Nalgonda Degree College, NALGONDA - Andhra Pradesh",
      "THE NATIONAL AND RURA EDUCATION ASSOCIATION, Karnataka - Karnataka",
      "The National Institute of Engineering, Karnataka - Karnataka",
      "The National Institute Of Engineering, Evening, Karnataka - Karnataka",
      "The New College, Maharashtra - Maharashtra",
      "The New College, CHENNAI - Tamil Nadu",
      "The New Polytechnic College, Tamil Nadu - Tamil Nadu",
      "The New Royal College of Engineering & Technology, CHENNAI - Tamil Nadu",
      "THE NIBARK SHIKSHAN PRASHIKSHAN MAHAVIDYALAYA, Rajasthan - Rajasthan",
      "THE OXFORD COLLEGE OF BUSINESS MGT, BANGALORE - Karnataka",
      "The Oxford College of Business Management, Karnataka",
      "THE OXFORD COLLEGE OF EDUCATION, Karnataka",
      "The Oxford College of Engineering, Karnataka",
      "The Oxford College Of Hotel Management, Karnataka",
      "The Oxford College of Law, Karnataka",
      "The Oxford College of Pharmacy , Bangalore, Karnataka",
      "The Oxford College of Science, Karnataka",
      "The Oxford Dental College , Bangalore, Karnataka",
      "The Oxford Institute of Pharmacy , Bangalore, Karnataka",
      "The Oxford Polytechnic, Karnataka",
      "THE PEDANANDIPADU COLLEGE OF ARTS & SCIENCE, Andhra Pradesh",
      "The Pharmaceutical College , Bargarh, Orissa",
      "THE PINNACLE SCHOOL, Delhi",
      "The Poona Dioccsan Education Societys Vidya Bhavan College Of Commerce, Maharashtra",
      "The Poona School & Home for the Blind, Teachers Training Centre, Maharashtra",
      "THE POST GRANDUNTE COLLEGE, Uttar Pradesh",
      "THE PRESIDENCY COLLEGE OF EDUCATION, Karnataka",
      "The Quaide Milleth College For Men, Tamil Nadu",
      "The Rajaas Engineering College, Tamil Nadu",
      "The Rajiv Gandhi National University of Law, Punjab",
      "The Ramakrishna Mission Blind Boys Academy, West Bengal",
      "THE REGENCY COLLEGE O EDUCATION, Karnataka",
      "The Regency PU College, Karnataka",
      "The Richmond Fellowship Post Graduate College For, Karnataka",
      "The Richmond Fellowship Society (India), Karnataka",
      "The Rural College, Karnataka",
      "THE RURAL EDUCATION SOCIETY(REGD.), Karnataka",
      "The Salem Co Op Sugar Mills Polytechnic College, Tamil Nadu",
      "The Salem Co-Operative Sugar Mills Polytechnic College, Tamil Nadu",
      "The Salem Polytechnic College, Tamil Nadu",
      "The Salvation Army Catherine Booth Hospital , School Of Nursing, Nagercoil, NAGARCOIL - Tamil Nadu",
      "The Salvation Army, Mac Robert Hospital, School Of Nursing , Gurdaspur, GURDASPUR - Punjab",
      "THE SCHOLARS ARENA GIRLS TEACHER TRAINING COLLEGE,  - Rajasthan",
      "The School of Indian Legal Thought, KOTTAYAM - Kerala",
      "The School Of Nursing, Porompat Under The , Modern Clinic & Village Ind.Imphal, IMPHAL - Manipur",
      "The School Of Nursing,Kozhikode, KOZHIKODE - Kerala",
      "The School of P.G. Studies In Law, RAIPUR - Chhattisgarh",
      "The Selvam Women Excellence Engineering Technology,  - Tamil Nadu",
      "The Sethupathy Government Arts College, RAMANATHAPURAM - Tamil Nadu",
      "The Shripur Education Society's RC Patel Institute of Technology,  - Maharashtra",
      "THE SOUTH INDIAN EDUCATION SOCIETY SIES COLLEGE OF MANAGEMENT STUDIES, THANE - Maharashtra",
      "The Spastic Society of Tiruchirapalli, TRICHY - Tamil Nadu",
      "The Spastics Society of India, BHANDARA - Maharashtra",
      "The Standard Fire Works Rajaratnam College For Women, SIVAKASI - Tamil Nadu",
      "The Surabi College Of Polytechnic,  - Tamil Nadu",
      "The Techno School,  - Orissa",
      "The Temple of Hahnemann Homoeopathic Medical College, MUNGER - Bihar",
      "THE THASSIM BEEVI ABDUL KHADER COLLEGE FOR WEMENS, RAMANATHAPURAM - Tamil Nadu",
      "The Ugar Education Trusts Arts & Comme Ugar,  - Karnataka",
      "The Unity Institute Of Nursing Sciences , Chitradurga, CHITRADURGA - Karnataka",
      "The Unity Law College, NAINITAL - Uttaranchal",
      "THE VYSYA COLLEGE OF EDUCATION,  - Tamil Nadu",
      "The WB National University of Juridical Sciences,  - West Bengal",
      "The Winners Polytechnic College,  - Tamil Nadu",
      "The Yash Foundations Institution Of Nursing & Medical Research Institute , Ratnagiri, RATNAGIRI - Maharashtra",
      "The Yash Foundations School Of Nursing,Ratnagiri, RATNAGIRI - Maharashtra",
      "The YMCA College of Physical Education Nandanam, CHENNAI - Tamil Nadu",
      "The Younis Sultan College Of Engineering, CHEVELLA - Andhra Pradesh",
      "THEERA JYOTHI TEACHER TRAINING INSTITUTE,  - Kerala",
      "Theivanai Ammal College for Women, VILLUPURAM - Tamil Nadu",
      "The Salvation Army Catherine Booth Hospital, School Of Nursing, Nagercoil, Tamil Nadu",
      "The Salvation Army, Mac Robert Hospital, School Of Nursing, Gurdaspur, Punjab",
      "THE SCHOLARS ARENA GIRLS TEACHER TRAINING COLLEGE, Rajasthan",
      "The School of Indian Legal Thought, KOTTAYAM, Kerala",
      "The School Of Nursing, Porompat Under The, Modern Clinic & Village Ind. Imphal, Manipur",
      "The School Of Nursing, Kozhikode, Kerala",
      "The School of P.G. Studies In Law, RAIPUR, Chhattisgarh",
      "The Selvam Women Excellence Engineering Technology, Tamil Nadu",
      "The Sethupathy Government Arts College, RAMANATHAPURAM, Tamil Nadu",
      "The Shripur Education Society's RC Patel Institute of Technology, Maharashtra",
      "THE SOUTH INDIAN EDUCATION SOCIETY SIES COLLEGE OF MANAGEMENT STUDIES, THANE, Maharashtra",
      "The Spastic Society of Tiruchirapalli, TRICHY, Tamil Nadu",
      "The Spastics Society of India, BHANDARA, Maharashtra",
      "The Standard Fire Works Rajaratnam College For Women, SIVAKASI, Tamil Nadu",
      "The Surabi College Of Polytechnic, Tamil Nadu",
      "The Techno School, Orissa",
      "The Temple of Hahnemann Homoeopathic Medical College, MUNGER, Bihar",
      "THE THASSIM BEEVI ABDUL KHADER COLLEGE FOR WOMEN, RAMANATHAPURAM, Tamil Nadu",
      "The Ugar Education Trusts Arts & Commerce Ugar, Karnataka",
      "The Unity Institute Of Nursing Sciences, Chitradurga, Karnataka",
      "The Unity Law College, NAINITAL, Uttaranchal",
      "THE VYSYA COLLEGE OF EDUCATION, Tamil Nadu",
      "The WB National University of Juridical Sciences, West Bengal",
      "The Winners Polytechnic College, Tamil Nadu",
      "The Yash Foundations Institution Of Nursing & Medical Research Institute, Ratnagiri, Maharashtra",
      "The Yash Foundations School Of Nursing, Ratnagiri, Maharashtra",
      "The YMCA College of Physical Education Nandanam, CHENNAI, Tamil Nadu",
      "The Younis Sultan College Of Engineering, CHEVELLA, Andhra Pradesh",
      "THEERA JYOTHI TEACHER TRAINING INSTITUTE, Kerala",
      "Theivanai Ammal College for Women, VILLUPURAM, Tamil Nadu",
      "Thirumagal Polytechnic College, Tamil Nadu",
      "THIRUMALA COLLEGE OF EDUCATION, Tamil Nadu",
      "Thirumala Devaswom Board Medical College, Kerala",
      "Thirumala Devaswom Board Medical College, Kerala",
      "Thirumalai Engineering College, Tamil Nadu",
      "Thirumalai Madhanur Polytechnic College, Tamil Nadu",
      "THIRUMALAI SRINIVASA COLLEGE, Tamil Nadu",
      "Thirumalai Srinivasa Para Medical Institution , School Of Nursing, Trichy, Tamil Nadu",
      "Thirumathi Elizabeth Polytechnic College, Tamil Nadu",
      "Thirumathi Elizabeth Polytechnic College, Tamil Nadu",
      "Thirumurugan Arts And Science College, Tamil Nadu",
      "Thirupattur Arts And Science College, Tamil Nadu",
      "Thiruthangal Nadar College, Tamil Nadu",
      "Thiruthani Polytechnic College, Tamil Nadu",
      "Thiruvalluvar Arts And Science College, Tamil Nadu",
      "Thiruvalluvar College, Tamil Nadu",
      "THIRUVALLUVAR COLLEGE OF EDUCATION, Tamil Nadu",
      "Thiruvalluvar College of Engineering and Technology, Tamil Nadu",
      "Thiruvalluvar Government Arts College, Tamil Nadu",
      "Thiruvalluvar Government Arts College, Tamil Nadu",
      "Thiruvalluvar Polytechnic College, Vellamadai, Tamil Nadu",
      "THIRUVALLUVAR TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Thiruvalluvar University, Tamil Nadu",
      "Thiruvarur Govt. Medical College, Thiruvarur, Tamil Nadu",
      "ThockchomIbotombi Institute of Teacher Education and Training, Manipur",
      "Thompson WomensSecondary Training School, Orissa",
      "THOMS CANGAN MEMORIAL TEACHER TRAINING COLLEGE, Rajasthan",
      "Thoothukudi Medical College, Thoothukudi, Tamil Nadu",
      "Thoubal College, Manipur",
      "THOZHILATHIBAR TEACHER TRAININGINSTITUTE, Tamil Nadu",
      "THREE DOTS GIRLS TRAINING COLLEGE, Uttar Pradesh",
      "Thrupti Institute Of Nursing, Bangalore, Karnataka",
      "THUNCHAN SMARAKA TEACHER TRAINING INSTITUTE, Kerala",
      "Thushara Degree College, HANAMAKONDA, Andhra Pradesh",
      "Thushara Pg School Of Information Science, WARANGAL, Andhra Pradesh",
      "TI MES COLLEGE OF EDUCATION, Madhya Pradesh",
      "Tihu College, Assam",
      "Tikaram Jagannath Arts Commerce & Science College, Maharashtra",
      "TIKARAM TEACHER TRAINING COLLEGE, Haryana",
      "Tikka Ram College Education, Haryana",
      "Tilak Ayurved Mahavidyalaya, Maharashtra",
      "Tilak College Of Education, Maharashtra",
      "Tilak Degree College, Uttar Pradesh",
      "Tilak Dhari Mahavidyalaya, JAUNPUR, Uttar Pradesh",
      "Tilak Dhari Mahila Mahavidyalaya, Uttar Pradesh",
      "Tilak Dhari PG College, Uttar Pradesh",
      "Tilak Maharashtra University, Institute Of Nursing Education & Research, Pune, Maharashtra",
      "Tilak Maharashtra Vidyapeeth, Maharashtra",
      "TILAK MAHARASHTRA VIDYAPEETH, Maharashtra",
      "TILAK NATH POST GRADUATE COLLEGE, Uttar Pradesh",
      "TILAK POST GRADUATE COLLEGE, Uttar Pradesh",
      "TILAK POST GRADUATE COLLEGE, Uttar Pradesh",
      "TILAK POST GRADUATE MAHAVIDYALAYA, Uttar Pradesh",
      "TILAK RAJ CHADHA INST. OF MGT. & TECH, Haryana",
      "TILAK RAM SAINI DEGREE COLLEGE FOR GIRLS, Uttar Pradesh",
      "TILAK TEACHERS TRAINING COLLEGE FOR WOMENS, Rajasthan",
      "Tilaka Dhari Mahavidhyalaya, JAUNPUR, Uttar Pradesh",
      "TILAKDHARI MAHAVIDHYALYA, Uttar Pradesh",
      "Tilka Manjhi Bhagalpur University, Bihar",
      "Tilkayat Shree Govindlal Government Shastri Sanskrit College, Rajasthan - Rajasthan",
      "TIM TRAINING COLLEGE, Kerala - Kerala",
      "TIMES MAHILA SHIKSHA MAHAVIDYALAYA, Rajasthan - Rajasthan",
      "TIMES PREPRIMARY TEACHER TRAINING INSTITUTE, Karnataka - Karnataka",
      "Tingkhong College, Assam - Assam",
      "Tinsukia College, Assam - Assam",
      "Tinsukia Commerce College, Assam - Assam",
      "Tinsukia Law College, Assam - Assam",
      "Tippu Shaheed Institute Of Technology, Hubli, Karnataka - Karnataka",
      "Tipu Sultan College of Pharmacy , GULBARGA, Karnataka - Karnataka",
      "Tirap Government College, Arunachal Pradesh - Arunachal Pradesh",
      "Tirath Ram Shah Hospital , Delhi, Delhi - Delhi",
      "Tirhut Anm Training School , Muzaffarpur, Bihar - Bihar",
      "Tirpude College of Social Work, Maharashtra - Maharashtra",
      "Tirpude Institute Of Management Education, Maharashtra - Maharashtra",
      "Tirthankar Anglo Vedic Institute Of Technical Education, Madhya Pradesh - Madhya Pradesh",
      "Tirukkovilur College Of Arts And Science, Tamil Nadu - Tamil Nadu",
      "Tirumala College Of Nursing , Nizamabad, Andhra Pradesh - Andhra Pradesh",
      "Tirumala College Of Nursing,Vizianagaram, Andhra Pradesh - Andhra Pradesh",
      "TIRUMALA DEVASWOM TEACHER TRAINING INSTITUTE, Kerala - Kerala",
      "Tirumala Engineering College, Andhra Pradesh - Andhra Pradesh",
      "Tirumala Polytechnic College, Tamil Nadu - Tamil Nadu",
      "Tirumala School Of Nursing , Armoor, Andhra Pradesh - Andhra Pradesh",
      "Tirumala School Of Nursing , Nizamabad, Andhra Pradesh - Andhra Pradesh",
      "Tirumala School Of Nursing , Vizianagaram, Andhra Pradesh - Andhra Pradesh",
      "Tirumalla Anm Nursing School,Latur, Maharashtra - Maharashtra",
      "Tirunelveli Medical College, Tamil Nadu - Tamil Nadu",
      "Tirunelveli Medical College Hospital,Tirunelveli, Tamil Nadu - Tamil Nadu",
      "Tirunelvelli Dakshina Mara Nadar Sangam College, Tamil Nadu - Tamil Nadu",
      "Tilkayat Shree Govindlal Government Shastri Sanskrit College, Rajasthan - Rajasthan",
      "TIM TRAINING COLLEGE, Kerala - Kerala",
      "TIMES MAHILA SHIKSHA MAHAVIDYALAYA, Rajasthan - Rajasthan",
      "TIMES PREPRIMARY TEACHER TRAINING INSTITUTE, Karnataka - Karnataka",
      "Tingkhong College, Assam - Assam",
      "Tinsukia College, Assam - Assam",
      "Tinsukia Commerce College, Assam - Assam",
      "Tinsukia Law College, Assam - Assam",
      "Tippu Shaheed Institute Of Technology, Hubli, Karnataka - Karnataka",
      "Tipu Sultan College of Pharmacy, GULBARGA, Karnataka - Karnataka",
      "Tirap Government College, Arunachal Pradesh - Arunachal Pradesh",
      "Tirath Ram Shah Hospital, Delhi - Delhi",
      "Tirhut Anm Training School, Muzaffarpur, Bihar - Bihar",
      "Tirpude College of Social Work, Maharashtra - Maharashtra",
      "Tirpude Institute Of Management Education, Maharashtra - Maharashtra",
      "Tirthankar Anglo Vedic Institute Of Technical Education, Madhya Pradesh - Madhya Pradesh",
      "Tirukkovilur College Of Arts And Science, Tamil Nadu - Tamil Nadu",
      "Tirumala College Of Nursing, Nizamabad, Andhra Pradesh - Andhra Pradesh",
      "Tirumala College Of Nursing, Vizianagaram, Andhra Pradesh - Andhra Pradesh",
      "TIRUMALA DEVASWOM TEACHER TRAINING INSTITUTE, Kerala - Kerala",
      "Tirumala Engineering College, Andhra Pradesh - Andhra Pradesh",
      "Tirumala Polytechnic College, Tamil Nadu - Tamil Nadu",
      "Tirumala School Of Nursing, Armoor, Andhra Pradesh - Andhra Pradesh",
      "Tirumala School Of Nursing, Nizamabad, Andhra Pradesh - Andhra Pradesh",
      "Tirumala School Of Nursing, Vizianagaram, Andhra Pradesh - Andhra Pradesh",
      "Tirumalla Anm Nursing School, Latur, Maharashtra - Maharashtra",
      "Tirunelveli Medical College, Tamil Nadu - Tamil Nadu",
      "Tirunelveli Medical College Hospital, Tirunelveli, Tamil Nadu - Tamil Nadu",
      "Tirunelvelli Dakshina Mara Nadar Sangam College, Tamil Nadu - Tamil Nadu",
      "TOGARI SARVAMANGALAMMA PRE PRIMARY TTI, Karnataka - Karnataka",
      "Tolani College Arts And Science, Gujarat - Gujarat",
      "Tolani Commerce College, Gujarat - Gujarat",
      "Tolani Institute of Law, Gujarat - Gujarat",
      "Tolani Institute of Pharmacy , ADIPUR KACHCHH, Gujarat - Gujarat",
      "TOM PATRICK INSTITUTE OF COMPUTER & INFORMATION TECHNOLOGY, Aurangabad - Maharashtra",
      "Tomi Polytechnic College, Arunachal Pradesh - Arunachal Pradesh",
      "Tontadarya college of Engineering, Karnataka - Karnataka",
      "Topiwala National Medical College, Mumbai - Maharashtra",
      "Toshniwal Arts and Commerce College, Maharashtra - Maharashtra",
      "Town Polytechnic, Balia, Uttar Pradesh - Uttar Pradesh",
      "Training Centre for Teachers of the Visually Handicapped, Bhubaneswar - Orissa",
      "Training centre for Teachers of the Visually Handicapped, Ludhiana - Punjab",
      "Training Centre for Teachers of Visually Handicapped, Secunderabad, Secunderabad - Andhra Pradesh",
      "Training Centre for the teachers of the Blind, Kadam Kuan, Patna - Bihar",
      "Training Centre for the Teachers of the MR Nilachal Seva Pratishthan, Puri - Orissa",
      "Training College for Teachers of the Deaf, Lucknow - Uttar Pradesh",
      "Training College for Teachers of the Deaf & Blind, Gandhi Nagar - Gujarat",
      "Training College for the Teachers of the Deaf, Kolkata - West Bengal",
      "Training College Of Nursing , Pune, Pune - Maharashtra",
      "Training Institute of Multi Rehabilitation Technology, Kerala - Kerala",
      "Training Institute of Multi Rehabilitation Technology Mercy Home, Kottayam - Kerala",
      "Training School Of Nursing , Akola, Akola - Maharashtra",
      "Training School Of Nursing , Dhule, Dhule - Maharashtra",
      "Training School Of Nursing , Sindhudurg, Sindhudurg - Maharashtra",
      "Training School Of Nursing A N M,Nasik, Maharashtra - Maharashtra",
      "Training School Of Nursing,Jalna, Jalna - Maharashtra",
      "Training School Of Nursing,Pune, Pune - Maharashtra",
      "Training School Of Nursing,Sindhudurg, Sindhudurg - Maharashtra",
      "Traininig Centre for Teacher of Hearing Impaired (TCTHI), Nagpur - Maharashtra",
      "Tranquebar Biship Maniokam Lutheeran College, Tamil Nadu - Tamil Nadu",
      "TRANSFORMATION INSTT. OF MANAGERIAL SCIENCE, MANGALORE, Karnataka - Karnataka",
      "TRANSLAM COLLEGE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "Translam College of Law, MEERUT, Uttar Pradesh - Uttar Pradesh",
      "Translam Institute of Technology and Management, Uttar Pradesh - Uttar Pradesh",
      "Travancore Business Academy, Kerala - Kerala",
      "Travancore College Of Nursing, Kollam, Kerala - Kerala",
      "Travancore Engineering College, Kollam, Kerala - Kerala",
      "Travancore Medical College, Kollam, Kerala - Kerala",
      "Travancore School Of Nursing, Kollam, Kerala - Kerala",
      "Tri Murti Instt For General Paramedical & Nursing Sciences, Gwalior, Madhya Pradesh - Madhya Pradesh",
      "Tribal Anm Training School, Ranchi, Jharkhand - Jharkhand",
      "Tribal College Of Nursing, Ranchi, Jharkhand - Jharkhand",
      "TRIBHUAN SINGH HARIHAR SINGH DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Tribhuvan Singh Harihar Singh Degree College, Uttar Pradesh - Uttar Pradesh",
      "Trichur Metropolitan Hospital, School Of Nursing, Thrissur, Kerala - Kerala",
      "Trichy Engineering College, TRICHY, Tamil Nadu - Tamil Nadu",
      "Trident Academy of Technology, Orissa - Orissa",
      "TRIDENT COLLEGE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "Trident Educational Society Valley College of Pharmacy, Bangalore, Karnataka - Karnataka",
      "Trident Institute Of Information Technology, Uttar Pradesh - Uttar Pradesh",
      "Trilok Nath Degree College, Uttar Pradesh - Uttar Pradesh",
      "TRILOK SINGH TEACHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Trimurti Law College, GWALIOR, Madhya Pradesh - Madhya Pradesh",
      "TRIMURTI PAWAN PRATISHTHAN, Maharashtra - Maharashtra",
      "Trinity College For Women, NAMAKKAL, Tamil Nadu - Tamil Nadu",
      "TRINITY COLLEGE OF EDUCATION, Uttaranchal - Uttaranchal",
      "Trinity College Of Engineering & Technology, Andhra Pradesh - Andhra Pradesh",
      "Trinity Degree College, Pedapalli, Andhra Pradesh - Andhra Pradesh",
      "Trinity Degree College, Ramagundam, Andhra Pradesh - Andhra Pradesh",
      "TRINITY INSTITUTE FOR HIGHER EDUCATION, Delhi - Delhi",
      "TRINITY INSTITUTE OF PROFESIONAL STUDIES, Delhi - Delhi",
      "Trinity Institute Of Technology & Research, Madhya Pradesh - Madhya Pradesh",
      "Trinity Nursing School , Chhindwara, Madhya Pradesh - Madhya Pradesh",
      "TRINITY PG COLLEGE, KHAMMAM - Andhra Pradesh",
      "Trinity Teacher Training College, Manipur - Manipur",
      "TRINITY WOMENS TEACHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Tripolia School Of Nursing , Patna, PATNA - Bihar",
      "Tripura Engineering College, Tripura - Tripura",
      "Tripura Govt. Law College, AGARTALA - Tripura",
      "Tripura Institute Of Paramedical Sciences,Tripura, Tamil Nadu - Tamil Nadu",
      "Tripura Institute Of Technology, Tripura - Tripura",
      "Tripura Medical College And Dr. B R A M Teaching Hospital, Agartala, Tripura - Tripura",
      "Tripura Sundari College Of Nursing , Tripura West, TRIPURA - Tripura",
      "Tripura University, Tripura - Tripura",
      "TRISHA TEACHER TRAINING COLLEGE, Himachal Pradesh - Himachal Pradesh",
      "Triveni Arts & Science College, KODAD - Andhra Pradesh",
      "Triveni Debi Bhalotia College, West Bengal - West Bengal",
      "Triveni Degree College, Jangareddyygudem, JANGAREDDIGUDEM - Andhra Pradesh",
      "Triveni Institute of Dental Sciences, Hosptial & Research Centre , Bilaspur, BILASPUR - Chhattisgarh",
      "Triveni Mahila (Sdmsm) Degree College, VIJAYAWADA - Andhra Pradesh",
      "TRIVENI TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "TRIVENI TEACHER TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Tropical Health Foundation of India, TRICHUR - Kerala",
      "TRP Engineering College, Tamil Nadu - Tamil Nadu",
      "TRR Engineering College, Andhra Pradesh - Andhra Pradesh",
      "Truba College of Engineering & Technology, Madhya Pradesh - Madhya Pradesh",
      "Truba Institute of Engineering & Information Technology., GANDHINAGAR - Madhya Pradesh",
      "Trupti Womens College, Orissa - Orissa",
      "TSS Smt VU Patil Arts & Late Dr BS Sc, Maharashtra - Maharashtra",
      "TRINITY INSTITUTE FOR HIGHER EDUCATION, Delhi - Delhi",
      "TRINITY INSTITUTE OF PROFESIONAL STUDIES, Delhi - Delhi",
      "Trinity Institute Of Technology & Research, Madhya Pradesh - Madhya Pradesh",
      "Trinity Nursing School, Chhindwara, Madhya Pradesh - Madhya Pradesh",
      "TRINITY PG COLLEGE, KHAMMAM, Andhra Pradesh - Andhra Pradesh",
      "Trinity Teacher Training College, Manipur - Manipur",
      "TRINITY WOMENS TEACHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Tripolia School Of Nursing, Patna, PATNA, Bihar - Bihar",
      "Tripura Engineering College, Tripura - Tripura",
      "Tripura Govt. Law College, AGARTALA, Tripura - Tripura",
      "Tripura Institute Of Paramedical Sciences, Tripura, Tamil Nadu - Tamil Nadu",
      "Tripura Institute Of Technology, Tripura - Tripura",
      "Tripura Medical College And Dr. B R A M Teaching Hospital, Agartala, Tripura - Tripura",
      "Tripura Sundari College Of Nursing, Tripura West, TRIPURA - Tripura",
      "Tripura University, Tripura - Tripura",
      "TRISHA TEACHER TRAINING COLLEGE, Himachal Pradesh - Himachal Pradesh",
      "Triveni Arts & Science College, KODAD, Andhra Pradesh - Andhra Pradesh",
      "Triveni Debi Bhalotia College, West Bengal - West Bengal",
      "Triveni Degree College, Jangareddyygudem, JANGAREDDIGUDEM, Andhra Pradesh - Andhra Pradesh",
      "Triveni Institute of Dental Sciences, Hospital & Research Centre, Bilaspur, BILASPUR - Chhattisgarh",
      "Triveni Mahila (Sdmsm) Degree College, VIJAYAWADA, Andhra Pradesh - Andhra Pradesh",
      "TRIVENI TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "TRIVENI TEACHER TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Tropical Health Foundation of India, TRICHUR - Kerala",
      "TRP Engineering College, Tamil Nadu - Tamil Nadu",
      "TRR Engineering College, Andhra Pradesh - Andhra Pradesh",
      "Truba College of Engineering & Technology, Madhya Pradesh - Madhya Pradesh",
      "Truba Institute of Engineering & Information Technology, GANDHINAGAR, Madhya Pradesh - Madhya Pradesh",
      "Trupti Womens College, Orissa - Orissa",
      "TSS Smt VU Patil Arts & Late Dr BS Sc, Maharashtra - Maharashtra",
      "TYAGA Institute of Advanced Studies and Research, CUTTACK - Orissa",
    ],
  },
];
