const WData = [
  {
    colleges: [
      "W.K. Bhagini Seva Mandals Arts & Commerce College For Women - Maharashtra",
      "Wagad G N M Nursing School, Udaipur - Rajasthan",
      "Waghire College of Arts Science and Commerce - Maharashtra",
      "Wai Akshar Institute, Satara - Maharashtra",
      "Waikhom Mani Girls College - Manipur",
      "WAIN GANGA COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Wainganga College of Engineering and Management - Maharashtra",
      "Walchand College of Arts and Science - Maharashtra",
      "Walchand College of Engineering, Sangli - Maharashtra",
      "Walchand Institute of Technology - Maharashtra",
      "Wali Institute of Teachers Education - West Bengal",
      "Wamanrao Ithape Nursing School, Ahmednagar - Maharashtra",
      "Wanaparthy College Of Computer & Mgt - Andhra Pradesh",
      "WARANGAL INSTITUTE OF MANAGEMENT, Warangal - Andhra Pradesh",
      "WASEEM TURKI MUSLIM DEGREE COLLEGE - Uttar Pradesh",
      "Watumull Institute of Electronic Engineering and Computer Technology, Mumbai - Maharashtra",
      "We Care Nursing College, Surguja - Chhattisgarh",
      "We Care Nursing School, Surguja - Chhattisgarh",
      "Weeta College Education - Jammu and Kashmir",
      "Weeta College of Education - Jammu and Kashmir",
      "Welcare College Of Nursing, Ernakulam - Kerala",
      "Welcome Group Graduate School of Hotel Administration (WGSHA) - Karnataka",
      "Welfare Association for the Disabled, Institute of Special Education & Disability Management, Indore - Madhya Pradesh",
      "Welfare Institute Of Nursing & Midwifery, Bharuch - Gujarat",
      "Welfare Institute Of Nursing And Midwifery, Bharuch - Gujarat",
      "WELINGKAR INSTITUTE OF MANAGEMENT DEVELOPMENT & RESEARCH, MUMBAI - Maharashtra",
      "WESLEY BOYS PG COLLEGE, Secunderabad - Andhra Pradesh",
      "Wesley Degree College Coeducation, Secunderabad - Andhra Pradesh",
      "Wesley Degree College For Women, Secunderabad - Andhra Pradesh",
      "West Bengal National University of Juridical Science - West Bengal",
      "West Bengal State University - West Bengal",
      "West Bengal Survey Institute - West Bengal",
      "West Bengal University Of Animal & Fishnery Sciences - West Bengal",
      "West Bengal University Of Technology - West Bengal",
      "WEST FORT HIGHER EDUCATION TRUST - Kerala",
      "West Goalpara College - Assam",
      "West Godavari Institute of Science & Engineering - Andhra Pradesh",
      "West Guwahati College of Education - Assam",
      "West Silchar College - Assam",
      "Western Maharashtra Nursing School ,Kolhapur - Maharashtra",
      "Westfort College Of Nursing , Thrissur - Kerala",
      "Westfort School Of Nursing,Thrissur - Kerala",
      "Westin College Of Hotel Management - Andhra Pradesh",
      "WHEREAS MODELWAYS NURSERY TEACHER EDUCATION INSTITUTE - Delhi",
      "WHITE MEMORIAL COLLEGE OF EDUCATION - Tamil Nadu",
      "White Memorial College Of Nursing , Kanyakumari - Tamil Nadu",
      "White Memorial College of Physiotherapy - Tamil Nadu",
      "White Memorial Homoeopathic Medical College - Tamil Nadu",
      "White Memorial School Of Nursing ,Kanyakumari - Tamil Nadu",
      "William Carey University - Meghalaya",
      "Williams School Of Nursing , Kanyakumari - Tamil Nadu",
      "Willingdon College - Maharashtra",
      "Wilson College - Maharashtra",
      "Wings Business School - Andhra Pradesh",
      "WISDOM COLLEGE OF EDUCATION - Tamil Nadu",
      "WISDOM D ED COLLEGE - Karnataka",
      "WISDOM TEACHER TRAINING COLLEGE - Rajasthan",
      "WLC College India - Uttar Pradesh",
      "WMO Arts & Science College - Kerala",
      "Wockhardt Institute Of Nursing , Bangalore - Karnataka",
      "Wockhardt Institute Of Nursing, Bangalore - Karnataka",
      "Women College of Home Science & BCA - Maharashtra",
      "Women India Trust, School Of Nursing, Raigad - Maharashtra",
      "Women Primary Teacher Education College - Bihar",
      "Women Primary Teacher Education College - Bihar",
      "Women Primary Teacher Training College - Jharkhand",
      "Women Primary Teacher's Education College - Bihar",
      "Women Primary Teacher's Education College - Jharkhand",
      "Women Primary Teacher's Education College (DIET) - Bihar",
      "WOMEN TEACHER TRAINING COLLEGE, BHIWANI - Haryana",
      "WOMEN TEACHER TRAINING COLLEGE, PALI - Rajasthan",
      "Women's College, Nizamabad - Andhra Pradesh",
      "Women'S Institute Of Technology, Darbhanga - Bihar",
      "Women's Polytechnic - Tripura",
      "Women's Polytechnic College - Kerala",
      "Women's Polytechnic College, Ernakulam - Kerala",
      "Women's Polytechnic College, Karaikal - Pondicherry",
      "Women's Polytechnic College, Kottakkal - Kerala",
      "Women's Polytechnic College, Kozhikode - Kerala",
      "Women's Polytechnic College, Lawspet - Pondicherry",
      "Women's Polytechnic College, Thrissur - Kerala",
      "Women's Polytechnic, Chandannagar - West Bengal",
      "Women's Polytechnic, Kayamkulam - Kerala",
      "Women's Polytechnic, Siliguri - West Bengal",
      "Women's Polytechnic, Kolkata - West Bengal",
      "Womens Christian College, Nagarcoil - Tamil Nadu",
      "Womens Christian College - West Bengal",
      "Womens Christian College, Chennai - Tamil Nadu",
      "Womens College - Meghalaya",
      "Womens College - Orissa",
      "Womens College, Jharsuguda - Orissa",
      "Womens College, Tripura - Orissa",
      "Womens College, Agartala - Tripura",
      "Womens College, Maharashtra - Orissa",
      "Womens College Silchar - Assam",
      "Womens College Tinsukia - Assam",
      "Womens Polytechnic, Chandannagar, Hooghly - West Bengal",
      "Womens Primary Teacher's Training College - Bihar",
      "Womens Training College - Bihar",
      "Woodland Institute Of Nursing, Shillong - Meghalaya",
      "Woodlands College Of Nursing, Parganas - West Bengal",
      "Woodlands Hosp. & Medical Research Centre, Calcutta, Kolkata - West Bengal",
      "World College of Technology and Management - Haryana",
      "World Institute of Technology - Haryana",
      "Wular Valley College Education - Jammu and Kashmir",
    ],
  },
];
