const JData = [
  {
    colleges: [
      "J B College - Assam",
      "J B Institute Of Nursing & Research , Gwalior - Madhya Pradesh",
      "J B S Dhanour College - Bihar",
      "J C E Trust Sanchalit Commerce College - Gujarat",
      "J C T College of Engineering and Technology - Tamil Nadu",
      "J C T TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "J D College of Engineering - Maharashtra",
      "J D College Of Nursing, kadapa - Andhra Pradesh",
      "J D S G College - Assam",
      "J D T Islam College Of Nursing , Calicut - Kerala",
      "J D T Islam Orphanage Committee, School Of Nursing,Calicut - Kerala",
      "J D Womens' College - Bihar",
      "J E E School Of Nursing,jaipur - Rajasthan",
      "J E S Mother Teresa College Of Nursing , Bangalore North - Karnataka",
      "J E S Mother Teresa College Of Nursing,Bangalore - Karnataka",
      "J Eashwari Bai Memorial School Of Nursing , Secunderabad - Andhra Pradesh",
      "J G College Commerce - Karnataka",
      "J G College Of Nursing ,Ahmedabad - Gujarat",
      "J G College Of Nusing , Ahmedabad - Gujarat",
      "J G School Of Nursing , Ahmedabad - Gujarat",
      "J J College Arrah - Bihar",
      "J J College Bihar - Bihar",
      "J J College Jharkhand - Jharkhand",
      "J J Institute Of Nursing, ,Pudukkottai - Tamil Nadu",
      "J J School Of Nursing , Secunderabad - Andhra Pradesh",
      "J K College Education - Jammu and Kashmir",
      "J K College Of General Nursing , Etawah - Uttar Pradesh",
      "J K College Of Nursing & Para Medical , Coimbatore - Tamil Nadu",
      "J K Institute Of Applied Physics Technology - Uttar Pradesh",
      "J K Institute Of Nursing & Para Medical Sciences , Jammu Tawi - Jammu and Kashmir",
      "J K K Nataraja College Arts Science - Tamil Nadu",
      "J K S College Mango - Jharkhand",
      "J L N College - Bihar",
      "J L N College Jharkhand - Jharkhand",
      "J L N Degree College - Chhattisgarh",
      "J L N Institute Of Nursing Education,Jaipur - Rajasthan",
      "J L N M College - Bihar",
      "J M College - Jharkhand",
      "J M D P L Mahila College - Bihar",
      "J M J College For Women - Andhra Pradesh",
      "J M J College Of Nursing , Hyderabad - Andhra Pradesh",
      "J M J College Of Nursing,Hyderabad - Andhra Pradesh",
      "J M M Institute of Technology - Karnataka",
      "J M S College - Bihar",
      "J M Shah Arts And Commerce College - Gujarat",
      "J N College Arunachal Pradesh - Arunachal Pradesh",
      "J S M School Of Nursing , Hyderabad - Andhra Pradesh",
      "J S S College - Karnataka",
      "J S S College Arts Commerce Science Chamrajanagar - Karnataka",
      "J S S College Arts Commerce Science Karnataka - Karnataka",
      "J S S College Arts Science Commerce Mysore - Karnataka",
      "J S S College for Women - Karnataka",
      "J S S College Karnataka - Karnataka",
      "J S S College Nanjanguda - Karnataka",
      "J S S College Of Nursing , Mysore - Karnataka",
      "J S S College Of Nursing ,Mysore - Karnataka",
      "J S S College Of Nursing, ,Mysore - Karnataka",
      "J S S College Pharmacy - Karnataka",
      "J S S College Pharmacy - Karnataka",
      "J S S Law College - Karnataka",
      "J S S Polytechnic For Physically Handicapped, Mysore - Karnataka",
      "J S S Polytechnic For Women, Mysore - Karnataka",
      "J S S Polytechnic, Njangud - Karnataka",
      "J S S School Of Nursing , Chamarajanagar - Karnataka",
      "J S S School Of Nursing , Chamarajnagara - Karnataka",
      "J S S School Of Nursing , Hassan - Karnataka",
      "J S S School Of Nursing , Mysore - Karnataka",
      "J S S Sh Tammannappa Chikkodi Arts Commerce College - Karnataka",
      "J S School Of Nursing , Ongole - Andhra Pradesh",
      "J U S S College Of Nursing & Medical Sciences , Gurdaspur - Punjab",
      "J U S S Institute Of Nursing & Medical Sciences , Gurdaspur - Punjab",
      "J V College Of Nursing , Thiruvallur - Tamil Nadu",
      "J V Institute Of Nursing, , Chennai - Tamil Nadu",
      "J Z Shah Arts H P Shah Commerce College - Gujarat",
      "J. Baruah Law College - Assam",
      "J. Buana College - Mizoram",
      "J. H. Govt. P. G. College Jaywanti Haksar Govt. P.G. College - Madhya Pradesh",
      "J. L. Verma Law College - Madhya Pradesh",
      "J. N. Konar Primary Teacher's Training Institute - West Bengal",
      "J. S. Institute of Management & Technology - Uttar Pradesh",
      "J. S. S. Law College - Karnataka",
      "J. S. S. Sakri Law College - Karnataka",
      "J. S. T. Govt. P.G. College - Madhya Pradesh",
      "J. Sikkle Degree College, Narsapur - Andhra Pradesh",
      "J. T. Mahajan Polytechnic - Maharashtra",
      "J. V. Jain College - Uttar Pradesh",
      "J.A. Arts And Science College - Tamil Nadu",
      "J.A.S. COLLEGE OF EDUCATION - Tamil Nadu",
      "J.B. INSTITUTE OF PG STUDIES - Andhra Pradesh",
      "J.B. Law College - Assam",
      "J.B. Shah Girls College - Rajasthan",
      "J.B. TEACHERS TRAINING INSTITUTE - Rajasthan",
      "J.B.M.TEACHER TRAINING COLLEGE - Haryana",
      "J.B.S.P. Mandal Instt. of Pharmacy , GEORAI - Maharashtra",
      "J.B.S.P. Mandal's arts College - Maharashtra",
      "J.B.S.P. Mandal's Mahila Mahavidyalaya - Maharashtra",
      "J.B.TEACHER TRAINING INSTITUTE - Rajasthan",
      "J.C. D.A.V. College - Punjab",
      "J.C. Education Trust Law College - Gujarat",
      "J.C. Mills Girls College - Madhya Pradesh",
      "J.D. Patil Sangludkar Arts & Commerce College - Maharashtra",
      "J.D.B. Girls College - Rajasthan",
      "J.D.C. Bytco Institute of Mangement Studies & Research - Maharashtra",
      "J.D.C. BYTECO INSTITUTE OF MANAGEMENT STUDIES - Maharashtra",
      "J.D.J.B. ANAND DEGREE COLLEGE - Uttar Pradesh",
      "J.D.M.V.P. Coop. Samajs Arts Science & Commerce College - Maharashtra",
      "J.D.M.V.P. Coop. Samajs Arts Science & Commerce College' - Maharashtra",
      "J.D.T. Islam College Of Arts & Science - Kerala",
      "J.D.TEACHER TRAINING COLLEGE - Punjab",
      "J.D.Women's College, Patna - Bihar",
      "J.E. COOP.SYS D.ED COLLEGE - Karnataka",
      "J.E.C.R.C. University - Rajasthan",
      "J.E.S. College of Pharmacy , NANDURBAR - Maharashtra",
      "J.E.S. Degree College For Women - Andhra Pradesh",
      "J.E.S.S.R.J.B. Artss.B.L. Commerce And R.Bezoji Science College - Maharashtra",
      "J.G.K.P. TEACHER TRAINING INSTITUTE - Karnataka",
      "J.G.TEACHER TRAINING COLLEGE - Haryana",
      "J.H. Patel College of Management and Technology - Gujarat",
      "J.J COLLEGE OF EDUCATION - Tamil Nadu",
      "J.J Polytechnic College - Tamil Nadu",
      "J.J. College Of Arts And Science - Tamil Nadu",
      "J.J. COLLEGE OF EDUCATION - Tamil Nadu",
      "J.J. College of Engg & Technology - Tamil Nadu",
      "J.J. College of Pharmacy Sciences, Maheshwaram - Andhra Pradesh",
      "J.J. Polytechnic College - Tamil Nadu",
      "J.J. ROJAA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "J.j.c.e.trust Sanchalit N.r.vrkaria Institute Of Technology - Gujarat",
      "J.J.M. Medical College - Karnataka",
      "J.J.M. Medical College - Karnataka",
      "J.J.R. EDUCATION SOCIETY(R) - Karnataka",
      "J.K COLELGE OF EDCATION - Tamil Nadu",
      "J.K. Institute of Engineering - Chhattisgarh",
      "J.K. Lakshmipat University - Rajasthan",
      "J.K. PADAMPAT SINGHANIA INSTITUTE OF MGT. & TECH - Haryana",
      "J.K.C. College - Andhra Pradesh",
      "J.K.COLLEGE OF EDUCATION - Tamil Nadu",
      "J.K.K. Munirajah College of Technology - Tamil Nadu",
      "J.K.K. Nataraja College of Engineering and Technology - Tamil Nadu",
      "J.K.K. Nataraja College of Pharmacy , Komarapalayam - Tamil Nadu",
      "J.K.K.NATTRAJA COLLEGE OF PHARMACY,ERODE - Tamil Nadu",
      "J.K.MEMORIAL TEACHER TRAINING COLLEGE - Haryana",
      "J.L. MEMORIAL TEACHER TRAINING COLLEGE, - Rajasthan",
      "J.L. Nehru Degree College - Uttar Pradesh",
      "J.L. Nehru Law College - Madhya Pradesh",
      "J.L. Nehru Law College - Madhya Pradesh",
      "J.L. Nehru Memorial Mahavidyalaya - Madhya Pradesh",
      "J.L. Nehru Smarak PG College - Uttar Pradesh",
      "J.L. Verma Law College - Madhya Pradesh",
      "J.L.N. Government College For Women - Punjab",
      "J.M. Institute of Speech & Hearing - Bihar",
      "J.M. Pandya Diploma Pharmacy College , Vadodara - Gujarat",
      "J.M. Patel Arts Commerce & Science College - Maharashtra",
      "J.M. PATEL COLLEGE - Maharashtra",
      "J.M.J D.ED COLLGE - Karnataka",
      "J.M.J. Degree College For Women - Andhra Pradesh",
      "J.M.J. Degree College For Women - Andhra Pradesh",
      "J.M.S. COLLEGE OF EDUCATION - Tamil Nadu",
      "J.N. College - Orissa",
      "J.N. College - Arunachal Pradesh",
      "J.N. College Of Technology - Madhya Pradesh",
      "J.N. PAUL INSTITUTE OF EDUCATION - Uttaranchal",
      "J.N.M.P MAHAVIDAYALYA - Uttar Pradesh",
      "J.N.N TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "J.P. COLLEGE OF EDUCATION - Karnataka",
      "J.P. Gupta Institute of Law - Madhya Pradesh",
      "J.P. Institute of Education - Uttar Pradesh",
      "J.P. Verma Science Mahavidyalaya - Uttar Pradesh",
      "J.P.C.L.DEGREE COLLEGE - Uttar Pradesh",
      "J.P.E TEACHER TRAINING INSTITUTE - Kerala",
      "J.P.INSTITUTE OF EDUCATION AND TECHNOLOGY - Uttar Pradesh",
      "J.P.Institute of Hotel Management & Catering Technology - Uttar Pradesh",
      "J.R. INSTITUTE OF EDUCATION - Haryana",
      "J.R. Kissan Homoeopathic Medical College and Hospital - Haryana",
      "J.R. MEMORIAL TEACHER TRAINING COLLEGE - Haryana",
      "J.R.D. Polytechnic, Vallakandini - Karnataka",
      "J.R.KISSAN TEACHER TRAINING COLLEGE - Haryana",
      "J.R.M. Adarsh Bhartiya Collegeof Pharmacy , Pathankot - Punjab",
      "J.R.R. Navodaya Degree College - Andhra Pradesh",
      "J.R.S.E.T College of Education - West Bengal",
      "J.S INSTITUTE OF EDUCATION - Uttar Pradesh",
      "J.S. ACADEMY - Uttar Pradesh",
      "J.S. Hindu Post-graduate College - Uttar Pradesh",
      "J.S. Hindu Postgraduate College - Uttar Pradesh",
      "J.S.COLLEGE OF EDUCATION - Uttar Pradesh",
      "J.S.College of Education - Uttar Pradesh",
      "J.S.HINDU DEGREE COLLEGE - Uttar Pradesh",
      "J.S.J.V. B.ED COLLEGE - Tamil Nadu",
      "J.S.M. ACODEMY , - Uttar Pradesh",
      "J.S.P.M. Sudhakar Rao Naik Institute of Pharmacy , Pusad - Maharashtra",
      "J.S.P.S. Govt. Homoeopathic Medical College - Andhra Pradesh",
      "J.S.P.Ss College Of Education - Maharashtra",
      "J.S.S Medical College, Mysore - Karnataka",
      "J.S.S. College of Pharmacy , Mysore - Karnataka",
      "J.S.S. College of Pharmacy , Ooty - Tamil Nadu",
      "J.S.S. Dental College & Hospital - Karnataka",
      "J.S.S. INSTITUTE OF EDUCATION - Karnataka",
      "J.S.S. INSTITUTE OF EDUCATION - Karnataka",
      "J.S.S. Kisan Veer Mahavidyalaya - Maharashtra",
      "J.S.S. Law College - Karnataka",
      "J.S.S. TEACHER TRAINING INSTITUTE FOR WOMEN - Karnataka",
      "J.S.S.College of Pharmacy , Ooty - Tamil Nadu",
      "J.S.S.S.S.S. DiplomaPharmacy College , Anand - Gujarat",
      "J.T. COLLEGE - Uttar Pradesh",
      "J.T.E.Ss Arts Commerce & Science College - Maharashtra",
      "J.Thankima College - Mizoram",
      "J.V. Jain College - Uttar Pradesh",
      "J.V. JAIN COLLEGE - Uttar Pradesh",
      "J.V. Jain College - Uttar Pradesh",
      "J.V. JAIN PG COLLEGE - Uttar Pradesh",
      "Jaagruthi Degree College - Andhra Pradesh",
      "JAANAGI INSTITUTE OF TEACHER EDUCATION - Tamil Nadu",
      "JAAT TEACHER TRAINING COLLEGE - Haryana",
      "Jabalpur Institute Of Health Sciences, Jabalpur - Madhya Pradesh",
      "Jabalpur Institute Of Nursing Science & Research , Jabalpur - Madhya Pradesh",
      "Jabalpur Institute Of Nursing Sciences & Research , Jabalpur - Madhya Pradesh",
      "Jackman School Of Nursing , Bilaspur - Chhattisgarh",
      "jadavpur university - West Bengal",
      "Jadavpur Vidyapith College of Education - West Bengal",
      "JADCHERLA POST GRADUATE COLLEGE - Andhra Pradesh",
      "JADEED ANJUMAN-E-TALEEM J.A.T. JUNIOR COLLEGE OF EDUCATION - Maharashtra",
      "Jadid Anjuman E Talem Arts Science & Commerce Girl - Maharashtra",
      "Jadid Anjuman E Talem Arts Science & Commerce Girls  College - Maharashtra",
      "Jadupati +3 College - Orissa",
      "JAG NARAYAN SHUKLA GRAMODAYA MAHAVIDYALAYA - Uttar Pradesh",
      "JAGADAMBA BAHUUDESHIYA GRAMIN VIKAS SANSTHA - Maharashtra",
      "JAGADGURU ANNADANESHWAR T.T.I - Karnataka",
      "Jagadguru Dattatray College Of Technology - Madhya Pradesh",
      "JAGADGURU RAMANANDACHARYA RAJASTHAN - Rajasthan",
      "Jagadguru Ramanandacharya Sanskrit University - Rajasthan",
      "JAGADGURU RAMBHADRACHARYA HANDICAPPED UNIVERSITY - Uttar Pradesh",
      "Jagadguru Rambhadracharya Handicapped University - Uttar Pradesh",
      "Jagadguru Shankarachariya College Of Nursing , Raipur - Chhattisgarh",
      "Jagadguru Shankaracharya College Of Nursing,Raipur - Chhattisgarh",
      "Jagadguru Sri Shivarathreeshwara College of Pharmacy , Mysore - Karnataka",
      "Jagadguru Sri Shivarathreeswara University - Karnataka",
      "Jagadish Chandra Basu Sikshak Sikshan Mahavidyalaya - West Bengal",
      "JAGADURU SRI RENUKACHARYA D. ED COLLEGE - Karnataka",
      "JAGAN INSTITUTE OF MANAGEMENT STUDIES - Delhi",
      "JAGAN INSTITUTE OF MANAGEMENT STUDIES - Rajasthan",
      "Jagan Nath University - Rajasthan",
      "JAGAN SHIKSHAK PRASHIKSHAN SANSTHAN - Rajasthan",
      "JAGAN'S INSTITUTE OF MANAGEMENT STDS - Andhra Pradesh",
      "Jaganath Mishra Law College - Bihar",
      "Jagannath Gupta Institute Of Engineering And Technology - Rajasthan",
      "Jagannath Institute For Technology And Management. - Orissa",
      "Jagannath Institute of Engineering & Technology - Orissa",
      "JAGANNATH INTERNATIONAL MANAGEMENT SCHOOL - Delhi",
      "Jagannath Jain College - Jharkhand",
      "Jagannath Kishore College - West Bengal",
      "Jagannath Mahavidyalaya (Degree College) - Orissa",
      "Jagannath Mishra Institute of Technology - Bihar",
      "Jagannath Munna Lal Choudhry Mahila Mahavidyalaya - Madhya Pradesh",
      "JAGANNATH PRASAD SMARAK COLLEGE OF EDUCATION - Uttar Pradesh",
      "Jagans Degree College - Andhra Pradesh",
      "Jagans Institute Of Science & Tech - Andhra Pradesh",
      "Jagarlamudi Kuppuswamy Choudhry College - Andhra Pradesh",
      "Jagruthi Degree College, Huzurabad - Andhra Pradesh",
      "Jagruthi Degree College, Mahabubnagar - Andhra Pradesh",
      "Jagruthi Degree College, Medak - Andhra Pradesh",
      "Jagruthi Degree College, Nalgonda - Andhra Pradesh",
      "Jagruti Institute of Engineering and Technologys - Andhra Pradesh",
      "Jagta Arts college - Maharashtra",
      "JAGWANT SINGH BHADORIA DEGREE COLLEGE - Uttar Pradesh",
      "Jahnavi Degree College - Andhra Pradesh",
      "Jahnavi Degree College, Secunderabad - Andhra Pradesh",
      "Jahnavi School Of Nursing , Bangalore - Karnataka",
      "Jahnavi Womens Degree College - Andhra Pradesh",
      "Jai Ambey Education Society, School Of Nursing , Hoshiarpur - Punjab",
      "JAI ARIHANT ACADEMIC INSTITUTE - Uttaranchal",
      "JAI BAJRANG COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Jai Bajrang Shiv Gulam Mahavidyalaya - Uttar Pradesh",
      "JAI BHAGWAN COLLEGE OF EDUCATION - Maharashtra",
      "JAI BHARAT TEACHER TRAINING COLLEGE - Haryana",
      "JAI BHARATH ARTS AND SCIENCE COLLEGE - Kerala",
      "JAI BHARATH TRAINING COLLEGE - Kerala",
      "Jai Bharati College - Madhya Pradesh",
      "JAI DURGA BHAWANI KRIDA MANDAL - Maharashtra",
      "Jai Durga College Of Nursing ,Jaipur - Rajasthan",
      "Jai Durga College Of Nursing,Jaipur - Rajasthan",
      "JAI GANESH EDUCATIONAL FOUNDATION - Maharashtra",
      "JAI GEETAANJALI TEACHER TRAINING COLLEGE - Haryana",
      "JAI HIND COLLEGE - Karnataka",
      "Jai Hind Defence College of Law - Madhya Pradesh",
      "Jai Hind Education Trusts Arts Science And Commerce College - Maharashtra",
      "Jai Hind Educational Trusts Zulal Bhilajirao Patil College - Maharashtra",
      "JAI HIND VISMIL EDUCATION COLLEGE - Madhya Pradesh",
      "Jai Institute Of Nursing & Research , Gwalior - Madhya Pradesh",
      "Jai Institute Of Nursing And Research Centre , Gwalior - Madhya Pradesh",
      "JAI JAWAN JAI KISAN SHIKSHAN PRASARAK MANDAL - Maharashtra",
      "JAI JYOTHI EDUCATION SOCIETY - Karnataka",
      "JAI KARNATAKA D.ED COLLEGE - Karnataka",
      "JAI KISAN SHIKSHAN SANSTHAS COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Jai Mahakali Shikshan Sanstha Agnihotri Polytechnic - Maharashtra",
      "Jai Mahakali Shikshan Sanstha Law College - Maharashtra",
      "JAI MAHAKALI SHIKSHAN SANSTHA RANIBAI AGNIHOTRI INSTITUTE OF COMPUTER  IN FORMATION TECHNOLOGY - Maharashtra",
      "JAI MAHAKALI SHIKSHAN SANSTHAS - Maharashtra",
      "Jai Mahakali Shikshan Sansthas Agnihotri College of Law - Maharashtra",
      "JAI MARUDHAR KESARI TEACHER TRAINING COLLEGE - Rajasthan",
      "Jai Mata School Of Nursing & Medical Sciences,Hisar - Haryana",
      "JAI MATA TEACHER TRAINING COLLEGE - Haryana",
      "Jai Narain Samarak Degree College - Uttar Pradesh",
      "JAI NARAIN SMARAK DEGREE COLLEGE - Uttar Pradesh",
      "Jai Narain Vyas University - Rajasthan",
      "Jai Narain Vyas University - Rajasthan",
      "Jai Narayan College of Tech. & Sc., JNCTS - Madhya Pradesh",
      "Jai Narayan Vyas School of Pharmacy & Diploma Engineering, Barmer - Rajasthan",
      "Jai Narayan Vyas School of Pharmacy , Barmer - Rajasthan",
      "JAI NARAYAN VYAS UNIVERSITY - Rajasthan",
      "Jai Polytechnic, Shahabad - Haryana",
      "JAI PRAKASH DEGREE COLLEGE - Uttar Pradesh",
      "Jai Prakash Mahavidyalaya Umarhan - Uttar Pradesh",
      "Jai Prakash Vishwavidyalaya - Bihar",
      "JAI RUPA COLLEGE OF EDUCATION - Tamil Nadu",
      "JAI SAI TRAINIG COLLEGE - Tamil Nadu",
      "JAI SAKTHI COLLEGE OF EDUCATION - Tamil Nadu",
      "JAI SHANTHI COLLEGE OF EDUCATION - Tamil Nadu",
      "JAI SHREE DAYAL TEACHERS TRAINING COLLEGEKAIRWALI, POST - PUPNBAS TEHSIL - NEEMKA THANA - Rajasthan",
      "JAI SHRI TEACHER S TRAINING INSTITUTE - Tamil Nadu",
      "JAI SHRIRAM B.ED. COLLEGE - Madhya Pradesh",
      "JAI SRI VENKATESHWARA COLLEG OF EDUCATION - Tamil Nadu",
      "Jaideo Education Society - Maharashtra",
      "Jain Asthanak Vasi Girls Degree College - Uttar Pradesh",
      "JAIN BALIKA VIDVAPEETH - Uttar Pradesh",
      "JAIN BHARTI INSTITUTE OF HIGHER EDUCATION - Delhi",
      "Jain College Of Education - Madhya Pradesh",
      "JAIN COLLEGE OF EDUCATION - Madhya Pradesh",
      "Jain College of Engineering, Bangalore - Karnataka",
      "Jain College of MCA and MBA - Karnataka",
      "Jain Degree College - Madhya Pradesh",
      "Jain Girls Degree College - Uttar Pradesh",
      "JAIN INSTITUTE - Madhya Pradesh",
      "Jain Jawan College - Madhya Pradesh",
      "JAIN MAHILA MANDAL WOMENS COLLEGE OF EDUCATION - Karnataka",
      "Jain Pathshala Walchand Institute of Technology - Maharashtra",
      "JAIN TEACHER TRAINING COLLEGE - Punjab",
      "Jain University - Karnataka",
      "Jain Vishva Bharati University - Rajasthan",
      "JAIN VISHWA SHARTI INSTITUTE LADNUN - Rajasthan",
      "Jainee College Of Nursing , Dindigul - Tamil Nadu",
      "Jainee School Of Nursing ,Dindigul - Tamil Nadu",
      "Jaipur College Of Nursing And Hospital,Jaipur - Rajasthan",
      "Jaipur College of Pharmacy , Jaipur - Rajasthan",
      "Jaipur College Of Post Basic Nursing, , Jaipur - Rajasthan",
      "Jaipur Dental College , Jaipur - Rajasthan",
      "Jaipur Engineering College - Rajasthan",
      "Jaipur Engineering College and Research Centre - Rajasthan",
      "Jaipur Hospital College Of Nursing , Jaipur - Rajasthan",
      "Jaipur Hospital College Of Nursing,Jaipur - Rajasthan",
      "Jaipur Hospital School Of Nursing , Jaipur - Rajasthan",
      "Jaipur Institute of Polytechnic & Technology - Rajasthan",
      "Jaipur Institute of Technology - Rajasthan",
      "Jaipur Law College - Rajasthan",
      "JAIPUR NATIONAL UNIVERSITY - Rajasthan",
      "Jaipur National University - Rajasthan",
      "Jaipur Nursing College , Jaipur - Rajasthan",
      "Jaipur Polytechnic College - Rajasthan",
      "Jaipur School Of General Nursing & Midwifery , Jaipur - Rajasthan",
      "JAIPURA INSTITUTE OF MANAGEMENT - Uttar Pradesh",
      "Jaipuria Institute of Management - Uttar Pradesh",
      "Jaipuria Institute of Management Indore - Madhya Pradesh",
      "Jaipuria Institute of Management, Jaipur - Rajasthan",
      "Jairam Arts And Science College - Tamil Nadu",
      "JAIRAM COLLEGE OF EDUCATION - Tamil Nadu",
      "Jairuppa College Of Engineering - Tamil Nadu",
      "Jaisingpur College - Maharashtra",
      "Jaiswal College Of B Sc Nursing,Kota - Rajasthan",
      "Jaiswal College Of Nursing ,Kota - Rajasthan",
      "Jaiswal School Of Nursing ,Kota - Rajasthan",
      "Jaiswal School Of Nursing,Kota - Rajasthan",
      "Jaju School Of Nursing,Ajmer - Rajasthan",
      "Jakh Institute Of Nursing , Shimla - Himachal Pradesh",
      "Jakir Hussa in B.Ed. College - West Bengal",
      "JAL PRAKASH INSTITUTE OF EDUCATION - Uttar Pradesh",
      "JAL PRAKASH INSTITUTE OF EDUCATION - Uttar Pradesh",
      "Jalagamvengalrao Government College - Andhra Pradesh",
      "Jalangi B.Ed. College - West Bengal",
      "Jaleswar College",
      "Jaleswar Womens College",
      "Jalna Education Society, Institute of Pharmacy , JALNA",
      "Jalna Nursing School,jalna",
      "Jalpaiguri Dooars Primary Teacher TrainingInstitute",
      "jalpaiguri Government Engineering College",
      "Jalpaiguri Law College",
      "Jalpaiguri Polytechnic Institute",
      "JAMAL MOHAMED COLLEGE OF TEACHER EDUCATION",
      "Jamal Mohammed College",
      "Jamalpur College",
      "Jamanlal Goenka Dental College & Hospital , Akola",
      "JAMEELA BEEVI MEMORAL CENTRE FOR TEACHER EDUCATION",
      "James College Engineering Technology",
      "JAMES COLLEGE OF EDUCATION",
      "Jamia College of Pharmacy , Nandurbar",
      "Jamia Hamdard Deemed University",
      "JAMIA ISLAMIA ISHAATUL ULOOMS JAMIA COLLEGE OF EDUCATION",
      "Jamia Milia Islamia, Institute of Advanced Studies in Education",
      "Jamia Millia Islamia University",
      "JAMIA NADAWIYYA TEACHERS TRAINING INSTITUTE",
      "Jamia Salafiya Pharmacy College , PULIKKAL",
      "JAMIA SALAFLA PRE PRIMARY TEACHER TRAINING INSTITUTE",
      "JAMIYA ISLAMIYA ISHATUL OLU JAMIA POLYTECHNIC AKKALKUWA",
      "Jamkhed Mahavidyalaya",
      "Jammu Law College",
      "JAMNA GIRLS TEACHER TRAINING COLLEGE",
      "Jamna Lal Ram Lal Keemti Girls College",
      "JAMNALAL BAJAJ INSTITUTE OF MANAGEMENT STUDIES",
      "Jamshedpur Co Operative College",
      "Jamshedpur Cooperative College",
      "Jamshedpur Cooperative Law College",
      "Jamshedpur Women'S College",
      "Jamshedpur Women's College",
      "Jamshedpur Womens College",
      "Jamshedpur Womens College",
      "Jamshedpur Workers College",
      "Jamtara College",
      "JAMUNA DEVI NBARESH CHANDRA MAHAVIDYALAYA",
      "Jamuna Prasad Bhagwan Das Mahajan Degree College",
      "Jamuna Prasad Bhagwan Das Mahajan Mahila Mahavidyalaya",
      "Jamuni Lal College",
      "JAMWA MATA TEACHERS TRAINING INSTITUTE",
      "Jamwamata College of Polytechnic",
      "Jan Kalyan Institute of Technical Education , Lucknow",
      "JAN KALYAN SHIKSHA SAMITI",
      "Jan Nayak Ch Devi Lal Memorial College of Engineering",
      "Jan Nayak Ch. Devi Lal Dental College , Sirsa",
      "Jan Nayak Ch. Devi Lal Polytechnic",
      "JAN NAYAK CH. DEVI LAL TEACHER TRAINING COLLEGE",
      "Jan Nayak Ch. Devilal Diploma College of Pharmacy , Sirsa",
      "Jan Sewa Rugnalay , Hausangabad",
      "Jan Swasthya Sahyog,Bilaspur",
      "Jana Hitha Degree College, Vizianagaram",
      "JANAK RAJ MAHAJAN TEACHER TRAINING COLLEGE",
      "Janakalyan School Of Nursing , Kendrapara",
      "Janaki Mahiladhar Pratishthan - Maharashtra",
      "Janardan Rai Nagar Rajasthan Vidyapeeth - Rajasthan",
      "Janarth Shikshan Prasarak Mandal - Maharashtra",
      "Janaseva Shikshan Mandal College of Arts & Commerce - Maharashtra",
      "Janata College - Orissa",
      "Janata College - Orissa",
      "Janata College - Assam",
      "Janata College Assam - Assam",
      "Janata Nursing School - Maharashtra",
      "Janata Shikshan Baba Sahib Naik College of Engineering - Maharashtra",
      "JANATA SHIKSHAN PRASAR SANGH COLLEGE OF EDUCATION - Karnataka",
      "JANATA SHIKSHAN PRASARAK MANDAL - Maharashtra",
      "JANATA SHIKSHAN PRASARAK MANDAL - Maharashtra",
      "Janata Shikshan Prasarak Mandals Dr.N.P.Hirani Polytechnic - Maharashtra",
      "JANATA SHIKSHAN SANGHA JANATA SHIKSHAN SANGHA - Karnataka",
      "JANATA VIDYAVARDHAKA SANGHAS D.ED COLLEGE - Karnataka",
      "Janatha Education Society Vivekananda College of Pharmacy - Karnataka",
      "Janatha Hospital, School Of Nursing - Kerala",
      "Janatha School Of Nursing - Karnataka",
      "JANATHA SEVA SHIKSHANA SAMSTHE - Karnataka",
      "JANATHA TEACHER TRAINING INSTITUTE - Karnataka",
      "Jancy Centre for Special Education - Kerala",
      "Jangaon Institute of Pharmaceutical Sciences - Andhra Pradesh",
      "JANGI DEGREE COLLEGE - Uttar Pradesh",
      "Jangi Mahavidyalaya - Uttar Pradesh",
      "Jangipur College - West Bengal",
      "Janhavi School Of Nursing - Karnataka",
      "Janhit College of Law - Uttar Pradesh",
      "JANHIT INSTITUTE OF EDUCATION - Uttar Pradesh",
      "JANHIT INSTITUTE OF EDUCATION & INFORMATION - Uttar Pradesh",
      "JANHIT INSTITUTE OF EDUCATION & INFORMATION - Uttar Pradesh",
      "Jankalyan Vikas Mandal Swargiya Lilawati Satish Award D.Pharmacy College , Nanded - Maharashtra",
      "Janki Devi Memorial College - Delhi",
      "JANKI JI INSTITUTE OF MANAGEMENT & TECHNOLOGY - Haryana",
      "JANKI JI TEACHER TRAINING COLLEGE - Haryana",
      "JANKI PRASAD CHOUDHARY MAHILA MAHAVIDYALAYA - Uttar Pradesh",
      "JANKIDAS KAPUR TEACHER TRAINING COLLEGE - Haryana",
      "Jankidevi Bajaj College of Science - Maharashtra",
      "JANKIDEVI BAJAJ INSTITUTE OF MANAGEMENT STUDIES - Maharashtra",
      "JANKIJI TEACHER TRAINING COLLEGE - Haryana",
      "JANKIJI TEACHER TRAINING COLLEGE - Haryana",
      "Jannayak Karpuri Thakur Vidhi Mahavidyalay - Bihar",
      "Janseva Mandals Sai Homoeopathic Medical College - Maharashtra",
      "JANSEVA SHIKSHAN MANDALS COLLEGE OF EDUCATION - Maharashtra",
      "Jansons Institute of Technology - Tamil Nadu",
      "JANSONS SCHOOL OF BUSINESS - Tamil Nadu",
      "Janta College - Madhya Pradesh",
      "Janta College Of Education - Maharashtra",
      "Janta College of Pharmacy , Sonepat - Haryana",
      "Janta Degree College - Uttar Pradesh",
      "Janta Degree College - Uttar Pradesh",
      "Janta Degree College - Uttar Pradesh",
      "JANTA JUNIOR COLLEGE OF EDUCATION - Maharashtra",
      "Janta Kala Vanijya Mahavidyalaya - Maharashtra",
      "Janta Koshi College - Bihar",
      "Janta Mahavidalaya - Maharashtra",
      "Janta Mahavidyalaya - Maharashtra",
      "Janta Mahavidyalaya - Maharashtra",
      "JANTA MAHAVIDYALAYA - Uttar Pradesh",
      "Janta Mahavidyalaya - Uttar Pradesh",
      "Janta Mahavidyalaya - Uttar Pradesh",
      "Janta Mahavidyalaya - Madhya Pradesh",
      "Janta Mahavidyalaya (PG) College - Uttar Pradesh",
      "Janta Mahavidyalaya (PG) College - Uttar Pradesh",
      "Janta Polytechnic Butana - Haryana",
      "Janta Polytechnic, Jahangirabad - Uttar Pradesh",
      "Janta Polytechnic, Jhangirabad (Bulandshar) - Uttar Pradesh",
      "Janta Raja Sahu Maharaj Special Training Centre - Maharashtra",
      "JANTA SHIKSHAN PRASARAK MANDALS COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Janta Shivratri College - Jharkhand",
      "JANTA TEACHER TRAINING COLLEGE - Haryana",
      "Janta Vedic College - Uttar Pradesh",
      "JANTA VEDIC COLLEGE - Uttar Pradesh",
      "Janta Vidhi Mahavidyalaya - Madhya Pradesh",
      "Janta Vidya Mandir G R R College - Haryana",
      "Japfu Christain College - Nagaland",
      "Jasdev Singh Sandhu Institute of Engineering - Punjab",
      "JASDEV SINGH SANDHU TEACHER TRAINING COLLEGE - Punjab",
      "Jashbhai Maganbhai Patel College of Commerce - Maharashtra",
      "Jashipur College - Orissa",
      "Jaslok College Of Nursing , Mumbai - Maharashtra",
      "JASMIN COLLEGE - Karnataka",
      "Jasmine School of Nursing , Bidar - Karnataka",
      "JASMINE TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JASODA DEVI COLLEGE - Rajasthan",
      "Jasoda Devi Polytechnic College, Dudu - Rajasthan",
      "JASODA DEVI TEACHERS TRAINING COLLEGE - Rajasthan",
      "JASPAL RANA INSTITUTE OF EDUCATION AND TECHNOLOGY - Uttaranchal",
      "JASRANA DEGREE COLLEGE - Uttar Pradesh",
      "Jat College of Polytehnic - Haryana",
      "Jat Education Society, Chhotu Ram Institute of Law",
      "JAT TEACHER TRAINING COLLEGE",
      "Jatadhari Degree College",
      "JATADHARI MAHAVIDYALAYA",
      "Jatan Swarup Degree College",
      "Jatindra Rajendra Mahavidyalaya",
      "Jatipita College of Engineering",
      "Jatiya Kabi Birakishore College",
      "Jawahar Arts Science & Commerce College",
      "Jawahar Bharathi College",
      "JAWAHAR BHARATHI EDUCATIONAL AND CHARITABLE TRUST",
      "Jawahar Bharati Degree College",
      "Jawahar College Education",
      "JAWAHAR COLLEGE OF EDUCATION",
      "Jawahar E.Soc's Annasaheb C.Patel Col Of Eng",
      "JAWAHAR EDUCATION SOCIETYS COLLEGE OF PHYSICAL EDUCATION",
      "Jawahar Engineering College",
      "Jawahar Lal Darda Institute of Engineering, Gandhi Bhavan",
      "JAWAHAR LAL NEHARU TEACHERS TRAINING COLLEGE",
      "Jawahar Lal Nehru College Of Education",
      "Jawahar Lal Nehru Degree College",
      "JAWAHAR LAL NEHRU DEGREE COLLEGE",
      "Jawahar Lal Nehru Hospital, School Of Nursing, Ajmer",
      "Jawahar Lal Nehru Medical College",
      "Jawahar Lal Nehru Polytechnic, Mehmudabad, Sitapur",
      "JAWAHAR LAL NEHRU TEACHER TRAINING COLLEGE",
      "JAWAHAR LAL NEHRU TEACHERS TRAINING COLLEGE",
      "JAWAHAR LAL SMARAK POST GRADUATE COLLEGE",
      "Jawahar Law College",
      "Jawahar Science College",
      "JAWAHAR SHIKSHAN PRASARAK SANSTHAS COLLEGE OF EDUCATION",
      "JAWAHAR VIDHYAPEETH TEACHERS TRAINING COLLEGE",
      "Jawaharlal College of Engineering and Technology",
      "Jawaharlal Institute Of Post Graduate Medical Education And Research J I P M E R , Pondicherry",
      "Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry",
      "Jawaharlal Institute of Technology",
      "Jawaharlal Instt of PG Medical Edu & Research",
      "Jawaharlal Instt. of P.G. Medical Edu. & Research",
      "Jawaharlal Nehru Architecture and Fine Arts University",
      "Jawaharlal Nehru Centre for Advanced Scientific Research",
      "Jawaharlal Nehru College",
      "JAWAHARLAL NEHRU COLLEGE",
      "Jawaharlal Nehru College",
      "JAWAHARLAL NEHRU COLLEGE OF EDUCATION",
      "Jawaharlal Nehru College of Technology",
      "Jawaharlal Nehru Degree College",
      "Jawaharlal Nehru Homoeopathic Medical College",
      "Jawaharlal Nehru Institute of Medical Sciences,Porompet,Imphal",
      "Jawaharlal Nehru Institute of Technology",
      "Jawaharlal Nehru Krishi Vishwavidyalaya",
      "Jawaharlal Nehru Law College",
      "Jawaharlal Nehru Medical College",
      "Jawaharlal Nehru Medical College and Associated Group of Hospital",
      "Jawaharlal Nehru Medical College, Ajmer",
      "Jawaharlal Nehru Medical College, Aligarh",
      "Jawaharlal Nehru Medical College, Belgaum",
      "Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha",
      "Jawaharlal Nehru Memorial Postgraduate College",
      "Jawaharlal Nehru National College of Engineering",
      "Jawaharlal Nehru School Of Nursing , Imphal",
      "JAWAHARLAL NEHRU SMARK (PG) COLLEGE - Uttar Pradesh",
      "JAWAHARLAL NEHRU SMRUTI MAHAVIDYALAYA - Madhya Pradesh",
      "JAWAHARLAL NEHRU SMRUTI MAHAVIDYALAYA - Madhya Pradesh",
      "JAWAHARLAL NEHRU TEACHER TRAINING INSTITUTE - Karnataka",
      "Jawaharlal Nehru Teachers' Training College - Rajasthan",
      "Jawaharlal Nehru Technological University - Andhra Pradesh",
      "Jawaharlal Nehru Technological University Kakinada - Andhra Pradesh",
      "Jawaharlal Nehru University - Delhi",
      "Jawaharlal Nehur Arts Commerce & Science College - Maharashtra",
      "Jawharlal Nehru College - Orissa",
      "JAY BAJRANG MAHILA MAHAVIDYALAYA - Uttar Pradesh",
      "Jay Bajrang Yuvak Education Charitable Trust , Rajkot - Gujarat",
      "JAY HIND DEFENCE COLLEGE - Madhya Pradesh",
      "Jay Hind Nursing School,Hingoli - Maharashtra",
      "Jay Institute Of Nursing,Pune - Maharashtra",
      "JAY MURTI COLLEGE - Uttar Pradesh",
      "Jay Prakash Degree Mahavidyalaya - Orissa",
      "Jay Shriram Group Of Institutions - Tamil Nadu",
      "Jay Siya The College Of Nursing , Gwalior - Madhya Pradesh",
      "Jay Somnath Institute Of Nursing Education , Rajkot - Gujarat",
      "Jaya Chandra (Jc) Degree College - Andhra Pradesh",
      "Jaya College Of Arts And Science - Tamil Nadu",
      "Jaya College Of B Sc Nursing,warangal - Andhra Pradesh",
      "JAYA COLLEGE OF EDUCATION - Tamil Nadu",
      "Jaya College Of Hotel And Catering Management - Tamil Nadu",
      "Jaya College Of Nursing , Warangal - Andhra Pradesh",
      "Jaya College Of Nursing, Secunderabad - Andhra Pradesh",
      "Jaya College of Pharmacy - Tamil Nadu",
      "Jaya College of Physiotherapy - Tamil Nadu",
      "Jaya Degree College - Andhra Pradesh",
      "Jaya Institute of Business Management - Andhra Pradesh",
      "Jaya Institute Of Technology - Tamil Nadu",
      "Jaya Nanda College - Bihar",
      "Jaya Polytechnic College - Tamil Nadu",
      "Jaya Polytechnic College - Tamil Nadu",
      "Jaya Prakash Narayan College of Engineering - Andhra Pradesh",
      "Jaya School of Nursing - Tamil Nadu",
      "Jaya School Of Nursing , Hanumakonda - Andhra Pradesh",
      "Jaya School of Nursing , Hyderabad - Andhra Pradesh",
      "Jaya School of Nursing , Secunderabad - Andhra Pradesh",
      "Jaya School Of Nursing,Gwalior - Madhya Pradesh",
      "Jaya School Of Nursing,Warangal - Andhra Pradesh",
      "Jaya Suriya Engineering College - Tamil Nadu",
      "JAYA VIGNESH TEACHERS TRAINING INSTITUTE - Tamil Nadu",
      "Jayagovind Harigopal Agarwal Agarsan College - Tamil Nadu",
      "Jayalakshmi Institute Technology - Tamil Nadu",
      "JAYALAKSHMI NARAYANA SWAMI COLLEGE OF EDUCATION - Tamil Nadu",
      "JAYAM COLLEGE OF EDUCATION - Tamil Nadu",
      "Jayam College of Engineering & Technology - Tamil Nadu",
      "Jayam Polytechnic College - Tamil Nadu",
      "Jayam School Of Nursing , Thanjavur - Tamil Nadu",
      "Jayamatha Engineering College - Tamil Nadu",
      "Jayamukhi Institute of Technology Science - Andhra Pradesh",
      "JAYANTHI COLLEGE OF EDUCATION - Tamil Nadu",
      "JAYANTHI PADMANABA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Jayaraj Annapackiam College for Women - Tamil Nadu",
      "Jayaraj Annapackiam CSI College Of Engineering - Tamil Nadu",
      "Jayaraj Annapackiam CSI Polytechnic College - Tamil Nadu",
      "Jayaraj Challadurai College - Tamil Nadu",
      "Jayaram College Of Engineering & Technology - Tamil Nadu",
      "Jayaram College of Engineering and Technology - Tamil Nadu",
      "JAYARAM COLLEGE OF TEACHER TRAINING NURSERY - Tamil Nadu",
      "Jayaram Polytechnic College - Tamil Nadu",
      "JAYASHANTHI TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JAYASIMHAN CHARITABLE TRUST - Tamil Nadu",
      "Jayasree Degree College - Andhra Pradesh",
      "JAYAVIGNESH TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JAYAWANT INSTITUTE OF MANAGEMENT STUDIES - Maharashtra",
      "Jayawant Mahavidyalaya - Maharashtra",
      "Jayawantrao Sawant Institute of Pharmacy , Pune - Maharashtra",
      "JAYBEES TRAINING COLLEGE OF B.ED - Kerala",
      "JAYBHARATH PRE PRIMARY TEACHER TRNG INSTITUTE - Kerala",
      "JAYE JOTHI TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JAYENDRA COLLEGE - Karnataka",
      "Jayoti Vidyapeeth Womens University - Rajasthan",
      "JAYPEE COLLEGE OF EDUCATION - Madhya Pradesh",
      "Jaypee Polytechnic and Training Centre, Rewa - Madhya Pradesh",
      "Jaypee University of Engineering & Technology - Madhya Pradesh",
      "Jaypore Law College - Orissa",
      "Jaypore Law College - Orissa",
      "Jaypur Panchanan Roy College - West Bengal",
      "Jayvantrai Harrai Desai Polytechnic - Gujarat",
      "Jaywant Institute Of Management - Maharashtra",
      "JAYWANT SHIKSHAN PRASARAK MANDAL ABACUS INSTITUTE OF COMPUTER APPLICATION - Maharashtra",
      "JAYWANT SHIKSHAN PRASARAK MANDAL ENIAC INSTITUTE OF COMPUTER APPLICATION - Maharashtra",
      "JAYWANTRAO SAWANT COLLEGE OF EDUCATION - Maharashtra",
      "Jaywantrao Sawant College Of Engineering - Maharashtra",
      "JAYWANTRAO SAWANT INST OF MANAGEMENT & RESEARCH - Maharashtra",
      "JB Institute of Engineering & Technology - Andhra Pradesh",
      "JB Institute of PG Courses - Andhra Pradesh",
      "JB Knowledge Park - Haryana",
      "JBaruah Law College - Assam",
      "JBTC Institute of Management - Delhi",
      "JBTC Institute of Management - Delhi",
      "JD Institute Of Fashion Technology - Madhya Pradesh",
      "JD Institute Of Fashion Technology,bangalore - Karnataka",
      "Jdmvp Co Op Samajs Sh.S.S.Patil Arts S.B.T.T.S Commerce & G.R.Pandit Science - Maharashtra",
      "JDS TEACHER TRAINING COLLEGE - Punjab",
      "JDT Islam College of Pharmacy , CALICUT - Kerala",
      "Jeev Seva Sansthan Group of Institutions for Women-Faculty of Management, Bhopal - Madhya Pradesh",
      "Jeeva College Of Nursing , Krishnagiri - Tamil Nadu",
      "Jeeva School Of Nursing , Krishnagiri - Tamil Nadu",
      "Jeevan - Jharkhand",
      "JEEVAN CHANAN TEACHER TRAINING COLLEGE - Haryana",
      "JEEVAN COLLEGE OF EDUCATION - Tamil Nadu",
      "Jeevan Jot Nursing Institute , Ludhiana - Punjab",
      "Jeevan Jyot Nursing College,Osmanabad - Maharashtra",
      "Jeevan Jyothi B Sc Nursing College,Guntur - Andhra Pradesh",
      "Jeevan Jyothi Hospital School Of Nursing , Anantapur - Andhra Pradesh",
      "JEEVAN JYOTHI INSTITUTE OF EDUCATION - Haryana",
      "Jeevan Jyoti College Of Nursing - Madhya Pradesh",
      "JEEVAN JYOTI D.ED COLLEGE - Karnataka",
      "Jeevan Jyoti School for the Blind - Uttar Pradesh",
      "Jeevan Jyoti School Of Nursing , Jamshedpur - Jharkhand",
      "JEEVAN JYOTI TEACHER TRAINING COLLEGE - Haryana",
      "Jeevan Polytechnic College - Tamil Nadu",
      "Jeevan Rekha School Of Nursing , Mandi - Himachal Pradesh",
      "Jeevan Rekha School Of Nursing,Yavtmal - Maharashtra",
      "Jeevan Vikas Mahavidyalaya - Maharashtra",
      "Jeevan Vikas Pratishthan - Maharashtra",
      "JEEVANA SHIKSHANA SAMI - Karnataka",
      "JEEVANDEEP INSTITUTE OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "JEEVANDEEP MAHILA MAHAVIDYALAYA - Uttar Pradesh",
      "Jeevandeep School Of Nursing, , Varnasi - Uttar Pradesh",
      "Jeevas Polytechnic College,Myleripalayam - Tamil Nadu",
      "Jeevoday College of Special Education - Maharashtra",
      "Jehlum Education Trust College Of Education - Jammu and Kashmir",
      "Jei Mathaajee College of Engineering - Tamil Nadu",
      "JEI MATHAJHI TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JEI MATHAJI TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Jengraimukh College - Assam",
      "Jenneys Academy of Tourism and Hotel Management - Tamil Nadu",
      "Jenneys Academy Of Tourism And Hotel Management - Tamil Nadu",
      "JENNEYS COLLEGE OF EDUCATION - Tamil Nadu",
      "Jennys College Of Nursing , Trichirapalli - Tamil Nadu",
      "Jeppiaar Engineering College - Tamil Nadu",
      "Jeppiaar Institute of Technology - Tamil Nadu",
      "Jerusalem College Of Engineering - Tamil Nadu",
      "JESI ADAM TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Jesus & Mary College - Delhi",
      "JESUS CHRIST TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "JESUS PEACE COLLEGE OF EDUCATION - Tamil Nadu",
      "JESUS PG COLLEGE - Andhra Pradesh",
      "JESUS TRAINING COLLEGE - Kerala",
      "Jethabhai Jhaverbhai College Science - Gujarat",
      "Jeya Polytechnic College - Tamil Nadu",
      "Jeyaraj Annapackiam C.S.I. Polytechnic College - Tamil Nadu",
      "Jeyaraj Chelladurai College Of Arts And Science - Tamil Nadu",
      "JEYASURIYA EDUCATIONAL TRUST - Tamil Nadu",
      "Jeypore College of Pharmacy , Jaypore - Orissa",
      "Jeypore Law College - Orissa",
      "Jeypore School of Engineering & Technology - Orissa",
      "JG COLLEGE OF EDUCATION (PG) - Karnataka",
      "JGI iDEA, School for Leadership and Entrepreneurial Excellence - Karnataka",
      "Jhabbu Singh Memorial College - Jharkhand",
      "Jhadeswar Institute of Enginering & Technology - Orissa",
      "Jhalawar Medical College, Jhalawar - Rajasthan",
      "JHAM BABA DEGREE COLLEGE - Uttar Pradesh",
      "Jham Baba Degree College - Uttar Pradesh",
      "Jhamman Lal Degree College - Uttar Pradesh",
      "Jhanji Hem Nath Sarma College - Assam",
      "JHANKAR TEACHER TRAINING COLLEGE - Haryana",
      "Jhanvi School Of Nursing ,Lucknow - Uttar Pradesh",
      "Jhargram Raj College - West Bengal",
      "Jharkhand College - Jharkhand",
      "Jharkhand Teacher's Training College - Jharkhand",
      "Jharkhand Vidhi Mahavidyalaya - Jharkhand",
      "Jharsuguda Engineering  School,  Jharsuguda - Orissa",
      "Jharsuguda Gnm Training College , Jharsuguda - Orissa",
      "Jhulelal Institute Of Technology - Maharashtra",
      "Jhulka Institute Of Nursing & Health Sciences , Gurdaspur - Punjab",
      "JhunJhunwala Mahila Mahavidyalaya - Uttar Pradesh",
      "JHUNJHUNWALA P.G.COLLEGE - Uttar Pradesh",
      "Jiadhal College - Assam",
      "Jiaganj Institute of Education & Training - West Bengal",
      "Jialal Institute of Education - Rajasthan",
      "JIBRAN QUADRI INSTITUTE OF MANAGEMENT SCIENCE & RESEARCH - Maharashtra",
      "JIET School of Engineering & Technology for Girls - Rajasthan",
      "Jija Mata Govt. Polytechnic College, Burhanpur - Madhya Pradesh",
      "JIJAMATA BAH-UDDESHIYA SHIKSHAN PRASARAK MANDAL - Maharashtra",
      "JIJAMATA EDUCATION SOCIETY - Maharashtra",
      "Jijamata Education Societys Arts Science & Commerce - Maharashtra",
      "Jijamata Education Societys Arts Science & Commerce - Maharashtra",
      "Jijamata Foundation Vidyapeeth Shri P.E. Tatya Patil Institute of Pharmacy, Jalgaon - Maharashtra",
      "Jijamata School Of Nursing,Beed - Maharashtra",
      "JIJAMATHA TEACHER TRAINING INSTITUTE D.ED - Karnataka",
      "JIJAU SHIKSHAN MAHAVIDYALAYA - Maharashtra",
      "JIMARS (Jyoti Institute of Medical & Rehabiltiation Sciences) Viklang Kendra - Uttar Pradesh",
      "Jind Institute of Engineering and Technology - Haryana",
      "Jind Polytechnic College - Haryana",
      "JINDAL INSTITUTEO OF EDUCATION - Uttar Pradesh",
      "Jindal School of Hotel Management - Gujarat",
      "Jindal School of Hotel Management - Gujarat",
      "JINDAL TEACHER TRAINING COLLEGE - Haryana",
      "Jiral College - Orissa",
      "Jiri College - Manipur",
      "JIS College of Engineering - West Bengal",
      "JIS College- Centre for Management Studies - West Bengal",
      "Jitendra Chauhan College of Law - Maharashtra",
      "Jitendra Chauhan College of Law, - Maharashtra",
      "Jiwach Mahavidyalaya - Bihar",
      "Jiwaji University - Madhya Pradesh",
      "JIWANI SHIKSHAK PRASHIKSHAN SANSTHAN - Rajasthan",
      "JIWANI TEACHER TRAINING COLLEGE - Rajasthan",
      "JJM Medical College, Davangere - Karnataka",
      "JK Business School - Haryana",
      "JK Institute of Management and Technology - Haryana",
      "JKK Munirajah School of Architecture - Tamil Nadu",
      "JKK Natrajah Dental College & Hospital , Komarapalayam - Tamil Nadu",
      "JKP Polytechnic - Haryana",
      "JM Sabva Institute of Engineering & Technology - Gujarat",
      "Jnan Chandra Ghosh Polytechnic - West Bengal",
      "Jnan Chandra Ghosh Polytechnic , Kolkata - West Bengal",
      "JNANA BHARATHI COLLEGE OF EDUCATION - Karnataka",
      "JNANA BHARATHI COLLEGE OF EDUCATION - Karnataka",
      "Jnana Bharathi School Of Nursing , Tumkur - Karnataka",
      "JNANA GANGA VIDYA PEE - Karnataka",
      "Jnana Jyothi School Of Nursing , Bangalore - Karnataka",
      "JNANA SAGAR D.ED COLLEGE - Karnataka",
      "JNANA VIKAS COLLEGE OF EDUCATION - Karnataka",
      "JNANABHARATHI SHIKSHARA TRAINING - Karnataka",
      "JNANADHARA TEACHER TRAINING INSTITUTE - Karnataka",
      "JNANAGANGA SHIKSHANA SAMSTHES - Karnataka",
      "Jnanajyothi Polytechnic - Karnataka",
      "Jnanavikasa Institute Of Technology - Karnataka",
      "JNANAYOGI SIDDESSHWARA SIXAN SAMSTHAS D.ED COLLEGE - Karnataka",
      "JNANAYOGI SRI.SIDDESHWA SWAMIJI COLLEGE OF EDUCATION - Karnataka",
      "Jnanesh Institute Of Nursing , Bangalore - Karnataka",
      "JNANESH TEACHER TRAINING INSTITUTE - Karnataka",
      "JNANODYA TEACHERS TRAINING D.ED COLLEGE - Karnataka",
      "JNN Institute Of Engineering - Tamil Nadu",
      "JNTU College of Engineering - Andhra Pradesh",
      "JNTU College of Engineering Andhra Pradesh - Andhra Pradesh",
      "JNTU College of Engineering Godavari - Andhra Pradesh",
      "Joda Women's College - Orissa",
      "Jodh Singh Namdhari Mahila College - Jharkhand",
      "Jodhpur Dental College & General Hospital , Jodhpur - Rajasthan",
      "Jodhpur Engineering College and Research Center - Rajasthan",
      "Jodhpur Institute of Engineering & Technology - Rajasthan",
      "Jodhpur Institute of Law - Rajasthan",
      "Jodhpur Law College and Research Centre - Rajasthan",
      "Jodhpur National University - Rajasthan",
      "Jodhpur Pharmacy College , Jodhpur - Rajasthan",
      "JODHPUR TEACHERS TRAINING INSTITUTE - Rajasthan",
      "Joe Suresh Engineering College - Tamil Nadu",
      "Jogaiah Institute of Tech. and Science - Andhra Pradesh",
      "Jogesh Chandra Chaudhari Law College - West Bengal",
      "Jogesh Chandra Chaudhuri College - West Bengal",
      "Jogesh Chandra Chaudhuri Law College - West Bengal",
      "Joginpally B.R. Engineering College - Andhra Pradesh",
      "Jogmaya Devi College - West Bengal",
      "John Bosco Engineering College - Tamil Nadu",
      "John Bosco Polytechnic College - Tamil Nadu",
      "John Enoch College of Pharmacy , THIRUVANANTHAPURAM - Kerala",
      "JOHN MEMORIAL TEACHER TRAINING INSTITUTE - Kerala",
      "JOHN TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Joitiba College Of Nursing , Mehsana - Gujarat",
      "Jorhat College Amulgumated - Assam",
      "Jorhat Engineering College - Assam",
      "Jorhat Kendriya Mahavidyalaya - Assam",
      "Jorhat Law College - Assam",
      "Jorhat Medical College & Hospital , Jorhat - Assam",
      "Josco College Of Nursing , Alappuzha - Kerala",
      "Josco College Of Nursing , Bangalore - Karnataka",
      "Josco School Of Nursing,Alappuzha - Kerala",
      "Joseph Arts And Science College - Tamil Nadu",
      "JOSEPH CHELLAMUTTU TEACHERTRAINING INSTITUTE - Tamil Nadu",
      "Joshi School Of Nursing , Bangalore - Karnataka",
      "Jote Kanurangarh Mahatma Primary Teacher's Training Institute - West Bengal",
      "Jothi College - Tamil Nadu",
      "JOTHI VALLUR COLLEGE OF EDUCATION - Pondicherry",
      "Joyrambati Ramakrishna Sarada - West Bengal",
      "JP College Of Engineering - Tamil Nadu",
      "JP Institute of Management - Uttar Pradesh",
      "JP School of Business - Uttar Pradesh",
      "JPM BED COLLEGE - Kerala",
      "Jr Health Assistant F Trg Centre,Raichur - Karnataka",
      "Jr. Health Assistant F Trg. Centre,Mysore - Karnataka",
      "Jr. Public Health Nurses Training Centre , Thiruvananthapuram - Kerala",
      "JRE Group of Institutions - Uttar Pradesh",
      "JRN Institute of Aviation Technology - Delhi",
      "JRS COLLEGE OF EDUCATION - Tamil Nadu",
      "JRS Institute of Technical Education - Rajasthan",
      "JRSET College of Law - West Bengal",
      "JS (PG)COLLEGE SIKANDRABAD - Uttar Pradesh",
      "JS S S Polytechnic, Mysore - Karnataka",
      "JSN College of Engineering & Technology - Andhra Pradesh",
      "JSPM's Eniac Institute Of Computer Application, Wagholi, Pune - Maharashtra",
      "JSPM'S RAJARSHI SHAHU COLLEGE OF EDUCATION - Maharashtra",
      "Jspss Ajjappa Gadami Arts And Commerce College - Karnataka",
      "JSR COLLEGE OF EDUCATION - Tamil Nadu",
      "JSS Academy of Technical Education - Uttar Pradesh",
      "JSS Academy of Technical Education Karnataka - Karnataka",
      "JSS COLLEGE OF EDUCATION - Karnataka",
      "JSS College of Nursing - Karnataka",
      "JSS College of Physiotherapy - Karnataka",
      "JSS Dental College & Hospital , Mysore - Karnataka",
      "JSS INSTITUTE OF EDUCATION - Karnataka",
      "JSS INSTITUTE OF EDUCATION - Karnataka",
      "JSS INSTITUTE OF EDUCATION - Karnataka",
      "JSS Medical College, Mysore - Karnataka",
      "Jss Sakaari Law College - Karnataka",
      "Jss Sakaari Law College - Karnataka",
      "Jubilee College - Jharkhand",
      "Jubilee Mission College Of Nursing , Thrissur - Kerala",
      "Jubilee Mission College Of Nursing , Thrissur - Kerala",
      "Jubilee Mission Hospital , Thrissur - Kerala",
      "Jubilee Mission Medical College & Research Institute, Thrissur - Kerala",
      "Jubin College Of Nursing,Sri Ganganagar - Rajasthan",
      "Jubin College Of Post Basic Bsc Nursing , Sri Ganganagar - Rajasthan",
      "Jubin Nursing School, Sriganganagar - Rajasthan",
      "JUGAL KISHORE MAHAVIDYALAYA - Uttar Pradesh",
      "JUGAL TEACHER TRAINING COLLEGE - Haryana",
      "Juhari Devi Girls Postgraduate College - Uttar Pradesh",
      "Jumma Masjid Charitable Trust''s Polytechnic - Maharashtra",
      "Junior Health Asstt F Training Centre,Chickmagalur - Karnataka",
      "Jupiter College Of Nursing , Bangalore - Karnataka",
      "Jupiter Degree College - Andhra Pradesh",
      "Jupiter School Of Nursing , Bangalore - Karnataka",
      "JUPITER TEACHER TRAINING COLLEGE - Himachal Pradesh",
      "Juria College - Assam",
      "Justice Basheer Ahmed Syed College For Women - Tamil Nadu",
      "Justice Kumaryya College of Law - Andhra Pradesh",
      "JV Mandal Polytechnic, Terdal Bagalkot - Karnataka",
      "JVS TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Jwala Devi Vidya Mandir (PG) Degree College - Uttar Pradesh",
      "Jyothi Engineering College - Kerala",
      "Jyothi Engineering College Andhra Pradesh - Andhra Pradesh",
      "Jyothi School Of Nursing - Andhra Pradesh",
      "Jyothishmathi College of Engineering and Technology - Andhra Pradesh",
      "Jyothishmathi Institute of Tech & Science - Andhra Pradesh",
      "Jyoti Bhushan Pratap Singh Law College - Chhattisgarh",
      "JYOTI COLLEGE OF MANAGEMENT SCIENCE & TECHNOLOGY - Uttar Pradesh",
      "Jyoti College Of Management Science & Technology , Bareilly - Uttar Pradesh",
      "JYOTI COLLEGE OF MANAGENENT AND SCLNCE AND TECHNOLOGY - Uttar Pradesh",
      "Jyoti Hospital A N M Training Center,Allahabad - Uttar Pradesh",
      "JYOTI KRISHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "JYOTI SHIKSHA PRASHIKSHAN VIDYALAYA - Rajasthan",
      "JYOTI TEACHER TRAINING COLLEGE - Punjab",
      "Jyoti Vikash Degree College - Orissa",
      "JYOTIBA SHIKSHAN SANSTHAS NTS COLLEGE OF EDUCATION - Maharashtra",
      "JYOTINIVAS COLLEGE - Karnataka",
      "Jyotinivas College - Karnataka",
      "Jyotirmoy Schol of Business - West Bengal",
      "Jyotirmoy School of Law - West Bengal",
    ],
  },
];
