const data = [
  {
    colleges: [
      "G B College - Bihar",
      "G B College Of Nursing,Bangalore - Karnataka",
      "G B M College - Bihar",
      "G B Pant Memorial Government College - Himachal Pradesh",
      "G B Pant University Of Agriculture Tech - Uttaranchal",
      "G B Patil School Of Nursing,Latur - Maharashtra",
      "G D College - Bihar",
      "G D M College - Bihar",
      "G D Modi College Arts - Gujarat",
      "G E Socity Arts And Commerce College - Karnataka",
      "G G D S D College Haryana - Haryana",
      "G G D S D College Himachal Pradesh - Himachal Pradesh",
      "G G Hospital School Of Nursing,Thiruvananthapuram - Kerala",
      "G G School Of Nursing & Paramedical,Agra - Uttar Pradesh",
      "G H Sanghavi Shikshan Mahavidyalaya - Gujarat",
      "G J Surya College Of Nursing ,Shivamogga - Karnataka",
      "G J Surya College Of Nursing,Shivamoga - Karnataka",
      "G Karunakaran Memorial Co-Operative College Of Management And Technology - Kerala",
      "G Kuppuswamy Naidu Memorial Hospital, School Of Nursing, , Coimbatore - Tamil Nadu",
      "G L A College Jharkhand - Jharkhand",
      "G L Bajaj Group of Institutions - Uttar Pradesh",
      "G L M College - Bihar",
      "G L Saini Memorial College Of Nursing,Jaipur - Rajasthan",
      "G L Saini Memorial Institute Of Nursing ,Jaipur - Rajasthan",
      "G M D Anm Nursing School,Nagpur - Maharashtra",
      "G M R D College - Bihar",
      "G N M Training Centre , Purulia - West Bengal",
      "G N M Training Centre, Dr B R Ambedkar Medical College , Raipur - Chhattisgarh",
      "G N M Training School , Nadia - West Bengal",
      "G N W Socitys Arts And Commerce First Grade College - Karnataka",
      "G P TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "G R D COLLEGE OF EDUCATION - Tamil Nadu",
      "G R D International Institute Of Nursing , Hoshiarpur - Punjab",
      "G R R College Of Nursing , Bangalore - Karnataka",
      "G R R College Of Nursing,Bangalore - Karnataka",
      "G S L College Of Nursing , East Godavari - Andhra Pradesh",
      "G S L School Of Nursing , Rajahmundry - Andhra Pradesh",
      "G S L Trust, Swatantra College Of Nursing,Rajahmundry - Andhra Pradesh",
      "G S Lohia Girls College - Assam",
      "G S R M Memorial College Of Nursing,Lucknow - Uttar Pradesh",
      "G S R M Memorial School Of Nursing, , Lucknow - Uttar Pradesh",
      "G S Science College - Karnataka",
      "G T R College Of Nursing,East Godavari - Andhra Pradesh",
      "G T R School Of Nursing , Kakinada - Andhra Pradesh",
      "G V M Nursing College,Panchmahal - Gujarat",
      "G V M S Shri G G P R College Commerce Economics - Goa",
      "G V P P Government First Grade College - Karnataka",
      "G V R S Government Degree College - Andhra Pradesh",
      "G V S M Government Degree College - Andhra Pradesh",
      "G Venkatswamy Naidu College - Tamil Nadu",
      "G. B. Pant Engineering College - Uttaranchal",
      "G. H. Raisoni Law School - Maharashtra",
      "G. Kasiviswanadh Degree College - Andhra Pradesh",
      "G. Narayanamma Institute of Technology and Science - Andhra Pradesh",
      "G. Pulla Reddy College of Pharmacy , Hyderabad - Andhra Pradesh",
      "G. Pulla Reddy Degree College - Andhra Pradesh",
      "G. Pulla Reddy Dental College & Hospital, Kurnool - Andhra Pradesh",
      "G. Singh Vidhi Mahavidyalaya - Uttar Pradesh",
      "G. V. Acharya Polytechnic - Maharashtra",
      "G.B. Murarka Arts & Commerce College - Maharashtra",
      "G.B. Pant Degree College - Uttar Pradesh",
      "G.B. Pant Govt. Engineering College - Delhi",
      "G.B.N. Govt. Polytechnic - Haryana",
      "G.B.R. Degree College - Andhra Pradesh",
      "G.B.R. Degree College - Andhra Pradesh",
      "G.B.S D.ED COLLEGE - Karnataka",
      "G.B.TEACHER TRAINING COLLEGE - Rajasthan",
      "G.C.Memorial College of Education - West Bengal",
      "G.D MEMORIAL COLLEGE OF MANAGEMENT & TECHNOLOGY - Rajasthan",
      "G.D. Memorial Homoeopathic Medical College and Hospital - Bihar",
      "G.D. Sawant Arts Commerce Science & B.C.S. College - Maharashtra",
      "G.D.Bagaria Teacher's Training College - Jharkhand",
      "G.D.M. Girls Degree College - Uttar Pradesh",
      "G.E. Societys N.B. Thakur Law College - Maharashtra",
      "G.E.T . TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "G.G.D.S.D. College - Punjab",
      "G.G.D.S.D. College - Haryana",
      "G.G.N. Khalsa College - Punjab",
      "G.H. PATEL P.G. INSTITUTE OF BUSINESS MANAGEMENT - Gujarat",
      "G.H. RAISONI ACADEMY FOR CREATIVE TEACHING - Maharashtra",
      "G.H. Raisoni College of Engineering - Maharashtra",
      "G.H. Raisoni College of Engineering and Management - Maharashtra",
      "G.H. Raisoni Institute of Engineering and Technology for Women - Maharashtra",
      "G.H. RAISONI INSTITUTE OF MANAGEMENT & RESEARCH - Maharashtra",
      "G.H. Raisoni Law School - Maharashtra",
      "G.H. RAISONI NATIONAL COLLEGE - Chhattisgarh",
      "G.H.G HARPRAKESH TEACHER TRAINING COLLEGE - Punjab",
      "G.H.G. Harparkaash College Of Education For Women - Punjab",
      "G.H.G. Khalsa College - Punjab",
      "G.H.G. Khalsa College Of Education - Punjab",
      "G.H.G. Khalsa College of Pharmacy , Gurusar Sadhar - Punjab",
      "G.H.Rai soni Institute of Life Sciences , Nagpur - Maharashtra",
      "G.H.Raisoni College of Engineering & Management - Maharashtra",
      "G.H.Raisoni Institute of Engineering & Management - Maharashtra",
      "G.I.D.C. RAJIU SHIROFF ROFEL INSTITUTE OF MANAGEMENT STUDIES - Gujarat",
      "G.I.M.T INSTITUTE OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "G.K. COLLEGE OF EDUCATION - Tamil Nadu",
      "G.K. Goswami Government College - Rajasthan",
      "G.K.G. College - Maharashtra",
      "G.K.M. B.ED COLLEGE - Karnataka",
      "G.K.M. PRIMARY TEACHER TRAINING INSTITUTE - Karnataka",
      "G.K.R.V.M. Degree & P.G College, Rajahmundry - Andhra Pradesh",
      "G.K.S.M. Government College - Punjab",
      "G.L.A. INSTITUTE OF BUSINESS MANAGEMENT - Uttar Pradesh",
      "G.M. College - Orissa",
      "G.M. COLLEGE OF EDUCATION - Karnataka",
      "G.M. Evening College - Orissa",
      "G.M. Law College - Orissa",
      "G.M. Sanghi College Of Commerce - Andhra Pradesh",
      "G.M.ALADMAR(NAIK) PRIMARY SCHOOL T.T.C - Karnataka",
      "G.M.College of Pharmacy , Bangalore - Karnataka",
      "G.M.D. Arts & B.W.Commerce & Science College - Maharashtra",
      "G.M.R. Degree College - Andhra Pradesh",
      "G.M.R. Vidyarthi Degree College - Andhra Pradesh",
      "G.M.S. Mavmm Polytechnic College - Tamil Nadu",
      "G.M.T TEACHER TRAINING COLLEGEAL - Punjab",
      "G.N.D.TEACHER TRAINING COLLEGE - Punjab",
      "G.P. Government Womens College - Manipur",
      "G.P. Polytechnic College - Tamil Nadu",
      "G.P.S. Degree College - Uttar Pradesh",
      "G.P.S. DEGREE COLLEGE - Uttar Pradesh",
      "G.P.S. MAHAVIDYALAYA - Uttar Pradesh",
      "G.Pulla Reddy Engineering College - Andhra Pradesh",
      "G.Pullaiah College of Engineering & Technology - Andhra Pradesh",
      "G.Pullaiah College of Engineering and Technology - Andhra Pradesh",
      "G.R. DAMODARAN ACADEMY OF MANAGEMENT - Tamil Nadu",
      "G.R. Gobindarajulu School Of Applied Computer Technology - Tamil Nadu",
      "G.R. GOVINDARAJULU COLLEGE OF EDUCATION - Tamil Nadu",
      "G.R. MEMORIAL INSTITUTE OF N.T.T. - Rajasthan",
      "G.R.DAMODARAN TECHER TRAINING INSTITUTE - Tamil Nadu",
      "G.R.G. Polytechnic College For Women - Tamil Nadu",
      "G.R.G. SCHOOL OF MANAGEMENT STUDIES FOR WOMEN - Tamil Nadu",
      "G.R.K. Degree College - Andhra Pradesh",
      "G.R.R & T.P.R. Degree College - Andhra Pradesh",
      "G.S. Arts & Science Degree College - Andhra Pradesh",
      "G.S. Ayurved Mahavidyalaya - Maharashtra",
      "G.S. Ayurved Mahavidyalaya - Maharashtra",
      "G.S. College Of Commerce - Maharashtra",
      "G.S. College Of Commerce & Economics - Madhya Pradesh",
      "G.S. COLLEGE OF COMMERCE & ECONOMICS - Madhya Pradesh",
      "G.S. College Of Commerce And Economics - Maharashtra",
      "G.S. COLLEGE OF EDUCATION - Uttar Pradesh",
      "G.S. College Of Science Arts & Commerce - Maharashtra",
      "G.S. Degree College - Uttar Pradesh",
      "G.S. DEGREE COLLEGE - Uttar Pradesh",
      "G.S. Hindu Degree College - Uttar Pradesh",
      "G.S. Krishna Memorial Law College - Andhra Pradesh",
      "G.S. TEACHER TRAINING COLLEGE - Haryana",
      "G.S. Tompe Arts & Commerce College - Maharashtra",
      "G.S.GANGID TEACHER TRAINING COLLEGE - Rajasthan",
      "G.S.K.M. Law College , Rajahmundry - Andhra Pradesh",
      "G.S.L Medical College, Rajahmundry - Andhra Pradesh",
      "G.S.M.COLLEGE OF ADVANCE EDUCATION - Uttar Pradesh",
      "G.S.MAHAVIDYALAYA - Uttar Pradesh",
      "G.S.R. Degree College - Andhra Pradesh",
      "G.S.R. Degree College, Kamareddy - Andhra Pradesh",
      "G.S.R.M. MEMORIAL DEGREE COLLEGE - Uttar Pradesh",
      "G.S.R.M. Memorial Degree College - Uttar Pradesh",
      "G.S.V.M. Medial College, Kanpur - Uttar Pradesh",
      "G.S.V.M.Medical College , KANPUR - Uttar Pradesh",
      "G.Singh G.P.Singh Khalsa College - Punjab",
      "G.T. Patil Arts Commerce And Science College - Maharashtra",
      "G.T. Polytechnic College, Jaora - Madhya Pradesh",
      "G.T. TEACHER TRAINING COLLEGE - Punjab",
      "G.T.N. Arts College - Tamil Nadu",
      "G.V COLLEGE OF EDUCATION. - Rajasthan",
      "G.V. College Of Education - Rajasthan",
      "G.V.COLLEGE OF EDUCATION - Rajasthan",
      "G.V.GOWDA MEMORIAL VIDYARTHINILAYA VOKKALIGARA SAN KOLLEGALA - Karnataka",
      "G.V.M INSTITUTE OF TECHNOLOGY & MANAGEMENT - Haryana",
      "G.V.M. TEACHER TRAINING COLLEGE FOR GIRLS - Haryana",
      "G.V.N. College - Tamil Nadu",
      "G.V.P College For Degree & Pg Courses - Andhra Pradesh",
      "G.V.R & S. Pg College - Andhra Pradesh",
      "G.V.R & Sailaja Degree College For Women - Andhra Pradesh",
      "G.V.V. SANGHAS D.ED COLLEGE - Karnataka",
      "Gadadhar Shlok Mahavidyalaya - Uttar Pradesh",
      "Gadibrahma College - Orissa",
      "Gadibrahma Womens College - Orissa",
      "GAGAN COLLEGE OF MANAGEMENT & TECHNOLOGY - Uttar Pradesh",
      "Gagan College of Management & Technology - Uttar Pradesh",
      "GAHLOT INSTITUTE OF MANAGEMENT STUDIES & RESEARCH - Maharashtra",
      "Gajadhar Bhagat College - Bihar",
      "Gajapati College Of Nursing,Gajapati - Orissa",
      "Gajapati College of Pharmacy , Paralakhemundi - Orissa",
      "GAJAPATI INSTITUTE OF MANAGEMENT - Orissa",
      "Gajapati School Of Nursing , Gajapati - Orissa",
      "Gajra Raja Medical College, Gwalior - Madhya Pradesh",
      "Gajraj Singh Memorial Degree College - Uttar Pradesh",
      "Galaxy Global Group of Institutions - Haryana",
      "Galaxy Institute of Management - Tamil Nadu",
      "Galaxy Para Medical College , Jammu - Jammu and Kashmir",
      "GALGOLIAS COLLEGE OF ENGINEERING AND TECHNOLOGY - Uttar Pradesh",
      "Galgotia University - Uttar Pradesh",
      "GALGOTIAS BUSINESS SCHOOL - Uttar Pradesh",
      "Galgotias College of Engineering & Technology - Uttar Pradesh",
      "Galsi Rabindra Nazrul College of Education - West Bengal",
      "Galuguribapi Raju Degree College - Andhra Pradesh",
      "GANA BHARATHI D.ED COLLEGE - Karnataka",
      "Ganadipathy Tulsi's Engineering College - Tamil Nadu",
      "GANAPATHI COLLEGE OF EDUCATION - Tamil Nadu",
      "Ganapathy Chettiar College of Engineering and Technology - Tamil Nadu",
      "Ganapathy Engineering College - Andhra Pradesh",
      "Ganapathy Seethai Ammal College (Women) - Tamil Nadu",
      "Ganapati Institute of Engineering & Technology(Polytechnic) - Orissa",
      "Ganauri Ramkali Teacher's Training College - Bihar",
      "Gandhi Adarsh College - Haryana",
      "Gandhi Centenary B.T. College - West Bengal",
      "Gandhi Centenary B.T. College - West Bengal",
      "GANDHI COLLEGE OF EDUCATION - Tamil Nadu",
      "Gandhi College of Pharmacy - Haryana",
      "Gandhi College of Pharmacy , KARNAL - Haryana",
      "Gandhi Degree College - Uttar Pradesh",
      "Gandhi Degree College - Andhra Pradesh",
      "Gandhi Dental College, Bhubaneswar - Orissa",
      "Gandhi Engineering college - Orissa",
      "GANDHI FAIZ-E-AAM COLLEGE - Uttar Pradesh",
      "Gandhi Faizeam College - Uttar Pradesh",
      "GANDHI GRAM WOMENS B.ED. COLLEGE - Maharashtra",
      "Gandhi Hospital School Of Nursing , Secunderabad - Andhra Pradesh",
      "Gandhi Institute for Technological Advancement - Orissa",
      "Gandhi Institute For Technology - Orissa",
      "Gandhi Institute of Advanced Computer & Research - Orissa",
      "Gandhi Institute of Engineering and Technology - Orissa",
      "GANDHI INSTITUTE OF PERFECT TEACHING STUDIES - Uttar Pradesh",
      "GANDHI INSTITUTE OF PROFESSIONAL AND TECHNICAL STUDIES - Uttar Pradesh",
      "GANDHI INSTITUTE OF TECH. & MGMT - Andhra Pradesh",
      "Gandhi Law College - Uttar Pradesh",
      "Gandhi Mahavidyalaya - Orissa",
      "Gandhi Mahila Kalasala - Andhra Pradesh",
      "Gandhi Medical College - Andhra Pradesh",
      "Gandhi Medical College - Madhya Pradesh",
      "Gandhi Medical College, Bhopal - Madhya Pradesh",
      "Gandhi Medical College,hyderabad - Andhra Pradesh",
      "Gandhi Memorial College - Jammu and Kashmir",
      "Gandhi Memorial Degree College, Godavarikhani - Andhra Pradesh",
      "Gandhi Memorial Mahila Degree College, Godavarikhani - Andhra Pradesh",
      "Gandhi Memorial National College - Haryana",
      "Gandhi Natha Rangaji Homoeopathic Medical College - Maharashtra",
      "GANDHI NATIONAL COLLEGE - Madhya Pradesh",
      "Gandhi Poly., Muzaffarnagar - Uttar Pradesh",
      "Gandhi Polytechnic - Orissa",
      "Gandhi Polytechnic College, Sathyamangalam - Tamil Nadu",
      "Gandhi Polytechnic Muzaffarnagar - Uttar Pradesh",
      "GANDHI POST GRADUATE - Uttar Pradesh",
      "Gandhi PR College - Madhya Pradesh",
      "Gandhi Samarak Dev Nagri College - Uttar Pradesh",
      "Gandhi School of Engineering - Orissa",
      "Gandhi School Of Nursing , Karnal - Haryana",
      "GANDHI SEVA SADAN TEACHER TRAINING INSTITUTE - Kerala",
      "Gandhi Shatabdi Smarak Mahavidyalaya - Uttar Pradesh",
      "GANDHI SHIKSHAN BHAWANS - Maharashtra",
      "GANDHI SMARAK COLLEGE - Uttar Pradesh",
      "Gandhi Smarak Degree College - Uttar Pradesh",
      "GANDHI SMARAK DEGREE COLLEGE - Uttar Pradesh",
      "Gandhi Smarak Triveni Mahavidyalaya - Uttar Pradesh",
      "Gandhi T.T. College - Rajasthan",
      "GANDHI VIDHYAMANDIR - Rajasthan",
      "Gandhi Vidya Niketan Degree College - Uttar Pradesh",
      "GANDHI VIDYAMANDIR MAHILA TEACHER TRAINING COLLEGE - Rajasthan",
      "GANDHI VIDYASHALA TEACHER TRAINING INSTITUTE FOR WOMEN - Karnataka",
      "GANDHI VOCATIONAL COLLEGE - Madhya Pradesh",
      "GANDHIGRAM RURAL INSTITUTE (DEEMED UNIVERSITY) GANDHIGRAM - Tamil Nadu",
      "Gandhigram Rural University - Tamil Nadu",
      "GANDHIJI COLLEGE OF D .Ed - Karnataka",
      "Gandhiji Institute Of Science And Technology - Andhra Pradesh",
      "Gandhinagar Charitable Trust Sanchalit Arts And Commerce College - Gujarat",
      "Gandhinagar Institute of Technology - Gujarat",
      "GANDI DEVI SHIKSHAN SANSTHAN - Rajasthan",
      "GANDI FAIZ -E-AAM COLLEGE - Uttar Pradesh",
      "Gandi Girls College - Rajasthan",
      "Ganesar College of Arts and Science - Tamil Nadu",
      "Ganesar Senthamil Kallori - Tamil Nadu",
      "GANESH COLLEGE OF EDUCATION - Tamil Nadu",
      "Ganesh College of Engineering - Tamil Nadu",
      "Ganesh Institute of Engineering & Technology - Orissa",
      "Ganesh Lal Aggarwal CollegeG.L.A. College - Jharkhand",
      "Ganesh Senthamizh Kalloori - Tamil Nadu",
      "Ganesh Shankar Vidyarthi Momorial Medical College - Uttar Pradesh",
      "Ganeshi Lal Bajaj Institute of Technology & Management - Uttar Pradesh",
      "Ganga College Of Nursing , Coimbatore - Tamil Nadu",
      "Ganga Degree College - Uttar Pradesh",
      "Ganga Devi Mahila College - Bihar",
      "GANGA INSTITUTE OF EDUCATION - Haryana",
      "Ganga Institute of Technology & Management - Haryana",
      "GANGA KAVERI PRE SCHOOL TEACHER EDUCATION - Karnataka",
      "Ganga School Of Nursing For Women,Coimbatore - Tamil Nadu",
      "Ganga Sheel College Of Higher Education,Bareilly - Uttar Pradesh",
      "Ganga Sheel School Of Nursing , Bareilly - Uttar Pradesh",
      "Ganga Singh College - Bihar",
      "Ganga Singh Law College - Bihar",
      "Gangaa Polytechnic College - Tamil Nadu",
      "GANGADHAR MEHER COLLEGE - Orissa",
      "Gangadhar Mohapatra Law College - Orissa",
      "GANGADHAR TEACHER TRAINING COLLEGE - Rajasthan",
      "Gangadharpur Mahavidyalaya - West Bengal",
      "Gangadharpur Sikshan Mandir - West Bengal",
      "GANGAMAI COLLEGE OF EDUCATION - Maharashtra",
      "Gangamai Institute of Pharmacy , Nagaon - Maharashtra",
      "Gangarampur B.Ed. College - West Bengal",
      "Gangarampur College - West Bengal",
      "Gangavathi Bhagyamma Memorial Rural College - Karnataka",
      "Gangavati Institute Of Nursing Sciences , Koppal - Karnataka",
      "Gangothri College Of Nursing,Bangalore - Karnataka",
      "GANGOTHRI INSTITUTE OF TEACHER TRAINING - Karnataka",
      "Gangothri School Of Nursing , Bangalore - Karnataka",
      "Gangothri Schoolof Nursing , Bangalore - Karnataka",
      "Gangotri Devi Mahila Degree College - Uttar Pradesh",
      "Gangotri Devi Mahila Mahavidyalay, S N , School Of Nursing, Gorakhpur - Uttar Pradesh",
      "Gangotri Hospital And Institute Of Para Medical Science , Uttarakhand - Uttaranchal",
      "Gangotri Hospital And Institute Of Para Medical Science ,Dehradun - Uttaranchal",
      "GANJADUNDWARA P.G. COLLEGE - Uttar Pradesh",
      "Ganjam College - Orissa",
      "Ganjam Law College - Orissa",
      "Ganjdundwara College - Uttar Pradesh",
      "GANJDUNDWARA P.G. COLLEGE - Uttar Pradesh",
      "Ganna Krishak PG Degree College - Uttar Pradesh",
      "GANNA KRISHEK POST GRADUAT COLLEGE - Uttar Pradesh",
      "Ganna Utpadak Mahavidyalaya - Uttar Pradesh",
      "GANPAT SABAI POST GRADUAT COLLEGE - Uttar Pradesh",
      "Ganpat University - Gujarat",
      "GANPAT UNIVERSITY - Gujarat",
      "Ganpath Sehay Degree College - Uttar Pradesh",
      "GANPATI  BUSINESS SCHOOL - Haryana",
      "GANPATI  COLLEGE OF MANAGEMENT FOR GIRLS - Haryana",
      "Ganpati College of Science Technology & Management, Jaipur - Rajasthan",
      "GANPATI INSTITUTE OF EDUCATION & TECHNOLOGY - Haryana",
      "GANPATI INSTITUTE OF EDUCATION FOR GIRLS - Haryana",
      "Ganpati Institute Of Hotel Management - Haryana",
      "GANPATI INSTITUTE OF SCIENCE & TECHNOLOGY - Uttar Pradesh",
      "Ganpati Institute of Technology & Management - Haryana",
      "GANPATI TEACHERS TRAINING COLLEGE - Rajasthan",
      "Ganpatrao Adke Institute Of Nursing, Nashik - Maharashtra",
      "Ganpatrao Arawade College Of Commerce - Maharashtra",
      "GARAH DEVI SHYAM HIHARI COLLEGE - Uttar Pradesh",
      "GARDEN CITY  COLLEGE OF  SC & MGT. STUDIES - Karnataka",
      "Garden City College Of Nursing , Bangalore - Karnataka",
      "Garden City College of Science and Hotel Management - Karnataka",
      "Garden City Law College - Karnataka",
      "Gargaon College - Assam",
      "Gargi College, New Delhi - Delhi",
      "GARGI SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Garhbeta College - West Bengal",
      "Garhbeta College - West Bengal",
      "Garv Institute of Management & Technology - Chhattisgarh",
      "Gate Degree College, Tirupati - Andhra Pradesh",
      "GATE INSTITUTE OF TECHNOLOGY & MANAGEMENT SCIENCES - Andhra Pradesh",
      "Gates Institute of Technology - Andhra Pradesh",
      "Gateway Institute of Engineering and Technology - Haryana",
      "Gauhati College - Assam",
      "Gauhati Commerce College - Assam",
      "Gauhati Medical College, Guwahati - Assam",
      "Gauhati University - Assam",
      "Gaur Brahman Degree College - Haryana",
      "GAUR TEACHER TRAINING COLLEGE - Haryana",
      "Gaurav Nursing School, 303702 - Rajasthan",
      "GAURAV TEACHER TRAINING COLLEGE - Rajasthan",
      "GAURAV TEACHER TRAINING COLLEGE - Haryana",
      "GAURI SHANKAR DWEVEDI MAHAVIDYALAYA - Uttar Pradesh",
      "Gauri Shankar Girls Degree College - Uttar Pradesh",
      "GAURI SHANKAR RAI KANYA MAHAVIDYALAYA - Uttar Pradesh",
      "Gauri Shanker Rai Kanya Mahavidyalaya - Uttar Pradesh",
      "Gautam Buddha Degree College Sahiyapur - Uttar Pradesh",
      "Gautam Buddha Girls Degree College - Uttar Pradesh",
      "Gautam Buddha Mahavidyalaya - Uttar Pradesh",
      "Gautam Buddha Teacher's Training College - Jharkhand",
      "Gautam Budh Government Degree College - Uttar Pradesh",
      "Gautam Budh Teacher's Training College - Bihar",
      "Gautam Budh Technial University - Uttar Pradesh",
      "GAUTAM BUDHA COLLEGE OF EDUCATION - Uttar Pradesh",
      "GAUTAM BUDHA DEGREE COLLEGE - Uttar Pradesh",
      "GAUTAM BUDHA DEGREE COLLEGE - Uttar Pradesh",
      "GAUTAM BUDHA DEGREE COLLEGE - Uttar Pradesh",
      "Gautam Budha Mahavidyalaya - Uttar Pradesh",
      "GAUTAM COLLEGE - Madhya Pradesh",
      "Gautam College Of Life Sciences & Technology,Gwalior - Madhya Pradesh",
      "Gautam Girls College - Himachal Pradesh",
      "Gautam Polytechnic - Himachal Pradesh",
      "Gautami Degree College, Khaleelwadi - Andhra Pradesh",
      "Gautami Degree College, Shantinagar - Andhra Pradesh",
      "Gautham School Of Nursing,Ernakulam - Kerala",
      "Gaya College - Bihar",
      "Gaya Nursing College,Beed - Maharashtra",
      "Gaya Prasad Vidhi Maha Vidyalaya - Uttar Pradesh",
      "GAYAK SANSKRIT TT COLLEGE - Rajasthan",
      "Gayathri College Of Nursing , Bangalore - Karnataka",
      "Gayathri College Of Nursing ,Bangalore - Karnataka",
      "Gayathri College of Science & Management - Andhra Pradesh",
      "Gayathri College Science Management - Andhra Pradesh",
      "Gayathri Degree College, Wanaparthy - Andhra Pradesh",
      "Gayathri Devi College Of Nursing,Bangalore - Karnataka",
      "Gayathri Institute Of Nursing Sciences,Bangalore - Karnataka",
      "Gayathri Mahila Degree College, Vizianagaram - Andhra Pradesh",
      "Gayathri School Of Nursing , Bangalore - Karnataka",
      "Gayatree Vidyapeeth Degree College - Uttar Pradesh",
      "Gayatri College For P.G Courses - Andhra Pradesh",
      "Gayatri College of Management - Orissa",
      "Gayatri College of Pharmacy , Sambalpur - Orissa",
      "Gayatri Degree College - Andhra Pradesh",
      "Gayatri Degree College, Gajapathinagaram - Andhra Pradesh",
      "Gayatri Degree College, Payakaraopet - Andhra Pradesh",
      "Gayatri Degree College, Seethanagaram - Andhra Pradesh",
      "Gayatri Degree College, Siddipet - Andhra Pradesh",
      "Gayatri Degree College, Tirupati - Andhra Pradesh",
      "Gayatri Degree College, Vizianagaram - Andhra Pradesh",
      "Gayatri Degree College, Yellareddypet - Andhra Pradesh",
      "GAYATRI DEVI COLLEGE OF EDUCATION - Uttar Pradesh",
      "Gayatri Education Institute Of Technology,Bhilai - Chhattisgarh",
      "Gayatri Education Nursing Institute, Udaipur - Rajasthan",
      "GAYATRI INSTITUTE OF COMPUTER & MANAGEMENT STUDIES - Orissa",
      "Gayatri Institute of Pharmaceutical Science , Gunupur - Orissa",
      "GAYATRI MAHAVIDYALAYA - Uttar Pradesh",
      "Gayatri School Of Management Studies & Science - Andhra Pradesh",
      "Gayatri Vidya Parishad College of Engineering - Andhra Pradesh",
      "Gayatri Vidya Parished Degree College - Andhra Pradesh",
      "Gayatruvidya Parishad Degree College - Andhra Pradesh",
      "Gaythri Dgree College, Srikakulam - Andhra Pradesh",
      "GCRG Memorial Trust's Group of Institutions - Uttar Pradesh",
      "GCS Medical College, Ahmedabad - Gujarat",
      "GD Rungta College of Engineering & Technology - Chhattisgarh",
      "GD. RUNGTA COLLEGE OF EDUCATION AND TEACHNOLOGY - Chhattisgarh",
      "GDR TEACHER TRAINING COLLEGE - Haryana",
      "GEAR B.ED COLLEGE - Karnataka",
      "GEAR INNOVATIVE MONTESSORI INSTITUTE - Karnataka",
      "Gee K P School Of Nursing ,Tiruvarur - Tamil Nadu",
      "GEETA ADARSH TEACHER TRAINING COLLEGE - Haryana",
      "GEETA ARYA TEACHER TRAINING COLLEGE - Haryana",
      "GEETA BAJAJ MAHILA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "GEETA BAJAJ PRE-PRIMARY MAHILA SHIKSHAK PRASHIKSHAN VIDYALAYA - Rajasthan",
      "GEETA CO-EDUCATION TEACHERS TRAINING.COLLEGE - Rajasthan",
      "GEETA DEVI TEACHER TRAINING COLLEGE - Rajasthan",
      "Geeta Institute of Law - Haryana",
      "GEETA INSTITUTE OF MANAGEMENT & TECH - Haryana",
      "Geeta Institute of Management and Technology. - Haryana",
      "GEETA JYOTI B.ED. COLLEGE - Madhya Pradesh",
      "GEETA JYOTI TEACHERS TRAINING COLLEGE - Rajasthan",
      "Geeta Niketan Nursing School,Bhiwani - Haryana",
      "GEETA RATAN TEACHER TRAINING INSTITUTE - Delhi",
      "GEETA TEACHER TRAINING COLLEGE - Haryana",
      "GEETA TEACHER TRAINING COLLEGE - Haryana",
      "Geetadevi Khandelwal Instt. of Pharmacy , AKOLA - Maharashtra",
      "Geetai Institute Of Nursing,Jalgaon - Maharashtra",
      "Geetam Degree College - Andhra Pradesh",
      "GEETANGALI INSTITUTE OF TEACHER TRAINING - Haryana",
      "GEETANJALI B.ED. COLLEGE - Rajasthan",
      "Geetanjali College Of Nursing , Udaipur - Rajasthan",
      "Geetanjali College Of Nursing,Kadapa - Andhra Pradesh",
      "Geetanjali College Of Nursing,Kurnool - Andhra Pradesh",
      "Geetanjali Colllege For Women - Andhra Pradesh",
      "Geetanjali Degree College - Andhra Pradesh",
      "Geetanjali Degree College, Yellamanchili - Andhra Pradesh",
      "Geetanjali Institute of Technical Education - Rajasthan",
      "Geetanjali Institute of Technical Studies - Gujarat",
      "Geetanjali Medical College And Hospital, Udaypur - Rajasthan",
      "Geetanjali School Of Nursing,Udaipur - Rajasthan",
      "GEETANJALI TEACHER TRAINING COLLEGE - Rajasthan",
      "Geetanjali University - Rajasthan",
      "Geetha Degree College - Andhra Pradesh",
      "Geethanjali College of Engineering and Technology - Andhra Pradesh",
      "Geethanjali Degree College For Women - Andhra Pradesh",
      "Geethanjali Degree College, Medak - Andhra Pradesh",
      "Geethanjali Institute Of P.G. Studies - Andhra Pradesh",
      "GEM Business Academy - Tamil Nadu",
      "Gem Gates Arts Science College - Tamil Nadu",
      "Gem Institute Of Nursing Education & Research , Coimbatore - Tamil Nadu",
      "Gems School Of Nusing , Rohtas - Bihar",
      "GENBA SOPANRAO MOZE B.ED. COLLEGE - Maharashtra",
      "Genba Sopanrao Moze College of Engineering - Maharashtra",
      "General Hospital , Ahmednagar - Maharashtra",
      "General Hospital , Alibagh - Maharashtra",
      "General Hospital , Bhiwani - Haryana",
      "General Hospital , Chandrapur - Maharashtra",
      "General Hospital , Nasik - Maharashtra",
      "General Hospital , Osmanabad - Maharashtra",
      "General Hospital , Sangli - Maharashtra",
      "General Hospital , School Of Nursing , Karnal - Haryana",
      "General Hospital , School Of Nursing, Satara - Maharashtra",
      "General Hospital , School Of Nursing, Rohtak - Haryana",
      "General Hospital , Siang - Arunachal Pradesh",
      "General Hospital Nursing School , Amreli - Gujarat",
      "General Hospital shri Chhatrapati Shivaji Maharaj , Solapur - Maharashtra",
      "General Hospital, Buldana - Maharashtra",
      "General Hospital, G N M School Of Nursing , Godhra - Gujarat",
      "General Hospital, health And Family Welfare,Bharatpur - Rajasthan",
      "General Hospital, School Of Nursing , Hissar - Haryana",
      "General Hospital, School Of Nursing , Mehsana - Gujarat",
      "General Hospital,Alwar - Rajasthan",
      "General Hospital,School Of Nursing, Mehsana - Gujarat",
      "General Hospital,School Of Nursing,Karnal - Haryana",
      "General Hospital,Wardha - Maharashtra",
      "GENERAL KARIYAPPA RASTRIYA DHYHIKA SHIKSHANA MAHAVIDHYALAY NATIONAL EDUCATION SOCIETY - Karnataka",
      "General Nursing And Midwifery Training School,Talcher - Orissa",
      "General Nursing School , Bhuj - Gujarat",
      "General Nursing School , Jamnagar - Gujarat",
      "General Nursing School , Nadiad - Gujarat",
      "General Nursing School , Narmada - Gujarat",
      "General Nursing School , Rajkot - Gujarat",
      "General Nursing School , Tapi - Gujarat",
      "General Nursing School, Referal Hosp & C H C,Vyara - Gujarat",
      "General Nursing Training Centre - Uttaranchal",
      "General Nursing Training Centre, Barmer , - Rajasthan",
      "General Nursing Training Centre, Tilli Hospital,Sagar - Madhya Pradesh",
      "General Nursing Training School , Shimla - Himachal Pradesh",
      "Genesis Institute of Dental Sciences & Research, Ferozepur - Punjab",
      "Genius Anm Training Centre, Bhilwara - Rajasthan",
      "Genius College Of Nursing, Bhilwara - Rajasthan",
      "Genius Health & Nursing Shikshan Sansthan, Bhilwara - Rajasthan",
      "GEORGE COLLEGE(DEPARTMENT OF MANAGEMENT STUDIES) - West Bengal",
      "Gess J S S Science College - Karnataka",
      "GET B.ED.COLLEGE - Tamil Nadu",
      "Get Well Institute Of Medical & Nursing Education, Ratlam - Madhya Pradesh",
      "GGR College of Engineering - Tamil Nadu",
      "GGS College of Modern Technology - Punjab",
      "GH Patel College of Engg and Technology - Gujarat",
      "GH Patel PG Institute of Business Management - Gujarat",
      "Ghana Kanta Baruah College - Assam",
      "Ghanashyam Hemalata Institute of Technology and Management - Orissa",
      "GHANSHYAM BINANI ACADAMY OF MANAGEMENT SCIENCE - Uttar Pradesh",
      "GHANSHYAM SINGH ARYA KANYA MAHAVIDYALAYA - Chhattisgarh",
      "Gharda Institute Of Technology - Maharashtra",
      "Ghatshila College - Jharkhand",
      "GHAZIABAD INSTITUTE OF MANAGEMENT AND TECHNOLOGY - Uttar Pradesh",
      "Ghess College - Orissa",
      "GHG HARPAKASH TEACHER TRAINING COLLEGE FOR WOMEN - Punjab",
      "Ghol Digrui Sikshan Mandir(B.Ed.) College - West Bengal",
      "Ghousia College of Engineering - Karnataka",
      "Ghousia Polytechnic For Women - Karnataka",
      "Ghousia Polytechnic For Women - Bangalore - Karnataka",
      "GIAN JYOTI INSTITUTE FOR TEACHER EDUCATION - Himachal Pradesh",
      "GIAN JYOTI INSTITUTE OF MANAGEMENT & TECH - Punjab",
      "Gian Sagar College Of Nursing , Patiala - Punjab",
      "Gian Sagar Dental College & Hospital, Patiala - Punjab",
      "Gian Sagar Medical College & Hospital, Patiala - Punjab",
      "Gian Sagar School Of Nursing , Patiala - Punjab",
      "Giani Gurbaksh Singh D.A.V. Centenary College - Punjab",
      "Giani Zail Singh College of Engineering and Technology - Punjab",
      "GICTS COLLEGE OF PROFESSIONAL EDUCATION - Madhya Pradesh",
      "GIET School of Pharmacy , Rajahmundry - Andhra Pradesh",
      "Gifford Memorial Hospital of 7th Day Adventists, School of Nursing , Krishna - Andhra Pradesh",
      "Gimageria Welfare Primary Teacher's Training Institute - West Bengal",
      "Gindo Devi Girls College - Uttar Pradesh",
      "GINNI DEVI MODI INSTITUTE OF EDUCATION, GINNI DEVI MODI GIRLS (PG) COLLEGE CAMPUS - Uttar Pradesh",
      "GIPDCE&T,Visakhapatnam - Andhra Pradesh",
      "GIREESHA SHIKSHANA MAHAVIDYALAYA - Karnataka",
      "Giridhar Ramanarayan Institute Of Commercial Practice - Karnataka",
      "Giridhi Law College - Jharkhand",
      "Giridih College - Jharkhand",
      "Giridih College - Jharkhand",
      "Girijabai Sail Institute of Technology - Karnataka",
      "Girijananda Chowdhury Institute of Management & Technology - Assam",
      "Girijananda Chowdhury Institute of Management and Technology - Assam",
      "GIRIRAJ BAHUUDESHIYA SHIKSHAN SANSTHA - Maharashtra",
      "Giriraj Nursing School ,pune - Maharashtra",
      "Girish Narayan Mishra College - Bihar",
      "Girivaasan Polytechnic College - Tamil Nadu",
      "GIRIVASAN COLLEGE OF EDUCATION - Tamil Nadu",
      "Girls' College - Assam",
      "Girraj Government College - Andhra Pradesh",
      "Girvani Degree College, Chittoor - Andhra Pradesh",
      "Gita Vidya Mandir Girls College - Haryana",
      "Gitam University - Andhra Pradesh",
      "Gitanjali School Of Nursing , Bhubaneswar - Orissa",
      "Gitanjali School Of Nursing , Khurda - Orissa",
      "GITARATALAN INSTITUTE OF ADVANCED STUDIES AND TRAINING - Delhi",
      "GITARATTAN INTERNATIONAL BUSINESS SCHOOL - Delhi",
      "GITS Gwalior Inst. Of Tech. & Sc - Madhya Pradesh",
      "GKM College of Engineering & Technology - Tamil Nadu",
      "GKM PRIMARY TEACHER TRAINING INSTITUTE - Karnataka",
      "GLA Institute of Technology & Management - Uttar Pradesh",
      "GLA University - Uttar Pradesh",
      "Global Academy of Technology - Karnataka",
      "GLOBAL BUSINESS SCHOOL - Karnataka",
      "GLOBAL COLLEGE OF EDUCATION - Karnataka",
      "Global College Of Nursing, Bangalore - Karnataka",
      "Global College Of Nursing, Kanyakumari - Tamil Nadu",
      "Global College Of Nursing, Nasik - Maharashtra",
      "Global College Of Nursing, Gandhinagar - Karnataka",
      "Global College Of Nursing, Nellore - Andhra Pradesh",
      "Global College Of Nursing, Vijayawada - Andhra Pradesh",
      "GLOBAL D ED COLLEGE - Karnataka",
      "GLOBAL EDUCATION SOCIETY - Karnataka",
      "Global Group of Institutions - Andhra Pradesh",
      "Global Health Care Institute School Of Nursing, Nashik - Maharashtra",
      "Global Healthcare Institute College Of Nursing, Nashik - Maharashtra",
      "GLOBAL INSTITUTE OF EDUCATION - Uttar Pradesh",
      "Global Institute of Engineering & Technology - Andhra Pradesh",
      "Global Institute of Engineering and Technology - Tamil Nadu",
      "Global Institute of Engineering and Technology - Andhra Pradesh",
      "GLOBAL Institute of Information Technology - Uttar Pradesh",
      "GLOBAL INSTITUTE OF MANAGEMENT - Orissa",
      "Global Institute of Management and Emerging Technologies - Punjab",
      "GLOBAL INSTITUTE OF MANAGEMENT TECHNOLOGY - Uttar Pradesh",
      "GLOBAL INSTITUTE OF MGT - Punjab",
      "Global Institute Of Nursing, Udaipur - Rajasthan",
      "Global Institute Of Nursing, Jaipur - Rajasthan",
      "Global Institute of Technology - Rajasthan",
      "Global Institute of Technology & Management - Haryana",
      "GLOBAL INSTITUTE OF TECHNOLOGY & MANAGEMENT SCIENCES - Andhra Pradesh",
      "Global Kasthurba College Of Nursing,Hyderabad - Andhra Pradesh",
      "Global Nature Care Sangathan's Group of Institutions, Jabalpur - Madhya Pradesh",
      "Global School Of Nursing , Bangalore - Karnataka",
      "Global School Of Nursing , Hyderabad - Andhra Pradesh",
      "Global School Of Nursing ,Kanyakumari - Tamil Nadu",
      "GLOBAL WOMENS COLLEGE OF EDUCATION - Karnataka",
      "Globus Engineering College - Madhya Pradesh",
      "Globysn Business School - West Bengal",
      "GLS Institute of Business Administration - Gujarat",
      "GLS Institute of Computer Technology - Gujarat",
      "Gm Institute Of Technology - Karnataka",
      "GM Law College - Orissa",
      "GMDARTS & BWCOMMERCE & SCIENCE COLLEGE - Maharashtra",
      "GMERS Medical College, Gandhinagar - Gujarat",
      "GMERS Medical College, Gotri - Gujarat",
      "GMERS Medical College, Sola - Gujarat",
      "GMERS Medical College, Valsad - Gujarat",
      "GMR Institute of Technology - Andhra Pradesh",
      "GMR Polytechnic,Rajamundry - Andhra Pradesh",
      "GMR Polytechnic,srisailam - Andhra Pradesh",
      "GMR.Polytechnic,Madanapalli - Andhra Pradesh",
      "GMT TEACHER TRAINING COLLEGE - Punjab",
      "GN Girls College - Punjab",
      "GNA INSTITUTE OF MANAGEMENT & TECHNOLOGY - Punjab",
      "Gnana Jyothi Degree College, Srikakulam - Andhra Pradesh",
      "GNANA PEETHA EDUCATION TRUST(R) D.ED COLLEGE - Karnataka",
      "Gnana Vikas Polytechnic, Chitradurga - Karnataka",
      "Gnanam School of Business - Tamil Nadu",
      "GNANAM TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "GNANAMANI COLLEGE OF EDUCATION - Tamil Nadu",
      "Gnanamani College of Engineering - Tamil Nadu",
      "Gnanamani College of Technology - Tamil Nadu",
      "Gnanamani Institute of Management Studies - Tamil Nadu",
      "GNANODAYA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "GND TEACHER TRAINING COLLEGE - Punjab",
      "GNIT Girls Institute of Technology - Uttar Pradesh",
      "Gnm School Of Nursing , Calcutta - West Bengal",
      "Gnm Training School , Ranchi - Jharkhand",
      "GNYAN GANGA D.ED COLL - Karnataka",
      "Gnyana Saraswati College of Engineering and Technology - Andhra Pradesh",
      "Goa College Architecture - Goa",
      "Goa College of Engineering - Goa",
      "Goa College of Home Science - Goa",
      "Goa College of Pharmacy - Goa",
      "Goa College ofPharmacy,PANAJI - Goa",
      "Goa College Pharmacy - Goa",
      "Goa Dental College & Hospital, Goa - Goa",
      "GOA INSTITUTE OF MANAGEMENT - Goa",
      "Goa Medical College - Goa",
      "Goa Medical College, Panaji - Goa",
      "Goa Polytechnic - Goa",
      "Goa University - Goa",
      "GOA VIDYAPRASARAK MANDAL'S COLLEGE OF EDUCATION - Goa",
      "Goa Vidyaprasarak Mandals College Education - Goa",
      "Goalpara College - Assam",
      "Goalpura Law College - Assam",
      "Gobardanga Hindu College - West Bengal",
      "Gobardanga Hindu College(B.Ed.) - West Bengal",
      "Gobi Arts and Science College - Tamil Nadu",
      "Gobind Ballabh Pant Degree College - Uttar Pradesh",
      "Gobind Ballabh Pant Polytechnic - Delhi",
      "Gobindapur Academic Primary Teacher's Training Institute - West Bengal",
      "Gobindapur Sephali Memorial Primary - West Bengal",
      "GOBINDGARH TEACHER TRAINING COLLEGE - Punjab",
      "Gochar Mahavidyalaya - Uttar Pradesh",
      "GOCHAR MAHAVIDYALAYA - Uttar Pradesh",
      "Godagari Vidyasagar Educational Institute and Social Welfare Primary Teacher Training Institute - West Bengal",
      "GODAI SHIKSHAN PRASARAK & SANSKRUTIK KRIDA MANDAL - Maharashtra",
      "Godavari College of Engineering - Maharashtra",
      "Godavari College Of Nursing , Jalgoan - Maharashtra",
      "Godavari College Of Nursing,West Godavari - Andhra Pradesh",
      "Godavari Degree College, Rajahmundry - Andhra Pradesh",
      "Godavari Foundations College Of Nursing , Jalgaon - Maharashtra",
      "Godavari Institute of Engineering & Technology - Andhra Pradesh",
      "GODAVARI INSTITUTE OF MANAGEMENT & RESEARCH - Maharashtra",
      "Godavari School Of Nursing , Bidar - Karnataka",
      "Godavari School Of Nursing , Jalgoan - Maharashtra",
      "Godavari School Of Nursing,Jalgaon - Maharashtra",
      "Godavari Shikshan Mandal ,Asian Institute of Pharmacy , Nashik - Maharashtra",
      "Godawri Foundation Dr. Ulhas Patil Homoeopathic Medical College - Maharashtra",
      "Godda College - Jharkhand",
      "Godhra Law College - Gujarat",
      "GODUTAI COLLEGE OF EDUCATION FOR WOMEN - Karnataka",
      "GODUTAI MAHILA SHIKSHAKARA TARABETI KENDRA - Karnataka",
      "Goel Instt. of Pharmacy , BIDAR - Karnataka",
      "Goenka Research Institute of Dental Sciences, Gandhinagar - Gujarat",
      "Gogamukh College - Assam",
      "Goganath Baba Nursing School, Aurangabad - Maharashtra",
      "Gojan School of Business and Technology - Tamil Nadu",
      "GOJAN SCHOOL OF TECHER EDUCATION GOJAN EDUCATION TRUST - Tamil Nadu",
      "Gokahle Education Societys DrTK Tope Arts and Commerce Night (Senior) College - Maharashtra",
      "GOKAK EDUCATION SOCIET COLLEGE OF EDUCATION - Karnataka",
      "Gokaraju Rangaraju College of Pharmacy, Hyderabad - Andhra Pradesh",
      "Gokaraju RangaRaju Institute of Engineering - Andhra Pradesh",
      "Gokaran Narvadeshwar Institute of Technology & Management - Uttar Pradesh",
      "GOKHALE EDUCATION SOCIETY'S COLLEGE OF EDUCATION AND RESEARCH - Maharashtra",
      "Gokhale Education Societys Arts and Commerce College - Maharashtra",
      "Gokhale Education Societys Arts Commerce And Science College - Maharashtra",
      "Gokhale Education Societys NBMehta (Valwada) Science College - Maharashtra",
      "Gokhale Education Societys Shri Bhausaheb Vartak Arts Commerce & Science College - Maharashtra",
      "Gokhale Education Societys Shrimati Manjulabai Raojisa Kashatriya Arts Mahila Mahavidyalaya - Maharashtra",
      "Gokhale Institute Of Politics And Economics - Maharashtra",
      "Gokhale Memorial Girls' College - West Bengal",
      "Gokhle Centenary College - Karnataka",
      "GOKHLE EDUCATION SOCIETYS COLLEGE OF EDUCATION - Maharashtra",
      "Gokul Das Hindu Girls College - Uttar Pradesh",
      "GOKUL DAS HINDU GIRLS COLLEGE - Uttar Pradesh",
      "Gokul Degree College - Andhra Pradesh",
      "Gokul Institute of Tech. & Science - Andhra Pradesh",
      "Gokul Kelvani Mandal Sanchalit Gardi Arts and Commerce College - Gujarat",
      "Gokul Pg College - Andhra Pradesh",
      "GOKUL Polytechnic Colleges - Andhra Pradesh",
      "Gokul Prabhati Ruler College - Orissa",
      "Gokula Krishna College of Engineering - Andhra Pradesh",
      "gokula krishna college of engineering sullurpet - Andhra Pradesh",
      "Gokulananda Maharathi Law College - Orissa",
      "Gokuldas Purushothamdas Ladda (Gpl) Degree College - Andhra Pradesh",
      "Gokuldas Tejpal Hospital,Mumbai - Maharashtra",
      "GOKULDASS HINDU GIRLS COLLEGE - Uttar Pradesh",
      "GOKULPURA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Golaghat Commerce College - Assam",
      "Golaghat Law College - Assam",
      "GOLD FIELD COLLEGE OF EDUCATION - Karnataka",
      "Gold Field Institute of Medical Sciences & Research, Ballabgarh, Faridabad - Haryana",
      "Gold Field Institute Of Technology and Management - Haryana",
      "GOLD FIELD TEACHER TRAINING COLLEGE - Haryana",
      "GOLDEN CITY D ED COL - Karnataka",
      "Golden College Of Nursing,Bangalore - Karnataka",
      "Golden College of Pharmacy , Kolar - Karnataka",
      "Golden Institute Of Nursing Science , Bangalore - Karnataka",
      "Golden Jubilee Institute of Management & Technology - Gujarat",
      "Golden Polytechnic College - Tamil Nadu",
      "Golden School Of Nursing , Bidar - Karnataka",
      "Goldfinch College Of Nursing , Bangalore - Karnataka",
      "Goldfinch School Of Nursing , Bangalore - Karnataka",
      "Gomatesh Polytechnic, Belgaum - Karnataka",
      "GOMATESH TEACHER TRAINING INSTITUTION - Karnataka",
      "Gomathi Ambal Polytechnic College - Tamil Nadu",
      "Gomati Smark College - Uttar Pradesh",
      "Gondia Education Society Manoharbhai Patel Institute of Pharmacy , GONDIA - Maharashtra",
      "Gondia Homoeopathic Medical College and Hospital - Maharashtra",
      "Gondia Nursing College,Gondia - Maharashtra",
      "GONDPIPRI COLLEGE OF EDUCATION - Maharashtra",
      "Gondwana University - Maharashtra",
      "Gonna Institute of Technology and Management Studies - Andhra Pradesh",
      "GONNA KRISHAK POST GRADUAT COLLEGE - Uttar Pradesh",
      "GOOD SAMARITAN COLLEGE OF EDUCATION - Tamil Nadu",
      "GOOD SAMARITAN INSTITUTE OF PHYSICAL EDUCATION - Tamil Nadu",
      "GOOD SHEPHERD COLLEGE OF EDUCATION - Tamil Nadu",
      "GOOD SHEPHERD COLLEGE OF EDUCATION - Tamil Nadu",
      "Gooda College - Jharkhand",
      "Gop College - Orissa",
      "Gopabandhu Ayurvedic Mahavidyalaya - Orissa",
      "Gopabandhu Ayurvedic Mahavidyalaya - Orissa",
      "Gopabandhu Ayurvedic Mahavidyalaya - Orissa",
      "Gopabandhu Institute Of Medical Sci. & Research , Cuttack - Orissa",
      "Gopabandhu Institute Of Medical Sci. & Research ,Cuttack - Orissa",
      "Gopabandhu Institute Of Medical Sci. & Research ,Cuttack - Orissa",
      "Gopal Chandra Memorial - West Bengal",
      "GOPAL D ED COLLEGE - Karnataka",
      "GOPAL DAS MEMORIAL EDUCATIONAL INSTITUTE CHAMRAULI - Uttar Pradesh",
      "Gopal Krishna College of Engineering & Technology - Orissa",
      "Gopal Ramalingam Memorial Engineering College - Tamil Nadu",
      "Gopal Reddy College of Engineering & Technology - Andhra Pradesh",
      "Gopala Gowda College Of Nursing,Mysore - Karnataka",
      "Gopala Gowda Shanthaveri Memorial Hospital Trust, School Of Nursing , Mysore - Karnataka",
      "Gopalan College of Engineering and Management - Karnataka",
      "Gopalbandhu Choudhury College - Orissa",
      "Gopaldas Jhamatmal Advani Law College - Maharashtra",
      "Gopalganj College - Bihar",
      "Gopalji Mahavidyalaya - Uttar Pradesh",
      "Gopalpur College - Orissa",
      "Gopeshwar College - Bihar",
      "GOPESHWAR SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Gopi Chand Arya Mahila College - Punjab",
      "Gopi Krishan Piramal T.T. College - Rajasthan",
      "GOPI NATH DEGREE COLLEGE - Uttar Pradesh",
      "Gopikabai Sita Ram Gawaride Arts & Commerce Colleg - Maharashtra",
      "Gopilalmurlidharsanghi College Commerce - Andhra Pradesh",
      "Gopinath Degree College - Uttar Pradesh",
      "Gopinath Gnm Training College , Nuapada - Orissa",
      "Gopinath Mahavidyalaya - Uttar Pradesh",
      "Gopsai Avinandan Sangha Primary Teacher Training Institute - West Bengal",
      "Gorakh Singh College - Bihar",
      "Goreswar College - Assam",
      "Gossaigaon B.Ed. College - Assam",
      "Gossaigaon College - Assam",
      "Gossner College - Jharkhand",
      "Goswami Ganesh Datt College - Himachal Pradesh",
      "Goswami Ganesh Dutta S D College - Chandigarh",
      "Goswami Tulsidas Rajkiya Mahavidyalaya - Uttar Pradesh",
      "Gour Brahman College Education - Haryana",
      "Gour Mahavidyalaya - West Bengal",
      "Gour Malda College of Education - West Bengal",
      "Gour Mohan Roy College - West Bengal",
      "GOURISHANKAR COLLEGE OF EDUCATION - Maharashtra",
      "Gourmohan Sanchin Mandal Mahavidyalaya - West Bengal",
      "GOUTHAM B.ED COLLEGE - Karnataka",
      "GOUTHAM COLLEGE OF EDUCATION - Karnataka",
      "Goutham College Of Nursing , Bangalore - Karnataka",
      "Goutham College Of Nursing, , Bangalore - Karnataka",
      "Goutham Degree College - Andhra Pradesh",
      "Goutham Instt Of Nsg Science & Research Centre , Bangalore - Karnataka",
      "Goutham School Of Nursing , Chamrajnagar - Karnataka",
      "Gouthama Budha Law College - Karnataka",
      "Gouthami College For Women - Andhra Pradesh",
      "Gouthami College Of Nursing,Bangalore - Karnataka",
      "Gouthami Degree College - Andhra Pradesh",
      "Gouthami Degree College, Medchel - Andhra Pradesh",
      "Gouthami Degree College, Nelakonda Pally - Andhra Pradesh",
      "Gouthami Degree College, Rangareddy - Andhra Pradesh",
      "Gouthami Sai Degree College - Andhra Pradesh",
      "Gouthami School Of Nursing , Bangalore - Karnataka",
      "Govardhan Reddy Degree College - Andhra Pradesh",
      "Goverdhan Das Binnani Mahavidyalaya - Uttar Pradesh",
      "Goverment College - Madhya Pradesh",
      "Goverment College Of Nursing , Raipur - Chhattisgarh",
      "Goverment Engineering College,Bharatpur - Rajasthan",
      "Goverment Medical College, College Of Nursing , Patiala - Punjab",
      "Goverment Medical College,Haldawani - Uttaranchal",
      "Goverment Polytechnic College , Srinagar - Uttaranchal",
      "Governement First Grade College - Karnataka",
      "Government  Polytechnic,  Mudagoda - Karnataka",
      "Government  Polytechnic, Karwar - Karnataka",
      "Government  Polytechnics, Dhenkanal - Orissa",
      "Government (Abv) Degree College - Andhra Pradesh",
      "Government (Asnm) Degree College - Andhra Pradesh",
      "Government (Ch.Vpmr) Degree College - Andhra Pradesh",
      "Government (Csts) Degree College, Jangareddigudem - Andhra Pradesh",
      "Government (Jvr) Degree College - Andhra Pradesh",
      "Government (Ntr) Degree College - Andhra Pradesh",
      "Government (Pingle) Degree College For Women - Andhra Pradesh",
      "Government (Rrds) Degree College - Andhra Pradesh",
      "Government (Scim) Degree College - Andhra Pradesh",
      "Government (Sga) Degree College, Yellamanchili - Andhra Pradesh",
      "Government (Sras) Degree College - Andhra Pradesh",
      "Government (Sum) Degree College - Andhra Pradesh",
      "Government (Sv) Degree College - Andhra Pradesh",
      "Government (Sytr) Degree College - Andhra Pradesh",
      "Government (V.S.S.C) Degree College - Andhra Pradesh",
      "Government (Vsk) Degree College - Andhra Pradesh",
      "Government (Vv.Giri) Degree College - Andhra Pradesh",
      "Government Abhyanandan Sanskrit College - Madhya Pradesh",
      "Government Adarsh Science College - Madhya Pradesh",
      "Government Adarsh Vigyan College - Madhya Pradesh",
      "Government Aes Training College - Madhya Pradesh",
      "Government Agrasen College - Chhattisgarh",
      "Government Anand Music Mahavidyalaya - Madhya Pradesh",
      "Government Anney Bharti Arts & Commerce College - Madhya Pradesh",
      "Government Arts & Commerce College - Madhya Pradesh",
      "Government Arts & Commerce College - Gujarat",
      "Government Arts & Commerce College,SabarKantha - Gujarat",
      "Government Arts & Commerce Degree College - Madhya Pradesh",
      "Government Arts & Commerce Degree College - Madhya Pradesh",
      "Government Arts & Commerce Science College - Madhya Pradesh",
      "Government Arts & Science College - Punjab",
      "Government Arts & Science College - Kerala",
      "Government Arts and Commerce College - Madhya Pradesh",
      "Government Arts And Commerce College - Gujarat",
      "Government Arts And Commerce College,Patan - Gujarat",
      "Government Arts And Commerce P G College - Chhattisgarh",
      "Government Arts And Science College For Women, Bargur - Tamil Nadu",
      "Government Arts And Sports College - Punjab",
      "Government Arts College - Gujarat",
      "Government Arts College - Chhattisgarh",
      "Government Arts College - Madhya Pradesh",
      "Government Arts College - Kerala",
      "Government Arts College - Karnataka",
      "Government Arts College - Madhya Pradesh",
      "Government Arts College - Tamil Nadu",
      "Government Arts College & Commerce - Madhya Pradesh",
      "Government Arts College Bangalore - Karnataka",
      "Government Arts College Chhattisgarh - Chhattisgarh",
      "Government Arts College for Men - Tamil Nadu",
      "Government Arts College For Men, Krishnagiri - Tamil Nadu",
      "Government Arts College for Women - Tamil Nadu",
      "Government Arts College For Women, Krishnagiri - Tamil Nadu",
    ],
  },
];
