const Ndata = [
  {
    colleges: [
      "N A B V Mahila Mandals Nursing Training Centre, Dhule, Maharashtra",
      "N A Manjammal Polytechnic College, Tamil Nadu",
      "N B G S M College, Haryana",
      "N B K R Arts Science College, NELLORE, Andhra Pradesh",
      "N B T N V C College, GUNTUR, Andhra Pradesh",
      "N C Bodiwala M C Desai Commerce College, , Gujarat",
      "N C Patel School Of Nursing , Bangalore, BANGALORE, Karnataka",
      "N D M V P Samajs Training College Of Nursing , Nashik, NASHIK, Maharashtra",
      "N D M V P Samajs Training School Of Nursing,Nashik, NASHIK, Maharashtra",
      "N D R K College Of Nursing , Hassan, HASSAN, Karnataka",
      "N E S Polytechnic, Karnataka",
      "N E Society Polytechnic, Chittapu, Karnataka",
      "N F Railway School Of Nursing , Gauhati, GUWAHATI, Assam",
      "N G Patel Polytechnic Isroli, Gujarat",
      "N H Patel College Education, Gujarat",
      "N H School Of Nursing , Nagapattinam, NAGAPATTINAM, Tamil Nadu",
      "N I M S College Of Nursing , Thiruvananthapuram, TRIVANDRUM, Kerala",
      "N I M S Nursing College , Jaipur, JAIPUR, Rajasthan",
      "N I M S School Of Nursing , Hyderabad, HYDERABAD, Andhra Pradesh",
      "N I M S School Of Nursing, Jaipur, JAIPUR, Rajasthan",
      "N I M S School Of Nursing,Malappuram, MALAPPURAM, Kerala",
      "N I M T College Of Nursing , Jaipur, JAIPUR, Rajasthan",
      "N I M T College Of Nursing,Jaipur, JAIPUR, Rajasthan",
      "N L S College, Bihar",
      "N M Trust Polytechnic, Nidasoshi, Karnataka",
      "N M Wadia Charitable Hospital,Sholapur, SHOLAPUR, Maharashtra",
      "N M Wadia Hospital, School Of Nursing, Pune, PUNE, Maharashtra",
      "N P A Centenary Polytechnic College, Tamil Nadu",
      "N P Arts And Commerce College, Gujarat",
      "N P M Instt Of Medical Science & Research , Keonjhargarh, , Orissa",
      "N R A M Polytechnic, Nitte, Karnataka",
      "N R I College Of Nursing, Guntur, Andhra Pradesh",
      "N R I School Of Nursing, Guntur, Andhra Pradesh",
      "N R School of Architecture, Tamil Nadu",
      "N S Memorial Instt Of Medical Sciences, School Of Nursing, Kollam, Kerala",
      "N S Memorial School Of Nursing, Datia, Madhya Pradesh",
      "N S Patel Arts College, Gujarat",
      "N S S Medical Mission Hospital, Pandalam, Kerala",
      "N S S Medical Mission Hospital, PandalamPandalam, Kerala",
      "N S V K Trust, Sri Venkateshwara, School Of Nursing, Bangalore, Karnataka",
      "N T R Govt Degree College For Women, Mahabubnagar, Andhra Pradesh",
      "N T S, Suri Sadar Hospital, Birbhum, West Bengal",
      "N T S Attached To District Hospital, Dakshin Dinajpur, West Bengal",
      "N T S, District Hospital, Cooch Behar, West Bengal",
      "N T S, District Hospital, Jalpaiguri, West Bengal",
      "N Ts, Murshidabad District Hospital, Murshidabad, West Bengal",
      "N. A. S. College, Meerut, Uttar Pradesh",
      "N. B. M. Law College, Visakhapatnam, Andhra Pradesh",
      "N. B. Thakur Law College, Nashik, Maharashtra",
      "N. D. M. V. P. Samajs Law College, Nashik, Maharashtra",
      "N. K. P. Salve Institute of Medical Sciences, Nagpur, Maharashtra",
      "N. L. Dalmia Institute of Management Studies and Research, , Maharashtra",
      "N. M. D. Arts & Commerce College, Mumbai, Maharashtra",
      "N. R. E. C. College, Bulandshahar, Uttar Pradesh",
      "N. R. I. P. T Allahabad, Uttar Pradesh",
      "N. S. Law College, Sangli, Maharashtra",
      "N. S. S. TRAINING COLLEGE, Kerala",
      "N.A. Manjammal Polytechnic College, Nilgiris, Tamil Nadu",
      "N.A.M. College, Kannur, Kerala",
      "N.A.S. College, Meerut, Uttar Pradesh",
      "N.A.S. College, Uttar Pradesh",
      "N.B. Science & Pg College, HYDERABAD, Andhra Pradesh",
      "N.B.C. College, Orissa",
      "N.B.M. College of Law, VISAKHAPATNAM, Andhra Pradesh",
      "N.B.R. Degree College, Nirmal, Andhra Pradesh",
      "N.B.S. Institute Of Polytechnic, Maharashtra",
      "N.B.T.M. Law College, VISAKHAPATNAM, Andhra Pradesh",
      "N.C. College of Engineering, Haryana",
      "N.C.TEACHER TRAINING COLLEGE, Haryana",
      "N.D. Y.M.C.A. INSTITUTE OF MANAGEMENT, DELHI, Delhi",
      "N.D.M.V.P. Samaj Instt. of Pharmaceutical Sciences , NASHIK, Maharashtra",
      "N.D.M.V.P. Samaj Medical College, Maharashtra",
      "N.D.M.V.P. Samajs Artsscience & Commerce College, Maharashtra",
      "N.D.M.V.P. SAMAJS COLLEGE OF EDUCATION, Maharashtra",
      "N.D.M.V.P. Samajs Law College, NASHIK, Maharashtra",
      "N.D.R.K. COLLEGE OF EDUCATION, Karnataka",
      "N.E.S. College Of Education, Madhya Pradesh",
      "N.E.S. College Of Information Technology, VISAKHAPATNAM, Andhra Pradesh",
      "N.E.S. Law College, JABALPUR, Madhya Pradesh",
      "N.E.S.EDUCATION COLLEGE, Madhya Pradesh",
      "N.E.W.S. Degree College, VISAKHAPATNAM, Andhra Pradesh",
      "N.G.S.M. Institute of Pharmaceutical Sciences , DERALAKATE, Karnataka",
      "N.I.M.H. Northern Regional Centre (NRC), DELHI, Delhi",
      "N.I.M.S INSTITUTE OF MANAGEMENT, JAIPUR, Rajasthan",
      "N.I.M.T INSTITUTE OF AGRI BUSINESS & RURAL MANAGEMENT COLLEGE, JAIPUR, Rajasthan",
      "N.I.M.T INSTITUTE OF HOSPITAL & PHARMA MANAGEMENT, NOIDA, Uttar Pradesh",
      "N.I.M.T. MAHILA TEACHER TRAINING COLLEGE, Rajasthan",
      "N.I.P. TEACHER TRAINING INSTITUTION, Tamil Nadu",
      "N.J.R. TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "N.J.S.A. Government College, Punjab",
      "N.A.S. College, Uttar Pradesh",
      "N.B. Science & Pg College, HYDERABAD, Andhra Pradesh",
      "N.B.C. College, Orissa",
      "N.B.M. College of Law, VISAKHAPATNAM, Andhra Pradesh",
      "N.B.R. Degree College, Nirmal, Andhra Pradesh",
      "N.B.S. Institute Of Polytechnic, Maharashtra",
      "N.B.T.M. Law College, VISAKHAPATNAM, Andhra Pradesh",
      "N.C. College of Engineering, Haryana",
      "N.C.TEACHER TRAINING COLLEGE, Haryana",
      "N.D. Y.M.C.A. INSTITUTE OF MANAGEMENT, DELHI, Delhi",
      "N.D.M.V.P. Samaj Instt. of Pharmaceutical Sciences , NASHIK, Maharashtra",
      "N.D.M.V.P. Samaj Medical College, Maharashtra",
      "N.D.M.V.P. Samajs Artsscience & Commerce College, Maharashtra",
      "N.D.M.V.P. SAMAJS COLLEGE OF EDUCATION, Maharashtra",
      "N.D.M.V.P. Samajs Law College, NASHIK, Maharashtra",
      "N.D.R.K. COLLEGE OF EDUCATION, Karnataka",
      "N.E.S. College Of Education, Madhya Pradesh",
      "N.E.S. College Of Information Technology, VISAKHAPATNAM, Andhra Pradesh",
      "N.E.S. Law College, JABALPUR, Madhya Pradesh",
      "N.E.S.EDUCATION COLLEGE, Madhya Pradesh",
      "N.E.W.S. Degree College, VISAKHAPATNAM, Andhra Pradesh",
      "N.G.S.M. Institute of Pharmaceutical Sciences , DERALAKATE, Karnataka",
      "N.I.M.H. Northern Regional Centre (NRC), DELHI, Delhi",
      "N.I.M.S INSTITUTE OF MANAGEMENT, JAIPUR, Rajasthan",
      "N.I.M.T INSTITUTE OF AGRI BUSINESS & RURAL MANAGEMENT COLLEGE, JAIPUR, Rajasthan",
      "N.I.M.T INSTITUTE OF HOSPITAL & PHARMA MANAGEMENT, NOIDA, Uttar Pradesh",
      "N.I.M.T. MAHILA TEACHER TRAINING COLLEGE, Rajasthan",
      "N.I.P. TEACHER TRAINING INSTITUTION, Tamil Nadu",
      "N.J.R. TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "N.J.S.A. Government College, Punjab",
      "N.K. SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, Rajasthan",
      "N.K. Varadkar Arts & R.V. Belose Commerce College, Maharashtra",
      "N.K.B.M. Girls College, Uttar Pradesh",
      "N.K.B.M.G. COLLEGE, Uttar Pradesh",
      "N.K.B.R. COLLEGE OF PROFESSIONAL STUDIES, Uttar Pradesh",
      "N.K.P. Salve Institute of Medical Sciences, Nagpur, Maharashtra",
      "N.K.R. Government Arts College For Women, Tamil Nadu",
      "N.K.T National College of Education for Women, Chennai, Tamil Nadu",
      "N.K.T. National College Of Education  For Women, Tamil Nadu",
      "N.K.T. NATIONAL COLLEGE OF EDUCATION FOR WOMEN, Tamil Nadu",
      "N.M INSTITUTE OF DIPLOMA AL-AMEEN EDUCATIONAL TRUST, Tamil Nadu",
      "N.M. Christian College, KANYAKUMARI, Tamil Nadu",
      "N.M. College Of Agriculture , Navsari, Gujarat",
      "N.M. Polytechnic College, Tamil Nadu",
      "N.M.D. PG COLLEGE OF ARTS, COMMERCE, LAW & MANAGEMENT, KUDWA, Maharashtra",
      "N.M.K.R.V. First Grade College For Women, Karnataka",
      "N.M.S. DAS P.G. COLLEGE, Uttar Pradesh",
      "N.M.S. Sermathai Vasan College For Women, MADURAI, Tamil Nadu",
      "N.M.S.Kamaraj Polytechnic College, Tamil Nadu",
      "N.M.S.M. Government College, Kerala",
      "N.M.S.M. Government College, WAYANAD, Kerala",
      "N.M.S.N. DASS P.G. COLLEGE, Uttar Pradesh",
      "N.M.S.S. Vellaichamy Nadar College, MADURAI, Tamil Nadu",
      "N.M.S.S.V.N. COLLEGE OF EDUCATION, Tamil Nadu",
      "N.N.R & C.L College, ONGOLE, Andhra Pradesh",
      "N.P. Girls Degree College, Uttar Pradesh",
      "N.P.A. Centenary Polytechnic College, COIMBATORE, Tamil Nadu",
      "N.P.R. P.G. (MCA) COLLEGE, WARANGAL, Andhra Pradesh",
      "N.P.V.N. Patil Law College, AURANGABAD, Maharashtra",
      "N.R. DASS TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "N.R. VEKARIA INSTITUTE OF BUSI. MAGT STUDIES, JUNAGADH, Gujarat",
      "N.R.E.C. College, BULANDSHAHAR, Uttar Pradesh",
      "N.R.E.C. College, Uttar Pradesh",
      "N.R.F.C. COLLEGE, Uttar Pradesh",
      "N.R.I Medical College, Guntur, Andhra Pradesh",
      "N.R.K & K.S.R. Gupta College, GUNTUR, Andhra Pradesh",
      "N.R.M. Degree College, RANGAREDDY, Andhra Pradesh",
      "N.R.T. Krishnaveni Degree College, GUNTUR, Andhra Pradesh",
      "N.S. Law College, SANGLI, Maharashtra",
      "N.S. TEACHER TRAINING COLLEGE, Haryana",
      "N.S.C.B.M. GOVERNMENT COLLEGE, Himachal Pradesh",
      "N.S.N College of Engineering and Technology, Tamil Nadu",
      "N.S.N TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "N.S.S COLLEGE OF EDUCATION, Uttar Pradesh",
      "N.S.S. College, Kerala",
      "N.S.S. College, KOLLAM, Kerala",
      "N.S.S. College, PATHANAMTHITTA, Kerala",
      "N.S.S. College, OTTAPALAM, Kerala",
      "N.S.S. College, IDUKKI, Kerala",
      "N.S.S. College, KERALA, Kerala",
      "N.S.S. College Of Engineering, PALAKKAD, Kerala",
      "N.S.S. Engineering College, Kerala",
      "N.S.S. Hindu College, KOTTAYAM, Kerala",
      "N.S.S. Polytechnic College, Kerala",
      "N.S.S. Training College, Kerala",
      "N.S.S. Training College, OTTAPPALAM, Kerala",
      "N.S.S. Training College, Kerala",
      "N.S.S. Training College, KOTTAYAM, Kerala",
      "N.S.V. Degree College, JAGITYAL, Andhra Pradesh",
      "N.T.A. Arts & Vedumurti S.R. Spare Commerce College, Maharashtra",
      "N.T.R Memorial Degree College, PRAKASAM, Andhra Pradesh",
      "N.T.S. SHRI SHANKAR ARTSAND COMMERCE COLLEGE, Karnataka",
      "N.V. Polytechnic College, Tamil Nadu",
      "N.V.K.S.D. COLLEGE OF EDUCATION, Tamil Nadu",
      "N.V.P. Mandals Artscommerce & Science College, Maharashtra",
      "N.Y.S.S Institute of Diploma in Pharmacy , NAGPUR, Maharashtra",
      "Naami College, Orissa",
      "Naba Krushna Choudhury College of Teacher Education, Orissa",
      "Nabadwip Vidyasagar College, West Bengal",
      "Nabagram Hiralal Paul College, West Bengal",
      "Nabajyoti College, Assam",
      "Nabapravat School Of Nursing , Cuttack, CUTTACK, Orissa",
      "Nabarangpur college, Orissa",
      "Nabarangpur Womens College, Orissa",
      "Nabinchandra College, Assam",
      "Nabira Mahavidalaya, Maharashtra",
      "Nachiappa Swamigal Polytechnic College	, Tamil Nadu",
      "Nachimuthu Polytechnic College, ERODE, Tamil Nadu",
      "Nachimuthu Polytechnic College, Pollachi, Tamil Nadu",
      "NACHIYARAMMAL COLLEGE OF EDUCATION, Tamil Nadu",
      "Nachuni College, , Orissa",
      "NADAPRABHU KEMPEGOWDA EDUCATIONAL SOCIETY, Karnataka",
      "Nadar Mahajana Sangam College of Pharmacy , KANYAKUMARI, Tamil Nadu",
      "NADAR MAHAJANA SANGAM KAMARA COLLEGE OF EDUCATION, , Tamil Nadu",
      "Nadar Mahajana Sangam S. Vellaichamy Nadar College, MADURAI, Tamil Nadu",
      "Nadar Mahajana Sangam Vimala Chelladurai, Tamil Nadu",
      "NADAR NAHAJANA SANGAM S. VELLAICHAMY NADAR COLLEGE, , Tamil Nadu",
      "NADAR SARASWATHI COLLEGE OF EDUCATION, Tamil Nadu",
      "Nadar Saraswathi College Of Engineering, THENI, Tamil Nadu",
      "Nadar Saraswathy College Of Arts And Science, THENI, Tamil Nadu",
      "Nadgir Evening Polytechnic, Karnataka",
      "Nadgir Institute Engineering Technology, Karnataka",
      "Nadgir Polytechnic, Bangalore",
      "Naga Hospital , School Of Nursing, Kohima, KOHIMA, Nagaland",
      "NAGAI COLLEGE OF EDUCATION, Tamil Nadu",
      "Nagaji Institute Of Nursing Sciences , Gwalior, GWALIOR, Madhya Pradesh",
      "NAGAJI INSTITUTE OF TEACHERS EDUCATION, Madhya Pradesh",
      "Nagaji Institute of Technology & Management, GWALIOR, Madhya Pradesh",
      "Nagaland College Of Education, Nagaland",
      "Nagaland College of Teacher Education, Nagaland",
      "NAGALAND INSTITUTE OF MANAGEMENT, DIMAPUR, Nagaland",
      "Nagaland University, Nagaland",
      "Nagamalai Navarasam Arts Science College, ERODE, Tamil Nadu",
      "NAGAMBIKA COLLEGE OF EDUCATION FOR WOMEN, Karnataka",
      "NAGAMMAI TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Nagaon Ed. Trusts, Gangamai College of Engineering, NAGAON, Maharashtra",
      "Nagaon G. N. D. G. Commerce College Nagaon, NAGAON, Assam",
      "Nagar Parishad Polytechnic, Maharashtra",
      "Nagar Yuvak Shikshan Sanstha Shreeram Polytechnic, Maharashtra",
      "Nagar Yuvak Shikshan Sanstha's Datta Meghe College of Engineering, THANE, Maharashtra",
      "NAGAR YUWAK SHIKSHAN SANSTHA-INSTITUTE OF MANAGEMENT & RESEARCH, NAGPUR, Maharashtra",
      "Nagarjuna College of Engineering & Technology, BANGALORE, Karnataka",
      "Nagarjuna College Of Nursing,Krishna, KRISHNA, Andhra Pradesh",
      "Nagarjuna Degree College For Women, CUDDAPAH, Andhra Pradesh",
      "Nagarjuna Degree College, Medak, MEDAK, Andhra Pradesh",
      "Nagarjuna Degree College, Sangareddy, SANGAREDDY, Andhra Pradesh",
      "Nagarjuna Educational Society College Of Nursing,Guntur, GUNTUR, Andhra Pradesh",
      "Nagarjuna Educational Society College Of Nursing,Guntur, GUNTUR, Andhra Pradesh",
      "Nagarjuna Government College, NALGONDA, Andhra Pradesh",
      "Nagarjuna Government Evening College, NALGONDA, Andhra Pradesh",
      "NAGARJUNA INSTITUTE OF MANAGEMENT STUDIES, ONGOLE, Andhra Pradesh",
      "Nagarjuna Institute of Technology & Science, , Andhra Pradesh",
      "Nagarjuna School of Nursing , Vijaywada, Andhra Pradesh",
      "NAGASHREE DIPLOMA IN EDUCATION INSTITUTION, , Karnataka",
      "Nagendra Jha Mahila College, , Bihar",
      "Nagesh Karajagi Orchid College Of Engineering & Technology, Solapur, Maharashtra",
      "Nagesh School Of Nursing , Channarayapatna, Karnataka",
      "Nagfani Insitute Of Nursing, Udaipur, Rajasthan",
      "NAGIN WOMEN WELFARE SOCIETY, Karnataka",
      "Nagindas Khandwala College of Commerce & Arts, Maharashtra",
      "Nagnath Arts Commerce and Science College, Maharashtra",
      "NAGNATH COLLEGE OF PHYSICAL EDUCATION, Maharashtra",
      "Nagnathappa Halge Engineering College, BEED, Maharashtra",
      "Nagpur College of Homoeopathy and Hospital, NAGPUR, Maharashtra",
      "Nagpur Institute of Technology, Maharashtra",
      "Nagpur Sharirik Shikshan Mahavidyalaya, , Maharashtra",
      "NAGPUR SHARIRIK SHIKSHAN MAHAVIDYALAYA, , Maharashtra",
      "Nagpur University, Maharashtra",
      "Nagpur University Dr Baba Saheb ambedkar College of Law, , Maharashtra",
      "NAGPURS COLLEGE OF EDUCATION, , Maharashtra",
      "Nagrik Degree College, Uttar Pradesh",
      "NAGRIK DEGREE COLLEGE, Uttar Pradesh",
      "Nagrik Shahakari Ruganalaya Naradit,Nagpur, NAGPUR, Maharashtra",
      "Nagrik Shikshan Sanstha College of Pharmacy , Mumbai, MUMBAI, Maharashtra",
      "NAGRIK SHIKSHAN SANSTHAS COLLEGE OF EDUCATION, , Maharashtra",
      "Naharkatiya College, Assam",
      "Nahata Jogendra Nath Mandal Smriti Mahavidyalaya, , West Bengal",
      "Nai Disha Institute Of Medical Sciences,Bhopal, BHOPAL, Madhya Pradesh",
      "Nai Disha School Of Nursing , Bhopal, BHOPAL, Madhya Pradesh",
      "Nai Disha Shikshan Prashikshan Evam Jan Kalyan Seva Sansthan, KATIHAR, Bihar",
      "Naiminath Homoeopathic Medical College, AGRA, Uttar Pradesh",
      "Naiminath Homoeopathic Medical College, AGRA, Uttar Pradesh",
      "Naina Mohamed College Of Arts And Science, THANJAVUR, Tamil Nadu",
      "NAINA MOHAMED COLLEGE OF EDUCATION, Tamil Nadu",
      "NAINAB SARASWATHI D E COLLEGE, Karnataka",
      "Naincy College Of Nursing , NAINITAL, Uttaranchal",
      "Naincy School Of Nursing , NAINITAL, Uttaranchal",
      "Naincy School Of Nursing ,NAINITAL, Uttaranchal",
      "Naipunnya Institute of Management and Information Technology, Kerala",
      "Nair Hospital Dental College, Maharashtra",
      "NAIRS TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Nakachari College, Assam",
      "Nakoda Parshavnath Jain Mahavidyalaya, Rajasthan",
      "Naktideul College, Orissa",
      "NALAND TEACHER TRAINING COLLEGE, Himachal Pradesh",
      "Nalanda College, Bihar",
      "Nalanda College Of Arts & Science, KASARAGOD, Kerala",
      "NALANDA COLLEGE OF EDUCATION, Uttaranchal",
      "NALANDA COLLEGE OF EDUCATION, Karnataka",
      "Nalanda college of pharmacy , NALGONDA, Andhra Pradesh",
      "NALANDA D ED COLLEGE, Karnataka",
      "NALANDA D.ED COLLEGE, Karnataka",
      "Nalanda Degree College, Andhra Pradesh",
      "Nalanda Degree College For Women, NIZAMABAD, Andhra Pradesh",
      "Nalanda Degree College, Adilabad, Andhra Pradesh",
      "Nalanda Degree College, Bheemgal, Andhra Pradesh",
      "Nalanda Degree College, Mahabubabad, Andhra Pradesh",
      "Nalanda Degree College, Medak, Andhra Pradesh",
      "Nalanda Degree College, Miryalaguda, Andhra Pradesh",
      "Nalanda Degree College, Mulugu, Andhra Pradesh",
      "Nalanda Degree College, Nalgonda, Andhra Pradesh",
      "Nalanda Degree College, Nizamabad, Andhra Pradesh",
      "Nalanda Degree College, Uppal, Andhra Pradesh",
      "NALANDA DIPLOMA IN EDUCATION, Karnataka",
      "Nalanda Engineering College, Nalanda, Bihar",
      "Nalanda Foundation Polytechnic, Hubli, Karnataka",
      "Nalanda Institute of Engineering & Technology, Guntur, Andhra Pradesh",
      "Nalanda Institute of Management Studies, Andhra Pradesh",
      "Nalanda Institute of P.G Studies, Andhra Pradesh",
      "Nalanda Institute of Technology, Orissa",
      "Nalanda Institute of Technology, Orissa",
      "Nalanda Law College, Mumbai, Maharashtra",
      "Nalanda Mahila College, Bihar",
      "Nalanda Medical College, Patna, Bihar",
      "Nalanda Medical College & Hospital , School Of Nursing , Patna, Bihar",
      "Nalanda Medical College, Patna, Bihar",
      "Nalanda Nursing School , Nalanda, Bihar",
      "Nalanda Open University, Patna, Bihar",
      "Nalanda Open University, Bihar",
      "Nalanda School of Business, Tamil Nadu",
      "Nalanda Teacher's Training College, Bihar",
      "Nalbari College, Nalbari, Assam",
      "Nalbari Commerce College, Assam",
      "Nalbari Law College, Nalbari, Assam",
      "Nalini Arvind T V Patel Arts College, Gujarat",
      "Nalini Devi Women Teachers Training College, Orissa",
      "Nalini Devi Womens College of Teacher Education, Orissa",
      "Nalla Malla Reddy Engineering College, Andhra Pradesh",
      "Nallamuthu Gounder Mahalingam College, Pollachi, Tamil Nadu",
      "Nalsar University Of Law, Hyderabad, Andhra Pradesh",
      "NALWA TEACHER TRAINING COLLEGE, Haryana",
      "Nam Ratra International College Of Nursing , Amritsar, Punjab",
      "Nam Ratra International School Of Nursing , Amritsar, Punjab",
      "Nam Rattra International College Of Nursing , Amritsar, Punjab",
      "Namakkal Kavignar Ramalingam Government Arts College For Women, Tamil Nadu",
      "Nambikkai Foundation, TUTICORIN, Tamil Nadu",
      "Nambol L. Sanoi College, Manipur",
      "NAMBOODIRIS COLLEGE OF EDUCATION, Kerala",
      "Namco Charitable Trust,Sardhar, Maharashtra",
      "NAMDHARI TEACHER TRAINING COLLEGE, Himachal Pradesh",
      "Namitadevi School Of Nursing , Puri, Orissa",
      "Namrup College, Assam",
      "Namrup College of Teacher's Education, Assam",
      "NANADURBAR TALUKA VIDHAYAK SAMITIS, Maharashtra",
      "Nanakram Bhagwandas Science College, Andhra Pradesh",
      "Nanasaheb Mahadik Polytechnic Institute, Maharashtra",
      "NANCY TEACHER TRAINING COLLEGE, Punjab",
      "NAND KISHORE SINGH DEGREE COLLEGE, Uttar Pradesh",
      "NAND KISHORE SINGH DEGREE COLLEGE, Uttar Pradesh",
      "Nanda Gokula School Of Nursing , Kolar, Karnataka",
      "Nanda Hospital , Una, Himachal Pradesh",
      "Nanda Nath Saikia College, Assam",
      "Nandalal Ghosh B.T. College, West Bengal",
      "Nandalal Ghosh B.T. College, West Bengal",
      "Nandan Sanskrit Mahavidyalaya, Bihar",
      "Nandana Degree College, NIRMAL, Andhra Pradesh",
      "NANDANI NAGAR MAHAVIDYALAYA, Uttar Pradesh",
      "NANDANI NAGAR MAHAVIDYALAYA, Uttar Pradesh",
      "Nandanpur Teacher's Training Institute, West Bengal",
      "Nanded Rural Dental College & Research Centre, Maharashtra",
      "Nandha Arts and Science College, ERODE, Tamil Nadu",
      "Nandha College Of Nursing , Perundurai, ERODE, Tamil Nadu",
      "Nandha College of Paramedical Sciences , Perudurai, ERODE, Tamil Nadu",
      "Nandha College of Pharmacy, Tamil Nadu",
      "Nandha College of Pharmacy , Perundurai, ERODE, Tamil Nadu",
      "Nandha College of Physiotherapy, ERODE, Tamil Nadu",
      "Nandha College Technology, Tamil Nadu",
      "Nandha Engineering College, ERODE, Tamil Nadu",
      "Nandha Polytechnic College, ERODE, Tamil Nadu",
      "Nandha School Of Nursing, , ERODE, Tamil Nadu",
      "NANDHA TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "NANDI TEACHER TRAINING INSTITUTE, Karnataka",
      "NANDINI COLLEGE, Karnataka",
      "Nandini Nagar Law College, BAREILLY, Uttar Pradesh",
      "Nandini Nagar Mahavidyalaya, Uttar Pradesh",
      "Nandini Nagar Mahavidyalaya College of Pharmacy , Gonda, Uttar Pradesh",
      "Nandini Nursing College,Raichur, RAICHUR, Karnataka",
      "Nandini Nursing School , Shimoga, SHIMOGA, Karnataka",
      "Nandini School Of Nursing , Raichur, RAICHUR, Karnataka",
      "NANDINI TEACHERS TRAINING COLLEGE, Karnataka",
      "Nandurbar Taluka Vidhayak Samiti, Institute of Pharmacy , Nandurbar, DHULE, Maharashtra",
      "Nandurbar Taluka Vidhayak Samitis College of Law, NANDURBAR, Maharashtra",
      "Nandurbar Taluka Vidhayak Samitis College of Law Nstitute of Legal Education & Research, NANDURBAR, Maharashtra",
      "Nandvandan College Of Nursing , Jabalpur, JABALPUR, Madhya Pradesh",
      "NANI-BAI COLLEGE OF EDUCATION, Maharashtra",
      "NANJAMMA TEACHER TRAINING INSTITUTE, Karnataka",
      "Nanjappa Institute Of Nursing Sciences College Of Nursing,Shimoga, SHIMOGA, Karnataka",
      "Nanjappa Institute Of Technology, COIMBATORE, Tamil Nadu",
      "Nanjappa Trust Hospital , School Of Nursing , Shimoga, SHIMOGA, Karnataka",
      "Nanjiah Lingammal Polytechnic College, KANYAKUMARI, Tamil Nadu",
      "Nanjiah Lingammal Polytechnic College, , Tamil Nadu",
      "NANKANA SAHIB TEACHER TRAINING COLLEGE, , Punjab",
      "Nao Nalanda Mahavihar, , Bihar",
      "Naorem Birahari College, , Manipur",
      "Naradha Art Science College, ERODE, Tamil Nadu",
      "Narain College, , Uttar Pradesh",
      "Naraina College of Engineering & Technology, KANPUR, Uttar Pradesh",
      "Naraina Nursing College , Kanpur, KANPUR, Uttar Pradesh",
      "Naraina Nursing College,Kanpur, KANPUR, Uttar Pradesh",
      "Naraina Vidya Peeth Management Institute, , Uttar Pradesh",
      "Narajole Raj College, , West Bengal",
      "Naran Lala School Of Industrial Management and Computer Science, , Gujarat",
      "Narandas Jethalal Sonecha Management & Technical Institute, , Gujarat",
      "Narasaraopet Engineering College, , Andhra Pradesh",
      "Narasimha Reddy Engineering College, , Andhra Pradesh",
      "Narasimma Pallavan Polytechnic College, , Tamil Nadu",
      "Narasingha Choudhury College, , Orissa",
      "Narasingha Dutta College, , West Bengal",
      "Narasinghapur Primary Teacher Training Institute, , West Bengal",
      "Narasu's Sarathy Institute of Technology, SALEM, Tamil Nadu",
      "NARAYAN ARYA KANYA PATHSALA POST GRADUATE COLLEGE, , Uttar Pradesh",
      "Narayan Arya Kanya Pathshala Degree PG College, , Uttar Pradesh",
      "NARAYAN INSTITUTE OF EDUCATION & TECHNOLOGY, , Uttar Pradesh",
      "Narayan Mahavidyalaya, , Bihar",
      "Narayan Medical College And Hospital, Sasaram, , Bihar",
      "Narayan S.S. College, , Kerala",
      "NARAYAN SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, , Rajasthan",
      "Narayan Swami College Of Nursing,Dehradun, DEHRADUN, Uttaranchal",
      "Narayan Swamy Institute of Medical Science & Research , Dehradun, DEHRADUN, Uttaranchal",
      "Narayana College Of Nursing , Nellore, NELLORE, Andhra Pradesh",
      "Narayana College Of Nursing, Nellore, Andhra Pradesh",
      "Narayana Dental College & Hospital , Chinthareddypalem, Nellore, Andhra Pradesh",
      "Narayana Dora Degree College, SRIKAKULAM, Andhra Pradesh",
      "Narayana Engineering College, Andhra Pradesh",
      "Narayana Hrudayala School Of Nursing , Bangalore, Karnataka",
      "Narayana Hrudayalaya College Of Nursing , Bangalore, Karnataka",
      "Narayana Medical College, Nellor, Andhra Pradesh",
      "Narayana Medical College, Nellore, Andhra Pradesh",
      "Narayana Memorial Degree College, KRISHNA, Andhra Pradesh",
      "Narayana Polytechnic,Gudem, Andhra Pradesh",
      "Narayana School Of Nursing , Nellore, Andhra Pradesh",
      "Narayana School Of Nursing , Srikakulam, Andhra Pradesh",
      "NARAYANA TEACHER TRAINING COLLEGE, Haryana",
      "Narayanaguru College of Engineering, KANYAKUMARI, Tamil Nadu",
      "Narayanbhai Bhikhabhai Patel Polytechnic, Gujarat",
      "Narayani School Of Nursing , Jagatsinghpur, Orissa",
      "NARAYANJI DEVI GIRLS TEACHER TRAINING COLLEGE, Rajasthan",
      "Narayanpet Institute of Technology & Science, MAHABUBNAGAR, Andhra Pradesh",
      "NARAYANRAO PATIL WASADE COLLEGE OF PHYSICAL EDUCATION, Maharashtra",
      "NARAYNI DEVI VERMA MAHILA PHYSICAL EDUCATION TEACHER TRAINING COLLEGE, Rajasthan",
      "NARAYNI DEVI VERMA MAHILA PHYSICAL EDUCATION TEACHER TRAINING COLLEGE, Uttar Pradesh",
      "NARENDAR COLLEGE OF EDUCATION, Tamil Nadu",
      "NARENDRA COLLEGE OF PHYSICAL EDUCATION, Karnataka",
      "Narendra Degree College, ARMOOR, Andhra Pradesh",
      "Narendra Degree College, Metpally, Andhra Pradesh",
      "Narendra Deva University Of Agriculture Technology, Uttar Pradesh",
      "Narendra Womens Degree College, ARMOOR, Andhra Pradesh",
      "NARESH SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, Rajasthan",
      "Nargund College of Pharmacy, Karnataka",
      "Nargund College of Pharmacy , Bangalore, Karnataka",
      "Nargund College of Pharmacy, Bangalore, Karnataka",
      "Narhar Balwant Thankur Law College, Nashik, Maharashtra",
      "Narheji Degree College, Uttar Pradesh",
      "Nari Shiksha Niketan Degree College, Uttar Pradesh",
      "NARIPELLA NARAYANA SWAMY VIDYA COLLEGE OF PG STUDIES, MANDAL, Andhra Pradesh",
      "Naripella Narayana Swamy Vidya Degree College, CHIRALA, Andhra Pradesh",
      "NARMADA COLLEGE OF MANAGEMENT, BHARUCH, Gujarat",
      "Narmada College Science And Commerce, Gujarat",
      "NARMADA DEVI MAHILA MAHAVIDYALAY, Uttar Pradesh",
      "NARMADA EDUCATION SOCIETY COLLEGE OF EDUCATION, Madhya Pradesh",
      "Narottam Singh Padam Singh Government College, Uttar Pradesh",
      "Narsaspur Christian Hospital & School Of Nursing, WEST GODAVARI, Andhra Pradesh",
      "NARSEE MONJEE INSTITUE OF MANAGEMENT STUDIES, MUMBAI, Maharashtra",
      "Narsinghpur College, Orissa",
      "Narsinhbhai Patel Dental College & Hospital, VISNAGAR, Gujarat",
      "Narula Institute of Technology, West Bengal",
      "Narula Institute of Technology -School of Management Studies, KOLKATA, West Bengal",
      "NARVA DESHWAR COLLEGE, Uttar Pradesh",
      "NARVADESHWAR MANAGEMENT COLLEGE, Uttar Pradesh",
      "Narvadeshwar Vidhi Mahavidyalaya, Uttar Pradesh",
      "Narvdeshwar Vidhi Mahavidyalaya, LUCKNOW, Uttar Pradesh",
      "NAS PG COLLEGE, Uttar Pradesh",
      "Nasamony Memorial Christian College, KANYAKUMARI, Tamil Nadu",
      "Naseema Institute of Speech & Hearing, BANGALORE, Karnataka",
      "NASHIK DISTRICT MARATHA VIDYA PRASARAK SAMAJ-INSTITUTE OF MANAGEMENT RESEARCH & TECHNOLOGY, NASHIK, Maharashtra",
      "Nashik Nursing School, AURANGABAD, Maharashtra",
      "NASIK GRAMIN SHIKSHA PRASARAK MANDAL BRAHAMA VALLEY COLLEGE OF EDUCATION, Maharashtra",
      "Nasik Medico Training Pvt Ltd, School Of Nursing, NASHIK, Maharashtra",
      "Nasik Nursing School, Nashik, Maharashtra",
      "Nataraj Research Centre & Training College, BHAVNAGAR, Gujarat",
      "NATESAN INSTITUTE OF CO-OPERATIVE MANAGEMENT, CHENNAI, Tamil Nadu",
      "Nath Chandrawat Mahavidyalaya, Uttar Pradesh",
      "NATHAM P.R. COLLEGE OF EDUCATION, Tamil Nadu",
      "NATHAM P.R. TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Nathubai V Patel College Pure Applied Science, Gujarat",
      "Nathulal das Primary Teacher's Training Institute, West Bengal",
      "National Academy of Legal Studies And Research University of Law (Nalsar), HYDERABAD, Andhra Pradesh",
      "National Association for the Blind, MUMBAI, Maharashtra",
      "National Association for the Blind, NASHIK, Maharashtra",
      "National Association for the Welfare of the Physically Handicapped, AMRAVATI, Maharashtra",
      "NATIONAL B.ED. COLLEGE, Madhya Pradesh",
      "National Brain Research Centre, Haryana",
      "National Centre for Rural Development Institute of Pharmacy , Navi Mumbai, MUMBAI, Maharashtra",
      "National College, Karnataka",
      "National College, Karnataka",
      "National College, Karnataka",
      "National College, Orissa",
      "National College, Punjab",
      "National College, TRICHY, Tamil Nadu",
      "National College, TRIVANDRUM, Kerala",
      "National College, Orissa",
      "National College for Women, Punjab",
      "National College Of Arts & Science, KOZHIKODE, Kerala",
      "NATIONAL COLLEGE OF EDUCATIO KRITHIKA GARDEN, Tamil Nadu",
      "National College of Education, Karnataka",
      "NATIONAL COLLEGE OF EDUCATION, Karnataka",
      "National College of Engineering, Tamil Nadu",
      "National College Of General Nursing & Midwifery , Barnala, Punjab",
      "National College of Health Sciences, Punjab",
      "National College of Law, SHIMOGA, Karnataka",
      "National College Of Nursing, Bangalore, Karnataka",
      "National College Of Nursing, Hissar, Haryana",
      "National College of Pharmacy, Kozhikode, Kerala",
      "National College of Pharmacy, Mukkam, Kerala",
      "National College of Pharmacy, Shimoga, Karnataka",
      "National College of Pharmacy, Tiruvallur, Tamil Nadu",
      "NATIONAL COLLEGE OF PHYSICAL EDUCATION,PATIALA, Punjab",
      "National College of Polytechnic, Haryana",
      "NATIONAL COLLEGE OF TEACHERS EDUCATION, Madhya Pradesh",
      "NATIONAL D.ED. COLLEGE, Karnataka",
      "National Dairy Research Institute, Haryana",
      "National Degree College, Uttar Pradesh",
      "National Degree College, Lucknow, Uttar Pradesh",
      "National Degree College Andhra Pradesh, Paloncha, Andhra Pradesh",
      "National Degree College, Kurnool, Andhra Pradesh",
      "National Degree College, Secunderbad, Andhra Pradesh",
      "National Dental College & Hospital, Gulabgarh, Punjab",
      "NATIONAL EDUCATION AND CULTURE TRUST,DADUHI, Himachal Pradesh",
      "NATIONAL EDUCATION COLLEGE, Madhya Pradesh",
      "National Education Institute Of Nursing, Nagaur, Rajasthan",
      "NATIONAL EDUCATIONAL TRUST, Karnataka",
      "National Engineering College, Kovilpatti, Tamil Nadu",
      "National Evening College Of Commerce, Karnataka",
      "National Health Care Charitable Trust ,Nadia, West Bengal",
      "National Health Law Research Institute, Sangli, Maharashtra",
      "National Homeopathic College, Uttar Pradesh",
      "National Hospital College Of Nursing , Calicut, Kerala",
      "National Hospital School Of Nursing, Calicut, Kerala",
      "NATIONAL INDUSTRIAL CULTURAL & EDUCATION. TRUST D.ED COLLEGE, Karnataka",
      "National Institue of Abiotic Stress Management, Maharashtra",
      "National Institute For Advanced Legal Studies, KOCHI, Kerala",
      "National Institute for Empowerment of Persons with Multiple Disabilities, , Tamil Nadu",
      "National Institute for Teacher Education, , Assam",
      "National Institute for the Mentally Handicapped, RAJAHMUNDRY, Andhra Pradesh",
      "National Institute for the Mentally Handicapped Regional Training Centre, KOLKATA, West Bengal",
      "National Institute for the Mentally Handicapped, Regional Centre, MUMBAI, Maharashtra",
      "National Institute for the Orthopaedically Handicapped, KOLKATA, West Bengal",
      "National Institute for the Orthopaedically Handicapped, AIZAWL, Mizoram",
      "National Institute For The Orthopaedically Handicapped , Kolkata, KOLKATA, West Bengal",
      "National Institute for the Orthopedically Handicapped  Regional Centre, DEHRADUN, Uttaranchal",
      "National Institute For The Orthopedically Handicapped , Kolkata, KOLKATA, West Bengal",
      "National Institute for the Visually Handicapped, DEHRADUN, Uttaranchal",
      "National Institute for the Visually Handicapped, CHENNAI, Tamil Nadu",
      "National Institute of Agricultural Marketing, , Rajasthan",
      "NATIONAL INSTITUTE OF AGRICULTURE MARKETING, JAIPUR, JAIPUR, Rajasthan",
      "National Institute of Ayurvedic, , Rajasthan",
      "National Institute of Bank Management, , Maharashtra",
      "National Institute of Business Studies (NIBS), , Delhi",
      "National Institute of Business Studies (NIBS), , Delhi",
      "NATIONAL INSTITUTE OF CO-OPERATIVE MANAGEMENT, GANDHI NAGAR, Gujarat",
      "NATIONAL INSTITUTE OF FINANCIAL MANAGEMENT, , Haryana",
      "National Institute of Fire Engineering & Safety Management, VISAKHAPATNAM, Andhra Pradesh",
      "National Institute of Food Technology, Entrepreneurship & Management, , Haryana",
      "National Institute of Foundry and Forge Technology, RANCHI, Jharkhand",
      "National Institute of Health And Family Welfare, DELHI, Delhi",
      "National Institute of Health and Family Welfare, New Delhi, DELHI, Delhi",
      "National Institute Of Health Edu & Research , Patna, PATNA, Bihar",
      "National Institute of Homoeopathy, , West Bengal",
      "NATIONAL INSTITUTE OF HUMAN RESOURCES DEVELOPEMENT, CHENNAI, Tamil Nadu",
      "National Institute of Industrial Engineering, MUMBAI, Maharashtra",
      "National Institute of Industrial Engineering - NITIE, Mumbai, Maharashtra",
      "National Institute of Law, Kurukshetra, Haryana",
      "NATIONAL INSTITUTE OF MANAGEMENT STUDIES, Chingleput, Tamil Nadu",
      "National Institute Of Medical & Management Studies , Bhubaneswar, Orissa",
      "National Institute of Medical Science & Research , Jaipur, Rajasthan",
      "National Institute of Medical Science & Research, Jaipur, Rajasthan",
      "National Institute of Mental Health & Neurosciences, Bangalore, Karnataka",
      "National Institute Of Mental Health And Neuro Sciences, Karnataka",
      "National Institute Of Nursing , Sangrur, Punjab",
      "National Institute Of Nursing Education , Chandigarh, Chandigarh",
      "National Institute Of Nursing Education, Chandigarh, Chandigarh",
      "National Institute Of Nursing Education,Chandigarh, Chandigarh",
      "National Institute of Planning Management, West Bengal",
      "National Institute of Polytechnic, Udayarpalayam, Tamil Nadu",
      "National Institute of Research on Jute & Allied Fibre Technology, Kolkata, West Bengal",
      "National Institute of Science & Technology, Berhampur, Orissa",
      "National Institute of Social Work, Maharashtra",
      "National Institute Of Social Work & Social Sciences ., Orissa",
      "National Institute of Speech & Hearing, Kerala",
      "National Institute of Speech & Hearing, Kerala",
      "National Institute of Technical Teachers Training and Research, Madhya Pradesh",
      "National Institute of Technical Teachers' Training & Res, West Bengal",
      "National Institute of Technical Teachers' Training & Research, NITTTR, Chandigarh, Chandigarh",
      "National Institute of Technology (NIT), Agartala, Tripura",
      "National Institute of Technology (NIT), Durgapur, West Bengal",
      "National Institute of Technology (NIT), Hamirpur, Himachal Pradesh",
      "National Institute of Technology (NIT), Jamshedpur, Jharkhand",
      "National Institute of Technology (NIT), Kannada, Karnataka",
      "National Institute of Technology (NIT), Kozhikode, Kerala",
      "National Institute of Technology (NIT), Kurukshetra, Haryana",
      "National Institute of Technology (NIT), Patna, Bihar",
      "National Institute of Technology (NIT), Raipur, Chhattisgarh",
      "National Institute of Technology (NIT), Rourkela, Orissa",
      "National Institute of Technology (NIT), Silchar, Assam",
      "National Institute of Technology (NIT), Srinagar, Jammu and Kashmir",
      "National Institute of Technology (NIT), Trichy, Tamil Nadu",
      "National Institute of Technology (NIT),Meghalaya, Meghalaya",
      "National Institute of Technology (NIT),nagaland, Nagaland",
      "National Institute of Technology (NIT),Sikkim, Sikkim",
      "National Institute of Technology (NIT)-Arunachal Pradesh, Arunachal Pradesh",
      "National Institute of Technology (NIT)-GOA, Goa",
      "National Institute of Technology (NIT)-Manipur, Manipur",
      "National Institute of Technology (NIT)-Uttarakhand, Haryana",
      "National Institute of Technology REC, Haryana",
      "National Institute of Technology(NIT)-Jalandhar, Punjab",
      "National Institute Of Technology,warangal, Andhra Pradesh",
      "National Institute of Virology, PUNE, Maharashtra",
      "National Instt Of Medical Sciences,Jaipur, Rajasthan",
      "National Instt. Of Mental Health & Neuro Sciences , Bangalore, Karnataka",
      "NATIONAL INSURANCE ACADEMY, Maharashtra",
      "National Law Institute University, Madhya Pradesh",
      "National Law School of India University, BANGALORE, Karnataka",
      "National Law School Of Indian University, Karnataka",
      "National Law University, Rajasthan",
      "National Law University, Orissa",
      "National Law University, Delhi",
      "National Law University and Judicial Academy, Assam",
      "National Management College, ERODE, Tamil Nadu",
      "National Minorities Degree College, CHIRALA, Andhra Pradesh",
      "National Museum Institute Of History Of Art, DELHI, Delhi",
      "National Nursing Institute , Hissar, Haryana",
      "NATIONAL P.G. COLLEGE, , Madhya Pradesh",
      "NATIONAL POST GRADUATE COLLEGE, , Uttar Pradesh",
      "NATIONAL POST GRADUATE COLLEGE, , Uttar Pradesh",
      "National Power Training Institute, DELHI, Delhi",
      "NATIONAL POWER TRAINING INSTITUTE, FARIDABAD, Haryana",
      "National Power Training Institute, Haryana",
      "National Power Training Institute Nagpur, NAGPUR, Maharashtra",
      "National Power Training Institute West Bengal, , West Bengal",
      "National Scchol Of Nursing,Malappuram, MALAPPURAM, Kerala",
      "National School Of Drama, DELHI, Delhi",
      "National School Of Nurisng , Thiruvananthapuram, TRIVANDRUM, Kerala",
      "National School Of Nursing , Bangalore, BANGALORE, Karnataka",
      "National School Of Nursing , Bellary, BELLARY, Karnataka",
      "National School Of Nursing , Fatehabad, , Haryana",
      "National School Of Nursing , Hissar, HISSAR, Haryana",
      "National School of Nursing , Ongole, ONGOLE, Andhra Pradesh",
      "National School Of Nursing , Sangrur, SANGRUR, Punjab",
      "National School Of Nursing,Akola, AKOLA, Maharashtra",
      "National School Of Nursing,Hisar, HISSAR, Haryana",
      "National Science Degree College, SRIKAKULAM, Andhra Pradesh",
      "National Sugar Institute, KANPUR, Uttar Pradesh",
      "NATIONAL TEACHER TRAINING COLLEGE,LOHARU, , Haryana",
      "NATIONAL TEACHER TRAINING COLLEGE,SIRSA, , Haryana",
      "NATIONAL TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "NATIONAL TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "National Teacher's Training College, Bihar",
      "NATIONAL TEACHERS TRAINING COLLEGE FOR GIRLS,VIJAY NAGAR, Rajasthan",
      "NATIONAL TEACHERS TRAINING INSTITUTE, Kerala",
      "NATIONAL TEACHERS TRAINING INSTITUTE, Karnataka",
      "NATIONAL TRAINING COLLEGE FOR WOMEN, Kerala",
      "National University of Advanced Legal Studies NUALS, KOCHI , Kerala",
      "National University Of Educational Planning Administration, DELHI , Delhi",
      "Natraj Polytechnic, Himachal Pradesh",
      "NATTHU SINGH MAHAVIDYALAYA, Uttar Pradesh",
      "Natwarlal Maniklal Dalal College Of Arts & Commerce, Maharashtra",
      "NAV BHARTI SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, Rajasthan",
      "NAV JAGRATI EDUCATION SOCIETY, , Madhya Pradesh",
      "Nav Nirman School Of Nursing,Chandrapur, CHANDRAPUR , Maharashtra",
      "Nav Samwat Law College, UJJAIN , Madhya Pradesh",
      "Nav Vani School for the Deaf, VARANASI , Uttar Pradesh",
      "NAVA BHARATHI COLLEGE OF PG STUDIES, SECUNDERABAD , Andhra Pradesh",
      "Nava Chaitanya Degree College, NARAYANGUDA , Andhra Pradesh",
      "NAVABHARATAEDUCATION. & PLANTATION FARMERS SOCIETY, , Karnataka",
      "Navabharath Degree College, SATHUPALLY , Andhra Pradesh",
      "Navachaitanya Mphwf Trg Institute,Guntur, GUNTUR , Andhra Pradesh",
      "NAVACHETHANA D.ED COLLEGE, Karnataka",
      "Navada Gram Udyog Vikas Samiti, Uttar Pradesh",
      "Navajeevan Residential Special school for the Deaf (HI), NANDYAL , Andhra Pradesh",
      "NAVAJYOTHI COLLEGE OF TEACHER EDUCATION FOR WOMEN, , Kerala",
      "NAVAKARNATAKA D.ED COLLEGE, Karnataka",
      "Naval College of Engineering. INS, Shivaji, PUNE , Maharashtra",
      "Naval Kishor Shivhare Nursing College , Bhind, BHIND , Madhya Pradesh",
      "Naval Kishore Shivhare Nursing College , Bhind, BHIND , Madhya Pradesh",
      "Naval Kishore Shivhare Nursing School, Bhind, BHIND , Madhya Pradesh",
      "Naval Kishore Shivhare School Of Nursing , Bhind, BHIND , Madhya Pradesh",
      "Naval's Girls Degree College, Uttar Pradesh",
      "NAVALBHAU PRATHISTHANS COLLEGE OF EDUCATION, Maharashtra",
      "Navalbhau Pratisthans Rukhminitai Arts And Commerce Mahila College, Maharashtra",
      "Navalbhau Pratisthas V. N. Patil Law College, AURANGABAD, Maharashtra",
      "Navambey Arts and Commerce College, Madhya Pradesh",
      "Navaneetham College Of Nursing , Bangalore, Karnataka",
      "Navaneetham School Of Nursing , Bangalore, Karnataka",
      "NAVANITAL RANCHHOLAL INSTITUTE OF BUSINESS MANAGEMENT, AHMEDABAD, Gujarat",
      "Navarasam Arts And Science College For Women, ERODE, Tamil Nadu",
      "NAVEEN BHARTI TEACHER TRAINING COLLEGE, Rajasthan",
      "NAVEEN COLLEGE OF EDUCATION, Karnataka",
      "NAVEEN VIDYAPEETH TEACHERS TRAINING COLLEGE, Rajasthan",
      "Naveena College, RANGAREDDY, Andhra Pradesh",
      "Navgan Shikshan Sanstha Rajuri (N) MrsKesharbhai Sonajirao Kshirsagar Alias Kaku Arts Science & Commerce College, Maharashtra",
      "Navgan Shikshan Sansthas Arts And Commerce College, Maharashtra",
      "Navgujarat Law College, AHMEDABAD, Gujarat",
      "NAVIN OSMANABAD ZILLA BALVIKAS SAMITEE, Maharashtra",
      "Navinchandra Mehta Institute of Technology and Development, Maharashtra",
      "NAVJEEVAN CO-EDUCATION ELEMENTARY TEACHERS TRAINING COLLEGE, Rajasthan",
      "NAVJEEVAN EDU. SOCIETYS COLLEGE OF EDUCATION & RESEARCH, Maharashtra",
      "Navjeevan Education Society's Polytechnic, Maharashtra",
      "NAVJEEVAN INSTITUTE OF MANAGEMENT, NASHIK, Maharashtra",
      "Navjeevan Law College, NASHIK, Maharashtra",
      "Navjeevan Nursing School,Gadchiroli, Maharashtra",
      "Navjeevan School Of Nursing, Darjeeling, West Bengal",
      "Navjeevan School Of Nursing,Latur, Maharashtra",
      "NAVJEEVAN SHIKSHAN SANSTHAS COLLEGE OF PHYSICAL EDUCATION, Maharashtra",
      "Navjeevan Training Institute, ,Sikar, Rajasthan",
      "Navjivan Arts and Commerce College, Gujarat",
      "Navjivan Hospital , Palmau, Jharkhand",
      "Navjivan School Of Nursing,Thane, Maharashtra",
      "Navjivan Science College, Gujarat",
      "Navjivini School of Special Education for Mentally Retarded Children, PATIALA, Punjab",
      "Navjyothi Trust Institute of Mental Retardationl, CHENNAI, Tamil Nadu",
      "NAVJYOTI SHIKSAHK PRASHIKSAHN MAHAVIDYALAYA, Rajasthan",
      "NAVJYOTI TEACHER TRAINING COLLEGE, Rajasthan",
      "NAVODAYA COLLEGE OF EDUCATION, Karnataka",
      "NAVODAYA COLLEGE OF EDUCATION, Karnataka",
      "Navodaya College Of Nursing, Raichur, Karnataka",
      "Navodaya College Of Nursing,Mahaboobnagar., Andhra Pradesh",
      "Navodaya College Of Nursing, Raichur, Karnataka",
      "NAVODAYA D.ED COLLEGE, Karnataka",
      "Navodaya Degree College, Mahabubnagar, Andhra Pradesh",
      "Navodaya Dental College , Raichur, Karnataka",
      "Navodaya Education Trust N.E.T. Pharmacy College , RAICHUR, Karnataka",
      "Navodaya Education Trusts N.E.T., Pharmacy College , Raichur, Karnataka",
      "NAVODAYA GIRLS COLLEGE TEACHERS TRAINING COLLEGE, Rajasthan",
      "Navodaya Medical College, Raichur, Karnataka",
      "Navodaya School Of Nursing , Bangalore, Karnataka",
      "Navodaya School Of Nursing , Raichur, Karnataka",
      "Navrachana University, Gujarat",
      "NAVRANG SHIKSHAK PRASHIKSHAN MAHA VIDYALAYA, Rajasthan",
      "NAVSAHAYADRI CHARITABLE TRUST COLLEGE OF EDUCATION, Maharashtra",
      "Navsahyadri Education Society, Maharashtra",
      "Navsarjan School Of Technology, Gujarat",
      "Navyug Arts and Commerce College, Madhya Pradesh",
      "Navyug Arts College, Gujarat",
      "NAVYUG COLLEGE, Madhya Pradesh",
      "NAVYUG COLLEGE FOR EDUCATION, Haryana",
      "Navyug Commerce College, Gujarat",
      "NAVYUG KANYA MAHAVIDHYALAYA, Uttar Pradesh",
      "Navyug Kanya Vidyalaya Degree College, Uttar Pradesh",
      "Navyug Law College, SURAT, Gujarat",
      "Navyug Mahavidyalaya, Uttar Pradesh",
      "NAVYUG MAHAVIDYALAYA, Uttar Pradesh",
      "NAVYUG MAHILA SIKSHA PRASHIKSHAN MAHAVIDYALAYA, Uttar Pradesh",
      "NAVYUG MANAVIDYALAYA, Uttar Pradesh",
      "Navyug Science College, Gujarat",
      "NAVYUG TEACHER TRAINING COLLEGE, Haryana",
      "NAVYUG TEACHER TRAINING COLLEGE, Haryana",
      "Navyug Vidyapeeth Trust College of Pharmacy , RAIGAD, Maharashtra",
      "Nawada Vidhi Mahavidyalaya, Bihar",
      "NAYAB ABBASI GIRLS DEGREE COLLEGE, Uttar Pradesh",
      "NAYAB ABBASI GIRLS DEGREE COLLEGE, Uttar Pradesh",
      "NAYAB ABBASI GIRLS DEGREE COLLEGE, Uttar Pradesh",
      "Nayagarh College, Orissa",
      "Nayagi Institute Of Nursing ,Vellore, Tamil Nadu",
      "NAYALA COLLEGE OF EDUCATION INSTITUTION, Karnataka",
      "Nazarene Nurses Training College , Washim, Maharashtra",
      "Nazarene Nurses Training College ,Washim, Maharashtra",
      "Nazareth College Arts Science, CHENNAI, Tamil Nadu",
      "NAZARETH COLLEGE OF EDUCATION FOR WOMEN, Tamil Nadu",
      "Nazareth Hospital Mokama , Patna, Bihar",
      "Nazareth Hospital School Of Nursing, ,Allahabad, Uttar Pradesh",
      "Nazareth Margoschin College, TUTICORIN, Tamil Nadu",
      "Nazira College, Assam",
      "Nazrul Centenary Polytechnic, West Bengal",
      "Nazrul Cetenary Polytechnic, West Bengal",
      "NBKR Institute Of Science And Technology, NELLORE, Andhra Pradesh",
      "NBN Sinhgad Technical Institutes Campus , Ambegaon, Maharashtra",
      "NBT&amp; NV C College, Andhra Pradesh",
      "NCR Business School of Excellence, Uttar Pradesh",
      "NCR Polytechnic, Haryana",
      "NCRD - Sterling Institute of Management, Maharashtra",
      "NCRDS STERLING COLLEGE OF EDUCATION, Maharashtra",
      "NDM COLLEGE OF EDUCATION, Tamil Nadu",
      "NDMVP Samaj College of Engineering, NASHIK, Maharashtra",
      "Ndmvp Samaj Institute Of Management Research And Technology, Maharashtra",
      "NDMVPS Samaj's Rajarshee Shahu Maharaj Polytechnic, Nashik, Maharashtra",
      "Neela Shaila Mahavidyalaya, Orissa",
      "Neelachal Institute Of Medical Sciences,Bhubaneswar, Orissa",
      "Neelachal Polytechnic, Orissa",
      "Neelachal School Of Nursing, Khurda, Orissa",
      "Neelagiri Degree College, Nalgonda, Andhra Pradesh",
      "NEELAM TEACHER TRAINING COLLEGE, Himachal Pradesh",
      "NEELAM TEACHER TRAINING COLLEGE, Rajasthan",
      "Neelavayni Krishna School Of Nursing , Rampur, Uttar Pradesh",
      "Neelkanth Group of Institutions, Uttar Pradesh",
      "Neelkanth Law College, JABALPUR, Madhya Pradesh",
      "NEELKANTH TEACHERS TRAINING COLLEGE, Rajasthan",
      "NEELKANTH VIDYAPEETH, Uttar Pradesh",
      "Neethipudi Ganapathi Rao (Ngr) Degree College, EAST GODAVARI, Andhra Pradesh",
      "NEF Law College, GUWAHATI, Assam",
      "Nehru Arts & Commerce College, Maharashtra",
      "Nehru Arts & Science College, KASARAGOD, Kerala",
      "Nehru Arts And Science College, COIMBATORE, Tamil Nadu",
      "Nehru College, Bihar",
      "Nehru College, Assam",
      "Nehru College, Assam",
      "Nehru College Assam, Assam",
      "Nehru College Of Arts & Science, TIRUPUR, Tamil Nadu",
      "Nehru College of Engineering and Research Centre, TRICHUR, Kerala",
      "Nehru College Of Nursing, Thiruchirappali, Tamil Nadu",
      "NEHRU D.ED COLLEGE, Karnataka",
      "Nehru Degree (PG) College, Uttar Pradesh",
      "NEHRU EDUCATION SC/ST ASSOCIATION, Karnataka",
      "Nehru Government College, Madhya Pradesh",
      "Nehru Government P. G. College, Madhya Pradesh",
      "Nehru Gram Bharati University, Uttar Pradesh",
      "Nehru Gram Bharati Vishwavidyalaya, Uttar Pradesh",
      "Nehru Homoeopathic Medical College and Hospital, Delhi",
      "Nehru Institute of Engineering & Technology, Coimbatore, Tamil Nadu",
      "NEHRU INSTITUTE OF IT AND MANAGEMENT, Coimbatore, Tamil Nadu",
      "Nehru Institute of Technology, Tamil Nadu",
      "Nehru Mahavidyalaya, Uttar Pradesh",
      "Nehru Memorial College, Trichy, Tamil Nadu",
      "Nehru Memorial College of Pharmacy, Hanumangarh, Rajasthan",
      "Nehru Memorial Government College, Jogipet, Andhra Pradesh",
      "Nehru Memorial Law College, Hanumangarh, Rajasthan",
      "Nehru Memorial PG College, Rajasthan",
      "Nehru Memorial Pg College, Rajasthan",
      "Nehru Memorial PG College, Punjab",
      "Nehru Memorial Shiv Narain Das P.G. College, Uttar Pradesh",
      "NEHRU MEMORIAL TEACHER TRAINING COLLEGE, Karnataka",
      "Nehru Nursing College, Tirunelveli, Tamil Nadu",
      "Nehru Nursing College, Vallioor, Tamil Nadu",
      "Nehru Samarak College, Rewa, Madhya Pradesh",
      "Nehru Samarak College, Madhya Pradesh",
      "Nehru Samarak P.G. College, Rewa, Madhya Pradesh",
      "NEHRU SHIKSHA MAHAVIDYALAYA, Rajasthan",
      "NEHRU SHIKSHA MAHAVIDYALAYA, Rajasthan",
      "Nehru Smaraka Vidya KendraTrust, Sri Venkateshwara College of Pharmacy, Bangalore, Karnataka",
      "NEHRU TEACHER TRAINING COLLEGE, Pondicherry, Pondicherry",
      "Neki Ram Nursing School,Rohtak, Rohtak, Haryana",
      "Nellore School Of Nursing , Nellore, NELLORE, Andhra Pradesh",
      "Nemgondadad Patil Night College Ofarts And Commerce, Maharashtra",
      "Neotia Academy Of Nursing , Kolkata, KOLKATA, West Bengal",
      "Neotia Academy Of Nursing,Kolkata, West Bengal",
      "Nesamony Memorial Christain College, KANYAKUMARI, Tamil Nadu",
      "Ness Wadia College of Commerce, Maharashtra",
      "Neta Ji Subhash Nursing Institution , Kangra, KANGRA, Himachal Pradesh",
      "Netai Charan Chakravarty Homoeopathic Medical College and Hospital, HOWRAH, West Bengal",
      "Netaji Anm Training Centre , Khurda, KHURTA, Orissa",
      "Netaji Degree College, HYDERABAD, Andhra Pradesh",
      "Netaji Institute Of Engineering and Technology, Andhra Pradesh",
      "Netaji Mahavidyalaya, West Bengal",
      "NETAJI MEMORIAL PRE PRIMARY TEACHERS TRAINING INSTITUTE, Kerala",
      "Netaji school and college of nursing, Orissa",
      "Netaji Subash Chandra Bose Government Medical College, Madhya Pradesh",
      "Netaji Subash Chandra Bose Medical College, Jabalpur, JABALPUR, Madhya Pradesh",
      "Netaji Subash Chandra Mahavidyalaya, West Bengal",
      "Netaji Subash Institute of Technology, DELHI, Delhi",
      "Netaji Subash Nursing College,Kangra, KANGRA, Himachal Pradesh",
      "Netaji Subhas Ashram Mahavidyalaya, West Bengal",
      "Netaji Subhas Chandra Bose Primary Teacher's Training Institute, West Bengal",
      "Netaji Subhas Institute of Business Management, Jharkhand",
      "Netaji Subhas Institute of Technology, HAJIPUR, Bihar",
      "Netaji Subhas National Instt. of Sports Medicine, Patiala, PATIALA, Punjab",
      "Netaji Subhas Open University, KOLKATA, West Bengal",
      "Netaji Subhas Primary Teacher's Training Institute, West Bengal",
      "Netaji Subhas Sansitorium Hospital School Of Nursing , Nadia, NADIA, West Bengal",
      "Netaji Subhash Bose College, Orissa",
      "NETAJI SUBHASH CHANDER BOSE TEACHER TRAINING COLLEGE, Haryana",
      "Netaji Subhash Chandra Bose Arts Science & Commerce College, Maharashtra",
      "Netaji Subhash Chandra Bose College, Orissa",
      "Netaji Subhash Chandra Bose College, Madhya Pradesh",
      "NETAJI SUBHASH CHANDRA BOSE COLLEGE OF PHYSICAL EDUCATION, Maharashtra",
      "Netaji Subhash Chandra Bose GovernmentGirls Deg.College, Uttar Pradesh",
      "Netaji Subhash Chandra Bose Govt.Girls Deg.College, Uttar Pradesh",
      "Netaji Subhash Engineering College, West Bengal",
      "NETAJI SUBHASH ENGINEERING COLLEGE, KOLKATA, West Bengal",
      "NETAJI SUBHASH INSTITUTE OF BUSINESS MANAGEMENT, Jharkhand",
      "Netaji Subhash Mahavidyalaya, Tripura",
      "Netaji Subhash Nursing & Para Medical Institute , Kangra, Himachal Pradesh",
      "NETAJI SUBHASH PHYSICAL EDUCATION COLLEGE, Chhattisgarh",
      "NETAJI SUBHASH TEACHER TRAINING COLLEGE, Haryana",
      "Netajinagar College For Women, West Bengal",
      "Netajinagar Day College, West Bengal",
      "NETHAJI COLLEGE OF EDUCATION, Karnataka",
      "Nethaji Institute Of Nursing Sciences ,Mangalore, Karnataka",
      "Nethaji Nursing College,Mangalore, Karnataka",
      "Nethaji School Of Nursing , Mangalore, Karnataka",
      "Nethaji Subash Chandra Bose College, TIRUVARUR, Tamil Nadu",
      "Nethaji Subash Chandra Bose Polytechnic College, Tamil Nadu",
      "NETHAJI TEACHER EDUCATION INSTITUTION, Karnataka",
      "NETHAJI TEACHER TRAINING INSTITUTE, Karnataka",
      "Nethra Homoeopathic Medical College & Hospital, COIMBATORE, Tamil Nadu",
      "NEVILLE WADIA INSTITUTE OF MANAGEMENT STUDIES & RESEARCH, Maharashtra",
      "Nevjabai Hitkarini College, Maharashtra",
      "NEW ADARSH INSTITUTE OF EDUCATION, Uttar Pradesh",
      "NEW ADARSH MAHILA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, Rajasthan",
      "New Adarsha Degree College, KANDUKUR, Andhra Pradesh",
      "New Alipore College, West Bengal",
      "NEW ARTS commerce & Science COLLEGE, Maharashtra",
      "New Arts Science & Commerce College, Maharashtra",
      "New Arts Science & Commerce College, Maharashtra",
      "New Aurobindo Degree College, NALGONDA, Andhra Pradesh",
      "New Cape Polytechnic College, Tamil Nadu",
      "New City College Of Nursing,Udupi, Karnataka",
      "New City Hospital School Of Nursing , Udupi, Karnataka",
      "New Civil Hospital, School Of Nursing, Ahmedabad, Gujarat",
      "New College, Tamil Nadu",
      "NEW COLLEGE, Kerala",
      "NEW DELHI INSTITUTE OF MANAGEMENT, DELHI, Delhi",
      "New Education Society Science College, Madhya Pradesh",
      "NEW ERA COLLEGE OF EDUCATION, Uttar Pradesh",
      "New Era College Of Nursing,Indore, Madhya Pradesh",
      "New Era College of Science and Technology Ghaziabad, Uttar Pradesh",
      "New Generation College For Women, KHAMMAM, Andhra Pradesh",
      "New Gobind School Of Nursing , Amritsar, Punjab",
      "New Government Degree College, Madhya Pradesh",
      "New Government Degree College, HYDERABAD, Andhra Pradesh",
      "New Govt.Polytechnic, Patna, Bihar",
      "NEW HORIZON COLLEGE O EDUCATION, Karnataka",
      "New Horizon College of Education, Karnataka",
      "New Horizon College of Engineering, Karnataka",
      "New Horizon Dental College & Research Instiute , Bilaspur, Chhattisgarh",
      "NEW HORIZON LEADERSHIP INSTITUTE, BANGALORE, Karnataka",
      "NEW HORIZON TEACHERS TRAINING INSTITUTE, Karnataka",
      "NEW IDEAL COLLEGE OF EDUCATION, Tamil Nadu",
      "New India College of Engineering & Technology, MEDCHAL, Andhra Pradesh",
      "New Indian Poly. College, Rajasthan",
      "NEW INDIAN TEACHER TRAINING COLLEGE, Rajasthan",
      "NEW KALPANA CHAWLA TEACHER TRAINING COLLEGE, Haryana",
      "NEW KANSHI D.ED TRAINING SCHOOL, Haryana",
      "New Law Academy, Maharashtra",
      "New Law College, AHMEDNAGAR, Maharashtra",
      "New Law College Bharathi Vidyapeeths Law College, KOLHAPUR, Maharashtra",
      "New Law College, Mumbai, MUMBAI, Maharashtra",
      "New Loyola Model Degree College, HYDERABAD, Andhra Pradesh",
      "New Malwa Institute Of Nursing , Faridkot, FARIDKOT, Punjab",
      "New Mangalore College Of Nursing,Mangalore, MANGALORE, Karnataka",
      "NEW MAULANA AZAD EDUCATION SOCIETY B.ED. COLLEGE, Maharashtra",
      "NEW MILLENNIUM COLLEGE OF EDUCATION, Tamil Nadu",
      "New Muppana Venkata Rao Degree College, VISAKHAPATNAM, Andhra Pradesh",
      "New Navodaya Institute Of Nursing , Mandya, MANDYA, Karnataka",
      "New Navodaya Institute Of Nursing,Mandya, MANDYA, Karnataka",
      "New Noble Degree College, RANGAREDDY, Andhra Pradesh",
      "New Novadaya Institute Of Nursing , Mandya, MANDYA, Karnataka",
      "New Nursing School,Beed, BEED, Maharashtra",
      "New Prince Shri Bhavani Arts And Science College, CHENNAI, Tamil Nadu",
      "New Prince Shri Bhavani College of Engineering and Technology, Tamil Nadu",
      "New RABalika P.G. Mahavidyalaya, Rajasthan",
      "NEW RAJASTHAN TEACHERS TRAINING COLLEGE, Rajasthan",
      "NEW RIVER ELEMENTARY TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "New Sarvodaya School Of Nursing , Bangalore, BANGALORE, Karnataka",
      "New Science College, HYDERABAD, Andhra Pradesh",
      "New Science Degree College, Bhupal Palli, BHOOPALPALLY, Andhra Pradesh",
      "New Science Pg College, HANAMAKONDA, Andhra Pradesh",
      "New Siddhartha Degree College For Women, HYDERABAD, Andhra Pradesh",
      "New Silver Jubilee Degree College, RANGAREDDY, Andhra Pradesh",
      "New Sri Shanthini College Of Nursing,Bangalore, BANGALORE, Karnataka",
      "New Sri Shantini College Of Nursing , Bangalore North, BANGALORE, Karnataka",
      "NEW VISION GLOBAL SCHOOL OF BUSINESS, AMBALA, Haryana",
      "New Vision Nursing School,Latur, LATUR, Maharashtra",
      "NEWAJ SINGH MAHAVIDYALAYA, Uttar Pradesh",
      "Newman College, Kerala",
      "News Scholars Degree College, RANGAREDDY, Andhra Pradesh",
      "NEWTON COLLEGE OF EDUCATION, Tamil Nadu",
      "Newton Institute of Engineering,, Andhra Pradesh",
      "NEYVELI TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Nezamia College of Education, Bihar",
      "NG. College, Manipur",
      "NGF College of Engineering & Technology, Haryana",
      "NGPM TEACHER TRAINING INSTITUTE, Kerala",
      "Niali College, Orissa",
      "NIBEDITA POLYTECHNIC, West Bengal",
      "NIC TEACHER TRAINING COLLEGE, Haryana",
      "NICE MANAGEMENT COLLEGE, MEERUT, Uttar Pradesh",
      "NIDA COLLEGE OF PHYSICAL EDUCATION, Uttar Pradesh",
      "NIDA INSTITUTE OF KARNATAKA EDUCATION TRUST, Karnataka",
      "Nida School Of Nursing , Bidar, BIDAR, Karnataka",
      "Nidhi College Of Nursing,Chickmagalur, CHIKMAGALUR, Karnataka",
      "NIE Insititute of Technology, Mysore., Karnataka",
      "Nift Tea College Knitwear Fashion, TIRUPUR, Tamil Nadu",
      "Nigama Engineering College, Andhra Pradesh",
      "Night College of Arts and Commerce, Maharashtra",
      "Night College Of Arts And Commerce, Maharashtra",
      "Nightangle College Of Nursing , Trivandrum, TRIVANDRUM, Kerala",
      "Nightangle School Of Nursing , Chikmagalur, CHIKMAGALUR, Karnataka",
      "Nightingal Nursing Institute , Imphal, IMPHAL, Manipur",
      "Nightingale College Of Nursing , Bangalore, BANGALORE, Karnataka",
      "Nightingale College Of Nursing , Ludhiana, Punjab",
      "Nightingale Institute Of Nursing , Gulbarga, Karnataka",
      "Nightingale Institute Of Nursing , Noida, Uttar Pradesh",
      "Nightingale Institute Of Nursing Education , Coimbatore, Tamil Nadu",
      "Nightingale Institute of Technology, Tamil Nadu",
      "NIGHTINGALE KANNADA D COLLEGE, Karnataka",
      "Nightingale Nursing Institute , Ludhiana, Punjab",
      "Nightingale Nursing Institute ,ImphalEast, Manipur",
      "Nightingale Nursing Institute,Imphal East, Manipur",
      "Nightingale School Of Diploma In General Nursing & Midwifery, Bidar, Karnataka",
      "Nightingale School Of Nursing , Bangalore, Karnataka",
      "Nightingale School Of Nursing , Mysore, Karnataka",
      "Nightingle College Of Nursing,Bundi, Rajasthan",
      "NIHAL SINGH D.ED COLLEGE, Haryana",
      "NIILM CENTER FOR MANAGEMENT STUDIES, NEW DELHI, Delhi",
      "NIILM University, Haryana",
      "Niims College Of Pharmacy , Jaipur, Rajasthan",
      "NIIS Institute of Business Administration, Bhubaneswar, Orissa",
      "NIIT University, Rajasthan",
      "NIKALAS MAHILA MAHAVIDDYALAYA, Maharashtra",
      "Nikam Institute Of Technology,Dhule, Maharashtra",
      "Nikhil Banga Sikshan Mahavidyalaya, West Bengal",
      "Nikhil Banga Sikshan Mahavidyalaya, West Bengal",
      "Nikhil Institute of Engineering & Management, Uttar Pradesh",
      "Nil Ratan Sircar Medical College Hospital , Sch. Of Nsg., Kolkata, West Bengal",
      "Nilagiri College, Orissa",
      "Nilai Educational Trust, Jharkhand",
      "Nilakantheswar Degree Mahavidyalaya, Orissa",
      "Nilamadhab Mahavidyalaya, Orissa",
      "Nilamani Mahavidyalaya, Orissa",
      "NILGIRI DIOCESAN SOCIETY ST.JOSEPH COLLEGE OF EDUCATION, Tamil Nadu",
      "Nilratan Circar Medical College, West Bengal",
      "Nilratan Sarkar Medical College And Hospital , Kolkatta, Kolkata, West Bengal",
      "Nilratan Sircar Medical College, Calcutta, West Bengal",
      "Nimapara College, Orissa",
      "NIMAS Group, West Bengal",
      "NIMBARK SANSKRIT S.T.C., Rajasthan",
      "Nimbark Teacher Training Mahavidyalaya, Rajasthan",
      "NIMBUS ACADEMY OF MANAGEMENT, Uttaranchal",
      "Nimra College of Business Management, Andhra Pradesh",
      "NIMRA College of Engineering & Technology., Vijayawada, Andhra Pradesh",
      "Nimra Institute of Engineering & Technology, Andhra Pradesh",
      "Nimra Institute of Science & Technology, Andhra Pradesh",
      "Nimra Women''s College of Engineering, Andhra Pradesh",
      "NIMS Dental College , Jaipur, Rajasthan",
      "NIMS School of Hotel Management, West Bengal",
      "NIMS University, Jaipur, Rajasthan",
      "NIMS University, Rajasthan",
      "NIMT Institute of Engineering & Technology, Ajmer, Rajasthan",
      "NIMT MAHILA TEACHER TRAINING COLLEGE, Rajasthan",
      "NIMT Mahila Technical College for Hotel Management and Catering Technology, Uttar Pradesh",
      "NINAIDEVI SHIKSHAN PRASARAK MANDAL, Maharashtra",
      "NINGOJI EDUCATION & RURAL DEVELOPMENT TRUST, Karnataka",
      "NIOSe Group of Education, West Bengal",
      "NIPS School of Hotel Management, West Bengal",
      "Niraj College Of Professional Studies, Begumpet, Andhra Pradesh",
      "NIRAMALA MIMORIAL FOUNDATION, Maharashtra",
      "NIRANJAN INSTITUTE OF EDUCATION TECHNOLOGY, Uttar Pradesh",
      "NIRMA INSTITUTE OF MANAGEMENT, Ahmedabad, Gujarat",
      "Nirma institute of technology ,ahmedabad, Ahmedabad, Gujarat",
      "Nirma University of Science and Technology, AHMEDABAD, Gujarat",
      "Nirmal Engineering College, MEDAK, Andhra Pradesh",
      "NIRMAL GANGA INSTITUTE OF EDUCATION, Uttar Pradesh",
      "Nirmal Haloi College, BARPETA, Assam",
      "Nirmal Krida and Samaj Prabodhan Trust's Arts Science and Commerce, Maharashtra",
      "NIRMAL TEACHER TRAINING COLLEGE, Rajasthan",
      "Nirmala College, ERNAKULAM, Kerala",
      "Nirmala College for Women, COIMBATORE, Tamil Nadu",
      "Nirmala College Jharkhand, Jharkhand",
      "Nirmala College Of Nursing , Calicut, CALICUT, Kerala",
      "Nirmala College Of Nursing , Ernakulam, ERNAKULAM, Kerala",
      "Nirmala College Of Nursing,Ananthpur, ANANTAPUR, Andhra Pradesh",
      "Nirmala College Of Nursing,Shimoga, SHIMOGA, Karnataka",
      "Nirmala College Of Pharmacy, Andhra Pradesh",
      "Nirmala College of Pharmacy , Guntur, GUNTUR, Andhra Pradesh",
      "Nirmala College of Pharmacy , Kadapa, CUDDAPAH, Andhra Pradesh",
      "Nirmala Gajwani School Of Nursing , Kutch, Gujarat",
      "Nirmala Hospital,Calicut",
      "Nirmala Institute Education, Goa",
      "Nirmala Institute of Education, Goa",
      "Nirmala Medical Centre, School Of Nursing,Ernakulum, ERNAKULAM, Kerala",
      "Nirmala Ramana Nursing School , Kodagu, Karnataka",
      "Nirmala Sadan Training College for Special Education, Kerala",
      "Nirmala School Of Nursing , Anantapur, ANANTAPUR, Andhra Pradesh",
      "Nirmala School Of Nursing , Bangalore Rural, BANGALORE, Karnataka",
      "Nirmala School Of Nursing , Shimoga, SHIMOGA, Karnataka",
      "NIRMALA TRAINING COLLEGE, Kerala",
      "Nirmalagiri College, KANNUR, Kerala",
      "Nirmali College, Bihar",
      "Nirogdham Anm Training Centre,Jhalawar, JHALAWAR, Rajasthan",
      "Nirogdham School Of Nursing, Jhalawar, Rajasthan",
      "Nirsu Narain Mahavidyalaya, Uttar Pradesh",
      "Nisarga College Of Nursing , Hassan, Karnataka",
      "NISARGA INSTITUTE OF EDUCATION, Karnataka",
      "Nisarga School Of Nursing , Hassan, Karnataka",
      "Nishad College Of Nursing & Allied Sciences , Satna, Madhya Pradesh",
      "Nishat Hospitals & Institute Of Paramedical Sciences , School Of Nursing,Lucknow, Uttar Pradesh",
      "Nishat Hospitals & Institute Of Paramedical Sciences,Lucknow, Uttar Pradesh",
      "Nishat Hospitals & Institute Of Paramedical Sciences,Lucknow, Uttar Pradesh",
      "Nishita Degree College, Andhra Pradesh",
      "Nishitha College of Engineering & Technology, Andhra Pradesh",
      "Nishitha Degree College, Andhra Pradesh",
      "Nistarini College, West Bengal",
      "Nit Polytechnic, Maharashtra",
      "Niteshwar Mahavidyalaya, Bihar",
      "NITISHREE DEGREE COLLEGE, Uttar Pradesh",
      "NITS Polytechnic,Jammu, Jammu and Kashmir",
      "NITTE Education Trust, Karnataka",
      "Nitte Mahalinga Adyanthaya, Karnataka",
      "Nitte Meenakshi Institute of Technology,, Karnataka",
      "NITTE University, Karnataka",
      "Nitte Usha Institute Of Nursing Sciences , Deralakatte, Karnataka",
      "Nitte Usha Instt. Of Nursing Sciences, School Of Nursing , Deralakatte, Karnataka",
      "Nitte Usha Instt. Of Nursing Sciences,Deralakatte, Karnataka",
      "Nittur Education Society Polytechnic, Karnataka",
      "NITYA NAND MAHAVIDYALAYA, Uttar Pradesh",
      "Nityanand School Of Nursing , Dhar, Madhya Pradesh",
      "Nityaseva Hospital Nursing School,Ahmednagar, Maharashtra",
      "NIV College Of Distance Education, Jharkhand",
      "Nivedita Community Care Centre , Hooghly, West Bengal",
      "Nivedita Polytechnic, Karnataka",
      "Nivedita School Of Nursing, GULBARGA, Karnataka",
      "Niveditha College of Pharmacy, KOLAR, Karnataka",
      "Niveditha Degree College, KOTHAKOTA, Andhra Pradesh",
      "Nizam College, HYDERABAD, Andhra Pradesh",
      "NIZAM INSTITUTE OF BUSINESS MGT, Andhra Pradesh",
      "Nizam Institute of Engineering & Technology, Andhra Pradesh",
      "Nizam'S Institute Of Medical Sciences, HYDERABAD, Andhra Pradesh",
      "Nizamabad Law College, NIZAMABAD, Andhra Pradesh",
      "Nizams Institute Of Medical Sciences, HYDERABAD, Andhra Pradesh",
      "Nizams Institute of Medical Sciences, HYDERABAD, Andhra Pradesh",
      "NKBR College of Pharmacy & Research Center, MEERUT, Uttar Pradesh",
      "NM Institute of Engineering and Technology, BHUBANESWAR, Orissa",
      "NMAM Institute of Technology, UDUPI, Karnataka",
      "Noble College, Madhya Pradesh",
      "Noble College, Andhra Pradesh",
      "Noble College Machilipatnam, MACHILIPATNAM, Andhra Pradesh",
      "Noble College of Commerce and Information Technology, Maharashtra",
      "NOBLE COLLEGE OF COMPUTER SCIENCE, MANDAL, Andhra Pradesh",
      "Noble College of Engineering & Technology for Women, Andhra Pradesh",
      "NOBLE COLLEGE OF PROFESSIONAL STUDIES, Uttar Pradesh",
      "Noble Degree College, HYDERABAD, Andhra Pradesh",
      "Noble Group of Institutions, Gujarat",
      "Noble Institute of Science & Technology, VISAKHAPATNAM, Andhra Pradesh",
      "Noble Nursing School, JUNAGADH, Gujarat",
      "NOBLE PG COLLEGE, Andhra Pradesh",
      "Noble School Of Nursing, HYDERABAD, Andhra Pradesh",
      "NOIDA COLLEGE OF EDUCATION, Uttar Pradesh",
      "Noida College Of Physical Eduation, Uttar Pradesh",
      "NOIDA COLLEGE OF PHYSICAL EDUCATION, Uttar Pradesh",
      "NOIDA COLLEGE OF PHYSICAL EDUCATION, Uttar Pradesh",
      "NOIDA INSTITUTE OF EDUCATION AND TECHNOLOGY, Uttar Pradesh",
      "Noida Institute of Engineering and Technology, NOIDA, Uttar Pradesh",
      "Noida International University, Uttar Pradesh",
      "Nonoi College Nagaon, NAGAON, Assam",
      "NOOR COLLEGE OF EDUCATION, Karnataka",
      "Noor College of Engineering and Technology, MAHABUBNAGAR, Andhra Pradesh",
      "Noor College Of Nursing , Bangalore, BANGALORE, Karnataka",
      "Noor Law College, BIDAR, Karnataka",
      "Noor School Of Nursing , Bangalore, BANGALORE, Karnataka",
      "Noor School Of Nursing , Bidar, BIDAR, Karnataka",
      "NOORIE COLLEGE OF EDUCATION, Karnataka",
      "Noorie College Of Nursing , Kolar, KOLAR, Karnataka",
      "Noorie School Of Nursing,Kolar, KOLAR, Karnataka",
      "Noorl Islam Arts And Science College, KANYAKUMARI, Tamil Nadu",
      "Noorul Islam College of Dental Sciences , NEYYATTINKARA, TRIVANDRUM, Kerala",
      "Noorul Islam College of Engineering, Tamil Nadu",
      "Noorul Islam Polytechnic College, KANYAKUMARI, Tamil Nadu",
      "Noorul Islam University, Tamil Nadu",
      "Nootan G N M Nursing School , Mehsana, MEHSANA, Gujarat",
      "NOOTAN SARVA VIDYALAYA KELAVANI MANDAL, SANCHALIT MBA COLLEGE, MEHSANA, Gujarat",
      "Nootan School Of Nursing,Raigad, RAIGAD, Maharashtra",
      "Nopany Institute of Healthcare Studies, West Bengal",
      "NORANG RAM DAYANAND DHUKIA COLLEGE OF MANAGEMENT, Rajasthan",
      "Norang Ram Dayanand Dhukia Nursing College ,Jhun Jhunu, Rajasthan",
      "Norangram Dayanad Dhukia Nursing School,Jhunjhunu, Rajasthan",
      "NORANGRAM DAYANAND DHUKHIA TEACHERS TRAINING COLLEGE, Rajasthan",
      "Norangram Dayanand Dhukia Nursing College,Jhunjhunu, Rajasthan",
      "Normal School, Assam",
      "North Bank College, Assam",
      "North Bengal Dental College , Darjeeling, West Bengal",
      "North Bengal Handicapped Rehabilitation Society, SILIGURI, West Bengal",
      "North Bengal University, West Bengal",
      "North Bengal University Law College, DARJEELING, West Bengal",
      "North Bengal Universityity College, , West Bengal",
      "North Calcutta Polytechnic, West Bengal",
      "North East Homoeopathic Medical College, ITANAGAR, Arunachal Pradesh",
      "North East Paramedical And Nursing Institute , Guwahati, Assam",
      "North Eastern Hill University, Meghalaya",
      "North Eastern Indira Gandhi Regional Instt Of Health & Med Sc, SHILLONG, Meghalaya",
      "North Eastern Indira Gandhi Regional Instt Of Health & Med Sc ,East Khasihills,, Meghalaya",
      "NORTH EASTERN REGIONAL INSTITUTE OF MANAGEMENT, GUWAHATI, Assam",
      "North Eastern Regional Institute of Management, Assam",
      "North Eastern Regional Institute of Science & Technology, ITANAGAR, Arunachal Pradesh",
      "North Eastern Regional Institute of Science & Technology, , Arunachal Pradesh",
      "North Eastern Regional Training Institute for the Mentally Handicapped, GUWAHATI, Assam",
      "North Gauhati College, GUWAHATI, Assam",
      "NORTH GUJARAT UNIVERSITY, Gujarat",
      "North India Institute of Technology, Najibabad, , Uttar Pradesh",
      "North Kamrup College, Assam",
      "NORTH KARNATAKA D ED COLLEGE, , Karnataka",
      "North Karnataka School Of Nursing , Bidar, BIDAR, Karnataka",
      "North Lakhimipur Law College, Assam",
      "North Lakhimpur College, Assam",
      "North Lakhimpur Law College, LAKHIMPUR, Assam",
      "North Maharashtra University, JALGAON, Maharashtra",
      "North Malda Teacher's Education College, West Bengal",
      "NORTH ORISSA SCHOOL OF COMMUNICATION & MANAGEMENT STUDIES, BARAPADA, Orissa",
      "North Orissa University, Orissa",
      "North West Institute Of Engineering And Technology, Punjab",
      "Northern India Engineering College, LUCKNOW, Uttar Pradesh",
      "Northern India Engineering College New Delhi, Delhi",
      "NORTHERN INST. FOR INTEGRATED LEARNING IN MANAGEMENT, DELHI, Delhi",
      "Northern Institute of Engineering Technical Campus, Alwar, Rajasthan",
      "NOTRE DAME JUNIOR COLLEGE OF EDUCATION, Karnataka",
      "Nova College of Business Management, Andhra Pradesh",
      "Nova College of Engineering & Technology, WEST GODAVARI, Andhra Pradesh",
      "Nova College of Engineering & Technology for Women, IBRAHIMPATNAM, Andhra Pradesh",
      "Nova College of Engineering & Technology., VIJAYAWADA, Andhra Pradesh",
      "Nova Degree College, Jangareddygudem, Andhra Pradesh",
      "Nova Institute Of Nursing & Paramedical Science,Lucknow, LUCKNOW, Uttar Pradesh",
      "Nova Institute Of Nursing & Paramedical Sciences , Lucknow, LUCKNOW, Uttar Pradesh",
      "Nova Pg College, Andhra Pradesh",
      "NOVA TEACHER TRAINING INSTITUTE ALFA EDUCATION TRUST, Tamil Nadu",
      "NOVEL INSTITUTE OF MANAGEMENT & RESEARCH, CHANDWAD, Maharashtra",
      "Novel Institute of Management Studies, Maharashtra",
      "Nowboicha College, Assam",
      "Nowgong College, NAGAON, Assam",
      "Nowgong Girls' College, Assam",
      "Nowgong Law College, NOWGONG, Assam",
      "Nowrangapur College, Orissa",
      "Nowrosjee Wadia College, Maharashtra",
      "NPR College Engineering Technology, Tamil Nadu",
      "NPR Polytechnic College, Tamil Nadu",
      "NREC COLLEGE, Uttar Pradesh",
      "Nri College Of Nursing , Guntur, GUNTUR, Andhra Pradesh",
      "NRI Institute of Information Science & Technology, BHOPAL, Madhya Pradesh",
      "NRI Institute of Medical Sciences, Andhra Pradesh",
      "NRI Institute of Pharmacy , Bhopal, BHOPAL, Madhya Pradesh",
      "NRI Institute of Technology & Management, GWALIOR, Madhya Pradesh",
      "NRJ TEACHER TRAINING COLLEGE, Haryana",
      "Nrupatanga Degree College, HYDERABAD, Andhra Pradesh",
      "Nrupatugna Arts & Commerce College, Karnataka",
      "NRUPATUNGA DEGREE PG COLLEGE, HYDERABAD, Andhra Pradesh",
      "Nrupur Institute Of Nursing Science & Research, Vadodara, VADODARA, Gujarat",
      "Nrupur Institute Of Nursing Science & Researchaiilsg , Vadodara, VADODARA, Gujarat",
      "Nrupur Institute Of Nursing Science And Research , Vadodara, VADODARA, Gujarat",
      "Nrupur Nursing Academy , Vadodara, VADODARA, Gujarat",
      "NSHM BUSINESS SCHOOL, West Bengal",
      "NSHM Knowledge Campus, West Bengal",
      "NSK TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "NSS College of Engineering, PALAKKAD, Kerala",
      "NSS TRAINING COLLEGE, Kerala",
      "NSS TRAINING COLLEGE, Kerala",
      "NSSR P.V.P College of Pharmacy , Beed, BEED, Maharashtra",
      "NSVK PRIMARTY TEACHER TRAINING INSTITUTE, Karnataka",
      "NSVK Sri Venkateshwara Dental College & Hospital , Bannerghatta, BANGALORE, Karnataka",
      "NTS COLLEGE OF EDUCATION, Pondicherry",
      "Ntsss Shri Shankar Arts & Commerce College, Karnataka",
      "Ntvss College Of Education, Maharashtra",
      "NURSERY TEACHERS TRAINING INSTITUTE, Delhi",
      "Nurses Training Centre, E S I Hospital , Kolkata, KOLKATA, West Bengal",
      "Nurses Training Institute , Sundergarh, Orissa",
      "Nurses Training Institute, Agartala, AGARTALA, Tripura",
      "Nursing College, Rajasthan",
      "Nursing Training Institute & Hospital , Jalandhar, JALANDHAR, Punjab",
      "Nursing Training School , Baghajatin State General Hospital , Kolkatta, KOLKATA, West Bengal",
      "Nursing Training School , E S I Hospital,Kolkata, KOLKATA, West Bengal",
      "Nursing Training School , Howrah, HOWRAH, West Bengal",
      "Nursing Training School , J N M Hospital , Nadia, NADIA, West Bengal",
      "Nursing Training School , Jhargram S D Hospital , Paschim Medinipore, West Bengal",
      "Nursing Training School , Kolkata, KOLKATA, West Bengal",
      "Nursing Training School , Kolkata, KOLKATA, West Bengal",
      "Nursing Training School , Midnapur, West Bengal",
      "Nursing Training School , Nadia, NADIA, West Bengal",
      "Nursing Training School , North 24 Praganas, NORTH 24 PARGANAS, West Bengal",
      "Nursing Training School , North Bengal Medical College And Hospital , Darjeeling, DARJEELING, West Bengal",
      "Nursing Training School , Rajganj District Hospital , Uttar Dinajpur, West Bengal",
      "Nursing Training School , S D Hospital , Burdwan, BURDWAN, West Bengal",
      "Nursing Training School , S D Hospital , Darjeeling, DARJEELING, West Bengal",
      "Nursing Training School , S D Hospital , Paschim Medinipur, West Bengal",
      "Nursing Training School , Sub Divisional Hospital , South 24 Parganas, SOUTH 24 PARGANAS, West Bengal",
      "Nursing Training School ,Balurghat, DINAJPUR, West Bengal",
      "Nursing Training School Anmr , Kolkata, KOLKATA, West Bengal",
      "Nursing Training School Anmr , Nadia, NADIA, West Bengal",
      "Nursing Training School Anmr , Nadia, NADIA, West Bengal",
      "Nursing Training School N T S , Cooch Behar, West Bengal",
      "Nursing Training School, , Kolkata, KOLKATA, West Bengal",
      "Nursing Training School, ,Howrah, HOWRAH, West Bengal",
      "Nursing Training School, Belley Sankarpur, West Bengal",
      "Nursing Training School, Burdwan, BURDWAN, West Bengal",
      "Nursing Training School, Malda, West Bengal",
      "Nursing Training School, Sadar Hospital, , Jalpaiguri, JALPAIGURI, West Bengal",
      "Nursing Training School,Murshidabad, MURSHIDABAD, West Bengal",
      "Nursing Trg. School. M J N Hospital , Cooch Behar, West Bengal",
      "Nusrathul Islam Arabic College, Kerala",
      "Nutan Adarsha Arts & Comm. & Smt. Maniben Hiralal Vagad College Of Science, Maharashtra",
      "Nutan Mahavidyalaya, Maharashtra",
      "Nutan Vidyalaya Artss.K.M. Science & Dr. P.P. Commerce College, Karnataka",
      "NUTAN VIDYALAYA SOCIETY, Karnataka",
      "Nutan Vidyalaya Society Polytechnic, Karnataka",
      "Nutan Vidyamandir Education Societys Mahila Mahavidyalaya, Maharashtra",
      "NUTANA COLLEGE OF EDUCATION, Karnataka",
      "Nuvapada Sri Balaji Mahavidyalaya, Orissa",
      "Nuzivid Polytechnic, Annavaram, Andhra Pradesh",
      "Nyaya Vidya Parishad Law College, Visakhapatnam, Andhra Pradesh",
      "Nyaya Vidya Peeth Law College, Visakhapatnam, Andhra Pradesh",
      "Nyruthi Institute of Technology and Science, Tamil Nadu",
      "Nyss Institute Of Management & Research, Maharashtra",
    ],
  },
];
