const KData = [
  {
    colleges: [
      "K A P Viswanathan Government Medical College, Trichy, TRICHY, Tamil Nadu",
      "K A R Polytechnic College, , Tamil Nadu",
      "K B College, , Jharkhand",
      "K B Jha College, , Bihar",
      "K B N College, VIJAYAWADA, Andhra Pradesh",
      "K B Patel College Of Nursing,koria, KORBA, Chhattisgarh",
      "K B Women'S College, , Jharkhand",
      "K C Das Commerce College, , Assam",
      "K C Seth Arts College, , Gujarat",
      "K C T C College, , Bihar",
      "K C T Polytechnic, Gulbarga, , Karnataka",
      "K D A Nursing College , Mumbai, MUMBAI, Maharashtra",
      "K D College Of Nursing , Hoshiarpur, HOSIARPUR, Punjab",
      "K D Gavit Nursing College, Nandurbar, NANDURBAR, Maharashtra",
      "K D Gavit Nursing School ,Nandurbar, NANDURBAR, Maharashtra",
      "K D S College, , Bihar",
      "K D School Of Nursing , Hoshiarpur, HOSIARPUR, Punjab",
      "K E M Hospital , Bombay, MUMBAI, Maharashtra",
      "K E T School Of Nursing , Bidar, BIDAR, Karnataka",
      "K G College Of Nursing , Coimbatore, COIMBATORE, Tamil Nadu",
      "K G Hospital, School Of Nursing,Angamaly, , Kerala",
      "K G N M Institute Of Nursing Education ,Jhalawar, JHALAWAR, Rajasthan",
      "K G R L Degree College, BHIMAVARAM, Andhra Pradesh",
      "K G R L Degree College, , Andhra Pradesh",
      "K G School Of Nursing, Coimbatore, COIMBATORE, Tamil Nadu",
      "K H Government Degree College, DHARMAVARAM, Andhra Pradesh",
      "K H Madhvani Arts And Commerce College, , Gujarat",
      "K I M S College Of Nursing , Nalgonda, NALGONDA, Andhra Pradesh",
      "K I M S College Of Nursing , Thiruvananthapuram, TRIVANDRUM, Kerala",
      "K I M S College Of Nursing,Eastgodavery, EAST GODAVARI, Andhra Pradesh",
      "K I M S College Of Nursing,segunderabad",
      "K I M S School Of Nursing,Trivandrum",
      "K J School Of Nursing,Chennai",
      "K J Somaiya College Of Engineering, Vidya-Nagar",
      "K J Somaiya College Of Nursing , Mumbai",
      "K J T E S Polytechnic, Mulbagal",
      "K K C College Of B Sc. Nursing,Chittoor",
      "K K C College Of Nursing , Chittoor",
      "K K E C S College Of Nursing,Bangalore",
      "K K Institute Of Nursing,Lucknow",
      "K K M College",
      "K K M College Jharkhand",
      "K K Memorial School Of Nursing & Research",
      "K K Parekh Commerce College",
      "K K Wagh College Of Nursing , Nashik",
      "K L E Polytechnic, Haveri",
      "K L E S 'S Arts Commerce College For Women",
      "K L E Society Polytechnic",
      "K L E Society Polytechnic, Bailhongal",
      "K L E Society Polytechnic, Chikodi",
      "K L E Society Polytechnic, Hubli",
      "K L E Societys Institute Of Nursing Sciences , Ankola",
      "K L E Societys Institute Of Nursing Sciences , Belgam",
      "K L E Societys Institute Of Nursing Sciences , Belgaum",
      "K L E Societys Institute Of Nursing Sciences , Hubli",
      "K L E Societys Institute Of Nursing Sciences , Uttar Kannada",
      "K L E Societys Institute Of Nursing Sciences , Dharwad",
      "K L E Societys Institute Of Nursing Sciences,Ankola",
      "K L E Societys S Nijalingappa College",
      "K L E Socitys Gogte Institute Technology",
      "K L E Socitys Gogte Institute Technology",
      "K L E Socitys Gogte Institute Technology",
      "K L E University Institute Of Nursing Sciences , Belgaum",
      "K L E Universitys Institute Of Nursing Sciences , Belgaum",
      "K L E Universitys Institute Of Nursing Sciences, Belgaum",
      "K L E's Gogte College of Commerce",
      "K L ES's Basavaprabhu Kore Arts Science Commerce College",
      "K L ES's GIB Arts Science & Commerce College",
      "K L ES's Gurusiddappa Kotambri Law College",
      "K L ES's Jagadguru Tontadarya College",
      "K L ES's SA Manvi Law College",
      "K L ES's SK Arts and HSK Science Institute",
      "K L ES's VS Bellubi Arts and Commerce College",
      "K L Mehta Dayanand College For Women",
      "K L S College",
      "K L S School Of Nursing , Hospet",
      "K L Sharma Genral Nursing School",
      "K L Sharma School Of Nursing , Sehore",
      "K L Shastri Smarak Nursing School,Lucknow",
      "K L TEACHER TRAINING COLLEGE",
      "K L University",
      "K L University Business School",
      "K M C College Of Nursing , Meerut",
      "K M C College Of Nursing , Trichy",
      "K M C College Of Nursing, Meerut",
      "K M C H College Of Nursing , Coimbatore",
      "K M C School Of Nursing , Tiruchirappalli",
      "K M C School Of Nursing, Meerut",
      "K M C School Of Nursing,Thiruvanathapuram",
      "K M C T College Of Nursing , Calicut",
      "K M C T School Of Nursing,Calicut",
      "K M College Education",
      "K M COLLEGE OF EDUCATION LAKSHMI EDUCATION AND RESEARCH",
      "K M D College",
      "K M E A Engineering College",
      "K M Government College",
      "K M H Memorial School Of Nursing,Malapuram",
      "K M J College Of Nursing,Bangalore",
      "K N Mahila College",
      "K N N College Of Nursing , Bangalore",
      "K N N School Of Nursing , Bangalore",
      "K N S School Of Nursing,Kottarakara",
      "K N SUBBARAJ MEMORIAL COLLEGE OF EDUCATION",
      "K N V V Sanghals Arts Commerce College",
      "K O College",
      "K O Shah Municipal Arts And Commerce College",
      "K P College",
      "K P M School Of Nursing,Malapuram",
      "K P R Institute of Engineering and Technology",
      "K P S M Anm Training School,Ramanagara",
      "K Pandyarajah Ballal Nursing Institute , Mangalore",
      "K Pandyarajah Ballal Nursing Institute , Ullal",
      "K R B Girl's College",
      "K R C E Socitys G G D Arts B M P Commerce S V S Science College",
      "K R College Of Nursing , Bangalore",
      "K R Desai Arts And Commerce College",
      "K R E College",
      "K R K Government Degree College",
      "K R M Muthiah College Arts And Science Chennai",
      "K R R Government Arts Science College",
      "K R S Institute Of Paramedical Sciences And Nursing,Gonda",
      "K R School Of Nursing , Bangalore",
      "K R School Of Nursing , Coimbatore",
      "K S College",
      "K S E R T College Education",
      "K S E R T College Education",
      "K S G M College",
      "K S Hegde Medical Academy, Mangalore",
      "K S Institute Of Women Health Worker , Gwalior",
      "K S M MEMORIAL DED COLLEGE",
      "K S Memorial College Of Nursing , Jodhpur",
      "K S Memorial College Of Nursing,Jodhpur",
      "K S Memorial School Of Nursing,Jodhpur",
      "K S N Govt Degree College For Women",
      "K S Nursing College , Gwalior",
      "K S Nursing College And Research Center , Gwalior",
      "K S Nursing Institution , Gwalior",
      "K S R Institute for Engineering and Technology",
      "K S R Mahavidyalaya",
      "K S R Polytechnic College",
      "K S RAJA TEACHER TRAINING INSTITUTE",
      "K S S Arts Commerce Science College",
      "K S S COLLEGE OF EDUCATION",
      "K S S Mahavidyalaya",
      "K S Samitis Vijayanaggar College Education",
      "K S TEACHER TRAINING INSTITUTE",
      "K S TEACHER TRAINING INSTITUTE",
      "K S V DED COLLEGE",
      "K T C T School Of Nursing,Thiruvananthapuram",
      "K T G College Of Nursing , Bangalore",
      "K T G School Of Nursing , Bangalore",
      "K T Patil College Of Bsc Nursing , Osmanabad",
      "K T Reddy Women'S College",
      "K T S Government Degree College",
      "K V G Institute Of Nursing , Sullia",
      "K V G Medical College, Sullia",
      "K V G Polytechnic, Sullia",
      "K V K COLLEGE OF EDUCATION",
      "K V K TEACHER TRAINING INSTITUTE",
      "K V M College Of Nursing , Alappuzha",
      "K V M Nursing College , Rohtak",
      "K V M Nursing School,Rohtak",
      "K V P Socitys Arts And Commerce College",
      "K V R Degree College",
      "K V R Govt College For Women",
      "K V R M K R College",
      "K V S College Of Nursing,Bangalore",
      "K V Science College",
      "K V Subba Reddy Degree College",
      "K V T Polytechnic",
      "K Velayudhan Memorial Hospital , Cherthala",
      "K W T S Divekar College Commerce Karnataka",
      "K. B. B. S. Law College",
      "K. B. H. Law College",
      "K. C. Law College",
      "K. C. S. Societys S. S. Maniyar Law College",
      "K. CHANDRAKALA PG COLLEGE",
      "K. E. Societys Law College",
      "K. G. K. College",
      "K. I. E. T. B.ED COLLEGE",
      "K. J. Somaiya Institute of Engineering & Information Technology,",
      "K. J. Somaiya Polytechnic",
      "K. K. Wagh Institute of Engineering Education & Research College Of Engineering",
      "K. K. Wagh Polytechnic",
      "K. L. E. Society's College of Engineering",
      "K. L. E. Societys B. V. Bellad Law College",
      "K. L. E. Societys Law College",
      "K. N. Nagegowda Law College",
      "K. NANJAPPA GOWNDER COLLEGE EDUCATION",
      "K. P. E. S. Law College",
      "K. P. E. Societys Siddarth Law College",
      "K. R. C. E. Societys H. V. Koujalagi Law College",
      "K. R. E. SOCIETYS KARNATAKA COLLEGE OF EDUCATION",
      "K. Ramakrishanan College Of Engineering",
      "K. S. Rangasamy College of Technology",
      "K. S. Saket Post Graduate College",
      "K. V. Ranga Reddy Law College",
      "K.A & H.L. Degree College, Eluru",
      "K.A. Pandi English Medium Law College",
      "K.A.P Viswanathan Government Medical College, Trichy",
      "K.B. PG College",
      "K.B.H. Law College",
      "K.B.Institute of Pharmaceutical Education & Research , Gandhinagar",
      "K.B.M. TEACHERS TRAINING COLLEGE",
      "K.B.P. College",
      "K.B.R. TEACHER TRAINING INSTITUTE",
      "K.C. Law College",
      "K.C. Reddy Pg College",
      "K.C.E. Soc's College Of Engineering And Information Technology",
      "K.C.E.S.s College Of Education",
      "K.C.Edu.Societys Instt.Of Management And Research",
      "K.C.Edu.Societys Instt.Of Management And Research",
      "K.C.Group Of Institutions Pandoga",
      "K.C.L. Institute of Laws",
      "K.C.N. Sanskrit College",
      "K.C.Polytechnic",
      "K.C.S. Kasi Nadar College Of Arts And Science",
      "K.C.S. Societys S.S. Maniyar Law College",
      "K.C.T. COLLEGE",
      "K.C.T. College of Pharmacy , GULBARGA",
      "K.C.TEACHER TRAINING COLLEGE",
      "K.C.TEACHER TRAINING COLLEGE",
      "K.C.TEACHER TRAINING COLLEGE",
      "K.D Polytechnich Patan",
      "K.D. College",
      "K.D. COLLEGE OF EDUCATION",
      "K.D. Dental College & Hospital",
      "K.D. Dental College , Mathura",
      "K.D. TEACHER TRAINING COLLEGE",
      "K.D. TEACHER TRAINING COLLEGE",
      "K.D. TEACHER TRAINING COLLEGE",
      "K.D.B. Degree College",
      "K.D.Gavit D.Pharmacy College , Nandurbar",
      "K.D.Pawar College of Pharmacy , Nagpur",
      "K.D.PAWAR SHIKSHAN MAHAVIDYALAYA",
      "K.D.R. Govt. Polytechnic, WANAPARTHY",
      "K.E. Societys Law College",
      "K.E.C COLLEGE OF EDUCATION",
      "K.E.S.s Chandrakant Hari Keluskar Homoeopathic Medical College",
      "K.E.T. COLLEGE OF TEACHER EDUCATION",
      "K.G. College",
      "K.G. College Of Arts And Science",
      "K.G. Engineering Institute",
      "K.G.F. College of Dental Sciences & Hospital , BEML Nagar",
      "K.G.I.S.L. INSTITUTE OF INFORMATION AND MANAGEMENT",
      "K.G.K. College",
      "K.G.N. College",
      "K.G.R. INSTITUTE OF INSTITUTE TECH & MANAGEMENT",
      "K.G.S. B.ED. COLLEGE",
      "K.G.V.A. SANGHAS MATOSHREE KANTAMMA SANGANAGOUDA PATIL SASANUR COLLEGE OF EDUCATION FOR WOMEN",
      "K.H. PATIL CENTRE FOR HUMAN EXCELLENCE",
      "K.I.E.T.COLLEGE OF P.G IN EDUCATION M.ED",
      "K.I.M.S. Degree & Pg College",
      "K.INDIRA COLLEGE OF EDUCATION",
      "K.J. Somaiya College Of Arts & Commerce",
      "K.J. Somaiya College Of Science & Commerce",
      "K.J. SOMAIYA INSTITUTE OF MANAGEMENT STUDIES & RESEARCH, MUMBAI",
      "K.J. Somaiyya Medical College & Research Centre, Mumbai",
      "K.J.N EDUCATION COLLEGE ALAMELU AMMAL EDUCATION TRUST",
      "K.J.SOMAIYA COMPREHENSIVE COLLEGE OF EDUCATION TRAINING AND RESEARCH",
      "K.K. College of Pharmacy , Chennai",
      "K.K. Das College Of Commerce",
      "K.K. Parekh Institute of Management Studies",
      "K.K. Polytechnic, Dhanbad",
      "K.K. WAGH COLLEGE OF EDUCATION",
      "K.K. Wagh Women's Polytechnic, Nashik",
      "K.K.C. College of Engineering and Technology",
      "K.K.C. College of Law",
      "K.K.C. INSTITUTE OF PG STUDIES",
      "K.K.DEGREE COLLEGE",
      "K.K.H.A. Arts & M.G.Lodha.Commerce College",
      "K.K.M.College",
      "K.K.R INSTITUTE OF INFORMATION TECH",
      "K.K.S MANI COLLEGE OF EDUCATION",
      "K.K.S. Womens College",
      "K.K.S.Mani Polytechnic College",
      "K.K.W.Arts Science & Commerce College",
      "K.L. D.A.V. Degree College",
      "K.L. Nagaswamy Memorial Polytechnic College",
      "K.L. Polytechnic",
      "K.L.B. D.A.V. College for Girls, Palampur",
      "K.L.B.,D.A.V. COLLEGE FOR GIRLS",
      "K.L.DAV COLLEGE",
      "K.L.E'S INSTT. OF MGT. STUDIE",
      "K.L.E. Society , Sardar V.V.Patil School of Pharmacy , Bangalore",
      "K.L.E. Society College of Pharmacy , Belgaum",
      "K.L.E. Society College of Pharmacy , NIPANI",
      "K.L.E. Society College of Pharmacy,GADAGBETGERI",
      "K.L.E. SOCIETYS COLLEGE OF EDUCATION",
      "K.L.E. Societys Law College",
      "K.L.E. SOCIETYS TEACHER TRAINING INSTITUTE",
      "K.L.E. Sociey College of Pharmacy , Hubli",
      "K.L.E.S S. Nijalingappa College",
      "K.L.N. College of Engineering",
      "K.L.N. TEACHER TRAINING INSTITUTE",
      "K.L.Nagaswamy Memorial Polytechnic",
      "K.L.R. College",
      "K.L.R. COLLEGE OF BUSINESS MGT",
      "K.L.R. Degree College",
      "K.L.R. Degree College, Nizamabad",
      "K.L.R. INSTITUTE OF MGT. & IT",
      "K.L.S. Gogte Institute of Technology",
      "K.L.S. INSTT. OF MGT., EDUCATION & RESEARCH",
      "K.M. Agrawal College of Arts Commerce & Science",
      "K.M. ASGHAR HUSSAIN COLLEGE OF EDUCATION",
      "K.M. COLLEGE OF EDUCATION",
      "K.M. Kundani College Of Pharmacy",
      "K.M. Kundani College Of Pharmacy",
      "K.M. Shah Dental College & Hospital , Vadodara",
      "K.M.A.S COLLEGE OF PHYSICAL EDUCATION",
      "K.M.B.ED. COLLEGE",
      "K.M.C.T. Medical College, Kozhikode",
      "K.M.C.T. Medical College, Kozhikode, Calicut",
      "K.M.C.T. SCHOOL OF BUSINESS (KSB)",
      "K.M.C.T. TEACHERS TRAINING INSTITUTE",
      "K.M.College of Pharmacy , Uthangudi",
      "K.M.D. MEMORIAL TEACHER TRAINING COLLEGE",
      "K.M.G. College Of Arts And Science",
      "K.M.G. COLLEGE OF EDUCATION",
      "K.M.G.COLLEGE OF EDUCATION",
      "K.M.M INSTITUTE OF PG STUDIES",
      "K.M.M. Government Womens College",
      "K.M.M. Institute of Technology and Science",
      "K.M.O Arts & Science College",
      "K.M.O. B.ED COLLEGE",
      "K.M.R. College of Pharmacy , Perudurai",
      "K.M.R. College of Pharmacy, Erode",
      "K.N. AGGARWAL INSTITUTE OF MANAGEMENT",
      "K.N. College Of Arts & Commerce",
      "K.N. Government Arts College For Women",
      "K.N. Government P.G. College",
      "K.N. Homoeopathic Medical College & Hospital",
      "K.N. Katju Law College",
      "K.N. TEACHER TRAINING COLLEGE",
      "K.N.M. Government Arts & Science College",
      "K.N.R. College Of Engineering & Technology",
      "K.N.R. Degree College",
      "K.N.S. WORLD MANAGEMENT COLLEGE",
      "K.P. Government College",
      "K.P. TRAINING COLLEGE",
      "K.P.B. Hinduja College Of Commerce",
      "K.P.C. Medical College And Hospital, Jadavpur, Kolkata",
      "K.P.M COLLEGE OF EDUCATION",
      "K.P.R & J.L. Siddhartha Degree College",
      "K.P.R. School of Business",
      "K.R. & E.D. Association Rani Chennamma, College of Pharmacy , Belgaum",
      "K.R. Arts And Science College",
      "K.R. COLLEGE OF EDUCATION",
      "K.R. GIRLS COLLEGE",
      "K.R. Girls Degree College",
      "K.R. Mandals Uttar Maharashtra College Of Commerce",
      "K.R. Sapkal College of Management Studies,Nashik",
      "K.R. TEACHER TRAINING COLLEGE",
      "K.R. TEACHERS TRAINING COLLEGE",
      "K.R.C.E. SOCIETY S COLLEGE OF EDUCATION",
      "K.R.E. SOCIETYS M.S.MUDDANNA INSTITUTE OF D.ED",
      "K.R.M.D.A.V. College",
      "K.R.N. TEACHER TRAINING INSTITUTE",
      "K.R.P COLLEGE OF EDUCATION",
      "K.R.R. Vignan Degree College For Women",
      "K.R.S.L. Degree College For Women",
      "K.Ramakrishnan College Of Engineering",
      "K.S Hegde Medical Academy, Manglore",
      "K.S TEACHER TRAINING INSTITUTE",
      "K.S. COLLEGE",
      "K.S. Rangasamy Institute Of Technology",
      "K.S. SAKET P.G. COLLEGE",
      "K.S. Saket Post Graduate College",
      "K.S. Saket Post-graduate College",
      "K.S. TEACHER TRAINING COLLEGE",
      "K.S. Wani Institute of Advanced Studies in Marathi",
      "K.S.COLLEGE OF EDUCATION",
      "K.S.E.F. COLLEGE OF EDUCATION",
      "K.S.G. College Of Arts And Science",
      "K.S.K COLLEGE OF EDUCATION",
      "K.S.K College Of Engineering And Technology",
      "K.S.M. COLLEGE OF EDUCATION WOMEN",
      "K.S.M. Polytechnic College",
      "K.S.MANIAM COLLEGE OF EDUCATION",
      "K.S.N.R. Degree College, Garuvu",
      "K.S.R. BUSINESS SCHOOL, TIRUCHENGODE",
      "K.S.R. College Of Arts And Science",
      "K.S.R. Institute of Dental Science & Research",
      "K.S.R. Polytechnic College",
      "K.S.R.COLLEGE OF EDUCATION",
      "K.S.S KANNADA TRANING COLLEGE",
      "K.S.S. VIJAYANAGAR COLLEGE OF EDUCATION",
      "K.S.TEACHER TRAINING INSTITUTE",
      "K.S.U.B. College",
      "K.S.V. INSTITUTE OF ENGINEERING & TECHNOLOGY",
      "K.T. PATIL COLLEGE OF EDUCATION",
      "K.T.G COLLEGE OF TEACHERS",
      "K.T.S.P. Mandal' Kmc College",
      "K.T.T.C. Koushik Degree College",
      "K.V. Babu Degree College",
      "K.V. P.G. COLLEGE",
      "K.V. PG COLLEGE",
      "K.V.C. Memorial Degree College",
      "K.V.G. Dental College & Hospital , Sullia",
      "K.V.G. Law College Kurunji Venkataramana Gowda Law College",
      "K.V.M College of Special Education",
      "K.V.M. TEACHER TRAINING COLLEGE,MAINA EDUCATION SOCITY",
      "K.V.N. Naik S.P. Sanstha's Polytechnic, Nashik",
      "K.V.P.S.s Ayurved Mahavidyalaya",
      "K.V.P.Sansthas Kisan Arts Commerce & Science Col",
      "K.V.P.Sansthas Kisan Mahavidhalaya",
      "K.V.S. TEACHERS TRAINING INSTITUTE",
      "K.V.S.SANTHAS BALKAVI THOMBARE COLLEGE OF PHYSICAL EDUCATION",
      "Kaamedhenu Arts And Science College",
      "Kabi Nazrul College",
      "Kabi Nazrul Mahavidyalaya",
      "Kabi Samrat Upendra Bhanja College of Teacher Education",
      "Kabi Sukanta Mahavidyalaya",
      "Kabi Sukanta Secondary Teacher's Training Institute",
      "Kabisurya Baladev Vigyan Mahavidyalaya",
      "Kabli Mal Ramji Dass Jain College for Women",
      "KABUTARI DEVI RAJESHWAR TRIPATHI SMARAK MAHILA MAHAVIDYALAYA",
      "Kachchh University",
      "Kadambini Womens College of Education",
      "KADAMBUR TEACHER TRAINING INSTITUTE",
      "Kadamibini Pal Womens College",
      "Kadawal Panchkroshi Shikshan Prasarak Mandals New Law College",
      "KADHRIYA COLLEGE OF EDUCATION",
      "Kadi Sarva Vishwavidyalaya",
      "KADU GURU DED COLLEGE",
      "Kahrdiha Degree College",
      "KAI. BHAUSAHEB HIRAY SMARNIKA SAMITI TRUSTS",
      "KAI. VANJIBABA GRAMIN VIKAS MANDAL'S COLLEGE OF EDUCATION",
      "Kaibalya Dayini College Of Commerce",
      "KAIKA INSTITUTE FOR RESEARCH AND ADVANCED STUDIES",
      "KAIKA INSTITUTE OF REASEARCH & ADVANCED STUDIES",
      "Kailash Institute Of Health & Medical Sciences , Panchkula",
      "Kailash Institute Of Health & Medical Sciences,Panchkula",
      "Kailash Institute of Nursing and Para - Medical",
      "Kailash Institute Of Nursing And Para Medical Sciences,Noida",
      "Kailash Institute Of Nursing And Paramedical Sciences ,Noida",
      "Kailash Narayan Patidar College of Science & Technology, Bhopal",
      "Kailaswasi Haribai Warpudkar College Of Nursing , Parbhani",
      "Kailkere Rukmini Shetty Memorial College Of Nursing , Mangalore",
      "Kairali Arts, Science And Commerce College",
      "KAITHAL TEACHER TRAINING COLLEGE",
      "KAIVALYADHAM SRIMAN MADHAVA YOGA MANDIR SAMITI",
      "Kaka Saheb Mhaske Homoeopathic Medical College",
      "Kakasaheb Chavan Mahavidyalaya",
      "Kakasaheb Mhaske Memorial Medical Foundation Kakasaheb Mhaske College of Pharmacy , Ahmednagar",
      "Kakatiya Degree College",
      "Kakatiya Degree College, Jammikunta",
      "Kakatiya Degree College, Nalgonda",
      "Kakatiya Government Degree College",
      "Kakatiya Institute of Management Studies",
      "KAKATIYA INSTITUTE OF MGT. STUDIES",
      "Kakatiya Institute of Technology & Science",
      "Kakatiya Mahila Degree College",
      "Kakatiya Mahila Degree Kalasala",
      "Kakatiya Medical College, Wrangal",
      "Kakatiya Medicalcollege",
      "Kakatiya University",
      "Kakatiya university",
      "kakatiya University College of Law",
      "Kakching Khunou College",
      "Kakdwip Primary Teacher's Training Institute",
      "Kakinada Institute of Engineering & Technology",
      "Kakinada Institute of Technological Sciences",
      "Kakojan College",
      "KALA ASHARAM COLLEGE OF TEACHER TRAINING",
      "Kala Institute of Management Studies And Research",
      "Kala Mahavidyalaya",
      "Kala Mahavidyalaya",
      "KALA NIKETAN COLLEGE EDUCATION",
      "Kala Niketan College Of Nursing,Bangalore",
      "Kala Pandian Polytechnic College",
      "Kala Vigyan Mahavidyalaya",
      "Kalabari College Kalabari",
      "Kalabhyraveswara Polytechnic",
      "Kalahandi Law College",
      "Kalahandi School of Engineering & Technology",
      "Kalahandi Training College",
      "KALAI BHARATHI TEACHER TRAINING INSTITUTION",
      "KALAIAMMAL COLLEGE OF EDUCATION",
      "KALAIBHARTHI COLLEGE OF EDUCATION",
      "Kalaignar Karunanidhi Institute of Technology",
      "KALAIMAGAL COLLEGE OF EDUCATION",
      "KALAIMAGAL TEACHER TRAINING INSTITUTE",
      "KALAIMAHAL COLLEGE OF EDUCATION",
      "Kalaivanar N.S.K. Polytechnic College",
      "KALAIVANI COLLEGE OF EDUCATION",
      "Kalaivani College of Engineering and Technology",
      "KALAIVANI TEACHER TRAINING INSTITUTE",
      "KALAPNA SHIKSHAN PRASHIKSHAN MAHAVIDYALAYA",
      "Kalasalingam Institute Technology",
      "Kalasalingam University",
      "Kalaslingam Academy of Research and Education",
      "Kalawati Girls Degree College",
      "KALAWATI GIRLS DEGREE COLLEGE",
      "Kalawati Snatak Maahavidyalaya",
      "Kalawatibai College Of Engineering & Technology",
      "KALGIDHAR INSTITUTE OF HIGHER EDUCATION",
      "Kali Charan Nigam Institute of Technology",
      "Kali Charan Nigam Institute of Technology, Banda",
      "Kaliabar College",
      "Kaliabor College of Education",
      "Kalicharan Degree College",
      "KALIDAS SANSKRIT TEACHERS TRAINING INSTITUTE",
      "Kalikadham Mahavidyalaya",
      "Kalimpong College",
      "Kalinagar Mahavidyalaya",
      "Kalindi Academy Of Nursing Sciences , Mahasamund",
      "Kalindi College",
      "Kalindi Institute Of Nursing Sciences , Kanker",
      "Kalinga Institute of Engineering & Technology",
      "Kalinga Institute Of Industrial Technology",
      "Kalinga Institute Of Industrial Technology ,Bhubaneswar",
      "Kalinga Institute of Medical Sciences, Bhubaneswar",
      "Kalinga Institute of Pharmaceutical Sciences , Balasore",
      "Kalinga Law College",
      "Kalinga Mahavidyalaya",
      "Kalinga Nursing School , Balasore",
      "Kalinga Nursing School,Bhubaneswar",
      "Kalinga Polytechnic",
      "Kalinga University",
      "Kalinganagar Polytechnic",
      "Kalipada Ghosh Terai Mahavidyalaya",
      "Kaliyaganj College",
      "Kalka Dental College & Hospital , Meerut",
      "KALKA INSTITUTE OF RESEARCH & ADVANCED STUDIES",
      "Kalna College",
      "Kalna College",
      "Kalna Polytechnic",
      "Kalna Primary Teacher's Training Institute",
      "KALOL INSTITUTE OF MANAGEMENT",
      "Kalol Institute of Technology & Research Centre",
      "Kalpana Chawla Government Polytechnic For Women - Ambala",
      "Kalpana Chawla Govt. Poly.for Women, AMBALA CITY",
      "KALPANA CHAWLA TEACHER TRAINING COLLEGE",
      "KALPANA SHIKSHAN PARSHIKSHAN MAHAVIDAYALAYA",
      "Kalpataru Institute of Technology",
      "Kalpataru Science College",
      "KALPATARU VIDYA SAMSTHE(R)",
      "Kalpatharu School Of Nursing , Dakshina Kannada",
      "Kalpi Degree College",
      "Kalpi Institute of Technology",
      "Kalptaru College Of B Sc Nursing,Udaipur",
      "Kalptaru College Of P.bsc Nursing , Udaipur",
      "Kalsar College Of Engineering",
      "KALVI THANTHAI A.K.R. SOURASHTRA TEACHER TRAINING",
      "KALVI ULAGAM TEACHER TRAINING SCHOOL",
      "Kalwan Nursing School,Nashik",
      "Kalyan Homoeopathic Medical College",
      "Kalyan Institute Of Nursing,Chandrapur",
      "Kalyan Law College",
      "KALYAN MAHAVIDYALAYA",
      "Kalyanam Karoti",
      "KALYANI GIRLS DEGREE COLLEGE",
      "Kalyani Mahavidyalaya",
      "KALYANI MCA COLLEGE",
      "Kalyani Mithila Sanskrit Mahavidyalaya",
      "Kalyani Nursing School,Nagpur",
      "Kalyani University",
      "KALYAYANI COLLEGE OF EDUCATION",
      "Kamadhenu College Of Arts And Science",
      "Kamakshi College Of Bsc Nursing, Kangra",
      "Kamakshi G N M Institute , Kangra",
      "Kamakshi School Of Nursing , Mysore",
      "Kamakshi School Of Nursing, Barmer",
      "Kamakshyanagar College",
      "KAMAL D.ED TRAINING SCHOOL",
      "KAMAL INSTITUTE OF HIGHER EDUCATION AND ADVANCE TECHNOLOGY",
      "Kamal Institute Of Nursing Education,Sangli",
      "KAMAL SINGH COLLEGE",
      "KAMALA NEHRU POLYTECHNIC FOR WOMEN",
      "KAMALA BALIGA COLLEGE EDUCATION",
      "Kamala Bezbaruah Memorial College ofTeacher Education",
      "Kamala College for Women",
      "KAMALA COLLEGE OF EDUCATION",
      "Kamala College Of Medical Sciences , Salem",
      "Kamala College Of Nursing,Bangalore",
      "Kamala Devi Sohanraj SinghviJain College of Education",
      "Kamala Institute of Management Studies",
      "Kamala Institute of Tech & Science",
      "Kamala Jayarao College of Pharmacy , Rajahmundry",
      "Kamala Krishna Royale Nursing College,Bangalore",
      "KAMALA NEHRU EDUCATION TRUST(R)",
      "Kamala Nehru Memorial Hospital , Allahabad",
      "Kamala Nehru Memorial National College Of Arts Science For Women",
      "Kamala Nehru Womens College",
      "KAMALA PRASAD SINGH MAHAVIDYALAYA",
      "Kamala School Of Nursing , Bangalore",
      "Kamalabai Umak Nursing School,Amaravati",
      "Kamalakshi Pandurangan College of Pharmacy , Tiruvannamalai",
      "Kamalnayan Bajaj Nursing College , Aurangabad",
      "Kamani Science And Ptaprai Arts College",
      "KAMARAAJAR COLLEGE OF EDUCATION TRUST",
      "Kamaraj College",
      "KAMARAJ COLLEGE OF EDUCATION KUPPAMMAL RAMASAMY EDUCATION TRUS",
      "Kamaraj College of Engineering & Technology",
      "KAMARAJ SECONDARY GRADE TEACHER TRAINING INSTITUTE",
      "KAMARAJ UNIVERSITY",
      "KAMARAJAR COLLEGE OF EDUCATION",
      "Kamarajar Polytechnic College",
      "Kamareddy Engineering College",
      "Kamargaon College",
      "Kamatchi Polytechnic College",
      "Kamath Institute of Technology Polytechnic",
      "Kamaxi Devi Homoeopathic Medical College",
      "Kamayani Prashikshan and Sanshodhan Society",
      "Kamban College Arts And Science For Women",
      "Kamban Engineering College",
      "Kamdar Anm Training School , Rajkot",
      "Kamdar School Of Nursing , Rajkot",
      "Kameshwar Prasad Singh College",
      "Kameshwar Singh Darbhanga Sanskrit",
      "Kameshwar Singh Darbhangha Sanskrit University",
      "Kamineni College Of Nursing , Hyderabad",
      "Kamineni Institute of Dental Sciences , Nalgonda",
      "Kamineni Institute of Medical Sciences , Narketpally",
      "Kamineni School Of Nursing , Hyderabad",
      "Kamla Arya Kanya Pg Degree College",
      "Kamla Baliga College Education",
      "KAMLA DEVI TEACHER TRAINING COLLEGE",
      "Kamla Lohtia S.D. College",
      "KAMLA NAHRU INSTITUTE OF PHYCIAL AND SOCIAL SCIENCE",
      "Kamla Nehru College",
      "Kamla Nehru College",
      "Kamla Nehru College for Women",
      "KAMLA NEHRU COLLEGE FOR WOMEN",
      "Kamla Nehru Degree College",
      "Kamla Nehru Girls College",
      "KAMLA NEHRU INSTITUTE OF MANAGEMENT & TECHNOLOGY",
      "Kamla Nehru Institute Of Management & Technology ,Sultanpur",
      "KAMLA NEHRU INSTITUTE OF PHYSICAL & SOCIAL SCIENCES",
      "KAMLA NEHRU INSTITUTE OF SCIENCE & TECHNOLOGY",
      "Kamla Nehru Institute of Technology",
      "KAMLA NEHRU INSTITUTION OF PHY. & SOCIAL SCIENCES",
      "Kamla Nehru Mahavidyalaya",
      "KAMLA NEHRU MAHAVIDYALAYA",
      "Kamla Nehru Mahavidyalaya, Nagpur",
      "KAMLA NEHRU MAHILA MAHAVIDYALAYA",
      "Kamla Nehru Memorial Hsopital,Allahabad",
      "Kamla Nehru Polytechnic for Women , HYDERABAD",
      "Kamla Nehru Vidhi Sansthan",
      "Kamla Prasad Singh Degree College",
      "KAMLA PRASAD SINGH DERGEE COLLEGE",
      "KAMLA PRASAD SINGH DERGEE COLLEGE",
      "KAMLA PRASAD SINGH DERGEE COLLEGE",
      "KAMLA PRASAD SINGH MAHAVIDYALAYA",
      "Kamla Prasad Singh Vidhi Mahavidalaya",
      "Kamla Raja Girls Degree College",
      "KAMLA SHIKSHAN SANSTHAN",
      "KAMMAVAR SANGAM COLLEGE OF EDUCATION",
      "KAMMAVARI EDUCATIONAL SOCIETY(R)",
      "Kammavary Polytechnic",
      "Kampur College",
      "Kamrup College",
      "Kamtaprasad Guru Bhasha Bharti Sansthan",
      "kanad Institute of Engg. & Management",
      "Kanak Manjari Institute of Pharm.Sciences , Rourkela",
      "Kanak Manyatri Womens College",
      "KANAKA TEACHERS TRAINING INSTITUTE",
      "KANAKA VIDYA SAMSTHE KANAKA VIDYA SAMSTHE SHADIMAHAL",
      "KANAKADAS SHIKSHANA SAMITI",
      "KANAKADAS SHIXAN SAMIT K.S.R. DIPLOMA EDUCATI COLLE",
      "KANAKADAS SHIXAN SAMIT TEACHER TRAINING INSTITUTE",
      "Kanakdas Shikshan Samitis Arts College",
      "Kanan Devi Memorial College of Education",
      "KANARA WELFARE TRUSTS B.ED COLLEGE",
      "Kanas College",
      "KANCHAN SINGH BHOOLI DEVI MAHAVIDYALAYA",
      "KANCHAN SINGH BHOOLI DEVI MAHAVIDYALAYA",
      "KANCHAN SINGH BHOOLI DEVI MAHAVIDYALAYA",
      "Kanchan Singh Bhooli Devi Mahavidyalaya",
      "KANCHAN SINGH BHOOLI DEVI MAHAVIDYALYA",
      "KANCHI COLLEGE OF TEACHER EDUCATION",
      "Kanchi Kamachi Amman Arts Science College For Women",
      "Kanchi Mamunivar Centre for PG Studies",
      "Kanchi Pallavan Engineering College",
      "KANCHI SHRI KAMATCHI AMMAN TEACHERS TRAINING INSTITUTE",
      "Kanchi Shri Krishna College Of Arts And Science",
      "Kanchrapara College",
      "Kandarpur College",
      "Kandaswami Kandars College",
      "Kandhamal G N M Training College ,Po Pokana Gaon",
      "KANDHASWAMY COLLEGE OF EDUCATION",
      "Kandi Primary Teacher'sTraining Institute",
      "Kandi Raj College",
      "Kandula Obul Reddy Memorial College of Engineering",
      "Kangleipak Medical And Nursing Institute , Imphal",
      "Kangleipak Medical And Nursing Institute,Imphal",
      "KANIKAI MATHA TEACHER TRAINING INSTITUTE",
      "Kanishka School Of Nursing,Satara",
      "Kankavali Arts & commerce College",
      "Kankavli College,kankavli",
      "Kankrej Arts And Commerce College",
      "KANKU VIJAY TEACHERS TRAINING COLLEGE",
      "KANNADA BALAGA SOCIETY RURAL T.T.I",
      "Kannada University",
      "Kannur Dental College , Kannur",
      "Kannur Medical College, Kannur",
      "KANNUR SALAFI B ED COLLEGE",
      "Kannur University",
      "KANNUR UNIVERSITY DEPARTMENT",
      "Kanohar Lal Sanatkottar Mahila Mahavidyalaya",
      "Kanoria Mahila Mahavidyalaya",
      "KANORIA TEACHER TRAINING COLLEGE",
      "Kanpur Anchalik Mahavidyalaya",
      "Kanpur Institute of Technology",
      "KANPUR VIDHYAMANDIR",
      "Kanpur Vidya Mandir Mahila Degree (P.G.) College",
      "Kanta Polytechnic",
      "KANTA TEACHER TRAINING COLLEGE",
      "KANTILAL KHIWASARA B.ED. COLLEGE",
      "KANWAY TEACHER TRAINING COLLEGE",
      "KANYA GURUKUL TEACHER TRAINING COLLEGE",
      "Kanya Mahavidyalaya",
      "Kanya Mahavidyalaya",
      "Kanya Mahavidyalaya",
      "Kanya Mahavidyalaya",
      "Kanya Mahavidyalaya Degree College",
      "Kanya Mahavidyalaya Guwahati",
      "Kanyakumari Government Medical College, Asaripallam",
      "Kanyakumari Medical Mission, Ingrid Kowski , School Of Nursing,Kanyakumari",
      "Kanyapur Polytechnic",
      "Kapadia N M M S Arts And S N S B S Commerce College",
      "Kapi Polytechnic College",
      "KAPI TEACHER TRAINING INSTITUTE",
      "KAPIL PONDA MEMORIAL SHIKSHAN SAMITI",
      "Kapisthal Institute Of Medical Sciences & Nursing , Kurukshetra",
      "KAPOORI DEVI KRIPA RAM MAHAVIDYALAYA",
      "Kaptipada College",
      "Kaptipada College",
      "Kar Polytechnic College",
      "Karabandia Subba Rao Memorial Degree College",
      "KARAIKAL INSTITUTE OF TEACHER TRAINING",
      "Karaikal Polytechnic College",
      "Karaikal Polytechnic College",
      "KARAIKAL TEACHER TRAINING INSTITUTE",
      "karaikudi institute of technology & karaikudi institute of management",
      "Karam Mano Vikas Sansthan",
      "KARAMAI HUSAIN MUSLIM GIRLS P.G. COLLEGE",
      "Karamat Husain Muslim Girls Degree College",
      "KARAMBHUMI TEACHERS TRAINING COLLEGE",
      "Karamchand Bhagat College",
      "KARAMKSHETRA MAHAVIDYALAYA",
      "Karamveer abasaheb alias Narain Mansaram sonawana Arts Science and Commerce College",
      "Karamveer Audumbar Patil Law College",
      "karamveer ganpat dada More Arts & Commerce College",
      "Karamveer Hire Arts Science And Commerce & Education College",
      "Karamveer Mamasaheb Jagdale Mahavidyalaya",
      "Karanam Padmavathi Memorial Degree College",
      "KARANATAKA GRAMEEN TEACHER TRAINING COLLEGE",
      "Karanjia College",
      "Karavali College of Hotel Management",
      "Karavali College Of Nursing Science , Mangalore",
      "Karavali College Of Nursing Sciences,Mangalore",
      "Karavali College of Pharmacy , Mangalore",
      "KARAVALI INSTITUTE OF EDUCATION",
      "Karavali Institute of Technology",
      "Karavali Polytechnic , Mangalore",
      "KARGIL SHAHID MAHAVIDYALAYA",
      "Karigiri School Of Nursing, ,Vellore",
      "Karim City College",
      "Karimala Degree College",
      "Karimganj College",
      "Karimganj Law College",
      "Karimpur Panna Devi College",
      "Karm Kshetra degree (PG) College",
      "KARM VIDYAMANDIR SHIKSHAN SANSTHAN MUNDAWAR",
      "Karmala Rani Training College",
      "karmaveer Bhauro Patil Pandharpur College",
      "Karmaveer Dadasaheb Kannamwar College of Engineering",
      "Karmaveer R.S. Wagh Education and Health Institute, Kadwa Polytechnic",
      "Karmaveer Ramrojee Aher Artsscience & Commerce College",
      "KARMAVEER SHIKSHAN PRASARAK MANDALS COLLEGE OF EDUCATION FOR WOMEN",
      "Karmavir Mahavidyalaya",
      "KARMELA RANI TRAINING COLLEGE",
      "Karmyogi Tulshiram Pawar College",
      "Karnal Institute of Polytechnic",
      "Karnal Institute of Technology & Management",
      "KARNATAK GRAMEEN VIDYA ABHIVRIDHI SANGH TALIKOTI",
      "KARNATAK RURAL EDUCATION SOCIETY",
      "Karnataka (Govt,) Polytechnic, Mangalore",
      "Karnataka Arts College",
      "Karnataka Arts Science And Commerce College",
      "KARNATAKA BHOVI WELFAR ASSOCIATION",
      "KARNATAKA COLLEGE OF EDUCATION",
      "Karnataka College of Management",
      "Karnataka College Of Nursing , Bangalore",
      "Karnataka College of Pharmacy , Bangalore",
      "KARNATAKA D.ED COLLEGE",
      "Karnataka Folklore University",
      "KARNATAKA GRAMEENA VID ABHIVRUDDHI SANGHA D.E COLLEGE",
      "Karnataka Handicapped Welfare Association",
      "Karnataka Health Institute Sch Of Nsg., Belgaum",
      "Karnataka Institute of Medical Sciences , Hubli",
      "Karnataka Institute Of Nursing , Bellary",
      "KARNATAKA KAVERI INSTT. OF MGT",
      "KARNATAKA LABOUR EDUCATION SOCIETY",
      "Karnataka Law College",
      "Karnataka Law Society's Viswanathrao Deshpande Rural Institute Of Technology",
      "KARNATAKA M.ED COLLEGE",
      "Karnataka Medical College",
      "Karnataka Parent's Association for the Mentally Retarded Citizens",
      "Karnataka People Education Society Milind Institute of Pharmacy , Bangalore",
      "KARNATAKA PEOPLES EDUCATION SOCIETY",
      "KARNATAKA PEOPLES EDUCATION SOCIETYS",
      "KARNATAKA RAJYA SAVITH SAMAJA",
      "Karnataka Sanskrit University",
      "Karnataka School Of Nursing , Bangalore",
      "Karnataka School Of Nursing , Gulbarga",
      "Karnataka Science College",
      "Karnataka Science College",
      "Karnataka State Law University",
      "Karnataka State Open University",
      "KARNATAKA STATE OPEN UNIVERSITY",
      "Karnataka State Women University",
      "KARNATAKA STATE WOMENS UNIVERSITY",
      "KARNATAKA TEACHERS COLLEGE",
      "Karnataka University",
      "Karnataka Veterinary, Animal & Fisheries Science University",
      "Karnavati School of Dentistry , Gandhinagar",
      "Karneemata Institute Of Nursing",
      "Karpaga Vinayag College Of Nursing ,Kanchipuram",
      "Karpaga Vinayaga College of Engineering and Technology",
      "Karpaga Vinayaga College Of Nursing , Kanchipuram",
      "Karpaga Vinayaga College Of Nursing , Pudukkottai",
      "Karpaga Vinayaga Institute of Dental Sciences , Chennai",
      "Karpaga Vinayaga Institute of Management",
      "Karpaga Vinayaga Institute of Medical Sciences,Maduranthagam",
      "KARPAGA VINAYAGAR COLLEGE OF EDUCATION",
      "Karpagam Arts & Science College",
      "Karpagam College of Engineering",
      "Karpagam College Of Nursing , Coimbatore",
      "Karpagam Faculty of Medical Sciences & Research, Coimbatore",
      "Karpagam Institute of Technology",
      "Karpagam Polytechnic College",
      "KARPAGAM TEACHER TRAINING INSTITUTE",
      "KARPAGAM TEACHER TRAINING INSTITUTE",
      "Karshak Engineering College",
      "KARTAR MEMORIAL TEACHER TRAINING COLLEGE",
      "Karthikeya Polytechnic College",
      "Karthikeyan Institute of Management Sciences",
      "Karthikeyan School Of Nursing, , Nagapattinam",
      "KARTHIKEYAN TEACHER TRAINING INSTITUTE",
      "Kartik Oraon College",
      "Karuna College Of Nursing , Pallakad",
      "Karuna College Of Nursing,hanumangarh",
      "Karuna Medical College, Palakkad",
      "Karuna Nursing School,Nashik",
      "KARUNA PG COLLEGE",
      "Karuna School of Nursing , Ranga Reddy",
      "Karuna School Of Nursing, Hanumangarh",
      "KARUNA SHIKSHAK PRASHIKSHAN MAHILA MAHAVIDYALAYA",
      "KARUNA SHIKSHAK PRASHIKSHAN MAHILA MAHAVIDYALAYA",
      "KARUNA SHIKSHAK PRASHIKSHAN MAHILA MAHAVIDYALAYA",
      "KARUNA SHIKSHAK PRASHIKSHAN MAHILA MAHAVIDYALAYA",
      "KARUNA TEACHER TRAINING INSTITUTE",
      "Karunji College of Arts & Science",
      "Karunya A N M Training School,Udupi",
      "Karunya Institute of Technology",
      "KARUNYA INSTITUTE OF TECHNOLOGY AND SCIENCES",
      "KARUNYA SCHOOL OF MANAGEMENT, COIMBATORE",
      "KARUNYA TEACHER TRAINING INSTITUTE",
      "Karunya University Coimbatore",
      "KARUNYAA TEACHER TRAINING INSTITUTE",
      "Karuppannan Mariappan College",
      "Karur College of Engineering",
      "Karve Society College Of Education",
      "Kasabai School Of Nursing,Wardha",
      "Kasals Nursing Training School,Sindhudurg",
      "Kashi Nath Mahavidyalaya",
      "Kashi Shahu College",
      "KASHINATH MAHAVIDYALAYA",
      "Kashipur Michael Madhusudan Mahavidyalaya",
      "Kashmir Creative Education Foundation",
      "Kashmir Creativeeducation Foundation College Education",
      "Kashmir Government Polytechnic",
      "Kashmir Law College",
      "Kasireddy Narayanreddy College of Engineering and Research",
      "KASTHOORBA GANDHI SMARAKA PRE PRIMARY TTI",
      "KASTHOORBA GANDHI TEACHER TRAINING INSTITUTE",
      "KASTHOORIBHA GANDHI COLLEGE EDUCATION",
      "Kasthurba College for Women",
      "KASTHURBA GANDHI KANYA GURUKULAM",
      "KASTHURBA GANDHI MEMORIAL HINDI TEACHER TRAINING INSTITUTE",
      "KASTHURIBA GANDHI JAL (SPAIN COLLEGE OF EDUCATION(FOR WOMEN))",
      "Kasturaba Gandhi Anmhw f Training School , Jagat Singh Pur",
      "KASTURBA COLLEGE OF EDUCATION",
      "Kasturba College Of Nursing , Bhopal",
      "Kasturba Gandhi College for Women",
      "Kasturba Gandhi College Of Nursing , Pillaiyarkuppam",
      "Kasturba Gandhi Hospital , Delhi",
      "KASTURBA GANDHI MAHILA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA",
      "Kasturba Gandhi Nursing College , Pillaiyarkuppam",
      "Kasturba Gandhi School Of Nursing ,Villapuram",
      "Kasturba Girls College",
      "Kasturba Health Societys Hospital, Kasturba Nursing College , Wardha",
      "Kasturba Health Societys Hospital, Wardha",
      "Kasturba Hospital",
      "Kasturba Hospital, New Delhi",
      "Kasturba Medical College, Mangalore",
      "Kasturba Medical College, Manipal",
      "Kasturba Medical College, Manipal Academy of Higher Education",
      "Kasturba Nursing College , Wardha",
      "Kasturba Polytechnic for Women",
      "Kasturba School Of Nursing , Rajahmundry",
      "KASTURBA WOMENS MULTIPURPOSE SOCIETIES COLLEGE OF EDUCATION",
      "Kasturbagram Rural Institute",
      "Kasturbai College Of Education",
      "KASTURBAI COLLEGE OF EDUCATION",
      "Kasturbai Gandhi Degree Pg College For Women",
      "KASTURI COLLEGE OF EDUCATION KASTURBAI MANEKBAI CHRT TRUS",
      "KASTURI RAM TEACHER TRAINING COLLEGE OF HIGHER EDUCATION,",
      "Kasturi School Of Nursing , Saroornagar",
      "KASTURI SHIKSHAN SANSTHA COLLEGE OF EDUCATION",
      "Kasturi Shikshan Sanstha, Institute of Management",
      "KASTURIBA MAHILA VIVIDODESHA SANSTHE SMT.INDIRA GANDHI WOMENS COLLEGE",
      "Katgara Polytechnic Institute",
      "Kathir College of Engineering",
      "Katihar Medical College, Katihar",
      "Katni College of Commerce & Arts",
      "Katrina Moller College Of Nursing",
      "Katruwar Arts R. Kabra Science & B.R. Mantri Commerce College",
      "Katuri College Of Nursing.Guntur",
      "Katuri Medical College, Guntur",
      "Katwa College",
      "Katwa College",
      "KATYAYANI COLLEGE OF EDUCATION",
      "Kaumadi College, Sirkakulam",
      "Kaushalendra Rao Law College",
      "KAUSHAMBI DEGREE COLLEGE",
      "Kaushambi Degree College",
      "Kaushambi Law College",
      "Kaushik College of Engineering",
      "KAUSHNIYA INSTITUTE FOR NURSERY TEACHER EDUCATION",
      "KAUSILYA MAHAVIDYALAYA",
      "KAUTILYA INSTITUTE OF MANAGEMENT & RESEARCH",
      "Kautilya Institute of Technology & Engineering",
      "KAUTILYA MAHILA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA",
      "Kauvery Women'S College",
      "Kaveri School Of Nursing , Bangalore",
      "KAVI KULGURU INSTITUTE OF TECHNOLOGY & SCIENCE",
      "KAVI KULGURU KALIDAS SANSKRIT VISHWAVIDYALAYA",
      "Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya",
      "Kavikulguru Institute of Technology and Science",
      "KAVINGAR KOLANJI TEACHER TRAINING INSTITUTE",
      "Kavitha Degree College",
      "Kavitha Memorial Degree College",
      "KAVIYATTU B.ED COLLEGE",
      "Kavuri Subba Rao College Of Nursing , Guntur",
      "Kavuri Subba Rao School Of Nursing , Kothapet",
      "Kawa Global Institute",
      "KAY JAY TEACHER TRAINING COLLEGE",
      "Kazi Nazowl Islam Mahavidyalaya",
      "KBH Law College",
      "KBR Engineering College",
      "KC College of Engineering",
      "KC College of Engineering and Information Technology",
      "KCB Technical Academy",
      "KCES Institute Of Management & Research, Jalgaon",
      "KCG College of Technology",
      "KCM ARMY TEACHER TRAINING COLLEGE",
      "KCP D.ED COLLEGE",
      "KCT Engineering College",
      "KDK College Of Engineering",
      "KDK Group of Institutes",
      "KEC TEACHER TRAINING INSTITUTE",
      "Kedar Lingaiah Hiremath Polytechnic",
      "Kedari Redekar Nursing School,Kolhapur",
      "Kedarnath Aggarwal Institute of Management",
      "Kedarnath Sanskrit College",
      "KEERAI THAMIL SELVAN COLLEGE EDUCATION FOR WOMEN",
      "Keerrai Thamil Selvan College Of Nursing , Pudukkottai",
      "Keerrai Thamil Selvan School Of Nursing ,Pudukkottai",
      "Keerthi College Of Nursing , Gulbargh",
      "KEERTHI EDUCATION TRUST",
      "Keerthi Education Trust Society regd. , Gulbarga",
      "KEHARI MAL GAUTAM SMARAK DEGREE COLLEGE",
      "KEINS TEACHER TRAINING INSTITUTE",
      "Kejriwal Institute of Management & Development Studies",
      "Kelomal Govt.Primary Teacher's Training Institute",
      "Kempegowda College Of Nursing , Bangalore",
      "Kempegowda Institute of Medical Sciences, Bangalore",
      "Kempegowda Institute of Nedical Sciences, Bangalore",
      "Kempegowda Institute Of Nursing Sciences , Bangalore",
      "Kempegowda Law College",
      "Kempegowda Memorial Polytechnic",
      "Kems Pratap College",
      "Ken College",
      "Kendrapara College",
      "KENDRIA COLLEGE OF EDUCATION",
      "KENDRIYA HINDI MAHAVIDYALAYAM",
      "KENDRIYA SANSKIT VIDYAPEETHU",
      "KENDRIYA SANSKRIT VIDHYAPEETH",
      "KENIS COLLEGE OF EDUCATION WOMEN",
      "KENNEDY COLLEGE OF EDUCATION",
      "KENWAY TEACHER TRAINING COLLEGE",
      "KENWAY TEACHER TRAINING COLLEGE",
      "Keonjhar Law College",
      "Kerala Agricultural University",
      "Kerala Federation of the Blind , Training Centre for the Teachers of V.H.",
      "Kerala Govt. Polytechnic College, Kozhikode",
      "KERALA HINDI PRACHAR SABHA",
      "Kerala Institute of Co-operative Management",
      "Kerala Institute Of Medical Sciences, College Of Nursing , Thiruvananthapuram",
      "KERALA INSTITUTE OF TOURISM AND TRAVEL STUDIES",
      "Kerala Kalamandalam",
      "Kerala Law Academy Law College",
      "Kerala University of Fisheries & Ocean Studies",
      "Kerala University of Health Sciences",
      "Kerala Veterinary & Animal Sciences University",
      "KES. Polytechnic.for Women,vijayawada",
      "Kesarsal Medical College & Research Institute, Ahmedabad",
      "Kesarwani Arts Commerce & Education College",
      "KESARWANI MAHAVIDYALAYA",
      "KESHAV INSTITUTE OF INFORMATION TECHNOLOGY",
      "KESHAV INSTITUTE OF MGT",
      "Keshav Kamal Nursing School",
      "KESHAV MAHAVIDHYALAYA",
      "Keshav Mahavidyalaya",
      "Keshav Mahavidyalya Delhi",
      "Keshav Memorial Degree College",
      "Keshav Memorial Institute of Technology",
      "Keshav Nursing School,Jaipur",
      "Keshav Prasad Ralhi Mahavidyalaya",
      "KESHAV TEACHER TRAINING COLLEGE",
      "KESHAV TEACHERS TRAINING",
      "KESHAV VIDYAPEETH TEACHERS TRAINING COLLEGE",
      "KESHAVRAJ SENIOR COLLEGE OF EDUCATION",
      "keshlata medical college bareilly",
      "Keshlata School Of Nursing, Bareilly",
      "Keshlata School Of Nursing,Barelly",
      "Kesinga Mahavidyalaya",
      "KET EDUCATION INSTITUTE",
      "KET Polytechnic College, krishnagiri",
      "KEVI WOMENS COLLEGE OF EDUCATION",
      "KEVLA NAND B.ED COLLEGE",
      "KEVLANAND B.ED COLLEGE",
      "KEWLA SUNDER MAHAVIDYALAYA",
      "Kewla Sunder Mahavidyalaya",
      "Keyi Sahib Training College",
      "KEYI SAHIB TRAINING COLLEGE",
      "KG Reddy College of Engineering and Technology",
      "KGiSL Institute Technology",
      "Kha Manipur College",
      "Khadar Daloi Law College",
      "Khader Memorial College of Engineering & Technology",
      "Khadija Nursing School , Gulbarga",
      "Khadir Mohideen College",
      "Khagarijan College",
      "KHAIR KANYA MAHAVIDYALAYA",
      "Khaira College",
      "Khaitanji Law College",
      "Khaja Banda Nawaz College of Engineering",
      "Khaja Banda Nawaz College Of Nursing,Gulbarga",
      "Khaja Banda Nawaz Institute of Medical Sciences, Gulbarga",
      "Khaja Banda Nawaz School Of Nursing , Gulbarga",
      "KHAJAN SINGH GIRLS DEGREE COLLEGE",
      "KHALAN TEACHER TRAINING COLLEGE",
      "Khalisani Mahavidyalaya",
      "Khallikota (Autonomous) College",
      "Khallikote Evening College",
      "Khalsa College",
      "Khalsa College",
      "Khalsa College for Women",
      "Khalsa College for Women",
      "Khalsa College Lyallpur Institute of Management and Technology",
      "Khalsa College Of Education",
      "Khalsa College Of Education",
      "Khalsa College Of Nursing , Amritsar",
      "Khalsa Nursing Training Institute & Hospital , Mansa",
      "Khalsa Nursing Training Institute For Gnm And Hospital , Mansa",
      "Khalsa Rural Nursing Training & Hospital Trust R , Mansa",
      "Khalsa Rural Nursing Training Institute & Hospital , Mansa",
      "Khalsa School Of Nursing , Amritsar",
      "KHALSA TEACHER TRAINING COLLEGE",
      "Khamargachi B.Ed. College",
      "Khamargachi Primary Teacher's Training Institute",
      "Khammam Institute of Technology & Science",
      "Khandelwal College of Management Science & Tech.",
      "KHANDELWAL COLLEGE OF MANAGEMENT SCIENCE & TECHNOLOGY",
      "KHANDELWAL COLLEGE OF MANAGEMENT SCIENCE & TECHNOLOGY",
      "Khandelwal Law College",
      "Khandesh College Education Society",
      "KHANDESH COLLEGE EDUCATION SOCIETYS COLLEGE OF EDUCATION",
      "KHANDESH EDUCATION SOCIETY-INSTITUTE OF MANAGEMENT & RESEARCH",
      "Khandesh Nursing Institute,Jalgaon",
      "Khandoli Institute of Technology",
      "Khandra College",
      "Kharagpur College",
      "Kharagpur Homoeopathic Medical College and Hospital",
      "Kharagpur Tribal Primary Teacher's Training Institute",
      "Kharasrota Mahavidyalaya",
      "Khariar College",
      "Kharshedbanu R.Mewawala Mahila Mahavidyalaya",
      "Kharupetia College Darrang",
      "Khasdar Govindrao Adik Law College",
      "Khasdur Shri Govindrao Adik Law College",
      "KHASI NATH MAHAVIDYALAYA",
      "Khatra Adibasi Mahavidyalaya",
      "KHATUN MINORITY WOMENS SOCIALS WELFARE AND EDUCATION SOCIETYS AM COLLEGE",
      "Khawaja Garib Nawaz College Of Nursing,Sikar",
      "Khawaja Gharib Nawaz College Of Nursing , Sikar",
      "Khawaja Gharib Nawaz College Of Nursing,Sikar",
      "Khawzawl College",
      "Khejuri College",
      "KHEMAJI NAIK COLLEGE OF EDUCATION",
      "Khemundi College",
      "Kherajkhat College",
      "Kheralu Nagarik Sahakari Bank Ltd Arts And Commerce College",
      "Khetra Basi D.A.V. College",
      "KHIZRA INSTITUTE OF INFORMATION TECH & MANAGEMENT",
      "KHK Institute of Engineering,Dharwad",
      "Khoirabari College",
      "Kholeshwar Mahavidyalaya",
      "Khowang College",
      "Khristiya Seva Niketan , Bankura",
      "Khun Khun Ji Girls Degree College",
      "KHUN KHUN JI GIRLS DEGREE COLLEGE",
      "KHUN KHUN JI GIRLS DEGREE COLLEGE",
      "Khunta Mahavidyalaya (+3 Degree)",
      "Khurda School Of Nursing , Khurda",
      "Khushi School Of Nursing , Hissar",
      "Khwaja Gharib Nawaz College Of Nursing , Sikar",
      "Kiang Nonghah Government College",
      "Kidderpore College",
      "Kidsology Educare Private Limited",
      "Kidwai Memorial Institute Of Oncology , Bangalore",
      "Kidwai Memorial Institute of Oncology, Bangalore",
      "KIET Polytechnic",
      "KIIT College of Engineering.",
      "KIIT School of Law",
      "Kilpauk Medical College, Chennai",
      "KINDER KIN TEACHER TRAINING COLLEGE",
      "KING COLLEGE OF EDUCATION",
      "King College of Technology",
      "King Edward Memorial Hsopital , Pune",
      "King George Hospital School Of Nursing , Visakhapatnam",
      "King George Medical University",
      "King Institute of Preventive Medicine",
      "King Nandivarman College Of Arts And Science",
      "King's Group of Institutions",
      "Kings  Engineering College",
      "Kings College of Engineering",
      "Kingston Engineering College",
      "Kingston Law College",
      "KINGSTON P.G. COLLEGE",
      "Kingston Polytechnic College",
      "Kinjirkela College",
      "KINKAR COLLEGE OF EDUCATION",
      "Kinnera College Of Nursing",
      "Kinwat Education Societys Baliram Patil Arts Commerce And Science College",
      "Kiran Bahuuddeshiya Shikshan Sanstha's R R Polytechnic",
      "Kiran College Of Nursing,Bangalore",
      "Kiran Kumari School Of Nursing , Bidar",
      "Kiran Memorial Kular School Of Nursing , Ludhiana",
      "Kiran School Of Nursing,Dhule",
      "Kiran Society",
      "KIRANAM Organisationa for the welfare of disabled",
      "Kiranmayi Degree College, Srikakulam",
      "KIRAPULA MAHILA MAHAVIDYALAYA",
      "Kirloskar Institute of Advanced Management Studies",
      "Kirodimal Institute of Technology",
      "KIROR LAL SHAATRI MAHAVIDYALAYA",
      "Kirori Mal College",
      "KIRORI MAL TEACHER TRAINING COLLEGE",
      "KIRORIMAL TEACHER TRAINING COLLEGE",
      "KIRPAL SAGAR TEACHER TRAINING COLLEGE",
      "KIRTI TEACHER TRAINING COLLEGE",
      "Kisan College",
      "KISAN DEGREE COLLEGE",
      "Kisan Degree College, Srikakulam",
      "KISAN DNYANODAY MANDAL",
      "Kisan Dnyanoday Mandal, GudheSanchalit Institute of Pharmacy , Chalisgaon",
      "Kisan Dnyanoday Mandals Homoeopathic Medical College",
      "Kisan Law College",
      "Kisan Mahavidyalaya",
      "Kisan P.G. College",
      "KISAN SHIKSHAN PRASARA MANDAL SHIVAJI D.ED COURSE(T.T.I)",
      "KISAN SHIKSHAN PRASARAK MANDALS",
      "Kisan Shikshan Prasarak Mandals Latur Homoeopathic Medical College",
      "Kisan Vidhi Mahavidyalaya Muriyari",
      "Kisan Vidya Prasarak Sanstha M.A.H. College of Pharmacy , BORADI",
      "KISAR MAHAVIDYALAYA",
      "KISAR MAHAVIDYALAYA",
      "Kishan Institute Of Information Technology",
      "Kishan Institute Of Teachers Education",
      "KISHAN INSTITUTE OF TEACHERS EDUCATION",
      "KISHAN P.G. COLLEGE",
      "KISHAN P.G. COLLEGE",
      "KISHAN PRASHIKSHAN MAHAVIDHYALYA",
      "KISHAN PRASHIKSHAN MAHAVIDYALAYA",
      "KISHAN VIDYALAYA",
      "Kishanchand Chellaram Law College",
      "Kishanlal Public College",
      "Kishinchand Chellaram Law College",
      "KISHNA MAHAVIDYALAYA",
      "KISHNA PAL SINGH DEGREE COLLEGE",
      "Kishni Mahavidyalaya",
      "Kishorenagar College",
      "Kishori Lal Mahavidyalaya Naini",
      "Kishori Raman Postgraduate College",
      "KISHORI RAMAN TEACHER TRAINING COLLEGE",
      "KISHORI RAMAN TEACHER TRAINING COLLEGE",
      "Kishori Sinha Mahila College",
      "KISHORI VIDYALAYA P.G. COLLEGE",
      "KISNI MAHAVIDYALAYA",
      "KISSAN SABHA TRUST",
      "KISSAN TEACHER TRAINING COLLEGE",
      "KIT's Institute of Management Education & Research",
      "Kite Polytechnic",
      "Kittel Arts College",
      "Kittel Science College",
      "Kitter Rani Channamma Education Society'S Law Coll",
      "KJ Institute Of Engineering And Technology",
      "KJ Mehta General Hospital College Of Medical Sciences Amargadh",
      "KJ Somaiyya Medical College & Research Centre, Mumbai",
      "KJSomaiya Centre for Buddhist Studies",
      "Kk Shah Jarodwala Maninagar Science College",
      "KK Wagh Institute of Engineering Education and Research, Nashik",
      "KKC Institute of PG Studies",
      "KKC Institute Of Technology and Engineering",
      "KKECS B.ED COLLEGE",
      "KKECS Institute of Management",
      "KLE Dr. MS Sheshgiri College of Engineering and Technology",
      "KLE Societys G.S.K. Law College",
      "KLE Societys Institute of Dental Sciences , Bangalore",
      "KLE Societys Institute of Management Studies and Research",
      "KLE SOCIETYS S.S. BASAVANAL TEACHER TRAINING INSTITUTE",
      "KLE University",
      "KLE Vishwanath Katti Institute of Dental Sciences , Belgaum",
      "Kle's B.V. Bellad Law College",
      "KLES College of Engineering and Technology",
      "Kles Gogte College Commerce",
      "KLES KLE Institute of Technology",
      "Kless Basavaprabhu Kore Arts Science Commerce College",
      "Kless G I B Arts Science Commerce College",
      "Kless Gurusiddappa Kotambri Law College",
      "Kless Jagadguru Tontadarya College",
      "Kless S K Arts And H A S K Science Institurte",
      "Kless S.A. Manvi Law College",
      "Kless V.S. Bellubi Arts And Commerce College",
      "KLN College of Information Technology",
      "KLR College of Engineering and Technology",
      "KLS Gogte Institute of Technology",
      "Km. Mayawati Govt. Girls Polytechnic, Badalpur",
      "KMCH College of Pharmacy , Coimbatore",
      "KMCT College of Engineering,",
      "KMCT Dental College , Kozhikode",
      "KMCT Medical College,Kozhikode, Calicut",
      "KMCT TEACHER TRAINING INSTITUTE",
      "KMG Polytechnic College",
      "KMKG TEACHER TRAINING INSTITUTE",
      "KMM COLLEGE OF ARTS & SCIENCE",
      "KNGD Modi Engineering College",
      "KNNWAY TEACHER TRAINING COLLEGE",
      "Knowledge Age Academy of Research and Education (KARE)",
      "Knowledge Business School",
      "Knowledge Gurukul Institute of Business Management",
      "Knowledge Institute of Technology",
      "KNS Institute of Technology",
      "KNS World Management College",
      "KNSK College Of Engineering",
      "Kodachadri Government First Grade College",
      "Kodada Institute Of Information For Women",
      "Kodada Institute of Technology and Science for Women",
      "Kodaikanal Christian College",
      "Kodaikanal Institute of Technology",
      "KODUVALLY MUSLIM ORPHANAGE TEACHER TRAINING INSTITUTE",
      "KOHETOOR D ED COLLEGE",
      "Kohima College",
      "Kohima Law College",
      "Kohinoor Business School, Khandala",
      "Kokan Women Students Developmental central Society",
      "Kokrajhar College",
      "Kokrajhar Law College",
      "Kol Valley Institute Of Nursing , Bilaspur",
      "KOLANDHAVEL TEACHER TRAINING INSTITUTE",
      "Kolasib College",
      "Kolhapur District Chemists Assoc., Instt. of Pharmacy , KOLHAPUR",
      "Kolhapur Instt.Of Tech's Col Of Engg",
      "Kolkata Girls B.T. College",
      "Kolkata Girls College",
      "Kolkata Teacher's Training College",
      "Kolkatta Port Trust School Of Nursing , Kolkatta",
      "Kommuri Pratap Reddy Institute of Technology",
      "Konagar Nadu Nursing And Inst Of Medical Technology , Thiruvidaimaruthur",
      "Konark Inst Of Sci & Tech",
      "Konark Institute of Science and Technology",
      "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram",
      "Konathala Arts & Science Degree College",
      "Konduraiah Narsaiah Memorial Degree College",
      "Koneru Lakshmaiah College Of Engineering",
      "Konghu Velalar Polytechnic College, Perundurai",
      "Kongu Arts And Science College",
      "Kongu College Of Arts & Science",
      "Kongu Engineering College",
      "Kongu HI-Tek Polytechnic College",
      "KONGU NAADU COLLEGE OF EDUCATION",
      "Kongu Polytechnic College",
      "Kongu Polytechnic College, Perundurai",
      "Kongunadu Arts & Science College",
      "KONGUNADU COLLEGE OF EDUCATION",
      "KONGUNADU COLLEGE OF EDUCATION",
      "Kongunadu College of Engineering and Technology",
      "Kongunadu College Of Nursing , Coimbatore",
      "Kongunadu Polytechnic College",
      "KONKAN AGRICULTURE EDUCATION AND RESEARCH INSTITUTE",
      "Konkan Education & Medical Trusts Virar Homoeopathic Medical College",
      "Konkan Education Society's Engineering College",
      "Konkan Education Societys Anandbai Pradhan Science College",
      "Konkan Gyanpeeth Uran College Of Commerce & Arts",
      "Konkan Gyanpith's College Of Engg",
      "KONNIYOOR MEENAKSHI AMMA MEMORIAL TTI",
      "Kooba Degree College",
      "KOOLIPPULAKKAL PATHUMMAKUTTY MEMORIAL TTI",
      "KOPAL COLLEGE FOR EXCELLENCE",
      "Kopal Institute of Science & Technology,Bhopal",
      "KORBA CITY COLLEGE",
      "Koringa College of Pharmacy, Koringi",
      "Koshala Anm Training School , Sambalpur",
      "Koshi College",
      "Koshys College Of Nursing , Bangalore",
      "Koshys Institute of Management Studies",
      "Koshys School Of Nursing , Bangalore",
      "KOTA COLLEGE OF EDUCATION",
      "Kota Open University",
      "KOTA OPEN UNIVERSITY",
      "Kota Polytechnic College",
      "KOTA TEACHER TRAINING COLLEGE",
      "Kotha Kota Sri Vidya Degree College",
      "Kothagudem School Of Mines",
      "Kothari Medical & Research Institute, S N , School Of Nursing, Bikaner",
      "Kothiwal Arhatia Mahavidyalaya",
      "Kothiwal Dental College & Research Centre , Moradabad",
      "Kotpad College",
      "Kottai Mariyamman Polytechnic College",
      "KOTTALUMOODU A.B.D. COLLEGE EDUCATION",
      "Kottam College of Engineering",
      "KOTTAM INSTITUTE OF ADVANCED STUDIES",
      "Kottam Karunakara Reddy Institute of Technology",
      "Kottureshwar College",
      "Kotturswamy College Of Education",
      "KOTTURSWAMY COLLEGE OF EDUCATION",
      "Koustav Institute Of Self Domain",
      "Koustav School of Enginering",
      "Koustuv Business School",
      "Koustuv Institute of Self Domain",
      "Kovai Kalaimagal College Of Arts And Science",
      "KOVILOOR ANDAVAR COLLEGE OF PHYSICAL EDUCATION",
      "KOYANA EDUCATION SANSTHAS COLLEGE OF EDUCATION (B ED COLLEGE )",
      "Koyili College Of Nursing , Kannur",
      "Koyili Hospital ,Cannanore",
      "KPE SOCIETYS TEACHER TRAINING INSTITUTE",
      "KPS Institute of Polytechnic",
      "Kr. Devendra Pal Singh (Memorial) Degree College",
      "KR. DEVENDRA PAL SINGH (MEMORIAL)DEGREE COLLEGE",
      "KR. R.C. MAHILA COLLEGE",
      "Kranthi Arts & Science Degree College",
      "Kranti Nursing School, Ahmednagar",
      "Kranti Nursing Training Institute,Ahmednagar",
      "Krantiagrani G D Bapu Lad School Of Nursing,miraj",
      "KRANTIVEER SANGOLLI RAYANNA COLLEGE OF EDUCATION",
      "KRANTIVEERA SANGOLI RAYANNA COLLEGE OF PHYSICAL EDUCATION.",
      "Krce Societies College Of Education",
      "KRD College of Education",
      "KRE SOCIETY M.ED PG CENTRE",
      "Kreda School Of Nursing , Bangalore",
      "Kripalu Institute Of Biomedical Sciences And Research , Raebareli",
      "Kripalu Institute Of Biomedical Sciences,Bareli",
      "Kripalu Mahila Mahavidyalaya",
      "Krishak College",
      "Krishak Degree College",
      "KRISHAK DEGREE COLLEGE",
      "KRISHAK MAHAVIDYALAYA",
      "KRISHAK MAHAVIDYALAYA",
      "KRISHAK MAHAVIDYALAYA",
      "Krishan Law College",
      "KRISHANA INSTITUTE OF MANGEMENT,KITHOLL",
      "Krishi Degree College",
      "Krishinchand Chellaram College",
      "KRISHMA EDUCATIONAL CENTRE",
      "KRISHNA ACADEMY",
      "KRISHNA ADARSH TEACHER TRAINING COLLEGE",
      "Krishna Bora B.Ed. College",
      "Krishna Chaitanya Institute Of Science & Tech",
      "Krishna Chandra College",
      "Krishna Charitable Trust Krishna College of Pharmacy , Satara",
      "KRISHNA COLLEGE OF EDUCATION BHARATH EDUCATION TRUST",
      "KRISHNA COLLEGE OF EDUCATION FOR WOMEN",
      "Krishna College of Law",
      "Krishna College Of Nursing,Mysore",
      "Krishna College of Pharmacy , Bijnor",
      "KRISHNA COLLEGE OF SCIENCE & INFORMATION TECHNOLOGY",
      "KRISHNA COLLEGE OF SCIENCE & RURAL TECHNOLOGY",
      "KRISHNA COLLEGE OF SCIENCE AND INFORMATION TECHNOLOGY",
      "KRISHNA COLLEGE OF SCIENCE RURAL TECHNOLOGY",
      "KRISHNA COLLEGE OF SCIENCES & INFORMATION TECHNOLOGY",
      "KRISHNA COLLEGE OF SPORTS & EDUCATION",
      "Krishna Degree College, Visakhapatnam",
      "Krishna Dental College , Ghaziabad",
      "Krishna Devi Girls Degree College",
      "Krishna Engineering College",
      "Krishna Foundation College of Pharmacy , Karad",
      "KRISHNA GIRLS ACADEMY",
      "Krishna Girls Engineering College, Kanpur",
      "Krishna Hosp. & Medical Research Centre , School Of Nursing, Karad",
      "Krishna Hospital School Of Nursing, , Cuddalore",
      "KRISHNA INSTITUTE OF EDUCATION & MANAGEMENT",
      "Krishna Institute Of Engineering and Technology",
      "Krishna Institute of Law",
      "KRISHNA INSTITUTE OF MANAGEMENT",
      "Krishna Institute Of Medical Sciences",
      "Krishna Institute Of Medical Sciences , Satara",
      "Krishna Institute Of Medical Sciences , Secunderabad",
      "Krishna Institute of Medical Sciences, Karad",
      "Krishna Institute Of Nursing Science And Research ,Kanpur",
      "Krishna Institute Of Nursing Sciences , Satara",
      "Krishna Institute Of Nursing, Bhilwara",
      "KRISHNA INSTITUTE OF RDUCATION & TECHNOLOGY",
      "KRISHNA INSTITUTE OF TEACHERS EDUCATION",
      "Krishna Institute of Technology & Engineering",
      "Krishna Kanta Handique Government Sanskrit College",
      "Krishna Kanta Handique State Open University",
      "Krishna Mahavidyalaya",
      "KRISHNA MAHAVIDYALAYA",
      "KRISHNA MAHILA TEACHERS TRAINING COLLEGE",
      "Krishna Menon Memorial Government Womens College",
      "Krishna Murthy Institute of Management",
      "Krishna Murthy Institute of Technology & Engineering",
      "Krishna Nursing & Paramedical Institute , Lucknow",
      "KRISHNA PAL SINGH DEGREE COLLEGE",
      "KRISHNA PATEL DEGREE COLLEGE ROHUVAR",
      "Krishna Polytechnic",
      "Krishna Sarada Degree College",
      "Krishna School Of Nursing , Chitradurga",
      "KRISHNA SUDAMA MAHAVIDYALAYA",
      "KRISHNA TEACHER TRAINING INSTITUE",
      "KRISHNA TEACHER TRAINING INSTITUTE",
      "KRISHNA TEACHER TRAINING INSTITUTE",
      "KRISHNA TEACHER TRAINING INSTITUTE",
      "Krishna Teja Degree College, Tirupti",
      "Krishna University",
      "Krishnadevaraya College of Dental Sciences & Hospital , Bangalore",
      "Krishnadevi Maheshwari Pharmacy College , Jhunjhunu",
      "Krishnagar Government College",
      "Krishnagar Womens' College",
      "Krishnai Shikshan Prasarak Mandal Latur's Janvikas",
      "KRISHNAI SHIKSHAN PRASARAK MANDALS COLLEGE OF EDUCATION",
      "Krishnanagar B.Ed. College",
      "Krishnapur Primary Teacher's Training Institute",
      "KRISHNASAGARA TEACHERS TRAINING COLLEGE",
      "KRISHNASAMY COLLEGE OF EDUCATION FOR WOMEN",
      "Krishnasamy College of Engineering & Technology",
      "Krishnasamy Memorial Polytechnic College",
      "Krishnath College",
      "KRISHNAVENI AMMAL COLLEGE OF EDUCATION",
      "Krishnaveni College Of Nursing,Guntur",
      "Krishnaveni Degree College",
      "Krishnaveni Degree College, Kothagudem",
      "Krishnaveni Exhibition Society Polytechnic for Women , Vijayawada",
      "KRISHNAVENI INST. OF TECHNOLOGY",
      "Krist Raja School Of Nursing , Godda",
      "Kristu Jayanti College",
      "KRISTU JAYANTI COLLEGE OF MANAGEMENT AND TECH",
      "Kristu Jayanti School Of Nursing,Kollam",
      "KRISTU JYOTHI COLLEGE OF MANAGEMENT AND TECHNOLOGY",
      "KRN Institute of Technology",
      "KRS College Of Engineering",
      "Krs Institute Of Paramedical Sciences And Nursing , Gonda",
      "Krupajal Business School,Bhubaneswar",
      "Krupajal Engg. School",
      "Krupajal Management Studies, Bhubaneswar",
      "Krupajala Engineering College",
      "Krupanidhi College Of Nursing,Bangalore",
      "Krupanidhi College of Pharmacy , Bangalore",
      "Krupanidhi Education Trust School Of Nursing , Bangalore",
      "Kruti Institute of Technology and Engineering",
      "KS Institute Of Technology,",
      "KS School of Engineering and Management",
      "KSGH Music and Performing Arts University",
      "Kshatriya College of Engineering",
      "Kshetramohan Science College",
      "KSLUs Law School",
      "KSR College of Engineering",
      "KSRM College of Engineering",
      "KSV University",
      "KT Reddy Women's College",
      "KTCT COLLEGE OF TEACHER EDUCATION",
      "KTVR Knowledge Park for Engineering and Technology",
      "KU SCHOOL OF ENGINEERING AND TECHNOLOGY",
      "Kuchaman College",
      "KUCHAMAN TEACHER TRAINING COLLEGE",
      "Kuchinda College",
      "Kudaravali Anjaiah Memorial (Kam) & Sree Sai Degree College",
      "Kudiram Bose Central College",
      "Kugler College Of Nursing,guntur",
      "Kugler Hospital School Of Nursing , Kothapet",
      "Kujanga College",
      "Kukke Sri Subrahmanyeshwara College",
      "Kukreja Institute of Hotel Management & Catering Technology",
      "KUKREJE INSTITUTE OF TEACHERS EDUCATION",
      "KULAMUDIYIL NEELAKANDAN NAIR MEMORIAL TTI",
      "Kular College Of Nursing , Ludhiana",
      "Kular School Of Nursing , Ludhiana",
      "Kulbhaskar Ashram Degree PG College",
      "KULLU TEACHER TRAINING COLLEGE",
      "Kulti Degree College",
      "Kum M.H.Gardi School of Management",
      "KUM. M.H. GARDI SCHOOL OF MANAGEMENT",
      "KUMADVATHI COLLEGE OF EDUCATION",
      "Kumadwathi College Of Education",
      "Kumaon University",
      "KUMARA RAJA TEACHER TRAINING INSTITUTE FOR WOMEN",
      "Kumara Rani Meena Muthiah College Of Arts & Science For Women",
      "Kumaraguru College of Technology",
      "KUMARAN ASHRAM MEDICAL TRUST TEACHER TRAINING INSTITUTE",
      "Kumaran Institute Of Technology",
      "Kumaran Polytechnic College",
      "Kumaran Polytechnic College",
      "Kumaran School Of Nursing,Vellore",
      "KUMARANASAN SMARAKA TEACHER TRAINING INSTITUTE",
      "Kumari Mayawati Government Mahila Mahavidyalaya",
      "KUMARI MONIKA BASAVARA KANNI B.ED COLLEGE",
      "Kumaun University",
      "Kumbhalkar College of Social Work",
      "Kumbi College",
      "Kumud Singh Mahavidyalaya",
      "Kumud Singh Mahavidyalaya Masuripur",
      "Kumuda College Of Nursing, Davangere",
      "Kumuda Institute Of Nursing Sciences , Davangere",
      "Kumuda School Of Nursing , Davangere",
      "KUMUDA UMASHANKAR TEACHER TRAINING INSTITUTE",
      "KUMUTHA COLLEGE OF EDUCATION",
      "KUNBI SHIKSHAN PRASARAK SANTHA COLLEGE OF EDUCATION",
      "KUNDAPURA TEACHERS TRAINING INSTITUTE",
      "Kundavai Nachiyar Government College For Women",
      "Kundavaii School Of Nursing, Thanjavur",
      "KUNHAHAMMED MASTER MEMORIAL COLLEGE OF TECHER EDUCATION",
      "KUNHATHUMMA MEMORIAL COLLEGE OF TEACHER EDUCATION",
      "Kunja BIHARi College",
      "KUNJU KRISHNAN NADAR MEMORIAL COLLEGE",
      "Kuntala Devi School Of Nursing , Nayagarh",
      "Kuntala Devi School Of Nursing , Odisha",
      "Kunthidevi Mahilabhyudaya School Of Nursing , Eluru",
      "Kunwar Haribansh Singh Institute Of Nursing & Paramedicals , Jaunpur",
      "Kunwar Haribansh Singh Institute Of Nursing & Paramedicals,Jaunpur",
      "Kunwar R.C. Mahila Degree College",
      "KUNWAR RAM BHAROSA SINGH MAHAVIDYALAYA",
      "Kunwar Singh PG Degree College",
      "Kuppam Engineering College",
      "kuppam engineering college",
      "Kureseong College",
      "Kuriakose  Gregorios College",
      "Kuriakose Elias College",
      "Kurinji Arts & Science College",
      "Kurinji College of Engineering and Technology",
      "KURINJI TEACHER TRAINING INSTITUTE",
      "Kurji Holy Family Hospital , Patna",
      "Kurnool Degree College",
      "Kurnool Medical College",
      "Kurnool Medical College, Kurnool",
      "Kurukshetra Polytechnic & Research Centre",
      "Kurukshetra University",
      "Kurukshetra. Institute of Technology & Management,",
      "Kurundwad Institute Of Nursing Education,Kolhapur",
      "KURUSHETRA UNIVERSITY",
      "Kusaleswar Anchalik Mahavidyalaya",
      "Kusha Bhao Thakre Nursing College , Bhopal",
      "Kusha Bhau Thakre Nursing College , Bhopal",
      "Kusha Bhau Thakre Nursing College , Kolam",
      "Kusha Bhau Thakre School Of Nursing",
      "Kushabhau Thakre Composite Regional Centre for Persons with Disabilities",
      "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
      "KUSHAGRA INSTITUTE OF INFORMATION & MANAGEMENT SCIENCE",
      "Kusum Gupta & Associates , Solan",
      "Kusumbai Jain Girls Degree College",
      "Kutir PG College",
      "KUTIR POST GRADUATE COLLEGE",
      "KUVEMPU D ED COLLEGE",
      "Kuvempu University",
      "KUVEMPU UNIVERSITY",
      "KV Institute of Management Studies and Information Studies",
      "KV Polytechnic",
      "KVG College of Engineering",
      "KVM College of Engineering and Information Technology",
      "KVM TEACHER TRAINING COLLEGE",
      "KVSR Siddhartha College of Pharmaceutical Sciences , Vijayawada",
      "KVVS Institute of Technology",
      "KYASA  INSTITUTE OF  MANAGEMENT STUDIES",
    ],
  },
];
