const PData = [
  {
    colleges: [
      "P & T Patel Institute Of Nursing - Gujarat",
      "P A C Ramasamy Raja Polytechnic College - Tamil Nadu",
      "P A College of Engineering and Technology - Tamil Nadu",
      "P A Polytechnic - Karnataka",
      "P B N College - Andhra Pradesh",
      "P B S College - Bihar",
      "P B Sidhartha College Arts Science - Andhra Pradesh",
      "P C G M School Of Nursing - Karnataka",
      "P C Vigyan Mahavidyalaya - Bihar",
      "P D Hinduja National Hospital & Mrc College Of Nursing - Maharashtra",
      "P D M College Commerce - Gujarat",
      "P D M Graduate Teachers College - Gujarat",
      "P D M S School Of Nursing - Uttar Pradesh",
      "P D M Subharati K Nursing School - Uttar Pradesh",
      "P D Pandya Mahila Commerce College - Gujarat",
      "P E S College Of Nursing - Andhra Pradesh",
      "P E S Institute Of Medical Sciences and Research - Andhra Pradesh",
      "P E S Polytechnic - Karnataka",
      "P E S Polytechnic Evening College - Karnataka",
      "P E S School Of Nursing - Andhra Pradesh",
      "P E T Polytechnic - Karnataka",
      "P G College Godwal - Andhra Pradesh",
      "P G College Medak - Andhra Pradesh",
      "P G College Mehboobnagar - Andhra Pradesh",
      "P G College Mirzapur - Andhra Pradesh",
      "P G College Nalgonda - Andhra Pradesh",
      "P G College Nizamabad - Andhra Pradesh",
      "P G College Of Nursing - Chhattisgarh",
      "P G College Osmania University - Andhra Pradesh",
      "P G College Science - Andhra Pradesh",
      "P G College Siddipet - Andhra Pradesh",
      "P G College Vikrabad - Andhra Pradesh",
      "P G P College Of Nursing & Research ,Namakkal - Tamil Nadu",
      "P G P College Of Nursing , Namakkal - Tamil Nadu",
      "P G P INSTITTUTE OF TEACHERE TRAINING - Tamil Nadu",
      "P G P Polytechnic College - Tamil Nadu",
      "P G School Of Nursing , Hassan - Karnataka",
      "P G School Of Nursing ,Malappuram - Kerala",
      "P Gee Varghese School Of Nursing , Kottayam - Kerala",
      "P Indra Reddy Memorial Engineering College - Andhra Pradesh",
      "P K Roy Memorial College - Jharkhand",
      "P K Technical Campus, Pune - Maharashtra",
      "P L Singh College - Bihar",
      "P M S College - Bihar",
      "P M S School Of Nursing , Bangalore - Karnataka",
      "P N C & K R College Of Nursing,GUNTUR - Andhra Pradesh",
      "P N C & K R School Of Nursing , Guntur - Andhra Pradesh",
      "P N C K R Degree College - Andhra Pradesh",
      "P N College - Bihar",
      "P N M School Of Nursing,Trivandrum - Kerala",
      "P N P Memorial Hindu Medical Mission Hospital , School Of Nursing,Kottayam - Kerala",
      "P P G COLLEGE OF EDUCATION WOMEN - Tamil Nadu",
      "P P G College Of Nursing , Coimbatore - Tamil Nadu",
      "P P G School Of Nursing, Saravanampatty - Tamil Nadu",
      "P P K College - Jharkhand",
      "P R College Of Nursing , Bangalore - Karnataka",
      "P R College Of Nursing,Bangalore - Karnataka",
      "P R Government College Evening Courses - Andhra Pradesh",
      "P R R Memorial Engineering College - Andhra Pradesh",
      "P R R V S Government College - Andhra Pradesh",
      "P R S College Of Nursing - Kerala",
      "P R S School Of Nursing - Kerala",
      "P S C K V S C Government College - Andhra Pradesh",
      "P S College Of Nursing - Tamil Nadu",
      "P S G COLLEGE OF EDUCATION - Tamil Nadu",
      "P S G College Of Nursing - Tamil Nadu",
      "P S N L COLLEGE OF EDUCATION - Tamil Nadu",
      "P S N R A M Polytechnic College For Girls - Tamil Nadu",
      "P S R Polytechnic College - Tamil Nadu",
      "P S V COLLEGE OF EDUCATION - Tamil Nadu",
      "P Science College - Bihar",
      "P T Sarvajanik College Science - Gujarat",
      "P V A Ekka M College - Jharkhand",
      "P V College Of Nursing - Andhra Pradesh",
      "P V K N Government College - Andhra Pradesh",
      "P V M D ED COLLEGE - Karnataka",
      "P V Polytechnic College - Tamil Nadu",
      "P V R Trust Degree College - Andhra Pradesh",
      "P V S Anm School - Karnataka",
      "P V S Anm School",
      "P V S College Of Nursing - Kerala",
      "P V S College Of Nursing - Karnataka",
      "P V S School Of Nursing - Karnataka",
      "P V S School Of Nursing - Karnataka",
      "P V S School Of Nursing - Kerala",
      "P. A. College of Engineering - Karnataka",
      "P. D. Bharatesh College Of Nursing - Karnataka",
      "P. E. S. Law College - Karnataka",
      "P. K. Institute of Technology & Management - Uttar Pradesh",
      "P. K. M. COLLEGE OF EDUCATION - Kerala",
      "P. Rami Reddy Memorial College of Pharmacy - Andhra Pradesh",
      "P. Satyanarayana Rao Memorial Degree College - Andhra Pradesh",
      "P. V. P. Polytechnic - Karnataka",
      "P.A Aziz College of Engineering and Technology - Kerala",
      "P.A. College of Engineering - Karnataka",
      "P.A.C. Ramasamy Raja'S Polytechnic College - Tamil Nadu",
      "P.B. College of Engineering - Tamil Nadu",
      "P.C Jabin Science College - Karnataka",
      "P.C. BANGLA COLLEGE - Uttar Pradesh",
      "P.C. Pratap Chandra Memorial Homoeopathic Medical College and Hospital - West Bengal",
      "P.C.M.S.D. College for Women - Punjab",
      "P.D. Law College - Uttar Pradesh",
      "P.D. Mahila Degree College - Uttar Pradesh",
      "P.D. MAHILA DEGREE COLLEGE - Uttar Pradesh",
      "P.D. RAJAN COLLEGE OF EDUCATION - Tamil Nadu",
      "P.D.E.As College Of Engg - Maharashtra",
      "P.D.M. TEACHER TRAINING COLLEGE - Haryana",
      "P.D.Memorial Polytechnic - Haryana",
      "P.D.R. VELLACHIAMMAL COLLEGE EDUCATION - Tamil Nadu",
      "P.E.S COLLEGE OF EDUCATION - Karnataka",
      "P.E.S Institute of Medical Science And Research - Andhra Pradesh",
      "P.E.S Law College - Karnataka",
      "P.E.S. College of Engineering - Karnataka",
      "P.E.S. College Of Physical Education - Maharashtra",
      "P.E.S. College Of Science - Karnataka",
      "P.E.S. Degree College - Andhra Pradesh",
      "P.E.S. Evening College - Karnataka",
      "P.E.S. Instt. of Pharmacy - Karnataka",
      "P.E.S. INSTT. OF TECH - Karnataka",
      "P.E.S. Law College - Karnataka",
      "P.E.S. Modern College of Arts Science and Commerce - Maharashtra",
      "P.E.S. Modern Law College - Maharashtra",
      "P.E.S. Polytechnic - Maharashtra",
      "P.E.T. TEACHERS TRAINING INSTITUTE - Karnataka",
      "P.E.TS DIPLOMA IN EDUCATION COLLEGE - Karnataka",
      "P.G DEPARTMENT OF MANAGEMENT STUDIES - Tamil Nadu",
      "P.G. College of Law - Andhra Pradesh",
      "P.G. College Of Science, Secunderabad - Andhra Pradesh",
      "P.G. Vigyan Mahavidyalaya - Madhya Pradesh",
      "P.G.CENTRE - Karnataka",
      "P.G.D.A.V. College - Delhi",
      "P.G.D.A.V. College (Evening) - Delhi",
      "P.G.M TEACHER TRAINING INSTITUTE - Kerala",
      "P.G.P. College Of Arts And Science - Tamil Nadu",
      "P.G.P. Polytechnic College - Tamil Nadu",
      "P.H. COLLEGE OF EDUCATION - Uttar Pradesh",
      "P.I.E.T. COLLEGE OF EDUCATION - Uttar Pradesh",
      "P.Indra Reddy Memorial engineering College - Andhra Pradesh",
      "P.J. COLLEGE OF MANAGEMENT & TECHNOLOGY - Orissa",
      "P.K.D.COLLEGE OF EDUCATION - Tamil Nadu",
      "P.K.M. College Of Education - Kerala",
      "P.K.N. Arts And Science College - Tamil Nadu",
      "P.K.R. Arts College For Women - Tamil Nadu",
      "P.K.R. JAIN TEACHER TRAINING COLLEGE - Haryana",
      "P.L.DUBEY MEMORIAL TEACHER TRAINING COLLEGE - Rajasthan",
      "P.M. Polytechnic - Haryana",
      "P.M.B. Gujarati Arts And Law College - Madhya Pradesh",
      "P.M.B. Gujarati Commerce College - Madhya Pradesh",
      "P.M.B. Gujarati Science College - Madhya Pradesh",
      "P.M.C. TEACHER TRAINING COLLEGE - Delhi",
      "P.M.N. Degree College - Andhra Pradesh",
      "P.M.N.M. Dental College & Hospital - Karnataka",
      "P.M.P. College Of Arts And Science - Tamil Nadu",
      "P.N. Das College - West Bengal",
      "P.N.B. Polytechnic College - Rajasthan",
      "P.N.C.A. Degree College - Andhra Pradesh",
      "P.P.College Of Education - Maharashtra",
      "P.P.G. College of Physiotherapy - Tamil Nadu",
      "P.R. Arts And Science College - Tamil Nadu",
      "P.R. PATIL COLLEGE OF EDUCATION (B.ED.) - Maharashtra",
      "P.R. Pote Education & Welfare Trust - Maharashtra",
      "P.R. Rajkiya Mahila Mahavidyalaya - Uttar Pradesh",
      "P.R.B.S. College of Polytechnic - Haryana",
      "P.R.D. TEACHER TRAINING COLLEGE - Haryana",
      "P.R.N.TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "P.R.Patil Instittute Of Polytechnic - Maharashtra",
      "P.R.R. INSTITUTE OF MANAGEMENT SCIENCES - Andhra Pradesh",
      "P.R.R.M. Institute Of Technolgy - Andhra Pradesh",
      "P.S. Raju College of Law - Andhra Pradesh",
      "P.S.B. Polytechnic College - Tamil Nadu",
      "P.S.D. Girls Law College - Haryana",
      "P.S.G Institute of Medical Sciences - Tamil Nadu",
      "P.S.G. Arts & Science College - Tamil Nadu",
      "P.S.G. College of Paramedical Sciences - Tamil Nadu",
      "P.S.G. INSTITUTE OF MANAGEMENT - Tamil Nadu",
      "P.S.G. Polytechnic College - Tamil Nadu",
      "P.S.G. PONNAMMAL TEACHERS TRAINING INSTITUTE - Tamil Nadu",
      "P.S.G.R. Krishnammal College For Women - Tamil Nadu",
      "P.S.G.V.P. Mandal Institute of Pharmacy - Maharashtra",
      "P.S.I Medical College - Andhra Pradesh",
      "P.S.MUTHU PHYSICAL EDUCATION TEACHER TRAINING INSTITUE - Tamil Nadu",
      "P.S.N. Murthy Degree College - Andhra Pradesh",
      "P.S.N. Polytechnic College - Tamil Nadu",
      "P.S.R. Engineering College - Tamil Nadu",
      "P.S.R.COLLEGE OF EDUCATION - Tamil Nadu",
      "P.S.R.Rengasamy College of Engineering for Women - Tamil Nadu",
      "P.S.Raju. Law College - Andhra Pradesh",
      "P.S.S.K. EDUCATIONAL TRUST - Karnataka",
      "P.S.S.R. College Of Arts And Science - Andhra Pradesh",
      "P.S.T. Channabasweshwar Pharmacy College - Maharashtra",
      "P.S.V. College of Engineering & Technology - Tamil Nadu",
      "P.S.Y. COLLEGE OF EDUCATION - Tamil Nadu",
      "P.T. Lee Chengalvaraya Naicker College of Engineering & Technology - Tamil Nadu",
      "P.T. Lee Chengalvaraya Naicker Polytechnic College - Tamil Nadu",
      "P.T.M COLLEGE OF EDUCATION - Kerala",
      "P.T.M. TEACHER TRAINING INSTITUTE - Kerala",
      "P.V. Krishna Kishore (Pvkk) Degree College - Andhra Pradesh",
      "P.V. Polytechnic - Maharashtra",
      "P.V. Polytechnic College - Tamil Nadu",
      "P.V.DEGREE COLLEGE - Uttar Pradesh",
      "P.V.S.EDUCAION AND RUR DEVELOPMENT SOCIETY - Karnataka",
      "P.W. Medical College Patna - Bihar",
      "P.W.S. Arts & Commerce College - Maharashtra",
      "PA Aziz College of Engineering & Technology - Kerala",
      "PA Polytechnic College - Tamil Nadu",
      "Paavaai Group of Institutions - Tamil Nadu",
      "PAAVAI COLLEGE OF EDUCATION - Tamil Nadu",
      "Paavai College of Engineering - Tamil Nadu",
      "Paavai College of Technology - Tamil Nadu",
      "Paavai Engineering College - Tamil Nadu",
      "Paavai Polytechnic College - Tamil Nadu",
      "Paavendhar College Of Arts And Science - Tamil Nadu",
      "Paavendhar Polytechnic College - Tamil Nadu",
      "PAAVENTHAR TEACHER TRAINING COLLEGE - Pondicherry",
      "Pabbu Madhusudhan Rao Degree College - Andhra Pradesh",
      "Pabitra Mohan Institute of Technology - Orissa",
      "PACE Institute Of Technology & Sciences - Andhra Pradesh",
      "Pachaiyappas College For Men - Tamil Nadu",
      "Pachaiyappas College For Men - Tamil Nadu",
      "Pachaiyappas College For Women- Tamil Nadu",
      "Pachaiyappas College, Kanchipuram - Tamil Nadu",
      "PACHAMUTHU COLLEGE OF EDUCATION - Tamil Nadu",
      "Pachhunga University College - Mizoram",
      "Pacific Academic of Higher Education Research University - Rajasthan",
      "PACIFIC COLLEGE OF TEACHER EDUCATION - Rajasthan",
      "Pacific Dental College & Hospital - Rajasthan",
      "Pacific Institute of Hotel Management - Rajasthan",
      "PACIFIC INSTITUTE OF MANAGEMENT - Rajasthan",
      "Pacific School of Engineering - Gujarat",
      "Pad. Dr Vithalrao Vikhe Patil Foundations College Of Nursing - Maharashtra",
      "PAD. DR. D.Y. PATIL INSTITUTE OF MANAGEMENT STUDIES - Maharashtra",
      "Pad. Dr. Vithalrao Vikhe Patil Foundation - Maharashtra",
      "Padala Ram Reddy Law College - Andhra Pradesh",
      "Padala Rama Reddi Degree College - Andhra Pradesh",
      "PADALA RAMA REDDY COLLEGE OF COMMERCE & MGT - Andhra Pradesh",
      "Padala Rama Reddy Law College - Andhra Pradesh",
      "Padalesuwarar Polytechnic College - Tamil Nadu",
      "Padalesuwarar Polytechnic College - Tamil Nadu",
      "Padam Shri Nursing Institute - Rajasthan",
      "PADAMASHREE DR.D.Y.PATIL INSTITUTE OF MANAGEMENT - Maharashtra",
      "Padamshree Institute of Management & Sciences - Karnataka",
      "Padma Chandra College Of Nursing - Andhra Pradesh",
      "PADMA PRIYA DED COL - Karnataka",
      "Padma Shri Dr Sivanthi Aditanar College Of Nursing - Tamil Nadu",
      "Padmabhooshan Vasantdada Patil Institute of Technology - Maharashtra",
      "Padmabhusan Sri N. Ramasamy Iyer Memorial Polytechnic College For Girls - Tamil Nadu",
      "Padmabhushan Dr. Vasantraodada Pail Mahavidyalaya - Maharashtra",
      "Padmabhushan Vasant Dada Patil College - Maharashtra",
      "Padmabhushan Vasantdada PPCollege Of Engg - Maharashtra",
      "Padmabhushan Vasantraodada Patil Institute of Technology - Maharashtra",
      "Padmaja Naidu College Of Music - West Bengal",
      "Padmanabham Narshiman Shetty Annapurnamma College - Andhra Pradesh",
      "Padmanabhan Jayantimala College Arts Science - Tamil Nadu",
      "Padmanava College Of Engineering - Orissa",
      "PADMASHREE COLLEGE OF EDUCATION - Karnataka",
      "PADMASHREE COLLEGE OF EDUCATION - Tamil Nadu",
      "Padmashree College Of Nursing - Karnataka",
      "Padmashree Dr D P Patil College Of Nursing - Maharashtra",
      "Padmashree Dr D Y Patil College Of Nursing - Maharashtra",
      "Padmashree Dr D Y Patil College Of Nursing - Maharashtra",
      "Padmashree Dr D Y Patil Institute Of Engineering & Technology - Maharashtra",
      "Padmashree Dr. D Y Patil Instt Of Nursing Education - Maharashtra",
      "Padmashree Dr. D Y Patil Medical College - Maharashtra",
      "Padmashree Dr. D. Y. Patil College of Law - Maharashtra",
      "Padmashree Dr. D. Y. Patil Institute of Management Studies - Maharashtra",
      "Padmashree Dr. D. Y. Patil Law College - Maharashtra",
      "Padmashree Dr. D.Y. Patil College of Law - Maharashtra",
      "Padmashree Dr. D.Y. Patil Dental College & Hospital - Maharashtra",
      "Padmashree Dr. D.Y. Patil Law College - Maharashtra",
      "Padmashree Dr. D.Y.Patil Medical College - Maharashtra",
      "Padmashree Dr. D.Y.Patil Medical College - Maharashtra",
      "PADMASHREE INSTITUTE OF MGT. STUDIES - Karnataka",
      "Padmashree Institute Of Nursing - Karnataka",
      "Padmashree Kurtartha Acharya College of Engineering - Orissa",
      "Padmashree School Of Nursing - Karnataka",
      "PADMASHRI AJIT WADEKAR COLLEGE OF PHYSCIAL EDUCATION - Maharashtra",
      "Padmashri Dr Vithalrao Vikhe Patil College of Engineering - Maharashtra",
      "Padmashri Dr Vithalrao Vikhe Patil Foundations Medical College - Maharashtra",
      "Padmashri Vikhe Patil College Of Arts Science & Commerce - Maharashtra",
      "Padmasree College Of Nursing - Tamil Nadu",
      "Padmasri Dr.B.V.Raju Institute of Technology - Andhra Pradesh",
      "Padmavani College Of Arts & Science For Women - Tamil Nadu",
      "PADMAVANI COLLEGE OF EDUCATION - Tamil Nadu",
      "Padmavathamma College Of Nursing - Andhra Pradesh",
      "PADMAVATHI COLLEGE OF EDUCATION - Tamil Nadu",
      "PADMAVATHI COLLEGE OF EDUCATION - Tamil Nadu",
      "Padmavathi College Of Nursing - Tamil Nadu",
      "Padmavathi College of Pharmacy - Tamil Nadu",
      "Padmavathi Degree College For Women - Andhra Pradesh",
      "PADMAVATHI INSTITUTE OF TEACHER TRAINING - Tamil Nadu",
      "Padmavathi Mahila Degree College - Andhra Pradesh",
      "Padmavathi School Of Nursing - Andhra Pradesh",
      "Padmavathi School Of Nursing - Tamil Nadu",
      "PADMAVATHY AMMAL COLLEGE OF EDUCATION - Tamil Nadu",
      "Padmavathy College of Physiotherapy - Tamil Nadu",
      "Padmavati College of Pharmacy - Tamil Nadu",
      "PADMAWSTI BAL VIDYAPEETH - Uttar Pradesh",
      "Pailan College of Management & Technology - West Bengal",
      "Pailan Technical Campus - West Bengal",
      "Paithan Nursing School - Maharashtra",
      "PAL COLLEGE OF EDUCATION & MANAGEMENT - Uttaranchal",
      "Pal College Of Nursing And Medical Sciences - Uttaranchal",
      "Pal Collegeof Nursing & Medical Sciences - Uttaranchal",
      "Pal Collegeof Nursing & Medical Sciences - Uttaranchal",
      "PAL RAJENDRA EDUCATION TRUSTS PAL RAJENDRA D.ED. COLLEGE - Maharashtra",
      "Paladugu Parvathi Devi College of Engineering & Technology - Andhra Pradesh",
      "Palamuru University - Andhra Pradesh",
      "PALANIAMMAL TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "PALI EDUCATION SOCIETY - Karnataka",
      "Paliwal Degree College - Uttar Pradesh",
      "Pallagatti Adavappa College Of Arts And Commerce - Karnataka",
      "Pallava Raja College of Engineering - Tamil Nadu",
      "PALLAVAN COLLEGE OF EDUCATION - Tamil Nadu",
      "Pallavan College of Engineering - Tamil Nadu",
      "Pallavan Polytechnic College - Tamil Nadu",
      "Pallavan Polytechnic College - Tamil Nadu",
      "Pallavi Degree College - Andhra Pradesh",
      "Pallerla Hanumanth Rao Memorial Degree College - Andhra Pradesh",
      "Pally Chandan School Of Nursing - Orissa",
      "Pamidi Institute Of Science And Technology - Andhra Pradesh",
      "PAN School of Education - Orissa",
      "Panampilly Memorial Government College - Kerala",
      "PANCHAGANGA SHIKSHAN PRASARAK MANDAL - Maharashtra",
      "PANCHAGIRI PRE PRIMARY TTI - Karnataka",
      "Panchakot Primary Teacher's Training Institute - West Bengal",
      "PANCHAMAVEDA SHIKSHANA SAMSTHE(R) - Karnataka",
      "Panchamukhi Degree College - Andhra Pradesh",
      "Panchanani Nandi Memorial Primary Teacher's Training Institute - West Bengal",
      "Panchayat College - Orissa",
      "Panchayat College - Orissa",
      "Panchayat College - Orissa",
      "Panchayat Samiti - Orissa",
      "Panchayat Samiti College - Orissa",
      "Panchayat Samiti College - Orissa",
      "Panchayat Samiti Degree College - Orissa",
      "Panchayat Smiti College - Orissa",
      "Panchkula Engineering College - Haryana",
      "Panchmi College of Law - Karnataka",
      "Panchmura Mahavidyalaya - West Bengal",
      "Panchsheel Homoeopathic Shikshan Prasarak Mandals Homoeopathic Medical College - Maharashtra",
      "PANCHSHEEL INSTITUTE OF EDUCATION - Haryana",
      "PANCHVATI INSTITUTE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "Pandian Polytechnic College - Tamil Nadu",
      "Pandian Saraswathi Yadav Engineering College - Tamil Nadu",
      "PANDIT BADRI PRASAD SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Pandit Bhagwat Dayal Sharma P.G. Institute Of Medical Sciences - Haryana",
      "Pandit Deen Dayal Upadhyay Government Girls Degree College - Uttar Pradesh",
      "Pandit Deendayal Petroleum University - Gujarat",
      "Pandit Deendayal Upadhayaya Institute for the Physically Handicapped - Delhi",
      "Pandit Deendayal Upadhayaya Institute for the Physically Handicapped (Ministry of Social Justice & E - Delhi",
      "Pandit Deendayal Upadhyay Medical College, Rajkot - Gujarat",
      "Pandit Dindayal Upadhyay Dental College, Solapur - Maharashtra",
      "PANDIT DURGA PRASAD MISHRA SHIKSHA AVAM SAMAJ KALYAN SOCIETY - Madhya Pradesh",
      "PANDIT G.R.MEMORIAL SHIKSHA SHASTRI COLLEGE - Rajasthan",
      "Pandit J.L.Nehru Mahavidyalaya - Maharashtra",
      "PANDIT J.P. UPADHYAY TEACHERS TRAINING COLLEGE - Rajasthan",
      "Pandit Jawahar Lal Nehru Memorial College - Karnataka",
      "PANDIT LAXMI NARAYAN MEMORIAL MAHAVIDYALAYA - Uttar Pradesh",
      "Pandit Moti Lal Nehru Vidhi Mahavidyalaya - Madhya Pradesh",
      "Pandit Panchaxara Gavaigalavar Arts College - Karnataka",
      "Pandit Raghunath Murmu Samritis Mahavidyalaya - West Bengal",
      "Pandit Raghunath Murmu Teacher's Training College - West Bengal",
      "PANDIT RAJPATI MISHRA COLLEGE OF EDUCATION & RESEARCH - Uttar Pradesh",
      "PANDIT RAJPATI MISHRA COLLEGE OF EDUCATION AND RESEARCH - Maharashtra",
      "PANDIT RAM NIWAS MEMORIAL TEACHER TRAINING COLLEGE - Haryana",
      "PANDIT RAMLAL SHARMA EDUCATION COLLEGE - Madhya Pradesh",
      "PANDIT RAMSWROOP DWIVEDI MAHAVIDYALAYA - Uttar Pradesh",
      "Pandit Ravishankar Shukla University - Chhattisgarh",
      "PANDIT SHIV DATTA SHASTRI EDUCATIONAL FOUNDATION'S - Maharashtra",
      "PANDIT SUJAN SINGH DEGREE COLLEGE - Uttar Pradesh",
      "Pandit Sundarlal Sharma University - Chhattisgarh",
      "PANDIT TEJRAM COLLEGE OF EDUCATION - Uttar Pradesh",
      "Pandit Ugam - Bihar",
      "Pandiyan Polytechnic College - Tamil Nadu",
      "Pandu College - Assam",
      "Pandua College of Education - West Bengal",
      "Pandurang Shamrao Mulgaonkar Vishesh Shikshan Adhyapak Mahavidyalaya - Maharashtra",
      "Pandurang Shamrao Mulgaonkar Vishesh Shikshan Adhyapak Mahavidyalaya - Maharashtra",
      "Pandyan College of Pharmacy , Virattipathu - Tamil Nadu",
      "Panihati Mahavidyalaya - West Bengal",
      "Panimalar Engineering College - Tamil Nadu",
      "PANIMALAR INSTITUTE OF MANAGEMENT STUDIES AND COMPUTER SCIENCE - Tamil Nadu",
      "Panimalar Institute of Technology - Tamil Nadu",
      "Panimalar Polytechnic College - Tamil Nadu",
      "PANIMALAR TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Panineeya Mahavidyalaya Institute of Dental Sciences & Research Centre , Hyderabad - Andhra Pradesh",
      "Panipat Institute of Engineering & Technology - Haryana",
      "Panjab University - Punjab",
      "Panna Dai School Of Nursing , Delhi - Delhi",
      "Panna Mahavidyalaya Kushahaon Brahman - Uttar Pradesh",
      "PANNA MAHAVIDYALAYA SHIKSHA SANSTHAN SAMITI - Uttar Pradesh",
      "Pannai College Of Engineering And Technology - Tamil Nadu",
      "Pannaikadu Veerammal Paramasivam College - Tamil Nadu",
      "Pannala Ram Reddy College of Business Management - Andhra Pradesh",
      "Panskura Banamali College - West Bengal",
      "Panskura Banamali College - West Bengal",
      "Panskura Primary Teacher's Training Institute - West Bengal",
      "Parabrahma Speciality Hospital & Research Centre , School Of Nursing, Kollam - Kerala",
      "Paradip College - Orissa",
      "Paradise Polytechnic College, Sikar - Rajasthan",
      "PARADISE TEACHER TRAINING COLLEGE - Haryana",
      "PARADISE TEACHER TRAINING COLLEGE - Haryana",
      "PARADISE TEACHER TRAINING COLLEGE - Punjab",
      "PARAG B.ED. COLLEGE - Maharashtra",
      "PARAGOAN INSTITUTE OF EDUCATION - Uttar Pradesh",
      "Parajang Mahavidyalaya - Orissa",
      "Param Institute of Management & Research - Gujarat",
      "Paramahans Ramakrishna Mauntibaba Sanstha's Anuradha Engineering College - Maharashtra",
      "Paramananda College - Orissa",
      "Parameswar Mahavidyalaya(B.Ed.) - West Bengal",
      "Paramhans Institute of Education - Madhya Pradesh",
      "Paramhans Ramkrishna Mouni Baba Shikshan Sanstha's Anuradha Polytechnic - Maharashtra",
      "PARAMHANS TEACHER TRAINING COLLEGE - Haryana",
      "PARAMOUNT EDUCATION SOCIETY - Haryana",
      "PARAMOUNT INSTITUTE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "Paramount School Of Nursing , Jhajjar - Haryana",
      "PARAMVEER COLLEGE OF EDUCATION - Tamil Nadu",
      "Paramveer Polytechnic College - Tamil Nadu",
      "Paraplegia & Training Centre & Physiotherapy College - Gujarat",
      "PARASAKTHI COLLEGE OF EDUCATION - Tamil Nadu",
      "Parashar Nursing Mahavidyalaya , Bhopal - Madhya Pradesh",
      "Parasnath Kushwaha College - Bihar",
      "Paravathareddy Babulreddy Visvodaya Institute Of Technology - Andhra Pradesh",
      "Parekh Brothers Science College - Gujarat",
      "Parigaon Omprakash Dinodia College - Assam",
      "Parijat Academy Teacher Education Institution - Assam",
      "PARIJAT COLLEGE - Madhya Pradesh",
      "Parijat College , Indore - Madhya Pradesh",
      "Parimal Mitra Smriti Mahavidyalaya - West Bengal",
      "Parimala Pandurangan Polytechnic College - Tamil Nadu",
      "Parimala School Of Nursing, , Tuticorin - Tamil Nadu",
      "PARIMALA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "PARISHKER INSTITUTE OF EDUCATION - Rajasthan",
      "Parisutham Institute of Technology and Science - Tamil Nadu",
      "Paritala Sriramulu Government College - Andhra Pradesh",
      "Paritran College Of Nursing ,Deoghar - Jharkhand",
      "Paritran School Of Nursing , Deoghar - Jharkhand",
      "Parivartan Sewabhavi Sanstha - Maharashtra",
      "Pariyaram College Of Nursing , Kannur - Kerala",
      "PARK COLLEGE OF EDUCATION - Tamil Nadu",
      "Park College of Engineering Technology - Tamil Nadu",
      "Park College of Technology - Tamil Nadu",
      "Parkar Medical Foundations School Of Nursing,Ratnagiri - Maharashtra",
      "Parks College - Tamil Nadu",
      "Parle Tilak Vidyalaya Associations Institute of Management - Maharashtra",
      "Parle Tilak Vidyalaya Associations Sathye College - Maharashtra",
      "Parmanand College of Technology , Sri Ganganagar - Rajasthan",
      "Parmarth Institute of Teacher's Education - Bihar",
      "PARMESHWAR MAHAVIDYALAYA - Uttar Pradesh",
      "Parmeswar Mahavidyalaya - Uttar Pradesh",
      "PARMNANAD TRILOK CHAND TEACHERS TRAINING COLLEGE - Rajasthan",
      "Parsandi Devi College of Law - Uttar Pradesh",
      "PARSHURAM SHIKSHAK PRASHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Parshwanath Charitable Trust's College of Engineering - Maharashtra",
      "PARTAP TEACHER TRAINING COLLEGE FOR WOMAN - Punjab",
      "PARTH VIDYA PRASARAK MANDAL - Maharashtra",
      "Partha School Of Nursing , Tirupati - Andhra Pradesh",
      "PARTIARCH IGNATIUS ZAKKA TRAINING COLLEGE - Kerala",
      "Parul Institute of Engineering & Technology - Gujarat",
      "Parul Polytechnic Institute - Gujarat",
      "Parul School Of Nursing , Jalandhar - Punjab",
      "PARVAT NATH MAHAVIDYALAYA - Uttar Pradesh",
      "Parvathaneni Brahmayya Siddhartha College Of Art & Science - Andhra Pradesh",
      "Parvathys Arts And Science College - Tamil Nadu",
      "PARVATI BAHUUDESHIYA SANSTHA - Maharashtra",
      "PARVATI DHONDIBA DHANKUDE B.ED. COLLEGE - Maharashtra",
      "Parvati Mahila Mahavidyalaya - Uttar Pradesh",
      "PARVATI MAHILA MAHAVIDYALAYA - Uttar Pradesh",
      "Parvatibai Genba Moze College of Engineering - Maharashtra",
      "Parvatibai Mhaske Institute Of Nursing, Nagapur - Maharashtra",
      "Paschim Banga Rajya Praibandhi Sammilani, A N M Training School , Kolkata - West Bengal",
      "Paschim Banga Rajya Pratibandhi Sammilani , Kolkata - West Bengal",
      "Paschim Dhemaji College - Assam",
      "Paschim Guwahati Mahavidyalaya - Assam",
      "PASCHIM MAHARASHTRA EDUCATION TRUST - Maharashtra",
      "Paschimbanga Rajya Pratibandhi Sammilani - West Bengal",
      "PASHUPATI INSTITUTE OF STUDIES - Uttar Pradesh",
      "PASPO COLLEGE OF EDUCATION - Tamil Nadu",
      "Pastor Lenssen Polytechnic College - Tamil Nadu",
      "Pasumpon Muthuramalinga Thevar College - Tamil Nadu",
      "Pasumpon Muthuramalinga Thevar College - Tamil Nadu",
      "Pasumpon Nethaji Polytechnic College - Tamil Nadu",
      "Pasumpon Nethaji Polytechnic College - Tamil Nadu",
      "Pasumpon Thiru. Muthuramalinga Thevar College - Tamil Nadu",
      "PATADUDI TEACHER TRAINING COLLEGE - Haryana",
      "Patanjali School Of Nursing , Chitradurga - Karnataka",
      "PATEL CO-EDUCATION TEACHERS TRAINING COLLEGE - Rajasthan",
      "Patel College of Education - Bihar",
      "Patel College Of Nursing,Ramanagaram - Karnataka",
      "Patel College of Pharmacy , Bangalore - Karnataka",
      "Patel College of Science & Technology - Madhya Pradesh",
      "Patel College Of Science & Technology, Ratibad - Madhya Pradesh",
      "Patel J B Rudelwada Arts Patel A M Rudewala Commerce Patel J D K Dawalwala Science - Gujarat",
      "Patel Memorial National College - Punjab",
      "Patel School Of Nursing , Bangalore - Karnataka",
      "Patel Shri Teekaram Mahavidyalaya - Uttar Pradesh",
      "Pathani Samanta College - Orissa",
      "Pathani Samanta Institute of Engineering and Technology - Orissa",
      "Pathani Samanta Nursing Centre , Nayagarh - Orissa",
      "Pathani Samanta School Of Nursing , Nayagarh - Orissa",
      "PATHANKOT TEACHER TRAINING COLLEGE - Punjab",
      "PATHANKOT TEACHER TRAINING COLLEGE - Punjab",
      "Patharkandi College of Education - Assam",
      "Patiala Institute of Engineering and Technology For Women - Punjab",
      "PATIALA TEACHER TRAINING COLLEGE - Punjab",
      "Patidarrang College Nalbari - Assam",
      "Patil College of Engineering and Technology, - Maharashtra",
      "Patiram Shivhare Nursing College , Bhind - Madhya Pradesh",
      "Patiram Shivhare Nursing School , Bhind - Madhya Pradesh",
      "Patitapaban Institute of Technology , Khurda - Orissa",
      "Patitapaban Mahavidyalaya - Orissa",
      "Patkai Christian College - Nagaland",
      "PATLIPUTRA  INSTITUTE OF  HOTEL  MANAGEMENT AND CATERING  TECHNOLOGY - Bihar",
      "Patliputra Anm Training School , Patna - Bihar",
      "Patliputra Medical College And Hospital , School Of Nursing , Dhanbad - Jharkhand",
      "Patliputra Medical College, Dhanbad - Jharkhand",
      "Patliputra Teacher's Training College - Bihar",
      "Patna College - Bihar",
      "Patna Dental College & Hospital , Patna - Bihar",
      "Patna Homoeopathic Medical College - Bihar",
      "Patna Law College - Bihar",
      "Patna Medical College Hospital , School Of Nursing , Patna - Bihar",
      "Patna Medical College, Panta - Bihar",
      "Patna Medical College, Patna - Bihar",
      "Patna PW Medical College - Bihar",
      "Patna Science College - Bihar",
      "Patna Training College - Bihar",
      "Patna Training College - Bihar",
      "Patna University - Bihar",
      "Patna Women's College - Bihar",
      "Patna Women'S Training College - Bihar",
      "Patna Womens College - Bihar",
      "Patratu Thermal Power Station College - Jharkhand",
      "PATRI SWAMY RURAL TEACHERS TRAINING INSTITUTION - Karnataka",
      "Patrician College Of Arts And Science - Tamil Nadu",
      "PATRICIAN COLLEGE OF EDUCATION - Uttaranchal",
      "Patronage Institute of Management Studies Greater Noida - Uttar Pradesh",
      "Patronage Institute of Professional Studies - Uttar Pradesh",
      "PATRONAGE INSTITUTE OF PROFESSIONAL STUDIES - Uttar Pradesh",
      "PATRONAGE INSTITUTE OF PROFESSIONAL STUDIES - Uttar Pradesh",
      "Pattammal Alagesan College Of Arts And Science - Tamil Nadu",
      "Pattammal School Of Nursing , Thanjavur - Tamil Nadu",
      "Pattamundai College - Orissa",
      "Pattukkottai Polytechnic College - Tamil Nadu",
      "Pattukkottai Polytechnic College - Tamil Nadu",
      "Pauls College Of Nursing , Villupuram - Tamil Nadu",
      "PAULS TEACHER TRAINING INSTITUTE - Pondicherry",
      "PAULSONS COLLEGE OF PHYSICAL EDUCATION - Tamil Nadu",
      "Pavai Polytechnic College - Tamil Nadu",
      "Pavai Varam Polytechnic College - Tamil Nadu",
      "Pavan College Of Nursing , Kolar - Karnataka",
      "Pavan Degree College - Andhra Pradesh",
      "Pavan School Of Nursing , Kolar - Karnataka",
      "Pavana College Of Nursing,Bangalore - Karnataka",
      "Pavana School Of Nursing , Bangalore - Karnataka",
      "Pavanatma College - Kerala",
      "Pavendar Bharadhidasan Arts And Science College - Tamil Nadu",
      "Pavendar Bharathidasan College Of Engineering - Tamil Nadu",
      "Pavendar Bharathidasan Institute Of Information Technology - Tamil Nadu",
      "Pavendar Bharathidasan Polytechnic College For Girls - Tamil Nadu",
      "Pavitra Degree College - Uttar Pradesh",
      "Pavitra Degree College - Andhra Pradesh",
      "PAWAN SHIKSHAN PRASARAK MANDALS COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Payyannur College - Kerala",
      "Pazhassi Raja College - Kerala",
      "Pazhassi Raja N.S.S. College - Kerala",
      "Pb. Govt. Dental College & Hospital, Amritsar - Punjab",
      "PBN College - Andhra Pradesh",
      "PCTE Group of Institutes",
      "Pd. Mahadev Shukla Krishak PG College - Uttar Pradesh",
      "PDA College of Engineering - Karnataka",
      "PDM College of Diploma Engineering & Technology - Haryana",
      "PDM College of Engineering - Haryana",
      "PDM Dental College & Research Institute , Bahadurgarh - Haryana",
      "PDMIET Karsindhu - Haryana",
      "PEACE COLLEGE OF EDUCATION - Tamil Nadu",
      "Peace Foundation Schoool Of Nursing,Ernakulum - Kerala",
      "PEARL TEACHERS TRAINING COLLEGE - Rajasthan",
      "PEARL VALLEY EDUCATION SOCIETY - Karnataka",
      "Pedanandipadu College Arts Science - Andhra Pradesh",
      "Pedanandipadu College of Arts & Science - Andhra Pradesh",
      "Pee Gee College Of Arts And Science - Tamil Nadu",
      "Pee Gee Polytechnic College - Tamil Nadu",
      "Pee Gee Polytechnic College - Tamil Nadu",
      "PEER ZANJANI TEACHERS TRAINING INSTITUTE - Karnataka",
      "Peerless College Of Nursing , Kolkatta - West Bengal",
      "Peerless Hospital & B K Roy Research Centre , Calcutta - West Bengal",
      "Peet Memorial Training College - Kerala",
      "PEET MEMORIAL TRAINING COLLEGE - Kerala",
      "PEETAMBER DEGREE COLLEGE - Uttar Pradesh",
      "PEETH BRAHAMAN TEACHER TRAINING COLLEGE - Haryana",
      "Pemraj Sarda College - Maharashtra",
      "Pendarani Mahavidyalaya - Orissa",
      "Pendekanti Institute of Management - Andhra Pradesh",
      "Pendekanti Law College - Andhra Pradesh",
      "Pendikanti Institute Of Mgt - Andhra Pradesh",
      "PENIEL RURAL COLLEGE OF EDUCATION - Tamil Nadu",
      "Pentakanti Law College - Andhra Pradesh",
      "People Arts Commerce & Science College - Maharashtra",
      "People Institute Of Management Studies - Kerala",
      "People's Institute of Hotel Management, Catering Technology - Madhya Pradesh",
      "People'S College of Medical Sciences & Research Centre,Bhanpur - Madhya Pradesh",
      "People's College of Research and Technology - Madhya Pradesh",
      "People's ED. Soc's College of Engg - Maharashtra",
      "People's Education Society Institute of Technology - Karnataka",
      "People's Education Society Sanchalit Sheth DL Law College - Gujarat",
      "PEOPLE'S INSTITUTE OF MANAGEMENT AND RESEACH - Madhya Pradesh",
      "People's University - Madhya Pradesh",
      "Peoples College - Orissa",
      "Peoples College - Orissa",
      "Peoples College - Andhra Pradesh",
      "Peoples College - Maharashtra",
      "Peoples College of Dental Sciences & Research Centre, Bhopal - Madhya Pradesh",
      "Peoples College of Medical Sciences & Research Centre, Bhanpur - Madhya Pradesh",
      "Peoples College Of Nursing & Research Centre , Bhopal - Madhya Pradesh",
      "Peoples College Of Nursing & Research Centre , Bhopal - Madhya Pradesh",
      "Peoples Dental Academy, Bhopall - Madhya Pradesh",
      "Peoples Education Scoietys Ist Grade College - Karnataka",
      "Peoples Education Society Sanchalit - Gujarat",
      "Peoples Education Society Sanchalit Shri J B Thakkar Commerce College - Gujarat",
      "PEOPLES EDUCATION SOCITYS P E S COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Peoples Institute of Legal Studies - Madhya Pradesh",
      "Perarignar Anna College - Tamil Nadu",
      "PERI Institute of Technology - Tamil Nadu",
      "PERINGATHUR TEACHERS TRAINING INSTITUTE - Kerala",
      "Periyar Centenary Girl'S Polytechnic College - Tamil Nadu",
      "Periyar Centenary Polytechnic College - Tamil Nadu",
      "Periyar College Of Pharmaceutical Sciences For Girls - Tamil Nadu",
      "Periyar College of Pharmaceutical Sciences for Girls , Trichy - Tamil Nadu",
      "Periyar E.V.R. Government Arts College - Tamil Nadu",
      "Periyar Government Arts College - Tamil Nadu",
      "Periyar Management Computer College Delhi - Delhi",
      "Periyar Maniammai College of Technology for Women - Tamil Nadu",
      "Periyar Maniammai University - Tamil Nadu",
      "PERIYAR TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Periyar University - Tamil Nadu",
      "PERIYAR UNIVERSITY DEPARTMENT OF EDUCATION - Tamil Nadu",
      "PERMANAND DEGREE COLLEGE - Rajasthan",
      "Perundurai Medical College and Institute of Road Transport, Perundurai - Tamil Nadu",
      "PERUNTHALAIVAR KAMARAJAR COLLEGE OF EDUCATION - Pondicherry",
      "Perunthalaivar Kamarajar Government Arts College - Pondicherry",
      "Perunthalaivar Kamarajar Institute Engineering Technology - Pondicherry",
      "Perunthurai Medical College and Institute of Road Transport, Perunthurai - Tamil Nadu",
      "Pes College Arts And Science - Goa",
      "PES College of Engineering - Karnataka",
      "PES College of Pharmacy , Bangalore - Karnataka",
      "PES Institute of Technology - Karnataka",
      "PES Institute Technology Management - Karnataka",
      "PES Modern College of Engineering, Pune - Maharashtra",
      "PES School of Engineering - Karnataka",
      "PESTLE WEED COLLEGE OF INFORMATION TECHNOLOGY - Uttaranchal",
      "PET COLLEGE OF TEACHERS EDUCATION - Tamil Nadu",
      "PET Engineering College - Tamil Nadu",
      "Pet Polytechnic College - Tamil Nadu",
      "PET POST GRADUATE CENTER FOR EDUCATION & RESEARCH - Karnataka",
      "PETER S COLLEGE OF EDUCATION - Tamil Nadu",
      "Pettigrew College - Manipur",
      "PF. SUJAN SINGH DEGREE COLLEGE - Uttar Pradesh",
      "PG Training College - Assam",
      "PGP COLLEGE OF EDUCATION - Tamil Nadu",
      "PGP College of Engineering and Technology - Tamil Nadu",
      "Phaltan Education Society Nursing School,Satara - Maharashtra",
      "Phani School Of Nursing , Vijayawada - Andhra Pradesh",
      "Phenku Singh Mahavidyalaya Chewar Lalganj - Uttar Pradesh",
      "Philadelphia Hospital , School Of Nursing , Ambala - Haryana",
      "Phoenix The Global Institute Of Nursing , Jalandhar - Punjab",
      "Phogat Nursing School,Bhiwani - Haryana",
      "Phonics School Of Engineering College - Uttaranchal",
      "PHOOL BUN TEACHERS TRAINING INSTITUTE FOR GIRLS - Karnataka",
      "Phool Devi Kusheshwar Jha College - Bihar",
      "Phoolwati Devi Institute of Law - Uttar Pradesh",
      "Phoolwati Institute of Law - Uttar Pradesh",
      "Phule Samaj Sudhark Samittis Shahir Annabhau Sath - Maharashtra",
      "Phulsing Naik Mahavidyalaya - Maharashtra",
      "PICT School of Technology and Management - Maharashtra",
      "Pier Giorgio Frassati College Of Nursing,Nalgonda - Andhra Pradesh",
      "PILLAI COLLEGE OF EDUCATION AND RESEARCH - Maharashtra",
      "Pillai Institute of Management Studies and Research - Maharashtra",
      "Pillai's Institute of Information Technology, Engineering, Media Studies & Research - Maharashtra",
      "Pillais Hoc Polytechnic - Maharashtra",
      "Pillais Polytechnic - Maharashtra",
      "PIMPALDARIS COLLEGE OF EDUCATION - Maharashtra",
      "Pimpri Chinchwad Education Trust's. Pimpri Chinchwad College of Engineering - Maharashtra",
      "Pindi Mahavidyalaya - Uttar Pradesh",
      "Pindikesh Anchalika College(+3) - Orissa",
      "PINE GROVE TEACHER TRAINING COLLEGE - Punjab",
      "Pingalakhi Public Welfare Organization - Orissa",
      "Pingla Thana Mahavidyalaya - West Bengal",
      "Pink City College Of Nursing , Jaipur - Rajasthan",
      "Pink City College Of Nursing,Jaipur - Rajasthan",
      "Pink City School Of Nursing,Jaipur - Rajasthan",
      "Pinnacle Institute Of Nursing Sciences , Nagarabhavi - Karnataka",
      "Pinnamaneni Rajendra Prasad Memorial Degree College - Andhra Pradesh",
      "Pioneer Anm Training School , Bhubaneswar - Orissa",
      "Pioneer College Of Arts And Science - Tamil Nadu",
      "Pioneer College Of Nursing , Rangareddy - Andhra Pradesh",
      "Pioneer College of Physiotherapy - Tamil Nadu",
      "PIONEER D.ED COLLEGE - Haryana",
      "PIONEER INSTITUTE OF MANAGEMENT (PIM) - Rajasthan",
      "PIONEER INSTITUTE OF PROFESSIONAL STUDIES - Madhya Pradesh",
      "Pioneer Institute of Professional Studies - Madhya Pradesh",
      "Pioneer Kumarasamy College - Tamil Nadu",
      "Pioneer School Of Nursing,Ramanathapuram - Tamil Nadu",
      "PIPAR TEACHERS TRAINING COLLEGE - Rajasthan",
      "Pipli College - Orissa",
      "PITAMAH UMDA SINGH TEACHER TRAINING COLLEGE - Haryana",
      "Pitambara School Of Nursing,Datia - Madhya Pradesh",
      "Pithapur Rajahs Government College - Andhra Pradesh",
      "PJ College of Management and Technology Bhubaneswar - Orissa",
      "PKJM TRAINING INSTITUTE - Kerala",
      "PLANEER INSTITUTE OF ACADEMICS - Uttar Pradesh",
      "Pluto IT Engineering & Multimedia Institute - Gujarat",
      "PMC TEACHER TRAINING COLLEGE - Delhi",
      "PMR Engineering College - Tamil Nadu",
      "PMS College of Dental Science & Research , Tiruvananthapuram - Kerala",
      "PNC & KR Degree College - Andhra Pradesh",
      "PNS School of Engineering & Tecnology - Orissa",
      "Pocker Sahib Memorial College - Kerala",
      "Poddar Group of Institution - Rajasthan",
      "PODDAR GROUP OF INSTITUTIONS - Rajasthan",
      "PODDAR MANAGEMENT TRAINING INSTITUTE - Rajasthan",
      "PODDAR SHIKSHAN SANSTHAN - Rajasthan",
      "Podhigai College of Engineering and Technology - Tamil Nadu",
      "Poineer College - Andhra Pradesh",
      "Poineer Kumaraswamy College - Tamil Nadu",
      "Pokaran Polytechnic college, Pokaran - Rajasthan",
      "POKHARAN TEACHERS TRAINING COLLEGE - Rajasthan",
      "Pollachi Institute of Engineering and  Technology - Tamil Nadu",
      "Polytechnic Education & Training Institute - Haryana",
      "Polytechnic For Women South Ext. - Delhi - Delhi",
      "Pompei College - Karnataka",
      "PONDA EDUCATION SOCIETYS COLLEGE OF EDUCATION - Goa",
      "Pondicherry Engineering College - Pondicherry",
      "Pondicherry Inst.of Hotel Management And Catering - Tamil Nadu",
      "Pondicherry Institute of Medical Sciences & Research, Pondicherry - Pondicherry",
      "Pondicherry University - Pondicherry",
      "Pondicherry university - Pondicherry",
      "PONJESLY COLLEGE OF EDUCATION - Tamil Nadu",
      "Ponjesly College of Engineering - Tamil Nadu",
      "PONKALIAMMAN COLLEGE OF EDUCATION - Tamil Nadu",
      "PONMANAM INSTITUTE OF MANAGEMENT STUDIES & COMPUTER APPLICATION - Tamil Nadu",
      "PONMARI COLLEGE OF EDUCATION - Tamil Nadu",
      "PONNAIYAH COLLEGE OF EDUCATION - Tamil Nadu",
      "Ponnaiyah Ramajayam College - Tamil Nadu",
      "PONNAIYAH RAMAJAYAM COLLEGE EDUCATION - Tamil Nadu",
      "Ponnaiyah Ramajayam College of Engineering & Technology (PRIST) - Tamil Nadu",
      "Ponnaiyah Ramajayam College Of Engineering And Technology - Tamil Nadu",
      "Ponnaiyah Ramajayam Polytechnic College	 - Tamil Nadu",
      "Ponnaiyah Ramajayam Polytechnic College	 - Tamil Nadu",
      "Ponnaiyah Ramajayam Polytechnic College - Tamil Nadu",
      "Ponnur Degree College - Andhra Pradesh",
      "PONNUSAMY NADAR COLLEGE OF EDUCATION - Tamil Nadu",
      "PONNUSWAMY GOUNDER TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Ponugoti Madhav Rao(Pmr) Degree College - Andhra Pradesh",
      "Ponugoti Madhava Rao Law College - Andhra Pradesh",
      "POOJA BHAGAVAT MAHAJANA POST GRADUATE WING OF SBRR - Karnataka",
      "Pooja Institute Of Nursing , Bellary - Karnataka",
      "Pooja Institute Of Nursing, Ajmer - Rajasthan",
      "Pooja Nursing Institute,Bhandara - Maharashtra",
      "Pooja School Of Nursing,Beed - Maharashtra",
      "POOJA SHARIRIK SHIKSHAN MAHAVIDYALAYA - Maharashtra",
      "POOJA TEACHER TRAINING COLLEGE - Haryana",
      "Poojya Sane Guruji V.P. Mandal's College of Engineering - Maharashtra",
      "Poojya Sane Guruji Vidhya Prasarak Mandal's G. M. Choudhari Polytechnic, Shahada - Maharashtra",
      "POOJYA SANE GURUJI VIDHYA PRASARAK MANDALS COLLEGE OF EDUCATION - Maharashtra",
      "Pookoya Thangal Memorial Government College - Kerala",
      "Poompuhar College - Tamil Nadu",
      "Poona College Of Arts Science And Commerce - Maharashtra",
      "Poona District Education Association , Seth Govind Raghunath Sable College of Pharmacy, SASWAD - Maharashtra",
      "Poona District Education Association College Of Engineering - Maharashtra",
      "Poona District Education Association Shakarrao Ursal College of Pharmacy , Haveli - Maharashtra",
      "Poona District Education Associations Law College - Maharashtra",
      "Poona Institute of Management Sciences &amp; Entrepreneurship - Maharashtra",
      "POONAMCHAND GUPTA VOCATIONAL COLLEGE - Madhya Pradesh",
      "Poonga College Of Arts And Science - Tamil Nadu",
      "POORANI TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Pooranmal Ram Lal Degree College - Uttar Pradesh",
      "POORNA PRAGNA INSTITUTE OF MANAGEMNET - Karnataka",
      "Poornaprajna Institute of Management - Karnataka",
      "POORNAPRAJNYA EDUCATION ASSOCIATION - Karnataka",
      "Poornasai Vivekananda Degree College - Andhra Pradesh",
      "Poornima College of Engineering - Rajasthan",
      "Poornima Institute of Engineering and Technology - Rajasthan",
      "Poornima University - Rajasthan",
      "POORVA TEACHER TRAINING COLLEGE - Haryana",
      "POPE JOHN PAUL II COLLEGE EDUCATION - Tamil Nadu",
      "Pope John Paul II College of Education - Pondicherry",
      "POPE JOHN PAUL II COLLEGE OF EDUCATION - Pondicherry",
      "Pope Paul Mercy Home - Kerala",
      "Popes College - Tamil Nadu",
      "Popular College Education - Jammu and Kashmir",
      "Popular School Of Nursing , Gulbarga - Karnataka",
      "PORUKARA COLLEGE OF EDUCATION - Kerala",
      "Post G. Training College For Physical Education - West Bengal",
      "POST GRADUAT COLLEGE - Uttar Pradesh",
      "Post Graduate College - Uttar Pradesh",
      "POST GRADUATE COLLEGE - Uttar Pradesh",
      "Post Graduate College of Law, Osmania University - Andhra Pradesh",
      "Post Graduate College Of Nursing , Gwalior - Madhya Pradesh",
      "Post Graduate Institute Of Food Processing Technology & Bioenergy , Anand - Gujarat",
      "Post Graduate Institute of Medical Education & Research - Chandigarh",
      "Post Graduate Institute Of Medical Education And Research - Chandigarh",
      "Post Graduate Institute of Swasthiyog Pratisthan, Miraj - Maharashtra",
      "POST GRADUATE TEACHING DEPARTMENT COLLEGE OF EDUCATION - Maharashtra",
      "POST GRADUATE TEACHING DEPARTMENT OF PHYSICAL EDUCATION - Maharashtra",
      "Post Graduate Training College - Assam",
      "Post Graduate Training College for Physical Education - West Bengal",
      "Postgraduate Institute of Medical Education & Research, Chandigarh - Punjab",
      "Postgraduate Institute of Swasthiyog Pratisthan, Miraj - Maharashtra",
      "PostGraduate Training College for Physical Education - West Bengal",
      "POTDAR B.ED. COLLEGE - Maharashtra",
      "Pothigai Polytechnic College - Tamil Nadu",
      "Potti Sreeramulu Telugu University - Andhra Pradesh",
      "Potti Sriramulu Chalavadi Mallikarjuna Rao College of Engineering And Technology - Andhra Pradesh",
      "Poulomi School Of Nursing , Secunderabad - Andhra Pradesh",
      "Pourvi Shikshan Prasarak Mandals Mahila Homoeopathic Medical College - Maharashtra",
      "Poyanil Hospital , Pathanamthitta - Kerala",
      "PPG Business School - Tamil Nadu",
      "PPG Institute of technology - Tamil Nadu",
      "PR Engineering College - Tamil Nadu",
      "Prabha Degree College - Andhra Pradesh",
      "Prabha Devi Bhagwati Prasad Mahavidyalaya - Uttar Pradesh",
      "PRABHA DEVI MAHAVIDYALAYA - Uttar Pradesh",
      "PRABHA DEVI MAHAVIDYALAYA - Uttar Pradesh",
      "PRABHA DEVI MAHAVIDYALAYA - Uttar Pradesh",
      "Prabha Devi Mahavidyalaya - Uttar Pradesh",
      "Prabha Institute of Nursing - Tamil Nadu",
      "Prabha School Of Nursing , Adilabad - Andhra Pradesh",
      "Prabha Shankar Pandya College Of Nursing,Banswara - Rajasthan",
      "PRABHAKAR PATIL EDUCATION SOCIETY - Maharashtra",
      "Prabhakar Patil Education Society Polytechnic - Maharashtra",
      "Prabhakar Patil Institute Of Nursing Education,Raigad - Maharashtra",
      "Prabhala Lakshminarayana Memorial Degree College - Andhra Pradesh",
      "PRABHALA PG COLLEGE FOR WOMEN - Andhra Pradesh",
      "Prabharani B.Ed. College - West Bengal",
      "Prabharani Institute of Education (B.Ed. College) - West Bengal",
      "Prabharani Institute of Education (Physical Education College) - West Bengal",
      "Prabhas Degree College - Andhra Pradesh",
      "Prabhat Education Societys P.D. Jain Homoeopathic Medical College - Maharashtra",
      "Prabhat Engineering College - Uttar Pradesh",
      "Prabhat Jyotirmoyee College of Education - West Bengal",
      "Prabhat Kumar College - West Bengal",
      "PRABHATH  INSTITUTE OF COMPUTER SCIENCES - Andhra Pradesh",
      "PRABHATH INSTITUTE OF BUSINESS MANAGEMENT - Andhra Pradesh",
      "Prabhavati Nursing School,Aurangabad - Maharashtra",
      "Prabhawati School Of Nursing,Chandrapur - Maharashtra",
      "Prabhodhan S.P. S's Rajendra Mane College of Engineering & Tech - Maharashtra",
      "Prabhu Dayal Polytechnic - Haryana",
      "Prabhu Jagatbandhu College - West Bengal",
      "PRABHU NARAYAN SINGH MAHAVIDYALAYA - Uttar Pradesh",
      "Prabhudas Thakkar Arts Commerce College - Gujarat",
      "Prabodhini Trust, indore - Maharashtra",
      "Prachya Niketan - Madhya Pradesh",
      "Prachya Sodh Peeth- Prayas Sansthan - Rajasthan",
      "Pradeep Centre for Autism Management - West Bengal",
      "PRADEEP MEMORIAL COMPREHENSIV OF EDUCATION - Delhi",
      "pradnyaa school of business management - Maharashtra",
      "Prafulla Chandra College - West Bengal",
      "PRAGA BAL UTHAN SAMITI - Madhya Pradesh",
      "Pragajyotish College - Assam",
      "Pragathi Arts & Science College - Andhra Pradesh",
      "Pragathi Arts & Science College, Mahaboobnagar - Andhra Pradesh",
      "Pragathi Charities - Andhra Pradesh",
      "PRAGATHI COLLEGE OF EDUCATION - Karnataka",
      "Pragathi College Of Nursing , Bangalore - Karnataka",
      "Pragathi Degree College - Andhra Pradesh",
      "Pragathi Degree College For Women - Andhra Pradesh",
      "Pragathi Degree College, Chundoor - Andhra Pradesh",
      "Pragathi Degree College, Kakinada - Andhra Pradesh",
      "Pragathi Degree College, Kothavalasa - Andhra Pradesh",
      "Pragathi Degree College, Nizamabad - Andhra Pradesh",
      "Pragathi Degree College, Valigonda - Andhra Pradesh",
      "Pragathi Institute Of Nursing , Bangalore - Karnataka",
      "Pragathi Pharmacy College , Warangal - Andhra Pradesh",
      "PRAGATHI SCHOOL OF BUSINESS - Andhra Pradesh",
      "Pragathi School Of Nursing , Hyderabad - Andhra Pradesh",
      "PRAGATHI TEACHER TRAINING INSTITUTE - Karnataka",
      "Pragathi Womens College - Andhra Pradesh",
      "Pragathi Womens Degree College - Andhra Pradesh",
      "PRAGATI COLLEGE - Chhattisgarh",
      "Pragati Engineering College - Andhra Pradesh",
      "Pragati Hospital & Research Centre , Sivasagar - Assam",
      "PRAGATI INSTITUTE OF EDUCATION AND TRAINING - Delhi",
      "PRAGATI MAHAVIDYALAYA PG COLLEGE - Andhra Pradesh",
      "PRAGATI MAHILA MANDAL - Maharashtra",
      "PRAGATI SHIKSHAN SANSTAHANS JAWAHARLAL NEHRU COLLEGE - Madhya Pradesh",
      "PRAGATI TEACHERS TRAINING COLLEGE - Rajasthan",
      "PRAGNA PG COLLEGE - Andhra Pradesh",
      "Pragya A N M School , Gwalior - Madhya Pradesh",
      "PRAGYA TEACHER TRAINING COLLEGE - Haryana",
      "Pragyan College Of Nursing , Bhopal - Madhya Pradesh",
      "Pragyna Degree College, Kakinada - Andhra Pradesh",
      "Prahar School of Architecture - Tamil Nadu",
      "Prahladrai D.L.College Of Commerce & Economics - Maharashtra",
      "Praja Mandal Mahila Mahavidyalaya - Orissa",
      "Prajananda Govt. Primary Teacher's Training Institute - West Bengal",
      "PRAJASATTAK COLLEGE OF EDUCATION - Maharashtra",
      "Prajna College Of Nursing,Hassan - Karnataka",
      "Prajna College Of Science And Arts - Andhra Pradesh",
      "PRAJNA D.ED COLLEGE - Karnataka",
      "Prajna Institute Of Technology And Managment - Andhra Pradesh",
      "Prajwal College Of Nursing , Bangalore - Karnataka",
      "Prakasam Degree College - Andhra Pradesh",
      "Prakasam Engineering College - Andhra Pradesh",
      "Prakash College Education - Gujarat",
      "Prakash Institute Of Nursing, Prakash Instt. Of , Physiotherapy & Allied Med Sciences,Omega - Uttar Pradesh",
      "Prakash Institute Of Nursing,Noida - Uttar Pradesh",
      "Prakash Institute Of Physiotherapy, Rehabilitation & , Allied Medical Sciences , Noida - Uttar Pradesh",
      "Prakash Nursing School ,Mau - Uttar Pradesh",
      "PRAKASH SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Pramathesh Barua College Dhuburi - Assam",
      "Pramila Katiyar Special Education Institute - Uttar Pradesh",
      "PRAMOD D ED COLLEGE - Karnataka",
      "PRAMOD D.ED COLLEGE - Karnataka",
      "PRAMOD MAHAVIDYALAYA - Uttar Pradesh",
      "PRAMOD RAVINDRA DHURI ADHYAPAK MAHAVIDYALAYA - Maharashtra",
      "Pramothes Barua College - Assam",
      "Pramukh Swami Medical College - Gujarat",
      "Pramukh Swami Science H D Patel Arts College - Gujarat",
      "Pramukhswami Medical College, Karmsad - Gujarat",
      "Pranabananda Womens College - Nagaland",
      "Pranakrishna Mahavidyalaya - Orissa",
      "Pranavam School Of Nursing , Kollam - Kerala",
      "Prannath Mahavidyalaya - Orissa",
      "Prannath Parnami Insititute of Management & Technology - Haryana",
      "Pranveer Singh Institute of Technology - Uttar Pradesh",
      "Prasad Institute of Management and Technology - Uttar Pradesh",
      "Prasad Institute of Technology - Uttar Pradesh",
      "Prasad Institute of Technology & Sciences - Andhra Pradesh",
      "Prasad Institute of Technology , Jaunpur - Uttar Pradesh",
      "Prasad V. Potluri Siddhartha Institute of Technology - Andhra Pradesh",
      "PRASANNA COLLEGE OF EDUCATION - Karnataka",
      "Prasanna College Of Nursing,Belthangady - Karnataka",
      "Prasanna School Of Nursing , Dakshina Kannada - Karnataka",
      "Prasannadeb Womens College - West Bengal",
      "Prasannamani College ofPhysical Education&Yoga - Orissa",
      "Prasanthi Degree College - Andhra Pradesh",
      "PRASASVI TEACHERS TRAINING COLLEGE - Rajasthan",
      "PRASHANATHI COLLEGE OF EDUACATION FOR WOMEN - Rajasthan",
      "PRASHANTH VIDYA SAMAST PRASHANTHA REDDY - Karnataka",
      "Prashanti Institute of Management - Madhya Pradesh",
      "PRASSACVI TEACHERS TRAINING COLLEGE - Rajasthan",
      "Pratap Bahadur Degree College - Uttar Pradesh",
      "PRATAP BAHADUR POST GRADUATE COLLEGE - Uttar Pradesh",
      "Pratap College of Management - Uttar Pradesh",
      "Pratap Institute of Technology & Science - Rajasthan",
      "Pratap Polytechnic College,Chirala - Andhra Pradesh",
      "PRATAP TEACHER TRAINING COLLEGE - Haryana",
      "PRATAP TEACHER TRAINING COLLEGE - Punjab",
      "PRATAP TEACHER TRAINING COLLEGE FOR WOMEN - Punjab",
      "Pratap University - Rajasthan",
      "Prathiba Degree College, Siddipet - Andhra Pradesh",
      "Prathiba Vignana Es Degree College For Women - Andhra Pradesh",
      "Prathibha Degree College, Kallur - Andhra Pradesh",
      "Prathima College Of Nursing , Karimnagar - Andhra Pradesh",
      "Prathima Institute Of Medical Sciences, Karimnagar - Andhra Pradesh",
      "Prathima Institute of Medical Sciences, Karimnager - Andhra Pradesh",
      "Prathima School Of Nursing, Karimnagar - Andhra Pradesh",
      "Prathisthan Mahavidyalaya - Maharashtra",
      "Prathyusha Institute of Technology and Management - Tamil Nadu",
      "Pratibha Degree College - Andhra Pradesh",
      "Pratibha Degree College For Women - Andhra Pradesh",
      "Pratibha Degree College, Rangareddy - Andhra Pradesh",
      "Pratibha Degree College, Vizianagaram - Andhra Pradesh",
      "Pratibha Institute of Business Management - Maharashtra",
      "Pratibha Institute Of Nursing, Raipur - Chhattisgarh",
      "Pratibha Niketan Mahavidyalaya(Arts Sc Com.) - Maharashtra",
      "Pratibha School Of Nursing, Navi Mumbai - Maharashtra",
      "Pratiksha School Of Nursing, Kamrup - Assam",
      "Pratishtha Institute of Pharmaceutical Sciences, Nalgonda - Andhra Pradesh",
      "Prativa Devi School Of Nursing, Bhubaneswar - Orissa",
      "Prativa Singh G N M Training Centre, Khurda - Orissa",
      "Prativadevi School Of Nursing, Bhubaneswar - Orissa",
      "Pravara Centre for Management Research & Development - Maharashtra",
      "Pravara Institute Of Medical Sciences, College Of Nursing, Ahmednagar - Maharashtra",
      "PRAVARA INSTITUTE OF RESEARCH & EDUCATION IN NATURAL & SOCIAL SCIENCE - Maharashtra",
      "Pravara Medical Trust, College Of Nursing, Ahmednagar - Maharashtra",
      "Pravara Medical Trust, Pravara Rural, Hospital, School Of Nursing, P O Loni - Maharashtra",
      "Pravara Medical Trusts School Of Nursing, Ahmednagar - Maharashtra",
      "PRAVARA RURAL COLLEGE OF EDUCATION - Maharashtra",
      "Pravara Rural College of Engineering, Ahmednagar - Maharashtra",
      "Pravara Rural College of Pharmacy - Maharashtra",
      "Pravara Rural College of Pharmacy, Ahmednagar - Maharashtra",
      "Pravara Rural Edu Soc Visvesvaraya Engineering College, Nashik - Maharashtra",
      "Pravara Rural Education Society's Pravara Rural - Maharashtra",
      "PRAVARA RURAL EDUCATION SOCIETYS COLLEGE OF PHYSICAL EDUCATION - Maharashtra",
      "Praveenya Institute of Marine Engineering - Andhra Pradesh",
      "Prayag Citizen Law College - Uttar Pradesh",
      "Prayag Mahila Vidyapeeth Degree College - Uttar Pradesh",
      "PRAYAG MAHLIA VIDYAPEETH DEGREE COLLEGE - Uttar Pradesh",
      "PRAYAG MAHLIA VIDYAPEETH DEGREE COLLEGE - Uttar Pradesh",
      "Prayas Centre for Special Education and Vocational Training - Rajasthan",
      "PRAYAS TEACHER TRAINING COLLEGE - Delhi",
      "Prayavi School Of Nursing , Bidar - Karnataka",
      "Praytna Nursing College,Ahmednagar - Maharashtra",
      "Prem Ashram Institute of Sisters of Charity - Himachal Pradesh",
      "Prem Mahavidyalay Polytechnic, Mathura - Uttar Pradesh",
      "Prem Raghu Hospital & Paramedical Institute , Mahamaya Nagar - Uttar Pradesh",
      "Prem Raghu Hospital And Paramedical Institute,Mahamaya Nagar - Uttar Pradesh",
      "PREM SHANTI NIKETAN TEACHERS TRAINING COLLEGE - Rajasthan",
      "PREMA KATIYAR SHIKSHAN SANSTHAN MAHAVIDYALAYA - Uttar Pradesh",
      "Prema Katiyar Shikshan Sansthan Mahavidyalaya - Uttar Pradesh",
      "Prema Sagari College Of Nursing,Vishakhapatnam - Andhra Pradesh",
      "Prema Sagari College Of Nursing,Vishakhapatnam - Andhra Pradesh",
      "Prema School Of Nursing , Visakhapatnam - Andhra Pradesh",
      "Premawati College Of Nursing , Jabalpur - Madhya Pradesh",
      "Premi Devi Samaj Kalyan - Uttar Pradesh",
      "Premi Devi Samaj Kalyan Mahila Mahavidyalaya - Uttar Pradesh",
      "PREMIER COLLEGE OF MANAGEMENT - Karnataka",
      "Premier College Of Nursing,Bangalore - Karnataka",
      "Premier Institute Of Nursing , Gowribidanur - Karnataka",
      "Premiere institute of hotel management - Orissa",
      "Premilatai Shende College Of Nursing,Solapur - Maharashtra",
      "PREMKUWAR VITHALDAS DAMODHAR THAKARSI COLLEGE OF EDUCATION FOR WOMENS - Maharashtra",
      "Premlila Vithaldas Polytechnic - Maharashtra",
      "Prerana Degree College - Andhra Pradesh",
      "Prerna A N M School Of Nursing,Sirsa - Haryana",
      "Prerna Sr Secondary School , Sirsa - Haryana",
      "Presbyterian Hospital, School Of Nursing, Aizwal - Mizoram",
      "PRESENTATION COLLEGE OF TEACHER EDUCATION - Uttaranchal",
      "Presidency College - Tamil Nadu",
      "Presidency College - Manipur",
      "PRESIDENCY COLLEGE - Karnataka",
      "PRESIDENCY COLLEGE - Karnataka",
      "Presidency College Berhampur - Orissa",
      "Presidency College For Women, Hyderabad - Andhra Pradesh",
      "Presidency College Of Arts & Science - Andhra Pradesh",
      "PRESIDENCY COLLEGE OF EDUCATION & TECHNOLOGY - Uttar Pradesh",
      "Presidency College Of Nursing,Bangalore - Karnataka",
      "Presidency Degree College - Andhra Pradesh",
      "PRESIDENCY SCHOOL OF MGT. & COMPUTER SCIENCES - Andhra Pradesh",
      "Presidency School Of Nursing , Bangalore - Karnataka",
      "Presidency University - West Bengal",
      "PRESTIGE INSTITUTE OF  MANAGEMENT. - Madhya Pradesh",
      "PRESTIGE INSTITUTE OF MANAGEMENT - Madhya Pradesh",
      "Prestige Institute of Management & Research - Madhya Pradesh",
      "Prestige Medical Health Sciences - Karnataka",
      "PRESTON COLLEGE - Madhya Pradesh",
      "Preston School Of Nursing, Gwalior - Madhya Pradesh",
      "Prgyan College Of Nursing , Bhopal - Madhya Pradesh",
      "PRIMARY TEACHER TRAINING CENTRE - Karnataka",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Bihar",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education College - Jharkhand",
      "Primary Teacher's Education Training College-cum-DIET - Bihar",
      "PRIME (MCA) COLLEGE - Andhra Pradesh",
      "Prime College of Architecture and Planning - Tamil Nadu",
      "PRIME TEACHER TRAINING INSITTUTE - Tamil Nadu",
      "Prin M C Shah College Commerce - Gujarat",
      "Prin Welingkar Institute of Management Development & Research - Maharashtra",
      "Prin. L. N. Welingkar Institute of Management Development - Maharashtra",
      "PRIN. L.N. WELLINGKAR INSTITUTE OF MGT. DEVELOP - Karnataka",
      "PRIN.N.G.NARALKAR INSTITUTE OF CAREER DEVELOPMENT & RESEARCH - Maharashtra",
      "PRINCE ACADEMY OF HIGHER EDUCATION - Rajasthan",
      "Prince Academy of Technical Education, Sikar - Rajasthan",
      "PRINCE ADVANCE STUDIES - Delhi",
      "Prince College Of Nursing,Bangalore - Karnataka",
      "Prince Dr. K. Vasudevan College of Engineering and Technology - Tamil Nadu",
      "PRINCE INSTITUTE OF INNOVATIVE TECHNOLOGY - Uttar Pradesh",
      "PRINCE MARTHANDA VARMA TEACHER TRAINING INSTITUTE - Kerala",
      "Prince Polytechnic College, Sikar - Rajasthan",
      "Prince School Of Nursing , Bangalore - Karnataka",
      "PRINCE SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA - Rajasthan",
      "Prince Shri Venkateshwara Arts And Science College - Tamil Nadu",
      "Prince Shri Venkateshwara Padmavathy Engineering College - Tamil Nadu",
      "Princes Shehkar College For Women - Andhra Pradesh",
      "Princess College Of Nursing, Bangalore - Karnataka",
      "Princess Durru Shehvar College Of Nursing, Hyderabad - Andhra Pradesh",
      "PRINCESS TEACHERS TRAINING COLLEGE - Rajasthan",
      "Princeton College Of Engineering & Technology - Andhra Pradesh",
      "Princeton Degree College - Andhra Pradesh",
      "PRINCETON PG COLLEGE - Andhra Pradesh",
      "Princies Esins Womens Hospital School Of Nursing, Hyderabad - Andhra Pradesh",
      "Princies Esins Womens Hospital School Of Nursing, Hyderabad - Andhra Pradesh",
      "Principal K.M.Kundnani Pharmacy, ULHASNAGAR - Maharashtra",
      "Prinkya Devi School Of Nursing, Puri - Orissa",
      "Prism School of Business & Entrepreneurship - Chhattisgarh",
      "Pristine Institute Of Nursing, Gurdaspur - Punjab",
      "PRITHVI RAJ CHAUHAN MAHAVIDYALAYA - Uttar Pradesh",
      "PRITHVI RAJ CHAUHAN MAHAVIDYALAYA - Uttaranchal",
      "Prithviraj Deshmukh Institute Of Nursing, Yavatmal - Maharashtra",
      "PRITIBHA COLLEGE OF EDUCATION - Maharashtra",
      "Priya Darshini Anjuman Islamia Girls College - Madhya Pradesh",
      "PRIYA DARSHINI D ED COLLEGE - Karnataka",
      "PRIYA SHIKSHSK PRASHIKSHAN SANSTHAN - Rajasthan",
      "PRIYADARSHANI TEACHER TRAINING COLLEGE - Himachal Pradesh",
      "Priyadarshini College - Andhra Pradesh",
      "Priyadarshini College of Computer Sciences - Uttar Pradesh",
      "Priyadarshini College of Engineering - Andhra Pradesh",
      "Priyadarshini College of Engineering Andhra Pradesh - Andhra Pradesh",
      "Priyadarshini College of Engineering Maharastra - Maharashtra",
      "Priyadarshini College Of Nursing, Bangalore - Karnataka",
      "Priyadarshini College Of Nursing,Eastgodavari - Andhra Pradesh",
      "Priyadarshini Degree & Pg College - Andhra Pradesh",
      "Priyadarshini Degree College - Andhra Pradesh",
      "Priyadarshini Degree College, Jangareddygudem - Andhra Pradesh",
      "Priyadarshini Degree College, Khammam - Andhra Pradesh",
      "Priyadarshini Degree College, Kothagudem - Andhra Pradesh",
      "Priyadarshini Degree College, Nalgonda - Andhra Pradesh",
      "Priyadarshini Degree College, Nellore - Andhra Pradesh",
      "Priyadarshini Dental College & Hospital , Thiruvallur - Tamil Nadu",
      "Priyadarshini Dnyan Prabodhini Law College - Maharashtra",
      "PRIYADARSHINI EDUCATION - Karnataka",
      "Priyadarshini Engineering College - Tamil Nadu",
      "Priyadarshini Institute of Engineering and Technology, - Maharashtra",
      "PRIYADARSHINI INSTITUTE OF MANAGEMENT & SCIENCE - Jammu and Kashmir",
      "PRIYADARSHINI INSTITUTE OF TEACHER TRAINING - Tamil Nadu",
      "Priyadarshini Institute of Technology & Science - Andhra Pradesh",
      "Priyadarshini Institute Of Technology And Management - Andhra Pradesh",
      "Priyadarshini Mahila Mahavidyalaya - Maharashtra",
      "PRIYADARSHINI PG CENTRE - Andhra Pradesh",
      "PRIYADARSHINI PG COLLEGE - Andhra Pradesh",
      "Priyadarshini Polytechnic - Maharashtra",
      "Priyadarshini Polytechnic College - Tamil Nadu",
      "Priyadarshini Polytechnic College - Tamil Nadu",
      "Priyadarshini School Of Nursing , Bangalore - Karnataka",
      "Priyadarshini School Of Nursing , Rajahmundry - Andhra Pradesh",
      "Priyadarshini School Of Nursing , Yadgir - Karnataka",
      "Priyadarshini School Of Nursing ,Kasargod - Kerala",
      "PRIYADARSHINI SEVA SANSTHA - Maharashtra",
      "PRIYADARSHINI TEACHER TRAINING INSTITUTE - Karnataka",
      "Priyadarshni Institute of Paramedical Sciences , THIRUVANANTHAPURAM - Kerala",
      "Priyanka Degree College For Women - Andhra Pradesh",
      "Priyanka Gandhi Nursing School,Aurangabad - Maharashtra",
      "PRIYANKA TEACHERS TRAINING COLLEGE - Karnataka",
      "Priyatam Institute of Technology & Science - Madhya Pradesh",
      "PRM VIJAYA TEACHERS TRAINING INSTITUTE - Karnataka",
      "PRMS Sanstha Anuradha College of Pharmacy , CHIKHLI - Maharashtra",
      "PRO TEACHER TRAINING COLLEGE - Haryana",
      "Procadence Institute of Pharmaceutical Sciences - Andhra Pradesh",
      "PROF S.A. COLLEGE OF EDUCATION - Tamil Nadu",
      "Prof. Dhanapalan College For Women - Tamil Nadu",
      "Prof. G. Sundera Reddy Degree College - Andhra Pradesh",
      "PROF. GURSEWAK SINGH GOVERNMENT COLLEGE OF PHYSICAL EDUCATION - Punjab",
      "Prof. Ram Meghe Institute of Technology & Research - Maharashtra",
      "ProfDrNDPatil Mahavidyalaya - Maharashtra",
      "Professional Assistants for National Developing Assets - Maharashtra",
      "Professional Educational Trust's Group Of Institutions - Tamil Nadu",
      "Progati College Dhuburi - Assam",
      "Progressive College - Andhra Pradesh",
      "Progressive Education Society Pune - Maharashtra",
      "Progressive Education Society's Modern College of Engineering - Maharashtra",
      "PROGRESSIVE EDUCATION SOCIETYS B.ED. COLLEGE - Maharashtra",
      "Progressive Education Societys Modern Law College - Maharashtra",
      "Progressive Engineering College - Andhra Pradesh",
      "PROGRESSIVE LEARING TEACHER TRAINING COLLEGE - Haryana",
      "Projyothi Niketan College - Kerala",
      "Proudadevaraya Institute Of Technology - Karnataka",
      "Providence College for Women - Tamil Nadu",
      "PROVIDENCE COLLEGE OF TEACHER EDUCATION (B.ED) - Kerala",
      "Providence Womens College - Kerala",
      "Providence Womens College, Kozhikode - Kerala",
      "PRR & VS Govt College - Andhra Pradesh",
      "PRR. Polytechnic, Giddaluru - Andhra Pradesh",
      "Pruthvi Evening Law College - Karnataka",
      "Pruthviraj Deshmukh Institute Of Nursing, Yavatmal - Maharashtra",
      "PSC & KVSC Govt College - Andhra Pradesh",
      "PSG College of Pharmacy , Peelamedu - Tamil Nadu",
      "PSG College of Technology - Tamil Nadu",
      "PSG Institute of Medical Sciences, Coimbatore - Tamil Nadu",
      "PSM College of Dental Sciences & Research , Thrissur - Kerala",
      "PSN COLLEGE OF EDUCATION - Tamil Nadu",
      "PSN College of Engineering and Technology - Tamil Nadu",
      "PSNA College of Engineering and Technology - Tamil Nadu",
      "PSV Polytechnic College - Tamil Nadu",
      "PT, SUJAN SINGH DEGREE COLLEGE - Uttar Pradesh",
      "Pt. Ambika Pratap Narayan Degree College - Uttar Pradesh",
      "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak Haryana - Haryana",
      "Pt. B.D Sharma Postgraduate Institute of Medical Science, Rohtak - Haryana",
      "PT. B.D. MEMORIAL D.ED. COLLEGE - Madhya Pradesh",
      "Pt. Bhagwat Dayal Sharma University of Health Sciences - Haryana",
      "PT. BRIJ KISHORE PATERIA SHIKSHA MAHAVIDYALAYA - Madhya Pradesh",
      "PT. CHARITRA, MISHRA MAHAVIDYALAYA - Uttar Pradesh",
      "Pt. Deen Dayal Institute - Physically Handicapped - Delhi",
      "Pt. Deen Dayal Upadhya Girls College - Madhya Pradesh",
      "Pt. Deen Dayal Upadhya Government Degree College - Uttar Pradesh",
      "Pt. Deen Dayal Upadhyay Goverment College - Uttar Pradesh",
      "Pt. Deen Dayal Upadhyay Government Girls Degree College - Uttar Pradesh",
      "Pt. Deen Dayal Upadhyay Gramodya Mahavidyalaya - Uttar Pradesh",
      "Pt. Deen Dayal Upadhyay Management College - Uttar Pradesh",
      "PT. DEEN DAYAL UPADHYAYA MANAGEMENT COLLEGE - Uttar Pradesh",
      "Pt. Gauri Shankar Memorial Polytechnic - Himachal Pradesh",
      "Pt. Gokul Kamla Memorial Education Soceity Anm Training Centre, Bilaspur - Chhattisgarh",
      "PT. HARI SAHAI DEGREE COLLEGE - Uttar Pradesh",
      "Pt. Hari Sahay Degree College - Uttar Pradesh",
      "PT. HARISHANKAR SHUKLA SMRITI MAHAVIDYALAYA - Chhattisgarh",
      "Pt. J N M Medical College, Raipur - Chhattisgarh",
      "Pt. J.L.N. College - Uttar Pradesh",
      "Pt. J.N.M Medical College, Raipur - Chhattisgarh",
      "Pt. Jag Narayan Shukla Gramoday Mahavidyalaya - Uttar Pradesh",
      "Pt. Jagannath Mishra Mahavidyalaya - Uttar Pradesh",
      "Pt. Jawahar Lal Nehru Memorial Institute of Homoeopathic Medical Sciences - Maharashtra",
      "PT. JAWAHARLAL NEHRU COLLEGE - Uttar Pradesh",
      "PT. JAWAHARLAL NEHRU INSTITUTE OF BUSINESS MANAGEMENT - Madhya Pradesh",
      "Pt. Jawaharlal Nehru State Homoeopathic Medical College and Hospital - Uttar Pradesh",
      "Pt. Kishori Lal Shukla Law College - Chhattisgarh",
      "PT. KUNDAN LAL SHUKLA MAHAVIDYALAYA - Uttar Pradesh",
      "PT. L.R. TEACHER TRAINING COLLEGE - Haryana",
      "PT. LALIT MOHAN SHARMA GOVT. P.G.DEGREE,COLLEGE - Uttaranchal",
      "Pt. Mohan Lal S.D. College for Women - Punjab",
      "Pt. Motilal Nehru Vidhi Mahavidyalaya - Madhya Pradesh",
      "PT. OM PRAKASH SHARMA MAHAVIDYALAYA - Uttar Pradesh",
      "Pt. Prithi Nath (PG) College - Uttar Pradesh",
      "Pt. Purnanand Tiwari Law College - Uttaranchal",
      "Pt. Ram Dutt Shukla Degree College - Uttar Pradesh",
      "Pt. Ram Komal Dwivedi Degree College - Uttar Pradesh",
      "Pt. Ram Lakhan Shukla Govt. P.G. College - Uttar Pradesh",
      "PT. RAM NIWAS MEMORIAL TEACHER TRAINING COLLEGE - Haryana",
      "Pt. Rameshwar Bajpai Smriti Mahavidyalaya - Uttar Pradesh",
      "Pt. S.N.Shukla GovernmentCollege - Madhya Pradesh",
      "Pt. Sahdev Prasad Trivedi Mahavidyalay - Uttar Pradesh",
      "PT. SITA RAM SHASTRI B.ED TRAINING COLLEGE - Haryana",
      "Pt. Sripati Mishra Degree College - Uttar Pradesh",
      "PT. SUNDAR LAL SHARMA (OPEN) UNIVERSITY - Chhattisgarh",
      "Pt. Sunderlal Memorial Degree College - Uttar Pradesh",
      "PT. SUNDERLAL MEMORIAL POST GRADUATE COLLEGE - Uttar Pradesh",
      "PT. SUNJAN SINGH DEGREE COLLEGE - Uttar Pradesh",
      "PT. SURYA NARAYAN CHATURVEDI DEGREE COLLEGE - Uttar Pradesh",
      "Pt. Surya Narayan Chaturvedi Law Degree College - Uttar Pradesh",
      "Pt. Thakur Prasad Tripathi - Uttar Pradesh",
      "Pt. Udai Jain Mahavidyalaya - Rajasthan",
      "PT.AMBIKA PRATAP NARAYAN DEGREE COLLEGE - Uttar Pradesh",
      "PT.AMBIKA PRATAP NARAYAN DEGREE COLLEGE - Uttar Pradesh",
      "PT.AMBIKA PRATAP NARAYAN DEGREE,COLLEGE - Uttar Pradesh",
      "Pt.B.D.Sharma Postgraduate Institute of Medical Sciences,ROHTAK - Haryana",
      "PT.DEEN DAYAL UPADHYAY MANAGEMENT COLLEGE - Uttar Pradesh",
      "PT.JAG NARAYAN SHUKLA GRAMODAYA MAHAVIDYALAYA - Uttar Pradesh",
      "PT.JAWAHAR LAL NEHRU PG COLLEGE - Uttar Pradesh",
      "PT.JAWAHAR LAL NEHRU PG COLLEGE - Uttar Pradesh",
      "PT.MANISH SHARMA DEGREE COLLEGE - Uttar Pradesh",
      "PT.OM PRAKASH SHARMA MAHAVIDYALAYA - Uttar Pradesh",
      "PT.TEJRAM COLLEGE OF EDUCATION - Uttar Pradesh",
      "PT.TRIYUGI NARAYAN MAHAVIDYALAYA - Uttar Pradesh",
      "PT.VASHUDEV TIWARI COLLEGE OF EDUCATION - Uttar Pradesh",
      "PTR College of Engineering & Technology - Tamil Nadu",
      "Pub Majuli College - Assam",
      "Pubkamrup College - Assam",
      "Public College - Punjab",
      "Public Health Training Instt.,S.M.S.Medical College , Jaipur - Rajasthan",
      "Public Khalsa College for Women - Punjab",
      "Public Khalsa College For Womens Vpo, School Of Nursing , Hoshiarpur - Punjab",
      "PUBLIC MAHILA SAHAR DEGREE COLLEGE BARAMADPUR - Uttar Pradesh",
      "Public Mahila Sahar Mahavidyalaya - Uttar Pradesh",
      "PUBLIC TEACHER TRAINING COLLEGE - Punjab",
      "Pujya Shri Madhavanji college of Engineering and Technology - Andhra Pradesh",
      "PUJYA SWAMI VIVEKANAND TEACHER TRAINING COLLEGE - Haryana",
      "PULAVAR KUPPUSWAMI TEACHER TRAINING INSTITUTION - Tamil Nadu",
      "Pulipati College Of Nursing,Andhra Paradesh - Andhra Pradesh",
      "Pulipati Prasad College Of Nursing,Khammam - Andhra Pradesh",
      "PULLA REDDY INSTITUTE OF COMPUTER SCIENCE - Andhra Pradesh",
      "Pulla Reddy Institute of Pharmacy - Andhra Pradesh",
      "Pune Institute Of Business Management - Maharashtra",
      "Pune Julha Mandals Mamasahib Mohol Arts & Commerce - Maharashtra",
      "Pune Vidhyarthi Griha's College of Engineering and Technology - Maharashtra",
      "Pune Vidyarthi Griha's Institute of Management - Maharashtra",
      "PUNITHA ANNAL TEACHER TRAININGINSTITUTE FOR WOMEN - Tamil Nadu",
      "PUNITHA OHM COLLEGE OF EDUCATION - Tamil Nadu",
      "PUNITHA VALANAR COLLEGE OF EDUCATION - Tamil Nadu",
      "Punjab Agriculture University Ludhiana - Punjab",
      "PUNJAB BUSINESS SCHOOL - Punjab",
      "Punjab College of Engineering & Technology - Punjab",
      "Punjab College of Pharmacy , Ferozepur - Punjab",
      "PUNJAB COLLEGE OF TECHNICAL EDUCATION - Punjab",
      "Punjab Engineering College - Chandigarh",
      "Punjab Group of colleges - Punjab",
      "PUNJAB INSTITUTE OF MANAGEMENT & TECHNOLOGY - Punjab",
      "Punjab Institute of Medical Sciences, Jalandhar - Punjab",
      "Punjab Institute Of Nursing , Bhatinda - Punjab",
      "Punjab Medical Institute Of Nursing & Hospital , Jalandhar - Punjab",
      "PUNJAB MUITIPURPOSE INSTITUTE,SHAINA - Punjab",
      "Punjab Multipurpose Institute Of Nursing , Barnala - Punjab",
      "Punjab Multipurpose Institute Of Nursing Shaina , Barnala - Punjab",
      "Punjab Multipurpose Medical Institute , Barnala - Punjab",
      "Punjab National Nursing School , Patiala - Punjab",
      "Punjab Public College Of Nursing , Bhatinda - Punjab",
      "Punjab School of Law - Punjab",
      "PUNJAB TEACHER TRAINING COLLEGE,FATEHGARH - Punjab",
      "PUNJAB TEACHER TRAINING COLLEGE,RAIPUR - Punjab",
      "PUNJAB TEACHER TRAINING COLLEGE,SARKAPDA - Punjab",
      "Punjab Technical University - Punjab",
      "Punjab University - Chandigarh",
      "PUNJABAI PATEL COLLEGE OF EDUCATION - Maharashtra",
      "Punjabi University - Punjab",
      "Punjabi University Patiala - Punjab",
      "Punjabi University Regional Centre - Punjab",
      "PUNJABI UNIVERSITY TEACHER TRAINING COLLEGE - Punjab",
      "Punyagiri Degree College, Vizianagaram - Andhra Pradesh",
      "Puranmal Lahoti Government Polytechnic - Maharashtra",
      "PURATCHI KAVINGNAR BHARATHIDASAN TEACHER TRAINING J.A.M.J EDUCATION TRUST - Pondicherry",
      "PURATCHI THALAIVAR DR.M.G.R. TEACHER EDUCATION - Tamil Nadu",
      "Purba Medinipur B.Ed.College - West Bengal",
      "Purba Medinipur Primary Teacher's Training Institute - West Bengal",
      "Puri Engineering School - Orissa",
      "Puri Saraswati School Of Nursing , Balasore - Orissa",
      "Puri School Of Nursing , Puri - Orissa",
      "Purna Chandra Institute of Engineering & Technology - Orissa",
      "Purnea College - Bihar",
      "Purnea Mahila College - Bihar",
      "Purnima Ram Pratap Sanskrit Mahavidyalaya - Bihar",
      "Purulia Polytechnic - West Bengal",
      "Purushottam Institute of Engineering and Technology - Orissa",
      "Purushottamdas Bagla Homoeopathic Medical College and Hospital - Maharashtra",
      "Purusottam School of Engineering & Technology - Orissa",
      "Purvanchal Degree College - Uttar Pradesh",
      "Purvanchal Institute of Dental Sciences , Gorakhpur - Uttar Pradesh",
      "Purvannchal Khadi Gramoudog Vikas Samiti - Uttar Pradesh",
      "PURVVANCHAL DEGREE COLLEGE - Uttar Pradesh",
      "PUSHP INSTITUTE OF SCIENCES AND HIGHER STUDIES - Uttar Pradesh",
      "Pushpa Singh Vidhi Mahavidyalaya - Uttar Pradesh",
      "PUSHPAGEETH COLLEGE OF TEACHER S EDUCATION - Kerala",
      "Pushpagiri College of Dental Sciences , Thiruvalla - Kerala",
      "Pushpagiri College Of Nursing , Pushpagiri Instt Of Medical Sciences & Research Centre , Pathanamthi - Kerala",
      "Pushpagiri College Of Nursing , Thiruvalla - Kerala",
      "Pushpagiri College of Pharmacy , Thiruvalla - Kerala",
      "Pushpagiri Hospital ,Thiruvalla - Kerala",
      "Pushpagiri Institute of Medical Sciences And Research Centre, Thiruvalla - Kerala",
      "PUSHPANJALI COLLEGE OF EDUCATION - Maharashtra",
      "Pushpanjali Institute Of Nursing , Agra - Uttar Pradesh",
      "PYARI DEVI RAJIT MAHAVIDYALAYA - Uttar Pradesh",
      "Pyari Devi Rajit Mahavidyalaya - Uttar Pradesh",
      "Pydah College - Andhra Pradesh",
      "PYDAH COLLEGE FOR PG STUDIES - Andhra Pradesh",
      "Pydah College For Women, Visakhapatnam - Andhra Pradesh",
      "Pydah College of Engineering & Technolog - Andhra Pradesh",
      "Pydah College Of Nursing,Visakhapatnam - Andhra Pradesh",
      "PYSSUM Research & Training Centre - Uttar Pradesh",
    ],
  },
];
