const OData = [
    {
        colleges: [
            "O P Jindal Institute of Technology - Chhattisgarh",
            "O P R Memorialschool Of Nursing, Cuddalore - Tamil Nadu",
            "O. P. R. Memorial College Of Nursing, Cuddalore - Tamil Nadu",
            "O.P. Jindal Global University - Haryana",
            "O.P.R. MEMORIAL COLLEGE OF EDUCATION - Tamil Nadu",
            "O.V.R. Degree College - Andhra Pradesh",
            "Oakbrook Business School - Gujarat",
            "OAS Institute Of Technology And Management, Group Of Institutions - Tamil Nadu",
            "OASIS IMPERIAL COLLEGE OF EDUCATION - Madhya Pradesh",
            "Oberoi School of Hotel Management, Delhi - Delhi",
            "Ocean College Of Nursing, Bangalore - Karnataka",
            "Ocean School Of Nursing, Bangalore - Karnataka",
            "Odaiyappa College of Engineering and Technology - Tamil Nadu",
            "Odapada Panchayat Samit Mahavidyalaya - Orissa",
            "OJASWANI COLLEGE PAR EXCELLENCE - Madhya Pradesh",
            "Ojaswini Institute of Management & Technology - Madhya Pradesh",
            "Ojaswini Institute Of Nursing Science & Research, Damoh - Madhya Pradesh",
            "Ojaswini Institute Of Nursing Sciences & Research, Damoh - Madhya Pradesh",
            "Ojaswini Institute Par Excellence - Madhya Pradesh",
            "Ojaswini Nursing College, Sagar - Madhya Pradesh",
            "Ojaswini Nursing School, Sagar - Madhya Pradesh",
            "Olaver College - Orissa",
            "OLIVE PG COLLEGE - Andhra Pradesh",
            "OM BHUDESHWAR NATH R.S.V.S. MAHAVIDYALAYA - Uttar Pradesh",
            "OM Bio- Sciences and Management College - Uttaranchal",
            "OM Institute of Polytechnic - Haryana",
            "OM INSTITUTE OF TECH. & MGT - Haryana",
            "OM KARNANDA INSTITUTE OF MANAGEMENT & TECHNOLOGY, Tehri Garhwal - Uttaranchal",
            "OM KOTHARI INSTITUTE OF MANAGEMENT & RESEARCH - Rajasthan",
            "OM KOTHARI INSTITUTE OF TEACHER TRAINING - Rajasthan",
            "Om Polytechnic - Maharashtra",
            "OM PRAKASH MEMORIAL INSTITUTE OF EDUCATION - Punjab",
            "Om Sai College of Pharmacy & Health Sciences, Ganjam - Orissa",
            "OM SAI D.ED COLLEGE - Karnataka",
            "Om Sakthi College Of Nursing, Dharmapuri - Tamil Nadu",
            "OM SHANKAR D.ED COLLEGE - Karnataka",
            "OM SHANTI COLLEGE OF EDUCATION - Tamil Nadu",
            "Om Shanti School Of Nursing, Gwalior - Madhya Pradesh",
            "OM SHIV MAHILA TEACHERS TRAINING COLLEGE - Rajasthan",
            "OM SHRI GURU SHAKTI RAM CHANDER INSTITUTE - Uttar Pradesh",
            "OM SRI VIGNESHWARA WOMEN TEACHER TRAINING INSTITUTE - Tamil Nadu",
            "OM TEACHER TRAINING COLLEGE - Haryana",
            "Om Vidyalankar Shikshan Sansthas Amita College of Law, Mumbai - Maharashtra",
            "OM VINDHYAVASANI INSTITUTE OF MANAGEMENT, Rajkot - Gujarat",
            "Omayal Achi College Of Nursing, Thiruvallur - Tamil Nadu",
            "OmDayal College of Engineering And Architecture - West Bengal",
            "Omega Degree College, Keesar - Andhra Pradesh",
            "OMEGA P.G. COLLEGE, Mandal - Andhra Pradesh",
            "Omkar College Of Nursing, Guna - Madhya Pradesh",
            "Omkar School Of Nursing, Guna - Madhya Pradesh",
            "Omkar School Of Professional Studies, Guna - Madhya Pradesh",
            "OMKARAMAL SOMANI COLLEGE OF EDUCATION - Karnataka",
            "Omkarananda Institute of Management and Technology - Uttaranchal",
            "OMM MURUGA COLLEGE OF EDUCATION - Tamil Nadu",
            "OMPRAKASH MEMORIAL INSTITUTE OF EDUCATION - Punjab",
            "Omsakthi School Of Nursing, Dharampuri - Tamil Nadu",
            "OMSHANTI COLLEGE OF EDUCATION - Maharashtra",
            "ONGC Girls Polytechnic - Uttaranchal",
            "Onkar College of Pharmacy , Sangrur - Punjab",
            "Onkarmal Somani College of Commerce - Rajasthan",
            "OOA-MAVMM School of Management - Tamil Nadu",
            "OOLIYASTHANAM TEACHER TRAINING INSTITUTE - Tamil Nadu",
            "Open Learning System - Orissa",
            "OPEN UNIVERSITY DIRECTORATE OF TECHNICAL EDUCATION - Tamil Nadu",
            "Opera College Of Nursing,Kota - Rajasthan",
            "Opera School Of Nursing, Kota - Rajasthan",
            "Orange City College of Social Work - Maharashtra",
            "ORIENTAL B.ED COLLEGE - Madhya Pradesh",
            "Oriental College - Nagaland",
            "Oriental College - Bihar",
            "Oriental College - Manipur",
            "Oriental College Bihar - Bihar",
            "Oriental College of Education - Bihar",
            "ORIENTAL COLLEGE OF EDUCATION AND RESEARCH - Maharashtra",
            "ORIENTAL COLLEGE OF MANAGEMENT - Madhya Pradesh",
            "Oriental College Of Nursing , Bangalore - Karnataka",
            "Oriental College Of Nursing,Korba - Chhattisgarh",
            "ORIENTAL COLLEGE OF TEACHER EDUATION - Kerala",
            "ORIENTAL EDUCATION SOCIETY - Maharashtra",
            "ORIENTAL INSTITUTE OF MANAGEMENT - Maharashtra",
            "Oriental Institute Of Nursing ,Balaghat - Madhya Pradesh",
            "Oriental Institute of Science and Technology, Thakral Nagar - Madhya Pradesh",
            "Oriental Law Institute - Uttar Pradesh",
            "Oriental School of Business - Maharashtra",
            "Oriental School of Hotel Management - Kerala",
            "ORIENTAL TEACHER TRAINING INSTITUTE - Tamil Nadu",
            "Oriental University - Madhya Pradesh",
            "Orissa College of Pharm Sciences , Dhenkanal - Orissa",
            "Orissa Computer Academy, KHURTA - Orissa",
            "Orissa Engineering College - Orissa",
            "Orissa Health Education School Of Nursing , Makangiri - Orissa",
            "Orissa Institute of Engineering & Technology - Orissa",
            "Orissa Medical College Of Homeopathy & Research - Orissa",
            "Orissa Medical College of Homoeopathy & Research - Madhya Pradesh",
            "Orissa Nursing Training Institute , Cuttack - Orissa",
            "Orissa School of Engineering, - Orissa",
            "Orissa School of Mining Engineering - Orissa",
            "Orissa School of Mining Engineering, Keonjhar - Orissa",
            "Orissa University of Agriculture & Technology College of Home Science - Orissa",
            "Orissa University Of Agriculture And Technology, BHUBANESWAR - Orissa",
            "Osmania College, KURNOOL - Andhra Pradesh",
            "Osmania Degree College, PRODDATUR - Andhra Pradesh",
            "Osmania Law College, KURNOOL - Andhra Pradesh",
            "Osmania Medical College - Andhra Pradesh",
            "Osmania School Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
            "Osmania University - Andhra Pradesh",
            "Oupada College - Orissa",
            "OUR LADY COLLEGE OF EDUCATION - Tamil Nadu",
            "OUR LADY DOLOURS TEACHER TRAINING INSTITUTE - Tamil Nadu",
            "Our Lady Of Health College Of Nursing , Thanjavur, THANJAVUR - Tamil Nadu",
            "Our Lady Of Health School Of Nursing, , Thanjavur, THANJAVUR - Tamil Nadu",
            "Our Lady Of Lourdes School Of Nursing , Dharwad, DHARWAD - Karnataka",
            "Our Lady School Of Nursing, , Dindigul, DINDIGUL - Tamil Nadu",
            "OUR LADYS TEACHER TRAINING INSTITUTE - Kerala",
            "Owaisi College Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
            "Owaisi School Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
            "OXBRIDGE BUSINESS SCHOOL, BANGALORE - Karnataka",
            "OXFORD COLLEGE OF EDUCATION - Tamil Nadu",
            "Oxford College of Engineering, BANGALORE - Karnataka",
            "Oxford College of Engineering Tamil Nadu, TRICHY - Tamil Nadu",
            "Oxford College Of Engineering,Thiruvannamali - Tamil Nadu",
            "Oxford College of Law, BANGALORE - Karnataka",
            "Oxford College Of Nursing , Bangalore - Karnataka",
            "OXFORD D.ED COLLEGE - Karnataka",
            "Oxford Degree College, VIZIANAGARAM - Andhra Pradesh",
            "Oxford Evening Polytechnic - Karnataka",
            "OXFORD GIRLS TEACHER TRAINING COLLEGE - Haryana",
            "OXFORD INTERNATIONAL TEACHER TRAINING COLLEGE - Haryana",
            "OXFORD KANNADA D ED COLLEGE - Karnataka",
            "OXFORD MODEL INSTITUTE OF ADVANCE STUDIES - Uttar Pradesh",
            "OXFORD School Of Management - Gujarat",
            "Oxford School Of Nursing , Bangalore - Karnataka",
            "Oxford School Of Nursing , Gulbarga - Karnataka",
            "Oxford School Of Nursing , Hyderabad - Andhra Pradesh",
            "OXFORD TEACHER TRAINING COLLEGE - Haryana",
            "OXFORD TEACHER TRAINING INSTITUTE - Karnataka",
            "OXFORD TEACHER TRAINING INSTITUTE - Tamil Nadu",
            "Oxpherd Polytechnic - Karnataka",
            "OZAR VIKAS SANSTHAS VISHWASATTYA D.ED. COLLEGE - Maharashtra",
        ]
    }
];
