const HData = [
  {
    colleges: [
      "H A College Commerce, Gujarat - Gujarat",
      "H C Boraiah Memorial Sc St First Grade College, Karnataka - Karnataka",
      "H C D G College, Assam - Assam",
      "H C T School Of Nursing ,Baran, Rajasthan - Rajasthan",
      "H C Women'S College, Chhattisgarh - Chhattisgarh",
      "H D Jain College, Bihar - Bihar",
      "H H B Kotak Institute Science, Gujarat - Gujarat",
      "H H Bhadrabahu Swamiji Nursing School , Belgaum, Karnataka - Karnataka",
      "H I C T A N M School , Gwalior, Madhya Pradesh - Madhya Pradesh",
      "H I C T College , Gwalior, Madhya Pradesh - Madhya Pradesh",
      "H I C T G N M College,Gwalior, Madhya Pradesh - Madhya Pradesh",
      "H K E S College Of Nursing , Gulbarga, Karnataka - Karnataka",
      "H K E S Womens Polytechnic, Gulbarga, Karnataka - Karnataka",
      "H K E S' Smt Chinamma Bisappapatil Arts Commerce College Karnataka, Karnataka - Karnataka",
      "H K E Society M S I Arts Science Degree College, Karnataka - Karnataka",
      "H K E Society Polytechnic, Karnataka - Karnataka",
      "H K E Societys College Of Nursing,Gulbarga, Karnataka - Karnataka",
      "H K E Societys School Of Nursing , Gulbarga, Karnataka - Karnataka",
      "H K E Socity Polytechnic, Karnataka - Karnataka",
      "H K E Socity'S A V Patil Degree College Of Arts Science Commerce, Karnataka - Karnataka",
      "H K E Socity'S A V Patil Degree College Of Arts Science Commerce, Karnataka - Karnataka",
      "H K Es S S Margol College Arts Science Commerce Shasabad, Karnataka - Karnataka",
      "H K Es Sri Prabhu Arts Science And J M Bohra Commerce College Sholapur, Karnataka - Karnataka",
      "H K H College, Tamil Nadu - Tamil Nadu",
      "H K Institute of Management Studies and Research, Maharashtra - Maharashtra",
      "H K L College Of Nursing , Firozpur, Punjab - Punjab",
      "H K Veerana Gowdh First Grade College, Karnataka - Karnataka",
      "H L G Government College Tauru, Haryana - Haryana",
      "H L Institute Commerce, Gujarat - Gujarat",
      "H L Institute Commerce C O H L Commerce College Comp Gujarat, Gujarat - Gujarat",
      "H L Institute Computer Applications, Gujarat - Gujarat",
      "H L Patel Arts And Commerce College, Gujarat - Gujarat",
      "H L. M GIRLS COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "H M R School Of Nursing , Bangalore, Karnataka - Karnataka",
      "H M S Polytechnic, Tumkur, Karnataka - Karnataka",
      "H M S Rural Polytechnic, Karnataka - Karnataka",
      "H M V Arts And Commerce College, Gujarat - Gujarat",
      "H Madhya Pradeshatel Institute English Training And Research, Gujarat - Gujarat",
      "H N Doshi Arts R N Doshi College Commerce, Gujarat - Gujarat",
      "H N S School Of Nursing , Gulbarga, Karnataka - Karnataka",
      "H P P C Government First Grade College, Karnataka - Karnataka",
      "H P S College, Bihar - Bihar",
      "H R College Amanour, Bihar - Bihar",
      "H R College Bihar, Bihar - Bihar",
      "H R Sri Ramalu Memorial Arts Science College, Karnataka - Karnataka",
      "H S College Bihar, Bihar - Bihar",
      "H S College Haveli Hkharagpur, Bihar - Bihar",
      "H. B. Patel Institute Of Diploma Engg. & Technology, Gujarat - Gujarat",
      "H. K. E. Societys Seth Shankarlal Lahoti Law College, Karnataka - Karnataka",
      "H. N. B Garhwal University, Uttaranchal - Uttaranchal",
      "H. S. Law College, Uttar Pradesh - Uttar Pradesh",
      "H.B. B.ED. COLLEGE, Maharashtra - Maharashtra",
      "H.B.T. Institute, Uttar Pradesh - Uttar Pradesh",
      "H.C. P.G.College, Uttar Pradesh - Uttar Pradesh",
      "H.D. TEACHER TRAINING INSTITUTE, Rajasthan - Rajasthan",
      "H.D.TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "H.Govindrao Pansare Mahavidyalaya, Maharashtra - Maharashtra",
      "H.H. MARTHOMA MATHEWS TEACHER TRAINING COLLEGE, Kerala - Kerala",
      "H.H. Memorial Law College, Karnataka - Karnataka",
      "H.H. Memorial Law College, Karnataka - Karnataka",
      "H.H. The Rajas College, PUDUKOTAI - Tamil Nadu",
      "H.I.M. GIRLS COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "H.I.S. Degree College, EAST GODAVARI - Andhra Pradesh",
      "H.J. INSTITUTE OF EDUCATION & TECHNOLOGY, Haryana - Haryana",
      "H.J. Thim College of Arts & Science, Maharashtra - Maharashtra",
      "H.K.C.C..M. INSTITUTE OF MANAGEMENT RESEARCH & DEVELOPMENT, AHMEDNAGAR - Maharashtra",
      "H.K.D.E. TRUSTS COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "H.K.D.E.Ts Dental College, Hospital & Research Intitute, Bidar, Karnataka - Karnataka",
      "H.K.E. Soceitys Narayan Shree Homoeopathic Medical College, Madhya Pradesh - Madhya Pradesh",
      "H.K.E. Societys P.D.A. Engineering College, Karnataka - Karnataka",
      "H.K.E. Societys, S. Nijalingappa Institute of Dental Sciences & Research , Gulbarga, Karnataka - Karnataka",
      "H.K.E.S.s College of Pharmacy , Gulbarga, Karnataka - Karnataka",
      "H.K.E.SOCIETY S BASAVESHWAR COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "H.K.INSTITUTE OF MANAGEMENT STUDIES & RESEARCH, MUMBAI - Maharashtra",
      "H.K.R.H. College, THENI - Tamil Nadu",
      "H.K.T. TEACHER TRAINING COLLEGE, Punjab - Punjab",
      "H.L. AGRAWAL COLLEGE OF EDUCATION, Madhya Pradesh - Madhya Pradesh",
      "H.L.M. COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "H.L.M. College, Uttar Pradesh - Uttar Pradesh",
      "H.L.M. Law College, GHAZIABAD - Uttar Pradesh",
      "H.L.Y. DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "H.M. Degree College, Punganur, Andhra Pradesh - Andhra Pradesh",
      "H.M. Degree College, Rayachoti, Andhra Pradesh - Andhra Pradesh",
      "H.M. TRAINING COLLEGE, Kerala - Kerala",
      "H.M.H.Degree College, Uttar Pradesh - Uttar Pradesh",
      "H.M.S. Education Society,H.M.S. College of Pharmacy , Tumkur, Karnataka - Karnataka",
      "H.N TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "H.N. Bahuguna Degree College, Uttar Pradesh - Uttar Pradesh",
      "H.N. SHUKLA COLLEGE OF MANAGEMENT STUDIES, Gujarat",
      "H.N.S.GARHWAL UNIVERSITY, Uttaranchal",
      "H.O.INSTITUTE OF EDUCATION AND TECHNOLOGY, Haryana",
      "H.P. Govt. Dental College & Hospital , Shimla, Himachal Pradesh",
      "H.P. INSTITUTE OF MGT. STUDIES, Himachal Pradesh",
      "H.P.T. Arts & R.Y.K.Science College, Maharashtra",
      "H.R. College Of Commerce & Economics, Maharashtra",
      "H.R.D. Degree College, Andhra Pradesh",
      "H.R.D. Degree College, Nalgonda, Andhra Pradesh",
      "H.R.Institute of Technology, Uttar Pradesh",
      "H.R.Patel Institute of Pharmacy , Dhule, Maharashtra",
      "H.S. Law College, Uttar Pradesh",
      "H.S.A. Degree College, Uttar Pradesh",
      "H.V. Desai College Of Artsscience & Commcollege, Maharashtra",
      "H.V.P. Mandal's College Of Gineering & Technology, Maharashtra",
      "H.V.TEACHER TRAINING INSTITUTE, Karnataka",
      "HAARDIK TEACHER TRAINING COLLEGE, Punjab",
      "HADI RANI TEACHER TRAINING COLLEGE, Rajasthan",
      "HAES;s Smt KA Jigalur Arts & Commerce College, Karnataka",
      "HaesS Smt K A Jigalur Arts Commerce College, Karnataka",
      "Hafiz Rehmat Khan Law College, Uttar Pradesh",
      "Hahnemann Homoeopathic Medical College, Madhya Pradesh",
      "Haindavi College, Andhra Pradesh",
      "HAIS PRE PRIMARY TEACHER TRAINING INSTITUTE, Kerala",
      "Haji Abdul Majid Memorial Nursing School , Nagaon, Assam",
      "Haji C.H. Mohammed Koya Memorial College for Advanced Studies, Kerala",
      "HAJI ISMAIL DEGREE COLLEGE, Uttar Pradesh",
      "HAJI S.M.S. SHAIK JALALUDEEN TEACHER TRAINING INSTITUTE, Tamil Nadu",
      "Haji Sheik Ismail Polytechnic College, Nagapattinam, Tamil Nadu",
      "HAKEEM HARBANS SINGH NEW ERA TEACHER TRAINING COLLEGE, Haryana",
      "Hakeem Mehtabuddin Hashmi College of Law, Uttar Pradesh - Uttar Pradesh",
      "Hakim Kishori Lal School Of Nursing , Ferozepur, FIROZPUR - Punjab",
      "Halakura College, DHUBURI - Assam",
      "Halamma School Of Nursing , Bagalkot, BAGALKOT - Karnataka",
      "Halamma School Of Nursing , Bagalkot, BAGALKOT - Karnataka",
      "HALAPPA KOTE B.ED COLLLEGE, - Karnataka",
      "Haldia Government College, - West Bengal",
      "Haldia Institute of Dental Sciences and Research, Midnapore, MEDINIPUR - West Bengal",
      "Haldia Institute Of Nursing Science , Medinipur, MEDINIPUR - West Bengal",
      "Haldia Institute Of Nursing Science , Purba Medinipur, - West Bengal",
      "Haldia Institute Of Technology., EAST MEDINIPUR - West Bengal",
      "Haldia Law College, MEDINIPUR - West Bengal",
      "Halflong Government College, - Assam",
      "HALIM MUSLIM COLLEGE, - Uttar Pradesh",
      "Halim Muslim Degree (PG) College, - Uttar Pradesh",
      "HALIM MUSLIM P.G. COLLEGE, - Uttar Pradesh",
      "HALLMARK BUSINESS SCHOOL, TRICHY - Tamil Nadu",
      "Halo Nursing School,Osmanabad, OSMANABAD - Maharashtra",
      "HAMANTH MEMORIAL EDUCATION SOCIETY, - Karnataka",
      "Hamdard Institute of Medical Sciences & Research, New Delhi, - Delhi",
      "HAMDARD WELFARE TRUSTS ASHRAFEE TEACHER TRAINING INSTITUTE, - Karnataka",
      "HAMEED PIYARE COLLEGE EDUCATION, - Karnataka",
      "Hamidabad College, NAGAON - Assam",
      "Hamidia Girls Degree College, - Uttar Pradesh",
      "Hamidia Hospital , School Of Nursing,Bhopal, BHOPAL - Madhya Pradesh",
      "HAMIRPUR COLLEGE OF ELEMENTARY TEACHER EDUCATION, - Himachal Pradesh",
      "HANAMGOWDA PATIL SMARA TEACHER TRAINING INSTITUTE, - Karnataka",
      "Handa College Education, - Jammu and Kashmir",
      "HANDIA (PG) COLLEGE, - Uttar Pradesh",
      "Handia Degree College, - Uttar Pradesh",
      "HANDIA P.G. COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Handia Polytechnic, Handia, Uttar Pradesh - Uttar Pradesh",
      "HANDIA POST GRADUATE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "HANDIA POST GRADUATE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Handique Girls' College, KAMRUP - Assam",
      "HANEEFA KUNJU MEMORIAL COLLEGE OF EDUCATION, Kerala - Kerala",
      "Hans Raj College, Delhi - Delhi",
      "HANS RAJ DAV TEACHER TRAINING COLLEGE, Punjab - Punjab",
      "Hans Raj Mahila College, Punjab - Punjab",
      "HANS RAJ MEMORIAL TEACHER TRAINING COLLEGE, Punjab - Punjab",
      "HANS TEACHERS TRAINIG COLLEGE, Rajasthan - Rajasthan",
      "HANSARAJ JEEVANDAS COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "Hansraj Jiwandas College Of Education, Maharashtra - Maharashtra",
      "HANTRAN TEACHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Hanuman Vyamshala Krida Mandals Physical Education College, Maharashtra - Maharashtra",
      "Hanumant School Of Nursing , Bhavnagar, BHAVNAGAR - Gujarat",
      "HANUMAT VIDYAPEETH WOMEN TEAVHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "HAPPY CHILD SHIKSHA SAMITI, Haryana - Haryana",
      "HAPPY INSTITUTE OF EDUCATION, Haryana - Haryana",
      "HAPPY TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HAPPY VALLEY BUSINESS SCHOOL, COIMBATORE - Tamil Nadu",
      "HAR SAHAI P.G. COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Harakejamd Chouradia College, Madhya Pradesh - Madhya Pradesh",
      "Haralaiah Polytechnic, Bhalki, Karnataka - Karnataka",
      "HARANAHALLI RAMASWAMY INSTITUTE OF HIGHER EDU, HASSAN - Karnataka",
      "Harasankar Bhattacharya Institute of Tech. & Mining, -",
      "Harbilas Bal & Mahila Chikitsalay , Lucknow, LUCKNOW - Uttar Pradesh",
      "Harcourt Butler Technological Institute, KANPUR - Uttar Pradesh",
      "HARDEKR MANJAPPA D ED COLLEGE, Karnataka - Karnataka",
      "Harhi College, Assam - Assam",
      "HARI ADARSH INSTITUTE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "Hari College of Law, SAHARANPUR - Uttar Pradesh",
      "Hari College of Law,, SAHARANPUR - Uttar Pradesh",
      "Hari Das Institute of Legal Studies And Research, MATHURA - Uttar Pradesh",
      "HARI INSTITUTE OF TECHNOLOGY, Uttar Pradesh - Uttar Pradesh",
      "HARI OM SHIV OM TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HARI SEWA SANSKRIT SHIKSHAK PRASHIKSHAN VIDYALAYA, Rajasthan - Rajasthan",
      "Hari Shankar Prasad Law College, BALLIA - Uttar Pradesh",
      "Hari Uday Institute Of Nursing Science,Morena, Madhya Pradesh - Madhya Pradesh",
      "Haribai Warpudkar Polytechnic, Maharashtra - Maharashtra",
      "Harichandra Mahavidhyalaya, VARANASI - Uttar Pradesh",
      "Harideojoshi Rajkiya Kanya Mahavidyalaya, Rajasthan - Rajasthan",
      "Harihar Prasad Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "HARIHARESHWARA VIDYA SAMSTHE VIVEKANANDA T.T.I, Karnataka - Karnataka",
      "Harinarain Singh Institute of Teacher's Education, Bihar - Bihar",
      "Haringata Mahavidyalya, West Bengal - West Bengal",
      "HARISH CHANDRA (PG) COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Harish Chandra Degree College, Uttar Pradesh - Uttar Pradesh",
      "HARISH CHANDRA POST GRADUATE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "HARISH MORE SHARIRIK SHIKSHAN MAHAVIDYALAYA, Maharashtra - Maharashtra",
      "HARISHCHANDRA DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Harishchandra Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "Haritha College Of Nursing , East Godavari, Andhra Pradesh - Andhra Pradesh",
      "Haritha School Of Nursing , Kakinada, Andhra Pradesh - Andhra Pradesh",
      "Harivallabhdas Kalidas Arts College, Gujarat - Gujarat",
      "Harkamaya College of Education, Sikkim - Sikkim",
      "HARLAL INSTITUTE OF MANAGEMENT & TECHNOLOGY, NOIDA - Uttar Pradesh",
      "HARLAL INSTITUTE OF MANAGEMENT & TECHNOLOGY, Uttar Pradesh - Uttar Pradesh",
      "Harlal School of Law, Uttar Pradesh - Uttar Pradesh",
      "HARMAN DAS LEKHRAJ INSTITUTE OF EDUCATION, Rajasthan - Rajasthan",
      "Harmukh College Education, Jammu and Kashmir - Jammu and Kashmir",
      "Harsahay Degree College, Uttar Pradesh - Uttar Pradesh",
      "Harsarn Dass Dental College, Ghaziabad, Uttar Pradesh - Uttar Pradesh",
      "HARSH MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "Harsh Mahila Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "Harsh School Of Nursing, Buldhana, Maharashtra - Maharashtra",
      "HARSH TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HARSH TEACHER TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Harsha College Of Nursing, Bangalore, Karnataka - Karnataka",
      "Harsha School Of Nursing, Bangalore, Karnataka - Karnataka",
      "Harshit School Of Nursing, Lucknow, Uttar Pradesh - Uttar Pradesh",
      "HARSHIT TEACHERS TRAINING INSTITUTE, Karnataka - Karnataka",
      "Harshith Group of Institutions, Andhra Pradesh - Andhra Pradesh",
      "HARUDHARA SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA, Rajasthan - Rajasthan",
      "Harur Muthu Arts And Science College For Women, Dharmapuri - Tamil Nadu",
      "Harvansh Daya Parkash Shyamo Devi Degree College, Uttar Pradesh - Uttar Pradesh",
      "Harvard Degree College, Thondangi, East Godavari - Andhra Pradesh",
      "Haryana College Of Nursing, Sirsa, Haryana - Haryana",
      "Haryana College of Special Education & Rehabilitation, Faridabad - Haryana",
      "HARYANA COLLEGE OF TEACHER TRAINING, Haryana - Haryana",
      "Haryana College of Technology & Management., Haryana - Haryana",
      "Haryana Engineering Colleges,, Haryana - Haryana",
      "HARYANA INSTITUTE OF BUSINESS MANAGEMENT, Bahadurgarh - Haryana",
      "HARYANA INSTITUTE OF EDUCATION, Haryana - Haryana",
      "Haryana Institute of Technology, Haryana - Haryana",
      "Haryana Polytechnic Institute, Haryana - Haryana",
      "HARYANA SCHOOL OF BUSINESS, Hissar - Haryana",
      "Haryana School Of Nursing, Sirsa, Haryana - Haryana",
      "HARYANA SHEKWATI DRAHMCHARYA ASHRAM, Haryana - Haryana",
      "HARYANA TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HARYANA TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HARYANA TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HASANAMBA COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "HASANAMBA COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "Hasananmba College Education, Karnataka - Karnataka",
      "HASHMATRAI AND GANGARAM HIMATHMAL MANSUKHANI INSTITUTE OF MANAGEMENT, Thane - Maharashtra",
      "Hashmi Girls Degree College, Uttar Pradesh - Uttar Pradesh",
      "Hashu Advani College of Special Education, Chembur - Maharashtra",
      "Hasmukh Goswami College of Engineering, Gujarat - Gujarat",
      "Hasnath College For Women, Karnataka - Karnataka",
      "Hassan Institute of Medical Sciences, Hasssan, Karnataka - Karnataka",
      "Hassan Shah Kohie Hami Memorial Government Degree College, Jammu and Kashmir - Jammu and Kashmir",
      "Hasvita Institute of Engineering & Technology HIET, Keesara - Andhra Pradesh",
      "Hatidhura College, Assam - Assam",
      "Havanur College of Law, Bangalore - Karnataka",
      "HAVERD INSTITUTE OF MANGEMENT & TECHNOLOGY, Uttar Pradesh - Uttar Pradesh",
      "HAWABAG WOMANS COLLEGE, Madhya Pradesh - Madhya Pradesh",
      "Hawabagh Womens College, Madhya Pradesh - Madhya Pradesh",
      "Hayagriva Polytechnic College, Tamil Nadu - Tamil Nadu",
      "Hayat Institute Of Nursing ,Lucknow, Lucknow - Uttar Pradesh",
      "HAYATHUL ISLAM ORPHANGE TEACHER TRAINING INSTITUTE, Kerala - Kerala",
      "Hayward Institute Of Nursing & Science , Gwalior, Gwalior - Madhya Pradesh",
      "Hayward Institute Of Nursing & Sciences,Gwalior, Madhya Pradesh - Madhya Pradesh",
      "HAZARI LAL DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "HAZARI LAL DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Hazaribag College of Dental Sciences and Hospital , Hazaribag, Hazaribag - Jharkhand",
      "HAZRAT SAYED FATEH SH VALI TEACHERS TRAINING INSTITUTE, Karnataka - Karnataka",
      "Hbservicess, Tamil Nadu - Tamil Nadu",
      "HDF School of Management, Orissa - Orissa",
      "HDPY B.ED COLLEGE, Kerala - State",
      "Healing Touch School Of Nursing , Hyderabad, Andhra Pradesh - State",
      "Health & Family Welfare Training Centre , Amritsar, Punjab - State",
      "Health & Hygiene Nursing Education Institute ,Alwar, Rajasthan - State",
      "Health Taining And Research Centre , Arunachal Pradesh, Arunachal Pradesh - State",
      "Health Worker Female Training Centre,Sikar, Rajasthan - State",
      "Health Worker mahila Trg Centre,Gorakhpur, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre , Almora, Uttaranchal - State",
      "Health Worker mahila Trg. Centre , Dehradun, Uttaranchal - State",
      "Health Worker mahila Trg. Centre , Haldwani, Uttaranchal - State",
      "Health Worker mahila Trg. Centre , Paurigarhwal, Uttaranchal - State",
      "Health Worker mahila Trg. Centre , Rampur, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre ,Gonda, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre ,Saharanpur, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Bahraich, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Basti, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Bijnore, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Deoria, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Faizabad, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Jhansi, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Kheeri, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Lucknow, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Mainpuri, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Mirzapur, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Moradabad, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Muzaffarnagar, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Pilibhit, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Pratapgarh, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Raibareli, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre,Shahjahanpur, Uttar Pradesh - State",
      "Health Worker mahila Trg. Centre, Sultanpur, Uttar Pradesh",
      "Health Worker mahila Trg. Centre, Varanasi, Uttar Pradesh",
      "Health Workers Training School , Aizawal, Mizoram",
      "Heartland College Of Nursing , Bangalore, Karnataka",
      "Heavy Engg. Corp Ltd , School Of Nursing , Ranchi, Jharkhand",
      "HEERA LAL YADAV BALIKA DEGREE COLLEGE, Uttar Pradesh",
      "Heeralal Yadav Balika Degree College, Uttar Pradesh",
      "Heeralal Yadav Law College, Lucknow, Uttar Pradesh",
      "Helen Kellar's Institute of Research and Rehabilitation for the Disabled Children, Hyderabad, Andhra Pradesh",
      "Helen Keller College of Special Education (HI), Cuddapah, Andhra Pradesh",
      "Helen Keller Govt. Teacher Training Centre for the Visually Handicapped Children, Govt. of Karnataka, Mysore, Karnataka",
      "Helen Kellers Institute of Deaf and Blind, Mumbai, Maharashtra",
      "Helen Kellers School for the Deaf, Cuddapah, Andhra Pradesh",
      "Helen Rose School Of Nursing, Yavatmal, Maharashtra",
      "Help School Of Nursing , Vijayawada, Andhra Pradesh",
      "HEMADRI B.ED COLLEGE, Karnataka",
      "Hemchandracharya North Gujarat University, Patan, Gujarat",
      "HEMCHANDRACHARYA NORTH GUJARAT UNIVERSITY, Gujarat",
      "Hemoprova Barbera Girls College, Assam",
      "Hemwati Nandan Bahuguna Garhwal University, Uttaranchal",
      "Henry Baker College, Kottayam, Kerala",
      "Heramba Chandra College, West Bengal",
      "Herambhu Business School, Andhra Pradesh",
      "HerbalCross Institute of Pharmacy HIP , Cuttack, Orissa",
      "HERITAGE COLLEGE OF PHYSICAL EDUCATION, Haryana",
      "Heritage Institute of Hotel and Tourism, Agra, Uttar Pradesh",
      "Heritage Institute Of Nursing & Paramedical Institute , Varanasi, Uttar Pradesh",
      "Heritage Institute of Technology, Kolkata, West Bengal",
      "HERITAGE INTERNATIONAL BUSINESS SCHOOL, Uttar Pradesh",
      "Heritage School Of Nursing & Paramedical Institute, Varanasi, Uttar Pradesh",
      "Heritage School Of Nursing, Fatehabad - Haryana",
      "Hetampur Rajbati Primary Teacher's Training Institute - West Bengal",
      "Hewett Polytechnic, Lucknow - Uttar Pradesh",
      "Hi Tech College of Pharmacy, Bhubaneswar - Orissa",
      "Hi Tech School Of Nursing, Khurda - Orissa",
      "Hi-Point College of Engineering & Technology - Andhra Pradesh",
      "Hi-Tech College of Engineering & Technology - Andhra Pradesh",
      "Hi-Tech Institute of Engineering - Uttar Pradesh",
      "Hi-Tech Institute of Engineering & Management - Orissa",
      "Hi-Tech Institute of Information & Technology - Orissa",
      "HI-TECH INSTITUTE OF INFORMATION TECHNOLOGY (HIIT) - Orissa",
      "Hi-Tech Institute Of Technology - Maharashtra",
      "HI-TECH INSTITUTE OF TECHNOLOGY - Uttar Pradesh",
      "Hi-Tech Medical College & Hospital, Bhubaneswar - Orissa",
      "Hi-Tech Medical College & Hospital, Rourkela - Orissa",
      "Hidayatullah National Law University - Chhattisgarh",
      "Hidayatullah National Law University Hnlu - Chhattisgarh",
      "Hierank Business School - Uttar Pradesh",
      "HIGHER EDUCATION OF TECHINCAL INSTITUTE - Uttar Pradesh",
      "HIGHER SEC SCHOOL KALLUPPALA TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Hightech Polytechnic, Gowribidanur - Karnataka",
      "HIHT University - Uttaranchal",
      "HILAL EDUCATION SOCIET (R) - Karnataka",
      "Hill College - Manipur",
      "Hill Side College Of Nursing, Bangalore - Karnataka",
      "HILL VALLEY COLLEGE OF EDUCATION FOR WOMEN - Kerala",
      "Hill View Nursing School, Ranchi - Jharkhand",
      "Hills College of Teacher Education - Arunachal Pradesh",
      "Hillside College Of Nursing, Bangalore - Karnataka",
      "HILLSIDE INSTITUTE OF MGT. & ACADEMY - Karnataka",
      "Hillside School Of Nursing, Bangalore - Karnataka",
      "HILTON TEACHERS TRAINING INSTITUTE - Tamil Nadu",
      "Him Navodaya Sikshan Sansthan, Chamba - Himachal Pradesh",
      "Himachal Dental College, Mandi - Himachal Pradesh",
      "Himachal Institute of Dental Sciences, Sirmour - Himachal Pradesh",
      "HIMACHAL INSTITUTE OF EDUCATION - Himachal Pradesh",
      "Himachal Institute Of Nursing, Sirmour - Himachal Pradesh",
      "HIMACHAL INSTITUTEOF EDUCATION - Himachal Pradesh",
      "Himachal Pradesh Agricultural University - Himachal Pradesh",
      "Himachal Pradesh College of Law - Himachal Pradesh",
      "Himachal Pradesh Technical University - Himachal Pradesh",
      "Himachal Pradesh University - Himachal Pradesh",
      "Himachal Pradesh University Evening College - Himachal Pradesh",
      "HIMACHAL TEACHER TRAINING COLLEGE - Himachal Pradesh",
      "Himalaya Modern School Of Nursing, Gurdaspur - Punjab",
      "HIMALAYA TEACHER TRAINING COLLEGE - Haryana",
      "HIMALAYAN COLLEGE - Uttaranchal",
      "Himalayan College Education - Jammu and Kashmir",
      "Himalayan College Of Nursing, Dehradun - Uttaranchal",
      "HIMALAYAN DOON ACADAMY - Uttaranchal",
      "Himalayan Group Of Professional Institution, Mandi - Himachal Pradesh",
      "Himalayan institute of Medical Sciences - Uttaranchal",
      "Himalayan Institute of Medical Sciences, Dehradun - Uttaranchal",
      "HIMALAYAN INSTITUTE OF MGT - Himachal Pradesh",
      "Himalayan Institute Of Nursing,Ambala - Haryana",
      "Himalayan Institute of Technology and Management - Uttar Pradesh",
      "Himalayan Instt. Hospital Trust, School Of Nursing, Dehradun - Uttaranchal",
      "Himalayan School Of Nursing, Sirmour - Himachal Pradesh",
      "Himalyan Institute Of Health Sciences, Mandi - Himachal Pradesh",
      "Himalyan Institute of Pharmacy - Himachal Pradesh",
      "Himalyan Pharmacy Institute, Gangtok - Sikkim",
      "Himalyan Polytechnic, Location Unknown - Himachal Pradesh",
      "HIMCAPES CoOperative School of Law, UNA - Himachal Pradesh",
      "Himcapes School Of Nursing, UNA - Himachal Pradesh",
      "HIMGIRI EDUCATIONAL INSTITUTE, Location Unknown - Uttaranchal",
      "HIMGIRI NABH VISHWAVIDYALAYA, Location Unknown - Uttaranchal",
      "Himgiri Zee University, Location Unknown - Uttaranchal",
      "Himmat Nagar Kelwani Mandal Law College, HIMMATNAGAR - Gujarat",
      "HIMTAJ DEGREE COLLEGE, Location Unknown - Uttar Pradesh",
      "Hina College Of Nursing, Bangalore - Karnataka",
      "Hina School Of Nursing, Bangalore - Karnataka",
      "Hind College Of Nursing, Barabanki - Uttar Pradesh",
      "Hind Institute of Medical Sciences, Barabanki - Uttar Pradesh",
      "Hind School Of Nursing, Barabanki - Uttar Pradesh",
      "HIND TEACHERS TRAINING COLLEGE, Location Unknown - Rajasthan",
      "Hindi Mahavidayalaya, NALGONDA - Andhra Pradesh",
      "HINDI PRACHARA KENDRA, Location Unknown - Kerala",
      "Hindi Teacher's Training Institute, Location Unknown - Orissa",
      "Hindi Teachers Training College, Location Unknown - Manipur",
      "Hindu College, GUNTUR - Andhra Pradesh",
      "Hindu College, Location Unknown - Uttar Pradesh",
      "Hindu College, Location Unknown - Haryana",
      "Hindu College, Location Unknown - Punjab",
      "Hindu College, DELHI - Delhi",
      "Hindu College, Location Unknown - Andhra Pradesh",
      "Hindu College Education, Location Unknown - Haryana",
      "HINDU COLLEGE OF EDUCATION, Location Unknown - Uttar Pradesh",
      "HINDU COLLEGE OF EDUCATION, Location Unknown - Uttar Pradesh",
      "Hindu College of Engineering, Location Unknown - Haryana",
      "Hindu College of Engineering and technology, Location Unknown - Andhra Pradesh",
      "Hindu College Of Management, Andhra Pradesh - Andhra Pradesh",
      "Hindu College of Pharmacy , Guntur, GUNTUR - Andhra Pradesh",
      "Hindu College of Pharmacy , SONEPAT, SONIPAT - Haryana",
      "Hindu Degree College, Uttar Pradesh - Uttar Pradesh",
      "Hindu Degree College For Women, HYDERABAD - Andhra Pradesh",
      "Hindu Girls College, Haryana - Haryana",
      "HINDU GIRLS COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Hindu Girls College, Haryana - Haryana",
      "Hindu Girls College Jagadhari, Haryana - Haryana",
      "HINDU INSTITUTE OF MANAGEMENT, Haryana - Haryana",
      "HINDU INSTITUTE OF MANAGEMENT & TECHNOLOGY, ROHTAK - Haryana",
      "Hindu Kanya College, Punjab - Punjab",
      "Hindu Kanya Mahavidyalaya, Punjab - Punjab",
      "Hindu Kanya Mahavidyalaya, Haryana - Haryana",
      "HINDU KANYA MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "Hindu Kanya Mahavidyalaya (PG) College, Uttar Pradesh - Uttar Pradesh",
      "Hindu Mission School Of Nursing , Chennai, CHENNAI - Tamil Nadu",
      "Hindu Rao Hospital , Malkaganj, DELHI - Delhi",
      "Hindu Rao Hospital, Delhi, DELHI - Delhi",
      "HINDU TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HINDU TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HINDU TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HINDU TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "HINDU TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "Hindustan Academy - Bangalore, BANGALORE - Karnataka",
      "HINDUSTAN AVIATION ACADEMY, Karnataka - Karnataka",
      "Hindustan College Of Nursing,Gulbarga, GULBARGA - Karnataka",
      "Hindustan College of Science & Technology, MATHURA - Uttar Pradesh",
      "Hindustan elect. Academy polytechnic, Karnataka - Karnataka",
      "Hindustan Institute Of Engineering Technology, TRICHY - Tamil Nadu",
      "HINDUSTAN INSTITUTE OF MANAGEMENT & COMPUTER STUDIES, Uttar Pradesh",
      "Hindustan Institute of Technology, NOIDA - Uttar Pradesh",
      "Hindustan Institute of Technology & Management, Haryana",
      "Hindustan Institute of Technology Tamil Nadu, COIMBATORE - Tamil Nadu",
      "Hindustan Polytechnic College, Tamil Nadu",
      "Hindustan Shipyard Degree College, VISAKHAPATNAM - Andhra Pradesh",
      "Hindustan University Chennai, Tamil Nadu",
      "HINDUSTANI EDUCATION SOCIETY, Maharashtra",
      "Hindusthan College Of Arts And Science, COIMBATORE - Tamil Nadu",
      "Hindusthan College Of Arts And Science, CHENNAI - Tamil Nadu",
      "HINDUSTHAN COLLEGE OF EDUCATION, Tamil Nadu",
      "Hindusthan College Of Engineering & Technology, COIMBATORE - Tamil Nadu",
      "HIRA B.ED COLLEGE, Karnataka",
      "HIRA LAL RAM NIWAS P.G. DEGREE COLLEGE, Uttar Pradesh",
      "HIRA LAL RAM NIWAS P.G. DEGREE COLLEGE, Uttar Pradesh",
      "Hira Nand Mahavidyalaya, Uttar Pradesh",
      "Hira Sugar Institute Of Technology, BELGAUM - Karnataka",
      "Hirachand Nemchand College Of Commerce, Maharashtra",
      "Hirakud College, Orissa",
      "Hiralal Bharat College, West Bengal",
      "Hiralal Ramniwas Post Graduate College, Uttar Pradesh",
      "Hiralal Ramniwas Post-graduate College, Uttar Pradesh",
      "Hiranandani College Of Nursing , Mumbai, Maharashtra",
      "HIREKERUR TALUKA VIDYAVARDHAK SAHAKARI SANGHA LTD., Karnataka",
      "HIREMATH SAMSTHAN VIDYAPEETH TRUST, Karnataka",
      "Hislop College, Maharashtra",
      "Hitech City College Of Nursing,Gulbarga, Karnataka",
      "Hitech College Of Nursing , Bhubaneshwar, Orissa",
      "HiTech Dental College & hospital , Bhubaneswar, Orissa",
      "Hitech Polytechnic College, Tamil Nadu",
      "Hitech School Of Nursing, Bhubaneswar - Orissa",
      "Hitkari Co Operative Shrmjivi Evening College - Rajasthan",
      "HITKARI CO.OP WOMENS COLLEGE OF EDUCATION - Rajasthan",
      "HITKARI TEACHER TRAINING COLLEGE - Haryana",
      "Hitkarini Arts Commerce & Science College - Madhya Pradesh",
      "Hitkarini Dental College & Hospital, Jabalpur - Madhya Pradesh",
      "Hitkarini Law College - Madhya Pradesh",
      "Hitkarini Mahila College - Madhya Pradesh",
      "Hitkarini Prashikshan Mahila Mahavidyalaya - Madhya Pradesh",
      "Hitkarni College of Engineering Technology - Madhya Pradesh",
      "HITKORI CO-UP WOMANS EDUCATION - Rajasthan",
      "Hits Degree College - Andhra Pradesh",
      "HKBK College of Engineering - Karnataka",
      "Hkdet Polytechnic - Karnataka",
      "HKE Society's PDA Engineering College - Karnataka",
      "HKEs SLN College of Engineering - Karnataka",
      "HKESs Matoshree Taradevi Rampure, Institute of Pharmaceutical Sciences, Gulbarga - Karnataka",
      "HKL TEACHER TRAINING COLLEGE - Punjab",
      "HLM COLLEGE - Uttar Pradesh",
      "HMR Institute of Technology and Management - Delhi",
      "HMS Institute Of Technology - Karnataka",
      "HMS TEACHERS TRAINING INSTITUTE - Karnataka",
      "Hojai College - Assam",
      "Holdsworth Memorial College Of Nursing, Mysore - Karnataka",
      "HOLIM MUSLIM P.G COLLEGE - Uttar Pradesh",
      "Holistic School Of Nursing, Sirsa - Haryana",
      "Holkar Science College - Madhya Pradesh",
      "Holy Angels School of Business - Tamil Nadu",
      "HOLY ANGELS TEACHER TRAINING INSTITUTE FOR WOMEN - Tamil Nadu",
      "Holy Child B.Ed College - West Bengal",
      "HOLY CRESCENT COLLEGE OF EDUCATION, Kerala - Kerala",
      "Holy Cross College, TRICHY - Tamil Nadu",
      "Holy Cross College, TRICHY - Tamil Nadu",
      "HOLY CROSS COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "Holy Cross College Of Nursing , Kollam, KOLLAM - Kerala",
      "Holy Cross College Of Nursing , Surguja, - Chhattisgarh",
      "Holy Cross College of Nursing , SURGUJA, - Chhattisgarh",
      "Holy Cross College, Nagercoil, NAGARCOIL - Tamil Nadu",
      "Holy Cross Degree College For Women, HYDERABAD - Andhra Pradesh",
      "Holy Cross Engineering College, - Tamil Nadu",
      "Holy Cross Home Science College, TUTICORIN - Tamil Nadu",
      "Holy Cross Hospital , School Of Nursing , Ambikapur, - Chhattisgarh",
      "Holy Cross Hospital, College Of Nursing,Surguja, - Chhattisgarh",
      "Holy Cross Institute Of Management And Technology, KOZHIKODE - Kerala",
      "Holy Cross School Of Nursing , Chamrajnagar, - Karnataka",
      "Holy Cross School Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
      "Holy Cross School Of Nursing,Pathanamthitta, PATHANAMTHITTA - Kerala",
      "HOLY CROSS TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "HOLY CROSS TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "HOLY FAITH PG COLLEGE, MANDAL - Andhra Pradesh",
      "Holy Family College Of Nursing , Idukki, IDUKKI - Kerala",
      "Holy Family Hospital , Delhi, DELHI - Delhi",
      "Holy Family Hospital , Koderma, - Jharkhand",
      "Holy Family Hospital , School Of Nursing , Ranchi, RANCHI - Jharkhand",
      "Holy Family Hospital , School Of Nursing,New Delhi, DELHI - Delhi",
      "Holy Family Hospital ,College Of Nursing,New Delhi, DELHI - Delhi",
      "Holy Family Institute Of Nursing Education, Thane, THANE - Maharashtra",
      "Holy Family School Of Nursing , Bangalore, BANGALORE - Karnataka",
      "Holy Family School Of Nursing,Idukki, IDUKKI - Kerala",
      "HOLY FAMILY TRAINING COLLEGE FOR WOMEN, - Kerala",
      "Holy Fatima School of Nursing, Hyderabad - Andhra Pradesh",
      "HOLY FLOWERS TEACHER TRAINING INSTITUTE, Pondicherry - Pondicherry",
      "Holy Ghost Mission Hospital, Kottayam - Kerala",
      "HOLY GRACE ACADEMY OF MANAGEMENT STUDIES, Kerala - Kerala",
      "Holy Institute Of Technology, Orissa - Orissa",
      "Holy Jesus & Mary Pg College Of Computer Science, Secunderabad - Andhra Pradesh",
      "Holy Mary College Of Nursing, Hyderabad - Andhra Pradesh",
      "Holy Mary Institute Of Tech. & Science, Andhra Pradesh - Andhra Pradesh",
      "Holy Mary Institute of Technology & Management, Andhra Pradesh - Andhra Pradesh",
      "Holy Mother Institute Of Nursing, Bangalore - Karnataka",
      "HOLY MOTHER PG COLLEGE, Hyderabad - Andhra Pradesh",
      "Holy Nursing School, Muktsar - Punjab",
      "Holy Spirit Institute Of Nursing Education, Mumbai - Maharashtra",
      "Holy Spirit School Of Nursing, Mumbai - Maharashtra",
      "HOLY TRINITY COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "HOME SCIENCE COLLEGE AND RESEARCH INSTITUTE, MADURAI - Tamil Nadu",
      "Homi Bhabha National Institute, Maharashtra - Maharashtra",
      "Homoeopathic Medical College, Akola - Maharashtra",
      "Homoeopathic Medical College and Hospital, Chandigarh - Chandigarh",
      "Homoeopathic Medical College and Hospital, Gulbarga - Karnataka",
      "Homoeopathy University, Rajasthan - Rajasthan",
      "Hon'able Loksevak Madhukarrao Chaudhari College of Pharmacy, Maharashtra - Maharashtra",
      "Hooghly B.C. Roy Institute, West Bengal - West Bengal",
      "Hooghly Engineering & Technology College, West Bengal - West Bengal",
      "Hooghly Institute of Technology, West Bengal - West Bengal",
      "Hooghly Mohsin College, Chinsurah - West Bengal",
      "Hooghly Pratyay Vidyaniketan, A N M Training School, Hooghly - West Bengal",
      "Hooghly Womens College, West Bengal - West Bengal",
      "HOPE, Durgapur - West Bengal",
      "Hope Educational and Welfare Trust, West Bengal - West Bengal",
      "Horizon Institute of Technology, RANGAREDDY - Andhra Pradesh",
      "Horsley Hills College Of Nursing,Chittoor, CHITOOR - Andhra Pradesh",
      "Horsleyhills College Of Nursing , Chittoor, CHITOOR - Andhra Pradesh",
      "HORTICULTURAL COLLEGE AND RESEARCH INSTITUTE,PERIYAKULAM, Periyakulam - Tamil Nadu",
      "HORTICULTURE COLLEGE AND RESEARCH INSTITUTE, COIMBATORE, COIMBATORE - Tamil Nadu",
      "HOSHIARPUR INSTITUTE OF MGT & TECH, Hoshiarpur - Punjab",
      "Hoskote Mission Institute Of Nursing , Bangalore, BANGALORE - Karnataka",
      "Hoskote Mission Institute Of Nursing,Bangalore, BANGALORE - Karnataka",
      "Hosmat College Of Nursing , Bangalore, BANGALORE - Karnataka",
      "Hosmat College Of Nursing, ,Bangalore, BANGALORE - Karnataka",
      "Hosur Institute of Technology and Science, Hosur - Tamil Nadu",
      "Hoyasaleswara College, Hoyasaleswara - Karnataka",
      "HP Institute of Management Studies, HP Institute - Himachal Pradesh",
      "Hrangbana College, Hrangbana - Mizoram",
      "HRIT Group of Institutions, HRIT - Uttar Pradesh",
      "HRSPMs Law College, PUNE - Maharashtra",
      "Hrudyananda Samarak Mahavidyalaya, Hrudyananda - Orissa",
      "HSM  Polytechnic, HSM - Haryana",
      "HTP COLLEGE OF EDUCATION, HTP - Tamil Nadu",
      "Hubli Institute Of Nursing Sciences , Hubli, HUBLI - Karnataka",
      "HULIYAPPA MALAMMA B.ED COLLEGE, Huliyappa - Karnataka",
      "HULKOTI CO OP EDUCATION, Hulkoti - Karnataka",
      "Hullcoti Co Operative Education Society Arts Science Commerce College Gadag, Gadag - Karnataka",
      "Human Resource Development Engineering College, DEVERAKONDA - Andhra Pradesh",
      "Human Torch Anm School , Jamnagar, JAMNAGAR - Gujarat",
      "Human Torch School Of Nursing , Jamnagar, JAMNAGAR - Gujarat",
      "HUMERA KHAN COLLEGE OF EDUCATION, HUMERA - Maharashtra",
      "Hurakadli Ajja Law College, DHARWAD - Karnataka",
      "HUSSAINI D ED COLLEGE, HUSSAINI - Karnataka",
      "Hutatma Institute Of Nursing,Sangli, SANGLI - Maharashtra",
      "Hutatma Rajguru Mahvidyalaya, Maharashtra - Maharashtra",
      "Hutatma Rashtriya Arts & Science College, Maharashtra - Maharashtra",
      "Hyderabad (Sind) National Collegiate Boards Navi Gursahani Law College, Thane - Maharashtra",
      "Hyderabad Degree College, Hyderabad - Andhra Pradesh",
      "Hyderabad Institute of Technology & Management Royal, Medak - Andhra Pradesh",
      "HYDERABAD PRESIDENCY COLLEGE, Hyderabad - Andhra Pradesh",
      "HYDERABAD PRESIDENCY COLLEGE PG CENTER, Rajendernagar - Andhra Pradesh",
      "HYDERABAD SCHOOL OF MGT, Mandal - Andhra Pradesh",
      "Hyderabad Sind National Collegiate Boards Nari Gursahani Law College, Thane - Maharashtra",
      "Hyderabad Study Circle, Domalguda - Andhra Pradesh",
      "HYMANSHU JYOTHI KAKA PEETHA PPTTI, Karnataka - Karnataka",
    ],
  },
];
