const LData = [
  {
    colleges: [
      "L B S Memorial College, Jharkhand - Jharkhand",
      "L C Bharali College, Assam - Assam",
      "L Chaobi Nursing Institute , Imphal, Imphal - Manipur",
      "L D H T Nursing School,Hingoli, Maharashtra - Maharashtra",
      "L G B Regional Institute Of Mental Health , Tezpur, Tezpur - Assam",
      "L K C Jagdamba Andh Vidyalaya Samiti, Hanumangarh - Rajasthan",
      "L M R College Of Nursing , Gwalior, Gwalior - Madhya Pradesh",
      "L N College, Bihar - Bihar",
      "L N D College, Bihar - Bihar",
      "L N Gupta College Science Commerce, Hyderabad - Andhra Pradesh",
      "L N Janta College, Bihar - Bihar",
      "L N K College Education, Gujarat - Gujarat",
      "L N Mishra B Jha Mahila College, Bihar - Bihar",
      "L N Mishra Memorial College, Bihar - Bihar",
      "L N Nursing College , Bhopal, Bhopal - Madhya Pradesh",
      "L N Nursing School, Bhopal - Madhya Pradesh",
      "L N Rameshwar Sanskrit Mahavidyalaya, Bihar - Bihar",
      "L N T COLLEGE OF EDUCATION, Haryana - Haryana",
      "L N T Mahavidyalaya, Bihar - Bihar",
      "L R Valia Arts And P R Mehta Commerce College, Gujarat - Gujarat",
      "L S College, Bihar - Bihar",
      "L T K College, Assam - Assam",
      "L,J Polytechnic, Gujarat - Gujarat",
      "L. B. S. Law College, Madhya Pradesh - Madhya Pradesh",
      "L. M. G. Memorial Law College, Manipur - Manipur",
      "L. M. S. Law College, Imphal - Manipur",
      "L. Patel Centre for Science and Technology, Anand - Gujarat",
      "L. R. Institute of Legal Studies, Solan - Himachal Pradesh",
      "L.A.S.E.DEPARTMENT OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "L.B.S College of Engineering, Kerala - Kerala",
      "L.B.S. INSTITUTE OF MANAGEMENT STUDIES & RESEARCH, CHANDIGARH - Chandigarh",
      "L.B.S. P.G COLLEGE,  - Uttar Pradesh",
      "L.B.S. P.G. COLLEGE,  - Uttar Pradesh",
      "L.B.S. TEACHER TRAININGINSTITUTE,  - Rajasthan",
      "L.C.R.T. TEACHER TRAINING COLLEGE,  - Haryana",
      "L.E.S. Smt. K. Mirji Arts And Commerce College,  - Karnataka",
      "L.G. TEACHER TRAINING COLLEGE,  - Haryana",
      "L.J. Institute of Computer Applications,  - Gujarat",
      "L.J. Institute of Engineering & Technology, AHMEDABAD - Gujarat",
      "L.J. INSTITUTE OF MANAGEMENT STUDIES,  - Gujarat",
      "L.J. Institute of Pharmacy , Ahmedabad, AHMEDABAD - Gujarat",
      "L.L.R.M. Medical College,  - Uttar Pradesh",
      "L.L.R.M.Medical College, Meerut, MEERUT - Uttar Pradesh",
      "L.M. College of Pharmacy , ,AHMEDABAD, AHMEDABAD - Gujarat",
      "L.M.S. Law College,  - Manipur",
      "L.N COLLEGE,  - Uttar Pradesh",
      "L.N. Medical College and Research Centre,Bhopal, BHOPAL - Madhya Pradesh",
      "L.N.INSTITUTE OF TEACHER EDUCATION,  - Rajasthan",
      "L.N.M. COLLEGE OF BUSINESS MANAGEMENT, BHAGALPUR - Bihar",
      "L.N.M. Institute Of Economic Development & Social Change, PATNA - Bihar",
      "L.N.Mishra College of Business Management,  - Bihar",
      "L.N.T. TEACHER TRAINING COLLEGE,  - Haryana",
      "L.P. POST GRADUAT COLLEGE,  - Uttar Pradesh",
      "L.R. COLLEGE OF ADVANCED STUDIES,  - Delhi",
      "L.R. INSTITUTE OF EDUCATION,  - Himachal Pradesh",
      "L.R. Institute of Engineering and Technology,  - Himachal Pradesh",
      "L.R. Institute of Legal Studies, SOLAN - Himachal Pradesh",
      "L.R. INSTITUTE OF MANAGEMENT,  - Himachal Pradesh",
      "L.R. Polytechnic,  - Himachal Pradesh",
      "L.R.G. Government Arts & Science College For Women, COIMBATORE - Tamil Nadu",
      "L.T.R. INSTITUTE OF TECHNOLOGY, Uttar Pradesh - Uttar Pradesh",
      "L.V.H. Arts Science & Commerce College, Maharashtra - Maharashtra",
      "L.V.R. NAIDU COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "LABOUR INDIA COLLEGE OF TEACHER EDUCATION, Kerala - Kerala",
      "Lachoo Memorial College Of Science, Rajasthan - Rajasthan",
      "Lachoo Memorial College of Science & Technology , Jodhpur, Rajasthan - Rajasthan",
      "LAD and Smt. SRP College for Women, Maharashtra - Maharashtra",
      "LADWA TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "Lady Barabourne College, West Bengal - West Bengal",
      "Lady Doak College, Tamil Nadu - Tamil Nadu",
      "Lady Harding Medical College & Hospital, Delhi - Delhi",
      "Lady Hardinge Medical College, New Delhi, Delhi - Delhi",
      "Lady Health Visitors School , Patna, Bihar - Bihar",
      "Lady Irwin College, Delhi - Delhi",
      "Lady Irwin College, New Delhi, Delhi - Delhi",
      "Lady Kean Girls College, Meghalaya - Meghalaya",
      "Lady Reading Health School , Delhi, Delhi - Delhi",
      "Lady Reid Basic Training Centre, Meghalaya - Meghalaya",
      "Lady Shri Ram College For Women, New Delhi, Delhi - Delhi",
      "LADY WILLINGDON INSTITUTE OF ADVANCED STUDY IN EDUCATION, Tamil Nadu - Tamil Nadu",
      "Lady Willingdon Training College, Chennai, Tamil Nadu - Tamil Nadu",
      "LAHERI TEACHERS TRAINING COLLEGE, Rajasthan - Rajasthan",
      "Lahoti Degree College, Kondanagula, Andhra Pradesh - Andhra Pradesh",
      "Lajjawati Jain Memorial Nursing Institute , Ludhiana, Punjab - Punjab",
      "Lajjiawati Jain Memorial Nursing Institute , Ludhiana, Punjab - Punjab",
      "Lajpat Rai College, Uttar Pradesh - Uttar Pradesh",
      "Lajpat Rai D.A.V. College, Punjab - Punjab",
      "Lajpat Rai Law College, Sambalpur, Orissa - Orissa",
      "Lake Side College Of Nursing , Bangalore, Karnataka - Karnataka",
      "Lake Side Medical Centre & Hosp Sch Of Nsg., Bangalore, Karnataka - Karnataka",
      "LAKHAN LAL SAHRAN SINGH MAHAIDAYALYA, Uttar Pradesh - Uttar Pradesh",
      "LAKHAN LAL SHARAN SINGH MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "Lakhdhirji Engineering College, Gujarat - Gujarat",
      "Lakhimpur Commerce College, Assam - Assam",
      "Lakhimpur Girls College, Assam - Assam",
      "Lakhimpur Kendriya Mahavidyalaya, Assam - Assam",
      "Lakhimpur Post Graduate Training College, Assam - Assam",
      "Lakhipur College, LAKHIMPUR - Assam",
      "Lakhmi Chand Institute of Technology, Chhattisgarh - Chhattisgarh",
      "LAKHMI CHAND PATWARI COLLEGE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "LAKHMI CHAND PATWARI COLLEGE OF EDUCATION, Uttar Pradesh - Uttar Pradesh",
      "Lakireddy Bali Reddy College of Engineering, Andhra Pradesh - Andhra Pradesh",
      "Lakshay College of Hotel Management, Haryana - Haryana",
      "LAKSHAY INSTITUTE OF EDUCATION, Himachal Pradesh - Himachal Pradesh",
      "LAKSHAY INSTITUTE OF MGT. STUDIES, PANIPAT - Haryana",
      "LAKSHAY TEACHER TRAINING COLLEGE, Haryana - Haryana",
      "LAKSHMI AMMAL COLLEGE OF EDUCADTION, Tamil Nadu - Tamil Nadu",
      "Lakshmi Ammal Polytechnic College, TRICHY - Tamil Nadu",
      "Lakshmi Ammal School Of Nursing, Chengalpattu, Tamil Nadu - Tamil Nadu",
      "Lakshmi Bai Batra College Of Nursing, DELHI - Delhi",
      "Lakshmi Bai College, DELHI - Delhi",
      "Lakshmi Bai National College of Physical Education, Kerala - Kerala",
      "LAKSHMI COLLEGE OF EDUCATION, Tamil Nadu - Tamil Nadu",
      "Lakshmi Devi School Of Nursing , Bangalore Rural, Karnataka - Karnataka",
      "Lakshmi M P H W F Trg Institute,Hyderabad, Andhra Pradesh - Andhra Pradesh",
      "Lakshmi Narain College Of Technology, Madhya Pradesh - Madhya Pradesh",
      "Lakshmi Narain College of Technology & Science, Madhya Pradesh - Madhya Pradesh",
      "LAKSHMI NARAYAN MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "Lakshmi Narayanan Visalakshi College Of Arts And Science, COIMBATORE - Tamil Nadu",
      "Lakshmi School Of Nursing , Hyderabad, Andhra Pradesh - Andhra Pradesh",
      "Lakshmi School Of Nursing, Ernakulam - Kerala",
      "Lakshmi Subramaniyan Poltechnic College - Tamil Nadu",
      "LAKSHMI TEACHER TRAINING INSTUTUTE - Tamil Nadu",
      "Lakshmi Venkatesh T G College Of Nursing, Kurnool - Andhra Pradesh",
      "LAKSHMIAMMAL COLLEGE OF EDUCATION - Tamil Nadu",
      "Lakshmiammal Polytechnic College - Tamil Nadu",
      "LAKSHMIAMMAL TEACHER TRAINING INSTITUTE - Tamil Nadu",
      "Lakshmibai National Institute Of Physical Education - Madhya Pradesh",
      "LAKSHMIBAI NATIONAL INSTITUTE OF PHYSICAL EDUCATION - Madhya Pradesh",
      "LAKSHYA DEEP SHIKSHAK PRASHIKSHAN SANSTHAN - Rajasthan",
      "Lakshya Institute Of Nursing, Gwalior - Madhya Pradesh",
      "LAKSSHMI AMMAL COLLEGE OF EDUCATION FOR WOMEN - Tamil Nadu",
      "Lal Baba College - West Bengal",
      "LAL BAHADHUR D.ED COLLEGE - Karnataka",
      "LAL BAHADHUR SHASTRI STC SCHOOL - Rajasthan",
      "Lal Bahadur Arts Science And S.B. Selabanna Setty Comm. Co - Karnataka",
      "Lal Bahadur College - Andhra Pradesh",
      "Lal Bahadur College, Hyderabad - Andhra Pradesh",
      "Lal Bahadur Memorial Mahila College - Punjab",
      "LAL BAHADUR SHASHTRI POST GRADUTE COLLEGE - Uttar Pradesh",
      "LAL BAHADUR SHASHTRI TEACHER TRAINING COLLEGE - Rajasthan",
      "LAL BAHADUR SHASTRI - Uttar Pradesh",
      "LAL BAHADUR SHASTRI - Uttar Pradesh",
      "Lal Bahadur Shastri College - Rajasthan",
      "Lal Bahadur Shastri College Of Arts Science & Commerce - Maharashtra",
      "Lal Bahadur Shastri College Post Graduate, Jaipur - Rajasthan",
      "Lal Bahadur Shastri Degree College - Uttar Pradesh",
      "Lal Bahadur Shastri Degree College - Uttar Pradesh",
      "Lal Bahadur Shastri Government College - Rajasthan",
      "Lal Bahadur Shastri Government Degree College - Himachal Pradesh",
      "Lal Bahadur Shastri Government First Grade College, Karnataka - Karnataka",
      "Lal Bahadur Shastri Homoeopathic Medical College, Madhya Pradesh - Madhya Pradesh",
      "Lal Bahadur Shastri Inst. of Management, Delhi - Delhi",
      "Lal Bahadur Shastri Institute of Management Development Studies, Uttar Pradesh - Uttar Pradesh",
      "Lal Bahadur Shastri Institute of Management Studies and Research, Bilaspur - Chhattisgarh",
      "Lal Bahadur Shastri Mahavidyalaya, Maharashtra - Maharashtra",
      "Lal Bahadur Shastri Mahavidyalaya (ARTSSC&COM), Maharashtra - Maharashtra",
      "Lal Bahadur Shastri National Academy of Administration, Uttaranchal - Uttaranchal",
      "Lal Bahadur Shastri School of Nursing, Yamuna Nagar, Haryana - Haryana",
      "Lal Bahadur Shastri Smarak Degree College, Uttar Pradesh - Uttar Pradesh",
      "Lal Bahadur Shastri Technical Institute, Uttaranchal - Uttaranchal",
      "Lal Bahadur Shastri Vyavsayik Adhyayan Mahavidyalaya, Madhya Pradesh - Madhya Pradesh",
      "Lal Bahadur Shastri, Sch. Of Nsg, Yamunanagar, Haryana - Haryana",
      "Lal Bahadur Singh Smarak Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "Lal Bhadur Shastri Smark P.G. College, Uttar Pradesh - Uttar Pradesh",
      "Lal Bhadur Shastri Mahila Shikshak Prasshikshan Mahavidyalaya, Rajasthan - Rajasthan",
      "Lal Bhadur Shastri Teacher Training College, Haryana - Haryana",
      "Lal Bhahadur Shastri Technical Education Institute, Uttaranchal - Uttaranchal",
      "Lal Bhai Dalpathbhai Arts College, Gujarat - Gujarat",
      "Lal Chand Mal Teacher Training College, Haryana - Haryana",
      "Lal Gee Polytechnic, Himachal Pradesh - Himachal Pradesh",
      "Lal Memorial Hospital, Thrissur, Kerala - Kerala",
      "Lal Singh Tyagi Gramin College, Bihar - Bihar",
      "Lal Singh Tyagi Gramin Mahavidyalaya, Bihar - Bihar",
      "Lala Ami Chand Monga Memorial College of Law, Ambala - Haryana",
      "Lala Ami Chand Monga Memorial Teacher Training College, Haryana - Haryana",
      "Lala Hans Raj Memorial Teacher Training College, Punjab - Punjab",
      "Lala Hans Raj Phutela College of Law, Sirsa - Haryana",
      "Lala Jagat Narayan Education College, Punjab - Punjab",
      "LALA JAGAT NARAYAN EDUCATION COLLEGE, Punjab",
      "Lala Lajpat Rai College of Law, Maharashtra",
      "Lala Lajpat Rai College of Pharmacy, Moga, Punjab",
      "Lala Lajpat Rai Government College, Punjab",
      "Lala Lajpat Rai Institute of Engineering & Technology, Punjab",
      "Lala Lajpat Rai Institute Of Nsg Education, School Of Nursing, Jalandhar, Punjab",
      "Lala Lajpat Rai Institute Of Nursing, Moga, Punjab",
      "Lala Lajpat Rai Institute Of Nursing Education, Jalandhar, Punjab",
      "LALA LAJPAT RAI MEMORIAL TEACHER TRAINING COLLEGE, Punjab",
      "Lala Lajpat Rai School Of Nursing, Moga, Punjab",
      "Lala Lajpat Rai University of Veterinary, Haryana",
      "Lala Lajpatrai College of Commerce & Economics, Maharashtra",
      "LALA LAJPATRAI INSTITUTE OF MANAGEMENT, Maharashtra",
      "LALA LAXMI NARAIN DEGREE COLLEGE, Uttar Pradesh",
      "Lala Mahadev Prasad Verma Balika Mahavidyalaya, Uttar Pradesh",
      "LALA MALTADEO PRASAD VERMA BALIKA DEGREE COLLEGE, Uttar Pradesh",
      "Lala Mangat Ram Mahavidyalaya, Delhi",
      "LALA MANGAT RAM MAHAVIDYALAYA, Uttar Pradesh",
      "Lala Munshi Ram Institue Of Health Sciences, Gurdaspur, Punjab",
      "Lala Rural College, Assam",
      "LALAMAUGAT RAM MAHAVIDYALAYA, Uttar Pradesh",
      "Lalbhai Dalpatbhai College of Engineering, Mehsana, Gujarat",
      "LALGEE TEACHER TRAINING COLLEGE, Himachal Pradesh",
      "Lalgudi Co Operative Polytechnic College, Tamil Nadu",
      "Lalgudi Co-Operative Polytechnic College, Madurai, Tamil Nadu",
      "Lalit Chandra Bharali College Guwahati, Assam",
      "Lalit Narayan Mishra College Business Mana, Bihar",
      "Lalit Narayan Mishra Institute of Economic Development And Social Change, Bihar",
      "Lalit Narayan Mithila University, Darbhanga, Bihar",
      "LALITA DEVI INSTITUTE OF MANAGEMENT & SCIENCE, Himachal Pradesh",
      "Lalita Naryan Mishra Institute Economic Development Social Change, Bihar",
      "Laliteshwar Prasad Shahi College, Bihar",
      "Lalitha College Of Nursing,Eastgodavari, Andhra Pradesh",
      "Lalitha College Of Nursing,Guntur, Andhra Pradesh",
      "Lalitha College of Pharmacy , Ghatkesar, Andhra Pradesh",
      "Lalitha Degree & Pg College, Andhra Pradesh",
      "LALITHA DEGREE & PG COLLEGE, GHATKESAR, Andhra Pradesh",
      "Lalithaa School Of Nursing , Coimbatore, Tamil Nadu",
      "Lalji Rai Degree College, Uttar Pradesh",
      "Lalta Singh Government Girls P.G. College, Uttar Pradesh",
      "Laluk College, Assam",
      "Lamka College, Manipur",
      "Lamp Degree College, Andhra Pradesh",
      "Langta Baba College, Jharkhand",
      "Lanka Mahavidyalaya, Assam",
      "Laqsha College Of Computer Studies, Andhra Pradesh",
      "Laqshya Institute of Technology & Sciences, Andhra Pradesh",
      "Larambha College, Orissa",
      "Larn Edutech, West Bengal",
      "LATA MANGAT RAM MAHAVIDYALAYA, Uttar Pradesh",
      "LATE A.M.PATIL PUBLIC EDUCATION SOCIETYS MANKARANABAI VINAYAKRAO MARATHI COLLEGE OF EDUCATION, Maharashtra",
      "Late Ahilyabai Kakade Bahuuddeshiya Shikshan Prasarak Mandal, Maharashtra",
      "Late Amrutrao Patil Pratishthan Khed, Maharashtra",
      "LATE ANIL RAMDAS KAMBE B.ED. COLLEGE, Maharashtra",
      "Late Annasaheb Patil's Polytechnic, Maharashtra",
      "Late Appasaheb R.B. Garud Arts And Commerce College, Maharashtra",
      "Late Babasaheb Deshmukh Gorthekar Mahavidyalaya, Maharashtra",
      "Late Babu Singh Balika Mahavidyalaya, Uttar Pradesh",
      "LATE BAHADUR SINGH MAHAVIDYALAYA, Uttar Pradesh",
      "Late Bhagwant Patel Panmati Devi Mahavidyalaya, Uttar Pradesh",
      "LATE BHAUSAHEB HIRAY S.S. TRUST INSTITUTE OF COMPUTER APPLICATIONS, MUMBAI - Maharashtra",
      "LATE DADARAO ADSAD SHARIRIK SHIKSHAN MAHAVIDHYALAYA,   - Maharashtra",
      "Late Dadasaheb Chavan Memorial Institute of Pharmacy , Karad, KARAD - Maharashtra",
      "Late Dattatraya Pusadkar Arts College,   - Maharashtra",
      "LATE DILEEP KUMAR SMARAK MAHAVIDYALAYA,   - Uttar Pradesh",
      "Late Dr. Haribhau Admane Arts & Commerce College,   - Maharashtra",
      "Late Dr. Shankar Rao Satav College,   - Maharashtra",
      "Late Freedom Fighter Manikraoji Muley Special Teachers Training Institute for Mental Retardation, LATUR - Maharashtra",
      "Late Freedom Fighter Ramchndraraoji Muley Teachers Training Institute (DSEHI), LATUR - Maharashtra",
      "LATE GOVINDRAO PATIL COLLEGE OF EDUCATION,   - Maharashtra",
      "LATE GULABBAI SMRUTI LATE GULABBAI YADAV S.S.M,   - Madhya Pradesh",
      "LATE H.G. ALIAS BALASAHEB KHARADE COLLEGE OF EDUCATION,   - Maharashtra",
      "Late Karamveer Dr. P.R. Ghogrey Science College,   - Maharashtra",
      "LATE KHATIJA COLLEGE OF EDUCATION,   - Maharashtra",
      "LATE KUMARI LAXMI BADHALA MAHILA TEACHERS TRAINING COLLEGE,   - Rajasthan",
      "LATE LALA SAHEB DESHMUKH D.ED. COLLEGE,   - Maharashtra",
      "LATE MADHAVRAO TIDKE SHARIRIK SHIKSHAN MAHAVIDYALA,   - Maharashtra",
      "LATE MADHURIBAI DESHMUKH SHARIRIK SHIKSHAN MAHAVIDHYALAYA,   - Maharashtra",
      "Late Maharudra Bappa Mote College of Pharmacy , Osmanabad, OSMANABAD - Maharashtra",
      "Late Minaben Kundalia Mahila Arts And Commerce College,   - Gujarat",
      "Late MLC Vasantraoji Kale Law College, AURANGABAD - Maharashtra",
      "Late Mrs Anusaya & Savitri Thakur Memorial School Of Nursing,Pune, PUNE - Maharashtra",
      "LATE NARAYAN SINGH UIKEY SHARIRIK SHIKSHAN MAHAVIDYALAYA,   - Maharashtra",
      "Late Narayandas Bhawandas Chhabada School Of Nursing,Satara, SATARA - Maharashtra",
      "Late Narayanrao Amrutrao Deshmukh Arts and Commerc,   - Maharashtra",
      "LATE NIRDHANRAO PATIL WAGHAYE ADHYAPAK MAHAVIDYALAYA,   - Maharashtra",
      "Late Panchfulabai Pawade Arts & Commerce,   - Maharashtra",
      "Late Panchfulabai Pawade Arts & Commerce Mahila Mahavidyalaya,   - Maharashtra",
      "Late Pandurang Patil Nursing College , Akola, AKOLA - Maharashtra",
      "LATE PT. SURYA NARAYAN RAJ MISHRA TEACHERS TRAINING COLLEGE,   - Rajasthan",
      "LATE PUNDLIKRAO TIRPUDE COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "Late Raghunathrao Mundhe Institute Of Nursing,Beed, BEED - Maharashtra",
      "Late Raghunathraoji Kendre Nursing School,Beed, BEED - Maharashtra",
      "LATE RAM PRASAD YADAV DEGREE COLLEGE, Uttar Pradesh - Uttar Pradesh",
      "Late Ram Prasad Yadav Mahavidyalaya, Uttar Pradesh - Uttar Pradesh",
      "LATE RAMRAOJI DUDHE COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "LATE RAMSWAROOP YADAV MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "Late Ratibhai Prabhudas Patel Nursing College,Anand, ANAND - Gujarat",
      "LATE SANJAY TOMPE & LATE SAMEER DESHMUKH B.ED.COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "Late Sh.Madan Gopalji Mundhada Kala And Vanijya Mahavidyalaya, Maharashtra - Maharashtra",
      "LATE SHIVRAMJI HIWSE B.ED. COLLEGE, Maharashtra - Maharashtra",
      "Late Shri G. W. College of Law, NAGPUR - Maharashtra",
      "Late Shri Ganpatrao Deshmukh Trg College Of Nsg , Nagpur, NAGPUR - Maharashtra",
      "LATE SHRI GOVINDRAO WANJARI COLLEGE OF EDUCATION, Maharashtra - Maharashtra",
      "LATE SHRI LAXMANJI MOTGHARE CHARITABLE TRUST, Maharashtra - Maharashtra",
      "Late Shri N R Boricha Education Trust Sanchalit, Gujarat - Gujarat",
      "Late Shri Yashwantrao Chavan Memorial Medical & Rural Development Foundations Dental College & Hosp, AHMEDNAGAR - Maharashtra",
      "LATE SHRIMATI B.F. KADRI COLLEGE OF WOMENS EDUCATION, Daman and Diu - Daman and Diu",
      "Late Sou Kamal Tai Jamkar Mahila Mahavidyalaya, Maharashtra - Maharashtra",
      "Late Sow Sheshabai Sitaram Mundhe Arts College, Maharashtra - Maharashtra",
      "LATE VASANTRAO NAIK COLLEGE OF PHYSICAL EDUCATION, Maharashtra - Maharashtra",
      "Late Wali Mohammad Islamiya Degree College, Uttar Pradesh - Uttar Pradesh",
      "Latha Madhavan Engineering College, MADURAI - Tamil Nadu",
      "Latha Mathavan Polytechnic College, DHARMAPURI - Tamil Nadu",
      "Latha Mathavan Polytechnic College, Tamil Nadu - Tamil Nadu",
      "Latur College of Pharmacy , Latur, LATUR - Maharashtra",
      "LAVANYA COLLEGE OF EDUCATION, Karnataka - Karnataka",
      "Law College, JUNAGADH - Gujarat",
      "Law College, GODHRA - Gujarat",
      "Law College, HIMMATNAGAR - Gujarat",
      "Law College, Madhya Pradesh - Madhya Pradesh",
      "Law College, BETUL - Madhya Pradesh",
      "Law College, SATNA - Madhya Pradesh",
      "Law College, MOTIHARI - Bihar",
      "Law College, DURGAPUR - West Bengal",
      "Law College, Kerala - Kerala",
      "Law College, Kerala - Kerala",
      "Law College, Madhya Pradesh - Madhya Pradesh",
      "Law College, Maharashtra - Maharashtra",
      "Law College Dehradun, DEHRADUN - Uttaranchal",
      "Law School, JAMMU - Jammu and Kashmir",
      "Laxmanrao Mankar College Of Polytechnic, Maharashtra - Maharashtra",
      "Laxmanrao Umak Moemorial Nursing School,Amrvati, AMRAVATI - Maharashtra",
      "Laxmi Bai Batra College of Nursing , Delhi, DELHI - Delhi",
      "Laxmi Bai Shahuji, College of Pharmacy , Jabalpur, JABALPUR - Madhya Pradesh",
      "LAXMI BAL MAHILA SANSKRIT TEACHERS TRAINNG INSTITUTE, Rajasthan - Rajasthan",
      "Laxmi Barah College, Orissa - Orissa",
      "LAXMI CHARAN HUBBLAL MAHAVIDYALAYA, Uttar Pradesh - Uttar Pradesh",
      "LAXMI COLLEGE OF EDUCATION, Haryana - Haryana",
      "Laxmi College Of Nursing , Hyderabad, HYDERABAD - Andhra Pradesh",
      "Laxmi College Of Nursing Sciences, GWALIOR - Madhya Pradesh",
      "Laxmi Devi Arya Kanya Girls Degree College, Uttar Pradesh - Uttar Pradesh",
      "Laxmi Devi Institute of Engg & Technology, Rajasthan - Rajasthan",
      "Laxmi Devi Institute of Engineering and Technology, Rajasthan - Rajasthan",
      "Laxmi Institute of Management, Sarigam, Gujarat - Gujarat",
      "Laxmi Meghal College Of Nursing , Kasaragod, KASARAGOD - Kerala",
      "Laxmi Memorial College Of Nursing , Mangalore, MANGALORE - Karnataka",
      "Laxmi Memorial College of Nursing, Mangalore, MANGALORE - Karnataka",
      "Laxmi Memorial Instt Of Nursing , Mangalore, MANGALORE - Karnataka",
      "Laxmi Memorial Instt. Of Nursing , Mangalore, MANGALORE - Karnataka",
      "Laxmi Memorial Instt. Of Nursing, Mangalore - Karnataka",
      "Laxmi Narayan Degree College - Orissa",
      "Laxmi Narayan Mahavidyalaya - Uttar Pradesh",
      "LAXMI NARAYAN TIWARI TEACHER TRAINING COLLEGE, - Rajasthan",
      "Laxmi Narayana College of Pharmacy , Dharmapuri - Tamil Nadu",
      "Laxmi Narayana Mahavidyalaya - Orissa",
      "Laxmi Narayana Polytechnic College - Tamil Nadu",
      "Laxmi Narayana School Of Nursing, , Dharmapuri - Tamil Nadu",
      "Laxmi Polytechnic College, Jaipur - Rajasthan",
      "LAXMI RATAN SHAH B.ED COLLEGE - Maharashtra",
      "Laxmi School Of Nursing , Samadhanapeta - Andhra Pradesh",
      "Laxmi School Of Nursing , Vizianagaram - Andhra Pradesh",
      "Laxmi School Of Nursing Sciences , Gwalior - Madhya Pradesh",
      "Laxmi Venkatesh Desai College - Karnataka",
      "Laxmi Yadunandan Degree College - Uttar Pradesh",
      "Laxmibai College Of Nursing , Bhandara - Maharashtra",
      "LAXMIBAI MAHILA TEACHERS TRAINING COLLEGE - Rajasthan",
      "Laxmibai Waghaye Nursing School, Bhandara - Maharashtra",
      "LAXMICHAND KATORI DEVI MAHAVIDYALAYA - Uttar Pradesh",
      "Laxmikanta College - Orissa",
      "Laxminarayan College - Orissa",
      "Laxminarayan College of Technology - Madhya Pradesh",
      "Laxminarayan Institute Of Technology - Maharashtra",
      "Laxminarayan Institute Of Technology - Maharashtra",
      "Laxminarayan Institute Of Technology - Maharashtra",
      "Laxminarayana Polytechnic College - Tamil Nadu",
      "Laxmipati Institute of Science and Technology, Bhopal - Madhya Pradesh",
      "Laxshmipuram College of Arts & Science - Tamil Nadu",
      "Layola Polytechnic, Pulivendula - Andhra Pradesh",
      "Lazarus School Of Nursing , Visakhapatnam - Andhra Pradesh",
      "LBS Institute of Technology for Women, TRIVANDRUM - Kerala",
      "LBS Polytechnic College, - Rajasthan",
      "LBS Polytechnic College, Jodhpur, - Rajasthan",
      "LC Institute of Technology, - Gujarat",
      "LCRT TEACHER TRAINING COLLEGE, - Haryana",
      "LDC Institute of Technology Studies, ALLAHABAD - Uttar Pradesh",
      "Lead College Of Management, - Kerala",
      "Leas Hurakadli Ajja Law College, - Karnataka",
      "Ledo College, - Assam",
      "Leela College Of Nursing,Hubli, HUBLI - Karnataka",
      "Leela Degree College, Huzurabad, HUZURABAD - Andhra Pradesh",
      "LEELA KALYAN TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "Leela Krishna Babuji Polytechnic,Ravulapalem, - Andhra Pradesh",
      "LEELA WATI WELFARE SOCIETY, - Madhya Pradesh",
      "Leelabai Thackersey College Of Nursing , Mumbai, MUMBAI - Maharashtra",
      "Leelaben Dashrathbhai Ramdas Patel Institute of Technology, GANDHI NAGAR - Gujarat",
      "Leeladevi Parasmal Sancheti Kanya Mahavidyalaya, - Rajasthan",
      "LEELAVATHI SHETTY COLLEGE OF EDUCATION, - Karnataka",
      "Lendy Degree College, Nellore, NELLORE - Andhra Pradesh",
      "Lenora College of Engineering, - Andhra Pradesh",
      "Lenora Institute of Dental Sciences , Rajahmundry, RAJAHMUNDRY - Andhra Pradesh",
      "Lepakshi Degree College, Proddatur, PRODDATUR - Andhra Pradesh",
      "LESIEUX INSTITUTE OF PRE SCHOOL TEACHER EDUACATION, - Kerala",
      "Let. Sh. Jagat narayan training College for Mentally Handicapped, ALLAHABAD - Uttar Pradesh",
      "Lexicon International School, - Maharashtra",
      "Leyamma Memorial Sn, Mandiram Hospital,Kottayam, KOTTAYAM - Kerala",
      "Liandig Puia Law College, AIZAWL - Mizoram",
      "Liberal College, - Manipur",
      "Liberty Anm Institute,Jaipur, JAIPUR - Rajasthan",
      "Liberty College Of Nursing, Jaipur, JAIPUR - Rajasthan",
      "Liberty School Of Nursing, Jaipur, JAIPUR - Rajasthan",
      "Libra College of Law, DEHRADUN - Uttaranchal",
      "Licchavi Collegeof Teacher's Training,  - Bihar",
      "Life Guard Nursing Institute, Sangrur, SANGRUR - Punjab",
      "Life Help Centre for the Handicapped, CHENNAI - Tamil Nadu",
      "Life Line School Of Nursing, Bangalore, BANGALORE - Karnataka",
      "Life Line School Of Nursing, Hanamkonda, HANAMAKONDA - Andhra Pradesh",
      "Life Line School Of Nursing, Raigad, RAIGAD - Maharashtra",
      "Light House Special teachers Training Centre, RAIGAD - Maharashtra",
      "Likmanya Senior College,  - Maharashtra",
      "Lilong Haoreibi College,  - Manipur",
      "Lincoln College of Law, FATEHGARH SAHIB - Punjab",
      "LINCON TEACHER TRAINING COLLEGE,  - Punjab",
      "LINGAMMAL TEACHER TRAINING INSTITUTE,  - Tamil Nadu",
      "Lingaraj College,  - Karnataka",
      "Lingaraj Law College, BERHAMPUR - Orissa",
      "Lingarajappa Engineering College,  - Karnataka",
      "LINGAYA''S TEACHER TRAINING COLLEGE,  - Haryana",
      "Lingaya's Institute of Management and Technology,  - Haryana",
      "Lingaya's University,  - Haryana",
      "Lingayas Institute of Management and Technology,  - Andhra Pradesh",
      "Lions Charitable Trust, BHILAI - Chhattisgarh",
      "Lions Juhu Nandalal Jalan Mahila Mahavidyalaya,  - Maharashtra",
      "Lisa School Of Nursing, Kozhikode, KOZHIKODE - Kerala",
      "Lisaa Delhi - School of Design,  - Delhi",
      "Lisie College Of Nursing, Ernakulam, ERNAKULAM - Kerala",
      "Lisie College of Pharmacy, COCHIN, KOCHI - Kerala",
      "Lisie Hospital, School Of Nursing, Ernakulam, ERNAKULAM - Kerala",
      "LISIEUX COLLEGE OF EDUCATION C,  - Tamil Nadu",
      "LISIEUX CONVENT TEACHER TRAINING INSTITUTE, Location - Kerala",
      "Lisieux School Of Nursing, Ernakulum, ERNAKULAM - Kerala",
      "LITT College Of Engineering, Location - Punjab",
      "Little Flower College, Location - Kerala",
      "Little Flower College Of Nursing, Ernakulam, ERNAKULAM - Kerala",
      "Little Flower Convent Hr. Sec. School for the Deaf, CHENNAI - Tamil Nadu",
      "LITTLE FLOWER D ED COLLEGE, Location - Karnataka",
      "Little Flower Degree College, BURGHAMPHAD - Andhra Pradesh",
      "Little Flower Degree College, Anantapur, ANANTAPUR - Andhra Pradesh",
      "Little Flower Degree College, Secunderadad, SECUNDERABAD - Andhra Pradesh",
      "Little Flower Degree College, Westgodavari, CHINTALAPUDI - Andhra Pradesh",
      "Little Flower Institute Of Social Sciences & Health, KOZHIKODE - Kerala",
      "LITTLE FLOWER PG COLLEGE, NANDYAL - Andhra Pradesh",
      "Little Flower Polytechnic College, PUDUKOTAI - Tamil Nadu",
      "Little Flower Polytechnic College, Location - Tamil Nadu",
      "Little Flower School Of Nursing, Ernakulam, ERNAKULAM - Kerala",
      "Little Flower School Of Nursing, Thiruvananthapuram, TRIVANDRUM - Kerala",
      "LITTLE FLOWER TEACHER TRAINING INSTITUTE FOR WOMEN, Location - Tamil Nadu",
      "Little Lourdes School Of Nursing, Kottayam, KOTTAYAM - Kerala",
      "Little Lourds Mission Hospital, Kottayam, KOTTAYAM - Kerala",
      "Little Rose Degree College, DRAKSHARAMA - Andhra Pradesh",
      "Little Step Science & Technology College, Location - Madhya Pradesh",
      "Lloyd Institute Of Management & Technology, Location - Uttar Pradesh",
      "Lloyd Law College, NOIDA - Uttar Pradesh",
      "LLRM Medical College, Merrut, MEERUT - Uttar Pradesh",
      "Lms Boys Brigade Hospital, Kundara, Location - Kerala",
      "LN Mishra College of Business Management, Location - Bihar",
      "Ln. G.V. Rao Modern Degree College, RAGHUNATHAPALEM - Andhra Pradesh",
      "LNM Institute of Information Technology, Location - Rajasthan",
      "LNT COLLEGE EDUCATION, Location - Haryana",
      "LNT TEACHER TRAINING COLLEGE, - Haryana",
      "LOAD SHIVA TEACHER TRAINING COLLEGE, - Haryana",
      "LOED SHIVA TEACHER TRAINING COLLEGE, - Rajasthan",
      "LOGAMBAL TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "Loganatha Narayanasamy Government Arts College, TIRUVALLUR - Tamil Nadu",
      "Lohia College, - Rajasthan",
      "Lok Bandhu Raj Narain Vidhi Mahavidyalaya, VARANASI - Uttar Pradesh",
      "Lok Bhandhu Raj Narain Vidhi Mahavidyalaya, VARANASI - Uttar Pradesh",
      "Lok Bharati Lok Seva Mahavidyalaya, - Gujarat",
      "Lok Mahavidyalaya, - Bihar",
      "LOK MANGA TILAK COLLEGE OF EDUCATION, - Rajasthan",
      "LOK NATH MAHAVIDYALAYA, - Uttar Pradesh",
      "LOKAMANYA TILAK COLLEGE OF EDUCATION, - Madhya Pradesh",
      "Lokanayak Omeo Kumar Das College, SONITPUR - Assam",
      "LOKESH TEACHER TRAINING COLLEGE, - Rajasthan",
      "LOKHIT COLLEGE OF PHYSICAL EDUCATION, - Maharashtra",
      "LOKHMANYA TILAK PG COLLEGE, IBRAHIMPATNAM - Andhra Pradesh",
      "Lokmangal Nursing School, SHOLAPUR - Maharashtra",
      "Lokmani Sharma Swatantrata Sangram Senani Govt. Degree College, - Uttar Pradesh",
      "LOKMANYA EDUCATION SOCIETY, - Madhya Pradesh",
      "Lokmanya Mahavidyalaya, - Maharashtra",
      "Lokmanya Medical Foundations Homoeopathic Medical College, - Maharashtra",
      "LOKMANYA TIALK JANKALYAN SANSTHAN, - Rajasthan",
      "Lokmanya Tilak College Of Education, - Madhya Pradesh",
      "LOKMANYA TILAK COLLEGE OF TEACHER EDUCATION, - Rajasthan",
      "LOKMANYA TILAK INSTITUTE OF MANAGEMENT STUDIES & RESEARCH, NAGPUR - Maharashtra",
      "LOKMANYA TILAK JANKALYAN SHIKSHAN SANSTHA, - Maharashtra",
      "Lokmanya Tilak Jankalyan Shikshan Sanstha's College of Technology, THANE - Maharashtra",
      "Lokmanya Tilak Mahavidyalaya, - Maharashtra",
      "Lokmanya Tilak Municipal General Hospital, MUMBAI - Maharashtra",
      "Lokmanya Tilak Municipal Medical College, Maharashtra",
      "Lokmanya Tilak Municipal Medical College, Mumbai - Maharashtra",
      "Lokmanya Tilak Municipal Medical College, Sion, Mumbai - Maharashtra",
      "LOKMANYA TILAK STC COLLEGE, Rajasthan",
      "Loknath Mahavidyalay, Uttar Pradesh",
      "Loknayak Bapuji Aney Mahila Mahavidyalaya, Maharashtra",
      "Loknete Rajarambapu Patil Training College Of Nsg, Sangli - Maharashtra",
      "Lokniketan Mahavidyalaya, Gujarat",
      "Lokopriya Gopinath Bordoloi, School Of Nursing, Tezpur - Assam",
      "LOKSHAHI SHIKSHAN SANSTHA, Maharashtra",
      "Lokvishwas Pratishthan Shantadurga Krupa Ashram, Goa",
      "Lombard Memorial Hospital c S I Hosp. , Dakshina Kannada - Karnataka",
      "Lonavla Education Trusts Arts and Commerce College, Maharashtra",
      "London International College of Law Technology and Management, Delhi",
      "Longowal Polytechnic & Pharmacy College, Patiala - Punjab",
      "Lord Ayyappa Institute of Engineering and Technology, Tamil Nadu",
      "Lord Buddha College, Bihar",
      "Lord Buddha Koshi Medical College & Hospital, Bihar",
      "Lord Jagannath Missions College & School Of Nursing, Bhubaneswar - Orissa",
      "Lord Jagannath Missions College Of Nursing, Bhubaneswar - Orissa",
      "Lord Jagannath Missions School Of Nursing, P O Rasulgrh - Orissa",
      "Lord Jegannath College Of Engineering & Technology, Kanyakumari - Tamil Nadu",
      "LORD KISHANA TEACHER TRAINING COLLEGE, Haryana",
      "LORD KRISHANA TEACHER TRAINING COLLEGE, Haryana",
      "LORD KRISHANA TEACHER TRAINING COLLEGE, Ambala City - Haryana",
      "Lord Krishna College of Engineering, Ghaziabad - Uttar Pradesh",
      "Lord Krishna College Of Engineering, Uttar Pradesh",
      "Lord Krishna College Of Nursing, Datia - Madhya Pradesh",
      "Lord Krishna College of Pharmacy, Sangrur - Punjab",
      "Lord Krishna College of Technology, Madhya Pradesh",
      "LORD KRISHNA INSTITUTE, Uttar Pradesh",
      "LORD KRISHNA INSTITUTE FOR EDUCATION, Uttar Pradesh",
      "Lord Krishna Polytechnic Institute, Haryana",
      "Lord Krishna School Of Nursing, Sabarkantha, Gujarat",
      "LORD KRISHNA TEACHER TRAINING COLLEGE, Haryana",
      "LORD KRISHNA TEACHER TRAINING COLLEGE, Punjab",
      "LORD KRISHNA TEACHER TRAINING COLLEGE, Punjab",
      "Lord Mahavira Bsc Nursing College, Solan, Himachal Pradesh",
      "Lord Mahavira College of Law, Moradabad, Uttar Pradesh",
      "Lord Mahavira Homoeopathic Medical College, Ludhiana, Punjab",
      "Lord Mahavira Institute Of Mphw anm, Chamba, Himachal Pradesh",
      "Lord Mahavira Paramedical Institute, Solan, Himachal Pradesh",
      "LORD MAHAVIRA TEACHER TRAINING COLLEGE, Punjab",
      "Lord Shiva College of Management, Haryana",
      "Lord Shiva College of Pharmacy, Haryana",
      "Lord Shiva College of Pharmacy, Sirsa, Haryana",
      "LORD SHIVA INSTITUTE FOR HIGHER STUDIES, Uttar Pradesh",
      "Lord Shiva School Of Nursing, Madhya Pradesh",
      "Lord Shiva School Of Nursing, Sangrur, Punjab",
      "Lord Shiva School Of Nursing, Sirsa, Haryana",
      "Lord Shiva School Of Nursing, Jodhpur, Rajasthan",
      "LORD SHIVA TEACHER TRAINING COLLEGE, Haryana",
      "LORD SHIVA TEACHER TRAINING COLLEGE, Haryana",
      "Lord Venkateshwara Engineering College, Kanchipuram, Tamil Nadu",
      "LORD VENKATESWARA INSTITUTE TEACHER TRAINING, Tamil Nadu",
      "Lord's Institute of Engineering and Technology, Andhra Pradesh",
      "LORD'S INTERNATIONAL COLLEGE OF MANAGEMENT, Rajasthan",
      "Lords Institute of Management, Gujarat",
      "LORDS INTERNATIONAL COLLEGE, Rajasthan",
      "LORDS INTERNATIONAL COLLEGE FOR TEACHER TRAINING, Rajasthan",
      "LORDS MAHAVIRA TEACHER TRAINING COLLEGE, Punjab",
      "Lords School Of Nursing, Trivandrum, Kerala",
      "Loreto College, West Bengal",
      "Loreto College, West Bengal",
      "Loreto College, West Bengal",
      "Loreto House Teacher Training, West Bengal",
      "LORVEN COLLEGE OF SCIENCE & MANAGEMENT, Karnataka",
      "LORVEN EDUCAITONAL CENTRE, Karnataka",
      "Lorven Educational centre, Karnataka",
      "Lorven International Institute of Management Studies, Karnataka",
      "Lorven School Of Nursing, Bangalore, Karnataka",
      "Lotus Business School, Maharashtra",
      "Lotus Medical Foundation, School Of Nursing, Kolhapur, Maharashtra",
      "Lotus Nursing Institute, Nanded, Maharashtra",
      "Lourde College Of Nursing, Kannur, Kerala",
      "LOURDES COLLEGE OF EDUCATION, Karnataka",
      "Lourdes College Of Nursing, Ernakulam, Kerala",
      "Lourdes Hospital, School Of Nursing, Ernakulam, Kerala",
      "Lourdes Matha College of Science & Technology, Kerala",
      "Lourdes Matha College of Science and Technology, Kerala",
      "Lourdes Matha Institute of Hotel Management and Catering Technology, Kerala",
      "Lourdes School Of Nursing, Kollam, Kerala",
      "Lovekush Institute Of Nursing, Ambikapur, Chhattisgarh",
      "Lovekush Institute Of Nursing, Chhattisgarh, Chhattisgarh",
      "Lovekush Institute Of Nursing, Koria, Chhattisgarh",
      "LOVELY INSTITUTE OF EDUCATION, Punjab",
      "LOVELY INSTITUTE OF EDUCATION, Punjab",
      "LOVELY INSTITUTE OF EDUCATION, Punjab",
      "Lovely Institute of Law, Phagwara, Punjab",
      "LOVELY INSTITUTE OF MANAGEMENT LOVELY MALL, Jalandhar, Punjab",
      "Lovely Institute of Technology, Punjab",
      "Lovely Institute of Technology, Phagwara - Punjab",
      "Lovely Professional University, Phagwara - Punjab",
      "Lovely Professional University, Punjab",
      "Lovely Teacher Training Institute, Delhi",
      "Lower Lakhwar Colony, Uttaranchal",
      "Lowry Memorial Teacher Training Institute, Karnataka",
      "Loyala Academy Degree College, Secunderabad - Andhra Pradesh",
      "Loyala Institute of Business Administration, Chennai - Tamil Nadu",
      "Loyala Teacher Training Institute, Tamil Nadu",
      "Loyola - ICAM College of Engineering and Technology, Tamil Nadu",
      "Loyola College, Chennai - Tamil Nadu",
      "Loyola College, Tamil Nadu",
      "Loyola College, Cuddalore - Tamil Nadu",
      "Loyola College of Education, Jharkhand",
      "Loyola College of Education, Sikkim",
      "Loyola College of Social Science, Kerala",
      "Loyola Degree College, Cuddapah - Andhra Pradesh",
      "Loyola Institute of Teacher Education, Pondicherry",
      "Loyola Institute of Technology, Tamil Nadu",
      "Loyola Institute of Technology & Science, Kanyakumari - Tamil Nadu",
      "Loyola Institute of Technology And Management, Andhra Pradesh",
      "Loyola Teacher Training Institute, Karnataka",
      "LSN Teacher Training Institute, Kerala",
      "Lt Shri Jamuna Prasad Nayak Shiksha Prasar Samiti, Madhya Pradesh",
      "Lt. B.N. Saoji Academys Teachers Training Centre of HI, Indore - Maharashtra",
      "Lt. College, Uttar Pradesh",
      "Lt. Km. Laxmi Badhala Mahila Primary Teacher Training School, Rajasthan",
      "Lt. Mahipat Singh Teacher Training College, Haryana",
      "Lt. Kumari Laxmi Badhala Education & Research Institute, Rajasthan",
      "LT.MAHIPAT SINGH TEACHER TRAINING COLLEGE, - Haryana",
      "LT.SARDAR SINGH SMRITI SHIKSHA SAMITEE, - Madhya Pradesh",
      "LTA School of Beauty, - Maharashtra",
      "Lucknow Christian Degree College, - Uttar Pradesh",
      "Lucknow Institute of Technology, - Uttar Pradesh",
      "Lucknow Law College, LUCKNOW - Uttar Pradesh",
      "Lucknow Polytechnic, Lucknow, - Uttar Pradesh",
      "Lucknow University, - Uttar Pradesh",
      "LUCKNOW UNIVERSITY, - Uttar Pradesh",
      "LUCKY INSTITUTE OF PROFESSIONAL STUDIES, - Rajasthan",
      "LUCKY INSTITUTE OF PROFESSIONAL STUDIES, - Rajasthan",
      "Ludhiana College Of Engineering And Technology, LUDHIANA - Punjab",
      "Ludhiana Institute Of Nursing , Ludhiana, LUDHIANA - Punjab",
      "Luipa Mahavidyalaya, - Orissa",
      "LUISE JAMES TEACHER TRAINING INSTITUTE, - Tamil Nadu",
      "Luitparia College Barpeta, BARPETA - Assam",
      "Lukhdhirji College Of Engineering, - Gujarat",
      "Lumding College, NAGAON - Assam",
      "Lunglei Government College, - Mizoram",
      "Luqman College of Pharmacy , GULBARGA, GULBARGA - Karnataka",
      "Luquman College Of Science & Arts, - Karnataka",
      "LUTAWAN DEGREE COLLEGE, - Uttar Pradesh",
      "LUTAWAN DEGREE COLLEGE, - Uttar Pradesh",
      "Lutheran Degree College For Women, RAJAHMUNDRY - Andhra Pradesh",
      "Lutheran Degree College, Bhimavaram, BHIMAVARAM - Andhra Pradesh",
      "Luxmi Bai Institute of Dental Sciences & Hospital , Patiala, PATIALA - Punjab",
      "Luxmi Nursing Training Centre,Gadchiroli, - Maharashtra",
      "LVR TEACHERS TRAINING INSTITUTE, - Karnataka",
      "Lyallpur Khalsa College, - Punjab",
      "Lyallpur Khalsa College for Women, - Punjab",
      "Lyallpur Khalsa Teacher Training College for Women, Punjab",
      "Lyceum Teacher Training College, Haryana",
    ],
  },
];
