const RData = [
  {
    colleges: [
      "R .V.S. College of Engineering and Technology (M.B.A)",
      "R A S School Of Nursing , Jaunpur",
      "R A S School Of Nursing, Jaunpur",
      "R A Vysya College, Madurai",
      "R B College",
      "R B G R College",
      "R B Memorial School Of Nursing , Darbhanga",
      "R B Nursing And Para Medical Institution , Kathua",
      "R B S College",
      "R B S College Bihar",
      "R B Sagar College Education",
      "R B V R R Women'S College",
      "R C College of Commerce",
      "R C Memorial College Of Nursing, Pali",
      "R C Memorial Nursing Institute , Pali",
      "R C Memorial Nursing Institute, Pali",
      "R C Memorial Post Basic Nursing College ,Pali",
      "R C S S College",
      "R D D J College",
      "R D Memorial College Of Nursing , Bhopal",
      "R D Memorial College Of Nursing , Indore",
      "R D Memorial School Of Nursing , Bhopal",
      "R D Memorial School Of Nursing , Indore",
      "R D S College",
      "R D T School Of Nursing , Bathalapalli",
      "R E S E T College Education",
      "R G Baruah College",
      "R G Kar Medical College Hospital , Calcutta",
      "R G M College Of Nursing, Jodhpur",
      "R G Shah Science College",
      "R G Teachers College",
      "R H Patel Arts Commerce College",
      "R I T E E College Of Nursing,Raipur",
      "R J S Polytechnic",
      "R K College Bihar",
      "R K College of Engineering",
      "R K College Of Nursing,Bellary",
      "R K D F College Of Nursing , Bhopal",
      "R K D F School Of Nursing,Bhopal",
      "R K M School Of Nursing , Bijapur",
      "R K Mahila College",
      "R K S D College",
      "r k s d college of pharmacy",
      "R K SAMY COLLEGE OF EDUCATION",
      "R L College",
      "R L D Nursing School,Bhind",
      "R L Jalappa Institute of Technology",
      "R L Nursing College , Morena",
      "R L Nursing College For Post Basic Bsc In Nursing , Morena",
      "R L S Y College",
      "R L S Y College Bihar",
      "R L School Of Nursing , Morena",
      "R M L School Of Medical Sciences & Hospital , Bhopal",
      "R M P C S I P S K RAJA COLLEGE OF EDUCATION",
      "R M Polytechnic, Gulburga",
      "R Mishra College",
      "R N A R College",
      "R N College",
      "R N College Bihar",
      "R N Institute of Poly. Studies",
      "R N S College Of Nursing, Uttara Kannada",
      "R N S College Of Nursing, Bhatkal",
      "R N S Nursing School, Cuttara Kannada",
      "R N Shetty Polytechnic",
      "R N Shetty Polytechnic, Belgaum",
      "R N T Medical College, Udaipur",
      "R P Inderaprastha Institute Of Medical Sciences, Karnal",
      "R P S College, Danapur",
      "R P S College, Vaishali",
      "R P Sharma Institute Of Technology, Patna",
      "R R Christian College Of Nursing, Kurnool",
      "R R Christian School Of Nursing, Nandyal",
      "R R College Of Nursing, Ajmer",
      "R R College Of Nursing, Bangalore",
      "R R College Of Nursing, Jaipur",
      "R R D ED College",
      "R R Institute Of Nursing, Jaipur",
      "R R Lalan College",
      "R R M College Science, C L P College Commerce, G D Modi College",
      "R R Mehta College Science And Chhattishgarh Parek College Commerce",
      "R R Nursing Institute, Ajmer",
      "R R Nursing School, Gurgaon",
      "R R Patil Institute Of Nursing Education, Sangli",
      "R R S College",
      "R R School Of Nursing, Bangalore",
      "R R School Of Nursing, Gurgaon",
      "R S C College Of Nursing, Gwalior",
      "R S C School Of Nursing, Gwalior",
      "R S C School Of Nursing, Balaghat",
      "R S College Bihar",
      "R S College Of Nursing, Bangalore",
      "R S K School Of Nursing, Trichy",
      "R S Mahavidyalaya",
      "R S More College",
      "R S P College",
      "R S S Mahila College",
      "R T Nagar School Of Nursing, Bangalore",
      "R V College Of Nursing, Bangalore",
      "R V S College Of Nursing, Coimbatore",
      "R V S School Of Nursing, Coimbatore",
      "R V Teachers Training Institution",
      "R V V Mahila College",
      "R. C. M. Hospital, Eranakulam",
      "R. C. Patel Institute of Technology",
      "R. E. Societys Shriman Bhagjsheths Keer Law College Late Sou. Indirabai Vishnupanth",
      "R. K. College Of Diploma Engineering",
      "R. L. Law College",
      "R. R. B.ED College P.K.M. Trust (R)",
      "R. S. Banaras Law College",
      "R. Sankar Memorial S.N.D.P. Yogam Arts & Science College",
      "R. T. E. Societys Law College",
      "R. V. Institute of Management",
      "R.A. Podar College Of Commerce & Economics",
      "R.B. Attal Arts Science & Commerce College",
      "R.B. Institute Of Management Studies",
      "R.B. Narayanrao Borawake College",
      "R.B.A.N.M.S. First Grade College",
      "R.B.D. Mahila Mahavidyalaya",
      "R.B.Degree College",
      "R.B.DEGREE COLLEGE",
      "R.B.Institute of Management Studies",
      "R.B.M T T I",
      "R.B.S. COLLEGE",
      "R.B.S. COLLEGE",
      "R.B.T. COLLEGE OF EDUCATION",
      "R.B.T. JUNIOR COLLEGE OF EDUCATION",
      "R.B.T.S. Govt. Homoeopathic Medical College",
      "R.B.U.S.S Ravi Institute of Diploma in Pharmacy , Nagpur",
      "R.C. Institute of Technology",
      "R.C. INSTITUTE OF TECHNOLOGY",
      "R.C. Jall Law College",
      "R.C. MEMORIAL TEACHER TRAINING COLLEGE",
      "R.C. Patel Arts Commerce And Science College",
      "R.C. Patel B. Pharmacy College",
      "R.C. Saharia Teacher's Training College",
      "R.C. TEACHER TRAINING COLLEGE",
      "R.C. TEACHER TRAINING INSTITUTE",
      "R.C. TEACHER TRAINING INSTITUTE",
      "R.C.A. Girls Degree College",
      "R.C.C INSTITUTE OF TECHNOLOGY",
      "R.C.M. Science College",
      "R.C.M. TEACHER TRAINING COLLEGE",
      "R.C.N.C TEACHER TRAINING INSTITUTE",
      "R.C.R. INSTITUTE OF MANAGEMENT TECHNOLOGY",
      "R.D Engineering College",
      "R.D. COLLEGE OF EDUCATION",
      "R.D. Kedia Homoeopathic Medical College",
      "R.D. MEMORIAL COLLEGE OF PHYSICAL EDUCATION",
      "R.D. MEMORIAL COLLEGE OF PHYSICAL EDUCATION, ",
      "R.D. National & W.A. Science College, ",
      "R.D. R.B. DEGREE COLLEGE, ",
      "R.D. Womens Degree College, HANAMAKONDA",
      "R.D.B COLLEGE OF EDUCATION, ",
      "R.D.B. INSTITUTE OF MANAGEMENT, THANJAVUR",
      "R.D.R.B. MAHAVIDYALAYA, ",
      "R.D.S. Mahavidyalaya, ",
      "R.D.S.N.D. Government Degree College, ",
      "R.D.TEACHER TRAINING COLLEGE, ",
      "R.E. Societys Shriman Bhagojisheth Keer Law College, RATNAGIRI",
      "R.G. Kar Medical College, ",
      "R.G. KESIA COLLEGE OF COMMERCE, HYDERABAD",
      "R.G. MISHRA TEACHER TRAINING COLLEGE, ",
      "R.G.E. SOCIETYS, ",
      "R.G.R Siddhanthi College, ",
      "R.G.R. Siddhanthi Degree College, SECUNDERABAD",
      "R.H. Patel Institute of Technology,Goblaj, ",
      "R.H.Patel Institute of Technology, ",
      "R.I.E.T. VIDYAPEETH, VILL. - POHLI, TEHSIL - SARDHANA, ",
      "R.I.H.S, ",
      "R.J. College Of Arts & Science & Commerce, ",
      "R.J. Computer Center, PATAN",
      "R.J.R.M. Degree College, WARANGAL",
      "R.K GUPTA MEMORIAL INSTITUTE OF TECHNOLOGY  & MANAGEMENT, AGRA",
      "R.K University, ",
      "R.K. College, ",
      "R.K. College, VIZIANAGARAM",
      "R.K. Degree College, ",
      "R.K. GUPTA MEMORIAL INSTITUTE OF TECHNOOGY & MANAGEMENT, ",
      "R.K. INSTITUTE OF MANAGEMENT & RESEARCH",
      "R.K. INSTITUTE OF MANAGEMENT AND COMPUTER SCIENCES",
      "R.K. Law College",
      "R.K. Polytechnic College",
      "R.K. School of Engineering",
      "R.K. Talreja College Of Artsscience & Commerce",
      "R.K. TEACHER TRAINING COLLEGE",
      "R.K. TEACHER TRAINING COLLEGE,",
      "R.K.. COLLEGE OF SYSTEM MAHAVIDYALAYA",
      "R.K.. COLLEGE OF SYSTEM MAHAVIDYALAYA",
      "R.K.Arya College",
      "R.K.D.F. Homoeopathic Medical College",
      "R.K.D.F. INSTITUTE OF MANAGEMENT",
      "R.K.GUPTA MEMORIAL INSTITUTE OF TECHNOLOGY & MANAGEMENT",
      "R.K.Institute of Management and Computer Science",
      "R.K.L.K. DPharmacy College , Nalgonda",
      "R.K.L.K. Rao Degree College",
      "R.K.L.K. Raos Women Degree College",
      "R.K.M. Law College",
      "R.K.Mission Boys Home Primary Teacher's Training Institute",
      "R.K.Mission Sarda Mandir Govt. Sponsored Primary Teacher's Training Institute",
      "R.K.P. Degree College",
      "R.K.R. TEACHER TRAINING INSTITUTE",
      "R.K.S.D. TEACHER TRAINING COLLEGE",
      "R.L TEACHER TRAINING COLLEGE",
      "R.L. INSTITUTE OF MANAGEMENT STUDIES",
      "R.L. Law College",
      "R.L.S.Law College",
      "R.L.S.Law College",
      "R.M. TEACHER TRAINING INSTITUTE",
      "R.M.D Engineering College",
      "R.M.K College of Engineering and Technology",
      "R.M.K Engineering College",
      "R.M.M. Law College",
      "R.M.R.COLLEGE OF EDUCATION",
      "R.Madhya Pradesh. Postgraduate College",
      "R.Madhya Pradesh.P.V. College",
      "R.MUDDURANGE GOWDA COLLEGE OF EDUCATION",
      "R.N. COLLEGE",
      "R.N. College of Engineering & Technology",
      "R.N. INSTITUTE OF MODERN MANAGEMENT EDUCATION & RESEARCH CENTRE",
      "R.N. SinghGovernment College",
      "R.N. T.T. COLLEGE",
      "R.N.C. Arts J.D.B. Commerce And N.S.C. Science College",
      "R.N.INSTITUTE OF MODERN MANAGEMENT EDUCATION & RESEARCH CENTRE",
      "R.N.M.M. Law College",
      "R.N.MEMORIAL MAHILA STC",
      "R.N.S.INSTITUTE OF EDUCATION D.ED",
      "R.N.T. COLLEGE OF TEACHER EDUCATION",
      "R.N.T. Medical College",
      "R.O.R.B. DEGREE COLLEGE",
      "R.P Educational Trust Group of Institutions",
      "R.P. Degree College",
      "R.P. Kanya Mahavidyalaya",
      "R.P.A. COLLEGE OF EDUCATION",
      "R.P.Gogate College Of Arts Science & R.V.J. College Of Commerce",
      "R.P.M. DEGREE COLLEGE",
      "R.P.P.G. COLLEGE",
      "R.P.S. COLLEGE OF EDEUCATION",
      "R.P.S. Law College",
      "R.P.S. Teacher's Training College",
      "R.R TAMIL MEDIUM D.ED COLLEGE",
      "R.R. Bawa D.A.V. College for Girls",
      "R.R. COLLEGE OF MANAGEMENT STUDIES & COMPUTER APPLICATIONS",
      "R.R. D.ED COLLEGE",
      "R.R. EDUCATIONAL TRUSTS B.ED. COLLEGE",
      "R.R. INSTITUTE OF ADVANCED STUDIES",
      "R.R. Lahoti Science College",
      "R.R. Memorial Degree College",
      "R.R.K. Samithi Kishan LalPande College of Pharmacy, BIDAR",
      "R.R.M.K. Arya Mahila Mahavidyalaya",
      "R.R.Polytechnic",
      "R.S. Banaras Law College",
      "R.S. Bidkar Artsscience & Commerce College",
      "R.S. College",
      "R.S. Mahavidyalaya",
      "R.S. MEMORIAL TEACHER TRAINING COLLEGE",
      "R.S.D. Academy",
      "R.S.D. ACADEMY",
      "R.S.D. College",
      "R.S.G.U. Degree (P.G.) College",
      "R.S.K.D. PG Degree College",
      "R.S.M. Degree College",
      "R.S.M. Educational Society, Sri Sai College of Pharmacy, Bangalore",
      "R.S.M.P DEGREE COLLEGE",
      "R.S.M.P. Degree College",
      "R.S.P. College",
      "R.S.S. Degree College",
      "R.S.S. DEGREE COLLEGE",
      "R.S.S.P. Mandals Ltd Sanchalit Rastriya Arts Sc Commerce College",
      "R.S.TEACHERS TRAINING COLLEGE",
      "R.S.V. COLLEGE OF EDUCATION",
      "R.T.C.B.Ed.College P.H.E.D",
      "R.T.E SOCIETYS COLLEGE OF EDUCATION",
      "R.T.E.S.s Arts Sc. & Commerce College",
      "R.V. Bidap Law College",
      "R.V. Bidap Law College",
      "R.V. Higher Education and Technical Institute",
      "R.V. NORTH LAND INSTITUTE",
      "R.V. Teachers College",
      "R.V. Teachers College",
      "R.V.HIGHER EDUCATION AND TECHNICAL INSTITUTE",
      "R.V.P. First Grade College",
      "R.V.S College Of Computer Application",
      "R.V.S. COLLEGE OF EDUCATION",
      "R.V.S. COLLEGE OF EDUCATION",
      "R.V.S. COLLEGE OF EDUCATION",
      "R.V.S. College of Engineering",
      "R.V.S. College of Engineering and Technology (M.C.A)",
      "R.V.S. College of Pharmaceutical Sciences , Sulur",
      "R.V.S. College of Physiotherapy",
      "R.V.S. Dental College & Hospital , Kannampalayam",
      "R.V.S. Educational Trust's Group of Institutions",
      "R.V.S. Medical Trust Homoeopathic Medical College",
      "R.V.S. Padhmavathy College of Engineering & Technology",
      "R.V.S. School of Architecture",
      "R.V.V.N. College",
      "RAADHAA COLLEGE OF EDUCATION",
      "Raak Nursing & Paramedical College , Villianur",
      "RAAK TEACHER TRAINING INSTITUTE",
      "Raasi Polytechnic College",
      "RAATH MAHAVIDYALAYA",
      "RAATH MAHAVIDYALAYA",
      "Rabiammal Ahamed Maideen College For Women",
      "Rabindharanath Tagoor College of Engineering for Women",
      "Rabindharanath Tagoore College Of Nursing For Women,Salem",
      "Rabindharanath Tagore College Arts And Science Women",
      "RABINDHARANATH TAGORE COLLEGE OF EDUCATION",
      "Rabindharanath Tagore College Of Nursing For Women , Salem",
      "Rabindharanath Tagore School Of Nursing For Women , Sankari West",
      "Rabindra Bharati University",
      "RABINDRA BHARTI TEACHER TRAINING COLLEGE",
      "Rabindra Mahavidyalaya",
      "RABINDRA NATH THAKUR COLLEGE OF EDUCATION",
      "Rabindra Nath Thakur Primary Teacher's Training Institute",
      "Rabindra Satabarsiki Mahavidyalaya",
      "Rabindra Shiksha Sammilani Law College",
      "Rabindranath Tagore International Institute Of Cardiac Sciences , Kolkata",
      "RabindraNazrulSmritiB.Ed. EducationalInstitute",
      "Rabindrasashan Girls College",
      "Rachapudi Nagabushanam Degree College",
      "RADHA GOVIND COLLEGE OF EDUCATION",
      "Radha Govind Engineering College",
      "Radha Govind Teacher's Training College",
      "RADHA HARI GOVERNMENT P.G. COLLEGE",
      "Radha Kirushnajee College Of Nursing , Kanchipuram",
      "RADHA KRISHAN TEACHERS TRAINING COLLEGE",
      "RADHA KRISHNA COLLEGE",
      "RADHA KRISHNA KANYA MAHAVIDYALAYA",
      "Radha Krishna Kanya Mahavidyalaya",
      "Radha Krishna Nursing Education Institute , Bhilwara",
      "RADHA MOAHAN KISHAN MAJDOOR MAHAVIDYALAYA",
      "Radha Mohan Kisan Majdoor Mahavidyalaya",
      "Radha Shanta Mahavidyalaya",
      "Radha Umakant Sanskrit Mahavidyalaya",
      "Radhabai Bahekar Nursing anm School,Gondia",
      "Radhabai Kale Mahila Mahavidyalya(Arts & Sciences)",
      "Radhamadhab College",
      "Radhanath Institute of Advance Studies",
      "Radhanath Institute of Advanced Study in Education",
      "Radhanath Secondary Training School",
      "Radharaman Engineering College",
      "Radharaman Institute of Research and Technology",
      "Radharaman Institute of Technology and Science",
      "Radhaswami Institute of Technology",
      "RADHASWAMI VIVIDH KARYKARI EDUCATION SANSTHA",
      "Radhika Nursing School,Akola",
      "Radhikatai Pandav Polytechnic",
      "Radiant College of Law",
      "Raffles University",
      "RAGAHAVENDRA RURAL DEVELOPMENT ASSOCIATION",
      "Ragas Dental College",
      "Ragas Dental College & Hospital , Uthandhi",
      "Raghavendar Institute of Pharmacetical education research",
      "Raghavendra College Of Nursing,Davangere",
      "Raghavendra Institute of Pharmaceutical Education & Research RIPER , Anantapur",
      "Raghavendra School Of Nursing , Davangere",
      "Raghu Degree College",
      "Raghu Engineering College",
      "Raghu Institute of Technology",
      "Raghukul Research & Technical Institute , Raghukul School Of Nsg, Jaipur",
      "RAGHUKUL TEACHERS TRAINING COLLEGE",
      "Raghunandan Prasad Mandal Degree Mahavidyalaya",
      "Raghunath College",
      "RAGHUNATH GIRLS P.G. COLLEGE",
      "Raghunath Girls Postgraduate College",
      "Raghunath Pandey Memorial Law College",
      "Raghunathjew College",
      "Raghunathpur College",
      "RAGHURAM MAHAVIDYALAYA",
      "Raghuvansham School of Modern Art",
      "Raghuvar Dayal Prabhu Dayal Kanya Mahavidyalaya",
      "Raghuveer Institute Of Nursing & Paramedical Sciences ,Uttar Pradesh",
      "RAGHUVIR SHARAN MEMORIAL DEGREE COLLEGE",
      "RAGHUWAR DAYAL PRABHU DAYAL GIRLS DEGREE COLLEGE",
      "Raghvendra Hospital & Nursing Training Institute , Jhansi",
      "Raghvendra Hospital & Nursing Training Institute,Jhansi",
      "Raghwendra Sanskrit College",
      "Raha College",
      "Rahat College Of Nursing , Khargone",
      "Rahdagovinda Baruah College Guwahati",
      "RAHOD EDUCATION SOCIETY",
      "RAHUL D.ED. COLLEGE (ENGLISH MEDIUM)",
      "Rahul Pg College Of Computer Science,",
      "RAHUL SHIKSHAN PRASARAK MANDAL SATYAGRAHA COLLEGE OF EDUCATION",
      "RAI SAHEB BHANWAR SINGH COLLEGE",
      "Rai School Of Nursing, Tikamgarh",
      "Rai University",
      "Raibag Polydstechnic, Raibag",
      "Raichur Institute of Medical Sciences,Raichur",
      "Raid Laban College",
      "Raidighi B.Ed. College",
      "Raidighi College",
      "Raiganj B.Ed. College",
      "Raiganj Polytechnic",
      "Raiganj Surendranath Mahavidyalaya",
      "Raiganj University College",
      "Raihan College Education",
      "Railway Degree College",
      "RAINBOW COLLEGE OF EDUCATION",
      "Rainbow College Of Nursing,Ranga Reddy",
      "RAINBOW TEACHER TRAININGINSTITUTE",
      "Raipur B.Ed. College",
      "Raipur Homoeopathic Medical College and Hospital",
      "Raipur Institute of Technology",
      "Rairangpur College",
      "RAITHA EDUCATION SOCIETY(R)",
      "RAIZADA DHARAM DASS INSTITUTE OF EDUCATION AND TECHNOLOGY",
      "Raj A N M Cum Para Medical Institute , Ranchi",
      "RAJ COLLEGE OF TEACHER EDUCATION",
      "RAJ DEEP MAHILA MAHAVIDYALAYA",
      "Raj Kishor Singh Mahavidyalaya",
      "Raj Kumar Goel Engineering College",
      "RAJ KUMAR GOEL GIRLS DEGREE COLLEGE",
      "Raj Kumar Goel Institute of Technology",
      "Raj Kumar Mphw f Training Institute,Rajahmundra",
      "Raj Kumari Amrit Kaur College of Nursing",
      "Raj Mahal Vilas School Of Nursing , Bangalore",
      "Raj Narain Pandey Degree College",
      "RAJ NARALIA PANDEY DEGREE COLLEGE",
      "RAJ NARAYAN PANDEY DEGREE COLLEGE",
      "Raj Narayan Singh Mahavidyalaya",
      "RAJ RAJESHWARY TEACHER TRAINING COLLEGE",
      "Raj Rani Co-Education College",
      "Raj Rishi College",
      "Raj School of Management Science",
      "Raj School Of Nursing , Gorakhpur",
      "Raj School Of Nursing,Gorakhpur",
      "RAJ SHIKSHAK PRASHIKSHAN MAHILA MAHAVIDYALAYA",
      "RAJ SHREE MAHILA TEACHER TRAINING COLLEGE",
      "RAJ TEACHER TRAINING COLLEGE",
      "RAJA BAHADUR VENKATA RAMA REDDY INSTITUTE OF TECH",
      "RAJA BALWANI SINGH COLLEGE",
      "Raja Balwant Singh College",
      "Raja Birendra Chandra College",
      "Raja College of Engineering and Technology",
      "RAJA DESINGH EDUCATIONAL TRU RAJA DESINGH COLLEGE OF EDUCATION",
      "Raja Desingh Polytechnic College",
      "RAJA DEVI DEGREE COLLEGE",
      "RAJA DEVI GOYAL MULTIPURPOSE",
      "RAJA DEVI MAHILA MAHAVIDYALAYA",
      "Raja Harpal Singh Degree College",
      "RAJA HARPAL SINGH PG COLLEGE",
      "RAJA HARPUR SINGH POST GRADUATE COLLEGE",
      "Raja Kanh Degree College",
      "Raja Kanh P.G. College",
      "Raja Kishore Chandra Academy of Technology",
      "RAJA KUMAR NAIK EDUCATIONL CHARITABLE TRUST",
      "Raja Lakhama Gonda Science Institute",
      "Raja Lakhamgonda Law College",
      "Raja Lakhamgonda Law College",
      "Raja Lakshma Gowda Law College",
      "Raja Mahendra College of Engineering",
      "Raja Mohan Girls Degree College",
      "Raja Narendralal Khan Womens College",
      "Raja Pearymohan College",
      "RAJA RAJAN TEACHER TRAINING INSTITUTE",
      "RAJA RAJESHWARI D ED COLLEGE",
      "Raja Ram Memorial Degree College",
      "RAJA RAM MOHAN RAIO INSTITUTE OF VOCANATIONAL STUDIES",
      "Raja Ram Mohan Roy College of Education (B.Ed.)",
      "RAJA RAM PREM SINGH SHIKSHA MAHAVIDYALAYA",
      "Raja Rammohan Roy Mahavidyalaya",
      "RAJA SADHA BAKKIYAM TEACHER TRAINING SCHOOL",
      "Raja Shree Shivaraya Pratishthans Maharastra Law College",
      "RAJA SHRI KRISHANDATT P.G. COLLEGE",
      "RAJA SHRI KRISHNA DUTTA PG",
      "Raja Shripatrao Bhagwantrao Mahavidyalaya",
      "Raja Singh College",
      "RAJABHAU JACHAK COLLEGE OF EDUCATION",
      "RAJADEVI GOYAL M/P COLLEGE BHERIAN PEHOWA",
      "Rajadhani Institute of Engineering & Technology",
      "RAJAGIRI BUSINESS SCHOOL",
      "Rajagiri College of Social Sciences",
      "Rajagiri Dawood Batcha College Of Arts And Science",
      "RAJAGIRI INSTITUTE OF MGT",
      "Rajagiri School of Engineering and Technology",
      "Rajagopal Polytechnic College",
      "Rajagopal Polytechnic College",
      "Rajah Duraisingam Memorial Government College",
      "Rajah Muthiah Dental College & Hospital, Chidambaram",
      "Rajah Muthiah Medical College, Annamalainagar",
      "Rajah R S R K Rangarao College",
      "Rajah Serfoji Government College",
      "Rajahs College",
      "Rajahs College Of Sanskrit & Tamil Studies",
      "Rajai Ranm Nursing Institute, Nanded",
      "Rajaji Institude Of Technology",
      "Rajaji Institute Of Technology",
      "RAJAJINAGAR COLLEGE OF EDUCATION",
      "RAJALAKSHMI COLLEGE OF EDUCATION",
      "RAJALAKSHMI COLLEGE OF EDUCATION",
      "Rajalakshmi College Of Nursing, Kancheepuram",
      "Rajalakshmi Engineering College",
      "Rajalakshmi Institute of Technology",
      "Rajalakshmi Polytechnic College",
      "Rajalakshmi Polytechnic College",
      "RAJALAKSHMI PRE-SCHOOL TEACHE TRAINING",
      "Rajalakshmi School of Architecture",
      "Rajamahendri Degree P G College For Woemn",
      "Rajamahendri Degree P G College For Women",
      "Rajamata Jijau Nursing School, Sholapur",
      "RAJAMMAL RANGASAMY ELEMENTARY TTI",
      "Rajan Babu T B Institute",
      "Rajan Babu T B Institute, Delhi",
      "Rajani Smruti Nursing School, Dhule",
      "RAJAPALAYAM DEIVANAI AMMAL COLLEGE OF EDUCATION",
      "Rajapalayam Nurses Trg. Inst., James Hos. , Rajapalyam",
      "Rajapalayam Rajus College",
      "Rajarajeswari College Of Nursing, Bangalore",
      "Rajarajeswari Dental College & Hospital, Bangalore",
      "Rajarajeswari Engineering College",
      "Rajarajeswari Medical College & Hospital, Bangalore",
      "Rajarajeswari School Of Nursing, Bangalore",
      "RAJARAM BAPU INSTITUTE OF BUSINESS MANAGEMENT",
      "RAJARAM BAPU INSTITUTE OF TECHNOLOGY & MANAGEMENT STUDIES",
      "RAJARAM BHOSALE SOCIAL AND EDUCATIONAL SOCIETY",
      "RAJARAM MOHAN ROY COLLEGE OF EDUCATION",
      "RAJARAM SHINDE COLLEGE OF MASTER OF BUSINESS ADMINISTRATION",
      "Rajarambapu Institute of Technology College of Engineering",
      "Rajarshi Chh.Sahu College",
      "RAJARSHI SCHOOL OF MANAGEMENT & TECHNOLOGY",
      "Rajarshi Shahu Arts And Commerce College",
      "Rajarshi Shahu Chhatrapati Institute of Pharmacy, KOLHAPUR",
      "Rajarshi Shahu College of Law",
      "Rajarshi Shahu Evening Law College",
      "Rajarshi Shahu Institute of Management, Aurangabad",
      "Rajarshi Shahu Law College",
      "Rajarshi Shahu Mahavidyalaya",
      "Rajarshi Shahu Polytechnic",
      "Rajarshi Shariwahan Degree College",
      "Rajarshi Shariwahan Degree College Bihar",
      "Rajarshi Tandon Mahila Mahavidyalaya",
      "Rajas Dental College & Hospital, Tirunelveli",
      "Rajas International Institute of Technology for Women",
      "RAJAS TEACHER TRAINING INSTITUTE",
      "Rajashree Chatrapati Shahu Maharaj Government Medical College, Kolhapur",
      "Rajashree School Of Nursing, Muldhana",
      "RAJASHREE SHAHU INSTITUTE OF MANAGEMENT",
      "Rajashri Shahu College of Engineering",
      "Rajashri Shahu Law College",
      "Rajastha School Of Nursing, Jhunjhunu",
      "Rajasthan Agricultural University",
      "Rajasthan Aryan Arts & Shri Mithulaji Kacholiya Commerce & Sh. Satyanarayanji Rathi Science Mahavidyalaya",
      "Rajasthan College Of B.sc Nursing, Dausa",
      "Rajasthan College of Engineering for Women",
      "Rajasthan College Of Nursing, Sikar",
      "Rajasthan College Of Nursing, Jaipur",
      "Rajasthan College Of Nursing, Jhunjhunu",
      "Rajasthan College Of Nursing, Sikar",
      "RAJASTHAN COLLEGE OF TEACHERS TRAINING",
      "RAJASTHAN COLLEGE OF TEACHERS TRAINING, JODHPUR",
      "Rajasthan Dental College & Hospital, Jaipur",
      "Rajasthan Education Institute Of Nursing, Dausa",
      "Rajasthan Girls Poly. College, Baran",
      "RAJASTHAN GIRLS STC SCHOOL",
      "Rajasthan Hospital School Of Nursing, Ajmer",
      "Rajasthan Institute of Engineering & Craft, Dholpur",
      "Rajasthan Institute of Engineering and Technology",
      "Rajasthan Institute Of Nurisng, Jhunjhunu",
      "Rajasthan Institute Of Nursing, Sirohi",
      "Rajasthan Institute Of Nursing, Jhunjhunu",
      "Rajasthan Law College",
      "RAJASTHAN MAHILA COLLEGE OF PHYSICAL EDUCATION, GYAN MARG",
      "Rajasthan Mahila Kalyan Mandal",
      "RAJASTHAN MAHILA TEACHER TRAINING COLLEGE, LAIKOTHI YEOJNA",
      "Rajasthan Mahila Teachers Training College",
      "Rajashree School Of Nursing, Muldhana",
      "RAJASHREE SHAHU INSTITUTE OF MANAGEMENT",
      "Rajashri Shahu College of Engineering",
      "Rajashri Shahu Law College",
      "Rajastha School Of Nursing, Jhunjhunu",
      "Rajasthan Agricultural University",
      "Rajasthan Aryan Arts & Shri Mithulaji Kacholiya Commerce & Sh. Satyanarayanji Rathi Science Mahavidyalaya",
      "Rajasthan College Of B.sc Nursing, Dausa",
      "Rajasthan College of Engineering for Women",
      "Rajasthan College Of Nursing, Sikar",
      "Rajasthan College Of Nursing, Jaipur",
      "Rajasthan College Of Nursing, Jhunjhunu",
      "Rajasthan College Of Nursing, Sikar",
      "RAJASTHAN COLLEGE OF TEACHERS TRAINING",
      "RAJASTHAN COLLEGE OF TEACHERS TRAINING, JODHPUR",
      "Rajasthan Dental College & Hospital, Jaipur",
      "Rajasthan Education Institute Of Nursing, Dausa",
      "Rajasthan Girls Poly. College, Baran",
      "RAJASTHAN GIRLS STC SCHOOL",
      "Rajasthan Hospital School Of Nursing, Ajmer",
      "Rajasthan Institute of Engineering & Craft, Dholpur",
      "Rajasthan Institute of Engineering and Technology",
      "Rajasthan Institute Of Nurisng, Jhunjhunu",
      "Rajasthan Institute Of Nursing, Sirohi",
      "Rajasthan Institute Of Nursing, Jhunjhunu",
      "Rajasthan Law College",
      "RAJASTHAN MAHILA COLLEGE OF PHYSICAL EDUCATION, GYAN MARG",
      "Rajasthan Mahila Kalyan Mandal",
      "RAJASTHAN MAHILA TEACHER TRAINING COLLEGE, LAIKOTHI YEOJNA",
      "Rajasthan Mahila Teachers Training College",
      "Rajasthan Medicare Releef Society College Of Nursing,Bhilwara",
      "Rajasthan Nursing Institute ,Sikar",
      "Rajasthan Nursing School,Jhunjhunu",
      "RAJASTHAN PHYSICAL TEACHER TRAINING VIDYALAYA",
      "Rajasthan Polytechnic College, Bikaner",
      "Rajasthan Polytechnic College, Jhunjhunu",
      "Rajasthan Polytechnic College, Ratangarh",
      "Rajasthan School Of Nursing ,Jhunjhunu",
      "Rajasthan Shiksha Prashikshan Vidyapeeth",
      "RAJASTHAN SHIKSHAK PRASHIKSHAN MAHAVIDYALAYA",
      "RAJASTHAN SHIKSHAK PRASHIKSHAN VIDHYAPEETH",
      "RAJASTHAN SHIKSHAK PRSASHIKSHAN MAHAVIDYALAYA",
      "RAJASTHAN TEACHER TRAINING COLLEGE, AGOLAI",
      "RAJASTHAN TEACHER TRAINING COLLEGE,NARNAUL",
      "RAJASTHAN TEACHER TRAINING COLLEGE,SHERGARH",
      "Rajasthan Teachers Training College For Women",
      "RAJASTHAN TEACHERS TRAINING COLLEGE, SADULPUR",
      "RAJASTHAN TEACHERS TRAINING COLLEGE,BIKANER",
      "RAJASTHAN TEACHERS TRAINING COLLEGE,BISSAU",
      "Rajasthan Technical University",
      "Rajasthan University of Health Sciences",
      "Rajasthan Vidyapeeth Haribhau Upadhya Shikshak Mahavidyalaya",
      "Rajasthan Vidyapeeth Homoeopathic Medical College",
      "Rajasthan vidyapeeth Jai Nagar",
      "RAJASTHAN VIDYAPEETH KUL HARI BHAU UPADHAYAYA MAHILA SHIKSHAK MAHAVIDYALYA",
      "Rajasthan Vidyapeeth Vijay S.Pathik Sharamjeevi College",
      "RAJAT DEGREE COLLEGE",
      "RAJAT GIRLS DEGREE COLLEGE",
      "RAJAT MAHILA MAHAVIDYALAYA",
      "RAJATHAN SHIKSHAK PRASHIKSHAN VIDYAKEETH",
      "Rajavijaysingh Commerce Raja Jaysing Arts College",
      "Rajbahadur Singh Smarak Mahavidyalaya",
      "Rajdeep Mahila Degree College",
      "Rajdeo Krishak Mahavidyalaya",
      "RAJDEO KRISHIK MAHAVIDYALAYA",
      "RAJDEV TEACHER TRAINING COLLEGE",
      "Rajdhani College",
      "Rajdhani College",
      "Rajdhani College of Engineering",
      "RAJDHANI COLLEGE OF ENGINEERING & MANAGEMENT",
      "Rajdhani Law College",
      "Rajdhani Polytechnic College",
      "Rajdhani School Of Nursing , Khurda",
      "Raje Chhatrapati Kala Mahavidyalaya",
      "Raje Ramrao College",
      "Rajebahadur Institute Of Nursing Education,Nashik",
      "Rajeev Academy For Technology & Management",
      "RAJEEV COLLEGE OF EDUATION",
      "Rajeev College Of Nursing , Hassan",
      "RAJEEV GANDHI COLLEGE",
      "RAJEEV GANDHI COLLEGE OF EDUCATION",
      "Rajeev Gandhi College Of Management Studies",
      "Rajeev Gandhi College Of Nursing , Bhopal",
      "Rajeev Gandhi College, Bhopal",
      "RAJEEV GANDHI DEGREE COLLEGE",
      "RAJEEV GANDHI EDUCATIONAL COLLEGE",
      "RAJEEV GANDHI KENDRIYA SANSKRIT VIDYA PEETA SRINGERI",
      "Rajeev Gandhi Memorial College of Engineering and Technology",
      "Rajeev Gandhi Memorial Teacher's Training College",
      "Rajeev Gandhi Prodyogiki Mahavidyalaya Gram Salaiya",
      "Rajeev Gandhi Proudyogiki Mahavidyalaya",
      "RAJEEV GANDHI RURAL EDUCATION",
      "RAJEEV GANDHI SHIKSHA MAHAVIDYALAYA",
      "RAJEEV GANDHI TEACHER TRAINING COLLEGE",
      "RAJEEV GANDHI VOCATIONAL EDUCATION AND TRAINING COLLEGE",
      "Rajeev Institute of Technology",
      "RAJEEV MEMORIAL CHARITABLE SOCIETY",
      "RAJEEV MEMORIAL INSTITUTE OF EDUCATION AND TECHNOLOGY",
      "Rajeev Polytechnic, Hassan",
      "Rajeev School Of Nursing , Hassan",
      "Rajendra Academy for Teacher's Education",
      "Rajendra Agricultural University",
      "Rajendra College",
      "RAJENDRA DEGREE COLLEGE",
      "Rajendra Institute of Medical Sciences, Ranchi",
      "Rajendra Law College",
      "Rajendra Mane College of Engineering & Technology",
      "Rajendra Mane Polytechnic",
      "Rajendra Medical College",
      "Rajendra Medical College And Hospital , School Of Nursing , Ranchi",
      "Rajendra Polytechnic",
      "Rajendra Prasad Degree College",
      "RAJENDRA PRASAD P.G. COLLEGE",
      "Rajendra School Of Nursing , Sirsa",
      "Rajendra Singh Khetasar Memorial Polytechnic College",
      "Rajesambhaji bahu Sevabhavi Sanstha and Dagdi Shahajanpur Dilasa Diploma Special Education",
      "RAJESH KUMAR MAHAVIDYALAYA",
      "Rajesh Pandey College of Law",
      "RAJESH PILOT MEMORIAL TEACHER TRAINING COLLEGE",
      "Rajeshwar Lal College",
      "Rajeshwar Lal College",
      "Rajeswari School Of Nursing,Hyderabad",
      "Rajeswari Vedachalam Government Arts College",
      "RAJGAD DNYANPEETH ADHYAPAK VIDYALAYA",
      "Rajgad Dnyanpeeth College of Pharmacy , BHOR",
      "Rajganj Degree College",
      "Rajguru College Applied Sciences Woman",
      "Rajindra College",
      "Rajindra Government College",
      "RAJIV ACADEMY FOR TECHNOLOGY & MANAGEMENT",
      "RAJIV ACADEMY FOR TECHNOLOGY & MANAGEMENT",
      "RAJIV GANDHI B.ED. COLLEGE",
      "Rajiv Gandhi Business school",
      "Rajiv Gandhi College",
      "RAJIV GANDHI COLLEGE EDUCATION",
      "RAJIV GANDHI COLLEGE EDUCATION",
      "RAJIV GANDHI COLLEGE OF BACHELOR IN EDUCATION",
      "RAJIV GANDHI COLLEGE OF EDUCATION",
      "Rajiv Gandhi College of Engineering",
      "Rajiv Gandhi College of Engineering & Technology",
      "Rajiv Gandhi College of Law",
      "Rajiv Gandhi College Of Nursing , Bangalore",
      "Rajiv Gandhi College Of Nursing,Jammu",
      "Rajiv Gandhi College of Pharmacy , Bhopal",
      "RAJIV GANDHI D.ED COLLEGE",
      "Rajiv Gandhi Degree College",
      "Rajiv Gandhi Degree College",
      "Rajiv Gandhi Degree College",
      "Rajiv Gandhi Degree College",
      "Rajiv Gandhi Degree College, Rajahmundry",
      "Rajiv Gandhi Government Polytechnic",
      "Rajiv Gandhi Govt. P.G. College",
      "Rajiv Gandhi Homoeopathic Medical College, Hospital and Research Centre Toll Tax Barrier",
      "RAJIV GANDHI INSTITUTE OF D.ED",
      "Rajiv Gandhi Institute of Law , Kakinada",
      "Rajiv Gandhi Institute of Medical Science, Adilabad",
      "Rajiv Gandhi Institute of Medical Science, Kadapa",
      "Rajiv Gandhi Institute of Medical Science, Srikakulam",
      "Rajiv Gandhi Institute Of Mgt. Sciences",
      "Rajiv Gandhi Institute of Pharmacy , Jammu",
      "Rajiv Gandhi Institute of Technology",
      "Rajiv Gandhi Institute of Technology Karnataka",
      "Rajiv Gandhi Institute Of Technology, Vidhyanagar",
      "RAJIV GANDHI KENDRIYA SANSKRIT",
      "RAJIV GANDHI MAHAVIDYALAYA,SHIKSHA SANKAYA B.ED.,",
      "RAJIV GANDHI MAHILA MAHAVIDYALAYA",
      "Rajiv Gandhi Mahila Mahavidyalaya",
      "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane",
      "Rajiv Gandhi Medical College, And Chhatrapati Shivaji Maharaj Hospital",
      "Rajiv Gandhi Memorial College Bongaigaon",
      "Rajiv Gandhi Memorial College Education",
      "Rajiv Gandhi Memorial School Of Nursing , Jodhpur",
      "Rajiv Gandhi National University of Law",
      "Rajiv Gandhi National University of Law",
      "Rajiv Gandhi Nursing School,Bikaner",
      "RAJIV GANDHI P.G. COLLEGE",
      "Rajiv Gandhi Polytechnic",
      "Rajiv Gandhi Polytechnic Nanded",
      "Rajiv Gandhi Polytechnic, Bangalore",
      "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
      "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
      "Rajiv Gandhi RECS Polyechnic, Kasimkota",
      "Rajiv Gandhi School of Intellectual Property Law",
      "Rajiv Gandhi School Of Nursing, Bangalore",
      "Rajiv Gandhi School Of Nursing, Bellary",
      "Rajiv Gandhi School Of Nursing, Bidar",
      "Rajiv Gandhi School Of Nursing, Hubli",
      "Rajiv Gandhi School Of Nursing, Ernakulam",
      "RAJIV GANDHI SHIKSHAN MAHAVIDYALAYA",
      "Rajiv Gandhi Technical University",
      "Rajiv Gandhi University",
      "Rajiv Gandhi University Of Health Sciences",
      "Rajiv Gandhi University of Knowledge and Technologies (AP IIIT)",
      "Rajiv Gandhi University of Knowledge Technologies",
      "Rajiv Gandhi University of Knowledge Technology",
      "Rajiv Gandhi Vidhi Mahavidyalay",
      "RAJIV GANDHI VOCATIONAL EDUCATION & TRAINING COLL",
      "Rajiv Inst. Of Tech And Mgt Studies, Tanuku",
      "Rajiv Memorial Education Soeity College of Pharmacy, Gulbarga",
      "Rajiv School Of Nursing, Chitradurga",
      "RAJIVGANDHI COLLEGE OF EDUCATION",
      "RAJKISHOR SINGH MAHAVIDYALAYA",
      "RAJKIYA DISKSHA VIDYALAYA",
      "Rajkiya Girls Degree College",
      "Rajkiya Mahavidyalaya",
      "Rajkiya Mahavidyalaya",
      "Rajkiya Mahavidyalaya",
      "Rajkiya Mahavidyalaya",
      "Rajkiya Mahavidyalaya Faridpur",
      "Rajkiya Mahila Degree College",
      "Rajkiya mahila Mahavidyalayao",
      "Rajkiya Manpuriya Shastri Sanskrit Mahavidyalaya",
      "Rajkiya Vithal Nath Acharya Sanskrit College",
      "Rajkot Homoeopathic Medical College",
      "Rajkumari Amrit Kaur College of Nursing , Delhi",
      "Rajkumari Sanatombi Devi College of Education",
      "Rajmata Jijau Nursing School ,Latur",
      "Rajmata Jijau Shikshan Prasarak Mandal Institute of Pharmacy , Pune",
      "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
      "RAJMATA VIJAYARAJE SCINDIA SHIKKSHAK PRASHIKSHAN SANSTHAN",
      "Rajmata Vijayraje Sindhiya Polytechnic college",
      "Rajputana College of Pharmacy , Bangalore",
      "Rajputana Law College",
      "Rajputana Vidhi Mahavidyalaya",
      "Rajshree Institute of Management & Technology",
      "Rajshree Mulak Polytechnic For Women",
      "Rajshri Institute of Medical Science",
      "Rajsunakhala College",
      "Raksha Shakti University",
      "Raksha Society for the Care of Children with Multiple Handicaps",
      "RAKSHPAL BAHADUR MANAGEMENT INSTITUTE",
      "RAKSHPAL BAHADUR MANAGEMENT INSTITUTE, BAIREILY",
      "RAKSHPAL BAHADUR TEACHERS TRAINING INSTITUTE",
      "RAKSHPAL BALESAHIR TEACHER TRAINING INSTITUTE",
      "RAM - EESH INSTITUTE OF EDUCATION",
      "RAM -EESH INSTITUTE OF EDUCATION",
      "Ram Adhar Nursing College , Ambedkar Nagar",
      "Ram Adhar Nursing College,Ambedkar Nagar",
      "RAM AVADH SMARK MAHAVIEYALAYA",
      "Ram Bali National Degree College",
      "Rajkiya mahila Mahavidyalayao",
      "Rajkiya Manpuriya Shastri Sanskrit Mahavidyalaya",
      "Rajkiya Vithal Nath Acharya Sanskrit College",
      "Rajkot Homoeopathic Medical College",
      "Rajkumari Amrit Kaur College of Nursing , Delhi",
      "Rajkumari Sanatombi Devi College of Education",
      "Rajmata Jijau Nursing School ,Latur",
      "Rajmata Jijau Shikshan Prasarak Mandal Institute of Pharmacy , Pune",
      "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
      "RAJMATA VIJAYARAJE SCINDIA SHIKKSHAK PRASHIKSHAN SANSTHAN",
      "Rajmata Vijayraje Sindhiya Polytechnic college",
      "Rajputana College of Pharmacy , Bangalore",
      "Rajputana Law College",
      "Rajputana Vidhi Mahavidyalaya",
      "Rajshree Institute of Management & Technology",
      "Rajshree Mulak Polytechnic For Women",
      "Rajshri Institute of Medical Science",
      "Rajsunakhala College",
      "Raksha Shakti University",
      "Raksha Society for the Care of Children with Multiple Handicaps",
      "RAKSHPAL BAHADUR MANAGEMENT INSTITUTE",
      "RAKSHPAL BAHADUR MANAGEMENT INSTITUTE, BAIREILY",
      "RAKSHPAL BAHADUR TEACHERS TRAINING INSTITUTE",
      "RAKSHPAL BALESAHIR TEACHER TRAINING INSTITUTE",
      "RAM - EESH INSTITUTE OF EDUCATION",
      "RAM -EESH INSTITUTE OF EDUCATION",
      "Ram Adhar Nursing College , Ambedkar Nagar",
      "Ram Adhar Nursing College,Ambedkar Nagar",
      "RAM AVADH SMARK MAHAVIEYALAYA",
      "Ram Bali National Degree College",
      "Ram Kumari Ayodhya Law College",
      "RAM LAGAN MAHAVIDYALAYA",
      "Ram Lagan Mahavidyalaya",
      "Ram Lakhan Degree College",
      "Ram Lakhan Singh Yadav College",
      "Ram Lakhan Singh Yadav College",
      "Ram Lal Anand College",
      "Ram Lal Anand College (Evening)",
      "RAM LALIT SINGH MAHAVIDYALAYA",
      "RAM MURTI DEVI GIRLS COLLEGE",
      "RAM NAGAR P.G. COLLEGE",
      "Ram Nagina Kisan Mahavidyalaya",
      "RAM NAGINA KISAN MAHAVIDYALAYA",
      "RAM NARAYAN INSTITUTE OF EDUCATION",
      "RAM NARAYAN INSTITUTE OF EDUCATION",
      "RAM NARAYAN INSTITUTE OF MANAGEMENT & TECH",
      "RAM NAWAL SINGH SMARAK DEGREE COLLEGE",
      "Ram Nawal Singh Smarak Degree College",
      "Ram Newaj Singh Mahavidyalaya",
      "RAM NIWAJ SINGH MAHAVIDYALAYA",
      "RAM PRASAD BOHARA TEACHER TRAINING COLLEGE",
      "Ram Prasad Degree College",
      "RAM PRATAP RANG LAL INSTITUTE OF MANAGEMENT & TECHNOLOGY",
      "RAM RAJI DEVI MAHILA MAHAVIDYALAYA",
      "Ram Sahai Rajkeeya Mahavidyalaya",
      "Ram Sajivan Singh College of Law",
      "Ram Sajivan Singh Mahavidyalaya",
      "Ram Sakal Singh Science College",
      "Ram Singh Mahavidyalaya",
      "RAM SINGH MAHAVIDYLAYA",
      "Ram Snehi College Of Nursing, Bhilwara",
      "Ram Vijay Smarak College",
      "RAMA - EESH INSTITUTE OF EDUCATION",
      "Rama Bai Ambedkar Government Degree College",
      "RAMA COLLEGE OF EDUCATION",
      "Rama College Of Nursing, Kanpur",
      "Rama Dental College, Hospital & Research Centre , Kanpur",
      "RAMA DEVI GIRLS COLLEGE",
      "RAMA DEVI KANYA MAHAVIDYALAYA",
      "RAMA DEVI TEACHER TRAINING COLLEGE",
      "Rama Devi Womens College",
      "RAMA INSTITUTE OF HIGHER EDUCATION",
      "Rama Jain Kanya Mahavidyalaya",
      "Rama Krishna Degree College",
      "Rama Krishna Degree College, Kamareddy",
      "Rama Krishna Degree College, Nalgonda",
      "Rama Krishna Degree College, Nellore",
      "Rama Krishna Institute Of Moral & Spiritual Education",
      "Rama Krishna Mission Seva Pratishthan Vivekananda Institute Of Medic",
      "Rama Krishna Mission Vivekananda Centenary College",
      "Rama Krishna School Of Nurisng , Bangalore",
      "RAMA KRISHNA TEACHER TRAINING COLLEGE, ROHTAK",
      "RAMA KRISHNA TEACHERS TRAINING INSTITUTE, NEW DELHI",
      "Rama Krishna Vivekananda College of Education",
      "RAMA MAHAVIDYALAYA",
      "Rama Mahavidyalaya",
      "Rama Medical College Hospital and Research Centre, Hapur, Gaziabad",
      "Rama Medical College Hospital And Research Centre, Kanpur",
      "Rama Prabha College Of Arts And Science",
      "RAMA PRATAP PHYSICAL TEACHER TRAINING COLLEGE",
      "Rama School Of Nursing , Kaithal",
      "Rama School Of Nursing , Kanpur",
      "RAMA TEACHER TRAINING COLLEGE",
      "Rama University",
      "RAMA VILASOM TEACHER TRAINING INSTITUTE",
      "Ramabai Government Girls Degree College",
      "Ramachandra College of Engineering",
      "RAMACHANDRA TEACHERS TRAINING INSTITUTE",
      "RAMADEVI MAHILA TEACHERS TRAINING COLLEGE",
      "Ramadevi School Of Nursing , Kendra Para",
      "Ramadhin College",
      "Ramajee Mahavidyalaya",
      "Ramakrish Polytechnic, Srinivasapur",
      "Ramakrishan School Of Nursing , Kakinada",
      "Ramakrishna College of Law",
      "RAMAKRISHNA INSTITUTE OF MORAL & SPIRITUAL EDUCATION",
      "RAMAKRISHNA MEMORIAL B.ED. TRAINING COLLEGE",
      "Ramakrishna Mission Brahmananda College of Education",
      "Ramakrishna Mission Hospital , School Of Nursing , Itanagar",
      "Ramakrishna Mission Seva Pratishtan Ma Sarada , College Of Nursing , Kolkata",
      "Ramakrishna Mission Seva Pratishthan ,Ma Sarada College Of Nursing,Kolkata",
      "Ramakrishna Mission Shikshan Mandira",
      "Ramakrishna Mission Shilpamandira",
      "Ramakrishna Mission Sikshana Mandira",
      "Ramakrishna Mission Technical Institute",
      "RAMAKRISHNA MISSION VIVEKANAN UNIVERSITY",
      "Ramakrishna Mission Vivekanand College",
      "Ramakrishna Mission Vivekanand University",
      "Ramakrishna Mission Vivekananda Educational Research Institute",
      "RAMAKRISHNA PARAMAHAMSA EDUCATIONAL TRUST",
      "Ramakrishna Sarada Mission Matri Bhavan ,Kolkata",
      "Ramakrishna Vivekananda Mission",
      "RAMAKRISHNAN CHANDRA COLLEGE EDUCATION",
      "Raman College Of Nursing , Mysore",
      "Raman College of Pharmacy , Bangalore",
      "Raman Degree College, Razole",
      "RAMAN MEMORIAL TEACHER TRAINING INSTITUTE",
      "Raman Polytechnic",
      "Raman Polytechnic College Dungargarh",
      "Raman School Of Nursing , Keonjhar",
      "RAMAN TEACHERS TRAINING INSTITUTE",
      "Ramanand Arya DAV College",
      "Ramanand Institute of Pharmacy Management and Technology",
      "RAMANAND TEACHER TRAINING COLLEGE",
      "RAMANAND VIDYAMANDIR WOMENS TEACHER TRAINING COLLEGE",
      "Ramananda Centenary College",
      "Ramananda College",
      "Ramanandatirtha Engineering College",
      "Ramanarayan College",
      "Ramanuj Pratap Degree College",
      "RAMANUJAN COLLEGE OF MANAGEMENT",
      "RAMANUJAN TEACHER TRAINING COLLEGE",
      "RAMANUJAN TEACHER TRAINING COLLEGE",
      "Ramappa Engineering College",
      "RAMARAJA INSTITUTE OF TECH. & SCIENCE",
      "RAMARANI Institute of Technology",
      "Ramarao Adik Edu Soc's Ramarao Adik Inst.Of Tech",
      "Ramasamy Tamil College",
      "Ramatuar Gautam Sanskrit College",
      "RAMBACHAN YADAV MAHAVIDYALAYA",
      "Rambai Ambedkar Government Degree College",
      "RAMBHAU LINGADE COLLEGE OF EDUCATION",
      "Rambhauji Lingade Polytechnic College",
      "Ramchandra Sanskritik KridaMandal C.P. College of D.Pharmacy , Jalna",
      "Ramchandra Sanskrutik Krida Mandal's Shri R D Bhakta Polytechnic",
      "Ramdeo Singh Yadav Law College",
      "Ramdev Degree College",
      "Ramdev Memorial Mahavidyalaya",
      "Ramdevi Ramdayal Mahila Poly , KANPUR",
      "Ramdulari Balika Sanskrit College",
      "RAMDULARI MAHILA SHIKSHAK PRASHIKSHAN SCHOOL",
      "Ramesh Jha Mahila College",
      "RAMESH KOTHALE COLLEGE OF EDUCATION",
      "Ramesh Prasad Yadav Teacher's Training College",
      "RAMESHCHANDRA MUNGHATE WOMENS COLLEGE OF EDUCATION",
      "Rameshwar Chethru College",
      "Rameshwar Das Agarwal Girls Degree College",
      "Rameshwar Mahavidyalaya",
      "Rameshwar Yadav Manihari College",
      "RAMESHWARAM INSTITUTE OF EDUCATION & TRAINING",
      "RAMESHWARAM INSTITUTE OF TECH & MANAGEMENT",
      "Rameshwari Devi Girls College",
      "RAMESHWARI DEVI KANYA MAHAVIDYALAYA",
      "RAMESHWARI TEACHER TRAINING INSTITUTE",
      "RAMESWARI DEVI KANYA MAHAVIDYALAYA",
      "Ramgarh College",
      "Ramgarhia College",
      "Ramgarhia College Of Education",
      "Ramgarhia Girls College",
      "Ramgarhia Institute of Engineering and Technology",
      "Ramgarhia Institute Of Health Sciences & Research , Kapurthala",
      "RAMGARHIA TEACHER TRAINING COLLEGE",
      "RAMGARHIA TEACHER TRAINING COLLEGE",
      "Ramgopal Nursing School,Bhiwani",
      "RAMGULAM RAI POST GRADUATE COLLEGE",
      "Rami Devi Anm Training Centre,Tonk",
      "Rami Devi College Of Nursing , Med City, Tonk",
      "Rami Devi College Of Nursing,Tonk",
      "Rami Devi Nursing And Paramedical Institute,Tonk",
      "Ramireddy Subbarami Reddy Engineering College",
      "Ramisht College Education",
      "RAMJAG MAHAVIDYALAYA",
      "Ramjas College",
      "RAMJAS TEACHER TRAINING COLLEGE",
      "Ramji Sahai Degree College",
      "RamKrishan Paramhans Polytechnic College",
      "Ramkrishanagar College",
      "Ramkrishna College Of Nursing,Guna",
      "Ramkrishna Institute Of Medical Science,Raipur",
      "Ramkrishna Mahavidyalaya",
      "Ramkrishna Mahavidyalaya",
      "Ramkrishna Mission Resindential College",
      "Ramkrishna Mission Seva Pratisthan , Kolkatta",
      "Ramkrishna Mission Shiksha Mandir",
      "Ramkrishna Mission Silpapitha",
      "Ramkrishna Mission Vidyamandir",
      "Ramkrishna Nursing School,Aurangabad",
      "Ramkrishna Sarada Mission Matri Bhavan , Kolkatta",
      "Ramkrishna School Of Nursing, Gwalior",
      "Ramkrishna Welfare Nursing & Paramedical Institute , Patna",
      "Ramlakhan Singh Yadav College",
      "Ramleela Degree College, Palakonda",
      "Ramnagar College",
      "Ramnagar Degree College",
      "RAMNAGAR P.G. COLLEGE",
      "Ramnarain Ruia College",
      "RAMNARAYAN INSTITUTE OF EDUCATION",
      "RAMNATH SINGH MAHAVIDYALAYA",
      "RAMNATH VIMLA DEVI KHALRA INSTITUTE OF EDUCATION",
      "Ramnihora Institute Of Nursing And Paramedical, Allahabad",
      "Ramnihora Institute Of Nursing And Paramedicals,Allahabad",
      "RAMPAL MOURYA MAHAVIDYALAYA",
      "RAMPRIYA TEACHER TRAINING INSTITUTE",
      "Rampurhat College",
      "Ramraje School Of Nursing,Ratnagiri",
      "Ramraji Devi Mahila Mahavidyalaya",
      "RAMRAO PATIL B.ED. COLLEGE",
      "RAMRAZI DEVI MAHILA MAHAVIDYALAYA",
      "Rams Rural Academy for Management Studies",
      "Ramsaday College",
      "Ramsnehi College Of Nursing , Bhilwara",
      "Ramsnehi School Of Nursing , Bhilwara",
      "RAMSWROOP AGRWAL TEACHER TAINING COLLEGE",
      "RAMSWROOP SIKSHA MAHA VIDYALAYA",
      "Ramthakur College",
      "Ramu Seetha Polytechnic College",
      "Ramu Seetha Polytechnic College",
      "Ramya Sathianathan Polytechnic College",
      "RAN MOHAR SINGH TEACHER TRAINING COLLEGE",
      "RANA PRATAP MAHILA TEACHER TRAINING COLLEGE",
      "Rana Shiksha Shivir Degree College",
      "Ranaghat College",
      "Ranapratap Degree College",
      "RANBIR SINGH GEETA INSTITUTE OF TEACHER EDUCATION",
      "Ranchi College",
      "Ranchi College",
      "Ranchi College of Pharmacy , Ranchi",
      "Ranchi Institute of Neuro-Psychiatry & Allied Sciences Kanke",
      "Ranchi Instt. of Neuro-Psychiatry And Allied Sciences, Kanke, Ranchi",
      "Ranchi Instt. Of NeuroPsychiatry and Allied Sciences,Kanke,Ranchi",
      "Ranchi University",
      "Ranchi University Ranchi",
      "Ranchi Women'S College",
      "Ranchi Womens College",
      "Rane Polytechnic Technical Campus",
      "Ranebennur College Of Nursing , Bangalore",
      "Ranebennur College Of Nursing,Bangalore",
      "RANEBENNUR TALUKA EDUCATION SOCIETY",
      "Rang Frah Government College",
      "Rangachachi College",
      "Rangammal Memorial Teacher Training School",
      "Rangamudri College Of Science & Arts",
      "Rangamudri Degree College, Vizianagaram",
      "Ranganathan Architecture College",
      "Ranganathan Engineering College",
      "Ranganathan Polytechnic College",
      "Ranganayakamma Womens",
      "Rangapara College",
      "Rangaraya Medical College",
      "Rangaraya Medical College, Kakinada",
      "RANGASWAMY COLLEGE OF EDUCATION",
      "Rangia Teacher Training College",
      "Rangyiya College",
      "Rani Avanti Bai Lodhi Nursing School,Chindwara",
      "RANI BHAGYAWATI DEVI MAHILA MAHAVIDYALAYA",
      "Rani Birla Girls College",
      "Rani Chandra Prabha Mahavidyalaya",
      "RANI CHANDRA PRABHA MAHAVIDYALAYA",
      "Rani Channamma University",
      "RANI DEVADOSS WOMEN TEACHER TRAINING SCHOOL",
      "Rani Dhanyakumari College",
      "Rani Durgavati Government P.G. College",
      "Rani Durgavati University",
      "Rani Durgavati Vishwavidyalaya",
      "RANI DURGAWATI UNIVERSITY",
      "RANI DURGAWATI UNIVERSITY DEPARTMENT OF PHYSICAL EDUCATION",
      "Rani Durgawati University,",
      "Rani Ganesh Kunwari Degree College",
      "Rani Jhansi Laxmi Bai Government Polytechnic Loharu",
      "RANI LAXMI BAI MAHILA DEGREE COLLEGE",
      "RANI LAXMI BAI TEACHER TRAINING COLLEGE",
      "Rani Laxmibai Mahavidyalaya",
      "Rani Laxmibai Mahila Mahavidyalaya",
      "RANI LAXMIBAI SHARIRIK SHIKSHAN MAHAVIDYALAYA",
      "Rani Meyyammai College Of Nursing , Annamalai Nagar",
      "Rani Parvati Devi College",
      "Rani Rudrama Devi (Rrd) Degree College",
      "Rani Shiksha Shivir Degree College",
      "RANI SUSHMA DEVI MAHILA MAHAVIDYALAYA",
      "Rani Sushma Devi Mahila Mahavidyalaya",
      "Rani Tirumala Devi College Of Science",
      "RANIBAI AGNIHOTRI SHARIRIK SHIKSHAN MAHAVIDYALAYA",
      "Ranibai Agnihotri Sharirik Shikshan Mahavidyalaya",
      "Raniganj Girls College",
      "Ranipet Institute Of Technology",
      "Ranippettai Engineering College",
      "Ranippettai Institude Of Technology",
      "RANIPPETTAI TEACHER TRAINING INSTITUTE",
      "RANJEET SINGH MEMORIAL TEACHER TRAINING COLLEGE AND TECHNOLOGY",
      "Ranjit College Education",
      "RANJIT SINGH MEMORIAL POST GRADUATE COLLEGE",
      "Rankireddy Pattabhi Ramaiah Degree College",
      "RANSAMRAT KREEDA MANDALS COLLEGE OF PHYSICAL EDUCATION",
      "Ranthambor College Of Nursing,Sawai Madhopur",
      "Ranthambore Law College",
      "RANVEER RANANAJAYA COLLEGE",
      "RANVIR RANANJAL P.G.COLLEGE",
      "Ranvir Rannjaya Postgraduate College",
      "Rao & Naidu Engineering College",
      "RAO ABHAY SINGH TEACHER TRAINING COLLEGE",
      "RAO ADAL SINGH TEACHER TRAINING COLLEGE",
      "RAO B.ED. COLLEGE",
      "Rao Bahadur Y. Mahabaleswarappa Engineering College",
      "Rao Birender Singh College Education",
      "RAO BIRENDER SINGH TEACHER TRAINING COLLEGE",
      "RAO DALIP SINGH TEACHER TRAINING COLLEGE",
      "Rao Jai Ram Polytechnic",
      "RAO JAI RAM TEACHER TRAINING COLLEGE",
      "RAO KHEM CHAND TEACHER TRAINING COLLEGE",
      "Rao Lal Singh College Education",
      "RAO LAL SINGH TEACHER TRAINING COLLEGE,AMBALA CITY",
      "RAO LAL SINGH TEACHER TRAINING COLLEGE,BHIWANI",
      "RAO LAL SINGH TEACHER TRAINING COLLEGE,GARBA",
      "RAO LAL SINGH TEACHER TRAINING COLLEGE,SIDHRAWALI",
      "RAO MAHAIVA INSTITUTE OF MANAGEMENT & TECHONLOGY",
      "RAO MOHAR SINGH ELEMENTARY INSTITUTE OF EDUCATION",
      "RAO MOOL CHAND TEACHER TRAINING COLLEGE",
      "RAO NEKI RAM MEMORIAL TEACHER TRAINING COLLEGE",
      "RAO O.P.M. TEACHER TRAINING COLLEGE",
      "RAO PAHLAD SINGH TEACHER TRAINING COLLEGE",
      "Rao Pratap Singh College",
      "RAO RAM SINGH TEACHER TRAINING COLLEGE",
      "RAO RANJEET TEACHER TRAINING COLLEGE",
      "RAO ROOP CHAND MEMORIAL TEACHER TRAINING COLLEGE",
      "Rao s College of Pharmacy",
      "RAO SULTAN SINGH TEACHER TRAINING COLLEGE",
      "RAO UDMI RAM MEMORIAL TEACHER TRAINING COLLEGE",
      "RAO UMRAO SINGH TEACHERS TRAINING COLLEGE",
      "RAO'S INSTITUTE OF MGT. STUDIES",
      "Raos College of Pharmacy , Nellore",
      "Raos Degree College",
      "Raos Degree College, Nandyal",
      "Raosaheb Gogate College Of Commerce And Smt. Saraswatibai Ganshet Walke College Of Arts",
      "Rapelle Christian Degree College",
      "RAPHAEL",
      "Rapsbun School Of Nursing, Shillong",
      "RASAMA COLLEGE OF EDUCATION",
      "RASHIDA BEGAM MUSLIM MAHAVIDYALAYA",
      "Rashidiya Rani Sagari Teacher's Education College",
      "RASHMI EDUCATIONAL SOCIETY",
      "RASHMI EDUCATIONAL TRAINING",
      "Rashmidhar Teja Degree College,",
      "RASHOBA TEACHER TRAINING COLLEGE",
      "RASHTIRYA MANAV SANSADHAN AVEM VIKAS SANSTHAN",
      "RASHTRA KAVI MAITHILI SHARAN GU.P.T MAVIDYALAYA",
      "RASHTRA UDAY TEACHE TRAINING COLLEGE",
      "RASHTRAHIT EDUCATION SOCIETY ABHINAV COLLEGE OF EDUCATION",
      "Rashtramata College of Special Education",
      "Rashtrapita Mahatma Gandhi Arts & Commerce College",
      "Rashtrasant Tukadoji Maharaj Nagpur University",
      "Rashtrasant Tukdoji College",
      "RASHTREEYA VIDYALAYA TEACHERS TRAINING INSTITUTE",
      "RASHTRIYA B.P.ED COLLEGE",
      "RASHTRIYA CHETNA COLLEGE OF TEACHER EDUCATION",
      "Rashtriya Degree College",
      "Rashtriya Degree College",
      "Rashtriya Drushtihin Shikshan and Punarvas Sanstha",
      "RASHTRIYA P.G. COLLEGE",
      "Rashtriya Sanskrit Sansthan",
      "RASHTRIYA SANSKRIT SANSTHAN",
      "RASHTRIYA SANSKRIT SANSTHAN",
      "RASHTRIYA SANSKRIT SANSTHAN (DEEMED UNIVERSITY)",
      "Rashtriya Sanskrit Sansthan (Deemed University)",
      "RASHTRIYA SANSKRIT SANSTHAN(DEEMED UNIVERSITY)",
      "Rashtriya Sanskrit Vidyapeetha University",
      "RASHTRIYA TEACHER TRAINING COLLEGE",
      "RASHTROTTHANA COLLEGE EDUCATION",
      "RASHTROTTHANA SHIKSHAKA TARABETHI SAMSTHE RASHTROTTHANA T.T.I.",
      "RASI COLLEGE OF EDUCATION",
      "RASIDA BEGAM MUSLIM MAHAVIDYALAYA",
      "Rass Academy College Of Nursing , Sivagangai",
      "Rass Academy College Of Nursing , Sivagangai",
      "RASS College of Special Education, Rashtriya Seva Samithi",
      "RASS-JB COLLEGE FOR PROFESSIONAL STUDIES",
      "RASTIRYA VIDYA EDUCATION COLLEGE",
      "Rastogi College Of Nursing , Durg",
      "Rastogi College Of Nursing , Durg",
      "Rastogi College Of Nursing Rajnandgaon,",
      "Rastogi College Of Nursing,Rajnandgaon",
      "Rastraguru Surendranath College",
      "RASTRIYA SANSKRIT SANSTHAN",
      "Rastriya Seva Samithi M P H W F Trg. Institute",
      "Ratan Global Business School",
      "Ratan Sen Degree College",
      "RATAN SEN DEGREE COLLEGE",
      "RATANSEN DEGREE COLLEGE",
      "RATEACHERS TRAININGAN PROFESSIONAL EDUCATION COLLEGE",
      "RATEACHERS TRAININGAN PROFESSIONAL EDUCATION COLLEGE",
      "RATEACHERS TRAININGAN SINGH GIRLS TEACHER TRAINING COLLEGE",
      "Rathinam College Of Arts And Science",
      "Rathinam Technical Campus",
      "Rathinavel Subramaniam College Of Arts And Science",
      "Rathinavel Subramaniam Polytechnic College",
      "Rathna College Of Nursing , Hassan",
      "Rathna College Of Nursing,Hassan",
      "Rathna Polytechnic College",
      "Rathna School Of Nursing , Hassan",
      "Rathnavel Subaramaniam College Of Arts & Science",
      "Ratnagiri Degree College",
      "Ratnam College Of Arts Science & Commerce",
      "Ratnam Degree College, Nellore",
      "Ratnam Institute Of Computer Science And Management",
      "Ratnapeeth College",
      "Ratnavel Subramaniam College of Engineering & Technology",
      "Ratnavel Subramaniam Polytechnic College",
      "RATNI DEVI BALIKA BSTC VIDHYALAYA",
      "Rattan Institute of Technology and Management",
      "Rattan Professional Edu Soc College Of Nursing , Mohali",
      "RATTAN PROFESSIONAL EDUCATION COLLEGE",
      "Rattan Professional Education College , Mohali",
      "Rattan Professional Education College Of Nursing , Mohali",
      "Rattan Professional Eudcation College , Mohali",
      "Ratulia Secondary Teacher's Training Institute",
      "Raveendras Rayalaseema Degree College",
      "Ravenshaw College",
      "Ravenshaw Morning College",
      "Ravenshaw University",
      "Raver Parisar Shikshan Prasarak Mandal's Sri Vitthalrao Naik Arts Comm& Sc College",
      "RAVI COLLEGE OF EDUCATION",
      "RAVI PG COLLEGE",
      "Ravi Shankar Business School",
      "RAVIDRA SINGH SMARAK MAHAVIDYALAYA",
      "RAVINDER NATH TAGORE SHIKSHAN SNSTHAN",
      "RAVINDRA & RAJENDRA PG COLLEGE",
      "Ravindra College",
      "Ravindra College of Engineering for Women",
      "Ravindra Degree College For Women",
      "Ravindra Kishore Shahi Government College",
      "Ravindra Nath Tagore Law College",
      "Ravindra Nursing School , Jhunjhunu",
      "Ravindra Polytechnic College",
      "Ravindra Singh Smarak Paramedical Sc & Nsg Inst,Gonda",
      "Ravindra Singh Smarak Paramedical Science And Nsg Inst. , Gonda",
      "Ravindranath Tagore Law College",
      "Ravindranath Tagore School Of Nursing , Bangalore",
      "RAVISHANKAR TEACHER TRAINING INSTITUTE",
      "RAVYUG MAHAVIDYALAYA",
      "Rawal Institute of Management",
      "Rawat College Of Nursing , Jaipur",
      "RAWAT MAHILA TEACHER TRAINING COLLEGE",
      "Rawat Nursing College,Jaipur",
      "Rawttakuppam, Hemerijckx Rural Centre",
      "Rayagada College",
      "Rayalaseema College Of Graduation",
      "Rayalaseema College Of Nursing,Kurnool",
      "Rayalaseema College Of Physical Education",
      "Rayalaseema Degree College, Kurnool",
      "RAYALASEEMA INSTITUTE OF INFORMATION & MGT. SCIENCES",
      "Rayalaseema School Of Nursing , Kurnool",
      "Rayalaseema University",
      "Rayat & Bahra College of Law",
      "Rayat & Bahra Institute Of Engineering & Bio-Technology",
      "Rayat & Bahra Institute of Hotel Management",
      "RAYAT & BAHRA INSTITUTE OF MGT",
      "RAYAT & BAHRA INSTITUTE OF MGT, MOHALI",
      "RAYAT AND BAHRA TEACHER TRAINING COLLEGE",
      "Rayat Bahra Dental College, Mohali",
      "RAYAT BAHRA TEACHER TRAINING COLLEGE",
      "Rayat College of Law",
      "Rayat College of Law",
      "RAYAT COLLEGE OF PHYSICAL EDUCATION",
      "RAYAT INSTITUTE OF ELEMENTARY TEACHERS EDUCATION",
      "Rayat Institute Of Engineering & Technology",
      "RAYAT INSTITUTE OF MANAGEMENT",
      "Rayat Polytechnic College , Nawanshahr",
      "RAYAT SHIKSHAN SANSTHA'S AZAD COLLEGE OF EDUCATION",
      "Rayat Shikshan Sanstha, Satara's. Karmaveer Bhaurao Patil College of Engineering and Polytechnic",
      "RAYAT SHIKSHAN SANSTHA-KARAMVEER BHAURAO PATIL INSTITUTE OF MANAGEMENT STUDIES AND RESEARCH",
      "Rayat Shikshan Sansthans Modern Colege",
      "RAYAT-BAHRA TEACHER TRAINING COLLEGE",
      "Rayatbahra College Of Nursing , Hoshiarpur",
      "Rayatbahra College Of Nursing , Mohali",
      "RBS Institute of Education",
      "RBSS Mahavidyalaya",
      "RC MAHILA VIDHYALAYA",
      "RC Patel B Pharmacy College",
      "RCC Institute of Information Technology, College of Leather Technology",
      "RCM Polytechnic",
      "RCPS INSTITUTE OF EDUCATION",
      "RDS TEACHER TRAINING COLLEGE",
      "REACH, Society for Remedial Education Assessment Counselling Handicapped",
      "REAH SCHOOL OF BUSINESS MANAGEMENT",
      "Reapara Primary Teacher's Training Institute",
      "Rebekah Ann Naylor School Of Nursing , Bangalore",
      "RECETAS SHRI JAGADGURU GURU SIDDHESHWAR T.T.C",
      "Rect Polytechnic College",
      "Red Crescent School Of Nursing, Calicut",
      "Red Cross Nursing Training Centre , Guwahati",
      "Redcrescent College Of Nursing , Kozhikode",
      "REDDY JANA SANGHA INSTITUTE OF MANAGEMENT STUDIES",
      "Redha Krishna Degree College For Women",
      "Redson Womens Degree College",
      "REGENCY COLLEGE OF EDUCATION",
      "Regency Colleges Of Arts And Science",
      "Regency Institute Of Technology",
      "Regency School Of Nursing , Kanpur",
      "REGENCY TEACHERS TRAINING COLLEGE",
      "Regenesys Business School",
      "Regent Educational and Research Foundation",
      "Regional Cancer Centre , Medical College P O , Thiruvananthapuram",
      "Regional Centre AYJNIHH",
      "Regional College",
      "Regional College",
      "Regional College for Education, Research and Technology",
      "Regional College Of Education",
      "Regional College Of Education",
      "Regional College Of Education",
      "Regional College Of Health Science , Nuapada",
      "REGIONAL COLLEGE OF MALWA COLLEGE",
      "Regional College Of Management",
      "Regional College of Management",
      "Regional College of Nursing , Guwahati",
      "Regional College Of Nursing , Kamrup",
      "Regional College of Pharmacy , Jaipur",
      "Regional College Of Physical Education",
      "Regional Dental College , Kamrum",
      "Regional Engineering College",
      "Regional Engineering College",
      "Regional Engineering College",
      "Regional Engineering College",
      "Regional Engineering College",
      "Regional Engineering College",
      "Regional Engineering College Hamirpur",
      "REGIONAL INSITUTE OF MANAGEMENT & TECH",
      "Regional Insitute Of Nursing , Jabalpur",
      "Regional Institute of Co-operative Management",
      "REGIONAL INSTITUTE OF COOPERATIVE MANAGEMENT",
      "Regional Institute Of Education",
      "REGIONAL INSTITUTE OF EDUCATION",
      "REGIONAL INSTITUTE OF EDUCATION",
      "Regional Institute of Education",
      "REGIONAL INSTITUTE OF EDUCATION",
      "REGIONAL INSTITUTE OF ENGLISH",
      "Regional Institute of Medical Sciences",
      "Regional Institute of Medical Sciences",
      "Regional Institute of Medical Sciences, Imphal",
      "REGIONAL INSTITUTE OF MGT",
      "Regional Institute Of Nursing , Jabalpur",
      "Regional Institute Of Nursing And Paramedical Technology , Jorhat",
      "Regional Institute of Para Medical and Nursing RIPAN , Aizawl",
      "Regional Institute of Pharm.Sciences & Technology , Agartala",
      "Regional Institute of Polytechnic",
      "Regional Institute of Polytechnic Studies",
      "Regional Institute of Polytechnic Studies Dhamotar",
      "Regional Institute of Polytechnic, Sardarsahar",
      "Regional Institute of Polytechnic, Vatika",
      "Regional Institute of Printing Technology",
      "Regional Institute of Social Science and Research",
      "REGIONAL INSTT. OF  CO-OPERATIVE MGT",
      "Regional Instt. of Opthalmology",
      "Regional Medical Research Centre (Indian Council of Medical Research)",
      "Regional Nursing School, Jabalpur",
      "Regional Polytechnic College, Kotputli",
      "Regional Public Health Training Nursing Institute , Ujjain",
      "REGIONAL TEACHER TRAINING COLLEGE",
      "Rehabilitation Society of the Visually Impaired",
      "Rehbar Institute Of Medical Sciences , Sangrur",
      "Rekha Devi Memorial Nursing Training Institute,Tonk",
      "REKHA DEVI MEMORIAL TEACHER TRAINING INSTITUTE",
      "REKHA SHIKSHAK PRASHIKSHAN MAHAVIDIDYALAYA",
      "Reliable Institute of Law",
      "RELIABLE INSTITUTE OF MANAGEMENT & TECHNOLOGY",
      "Remedy School Of Nursing , Hyderabad",
      "Renaissance Polytechnic Chandrapur",
      "Renganyagi Varatharaj College Of Engineering",
      "Renu Mahavidyalaya",
      "Renuka Debi B.Ed. College",
      "RENUKA EDUCATION SOCIETY",
      "Renuka Kala Mahavidyalaya",
      "RENUKA MATA KRISHI VIKAS PRATISTHAN",
      "Renuka Primary Teacher's Training Institute",
      "Renuka School Of Nursing,Nagpur",
      "Renukamata KrishiVikas Pratisthan Swami Vivekanand Polytechnic",
      "Repalle Christian College Of Nursing,Guntur",
      "RES Polytechnic",
      "Research Education And Audiological Development Society",
      "RESIDENCY  COLLEGE",
      "Residential College",
      "Residential Women's Polytechnic College,Payyannur",
      "Rev Noorunissa College Of Nursing, Kolar",
      "Rev Noorunissa School Of Nursing, Andersonpet",
      "Rev Noorunnissa Anm Nursing, Kolar",
      "REV NOORUNNISSA COLLEG OF DIPLOMA IN EDUCATION",
      "Rev Noorunnissa College Of Nursing, Kolar",
      "Rev. Jacob Memorial Christian College",
      "REV. JAMES HALE TEACHERS TRAINING INSTITUTE",
      "REV. JOHN THOMAS COLLEGE OF EDUCATION FOR WOMEN",
      "Reva Institute for Engineering and Technology Studies",
      "REVA INSTITUTE OF EDUCATION",
      "REWA COLLEGE OF EDUCATION",
      "Rewa Institute of Technology",
      "Rewa Polytechnic Pharmacy, Rewa",
      "RG Kar Medical College, Calcutta",
      "Rich College Of Nursing, Nellor",
      "Right College Of Nursing, Chennai",
      "Right School Of Nursing, Chennai",
      "Right Value Institute Of Nursing, Nagpur",
      "RIMT TEACHER TRAINING COLLEGE",
      "Rimt- Institute Of Management & Technology",
      "Rimt-Maharaja Agrasen Engineering College",
      "Rimuli College",
      "Rino Simonetti Memorial School Of Nursing, West Garo Hills",
      "RIPU DAMAN SINGH COLLEGE OF EDUCATION",
      "Ripudaman Singh Bisen School Of Nursing, Balaghat",
      "RISE MAX TEACHER TRAINING COLLEGE",
      "RISHABH INSTITUTE",
      "Rishi Bankim Chandra College",
      "Rishi Bankim Chandra College For Women",
      "Rishi Bankim Chandra Evening College",
      "Rishi Degree College",
      "Rishi Galav Degree College",
      "RISHI GALAV TEACHER TRAINING COLLEGE",
      "RISHI GALAV TEACHER TRAINING COLLEGE",
      "RISHI GALAV TEACHERS TRAINING COLLEGE",
      "Rishi Raj College of Dental Sciences & Research Centre , Bhopal",
      "RISHI RAM NARESH KRISHAK DEGREE COLLEGE",
      "Rishi Ram Naresh Krishak Mahavidyalaya",
      "Rishi Ubr Pg College For Women",
      "RISHIKUL GROUP OF B.ED. COLLEGE",
      "Rishiraj Institute of Technology",
      "Rishishwar Mhavidyalaya",
      "Rishra Seva Sadan Gnm School Of Nursing , Hooghly",
      "Rishra Seva Sadan, A N M Training School , Hoogly",
      "RITURAJ DEGREE COLLEGE",
      "Riward Mahavidyalaya",
      "RIZVI COLLEGE OF EDUCATION",
      "Rizvi College of Hotel Management, Mumbai",
      "Rizvi Education Society's Rizvi College of Engineering",
      "RIZVI EDUCATION SOCIETY-RIZVI INSTITUTE OF MANAGEMENT STUDIES & RESEARCH",
      "Rizvi Education Societys Rizvi College Of Arts Science & Commerce",
      "Rizvi Institute of Management Studies and Research",
      "Rizvi Law College",
      "RJ School of Management Studies",
      "RJS Institute Of Management Studies",
      "RK Institute of Engg & Technology",
      "RK Saha Women's College",
      "RKDF College of Engineering",
      "RKDF Dental College & Research Centre , Bhopal",
      "Rkdf Institute Of Hotel Management",
      "RKDF Institute Of Technology",
      "RKDF Polytechnic Pharmacy , Bhopal",
      "RKDF School Of Engineering - Engineering",
      "RKDF University",
      "RKG EDUCATIONAL COLLEGE",
      "RKKR School of Management Studies",
      "RKPET D.ED COLLEGE",
      "RKSD College of Pharmacy",
      "RML College of Pharmacy , Belgaum",
      "RMRS PG College",
      "RMS Polytechnic",
      "RN Modi Engineering College",
      "RNMM Law College",
      "RNS Institute of Pharmacy , Gwalior",
      "RNS Institute Of Technology",
      "RNT INSTITUTE OF BSTC",
      "ROBERT LOUIS INSTITUTE OF TECH",
      "ROCK VALLEY TEACHERS COLLEGE",
      "Roda Mistry College Of Social Work Research Centre",
      "Rode Polytechnic",
      "Roever College of Engineering and Technology",
      "Roever Engineering College",
      "ROHIDAS PATIL INSTITUTE OF MANAGEMENT STUDIES",
      "Rohilkhand College Of Nursing,Bareilly",
      "Rohilkhand Medical College & Hospital, Bareilly",
      "Rohilkhand School Of Nursing, Bareilly",
      "Rohilkhand School Of Nursing,Bareilly",
      "Rohini College of Engineering & Technology",
      "Rohini College Of Nursing,Warangal",
      "Rohini School Of Nursing , Hanumakonda",
      "Rohit Memorial Degree College",
      "ROHIT MEMORIAL INSTITUTE OF EDUCATION",
      "Rohtas Mahavidyalaya",
      "Rohtas Mahila College",
      "Roland Institute of Pharm Sciences , Berhampur",
      "Roland Institute Of Technology",
      "RONALD ROSS PG COLLEGE",
      "Roohi College Of Nursing, Bangalore",
      "Roohi College Of Nursing,Bangalore",
      "Roohi School Of Nursing , Bangalore",
      "Roohi School Of Nursing , Gulbarga",
      "ROOKWOOD BUSINESS SCHOOL",
      "Roop Rajat School Of Nursing,Ajmer",
      "ROOP RANI SUKHANANDAN SINGH COLLEGE",
      "Roorkee College of Pharmacy , Roorkee",
      "Roorkee College of Polytechnic",
      "ROORKEE DEGREE COLLEGE",
      "Roorkee Degree College of Law",
      "Roorkee Institute of Technology",
      "Ropar School Of Nursing , Ropar",
      "ROSA MISTICA TEACHER TRAINING INSTITUTE",
      "Rosalind S Teton School Of Nursing, Marg,",
      "ROSAMMAL TEACHER TRAINING INSTITUTION FOR WOMEN",
      "Rosary College Commerce And Arts",
      "ROSE DALE TEACHER TRAINING INSTITUTE",
      "Rose Mary Arts And Science College",
      "ROSE TEACHERS TRAINING COLLEGE",
      "ROSELINE TEACHER TRAINING COLLEGE",
      "ROSHAN LAL INSTITUTE OF SCIENCE & TECHNOLOGY",
      "Roshan Lal Institute of Science & Technoloogy",
      "ROSHANLAL DAIPURIA MAHAVIDYALAYA",
      "Rotary School Of Nursing, Chennai",
      "Rourkela College of Educational Training",
      "Rourkela Institute Of Managment Studies",
      "Rourkela Institute of Managment Studies",
      "Rourkela Institute of Technology",
      "Rourkela Institute of Technology",
      "Rourkela Law College",
      "ROUSSEAU INSTITUTE OF MANAGEMENT STUDIES",
      "Rouzathul Uloom Arabic College",
      "Royal Academy Of Law",
      "Royal Academy of Law",
      "ROYAL COLLEGE OF B.ED",
      "ROYAL COLLEGE OF EDUCATION",
      "ROYAL COLLEGE OF EDUCATION",
      "ROYAL COLLEGE OF EDUCATION",
      "ROYAL COLLEGE OF EDUCATION",
      "Royal College of Engineering",
      "Royal College of Engineering & Technology Kerala",
      "Royal College of Law,",
      "Royal College Of Nursing , Bangalore",
      "Royal College Of Nursing , Coimbatore",
      "Royal College Of Nursing,East Godavari",
      "Royal College of Pharmacy & Paramedical Sciences , Madukkarai",
      "Royal College of Pharmacy &Health Sciences , Berhampur",
      "Royal College of Pharmacy , Raipur",
      "Royal College of Technology",
      "ROYAL D ED COLLEGE",
      "Royal Degree College, Medak",
      "Royal Dental College , Palakkad",
      "ROYAL EDUCATION INSTITUTE",
      "ROYAL EDUCATIONAL INSTITUTE",
      "Royal Institute of Management & Technology",
      "Royal Institute of Management and Advanced Studies",
      "Royal Institute Of Nursing , Gurdaspur",
      "ROYAL INSTITUTE OF SCIENCE AND MANAGEMENT",
      "Royal Institute of Technology & Science",
      "Royal Pg Center",
      "Royal Polytechnic",
      "Royal Polytechnic College",
      "ROYAL PRUDENCE DEGREE COLLEGE",
      "ROYAL SCHOOL OF INFORMATION & MANAGEMENT SCIENCE",
      "Royal School Of Nursing , Bangalore",
      "Royal School Of Nursing , Bhadrak",
      "Royal School Of Nursing , Imphal",
      "Royal School Of Nursing, , Coimbatore",
      "Royal School Of Nursing,Kollam",
      "Royal Seema Seva Samiti",
      "ROYAL TEACHER TRAINING INSTITUTE",
      "ROYAL TEACHER TRAINING INSTITUTE",
      "ROYAL TEACHER TRAINING INSTITUTE",
      "ROYAL TEACHER TRAINING INSTITUTE FOR WOMEN",
      "ROYAL TEACHERS TRAINING INSTITUTE",
      "Royale Business School",
      "ROYALE CONCORDE TEACHER TRAINING INSTITUTE",
      "RP Sharma Institute of Technology",
      "RR Institute of Technology",
      "RRASE college of Engineering College",
      "RRS College of Engineering and Technology, Patancheru",
      "RRSCollege of Engineering and Technology",
      "RS College Of Management",
      "RSMHI Teacher Training Institute",
      "RSR Rungta College of Engineering and Technology",
      "RSS DEGREE COLLEGE",
      "Rte Societys Rural Engineering College",
      "Rte Societys Rural Engineering College",
      "Rubber Technology Centre",
      "RUBEN COLLEGE OF EDUCATION",
      "RUBY COLLEGE OF PRECEPTORS",
      "Ruby General Hospital Ltd , Kolkata",
      "Ruchi's Institute of Creative Arts (POLYTECHNIC)",
      "Ruckmoni College Of Nursing , Trivandurm",
      "Rudhraveni Muthuswamy Polytechnic College",
      "RUDRA INSTITUTE OF TECHNOLOGY",
      "Rudragonda Patil Government First Grade College",
      "RUDRAKSH INSTITUTE OF EDUCATION & TECHNOLOGY",
      "Rudraveni Muthuswamy Polytechnic College",
      "Rufaida College of Nursing , Delhi",
      "Rufaida School Of Nursing , Delhi",
      "Ruhi Nursing College Of Nursing , Bhilwara",
      "RUKMANI COLLEGE OF EDUCATION",
      "Rukmani Devi Institute of Science and Technology",
      "RUKMANI DEVI TEACHER TRAINING COLLEGE",
      "RUKMANI MAHAVIDYALAYA",
      "RUKMINI DEVI  INSTITUTE OF  ADVANCED STUDIES",
      "Rukmini Devi Chilika Mahavidyalaya",
      "Rukmini Devi Institute Technology",
      "Rukmini Shanmugam Polytechnic College",
      "Rukmini Shanmugam Polytechnic College",
      "RUKMINI SHIKSHAN SHASTRA MAHAVIDYALAYA",
      "Ruman School Of Nursing , Bangalore",
      "Rungta College of Dental Sciences & Research , Durg",
      "Rungta College of Engineering and Technology, Rungta",
      "Rupahi College Nagaon",
      "RURAL B.ED COLLEGE",
      "RURAL B.ED COLLEGE",
      "Rural College Education",
      "Rural College Of Engineering & Technology",
      "Rural College of Pharmacy , DEVANAHALLI",
      "Rural Dental College , Ahmednagar",
      "Rural Developments Society's Bachelor of Social Work College",
      "Rural Engineering College",
      "RURAL FOUNDATION",
      "Rural Health Training Centre , Najafgarh",
      "Rural India Medical and Relief Society (RIMRS), Institute for the Mentally Handicapped",
      "Rural Medical College, Loni",
      "Rural Nursing Training Institute , Sonipat",
      "Rural Polytechnic For Women",
      "Rural Polytechnic, Hulkoti",
      "Rural Research Institute For Health , Education, Jaipur",
      "RURAL TEACHERS TRAINING CENTRE",
      "Rustamji Institute of Technology",
      "Rutviks College",
      "Ruxmaniben Deepchand Gardi Medical College, Ujjain",
      "RV Industrial Training",
      "RVR & JC College of Engineering",
      "RVR Institute of Engineering and Technology",
      "RVS College of Computer Application",
      "RVS College Of Engineering and Technology Coimbatore",
      "RVS College Of Engineering and Technology,",
      "RVS Institute of Management Studies",
      "RVS Institute of Management Studies and Computer Applications",
      "RVS KVK Institute of Management Studies",
      "RVS KVK School of Architecture",
      "RVS Padmavathy School of Architecture",
      "RVS Polytechnic College",
      "RVS Technical Campus Coimbatore",
      "RYAN TEACHER TRAINING COLLEGE AND TECHNOLOGY CENTER",
    ],
  },
];
